### ISSUE TITLE
Batched rotation of packed point cloud?

### ISSUE THREAD

**Issue by davezdeng8** [facebookresearch/pytorch3d#1001]
Hi,

How can I perform a batched rotation of a batch of point clouds of varying sizes?

i.e. I have a length N 3d rotation transform and a batch size N of point clouds in the packed representation. How can I apply each rotation to its corresponding point cloud in the batch in one operation?

Thanks!

**Comment by bottler** [comment]
When you say "in the packed representation", I think you mean you just have the points in a tensor of shape (sum(n), 3), and you are trying to avoid the Pointclouds object. If so, there's no single operation. What is the real constraint you are facing?

**Comment by nikhilaravi** [comment]
@davezdeng8 do you still need help with this issue?

**Comment by davezdeng8** [comment]
Whoops sorry, basically I ended up converting between packed and padded representations for this, and I found the update_padded point cloud method very helpful. Thanks!

**Comment by brbr1** [comment]
Hello, 
I want to have a batch (to work with it to train my model) of pointclouds that have not the same size. could you please give me an example of this.

Thanks in advance.

**Comment by bottler** [comment]
Please open a new issue for a question! Batches of point clouds with different numbers of points in each is a normal use of the PointClouds object. Take a look at its docstring. You'll need to initialize it with a list.
