### ISSUE TITLE
Is the Chamfer Distance Here Bidirectional or Only One Direction?

### ISSUE THREAD

**Issue by ardianumam** [facebookresearch/pytorch3d#1002]
Hi!

As written in the title, for the Chamfer distance implemented here, is it bidirectional or one direction? 
Bidirectional --> `chamfer_disc(source, taget) == chamfer_dist(target, source)`
One direcetion --> `chamfer_disc(source, taget) := forward distance from source to target != chamfer_dist(target, source)`

Many thanks.

**Comment by patricklabatut** [comment]
It's the symmetrized version, see the source code: [[1]](https://github.com/facebookresearch/pytorch3d/blob/main/pytorch3d/loss/chamfer.py#L216) [[2]](https://github.com/facebookresearch/pytorch3d/blob/main/pytorch3d/loss/chamfer.py#L152-L153).
