### ISSUE TITLE
How to specify the lights intensity?

### ISSUE THREAD

**Issue by Yougrianes** [facebookresearch/pytorch3d#1005]
I couldn't find any arguments in class PointLights, it just has some arguments with lights and locations.
Can anybody help me? :-<

**Comment by bottler** [comment]
The intensity is the magnitudes in `ambient_color`, `diffuse_color` and `specular_color` [here](https://github.com/facebookresearch/pytorch3d/blob/main/pytorch3d/renderer/lighting.py#L223).

**Comment by Yougrianes** [comment]
> The intensity is the magnitudes in `ambient_color`, `diffuse_color` and `specular_color` [here](https://github.com/facebookresearch/pytorch3d/blob/main/pytorch3d/renderer/lighting.py#L223).

I got it. So what I need to do is specify a 3-dimension tuple of shape (1, 3) and it means the RGB value. Thanks!
