### ISSUE TITLE
How to get the intrinsic matrix of `FoVPerspectiveCameras`?

### ISSUE THREAD

**Issue by zeakey** [facebookresearch/pytorch3d#1014]
## ❓ How to get the intrinsic matrix of `FoVPerspectiveCameras`

I wanna compute the projected 2d coodinates of 3d vertices using the `FoVPerspectiveCameras` camera model.

However, there comes several problems about the concepts and implementation in PyTorch3d.

### Question 1

According to the [doc](https://pytorch3d.readthedocs.io/en/latest/notes/cameras.html):

> Cameras in PyTorch3D transform an object/scene from world to view by first transforming the object/scene to view (via transforms R and T) and then projecting the 3D object/scene to a normalized space via the projection matrix P = K[R | T], where K is the intrinsic matrix. 

The projection matrix is computed using R, T and intrinsic matrix K.

However, the implementation of `compute_projection_matrix` 
<https://github.com/facebookresearch/pytorch3d/blob/d67662d13ce497e746196f68cfd90b61954fea23/pytorch3d/renderer/cameras.py#L545-L595> 
DOES NOT use `R` and `T` at all.

### Question 2

Besides, in my understanding, the projection matrix `P =  K[R | T]` (according to the doc mentioned above) should be a
(N, 3, 4) matrix since K is a (3, 3) matrix and [R | T] is a (3, 4) matrix.
However, the `compute_projection_matrix` function returns a (N, 4, 4) matrix.

### Question 3

Additionally, the function name (and also the doc menetioned above) tells me that it returns the 'projection matrix',
however, in the inline docstring, the return of the function is described as a 'calibration matrix':

> Returns:
>             torch.FloatTensor of the calibration matrix with shape (N, 4, 4)

whichreally makes people like me confuse.

**Comment by bottler** [comment]
The sentence you quote in Question 1 is slightly hard to read out of context. All this code and documentation is following one of the standard conventions, and isn't trying to be a textbook. Another way to learn might be to debug and print out intermediate values.

K and P are both 4x4 matrices and projective coordinates are in use. The symbol `[R | T]` really means R and T with the extra row `[0,0,0,1]` appended at the bottom.

The name "projection matrix" needs to be interpreted in context. "calibration matrix" and "intrinsic matrix" sound like the same thing - the `K`.

**Comment by cgmcvey** [comment]
Feel like this post should be revisited and taken seriously. This documentation is deeply confusing to anyone that properly understands photogrammetry, as it completely contradicts the conventions established in Hartley and Zisserman. I am also struggling to understand how K returned by compute_projection_matrix is 4x4 in pytorch3d, when it should be 3x3, and how it an be converted to 3x3 so that I can utilize standard OpenCV utilities.
