### ISSUE TITLE
find a bug in pytorch3d/structures/pointclouds.py

### ISSUE THREAD

**Issue by vicdxxx** [facebookresearch/pytorch3d#1015]
master branch
line 895 will occur error if not add .long() before
![image](https://user-images.githubusercontent.com/14140837/148043394-f60a69c1-684d-4116-8472-0ffb9fced884.png)

**Comment by bottler** [comment]
This function works for me because `keep_np` will be int64, but that is on linux. This is a problem on Windows, right?

**Comment by vicdxxx** [comment]
> This function works for me because `keep_np` will be int64, but that is on linux. This is a problem on Windows, right?

Yes, I found you guys already fix this bug in new updates
