### ISSUE TITLE
Artifacts over the diagonal edge when rendering a simple square

### ISSUE THREAD

**Issue by Peter-Kocsis** [facebookresearch/pytorch3d#1026]
Hi, first of all thanks a lot for the great repo, it's really well structured and easy to use! During my project, I came across some strange artifacts during rendering and I was able to simplify the code to reproduce it easily. 

## 🐛 Bugs / Unexpected behaviors

When rendering a simple square, some pixels over the diagonal edge of the triangle faces seems to become transparent. I tried different rasterization settings, but nothing helped. 

### Code [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1MG1RIy6aZAjg_2hbX1cA89ieVwQR3ZeZ?usp=sharing)

```python
import torch
from pytorch3d.renderer import TexturesVertex, look_at_view_transform, FoVPerspectiveCameras, PointLights, \
    RasterizationSettings, MeshRenderer, MeshRasterizer, SoftPhongShader
from pytorch3d.structures import Meshes
import matplotlib.pyplot as plt

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

y_plane_mesh = Meshes(
    verts=[torch.tensor([
        [-1., 0., -1.],
        [-1., 0.,  1.],
        [ 1., 0.,  1.],
        [ 1., 0., -1.],
    ], device=device)],
    faces=[torch.tensor([
        [0, 1, 2],
        [2, 3, 0],
    ], device=device)],
)
y_plane_mesh.textures = TexturesVertex(
    verts_features=torch.ones_like(y_plane_mesh.verts_padded(), device=device)
)

R, T = look_at_view_transform(dist=2, elev=90, azim=0)
cameras = FoVPerspectiveCameras(device=device, R=R, T=T)

raster_settings = RasterizationSettings(
    image_size=512,
    blur_radius=0.0,
    faces_per_pixel=1,
)

lights = PointLights(device=device, location=[[0.0, 10.0, 0.0]])

renderer = MeshRenderer(
    rasterizer=MeshRasterizer(
        cameras=cameras,
        raster_settings=raster_settings,
    ),
    shader=SoftPhongShader(
        device=device,
        cameras=cameras,
        lights=lights
    )
)

images = renderer(y_plane_mesh)
plt.figure(figsize=(10, 10))
plt.imshow(images[0, ..., :3].cpu().numpy())
plt.axis("off");
plt.show()
```

### Result

![DiagonalArtifacts](https://user-images.githubusercontent.com/31744529/148570902-31ae798d-a276-4e6c-a948-2b6c6527be34.png)

**Comment by gkioxari** [comment]
This is because of edge cases. The edges of the mesh faces are likely perfectly aligned with the pixels. If you set the blur radius to something small, e.g. `blur_radius=0.00001` you get the desired outcome and that is because the edges of the mesh get smoothen'ed out (is that even a verb? oh well!). 

![image_issue](https://user-images.githubusercontent.com/4369065/148665795-375af98a-1e78-4d39-b3d4-19739b435059.png)

**Comment by Peter-Kocsis** [comment]
I see, thanks a lot for the quick help and explanation!

**Comment by DerekGrant** [comment]
> This is because of edge cases. The edges of the mesh faces are likely perfectly aligned with the pixels. If you set the blur radius to something small, e.g. `blur_radius=0.00001` you get the desired outcome and that is because the edges of the mesh get smoothen'ed out (is that even a verb? oh well!).
> 
> ![image_issue](https://user-images.githubusercontent.com/4369065/148665795-375af98a-1e78-4d39-b3d4-19739b435059.png)

Thanks a lot, it solved my problem!
