### ISSUE TITLE
Voxel rendering with transformed/custom rays

### ISSUE THREAD

**Issue by robot0321** [facebookresearch/pytorch3d#1030]
## ❓ Questions on how to render a voxel with curved/transformed rays

Hi pytorch3d representative,
At first, thanks for the great packages!

I'd like to render an image from a **voxel** following curved rays (not straight rays)
Now **I have** a point-transform function as below.
![output](https://user-images.githubusercontent.com/11347296/148740286-88525fbc-71aa-4851-aee4-2d2232a7dae5.png)
Note that black rays are normal rays from camera and green dots are transformed one. (magenta lines shows their correspondence)

**Here, my question is :** 
Is there any way to manipulate the custom Ray (or sampling points) to render a voxel in Pytorch3D? 
Any glitch or niche is also fine. :+1: 
If you instruct any guide about the custom voxel rendering, I can try to modify it personally except the CUDA language.

Thank you for your time!

**Comment by bottler** [comment]
This is not supported. By studying the current code, which is designed for straight rays, you may be able to adapt it to other rays.
