### ISSUE TITLE
Installation example seems to be wrong but still working

### ISSUE THREAD

**Issue by themataleao** [facebookresearch/pytorch3d#1031]
According to your install.md the installation through wheels example looks like that:

We have prebuilt wheels with CUDA for Linux for PyTorch 1.10.0, for each of the CUDA versions that they support, for Python 3.7, 3.8 and 3.9. These are installed in a special way. For example, to install for Python **3.8**, PyTorch **1.9.0** and CUDA **10.2**

```bash
pip install pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py38_cu102_pyt1100/download.html
```
Am I wrong the given expression will install:

Python 3.8
CUDA 10.2
Pytorch **1.10.0** and not PyTorch 1.9.0

Am I right that it does not install PyTorch 1.9.0?

My installation script still works even if I installed PyTorch 1.9 so I am a bit confused. Please clarify.

Thanks in advance.

**Comment by bottler** [comment]
Yes, you are right. There's a mistake there in INSTALL.md. That command will be for PyTorch 1.10.0.

When installing the wheels from fbaipublicfiles you have to install the dependencies first, and ask for the right wheel. Otherwise installation may succeed but things will just not work.

**Comment by bottler** [comment]
And in fact we don't have Linux wheels for PyTorch 1.9.0 now. It is just 1.10.0 and 1.10.1. The main binaries for PyTorch3D are via conda, where it is much easier to get the right versions.

**Comment by themataleao** [comment]
Okay thanks for the answer. I am currently trying to install it in a docker environment and am struggling quite heavily with the dependencies :) However the wheels worked really smoothly.
