### ISSUE TITLE
how get normal specular?

### ISSUE THREAD

**Issue by haoxurt** [facebookresearch/pytorch3d#1037]
I want get specular at mouth and eye. However, when I set a render as following policy, I got abnormal specular between the eyebrows.I save the left image from the function '_apply_lighting' in renderer/mesh/shading.py.
materials = Materials(device=device,
            ambient_color=((1, 1, 1),),
            diffuse_color=((1, 1, 1),),
            specular_color=((1, 1, 1),),
            shininess=64,
        )
        lights = PointLights(device=device,
            location=[[0.0, 0.0, 2.0]],
            ambient_color=((0.7, 0.7, 0.7),),
            diffuse_color=((0.3, 0.3, 0.3),),
            specular_color=((0.7, 0.7, 0.7),),
        )
![image](https://user-images.githubusercontent.com/43776429/149307183-7372436a-f0ce-45e7-aa35-c6a01fb654cb.png)

**Comment by bottler** [comment]
What do you mean by "abnormal"? Why do you not expect a specular highlight between the eyebrows? The light looks to be coming from the same direction as the camera - straight in front of the face. Is that intended?

**Comment by haoxurt** [comment]
I means how to displace specular data with a uvmap in the class Materials or in the class Lights ?
![image](https://user-images.githubusercontent.com/43776429/149344128-b423deab-69f7-49d5-8282-e721ff548a4c.png)
