### ISSUE TITLE
How does Pytorch3D use normal from OBJ file to render?

### ISSUE THREAD

**Issue by NengQian** [facebookresearch/pytorch3d#104]
From the tutorial, I think pytorch3d can calculate the normal information for each vertex by itself. 
But how about if I want to use the normal information from Obj file to render? Is it possible in Pytorch 3D currently?

Seems like the meshes class does not accept normal as input?

**Comment by nikhilaravi** [comment]
@NengQian the `load_obj` function does support reading the normals from an `.obj` file but we do not support using the normals from an obj file within `Meshes`. For the lighting/shading modules in the rendering pipeline, we use methods on `Meshes` which calculate the vertex/face normals based on the vertices.

What is the use case for which you need to render an object with normals from a file? 

For context, in PyTorch3D we aim to support use cases where the mesh might be optimized e.g. the positions of the vertices are being updated on each iteration of an optimization/training loop. In this case the normals would also change on each iteration so it would be necessary to recompute them in order for them to be correct (or also optimize the normals themselves).

**Comment by NengQian** [comment]
Yes, you are right. Since the mesh will deform during the optimization, the normal information will anyway also change during optimization.
The issue is, our obj file contains some duplicated vertices, which contains the same 3D position but with different texture UV coordinator due to we are using a texture atlas.
And these duplicated vertices do not have complete neighbor faces,  therefore normal information computed by Pytorch3d will not be consistent at these vertices even though they are at the same position.
This leads to, when we try to have some shading effect on our mesh, there will ba seam on the rendering result, since the normal information on these vertices are not consistent.
It is, first ugly, then may also affect our optimization result.
**So are there any solution in pytorch3d which can help these mesh with duplicated vertices?**

**Comment by wangsen1312** [comment]
@NengQian You may need use Meshlab to remove duplicate faces and vertices first. Meshlab can offer command line to do it.

**Comment by NengQian** [comment]
@wangsen1312 Thanks for you help. The duplicated vertice are manually duplicated by me to make it renderable in OpenGL. 
@nikhilaravi A quick and short question, does Pytorch3d allow one vertex has more than one UV coordinate?

**Comment by nikhilaravi** [comment]
@NengQian yes this is possible. When specifying the [textures](https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/structures/textures.py#L93-L95) you need to have two tensors:
- `verts_uvs` of shape (N, V, 2) where V does not have to be the same as the number of vertices in the vertices tensor. 
- `faces_uvs` of shape (N, F, 3) where F has to be the same as the number of faces in the mesh faces tensor.

So long as the indices in the `faces_uvs` index correctly in `verts_uvs` then the texture interpolation will work correctly providing you have one texture image per mesh in the batch that you also provide. 

From the comment above  - you mention you're using. texture atlas?  Do you mean a `(T x T)` texture per face in the mesh?

**Comment by NengQian** [comment]
@nikhilaravi Great, thank you. This already solves the issue.

> From the comment above - you mention you're using. texture atlas? Do you mean a (T x T) texture per face in the mesh?
Yes, this is the reason why I duplicate the vertex. Since in this atlas setting, each vertex on mesh will have more than one uv coordinate.
