### ISSUE TITLE
Why nobody answers PyTorch3D questons on PyTorch community? 

### ISSUE THREAD

**Issue by hopezh** [facebookresearch/pytorch3d#1041]
I found most of the questions related to PyTroch3D, based on [a simple keyword search on the PyTorch community](https://discuss.pytorch.org/search?q=pytorch3d) were not answered by any developers of PyTorch3D. 

How do you expect the users community of PyTorch3D to grow if no help can be found except the meager official documents which are poorly prepared?  

I hope the developers and contributors of PyTorch3D can dedicate sometime to help the users.

**Comment by bottler** [comment]
Thank you for pointing those out. I had no idea. There are about 20 of them. We can have a look. Many more questions than that have been asked here as issues, which is the proper way to ask questions of us, and we are usually quite responsive. We are not trying to hide!

Can you give specific examples of things in the documentation which you find "poorly prepared" or ways things could be better documented?

**Comment by gkioxari** [comment]
@hopezh 
We have extensive documentation and support for PyTorch3D. 

* Tutorials for getting hands-on experience: https://github.com/facebookresearch/pytorch3d/tree/main/docs/tutorials
* Notes which explain some of the key operators (such as IO, renders, etc.): https://github.com/facebookresearch/pytorch3d/tree/main/docs/notes
* Our code is extensively documented 
* We are extremely active on addressing GH issues and we have a lively GH Discussion page where users discuss various aspects and applications of the library

 If you run into issues with PyTorch3D, please open an issue on GH
