### ISSUE TITLE
How to use Pytorch3D for projection of vertices point cloud exported from Unity

### ISSUE THREAD

**Issue by ShuoZheLi** [facebookresearch/pytorch3d#1042]
Currently, I export object vertices from Unity and try to project the point cloud of it following the official example "https://pytorch3d.org/tutorials/render_colored_points". However, it seems I am having an issue with adjusting the camera position and angle. 

To verify that I am using the right vertices data, I displayed it on pyplot:
![image](https://user-images.githubusercontent.com/37442704/149550146-e031e3f1-6b5a-4057-aed8-dd09fd79bf1a.png)

However, I get something like this with the following setup code, it seems that the camera is too close to the object. I tried to change distance, but it does not really work:
![image](https://user-images.githubusercontent.com/37442704/149550702-2c81d3e9-2925-4c09-adb0-3c5bc2446355.png)

`
verts = torch.Tensor(pc).to(device)
rgb = torch.Tensor(np.zeros((47466, 4))).to(device)
point_cloud = Pointclouds(points=[verts], features=[rgb])

R, T = look_at_view_transform(10, 300, 360)
raster_settings = PointsRasterizationSettings(
    image_size=512,
    radius = 0.009,
    points_per_pixel = 10
)
cameras = FoVOrthographicCameras(device=device, R=R, T=T, znear=0.3, zfar=1000)
rasterizer = PointsRasterizer(cameras=cameras, raster_settings=raster_settings)
renderer = PointsRenderer(
    rasterizer=rasterizer,
    compositor=AlphaCompositor(background_color=(1, 1, 1))
)
images = renderer(point_cloud)
plt.figure(figsize=(5, 5))
plt.imshow(images[0, ..., :3].cpu().numpy())
plt.axis("off");
`

This is what we want to achieve:
![image](https://user-images.githubusercontent.com/37442704/149551940-2600f7c3-0368-4437-9b1d-7c87245c5738.png)

Could someone please give me some suggestions on how to change the camera position and angle?
Or is there any silly mistake in my code?

Here is the zipped npz file, if you want to give it a try!
[NPZ_file.zip](https://github.com/facebookresearch/pytorch3d/files/7872092/NPZ_file.zip)

Thank You So Much!!

**Comment by ShuoZheLi** [comment]
[data.zip](https://github.com/facebookresearch/pytorch3d/files/7872015/data.zip)
Here is the zipped npz file if you want to give it a try.
Thank You !!

**Comment by nikhilaravi** [comment]
@ShuoZheLi firstly the z values which are < 0 will be clipped by the rasterizer so you should shift your pointcloud so that it has all z values > 0. 

Can you try using `FoVPerspectiveCameras` instead of `FoVOrthographicCameras`?
