### ISSUE TITLE
What is maximum values of fragments.zbuf

### ISSUE THREAD

**Issue by icedpanda** [facebookresearch/pytorch3d#1047]
I'm using pytorch3d and specifically the output of `fragments.zbuf` (object depth) as additional features for my classification model.

I wonder about the maximum values of `fragments.zbuf` (N, image_size, image_size, faces_per_pixel) as I wanted to normalize the depth to the range of [0,1]. I know the minimum value is -1, but I couldn't find any documentation regarding the maximum. 

We can easily normalize image values to [0,1] as we know RGB values are range from [0, 255]. How can I achieve this while using `fragments.zbuf` especially the depth here.

Here's my sample code for Renderer

```python
        blend_params = BlendParams(
            sigma=1e-4,
            gamma=1e-4,
            background_color=(
                0,
                0,
                0))
        raster_settings = RasterizationSettings(
            image_size=self.input_res,
            blur_radius=0,
            faces_per_pixel=1,
            max_faces_per_bin=1000000,
        )

        # renderer
        # cameras = SfMPerspectiveCameras(
        #     focal_length=self.fl, R=self.ptR.expand(
        #         opt.batch_size, -1, -1), device='cuda')
        cameras = PerspectiveCameras(
            focal_length=self.fl, R=self.ptR.expand(
                opt.batch_size, -1, -1), device='cuda')
        rasterizer = MeshRasterizer(raster_settings=raster_settings)
        shader_rgb = HardFlatShader(blend_params=blend_params)

        self.renderer = Renderer(
            rasterizer,
            shader_rgb,
            SoftSilhouetteShader(),
            cameras)
```

Thanks

**Comment by icedpanda** [comment]
@gkioxari so the max depth `z` here from `fragments.zbuf` would depend on input data right?

**Comment by nikhilaravi** [comment]
@icedpanda yes exactly -- the maximum and minimum values are dependent on the input data. 

>> the minimum value is -1

This is incorrect -- the -1 represents padded values. You should use `torch.min(fragments.zbuf[fragments.pix_to_face > 0]) to find the min value`.

**Comment by icedpanda** [comment]
thanks
