### ISSUE TITLE
Background Color Support for RGB Point Clouds

### ISSUE THREAD

**Issue by jasonyzhang** [facebookresearch/pytorch3d#1048]
## 🚀 Feature

Hi,

The AlphaCompositor and NormWeightedCompositor currently only apply the background color if the point cloud is RGBA rather than RGB. However, the `_add_background_color_to_images` actually works fine whether the pointcloud is RGB or RGBA.

The current code does not apply the background color for RGB point clouds, explicitly checking for an alpha channel:

https://github.com/facebookresearch/pytorch3d/blob/9e2bc3a17faf7dfffad9b0803f335da328b08a61/pytorch3d/renderer/points/compositor.py#L37-L39

https://github.com/facebookresearch/pytorch3d/blob/9e2bc3a17faf7dfffad9b0803f335da328b08a61/pytorch3d/renderer/points/compositor.py#L59-L61

Is there a specific rationale for this? I have tested setting `images.shape[1] == 4` to `images.shape[1] in (3, 4)`, and the output is as expected.

Thanks in advance!

**Comment by nikhilaravi** [comment]
Thanks for pointing this out! We will update this function to work for both RGB and RGBA.
