### ISSUE TITLE
How can I apply learnable light when using TexturesUV

### ISSUE THREAD

**Issue by rainsoulsrx** [facebookresearch/pytorch3d#1049]
Hi, I want to use learnable Spherical Harmonic Lighting when rending with TexturesUV. Is there a demo? Thanks a lot!

**Comment by bottler** [comment]
We don't have an implementation of spherical harmonic lighting, even as a demo.

**Comment by nikhilaravi** [comment]
You can have learnable lights using the [light options](https://github.com/facebookresearch/pytorch3d/blob/main/pytorch3d/renderer/lighting.py) we support now, but we don't have support for Spherical Harmonics.
