### ISSUE TITLE
Please implement pytorch3D in Anaconda

### ISSUE THREAD

**Issue by jamalknight** [facebookresearch/pytorch3d#105]
When trying to set up in Anaconda, this code does not seem to work.

I believe this is a known issue, just putting it out there as another request.

Thanks

**Comment by bottler** [comment]
Can you explain in more detail? Pytorch3d likes anaconda. The easiest way to use pytorch3d *is* in anaconda on Linux. Can you describe what you have tried and what system you are using. 

If you mean the Python 2.7 version of anaconda, then that will never work with Pytorch3d.

If you mean anaconda on Windows, then this works but requires building pytorch3d yourself. 
We plan to make prebuilt packages available soon for Windows.

**Comment by jamalknight** [comment]
Hi there

Here are some details:

Installing on Anaconda on Linux

**My steps:**

**Create anaconda env:**
-conda create --name Mesh_RCNN_v04 python=3.6


**Install Detectron2 Dependencies** 
Conda install -c pytorch torchvision 
Conda install -c anaconda cython 
Conda install -c anaconda pyyaml
Conda install -c conda-forge opencv 
 pip install 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'

Everything above works ok, but the next step 'Build detectron2 from source' fails:
pip install 'git+https://github.com/facebookresearch/detectron2.git'

**Error message:**
(really long, but the last paragraph was this:

error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/13787650/anaconda3/envs/Mesh_RCNN_v07/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-yb75ru2t/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-yb75ru2t/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-90lrbp3a/install-record.txt --single-version-externally-managed --compile --install-headers /home/13787650/anaconda3/envs/Mesh_RCNN_v07/include/python3.6m/detectron2 Check the logs for full command output.

**Comment by gkioxari** [comment]
Hi @jamalknight 
We haven't heard from you regarding this issue. PyTorch3D and anaconda are good friends. If you find that there is a problem, please re-open this issue.
