### ISSUE TITLE
Convert world coordinates to screen, then back again.

### ISSUE THREAD

**Issue by nashapir** [facebookresearch/pytorch3d#1056]
## ❓ Questions on how to use PyTorch3D

Hello!

I'm trying to transform a set of vertices from world coordinates (x,y,z) to screen coordinates (x,y,depth), then back again to world coordinates. I've managed the first transformation from world to screen successfully, but I'm having trouble going in the opposite direction. I'm using an orthographic camera. (There are related issues -- #720 and #860 -- but I don't think either directly answers my question directly)

My the code I'm using is here:

`
verts = mesh.verts_packed()
transformed_points = camera.transform_points_screen(verts, image_size=torch.tensor([[img_size, img_size]]))
untransformed_points = camera.unproject_points(transformed_points[None, :], from_ndc=False)
print(verts)
print(transformed_points)
print(untransformed_points)

`
The printed output is...

tensor([[-0.3072,  0.3689,  0.3239],
        [-0.3072, -0.3689,  0.3239],
        [ 0.3072, -0.3689,  0.3239],
        [ 0.3072,  0.3689,  0.3239],
        [-0.3072,  0.3689, -0.3239],
        [-0.3072, -0.3689, -0.3239],
        [ 0.3072, -0.3689, -0.3239],
        [ 0.3072,  0.3689, -0.3239]])
tensor([[1.4236e+02, 1.8128e+02, 1.7874e-02],
        [1.4236e+02, 3.4314e+02, 2.1716e-02],
        [2.6202e+02, 3.9576e+02, 1.8265e-02],
        [2.6202e+02, 2.3389e+02, 1.4423e-02],
        [2.4998e+02, 1.1624e+02, 2.2139e-02],
        [2.4998e+02, 2.7811e+02, 2.5981e-02],
        [3.6964e+02, 3.3072e+02, 2.2530e-02],
        [3.6964e+02, 1.6886e+02, 1.8688e-02]])
tensor([[[-167.2972,  156.8746,   23.2388],
         [-221.4495,  295.5739,  -40.2450],
         [-330.0834,  340.6605,   16.7758],
         [-275.9311,  201.9612,   80.2596],
         [-227.4205,  101.1427,  118.5855],
         [-281.5728,  239.8420,   55.1017],
         [-390.2067,  284.9286,  112.1225],
         [-336.0544,  146.2293,  175.6063]]])

I've also looked into transforming the points from screen to NDC before passing into unprotect but have had limited success on that route as well. Was wondering if I could get a little guidance. 

Thanks so much, I really appreciate it!

**Comment by bottler** [comment]
There's a couple of complications here. Is the camera defined in screen space or NDC space?

**Comment by nashapir** [comment]
Thanks so much! Super helpful!
