### ISSUE TITLE
How to construct ray bundles if camera parameters are defined in screen space?

### ISSUE THREAD

**Issue by mayankgrwl97** [facebookresearch/pytorch3d#1059]
##  Why is "from_ndc" hard coded to True while constructing ray bundle from xy grid?

Ref: https://github.com/facebookresearch/pytorch3d/blob/5053142363afca730c44ed2bd1a6aa24d4fc7635/pytorch3d/renderer/implicit/raysampling.py#L552

How can we generate ray bundles if the camera parameters are defined in the screen space. Why does the unproject_points function not use the "in_ndc" parameter instead?

**Comment by bottler** [comment]
The raysampling code sets up its rays in NDC space. Hardcoding `from_ndc=True` should mean it the raysamplers are correct even if the cameras have `in_ndc=False`.

This way the raysampling code is only written once but works for both. When you say use "in_ndc" instead, do you mean to look at in_ndc and do one of two different things? I think that would need much more code.
