### ISSUE TITLE
what's the focal_lenght unit compare with a fixed length hyposisi trained 3d pose model

### ISSUE THREAD

**Issue by jinfagang** [facebookresearch/pytorch3d#1061]
Hi, I have a 3d pose trained model, this model using a fixed focal lenght in 1000.

In opendr, it can rendered in such way:

```
camera_t = np.array([camera[1], camera[2], 2*focal_length/(res * camera[0] +1e-9)])
rend_img = renderer.render(vertices, camera_t=camera_t,
                           img=img, use_bg=True,
                           focal_length=focal_length,
                           body_color=color)
```
Here, the focal_lenght is 1000.

I can visualized normally.

But I tried using same Perspetive camera in Pytorch3d, if set focal_lenght to 1000, it too close to see the mesh target, can not see the correct size of mesh.

If I set to focal_length / 224, the result like this:

![image](https://user-images.githubusercontent.com/21303438/151480119-475f1992-7f39-412c-afbe-c651b14acbd0.png)

as it can be seen, the rendered result smaller than original image.

But when I set focal_length to focal_lenght * 2 /224, the result like:

![image](https://user-images.githubusercontent.com/21303438/151480488-a6397a8f-e609-4a24-95ae-7695490b397a.png)

what's exactly focal_lenght should be set in pytorch3d camera?

**Comment by bottler** [comment]
Focal length is as described in the formulas in [the cameras doc](https://github.com/facebookresearch/pytorch3d/blob/main/docs/notes/cameras.md). It looks like you are rescaling the depth of your data before you pass to opendr. Do you know the exact definitions used in opendr and why you had to do that?

**Comment by jinfagang** [comment]
@bottler am not really sure, it was some common usage on popular human 3d mesh models such as SPIN, HMR, etc. they all using opener render, I want using pytorch3d since it was faster, but seems it can not fully aligned.
