### ISSUE TITLE
when calculate normal map, we find "pix_to_face   -1 "

### ISSUE THREAD

**Issue by wasahaiah** [facebookresearch/pytorch3d#1063]
With a mesh, I want to obtain its normal map. I find the normal map is unexpected:
![uv](https://user-images.githubusercontent.com/26264214/151644052-c1b11f2c-6930-4c89-a321-3f9399d5a3f1.png)
When I debug the code, I find "pix_to_face" below:
![1](https://user-images.githubusercontent.com/26264214/151644039-27bf0bb4-ae48-41ea-9029-e3467ab00df7.png)

what should I do to get the right result.

The attached code with .obj file is below:
[render.zip](https://github.com/facebookresearch/pytorch3d/files/7962825/render.zip)

**Comment by gkioxari** [comment]
Yes that's normal. Read here

https://github.com/facebookresearch/pytorch3d/blob/c2862ff42706ae98ce4053e7d76959f05fb2c3b3/pytorch3d/renderer/mesh/rasterize_meshes.py#L106-L113

**Comment by zhangyahu1** [comment]
Hi @gkioxari, from the @wasahaiah's code, the UV map is obtained. May I know how to get a 2D normal map of the mesh provided by @wasahaiah, but not UV map? To be clear, the 2D normal map should be aligned well with the rendered image (as below). Thanks.
<img width="238" alt="rendered image" src="https://user-images.githubusercontent.com/44366284/222821125-f3f8b944-438b-44b8-a5c5-d37b33dec63f.png">

**Comment by yejr0229** [comment]
Hi, I wonder have you solve this? I use this code to render normal map:
![image](https://github.com/user-attachments/assets/8f99d9fb-5496-4243-88fd-05a7bfb9351b)

And I get:
![image](https://github.com/user-attachments/assets/0779d7df-2e94-40a2-a6f8-4ea64e0e83f5)

How to render a normal map like this?
https://github.com/facebookresearch/pytorch3d/blob/6f2212da46f3ad1a596b3e1017be2d16eaaf95f9/pytorch3d/renderer/mesh/rasterizer.py#L168
