### ISSUE TITLE
Confusing warning in "rasterize_coarse.cu"

### ISSUE THREAD

**Issue by Angtian** [facebookresearch/pytorch3d#1064]
The warning in rasterize_coarse.cu. Line 193 is confusing. It says:
            "Bin size was too small in the coarse rasterization phase. "
            "This caused an overflow, meaning output may be incomplete. "
            "To solve, "
            "try increasing max_faces_per_bin / max_points_per_bin, "
            "decreasing bin_size, "
            "or setting bin_size to -1 to use the naive rasterization.";
It is my understanding that it warning appears when Bin size is large than excepted, not small.

**Comment by gkioxari** [comment]
Our rasterizer takes a coarse-to-fine approach by binning the image into rectangles to compute the rasterization outputs. 
We set the bin size by default but if your mesh/point cloud is too large then the default value might not be appropriate. 
This warning tells you exactly that. So you need to increase the `max_faces_per_bin` (for meshes) or the `max_points_per_bin` (for point clouds).

**Comment by Angtian** [comment]
Thanks for the reply. I get the point. But may I have one more question, In the first sentence it says "Bin size was too small", but it also suggests "decreasing bin_size", I am confused about this since it seems to be a conflict.

**Comment by gkioxari** [comment]
There are two parameters here: `bin_size` and `max_faces_per_bin`

You can find their definitions here:
https://github.com/facebookresearch/pytorch3d/blob/c2862ff42706ae98ce4053e7d76959f05fb2c3b3/pytorch3d/renderer/mesh/rasterizer.py#L37-L45

**Comment by Angtian** [comment]
Then for your reply. So if my understanding is correct that this warning means the "bin size" is set to be too large that we need to decrease it?

**Comment by gkioxari** [comment]
Yes. Or increase `max_faces_per_bin`.

**Comment by JLee2022** [comment]
excellent！

**Comment by JLee2022** [comment]
excellent！help me a lot

**Comment by Veni-VidiVici-xiaoxu** [comment]
so what number shall I take for bin_size and max_points_per_bin?

**Comment by HernandoR** [comment]
> so what number shall I take for bin_size and bin_size?

furtheraway, what whould be the difference between increasing bin_size and bin_size?

**Comment by wjh19990923** [comment]
but making bin_size=0 will significantly increase the computational time, is there any way to switch off the warning because its annoying in iterative optimization

**Comment by bottler** [comment]
The warning is usually important: ignoring it will mean the rasterization result is liable to be incorrect!

**Comment by ttaoREtw** [comment]
Any recommended ways to set the values for `bin_size` and `max_points_per_bin` if we meet this warning?

**Comment by wellneck** [comment]
I was rendering some voxels，this warning was print to terminal so many times that i can't see any other output
