### ISSUE TITLE
Installation problem on Windows

### ISSUE THREAD

**Issue by titikakakuko** [facebookresearch/pytorch3d#1065]
Cannot compile .cpp to .obj, how should I change the source code?

```
LINK : fatal error LNK1181: cannot open input file 'C:\Users\pytorch3d\build\temp.win-amd64-3.7\Release\Users\pytorch3d\pytorch3d\csrc\ext.obj'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX64\\x64\\link.exe' failed with exit status 1181
```

**Comment by bottler** [comment]
Can you check that the log file doesn't have any other errors? If not, this isn't a problem with the code. I don't know what  causes error LNK1181 . It is apparently an error related to paths. It has been mentioned in a few other issues, but the reason it was solved wasn't clear. People tried building in a different way.

**Comment by loss133** [comment]
Hello, I also encountered this problem, how did you solve it?

fatal error LNK1181: 无法打开输入文件“D:\Documents\DECA1\pytorch3d\build\temp.win-amd64-3.9\Release\Documents\DECA1\pytorch3d\pytorch3d\csrc\ball_query\ball_query.obj”
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX64\\x64\\link.exe' failed with exit code 1181

Mine is no “ball_query.obj” file in “D:\Documents\DECA1\pytorch3d\build\temp.win-amd64-3.9\Release\Documents\DECA1\pytorch3d\pytorch3d\csrc\ball_query\”

**Comment by loss133** [comment]
Hello, I got this problem too, how did you solve it?

The problem are as follows:
LINK : fatal error LNK1181: 无法打开输入文件“D:\Downloads\pytorch3d\build\temp.win-amd64-3.8\Release\Downloads\pytorch3d\pytorch3d\csrc\ext.obj”
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181

I looked it up and found out that there was not "ext.obj" in "“D:\Downloads\pytorch3d\build\temp.win-amd64-3.8\Release\Downloads\pytorch3d\pytorch3d\csrc\",but I don't know why. Can someone help me?

**Comment by zaiyicheng** [comment]
i got this problem too, have anyone solve this?

**Comment by ywh0703** [comment]
i got this problem too, have anyone solve this?
