### ISSUE TITLE
How to set the raster_settings?

### ISSUE THREAD

**Issue by JasonBoy1** [facebookresearch/pytorch3d#1066]
## ❓ Questions on how to use PyTorch3D

![image](https://user-images.githubusercontent.com/33180378/152837052-c35f67be-28cb-43be-8368-e97176175aaf.png)

I am wondering how to use the proper raster settings for different meshes. E.g, this mesh has 6890 vertices and I use `blur_radius=np.log(1e-4-1)*1e-4, faces_per_pixel=50` but the edges are very explicit but the faces are very vague. Could you teach me how to modify the settings due to different meshes?

**Comment by JasonBoy1** [comment]
@bottler

**Comment by bottler** [comment]
Sorry - I can't really help. This depends on your modelling situation.

**Comment by nikhilaravi** [comment]
@JasonBoy1 what shader are you using to get the image above?
