### ISSUE TITLE
OBJ does not render with texture without explicit usemtl

### ISSUE THREAD

**Issue by YuxuanSnow** [facebookresearch/pytorch3d#1068]
Dear PyTorch3d developers,

i want to render an object which I downloaded from http://ycb-benchmarks.s3-website-us-east-1.amazonaws.com/. The `.obj`, `.mtl`, and `.png` texture image are available. However, when I tried to load the object using `load_obj`, the `aux` object only contains `normals` and `verts_uvs`, no information about texture in `material_colors`, `texture_iamges`,  and `texture_atlas`.  

I uploaded the textured object file into google drive: https://drive.google.com/file/d/1FU04gYsXy7_agL_1G9ZcjI8AQd1iY3Lx/view?usp=sharing. I wonder if you can try to load the aux and tell me how should I modify the `.mtl` file?

Thanks!

**Comment by bottler** [comment]
The obj file has no `usemtl` line.

**Comment by patricklabatut** [comment]
Such `usemtl` line may however not be mandatory as long as a material library has been specified: a default material can be automatically picked from the `.mtl` file (e.g. the first / last one). In particular, this seems to be the behavior of the built-in viewer on macOS (the shared object renders with texture without any change).

**Comment by patricklabatut** [comment]
@YuxuanSnow Could try to add the following line to the `.obj` file, right after the `mtllib`:

```
usemtl texture_textured.png
```

**Comment by YuxuanSnow** [comment]
@bottler @patricklabatut That works after i added the line in `.obj` file. Thank you so much for your answer and help!

**Comment by patricklabatut** [comment]
@bottler It could still be a good idea to implement the fallback / default material.
