### ISSUE TITLE
How to load obj files with rgb info per vertex

### ISSUE THREAD

**Issue by ChunLLee** [facebookresearch/pytorch3d#1069]
## ❓ Questions on how to use PyTorch3D

Hi I want to load the .obj files with rgb values per vertex, as shown below:
v x1 y1 z1 r1 g1 b1
v x2 y2 z2 r2 g2 b2
v x3 y3 z3 r3 g3 b3
...

However, after the mesh is loaded with load_objs_as_meshes, the texture information is missing and mesh.textures is NoneType.
Is there any method to load the mesh such texture and how to render it, since the info about the material is also not available?

NOTE: Please look at the existing list of Issues tagged with the label ['question`](https://github.com/facebookresearch/pytorch3d/issues?q=label%3Aquestion) or ['how-to`](https://github.com/facebookresearch/pytorch3d/issues?q=label%3A%22how+to%22). **Only open a new issue if you cannot find an answer there**.

Also note the following:

1. If you encountered any errors or unexpected issues while using PyTorch3D and need help resolving them,
   please use the "Bugs / Unexpected behaviors" issue template.

2. We do not answer general machine learning / computer vision questions that are not specific to
   PyTorch3D, such as how a model works or what algorithm/methods can be
   used to achieve X.

**Comment by patricklabatut** [comment]
See the discussion in #779. At this time, vertex colors in OBJ files are not supported because it is a non-standard extension of the file format. For now, try converting your OBJ files to PLY and then loading the PLY files instead in PyTorch3D.

**Comment by ChunLLee** [comment]
Thank you very much for your help!
