### ISSUE TITLE
Which space value is the depth we can get from rasterizer?

### ISSUE THREAD

**Issue by KeitoTakaishi** [facebookresearch/pytorch3d#1070]
## ❓ Questions on how to use PyTorch3D

Hi!

We can get the depth value using rasterizer as follows.
```
rasterizer = MeshRasterizer(cameras=cameras, raster_settings=raster_settings)
fragments = rasterizer(mesh)
depth = fragments.zbuf 
```

However, it is not clear which space this depth is a value for.
in NDC, Clip space or camera space?

I want to get depth in NDC.
How can I achieve this?

The value of depth in NDC differs depending on the Graphics API.
In openGL -1.0 ~ 1.0, in DirectX 0.0 ~ 1.0.
How is it defined in Pytorch3D?
I have read this [page](https://pytorch3d.org/docs/renderer_getting_started), but I'm not clear.

**Comment by bottler** [comment]
zbuf is positive where there is a face found, with a higher number for a further away face. I think the scale will depend on the camera type in use. I think clipping doesn't change the z value, just whether or not it will be present.
