### ISSUE TITLE
Does pytorch3d support ROCM platform？

### ISSUE THREAD

**Issue by loss133** [facebookresearch/pytorch3d#1073]
I followed the steps in the INSTALL.md to install PyTorch, and tried different versions of PyTorch, but it always showing the Error: Not Compiled with GPU Support. 
I also tried to solve this problem according to the methods mentioned in other issues, but all failed. I don't know where the problem is. Can you tell me if 3D supports ROCM platform?

**Comment by bottler** [comment]
No. The compiled parts of PyTorch3D are only in C++ (for running on CPUs) and CUDA (for running on NVidia GPUs).

**Comment by patricklabatut** [comment]
@bottler If there are other similar reports (looks to me this is the first one), could this be caught earlier / with a more explicit message?

**Comment by kjchalup** [comment]
I haven't seen other reports, this would probably be a very rare use-case we will not support in the future. I'm closing the issue.
