### ISSUE TITLE
Pulsar Batching

### ISSUE THREAD

**Issue by grgkopanas** [facebookresearch/pytorch3d#1077]
Hi,

I am trying to use the Pulsar renderer by batching different cameras while using the same geometry. I have a point cloud and I want to render it in multiple different cameras at once so I can utilize the full potential of the GPU.

I believe I have done most of this correctly but I get:
`RuntimeError: invalid argument 4: cam_pos must have dimension 1.`
I track this issue down to the fact that in https://github.com/facebookresearch/pytorch3d/blob/main/pytorch3d/csrc/pulsar/pytorch/renderer.cpp#L228
the batch size is controlled only by the batch dimension of the spheres.

Is what I am doing supported? On one hand, I could practically batch all the tensors, but the amount of unused and duplicate information would be enormous for a large point cloud and small camera sensors.

**Comment by bottler** [comment]
The cameras and point clouds have to have the same batch size, meaning you need to extend the Pointclouds to the number of cameras. Not all the additional memory this takes is thereby "wasted": for example the transformed camera-space point clouds will need to be stored separately anyway.

You may be able to save some memory by using a Pointclouds initialised from expand()ed tensors and similar tricks.

**Comment by grgkopanas** [comment]
I see, it is just that having small sensors means that most of the sphere will rasterize outside the image plane. I will try that. Thanks for the very swift response.
