### ISSUE TITLE
Difficulty in installation

### ISSUE THREAD

**Issue by yyl494** [facebookresearch/pytorch3d#108]
Here is some error in the 2nd step of installation, which is installing prebuilt binaries for Pytorch3d. But I think my core library is correct.
![image](https://user-images.githubusercontent.com/62021819/76322287-949cd780-62b9-11ea-8768-5d9ddf40edb2.png)
Here is my conda list. torch version is 1.4.0
![image](https://user-images.githubusercontent.com/62021819/76322996-75eb1080-62ba-11ea-8a68-a73d210f543c.png)
![image](https://user-images.githubusercontent.com/62021819/76323062-9024ee80-62ba-11ea-82b7-208cc5eaee92.png)
![image](https://user-images.githubusercontent.com/62021819/76323105-9fa43780-62ba-11ea-8c33-50afecddfc23.png)
![image](https://user-images.githubusercontent.com/62021819/76323122-a8950900-62ba-11ea-9c5d-77073c8e1e15.png)
![image](https://user-images.githubusercontent.com/62021819/76323149-b2b70780-62ba-11ea-8888-4f46d7cea607.png)

my python version is 3.6 and cuda 10.0 in 'nvcc -V'. I don't know what is '__cuda = 10.2' is in the following picture.
![image](https://user-images.githubusercontent.com/62021819/76323372-01fd3800-62bb-11ea-93d9-17ba0ce549dc.png)

**Comment by bottler** [comment]
You don't have pytorch (or torchvision) installed in the list. That's why it's complaining.

**Comment by yyl494** [comment]
> You don't have pytorch (or torchvision) installed in the list. That's why it's complaining.

But I can see my toch and torchvision in the last picture in conda list

**Comment by bottler** [comment]
Sorry. I missed them. Something funny is happening. It looks like torch is installed from pypi not conda - is that right? That means you don't actually have pytorch conda package.

Can you maybe try in a new repository, just installing what you need.

It is true that we don't support cuda 10.2, but I don't think that's a problem here, you have the 10.0 cudatoolkt.

**Comment by yyl494** [comment]
I use pypi because of a firewall. Can I use torch 1.3 from a mirror website？

**Comment by bottler** [comment]
If you are happy with CPU-only for some parts of pytorch3d, you can try `pip install pytorch3d` in that environment.

Another possibility is building pytorch3d from source in that environment.

**Comment by yyl494** [comment]
Thank you! I'll try these.

**Comment by yyl494** [comment]
I solve the problem with `conda install --offline` for torch, torchvision and pytorch3d. It's really important to use conda and pypi is the reason of conflicts. Thank you.
