### ISSUE TITLE
Question on the definition of voxel in volume rendering

### ISSUE THREAD

**Issue by hwjiang1510** [facebookresearch/pytorch3d#1081]
Thanks for implementing the volume rendering techniques! It really makes research much easier.

When I was going through the official tutorial on [fitting a volume using volume rendering](https://colab.research.google.com/github/facebookresearch/pytorch3d/blob/stable/docs/tutorials/fit_textured_volume.ipynb), some questions came to me.

![1645158244(1)](https://user-images.githubusercontent.com/32667116/154617607-510a534b-12de-4d21-95ad-44237dc2487a.png)

1. As commented in the code, the voxel is centered at the origin point [0,0,0]. How can we set an offset to the voxels, where I want to locate the center of the volume at [x, y, z]?
2. Is there any physical meaning for the parameter volume_extend_world? Is it the size of the volume in meters?

Thanks!

**Comment by hwjiang1510** [comment]
For the first question, I saw we can set a parameter **volume_translation** when initializing the volume. So, is the number in the volume_translation also in meters?

**Comment by bottler** [comment]
The world space unit of measure is whatever you want it to be (e.g. meters, inches). Everything scales by it.
