### ISSUE TITLE
Returning the index of the closest face from a point to a mesh

### ISSUE THREAD

**Issue by nmakes** [facebookresearch/pytorch3d#1083]
Hi,

In [point_face_distance](https://github.com/facebookresearch/pytorch3d/blob/327bd2b9762c05ec7a6f74c2ec1e46f2a764e326/pytorch3d/loss/point_mesh_distance.py#L21), it seems like the intent was to return both indices and distances (according to the [docstring](https://github.com/facebookresearch/pytorch3d/blob/327bd2b9762c05ec7a6f74c2ec1e46f2a764e326/pytorch3d/loss/point_mesh_distance.py#L43)). However, only [distances are being returned](https://github.com/facebookresearch/pytorch3d/blob/327bd2b9762c05ec7a6f74c2ec1e46f2a764e326/pytorch3d/loss/point_mesh_distance.py#L56) (`idxs` is not returned). Was this intentional?

I'm trying to extract the index of the nearest face to a 3D point. Could anyone please refer me to an alternative function?

Thanks!

**Comment by bottler** [comment]
If you just need the forward pass, you can call the underlying function `pytorch3d._C.point_face_dist_forward` with arguments `points, points_first_idx, tris, tris_first_idx, max_points` which returns both. 

If you was to use the distances at the same time, and you need the backward pass, you need to write a modified _PointFaceDistance class.

**Comment by nmakes** [comment]
Thanks for the quick reply!

Closing the issue for now.
