### ISSUE TITLE
What is R and T?

### ISSUE THREAD

**Issue by UestcJay** [facebookresearch/pytorch3d#1086]
when I use PointsRenderer, :
`cameras = FoVOrthographicCameras(device=device, R=R, T=T, znear=0.01)`, is the R and T extrinsics of the camera? I want to render point cloud in world to a view, Is this all right?
` R = torch.from_numpy(extrinsics_ref[:3,:3][np.newaxis,:,:])

        T = torch.from_numpy(extrinsics_ref[:3,3][np.newaxis,:])

        cameras = FoVPerspectiveCameras(device='cpu', R=R, T=T, znear=0.01)
        raster_settings = PointsRasterizationSettings(
            image_size=(128,160),
            radius=0.03,
            points_per_pixel=10
        )

        rasterizer = PointsRasterizer(cameras=cameras, raster_settings=raster_settings)

        renderer = PointsRenderer(
            rasterizer=rasterizer,
            compositor=AlphaCompositor()
        )

        verts = torch.from_numpy(xyz_ref.T.astype(np.float32)).to('cpu')

        rgb = torch.from_numpy(resized_img_src).to('cpu')

        point_cloud = Pointclouds(points=[verts], features=[rgb])

        images = renderer(point_cloud)`

**Comment by bottler** [comment]
Yes, R and T are the extrinsics, defining the camera location. https://pytorch3d.org/docs/cameras may be helpful.

**Comment by UestcJay** [comment]
这是来自QQ邮箱的自动回复邮件。你好，你的来件我已收到，谢谢。
