### ISSUE TITLE
How to apply differentiable transforms to meshes?

### ISSUE THREAD

**Issue by achleyd** [facebookresearch/pytorch3d#1087]
## How to apply (differentiable) transforms to meshes?

I want to adapt the "camera position optimization"-tutorial such that the pose of the mesh is optimized instead of the pose of the camera. To achieve this, I want to apply a transform to the mesh and make the parameters (translation & rotation) of this transform learnable parameters of the model.

To test this, I have adapted the Model from the tutorial and added a mesh transform (just a translation for now) to the forward step as follows:

```
class Model(nn.Module):
    def __init__(self, meshes, renderer, image_ref):
        super().__init__()
        self.meshes = meshes
        self.device = meshes.device
        self.renderer = renderer
        
        # Get the reference/target depth image
        image_ref = image_ref.clone()
        self.register_buffer('image_ref', image_ref)
        
        # Create an optimizable parameter for the x, y, z translation of the mesh. 
        self.translation_params = nn.Parameter(
            torch.from_numpy(np.array([[0,0,0]], dtype=np.float32)).to(self.device))

    def forward(self):
        trans = Translate(self.translation_params, device=self.device)
        tverts = trans.transform_points(self.meshes.verts_list()[0])
        faces = self.meshes.faces_list()[0]
        tmesh = pytorch3d.structures.Meshes(
            verts=[tverts.to(self.device)],   
            faces=[faces.to(self.device)],
        )

        # render mesh with static camera
        R = torch.eye(3, device=self.device).unsqueeze(dim=0)
        T = torch.tensor([0,0,4], device=self.device).unsqueeze(dim=0)
        fragments = self.renderer(meshes_world=self.meshes, R=R, T=T)
        dimg = fragments.zbuf

        loss = torch.sum((dimg - self.image_ref) ** 2)
        return loss, dimg

```

For my example use case I was only interested in depth images. The renderer consists then only of a rasterizer:
```
raster_settings = RasterizationSettings(
    image_size=(height, width),
    faces_per_pixel=1,
    blur_radius=0
)
renderer = MeshRasterizer(
    cameras=cameras, 
    raster_settings=raster_settings
)

```

This currently fails during the call to loss.backwards() with a runtime error:
```
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```
where the optimization loop and optimizer etc are all identical to the original tutorial code:
```
...
for i in loop:
    optimizer.zero_grad()
    loss, _ = model()
    loss.backward()
    optimizer.step()
...
```

I currently assume that the creation of the new mesh detaches the loss from the translation parameters. Is this correct? If so, how can a transform be applied to a mesh without breaking this? What would be an alternative/correct way to achieve my initial goal of optimizing the mesh pose instead of the camera pose?

**Comment by bottler** [comment]
The error means that `loss` is not the output of a calculation based on a Parameter or something which requires_grad, so there is no autograd graph. In this case, it is that the calculation doesn't use translation_params.

I think for what you mean, you need to change 
```
fragments = self.renderer(meshes_world=self.meshes, R=R, T=T)
```
to
```
fragments = self.renderer(meshes_world=tmesh, R=R, T=T)
```

**Comment by ZheningHuang** [comment]
> The error means that `loss` is not the output of a calculation based on a Parameter or something which requires_grad, so there is no autograd graph. In this case, it is that the calculation doesn't use translation_params.
> 
> I think for what you mean, you need to change
> 
> ```
> fragments = self.renderer(meshes_world=self.meshes, R=R, T=T)
> ```
> 
> to
> 
> ```
> fragments = self.renderer(meshes_world=tmesh, R=R, T=T)
> ```

this is working! thanks!
