### ISSUE TITLE
opencv_from_cameras_projection does not work with batches

### ISSUE THREAD

**Issue by WeberSamuel** [facebookresearch/pytorch3d#1089]
## 🐛 Bugs / Unexpected behaviors
When trying to get opencv values for cameras with batch sizes higher than two, the function throws a runtime error:

```
~/miniconda3/envs/IDP/lib/python3.8/site-packages/pytorch3d/renderer/camera_conversions.py in _opencv_from_cameras_projection(cameras, image_size)
     82     # pyre-fixme[29]: `Union[BoundMethod[typing.Callable(torch.Tensor.__neg__)[[Named...
     83     principal_point = -p0_pytorch3d * scale + c0
---> 84     focal_length = focal_pytorch3d * scale
     85 
     86     camera_matrix = torch.zeros_like(R)

RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 1
```

## Instructions To Reproduce the Issue:

```
import torch
from pytorch3d.renderer import PerspectiveCameras
from pytorch3d.ops import eyes
from pytorch3d.utils.camera_conversions import opencv_from_cameras_projection, cameras_from_opencv_projection

cams = PerspectiveCameras(R=eyes(3, 4), T=torch.zeros(4, 3))
opencv_from_cameras_projection(cams, image_size=torch.full((4, 2), 400))
```

## Workarounds
Setting ``cams.focal_length = cams.focal_length[..., None]`` before the function call fixes the issue.

Alternative changing the error line to:
``focal_length = focal_pytorch3d[..., None] * scale`` fixes it also

**Comment by bottler** [comment]
Which version of PyTorch3D are you using? Your code works fine for me with the latest `main`, so I wonder if there's a bug which has been fixed.

**Comment by WeberSamuel** [comment]
Version 0.6.1
Then it is probably already fixed

**Comment by bottler** [comment]
Must be fixed recently. I'm closing for the moment.
