### ISSUE TITLE
The rendering results of pytorch3d 

### ISSUE THREAD

**Issue by UestcJay** [facebookresearch/pytorch3d#1091]
## ❓ Questions on how to use PyTorch3D

I have a depth image of a view V1, want to get depth image in view V2.  we have R and T of view V1, V2, So I use PointsRasterizer. 

`       width, height = depth_src.shape[1], depth_src.shape[0]

        # src view x, y
        x_src, y_src = np.meshgrid(np.arange(0, width), np.arange(0, height))

        x_src, y_src = x_src.reshape([-1]), y_src.reshape([-1])

        # src 3D space: 3 × N
        xyz_src = np.matmul(np.linalg.inv(intrinsics_src),
                            np.vstack((x_src, y_src, np.ones_like(x_src))) * depth_src.reshape([-1]))

        # ref 3D world space: 3 × N
        xyz_ref = np.matmul(np.linalg.inv(extrinsics_src),
                            np.vstack((xyz_src, np.ones_like(x_src))))[:3]

        R = torch.from_numpy(extrinsics_ref[:3, :3][np.newaxis, :, :]).to(self.device)
        T = torch.from_numpy(extrinsics_ref[:3, 3][np.newaxis, :]).to(self.device)
        image_size = torch.tensor([[128, 160]], device=self.device)

        camera_matrix = torch.from_numpy(intrinsics_ref[np.newaxis, :, :]).to(self.device)
        pytorch_cameras = cameras_from_opencv_projection(R, T, camera_matrix, image_size).to(self.device)
        cameras = PerspectiveCameras(focal_length=pytorch_cameras.focal_length,
                                     principal_point=pytorch_cameras.principal_point,
                                     R=pytorch_cameras.R,
                                     T=pytorch_cameras.T,
                                     image_size=[[128, 160]],
                                     in_ndc=True,
                                     device=self.device)
        raster_settings = PointsRasterizationSettings(
            image_size=[128, 160],
            radius=0.02,
            points_per_pixel=10
        )
        rasterizer = PointsRasterizer(cameras=cameras, raster_settings=raster_settings)
        renderer = PointsRenderer(
            rasterizer=rasterizer,
            compositor=AlphaCompositor()
        )
        verts = torch.from_numpy(xyz_ref.T.astype(np.float32)).to(self.device)
        depth = torch.from_numpy(depth_src.reshape([-1, 1])).to(self.device)
        depth_cloud = Pointclouds(points=[verts], features=[depth])
        depth_images = renderer(depth_cloud).cpu().numpy()
`
but the rendered depth image have so many small holes in rendered depth, how can I improve it, the up image is depth of V1, other is rendered depth of V2?
![depth_V1](https://user-images.githubusercontent.com/37372259/155839205-9c4cbd92-2f6a-4bdf-ba3c-72397193b2f9.JPG)
![depth_V2](https://user-images.githubusercontent.com/37372259/155839223-de94264e-0d61-43fc-85d7-fe34ba625f1a.JPG)

**Comment by gkioxari** [comment]
This does not seem to be a bug/issue with the library. If you need help from other users, please move this to the GH Discussions page. Note that the issue page is for reporting bugs or feature requests.
