### ISSUE TITLE
The form of the inhomogeneous 4D vector

### ISSUE THREAD

**Issue by AlphaPlusTT** [facebookresearch/pytorch3d#1092]
## ❓ Questions on how to use PyTorch3D
As far as i know, an extend 4D world vector `pw = (xw, yw, zw, 1).T` can use a full rank 4x4 projection matrix `P` to get a 4D screen vector  `ps` and we can normalize `ps` wrt. its 3rd entry to get `ps = (xs/zs, ys/zs, 1, 1/zs).T` and the `xs/zs, ys/zs` is the image pixels coordinate. 

So, if we want to retrieve a 3D point from its pixel coordinates, we just need `P.inverse() x ps` and subsequent normalization of the output wrt. its 4th entry, but in this repository, a strange form of ps is used, like `(xs/zs, ys/zs, 1/zs, 1).T` (the inverse depth `1/zs` is the 3rd instead of 4th), and the unproject is `ps x P.inverse()` instead of `P.inverse() x ps`, is there something I have missed?

The strange form of `ps` is declared [here](https://github.com/facebookresearch/pytorch3d/blob/471b12681888d37e15bd3fe6ae2b70032f06c026/pytorch3d/renderer/cameras.py#L1134) as `(xs/zs, ys/zs, 1/zs)`, and expand 1 [here](https://github.com/facebookresearch/pytorch3d/blob/471b12681888d37e15bd3fe6ae2b70032f06c026/pytorch3d/transforms/transform3d.py#L343) as `(xs/zs, ys/zs, 1/zs, 1).T`, but i believe it should be `(xs/zs, ys/zs, 1, 1/zs).T`, and product the P [here](https://github.com/facebookresearch/pytorch3d/blob/471b12681888d37e15bd3fe6ae2b70032f06c026/pytorch3d/transforms/transform3d.py#L346) should be` _broadcast_bmm(composed_matrix, points_batch)`.

**Comment by bottler** [comment]
In the conversion from projective space to affine space in PyTorch3D, I think it's simpler to think that the fourth entry is what we divide by, not the third. So from [a,b,c,d], you get x=a/d, y=b/d, and depth (whose convention varies in the different camera objects) is c/d.

**Comment by AlphaPlusTT** [comment]
@bottler thanks for your replay and i found the form of K in pytorch3D is not what I thought. As shown in the figure below:
![2058986763](https://user-images.githubusercontent.com/58316756/156560368-d3f89307-6a38-42b8-a8b2-daeb886573d8.jpg)

But I have another question is that i found the K and T are transposed both but R is not, As shown in the second line in the following figure, why?
![1049525133](https://user-images.githubusercontent.com/58316756/156560875-f769bc10-a1ed-46bd-be22-5eea70446646.jpg)

the R and T is in pytorch3d/renderer/cameras.py#L1550

**Comment by bottler** [comment]
I don't understand the question. But PyTorch3D is consistent with itself, so you should be able to work out step by step.
