### ISSUE TITLE
Speed of PointsRenderer

### ISSUE THREAD

**Issue by ShuoZheLi** [facebookresearch/pytorch3d#1093]
I am working on a project that requires me to continuously update camera position & angle then render the scene. However, as I measure the time spent of PointsRenderer, it is close to 1s. Does this make sense? Is there any way that I can speed up the renderer?

the code for set up the rendering pipeline:

`t0 = time.time()
new_r, new_T = rotate_on_spot(
	# camera's rotation around the origin
	R = torch.Tensor((RT.from_euler('y', 0, degrees=True)).as_matrix())[None, :].to(device,non_blocking=True),
	# camera's position
	T = torch.Tensor([13.7, -5.7, -4.4]).unsqueeze(0).to(device,non_blocking=True), 
	# camera's rotation to itself
	rotation = torch.Tensor((RT.from_euler('yxz', [348.9,0,0], degrees=True)).as_matrix())[None, :].to(device,non_blocking=True)
)
#- initialize the camera
cameras = FoVPerspectiveCameras(device=device, R=new_r, T=new_T, fov = 60)
#- initialize PointsRasterizer
rasterizer = PointsRasterizer(cameras=cameras, raster_settings=raster_settings)
#- initialize render
renderer = PointsRenderer(
	rasterizer=rasterizer,
	compositor=AlphaCompositor()
)

images = renderer(point_cloud_vk)
torch.cuda.synchronize()
print(time.time() - t0)`

Also, without, the initialization before the rendering. The time measured like this also cost almost 1s.
`t0 = time.time()
renderer(point_cloud_vk)
torch.cuda.synchronize ()
print(time.time() - t0)`

Is there any way that I can speed up the renderer?
Thank You !!

**Comment by gkioxari** [comment]
The speed of the renderer depends on the image size and the size of the point cloud and also the K (`num_points_per_pixel`). The image size and K are set in the `raster_settings`. Try playing with those.

**Comment by hzy0211** [comment]
Hi, I have the same issue. Please see the following code:
for i in range(10):
    t0 = time.time()
    RR = torch.Tensor((RT.from_euler('y', 0, degrees=True)).as_matrix())[None, :].to(device)
    TT = torch.Tensor([13.7, -5.7, -4.4]).unsqueeze(0).to(device)
    rotation_rotation = torch.Tensor((RT.from_euler('yxz', [348.9,0,0], degrees=True)).as_matrix())[None, :].to(device)

    new_r, new_T = rotate_on_spot(
        # camera's rotation around the origin
        R = RR,
        # camera's position
        T = TT,
        # camera's rotation to itself
        rotation = rotation_rotation
    )
    cameras = FoVPerspectiveCameras(device=device, R=new_r, T=new_T, fov = 60)
    rasterizer = PointsRasterizer(cameras=cameras, raster_settings=raster_settings)
    renderer = PointsRenderer(
        rasterizer=rasterizer,
        compositor=AlphaCompositor()
    )
    images = renderer(point_cloud_vk)
    print(time.time() - t0)
    # time.sleep(1)

The printing result:
0.004343509674072266 
0.06047654151916504 
0.04998898506164551 
0.04793429374694824 
0.04870963096618652 
0.05289936065673828 
0.04149770736694336 
0.038056135177612305 
0.038510799407958984 
0.03791308403015137

If I add a time.sleep(1) at the end of each loop, the rendering time is: 
0.0046558380126953125 
0.003924369812011719 
0.005191802978515625 
0.0052721500396728516 
0.005522251129150391 
0.005066871643066406 
0.0052793025970458984 
0.005238533020019531 
0.003215789794921875 
0.005059719085693359

Without the sleep function, only the first iteration takes a normal time, but others take much longer time. It seems that the renderer prevents moving the data from CPU to GPU for the next iteration. Could you let me know how to resolve this issue?

**Comment by bottler** [comment]
@hzy0211 You need to take account of synchronization. The GPU works asynchronously with respect to Python on the CPU, which means measuring time taken is a bit complicated. When Python reaches the line `print(time.time() - t0)`, it doesn't mean that the renderer has completed. If you add `torch.cuda.synchronize()` before that line like the code earlier, then things may become a bit clearer.
