### ISSUE TITLE
save_texture missing in fit_textured_mesh

### ISSUE THREAD

**Issue by yosun** [facebookresearch/pytorch3d#1094]
## ❓ Questions on how to use PyTorch3D

How do you generate and save the final predicted texture?

https://github.com/facebookresearch/pytorch3d/blob/main/docs/tutorials/fit_textured_mesh.ipynb

**Comment by gkioxari** [comment]
You should use the `IO` functionality: https://github.com/facebookresearch/pytorch3d/blob/main/docs/notes/io.md

https://github.com/facebookresearch/pytorch3d/blob/471b12681888d37e15bd3fe6ae2b70032f06c026/pytorch3d/io/pluggable.py#L143-L150
