### ISSUE TITLE
How do you convert save_obj to save_mesh

### ISSUE THREAD

**Issue by yosun** [facebookresearch/pytorch3d#1095]
## ❓How do you convert save_obj to save_mesh

I'm trying to generate a final texture from this example: https://colab.research.google.com/github/facebookresearch/pytorch3d/blob/main/docs/tutorials/fit_textured_mesh.ipynb

In the final step: 4. Save the final predicted mesh

```
# Fetch the verts and faces of the final predicted mesh
final_verts, final_faces = new_src_mesh.get_mesh_verts_faces(0)

# Scale normalize back to the original target size
final_verts = final_verts * scale + center

# Store the predicted mesh using save_obj
final_obj = os.path.join('./', 'final_model.obj')
save_obj(final_obj, final_verts, final_faces)
```

Was suggested to use save_texture - however, it seems that the final_verts and final_facess generated from this example for save_obj are of a different dimension than save_mesh expects 

So, if the only way to generate a final texture is to use save_mesh, how do you do you convert the data to fit? 

Here is what I have tried 

```
import io
from pytorch3d.structures import Meshes
meshes = Meshes(final_verts,final_faces)
save_mesh(self, meshes, final_obj, None, True)
```

Errors

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-26-1312ae8ec62c>](https://localhost:8080/#) in <module>()
      1 import io
      2 from pytorch3d.structures import Meshes
----> 3 meshes = Meshes(final_verts,final_faces)
      4 save_mesh(self, meshes, final_obj, None, True)

[/usr/local/lib/python3.7/dist-packages/pytorch3d/structures/meshes.py](https://localhost:8080/#) in __init__(self, verts, faces, textures, verts_normals)
    378 
    379         elif torch.is_tensor(verts) and torch.is_tensor(faces):
--> 380             if verts.size(2) != 3 or faces.size(2) != 3:
    381                 raise ValueError("Verts or Faces tensors have incorrect dimensions.")
    382             self._verts_padded = verts

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)
```

**Comment by bottler** [comment]
What is `save_mesh`?

Anyway, the specific error is because `final_verts` and `final_faces` are the verts and faces of a single mesh. So to initialise the Meshes object, which represents a batch of meshes, you need `Meshes(final_verts[None],final_faces[None])` or `Meshes([final_verts],[final_faces])`.
