### ISSUE TITLE
save_obj does not save a usable mesh in fit_textured_mesh.ipynb

### ISSUE THREAD

**Issue by yosun** [facebookresearch/pytorch3d#1096]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## 🐛 Bugs / Unexpected behaviors
save_obj does not save a usable mesh in fit_textured_mesh.ipynb

## Instructions To Reproduce the Issue:

Please include the following (depending on what the issue is):

1. Run `/github/facebookresearch/pytorch3d/blob/main/docs/tutorials/fit_textured_mesh.ipynb`
2. download the generated final_model.obj
3a. Try opening it up in any 3D model viewer - nothing seems to appear. 
3b. Open up the obj file and observe that it is a bunch of NaNs
```
v nan nan nan
v nan nan nan
v nan nan nan
v nan nan nan
v nan nan nan
v nan nan nan
v nan nan nan
v nan nan nan
v nan nan nan
```

**Comment by yosun** [comment]
Might be related to 


```
# We initialize the source shape to be a sphere of radius 1.  
src_mesh = ico_sphere(4, device)
```
```
/usr/local/lib/python3.7/dist-packages/pytorch3d/structures/meshes.py:1108: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  self._edges_packed = torch.stack([u // V, u % V], dim=1)
```

**Comment by gkioxari** [comment]
This suggests that your optimization diverged and caused nans in the vertices of the mesh.

**Comment by yosun** [comment]
This is just running the default example - have there been breaking changes
on the defaults?
-- 
Yosun Chang, Founder and CTO

Permute.xyz | AIMagical.com

Phone: (415) 779 6786
WWW: AReality3D.com
Twitter: @yosun
