### ISSUE TITLE
Errors when compiling PyTorch3D locally

### ISSUE THREAD

**Issue by panchangda** [facebookresearch/pytorch3d#1097]
/usr/local/cuda/include/cub/detail/device_synchronize.cuh(24): error: this declaration has no storage class or type specifier

    /usr/local/cuda/include/cub/detail/device_synchronize.cuh(26): error: expected a ";"

    /usr/local/cuda/include/cub/detail/device_synchronize.cuh(33): error: this pragma must immediately precede a declaration

    /usr/local/cuda/include/cub/detail/device_synchronize.cuh(64): warning #12-D: parsing restarts here after previous syntax error

    /usr/local/cuda/include/cub/detail/device_synchronize.cuh(65): error: expected a declaration

    /usr/local/cuda/include/thrust/system/cuda/detail/util.h(60): warning #12-D: parsing restarts here after previous syntax error

    /usr/local/cuda/include/thrust/system/cuda/detail/util.h(61): error: expected a declaration

    /usr/local/cuda/include/thrust/system/cuda/detail/util.h(204): warning #12-D: parsing restarts here after previous syntax error

    /usr/local/cuda/include/thrust/system/cuda/detail/util.h(206): error: this declaration has no storage class or type specifier

    /usr/local/cuda/include/thrust/system/cuda/detail/util.h(206): error: expected a ";"

    /usr/local/cuda/include/thrust/system/cuda/detail/util.h(208): error: expected a declaration

    /usr/local/cuda/include/thrust/system/cuda/detail/util.h(237): warning #12-D: parsing restarts here after previous syntax error

    /usr/local/cuda/include/thrust/system/cuda/detail/util.h(239): error: this declaration has no storage class or type specifier

    /usr/local/cuda/include/thrust/system/cuda/detail/util.h(239): error: variable "cuda_cub" has already been defined

    /usr/local/cuda/include/thrust/system/cuda/detail/util.h(239): error: expected a ";"

    /usr/local/cuda/include/thrust/system/cuda/detail/util.h(241): error: expected a declaration

    /usr/local/cuda/include/thrust/system/cuda/detail/util.h(355): warning #12-D: parsing restarts here after previous syntax error

    /usr/local/cuda/include/thrust/system/cuda/detail/util.h(364): error: iterator_traits is not a template

    /usr/local/cuda/include/thrust/system/cuda/detail/util.h(588): error: expected a declaration

    /usr/local/cuda/include/thrust/system/cuda/detail/core/alignment.h(58): warning #12-D: parsing restarts here after previous syntax error

    /usr/local/cuda/include/thrust/system/cuda/detail/core/alignment.h(61): error: expected a declaration

    /usr/local/cuda/include/thrust/system/cuda/detail/core/alignment.h(68): warning #12-D: parsing restarts here after previous syntax error

    /usr/local/cuda/include/thrust/system/cuda/detail/core/alignment.h(248): error: expected a declaration

    /usr/local/cuda/include/thrust/system/cuda/detail/core/triple_chevron_launch.h(669): warning #12-D: parsing restarts here after previous syntax error

    /usr/local/cuda/include/thrust/system/cuda/detail/core/triple_chevron_launch.h(670): error: expected a declaration

    /usr/local/cuda/include/thrust/system/cuda/detail/core/triple_chevron_launch.h(696): warning #12-D: parsing restarts here after previous syntax error

    /usr/local/cuda/include/thrust/system/cuda/detail/core/triple_chevron_launch.h(697): error: expected a declaration

    /usr/local/cuda/include/thrust/system/cuda/detail/core/triple_chevron_launch.h(722): warning #12-D: parsing restarts here after previous syntax error

    /usr/local/cuda/include/thrust/system/cuda/detail/core/triple_chevron_launch.h(724): error: expected a declaration

    /usr/local/cuda/include/thrust/system/cuda/detail/core/triple_chevron_launch.h(725): error: expected a declaration

    /usr/local/cuda/include/thrust/system/cuda/detail/core/triple_chevron_launch.h(750): warning #12-D: parsing restarts here after previous syntax error

    /usr/local/cuda/include/thrust/system/cuda/detail/core/triple_chevron_launch.h(751): error: expected a declaration

    /usr/local/cuda/include/thrust/system/cuda/detail/core/triple_chevron_launch.h(753): error: expected a declaration

    /usr/local/cuda/include/thrust/system/cuda/detail/core/triple_chevron_launch.h(754): error: expected a declaration

    /usr/local/cuda/include/thrust/system/cuda/detail/core/triple_chevron_launch.h(779): warning #12-D: parsing restarts here after previous syntax error

    /usr/local/cuda/include/thrust/system/cuda/detail/core/triple_chevron_launch.h(780): error: expected a declaration

    /usr/local/cuda/include/thrust/system/cuda/detail/core/triple_chevron_launch.h(781): error: expected a declaration

    /usr/local/cuda/include/thrust/system/cuda/detail/core/triple_chevron_launch.h(783): error: expected a declaration

    /usr/local/cuda/include/thrust/system/cuda/detail/core/triple_chevron_launch.h(784): error: expected a declaration

    /usr/local/cuda/include/thrust/system/cuda/detail/core/triple_chevron_launch.h(809): warning #12-D: parsing restarts here after previous syntax error

    /usr/local/cuda/include/thrust/system/cuda/detail/core/triple_chevron_launch.h(810): error: expected a declaration

    /usr/local/cuda/include/thrust/system/cuda/detail/core/triple_chevron_launch.h(811): error: expected a declaration

    /usr/local/cuda/include/thrust/system/cuda/detail/core/triple_chevron_launch.h(812): error: expected a declaration

    /usr/local/cuda/include/thrust/system/cuda/detail/core/triple_chevron_launch.h(814): error: expected a declaration

    /usr/local/cuda/include/thrust/system/cuda/detail/core/triple_chevron_launch.h(815): error: expected a declaration

    /usr/local/cuda/include/thrust/system/cuda/detail/core/triple_chevron_launch.h(970): warning #12-D: parsing restarts here after previous syntax error

    /usr/local/cuda/include/thrust/system/cuda/detail/core/triple_chevron_launch.h(972): error: expected a declaration

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(140): warning #12-D: parsing restarts here after previous syntax error

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(143): error: this declaration has no storage class or type specifier

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(143): error: expected a ";"

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(146): error: this declaration has no storage class or type specifier

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(146): error: variable "agent" has already been defined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(146): error: expected a ";"

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(151): warning #12-D: parsing restarts here after previous syntax error

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(154): error: this declaration has no storage class or type specifier

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(154): error: variable "agent" has already been defined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(154): error: expected a ";"

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(156): error: expected a declaration

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(221): warning #12-D: parsing restarts here after previous syntax error

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(223): error: identifier "WrappedLevelIteratorT" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(223): error: identifier "d_levels" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(225): error: identifier "num_output_levels" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(226): error: expected a declaration

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(233): warning #12-D: parsing restarts here after previous syntax error

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(240): error: identifier "LevelT" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(241): error: identifier "LevelT" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(242): error: identifier "LevelT" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(285): error: identifier "CacheLoadModifier" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(295): error: identifier "CacheLoadModifier" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(305): error: identifier "CacheLoadModifier" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(320): error: identifier "CacheLoadModifier" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(339): error: identifier "SampleT" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(340): error: identifier "NUM_ACTIVE_CHANNELS" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(349): error: AgentHistogramPolicy is not a template

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(351): error: identifier "NUM_CHANNELS" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(352): error: identifier "BLOCK_LOAD_DIRECT" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(353): error: identifier "LOAD_DEFAULT" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(355): error: identifier "GMEM" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(364): error: AgentHistogramPolicy is not a template

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(365): error: identifier "NUM_CHANNELS" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(367): error: identifier "BLOCK_LOAD_DIRECT" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(367): error: identifier "BLOCK_LOAD_WARP_TRANSPOSE" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(368): error: identifier "LOAD_DEFAULT" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(370): error: identifier "SMEM" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(379): error: AgentHistogramPolicy is not a template

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(381): error: identifier "NUM_CHANNELS" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(382): error: identifier "BLOCK_LOAD_DIRECT" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(383): error: identifier "LOAD_DEFAULT" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(385): error: identifier "GMEM" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(394): error: AgentHistogramPolicy is not a template

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(397): error: identifier "BLOCK_LOAD_DIRECT" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(398): error: identifier "LOAD_LDG" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(400): error: identifier "BLEND" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(409): error: AgentHistogramPolicy is not a template

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(412): error: identifier "BLOCK_LOAD_DIRECT" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(413): error: identifier "LOAD_LDG" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(415): error: identifier "SMEM" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(444): error: class "Policy500" has no member class "HistogramSweepPolicy"

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(534): error: identifier "SampleIteratorT" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(535): error: identifier "CounterT" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(535): error: identifier "NUM_ACTIVE_CHANNELS" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(541): error: identifier "OffsetT" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(542): error: identifier "OffsetT" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(543): error: identifier "OffsetT" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(716): error: identifier "SampleIteratorT" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(717): error: identifier "CounterT" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(717): error: identifier "NUM_ACTIVE_CHANNELS" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(719): error: identifier "LevelT" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(720): error: identifier "OffsetT" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(721): error: identifier "OffsetT" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(722): error: identifier "OffsetT" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(725): error: Int2Type is not a template

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(732): error: identifier "PtxVersion" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(740): error: SearchTransform is not a template

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(740): error: identifier "LevelT" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(740): error: expected an expression

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(758): error: identifier "MAX_PRIVATIZED_SMEM_BINS" is undefined

    /home/pcd/software/cub-1.10.0/cub/device/dispatch/dispatch_histogram.cuh(763): error: identifier "DeviceHistogramInitKernel" is undefined

    Error limit reached.

**Comment by panchangda** [comment]
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
# packages in environment at /home/pcd/software/anaconda3/envs/fx:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             4.5                       1_gnu
absl-py                   1.0.0                    pypi_0    pypi
astor                     0.8.1                    pypi_0    pypi
blas                      1.0                         mkl
bzip2                     1.0.8                h7b6447c_0
ca-certificates           2021.10.8            ha878542_0    conda-forge
cached-property           1.5.2                    pypi_0    pypi
certifi                   2016.9.26                py36_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
cudatoolkit               11.1.74              h6bb024c_0    nvidia
cycler                    0.11.0                   pypi_0    pypi
dataclasses               0.8                pyh4f3eec9_6
decorator                 4.4.2                    pypi_0    pypi
dlib                      19.23.0                  pypi_0    pypi
face-alignment            1.1.1                    pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
freetype                  2.11.0               h70c0345_0
fvcore                    0.1.5.post20210915            py36    fvcore
gast                      0.2.2                    pypi_0    pypi
gmp                       6.2.1                h2531618_2
gnutls                    3.6.15               he1e5248_0
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.44.0                   pypi_0    pypi
h5py                      3.1.0                    pypi_0    pypi
imageio                   2.15.0                   pypi_0    pypi
importlib-metadata        4.8.3                    pypi_0    pypi
importlib-resources       5.4.0                    pypi_0    pypi
intel-openmp              2022.0.1          h06a4308_3633
iopath                    0.1.9                      py36    iopath
joblib                    1.1.0                    pypi_0    pypi
jpeg                      9d                   h7f8727e_0
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.3.1                    pypi_0    pypi
lame                      3.100                h7b6447c_0
lcms2                     2.12                 h3be6417_0
ld_impl_linux-64          2.35.1               h7274673_9
libffi                    3.3                  he6710b0_2
libgcc-ng                 9.3.0               h5101ec6_17
libgomp                   9.3.0               h5101ec6_17
libiconv                  1.15                 h63c8f33_5
libidn2                   2.3.2                h7f8727e_0
libpng                    1.6.37               hbc83047_0
libstdcxx-ng              9.3.0               hd4cf53a_17
libtasn1                  4.16.0               h27cfd23_0
libtiff                   4.2.0                h85742a9_0
libunistring              0.9.10               h27cfd23_0
libuv                     1.40.0               h7b6447c_0
libwebp-base              1.2.2                h7f8727e_0
lz4-c                     1.9.3                h295c915_1
markdown                  3.3.6                    pypi_0    pypi
matplotlib                3.3.4                    pypi_0    pypi
mkl                       2020.2                      256
mkl-service               2.3.0            py36he8ac12f_0
mkl_fft                   1.3.0            py36h54f3939_0
mkl_random                1.1.1            py36h0573a6f_0
ncurses                   6.3                  h7f8727e_2
nettle                    3.7.3                hbbd107a_1
networkx                  2.5.1                    pypi_0    pypi
ninja                     1.10.2               h5e70eb0_2
numpy                     1.19.2           py36h54aff64_0
numpy-base                1.19.2           py36hfa32c7d_0
nvidiacub                 1.10.0                        0    bottler
olefile                   0.46                     py36_0
opencv-python             4.5.5.62                 pypi_0    pypi
openh264                  2.1.1                h4ff587b_0
openjpeg                  2.4.0                h3ad879b_0
openssl                   1.1.1m               h7f8727e_0
pillow                    8.4.0                    pypi_0    pypi
pip                       21.2.2           py36h06a4308_0
portalocker               1.4.0                      py_0    conda-forge
protobuf                  3.19.4                   pypi_0    pypi
pyparsing                 3.0.7                    pypi_0    pypi
python                    3.6.13               h12debd9_1
python-dateutil           2.8.2                    pypi_0    pypi
pytorch-mutex             1.0                        cuda    pytorch
pywavelets                1.1.1                    pypi_0    pypi
pyyaml                    5.1.2            py36h516909a_1    conda-forge
readline                  8.1.2                h7f8727e_1
scikit-image              0.17.2                   pypi_0    pypi
scikit-learn              0.24.2                   pypi_0    pypi
scipy                     1.5.4                    pypi_0    pypi
setuptools                58.0.4           py36h06a4308_0
six                       1.16.0             pyhd3eb1b0_1
sqlite                    3.37.2               hc218d9a_0
tabulate                  0.8.9              pyhd8ed1ab_0    conda-forge
tensorboard               1.14.0                   pypi_0    pypi
tensorflow-estimator      1.14.0                   pypi_0    pypi
tensorflow-gpu            1.14.0                   pypi_0    pypi
termcolor                 1.1.0                      py_2    conda-forge
threadpoolctl             3.1.0                    pypi_0    pypi
tifffile                  2020.9.3                 pypi_0    pypi
tk                        8.6.11               h1ccaba5_0
torch                     1.8.0+cu111              pypi_0    pypi
torchaudio                0.8.0                    pypi_0    pypi
torchvision               0.9.0+cu111              pypi_0    pypi
tqdm                      4.63.0             pyhd8ed1ab_0    conda-forge
typing_extensions         3.10.0.2           pyh06a4308_0
werkzeug                  2.0.3                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0
wrapt                     1.13.3                   pypi_0    pypi
xz                        5.2.5                h7b6447c_0
yacs                      0.1.8              pyhd8ed1ab_0    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zipp                      3.6.0                    pypi_0    pypi
zlib                      1.2.11               h7f8727e_4
zstd                      1.4.9                haebb681_0

**Comment by panchangda** [comment]
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 511.65       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0  On |                  N/A |
| N/A   41C    P8    14W /  N/A |   1348MiB /  6144MiB |      6%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by panchangda** [comment]
Python 3.6  PyTorch 1.8.0+cu113 
gcc & g++ 9.3.0
fvcore & ioPath installed
WSL2 ubuntu 20.04
if i installed with conda
the output result will be 
The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - feature:|@/linux-64::__glibc==2.31=0

Your installed version is: 2.31

**Comment by bottler** [comment]
Something has gone very wrong with the compilation. Perhaps a C or C++ compiler is trying to compile CUDA code. How did you run the compilation? What do you get when you type `nvcc --version`?

**Comment by panchangda** [comment]
> Something has gone very wrong with the compilation. Perhaps a C or C++ compiler is trying to compile CUDA code. How did you run the compilation? What do you get when you type `nvcc --version`?

thx for ur reply
the output of  `nvcc --version` is:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Thu_Feb_10_18:23:41_PST_2022
Cuda compilation tools, release 11.6, V11.6.112
Build cuda_11.6.r11.6/compiler.30978841_0

**Comment by panchangda** [comment]
> Something has gone very wrong with the compilation. Perhaps a C or C++ compiler is trying to compile CUDA code. How did you run the compilation? What do you get when you type `nvcc --version`?

But isn't the cuda already installed by `conda install -c cudatoolkit=11.1` ?

**Comment by panchangda** [comment]
> Something has gone very wrong with the compilation. Perhaps a C or C++ compiler is trying to compile CUDA code. How did you run the compilation? What do you get when you type `nvcc --version`?

As for my CUDA-11.6 *outside* the *anaconda env* I'm using,
I followed the instruction on *CUDAToolkit official website*
`wget https://developer.download.nvidia.com/compute/cuda/11.6.1/local_installers/cuda_11.6.1_510.47.03_linux.run`
&
`sudo sh cuda_11.6.1_510.47.03_linux.run`

**Comment by panchangda** [comment]
> > Something has gone very wrong with the compilation. Perhaps a C or C++ compiler is trying to compile CUDA code. How did you run the compilation? What do you get when you type `nvcc --version`?
> 
> As for my CUDA-11.6 **outside** the **anaconda env** I'm using, I followed the instruction on **CUDAToolkit official website** `wget https://developer.download.nvidia.com/compute/cuda/11.6.1/local_installers/cuda_11.6.1_510.47.03_linux.run` & `sudo sh cuda_11.6.1_510.47.03_linux.run`
and configure my ~/.bashrc as well

**Comment by panchangda** [comment]
I update my cub folder from **cub-1.10.0**  to  **cub-cuda-11.6**, and successfully build pytorch3d

**Comment by SavvaI** [comment]
> cub-cuda-11.6

Can you please tell, where/which conda channel did you use to get cub-cuda-11.6?

**Comment by Wecombo** [comment]
Succeed to build under cuda 11.6 by using cub 1.15.0 downloaded from official repo.
