### ISSUE TITLE
Can't import MeshRendererWithFragments

### ISSUE THREAD

**Issue by aja9675** [facebookresearch/pytorch3d#1098]
## 🐛 Bugs / Unexpected behaviors
Can't import MeshRendererWithFragments

## Instructions To Reproduce the Issue:
from pytorch3d.renderer import MeshRendererWithFragments

Error message:
ImportError: cannot import name 'MeshRendererWithFragments' from 'pytorch3d.renderer.mesh'

This patch fixed the issue for me:
[MeshRendererWithFragments.txt](https://github.com/facebookresearch/pytorch3d/files/8162762/MeshRendererWithFragments.txt)

**Comment by bottler** [comment]
Yes, indeed. This class is not exported at higher levels. You can use it with

```
from pytorch3d.renderer.mesh.renderer import MeshRendererWithFragments
```

**Comment by aja9675** [comment]
So this is intentional?

**Comment by aja9675** [comment]
Correct, it's not blocking me. I just assumed it was an oversight and should be fixed. If that's not the case, we can close the issue.

**Comment by gkioxari** [comment]
Feel free to submit a pull request. And thank you for bringing it up!
