### ISSUE TITLE
Missing the data of 10014_dolphin_v2_max2011_it2.obj

### ISSUE THREAD

**Issue by Robonchu** [facebookresearch/pytorch3d#11]
I cannot see the data of `10014_dolphin_v2_max2011_it2.obj` in `pytorch3d/docs/tutorials/data` for the tutorial(deform_source_mesh_to_target_mesh.ipynb).
Maybe forget to upload??

**Comment by gkioxari** [comment]
As the comments suggest, you should download the data
```
# e.g. download https://free3d.com/3d-model/-dolphin-v1--12175.html and save in ./data/dolphin
```
We are not allowed to redistribute the models. But the model is free, so you should be able to download it yourself.

**Comment by Robonchu** [comment]
Thanks!
I found the typo in the tutorial such as `/data/doplhin`  (<- `/data/dolphin`) in the [4].
Should I make PR?
