### ISSUE TITLE
Bug when loading ply mesh from open3d

### ISSUE THREAD

**Issue by dalnoguer** [facebookresearch/pytorch3d#1104]
Problem loading ply mesh. Triangle faces expected in int32 type. However, when parsed from the ply the resulting array is uint32.

This is the original line: https://github.com/facebookresearch/pytorch3d/blob/main/pytorch3d/io/ply_io.py#L1043

Git diff
```
# original line
faces = torch.LongTensor(np.vstack(face_arrays))

# fix
faces = torch.LongTensor(np.vstack(face_arrays).astype(np.int32))
```

Let me know what you thing about the fix.

Thanks!

**Comment by bottler** [comment]
Makes sense. I think this means you have a PLY file where face vertices have a declared type "uint" or "uint32", whereas the ones I've seen typically have type "int" like "property list uchar int vertex_index".  Can you share the header of the PLY file you are looking at, and perhaps say where it came from?

There might be other lines where the same fix is needed. (It would be slightly cleaner to convert to `np.int64`, although this only matters if there are more than `2**31` verts, which is unlikely.)

**Comment by dalnoguer** [comment]
Thanks for the reply.

Here is the header:

```
ply
format binary_little_endian 1.0
comment Created by Open3D
element vertex 57504
property double x
property double y
property double z
property double nx
property double ny
property double nz
property uchar red
property uchar green
property uchar blue
element face 112878
property list uchar uint vertex_indices
end_header
```

**Comment by bottler** [comment]
If you want to create a PR for this with a simple test let us know and that would be great. Although the data where this is relevant is binary, I think it's good enough to create an ascii example in the test because the logic which needs to change is shared. An example can just have 3 vertices and 1 face.

Or otherwise let us know we can make the change.
