### ISSUE TITLE
Render image with background image

### ISSUE THREAD

**Issue by ZhengyiLuo** [facebookresearch/pytorch3d#111]
## 🚀 Feature
Would it be possible for us to specify a background image to be rendered as the background for the mesh image?

## Motivation
It would be great if we can render meshes with background images and have it directly in the renderer instead of rendering two images (foreground + background) and then blend with a background image (not sure if this is the correct way to do). 

## Pitch

Rendering with background would be great if rendered mesh is input for RGB based deep learning methods.

**Comment by nikhilaravi** [comment]
@ZhengyiLuo thanks for suggesting this feature. It is in the roadmap for our next major release which is scheduled for April.

**Comment by ZhengyiLuo** [comment]
Thanks a ton! Looking forward to it!

**Comment by AnkaChan** [comment]
Hi,
I am also expecting this functionality for my project, however, it hasn't come yet. I did find it in April's release. 
Is it still on the road map?

**Comment by nikhilaravi** [comment]
This functionality was added in 65620e7. We haven't yet included it in an anaconda package release but it is available on master.

**Comment by fabienbaradel** [comment]
@nikhilaravi thanks for adding this feature, that's could be very useful. Would it be possible to give a quick demo code? Thanks.

**Comment by YuxuanSnow** [comment]
Hi all,

you can use the [H, W, 3] image as the background image. The background image is an RGB image with pixel value in range [0, 1] .

`blend_params = BlendParams(sigma=1e-4, gamma=1e-4, background_color=background/255)`

**Comment by shahaamirbader** [comment]
Hey YuxuanSnow,

I am stuck in a similar problem. My issue is posted here https://github.com/facebookresearch/pytorch3d/issues/1164. Can you elaborate as to how a back ground image can be included as [H,W,3] ? Is that different from using cv2.imread?
