### ISSUE TITLE
PointRenderer rasterizer per-point radius bug

### ISSUE THREAD

**Issue by ray8828** [facebookresearch/pytorch3d#1111]
The rasterizer's radius can be per-point, but the PointRenderer still uses this radius as a float.

```python
def forward(self, point_clouds, **kwargs) -> torch.Tensor:
        fragments = self.rasterizer(point_clouds, **kwargs)

        # Construct weights based on the distance of a point to the true point.
        # However, this could be done differently: e.g. predicted as opposed
        # to a function of the weights.
        r = self.rasterizer.raster_settings.radius

        dists2 = fragments.dists.permute(0, 3, 1, 2)
        weights = 1 - dists2 / (r * r)
        images = self.compositor(
            fragments.idx.long().permute(0, 3, 1, 2),
            weights,
            point_clouds.features_packed().permute(1, 0),
            **kwargs,
        )

        # permute so image comes at the end
        images = images.permute(0, 2, 3, 1)

        return images
```

`weights = 1 - dists2 / (r * r)`  if we set per-point radius in the rasterizer settings, then here will report shape mismatch error

**Comment by ray8828** [comment]
Following modification can fix this bug:

```python
fragments = rasterizer(point_cloud)
r = rasterizer.raster_settings.radius

if isinstance(r, torch.Tensor):
    idx = fragments.idx.long()
    r = r[0][idx.reshape(-1)].reshape(idx.shape)
    r = r.permute(0,3,1,2)

dists2 = fragments.dists.permute(0, 3, 1, 2)
weights = 1 - dists2 / (r * r)
```

**Comment by gkioxari** [comment]
`self.rasterizer.raster_settings.radius` is expect to be a scalar. You probably provided it as a tensor of some shape. You don't provide the code for it, so I can't know for sure. But if you set radius to be a `scalar` no shape mismatch should happen.

**Comment by ZhaoyangZh** [comment]
https://github.com/facebookresearch/pytorch3d/blob/c3c4495c7ac8181be47e49ed2bc935d340e47981/pytorch3d/renderer/points/rasterizer.py#L25-L53

I am having exactly the same issue when rendering point clouds with varying radius per point. The docstring here said that `radius` could be a `torch.Tensor` with shape `[N, P]`.

**Comment by ZhaoyangZh** [comment]
> Following modification can fix this bug if batchsize=1
> 
> ```python
> fragments = rasterizer(point_cloud)
> r = rasterizer.raster_settings.radius
> 
> if isinstance(r, torch.Tensor):
>     idx = fragments.idx.long()
>     r = r[0][idx.reshape(-1)].reshape(idx.shape)
>     r = r.permute(0,3,1,2)
> 
> dists2 = fragments.dists.permute(0, 3, 1, 2)
> weights = 1 - dists2 / (r * r)
> ```

Hi, I found that `idx` could be `-1` which I think indicates that there are less than `points_per_pixel` points visible in that pixel. In this situation, I think `r[0][idx.reshape(-1)]` would be problematic, since index `-1` simply returns the last value of `r[0]`, which does not make sense.

I tried to allow `batch_size != 1` and successfully use the following code to produce my expected results.

```python
if isinstance(r, torch.Tensor):
    index = fragments.idx.long()
    flatten_index = index.reshape(-1)
    flatten_r = r.reshape(-1)
    N, P = r.shape
    H, W = dists2.shape[-2:]
    flatten_r = torch.cat([flatten_r, torch.tensor([0]).cuda()], dim=0)
    flatten_index = torch.where(flatten_index == -1, flatten_r.shape[0] - 1, flatten_index)
    r = torch.index_select(input=flatten_r, dim=0, index=flatten_index).reshape(N, H, W, -1).permute(0, 3, 1, 2)
```

My idea is to let invisible points' radius to be `0`. Since `torch.index_select` does not support negative indexing, I use `flatten_index = torch.where(flatten_index == -1, flatten_r.shape[0] - 1, flatten_index)` instead. It may looks a little bit messy, but I hope you will find it useful.

Any further discussion is welcomed.
