### ISSUE TITLE
Meshes without light?

### ISSUE THREAD

**Issue by ZhengdiYu** [facebookresearch/pytorch3d#1112]
## ❓ Questions on how to use PyTorch3D

Hi, I was wondering why my meshes are all white without lights and shadow
![image](https://user-images.githubusercontent.com/63605407/157497256-008e1b49-f132-47db-9552-704d103c6b44.png)

The mesh coordinate range is 
![image](https://user-images.githubusercontent.com/63605407/157497685-6e3675d6-4c9a-4e5f-8042-b19452888dc4.png)

The renderer is set:
```
        if R is None:
            R = torch.Tensor([[[1., 0., 0.], [0., 1., 0.], [0., 0., 1.]]])
        if T is None:
            T = torch.Tensor([[0., 0., 0.]])

        if self.perps:
            self.cameras = FoVPerspectiveCameras(R=R, T=T, fov=60, device=self.device)
            self.lights = PointLights(ambient_color=((0.56, 0.56, 0.56),),location=torch.Tensor([[0., 0., 0.]]), device=self.device)
        else:
            self.cameras = FoVOrthographicCameras(R=R, T=T, znear=0., zfar=100.0, max_y=1.0, min_y=-1.0, max_x=1.0, min_x=-1.0, device=self.device)
            self.lights = DirectionalLights(direction=torch.Tensor([[0., 1., 0.]]), device=self.device)

        # Define the settings for rasterization and shading. Here we set the output image to be of size
        # 512x512. As we are rendering images for visualization purposes only we will set faces_per_pixel=1
        # and blur_radius=0.0. 
        raster_settings = RasterizationSettings(
            image_size=resolution[0], 
            blur_radius=0.0, 
            faces_per_pixel=1)

        # Create a Phong renderer by composing a rasterizer and a shader. The textured Phong shader will 
        # interpolate the texture uv coordinates for each vertex, sample from a texture image and 
        # apply the Phong lighting model
        self.renderer = MeshRenderer(
            rasterizer=MeshRasterizer(
                cameras=self.cameras, 
                raster_settings=raster_settings),
            shader=SoftPhongShader(
                device=self.device,
                cameras=self.cameras,
                lights=self.lights))
```
ideally it should be like this:
![image](https://user-images.githubusercontent.com/63605407/157499578-7b6091a5-41db-4234-8213-b429184cf984.png)

**Comment by gkioxari** [comment]
Where is the light source compared to your mesh? Maybe you need to play with the location. 

Also, why does your image have subtle code in the background. So confused :P

**Comment by ZhengdiYu** [comment]
> Where is the light source compared to your mesh? Maybe you need to play with the location.
> 
> Also, why does your image have subtle code in the background. So confused :P



About the question, I think it I misunderstood it. It's not rendering without light, instead, it's like there is an invisible wall in the image plane. Sometime just like this
![image](https://user-images.githubusercontent.com/63605407/158042995-1c74ab4c-2846-47c4-a9cf-b0f14bf5a544.png)


I'm new to pytorch3d so I don't know what's happening yet. Is this due to the camera location or something?

And about the code in the background. haha it's because I have altered my vscode's  opacity so I can see through it.

**Comment by ZhengdiYu** [comment]
Oh, Thanks, I have fixed this by editing FOV. However I just randomly tried some numbers to get it work.
