### ISSUE TITLE
Questions on box3d_overlap

### ISSUE THREAD

**Issue by DianChen-TRI** [facebookresearch/pytorch3d#1113]
## ❓ Questions on how to use PyTorch3D

Hi! I have two quick questions regarding `pytorch3d.ops.box3d_overlap`:

1. Can I use it for arbitrarily posed boxes? In other words, does it assume boxes to be axis-aligned?
2. Is it differentiable, meaning I can use it for calculating loss?

Thank you!

**Comment by gkioxari** [comment]
> Can I use it for arbitrarily posed boxes? In other words, does it assume boxes to be axis-aligned?

No, boxes need not be axis aligned. They can be posed or skewed

> Is it differentiable, meaning I can use it for calculating loss?

We don't have support for differentiability yet.
