### ISSUE TITLE
BlenderCamera used in R2N2().render() does not implement in_ndc() and is_perspective()

### ISSUE THREAD

**Issue by Xie-Fangyuan** [facebookresearch/pytorch3d#1118]
In the customized `render()` function of the R2N2 dataset, a `BlenderCamera` is used to render images, which inherits from `CamerasBase` but does not implement the `in_ndc()` and `is_perspective()` functions, thereby `NotImplementedError`s are raised.

I checked other `Cameras` classes inheriting from `CamerasBase`, and found they all implement the `in_ndc()` and `is_perspective()`. Hope this issue can be fixed.

**Comment by bottler** [comment]
That looks like a good change (for this and #1115). Can you make it a PR against this repo? At the moment it is just a PR on your own fork, which you might not have intended.

**Comment by Xie-Fangyuan** [comment]
> That looks like a good change (for this and #1115). Can you make it a PR against this repo? At the moment it is just a PR on your own fork, which you might not have intended.

I made the PR again, but there is one test failed when pulling the docker image. I have no idea how to fix this. Can you check it?

**Comment by bottler** [comment]
Thanks - I'll take a look.
