### ISSUE TITLE
Python 3.9, CUDA 11.1 and Pytorch 1.9.0 - py39_cu111_pyt190, no prebuilt wheel for Linux

### ISSUE THREAD

**Issue by apolinario** [facebookresearch/pytorch3d#1119]
The URL `https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py39_cu111_pyt190/download.html` doesn't exist for the above settings

**Comment by bottler** [comment]
Yes. The main binaries for linux are via conda. The wheels are made available for the combinations of dependencies which might get used by google Colab, which was already on PyTorch 1.10.0 at the time of the last release.

**Comment by patricklabatut** [comment]
Closing. @bottler Maybe the installation [documentation](https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md#3-install-wheels-for-linux) could be more explicit and indicate what is / what is not supported and stress that conda is strongly preferred for Linux.
