### ISSUE TITLE
Rendering using batch size > 1 scales compute time linearly

### ISSUE THREAD

**Issue by dalnoguer** [facebookresearch/pytorch3d#1120]
Hello everyone,

I am rendering silhouettes to obtain segmentation masks. However, when rendering in batches, computation time takes batch_size times longer. I assume it should take a bit longer but not scale linearly. Here is the code I used.

```
T = np.array(cam_params["extrinsics"])

# torch3d uses left-up-front vs colmap right-down-front
# We need to convert local camera coordinate system
torch3d_T_colmap = np.array([[-1, 0, 0], [0, -1, 0], [0, 0, 1]])
R, t = T[:3, :3], T[:3, 3]
R = (torch3d_T_colmap @ R).T
t = torch3d_T_colmap @ t

R = torch.Tensor(R).unsqueeze(0)
t = torch.Tensor(t).unsqueeze(0)

R = R.repeat(self.batch_size, 1, 1)
t = t.repeat(self.batch_size, 1)

# Generate Perspective Cameras
K = np.array(cam_params["intrinsics"]) / self.resize_factor
fx, fy, px, py = K[0, 0], K[1, 1], K[0, 2], K[1, 2]
image_size = (
    cam_params["width"] // self.resize_factor,
    cam_params["height"] // self.resize_factor,
)
cameras = pytorch3d.renderer.PerspectiveCameras(
    device="cuda",
    R=R,
    T=t,
    focal_length=((fx, fy),),
    principal_point=((px, py),),
    in_ndc=False,
    image_size=(image_size,),
)

# Rasterization settings for silhouette rendering
raster_settings_silhouette = pytorch3d.renderer.RasterizationSettings(
    image_size=image_size,
)

# Silhouette renderer
renderer_silhouette = pytorch3d.renderer.MeshRenderer(
    rasterizer=pytorch3d.renderer.MeshRasterizer(
        cameras=cameras, raster_settings=raster_settings_silhouette
    ),
    shader=pytorch3d.renderer.SoftSilhouetteShader(),
)

# Render segmentation mask
masks = renderer_silhouette(obj_mesh, cameras=cameras)[..., 3]
masks[masks > 0] = 255  # Binarize segmentation mask
```

In this example I just repeat the Transformations in the batch dimension. 

When using `batch_size = 1` it takes around 1 second per iteration. Then, when using `batch_size = 3` it takes 3s.

What am I doing wrong?

Thanks!

**Comment by gkioxari** [comment]
To echo @bottler, are you timing the run of the whole code you provide or just the renderer? Your code does more things than just rendering so you should profile it properly before you report runs. 

It would also good if you cleaned up your code. For example `R = torch.Tensor(R).unsqueeze(0)` is in CPU but you define `device="cuda"` in the renderer, which means that things need to be transferred to GPU within the `cameras`.
