### ISSUE TITLE
Question on silhouette for Point Clouds

### ISSUE THREAD

**Issue by Yang-L1** [facebookresearch/pytorch3d#1121]
## ❓ Questions on how to use PyTorch3D

Hi! I want to render a silhouette image for point clouds and compute silhouette loss. Is this dorable for the current PyTorch3D?

Thank you!

**Comment by gkioxari** [comment]
Please see the tutorials, e.g. https://github.com/facebookresearch/pytorch3d/blob/main/docs/tutorials/render_colored_points.ipynb

**Comment by Yang-L1** [comment]
Thanks for the reply. Is this silhouette differentiable? As I noticed that in the mesh case, it has a SoftSilhouetteShader.

**Comment by gkioxari** [comment]
Yes. With point clouds you use compositing. Please read the code in the tutorial. All the information is available.

**Comment by tigogogo** [comment]
> ## ❓ Questions on how to use PyTorch3D
> Hi! I want to render a silhouette image for point clouds and compute silhouette loss. Is this dorable for the current PyTorch3D?
> 
> Thank you!

Hi, bro, have you found a way to render a silhouette image for point clouds? I have the same problem. Would you mind telling me your methods? Thanks a lot.

**Comment by Yang-L1** [comment]
I basically followed this tutorial https://github.com/facebookresearch/pytorch3d/blob/main/docs/tutorials/render_colored_points.ipynb
Just set the point cloud to white and background to black.
Then you can render a silhouette which is differentiable.

**Comment by tigogogo** [comment]
> 
Thank you very much, bro. So just concatenate an array of constant 1 and point coordinates to [x,y,z,1], and then render them? But the released two kinds of compositing methods, Alpha and NormWeight,  seem not suitable for rendering silhouette images. According to the paper, "Accelerating 3D Deep Learning with PyTorch3D", Equation 2, the former involves depth which is useless in the silhouette rendering task. The latter will always get pixels with value 1 if we set the point cloud feature to 1.


>
