### ISSUE TITLE
How to Define THRUST_IGNORE_CUB_VERSION_CHECK? Installaton on windows

### ISSUE THREAD

**Issue by tradenity** [facebookresearch/pytorch3d#1123]
Hi

I am trying to install on windows with the following configuration

Windows 10
using conda environment
python 3.7
pytorch3d master branch
pytorch=1.11.0
cudatoolkit=11.3 (I have RTX 3060 card)
CUB_HOME set correctly with lib source ver. 1.16.0
MSVC 2019 setup correctly
removed c++14 references from setup.py

When I run setup install or "pip install -e ."
I get the following error

```
C:/Users/Joseph/.conda/envs/adnerf/Library/include\thrust/system/cuda/config.h(78): fatal error C1189: #error:  The version of CUB in your include path is not compatible with this release of Thrust. CUB is now included in the CUDA Toolkit, so you no longer need to use your own checkout of CUB. Define THRUST_IGNORE_CUB_VERSION_CHECK to ignore this.
    ball_query.cu
```

So How to Define THRUST_IGNORE_CUB_VERSION_CHECK? or how to resolve the issue?
I tried change setup.py
define_macros += [("THRUST_IGNORE_CUB_VERSION_CHECK", True)]
or
define_macros += [("THRUST_IGNORE_CUB_VERSION_CHECK", 1)]

with no luck, same error

Thanks

**Comment by bottler** [comment]
Either of those lines should be fine, because the [check inside thrust](https://github.com/NVIDIA/thrust/blob/main/thrust/system/cuda/config.h#L75) is just looking at whether the variable is defined. Maybe the easiest thing to try is to build with CUB_HOME not set and thereby use the built-in cub.

**Comment by Junking1** [comment]
I solved this problem by change the C:/Users/Joseph/.conda/envs/adnerf/Library/include\thrust/system/cuda/config.h：

// #ifndef THRUST_IGNORE_CUB_VERSION_CHECK
// #include <thrust/version.h>
// #include <cub/util_namespace.cuh> // This includes <cub/version.cuh> in newer releases.
// #if THRUST_VERSION != CUB_VERSION
// #error The version of CUB in your include path is not compatible with this release of Thrust. CUB is now included in the CUDA Toolkit, so you no longer need to use your own checkout of CUB. Define THRUST_IGNORE_CUB_VERSION_CHECK to ignore this.
// #endif
// #endif

**Comment by Mynuddin-dev** [comment]
don't need change anything . just add 
def THRUST_IGNORE_CUB_VERSION_CHECK true

in config.h file before this line
// #ifndef THRUST_IGNORE_CUB_VERSION_CHECK

**Comment by poeiradonorte** [comment]
> Reference in new

in addition, I also need to comment out the line:

“#else  THRUST_IGNORE_CUB_VERSION_CHECK”

and it's working perfectly!

**Comment by poeiradonorte** [comment]
> Hi
> 
> I am trying to install on windows with the following configuration
> 
> Windows 10 using conda environment python 3.7 pytorch3d master branch pytorch=1.11.0 cudatoolkit=11.3 (I have RTX 3060 card) CUB_HOME set correctly with lib source ver. 1.16.0 MSVC 2019 setup correctly removed c++14 references from setup.py
> 
> When I run setup install or "pip install -e ." I get the following error
> 
> ```
> C:/Users/Joseph/.conda/envs/adnerf/Library/include\thrust/system/cuda/config.h(78): fatal error C1189: #error:  The version of CUB in your include path is not compatible with this release of Thrust. CUB is now included in the CUDA Toolkit, so you no longer need to use your own checkout of CUB. Define THRUST_IGNORE_CUB_VERSION_CHECK to ignore this.
>     ball_query.cu
> ```
> 
> So How to Define THRUST_IGNORE_CUB_VERSION_CHECK? or how to resolve the issue? I tried change setup.py define_macros += [("THRUST_IGNORE_CUB_VERSION_CHECK", True)] or define_macros += [("THRUST_IGNORE_CUB_VERSION_CHECK", 1)]
> 
> with no luck, same error
> 
> Thanks

 find the line containing the following statement
“#ifndef THRUST_IGNORE_CUB_VERSION_CHECK”

add this command above the previous line
“#define THRUST_IGNORE_CUB_VERSION_CHECK true”

and uncomment the line
“#else THRUST_IGNORE_CUB_VERSION_CHECK”

and it's working perfectly!
