### ISSUE TITLE
How to cut a new 2D mesh from a generated 2D mesh by mask?

### ISSUE THREAD

**Issue by DRosemei** [facebookresearch/pytorch3d#1126]
## ❓ Questions on how to use PyTorch3D

I want to know how to cut a new 2D mesh from a generated 2D mesh by mask, We need verts and faces to construct meshes.  It is easy to cut faces from mask, while how to cut verts that are correspond to faces is not so easy. Have you implemented some tools? Thanks in advance!

**Comment by bottler** [comment]
The new submesh() function on Meshes may help.
