### ISSUE TITLE
Wrong point cloud rendering on NVidia RTX3060 GPU

### ISSUE THREAD

**Issue by IlliaOvcharenko** [facebookresearch/pytorch3d#1129]
Code is pretty much the same as in [point cloud rendering tutorial](https://github.com/facebookresearch/pytorch3d/blob/main/docs/tutorials/render_colored_points.ipynb).

I tested it with several GPU options: NVidia P600 (cuda version 11.3), NVidia RTX3060 (cuda version 11.2) and CPU only.
The result I get using NVidia RTX3060 is quite unexpected and looks wrong.

**Code**: https://gist.github.com/IlliaOvcharenko/4cdbafc0188b6c38d49ac0277e35f0e2
**Data**: https://drive.google.com/file/d/1EtM__56rvu6h1QXvL7yKj4-ruPiSMu0b/view?usp=sharing
**Env**: 
```
fire==0.4.0
fvcore==0.1.5.post20220305
iopath==0.1.9
laspy==2.1.2
laszip==0.1.0
matplotlib==3.5.1
numpy==1.21.5
opencv-python-headless==4.5.5.64
pandas==1.3.5
pytorch3d==0.6.1
torch==1.10.2+cu111
torchvision==0.11.3+cu111
tqdm==4.63.0
``` 
Result on **NVidia P600 and CPU**:
![name=render-custom-pc-device=cuda-time=17-03-20-13-22](https://user-images.githubusercontent.com/22120875/158879115-fdd8d2f9-b234-44f1-8b8e-4db73f664432.png)

Result on **NVidia RTX3060** (which looks wrong):
![name=render-custom-pc-device=cuda-time=17-03-20-12-03](https://user-images.githubusercontent.com/22120875/158879250-ed2c907a-4610-4496-ad23-7e00983fe7b1.png)

**Could be related issues**: https://github.com/facebookresearch/pytorch3d/issues/963 and https://github.com/facebookresearch/pytorch3d/issues/559

**Comment by IlliaOvcharenko** [comment]
@bottler

**Comment by bottler** [comment]
I don't have a good idea. Can you try setting `bin_size` to -1 in the `RasterizationSettings`? I wonder if nondeterminism as a result of overflow in the coarse-to-fine rasterization is the difference between the machines.

**Comment by IlliaOvcharenko** [comment]
Thank you for a response!

I got an exception when set ```bin_size``` to -1 one, so i think it is not a valid value for that parameter:
```
RuntimeError: Trying to create tensor with negative dimension -510: [1, -510, -510]
```

As I understand from docs, ```bin_size``` equal to 0 whould turn off coarse-to-fine rasterization, but I got the same wrong rasterization result with zero value too.

**Comment by gkioxari** [comment]
This is interesting. So you are running the same code but on different GPUs? Do you get the same discrepancy in outcomes when you run the tutorial (exactly as is on the data we provide and without any changes to the code)?

**Comment by jcjohnson** [comment]
This is a pretty unexpected result! I don't think this is related to https://github.com/facebookresearch/pytorch3d/issues/963 (since in that case the kernels wouldn't run at all and you should get some error message); it might be related to https://github.com/facebookresearch/pytorch3d/issues/559 (and also https://github.com/facebookresearch/pytorch3d/issues/448) but running with `bin_size=0` should fall back to naive rasterization which should't be subject to the overflow issue that causes https://github.com/facebookresearch/pytorch3d/issues/448, so maybe this is a different issue after all.

Do you see any different behavior or error messages if you set the environment variable `CUDA_LAUNCH_BLOCKING=1` before running your script?

**Comment by IlliaOvcharenko** [comment]
@gkioxari 
Some calrification for a description I provide before.

I started a developing on less powerful PC with NVidia P600 inside. All rendering looks fine. Then a switch to another PC with NVidia RTX3060. I copied my code and tried to replicate the same environment  I had before (same library versions), except a cuda version, which is different for those desktops. 

As I could see from a rendering results from RXT3060 GPU, the problem is with a wrong location of virtual camera. It could be not absolutly clear from images i provide above, but on a render,  the overall scene is located far away from a camera, shifted and rotated, not in a way I expect (and even differs form a results I get running this code on the same machine with CPU option). It is not just a missed part of rendering like in issues a linked in description. Also, as i tested later, small changes of R, T matricies do not move camera in some predictable way for that point cloud.

However, when I try to normalize a coordinate of a point cloud i use (xyz=0 represent a center point of a scene), and change transition matrix to see how those cnahges reflect on the direction how the camera moves, the result is the same on both machines I used.

So, I personaly dont get a moment when and in on what circumctences R, T matrices become processing in wrong way.


When i run a tutorail on RTX3060 i get ```UserWarning: R is not a valid rotation matrix``` but a result is the same as should be.

**Comment by IlliaOvcharenko** [comment]
@jcjohnson 
Setting ```CUDA_LAUNCH_BLOCKING=1``` did not change a result i get, there wasn`t any errors/warning in output.

**Comment by GiBucci** [comment]
Hi @IlliaOvcharenko, I found the same problem during one of my experiments, I am running on a NVIDIA RTX3060, it renders only a black image, it gives me the same `UserWarning: R is not a valid rotation matrix` and I can't figure out what is the problem.

Did you manage to solve this in any way?

Thank you in advance for your response.

**Comment by IlliaOvcharenko** [comment]
Hi @GiBucci! Unfortunately no, just switched to another GPU.
