### ISSUE TITLE
How to rendering the selected part of a mesh ? 

### ISSUE THREAD

**Issue by lith0613** [facebookresearch/pytorch3d#1132]
I have a mesh and a list of index corresponding to the vertex or triangle face. My question is how to render the selected index part of the mesh rather than the full mesh, any easy function can do this in pytorch3d ?  Thanks !

**Comment by gkioxari** [comment]
This does not appear to be an issue with the library but a question about your specific project. Could you please move this to the github discussion page rather than open an issue on the issues page. Thank you.
