### ISSUE TITLE
The pytorch3d_implicitron_runner file

### ISSUE THREAD

**Issue by greeneggsandyaml** [facebookresearch/pytorch3d#1140]
Hello PyTorch3D authors, 

Thank you for your great library. I am trying to reproduce some results using implicitron. 

It seems that the executable `pytorch3d_implicitron_runner` is missing. My apologies if I am asking about this prematurely (I realize that the implicitron code was only released recently), I just wanted to make sure that the file was not forgotten.

Thanks again and all the best.

**Comment by bottler** [comment]
It *is* the module `projects/implicitron_trainer/experiment.py`. We intend to change setup.py to add an entry point `pytorch3d_implicitron_runner` for that file.

**Comment by greeneggsandyaml** [comment]
Ah, I see! Apologies for the confusion, and thank you for the very quick response. I really appreciate it. 

I have a follow-up question, which I will post below, but since this question is answered, I am closing this issue.

**Comment by greeneggsandyaml** [comment]
My follow-up question was whether you currently provide functionality for multi-GPU training with implicitron. 

I am asking because some of the experiments (namely `repro_multiseq_nerformer`) seem to take a very long time. 

Specifically, when I run with the following command: 
```bash
python experiment.py --config-path configs --config-name repro_multiseq_nerformer dataset_args.dataset_root=$CO3D_DATASET_ROOT dataset_args.category="hydrant" test_when_finished=True exp_dir=outputs
```
I find that each iteration takes around 0.75 seconds (on an RTX 6000), which translates to a total of 2_250_000 steps (since the configuration specifies 1000 steps/epoch for 3000 epochs) which is approximately 26 days. 

This seems quite long, especially given that it is only for a single category. Is this correct, or should I be running a different command (or using multiple GPUs in some way)?
