### ISSUE TITLE
pickle error when saving implictron models

### ISSUE THREAD

**Issue by CoolChameleon** [facebookresearch/pytorch3d#1144]
I‘m just running projects/implicitron_trainer/experiment.py and I get the following error when an epoch ends and the code starts to save model:
![1648577163(1)](https://user-images.githubusercontent.com/23183849/160676606-c1ad8fbd-c144-415d-ac69-2c803df36e66.png)
I wonder why I got this error. Could it be inconsistent versions of some dependencies?

**Comment by bottler** [comment]
We can replicate this problem and we're discussing internally what to do about it. For the moment, rolling back to revision 8ac5e8 from 24 March should fix it.

**Comment by CoolChameleon** [comment]
> 
Thanks! This method works for me. Looking forward to the new version!

**Comment by bottler** [comment]
I hope this is fixed by https://github.com/fairinternal/pytorch3d/commit/518aa1f5cfe8f289c6a8dae09beb61624931934f.
