### ISSUE TITLE
Support for PyTorch 1.10.2

### ISSUE THREAD

**Issue by akshaygadipatil** [facebookresearch/pytorch3d#1146]
Hi folks,

Is there PyT3D support for PyTorch 1.10.2? Installation documentation says that the latest PyTorch version that is supported is 1.10.0, but wanted to check if there is support for more recent PyTorch versions. Thanks.

**Comment by bottler** [comment]
The nightly build (on Linux via conda) has builds for PyTorch 1.10.2 and 1.11.0, but they aren't included in the latest release (PyTorch3D 0.6.1).

**Comment by bottler** [comment]
The new release 0.6.2 has builds for PyTorch 1.10.2.
