### ISSUE TITLE
A question about obtaining  the depth map from a point cloud by using fragments.zbuf

### ISSUE THREAD

**Issue by pipi2500** [facebookresearch/pytorch3d#1147]
## A question about obtaining  the depth map from a point cloud by using `fragments.zbuf`

Thank you for publishing such a powerful tool!

As far as I understood, I can infer pixel depth from `fragments.zbuf`. I extend the **`PointsRenderer`** class to get the `fragments.zbuf` as described in https://github.com/facebookresearch/pytorch3d/issues/35. 
```
class PointsRenderer(nn.Module):
    def __init__(self, rasterizer, compositor) -> None:
        super().__init__()
        self.rasterizer = rasterizer
        self.compositor = compositor

    def forward(self, point_clouds, **kwargs) -> torch.Tensor:
        fragments = self.rasterizer(point_clouds, **kwargs)

        r = self.rasterizer.raster_settings.radius

        dists2 = fragments.dists.permute(0, 3, 1, 2)
        weights = 1 - dists2 / (r * r)
        images = self.compositor(
            fragments.idx.long().permute(0, 3, 1, 2),
            weights,
            point_clouds.features_packed().permute(1, 0),
            **kwargs,
        )

        # permute so image comes at the end
        images = images.permute(0, 2, 3, 1)

        return images, **fragments.zbuf**
```
I find that `fragments.zbuf` is a tensor with dims of (1,W,H,N). I know W and H represent the size of the image, but what is the meaning of N. 
I notice that N equals to `points_per_pixel` that I set in `PointsRasterizationSettings`.
```
    raster_settings = PointsRasterizationSettings(
        image_size=(height, width),
        radius=0.007,
        points_per_pixel=15,
    )
```
In this case, I set `points_per_pixel=15`. I print the 15 channels, and notice that each channel is slightly different. I visualize each channel as followings:

**`Channel 0`**:
![Screenshot from 2022-03-30 14-38-26](https://user-images.githubusercontent.com/102641867/160767615-2e7c586e-3786-4355-b6f6-7d8b88608b43.png)

**`Channel 1`**:
![Screenshot from 2022-03-30 14-43-44](https://user-images.githubusercontent.com/102641867/160768164-7a0e2946-ee36-431a-b830-73ac200f6f79.png)

**`Channel 2`**:
![Screenshot from 2022-03-30 14-49-24](https://user-images.githubusercontent.com/102641867/160769081-85df9d7c-7e6f-4b65-b762-692f8b4bb98e.png)

**`etc.`**

I wonder which channel represents the depth map of the point cloud. Thanks in advance for any reply.

**Comment by gkioxari** [comment]
@pipi2500 
I think it would be useful for you to understand what the outputs of the rasterizer are. This can be found here. 

https://github.com/facebookresearch/pytorch3d/blob/a54ad2b912891a9b22aa858c2daf93918e4bf5ed/pytorch3d/renderer/points/rasterize_points.py#L70-L89

`N=points_per_pixel` and the rasterizer returns the N closest points (in `Z` aka depth) hit by the ray originating at each pixel. So `zbuf[i,j,0]` should returns the depth of the closest point at. `zbuf[i, j, 1]` returns the depth second closest point etc.

**Comment by pipi2500** [comment]
@gkioxari 
Thanks for your reply.:) Now I have completely understood. 
Have a nice day.

**Comment by Jankin66** [comment]
I want to get the depth image from the pointcloud(w/o color) using pytorch3d rendering, would you mind providing a example for me. THANK YOU very much!
