### ISSUE TITLE
Parallel Training Needed plz

### ISSUE THREAD

**Issue by 87003697** [facebookresearch/pytorch3d#1149]
## 🚀 Feature

Hi, is  parallel training one of the features that you are working on ? Or when can we expect your realization support data parallel or even data distributed parallel? 

NOTE: Please look at the existing list of Issues tagged with the label ['enhancement`](https://github.com/facebookresearch/pytorch3d/issues?q=label%3Aenhancement). **Only open a new issue if you do not see your feature request there**.

## Pitch

NOTE: we only consider adding new features if they are useful for many users.

**Comment by bottler** [comment]
For implicitron, yes, this is something we are aiming for.

**Comment by kjchalup** [comment]
This should be already available in Implicitron, please take a look and reopen the issue with more explanation / a concrete use-case if the current functionality is not sufficient.
