### ISSUE TITLE
better support for pip install

### ISSUE THREAD

**Issue by AsaphLightricks** [facebookresearch/pytorch3d#1150]
## 🚀 Feature
allow installing pytorch3d with `pip install pytorch3d` for other OS (linux!) and with cuda support.

## Motivation

Currently, you can only `pip install` pytorch3d on macOS, and it only works with `pytorch==1.9.0` and it is CPU-only.
This hinders using pytorch3d as requirement for other packages. I want to use pytorch3d in a package, meant to be installed using pip, but right now it can't be used on linux, since you don't support pip install for linux. 

## Pitch

Make pytorch3d installable using pip on linux with support for GPU (for all torch versions)
Can you share when this will be available?

**Comment by bottler** [comment]
Sorry - this isn't going to change. It is deliberate that we use conda packages as our main distribution method. It allows us to have separate packages for separate builds of our dependencies, and enforces they are used correctly. It might be a good option for packaging your package.

There are though some Linux builds with pip with CUDA, if you look at the "Install wheels for Linux" section of INSTALL.md. This targets google colab, and it might help you too. A special command line is needed.
