### ISSUE TITLE
How to convert the camera parameters of NeRF's public dataset into the camera parameters supported by pytorch3D?

### ISSUE THREAD

**Issue by ghost** [facebookresearch/pytorch3d#1151]
I am using pytorch3D to do related work on NeRF recently. Is there a way to convert the camera parameters of NeRF's public dataset into the camera parameters supported by pytorch3D.

**Comment by gkioxari** [comment]
Please check out our project that implements NeRF and other models: https://github.com/facebookresearch/pytorch3d/tree/main/projects/implicitron_trainer

You should follow/read the instructions there to configure your system with the data you have!

**Comment by MatrixZzu** [comment]
> Hello, I found NeRF implemented by Pytorch3D, which provides processed public datasets and provides downloads as .path files, but does not provide a method for processing .path files

**Comment by patricklabatut** [comment]
Directly using public datasets for neural rendering is something we are actually looking into.

**Comment by AIBluefisher** [comment]
I'm implementing using pytorch3D to deal with public datasets, maybe I can create a PR later. May I know if there is any progress on this already?

**Comment by victkid** [comment]
It would be helpful to have a script that demonstrates the process of converting public datasets into a camera representation in PyTorch3D.
