### ISSUE TITLE
Questions on Point cloud prediction algorithm Point Align

### ISSUE THREAD

**Issue by tigogogo** [facebookresearch/pytorch3d#1160]
## ❓ Questions on how to use PyTorch3D
Hi, I have read your awesome paper '' Accelerating 3D Deep Learning with PyTorch3D''. In this paper, you have tested the Pytorch3D renderer on point cloud prediction task with your algorithm named Point Align. I cannot find the codes in this Github project. I wonder if the codes are available?

**Comment by gkioxari** [comment]
We haven't released code.
