### ISSUE TITLE
Overlay the 3D Model (.obj file) on top of a jpeg image

### ISSUE THREAD

**Issue by shahaamirbader** [facebookresearch/pytorch3d#1164]
## ❓ Questions on how to use PyTorch3D

**AIM**: Basically asking for something already discussed in https://github.com/facebookresearch/pytorch3d/issues/577. However, with concrete code that works. So my aim is to overlay the 3d object (.obj file) on top of a jpeg image, as shown in the figure in comment below (which I achieved using Paint 3D).  However, I would like to use pytorch3d in a python script to achieve the same results. 

**EFFORT UNDERTAKEN** Following the instructions in https://github.com/facebookresearch/pytorch3d/issues/577, I Amended the code in blender.py as follows. + made necessary changes in shader.py however the code still  produces output images with 3d object having a white background. I am unable to overlay the 3d object on top of the image path provided to the "BlendParams" class using cv2.  I have made sure the image size for output is same as the background image. Still no success. 
```
class BlendParams(NamedTuple):
    sigma: float = 1e-4
    gamma: float = 1e-4
    background_color: Sequence = (1.0, 1.0, 1.0)
    # add background image as a param here 
    background_image = cv2.imread('/homelocal/Angle-Finder/assets/AR_Images_4/image_0.jpeg')

def hard_rgb_blend(colors, fragments, blend_params) -> torch.Tensor:
    N, H, W, K = fragments.pix_to_face.shape
    device = fragments.pix_to_face.device

    # Mask for the background.
    is_background = fragments.pix_to_face[..., 0] < 0  # (N, H, W)

    if torch.is_tensor(blend_params.background_image):
        background_image = blend_params.background_image.to(device)
    else:
        background_image = colors.new_tensor(blend_params.background_image)  # (H, W, 3)

    # Format background image
    # (H, W, 3) -> (N, H, W, 3) -> select only pixels which are in the background using the mask 
    background_image_masked = background_image[None, ...].expand(N, -1, -1, -1)[is_background[..., None]] 

    # Set background color pixels to the colors from the background image
    pixel_colors = colors[..., 0, :].masked_scatter(
        is_background[..., None],
        background_image_masked
    )  # (N, H, W, 3)

    # Concat with the alpha channel.
    alpha = torch.ones((N, H, W, 1), dtype=colors.dtype, device=device)
    return torch.cat([pixel_colors, alpha], dim=-1)  # (N, H, W, 4)

# Wrapper for the C++/CUDA Implementation of sigmoid alpha blend.

```
**QUESTION**
So I have two questions:
1. Using pytorch3d, how can I insert a background image such that the renderer can overlay 3D object on top of it? I have attached the picture in comment as to what I would like to achieve.
2. I would like to overlay the 3D object at a specific pixel location (x,y) on top of a jpeg image. Of course the elevation and azimuth will be fed in by the .json file.

**Comment by bottler** [comment]
Can you debug your code and see if it goes in to your function? Can you work out where the white background is coming from?

**Comment by shahaamirbader** [comment]
The white background is coming from the following command
```
matplotlib.image.imsave(filename, image[0, ..., :3].cpu().numpy())
```
Changing it to 
```
matplotlib.image.imsave(filename, image[0].cpu().numpy())
```
removes the white background and makes it transparent. I have been somewhat able to find a very naïve method of overlaying the object using the following code. The following code runs the pytorch3d object rendering code and generates a 3D object (cow in this case) with a transparent background. Then I overlay the object on top of the  background image. However the results are not promising. Results are shown in Fig below. 
```
def main():
    [compile_all_steps(params.image_size, params.camera_dist, device, x, y,
                        params.obj_filename)
         for x in params.elevation for y in params.azim_angle]

    background = cv2.imread('/homelocal/Angle-Finder/assets/AR_Images_4/image_0.jpeg')
    overlay = cv2.imread('/homelocal/Angle-Finder/out/COW_elev0_azim0.png', cv2.IMREAD_UNCHANGED)  # IMREAD_UNCHANGED => open image with the alpha channel

    height, width = overlay.shape[:2]
    for y in range(height):
        for x in range(width):
            overlay_color = overlay[y, x, :3]  # first three elements are color (RGB)
            overlay_alpha = overlay[y, x, 3] / 255  # 4th element is the alpha channel, convert from 0-255 to 0.0-1.0

            # get the color from the background image
            background_color = background[y, x]

            # combine the background color and the overlay color weighted by alpha
            composite_color = background_color * (1 - overlay_alpha) + overlay_color * overlay_alpha

            # update the background image in place
            background[y, x] = composite_color

    cv2.imwrite('combined.png', background)

if __name__ == "__main__":
    main()

```
![combined](https://user-images.githubusercontent.com/78397774/162964087-0d2c6dad-e782-4f1a-8fa2-c4de99246033.png)

What I am looking to achieve is to be able to overlay the object on top of my background image during the rendering phase. The code shared in the start from https://github.com/facebookresearch/pytorch3d/issues/577 is not allowing me to do so. And despite debugging, I have not been able to find the solution, probably because there has to be some more lines of code that needs to be written in the rendering function.

**Comment by bottler** [comment]
There are two ways to do this, and either should work with some debugging. You seem to have switched strategies.

1. replace the blending code.  (first attempt)

2. Use the results of rendering to merge the images. For this, best to use MeshRendererWithFragments, and you can use the fragments to see exactly which pixels are object and which are background. The alpha channel of the result isn't the right thing to use. (more recent attempt)

**Comment by shahaamirbader** [comment]
I agree. I would love to use the blending code. (First Attempt). However, unfortunately, pytorch3d documentation does not have any tutorial related to that. Moreover I have been over almost all the issues and could not find one related to it except https://github.com/facebookresearch/pytorch3d/issues/577, which also is not able to produce results I am looking for.

I understand you are not suppose to spoon-feed with codes here. Nevertheless any sample code/ tutorial that can help in achieving this task would be really appreciated.

**Comment by bottler** [comment]
Method 2 would be like this: 
Replace `x=MeshRenderer(...)` with
```
from pytorch3d.renderer.mesh.renderer import MeshRendererWithFragments
x=MeshRendererWithFragments(...)
```
and `image=x(...)` with `image, fragments=x(...)`.
Then use `1.0 - (fragments.pix_to_face[batch_index, ..., 0] == -1).float()` as a HxW tensor of your overlay_alpha.

**Comment by gkioxari** [comment]
The way to overlay an image `(img1, mask)` on top of `img2` is simple
`img = img2 * (1-mask) + mask * img1`

where `mask` is a binary [0, 1] mask which you can get from `mask = fragments.pix_to_face > -1` and `img1` is the output of the renderer.

**Comment by shahaamirbader** [comment]
@gkioxari I did try what you said. The procedure you mentioned is some what similar to @bottler had proposed in his comment. So  the code is same as in my last comment except for line 102 which previously was ```img = background * (1.0 - (fragments.pix_to_face[:1, ..., 0] -1).float()) + ((fragments.pix_to_face[:1, ..., 0] -1).float())* overlay  ``` i replaced it with ``` img = background * (1.0 - (1-mask).float()) + (mask)* overlay ``` to implement the "mask" procedure as you mentioned.

The output is as follows:
```
(base) xubuntu@b5ce616211e0:/homelocal/Angle-Finder$ ipython image_overlay.py 
/home/xubuntu/.local/lib/python3.8/site-packages/pytorch3d/io/obj_io.py:533: UserWarning: Mtl file does not exist: /homelocal/Angle-Finder/models/cow.mtl
  warnings.warn(f"Mtl file does not exist: {f}")
fragments Fragments(pix_to_face=tensor([[[[-1],
          [-1],
          [-1],
          ...,
          [-1],
          [-1],
          [-1]],

         [[-1],
          [-1],
          [-1],
          ...,
          [-1],
          [-1],
          [-1]],

         [[-1],
          [-1],
          [-1],
          ...,
          [-1],
          [-1],
          [-1]],

         ...,

         [[-1],
          [-1],
          [-1],
          ...,
          [-1],
          [-1],
          [-1]],

         [[-1],
          [-1],
          [-1],
          ...,
          [-1],
          [-1],
          [-1]],

         [[-1],
          [-1],
          [-1],
          ...,
          [-1],
          [-1],
          [-1]]]], device='cuda:0'), zbuf=tensor([[[[-1.],
          [-1.],
          [-1.],
          ...,
          [-1.],
          [-1.],
          [-1.]],

         [[-1.],
          [-1.],
          [-1.],
          ...,
          [-1.],
          [-1.],
          [-1.]],

         [[-1.],
          [-1.],
          [-1.],
          ...,
          [-1.],
          [-1.],
          [-1.]],

         ...,

         [[-1.],
          [-1.],
          [-1.],
          ...,
          [-1.],
          [-1.],
          [-1.]],

         [[-1.],
          [-1.],
          [-1.],
          ...,
          [-1.],
          [-1.],
          [-1.]],

         [[-1.],
          [-1.],
          [-1.],
          ...,
          [-1.],
          [-1.],
          [-1.]]]], device='cuda:0'), bary_coords=tensor([[[[[-1., -1., -1.]],

          [[-1., -1., -1.]],

          [[-1., -1., -1.]],

          ...,

          [[-1., -1., -1.]],

          [[-1., -1., -1.]],

          [[-1., -1., -1.]]],


         [[[-1., -1., -1.]],

          [[-1., -1., -1.]],

          [[-1., -1., -1.]],

          ...,

          [[-1., -1., -1.]],

          [[-1., -1., -1.]],

          [[-1., -1., -1.]]],


         [[[-1., -1., -1.]],

          [[-1., -1., -1.]],

          [[-1., -1., -1.]],

          ...,

          [[-1., -1., -1.]],

          [[-1., -1., -1.]],

          [[-1., -1., -1.]]],


         ...,


         [[[-1., -1., -1.]],

          [[-1., -1., -1.]],

          [[-1., -1., -1.]],

          ...,

          [[-1., -1., -1.]],

          [[-1., -1., -1.]],

          [[-1., -1., -1.]]],


         [[[-1., -1., -1.]],

          [[-1., -1., -1.]],

          [[-1., -1., -1.]],

          ...,

          [[-1., -1., -1.]],

          [[-1., -1., -1.]],

          [[-1., -1., -1.]]],


         [[[-1., -1., -1.]],

          [[-1., -1., -1.]],

          [[-1., -1., -1.]],

          ...,

          [[-1., -1., -1.]],

          [[-1., -1., -1.]],

          [[-1., -1., -1.]]]]], device='cuda:0'), dists=tensor([[[[-1.],
          [-1.],
          [-1.],
          ...,
          [-1.],
          [-1.],
          [-1.]],

         [[-1.],
          [-1.],
          [-1.],
          ...,
          [-1.],
          [-1.],
          [-1.]],

         [[-1.],
          [-1.],
          [-1.],
          ...,
          [-1.],
          [-1.],
          [-1.]],

         ...,

         [[-1.],
          [-1.],
          [-1.],
          ...,
          [-1.],
          [-1.],
          [-1.]],

         [[-1.],
          [-1.],
          [-1.],
          ...,
          [-1.],
          [-1.],
          [-1.]],

         [[-1.],
          [-1.],
          [-1.],
          ...,
          [-1.],
          [-1.],
          [-1.]]]], device='cuda:0'))
this is mask tensor([[[[False],
          [False],
          [False],
          ...,
          [False],
          [False],
          [False]],

         [[False],
          [False],
          [False],
          ...,
          [False],
          [False],
          [False]],

         [[False],
          [False],
          [False],
          ...,
          [False],
          [False],
          [False]],

         ...,

         [[False],
          [False],
          [False],
          ...,
          [False],
          [False],
          [False]],

         [[False],
          [False],
          [False],
          ...,
          [False],
          [False],
          [False]],

         [[False],
          [False],
          [False],
          ...,
          [False],
          [False],
          [False]]]], device='cuda:0')
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/homelocal/Angle-Finder/image_overlay.py in <module>
    112 
    113 if __name__ == "__main__":
--> 114     main()
    115 
    116 

/homelocal/Angle-Finder/image_overlay.py in main()
    109 
    110 def main():
--> 111     overlay_image(params.image_size, params.camera_dist, device, params.elevation[0], params.azim_angle[0],params.obj_filename)
    112 
    113 if __name__ == "__main__":

/homelocal/Angle-Finder/image_overlay.py in overlay_image(image_size, dist, device, elev, azim, obj_filename)
    101     print("this is mask", mask)
    102     #img = background * (1.0 - (fragments.pix_to_face[:1, ..., 0] -1).float()) + ((fragments.pix_to_face[:1, ..., 0] -1).float())* overlay
--> 103     img = background * (1.0 - mask) + (mask)* overlay
    104     composited = torch.stack(channels, axis=2)
    105     background[y, x] = composited

/opt/conda/lib/python3.8/site-packages/torch/_tensor.py in __rsub__(self, other)
    532         if has_torch_function_variadic(self, other):
    533             return handle_torch_function(Tensor.__rsub__, (self, other), self, other)
--> 534         return _C._VariableFunctions.rsub(self, other)
    535 
    536     def __rdiv__(self, other):

RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `logical_not()` operator instead.

```

I did try replacing the '-' operator with the '~' operator, however the error changed to 
```
/homelocal/Angle-Finder/image_overlay.py in overlay_image(image_size, dist, device, elev, azim, obj_filename)
    101     print("this is mask", mask)
    102     #img = background * (1.0 - (fragments.pix_to_face[:1, ..., 0] -1).float()) + ((fragments.pix_to_face[:1, ..., 0] -1).float())* overlay
--> 103     img = background * (~mask) + (mask)* overlay
    104     composited = torch.stack(channels, axis=2)
    105     background[y, x] = composited

TypeError: unsupported operand type(s) for *: 'numpy.ndarray' and 'Tensor'
```
I am really struggling to get this code working and obtain results. Any help would be appreciated. Thanks

**Comment by bottler** [comment]
The `.float()` at the end of my code is a cure for the negating bool problem. So  `(1.0 - mask)` should be ` (1.0 - mask.float())`. The second error is just from mixing numpy arrays and torch tensors - you need to keep track of what is what and explicitly convert between them.

**Comment by shahaamirbader** [comment]
Tried adding .float() as well to the end. But does not resolve the issue. 

![image](https://user-images.githubusercontent.com/78397774/163175396-359afa57-93e4-444a-ac58-c33fcfb8c201.png)

**Comment by shahaamirbader** [comment]
@bottler, there is a complete comment on top of my last comment, that shows the result of what you had proposed. I have mentioned you in that comment. Would you like to comment over that as well?

**Comment by shahaamirbader** [comment]
> @bottler. Thanks for the help. I did try what you recommended, however still not able to get the results. This is my complete code that I am trying to execute.
> 
> ```
> import cv2
> import os
> import sys
> import torch
> import math
> 
> import json
> if torch.__version__ == '1.6.0+cu101' and sys.platform.startswith('linux'):
>     get_ipython().system('pip install pytorch3d')
> else:
>     need_pytorch3d = False
>     try:
>         import pytorch3d
>     except ModuleNotFoundError:
>         need_pytorch3d = True
>     if need_pytorch3d:
>         get_ipython().system('curl -LO https://github.com/NVIDIA/cub/archive/1.10.0.tar.gz')
>         get_ipython().system('tar xzf 1.10.0.tar.gz')
>         os.environ["CUB_HOME"] = os.getcwd() + "/cub-1.10.0"
>         get_ipython().system("pip install 'git+https://github.com/facebookresearch/pytorch3d.git@stable'")
> from pytorch3d.io import load_obj
> from pytorch3d.structures import Meshes
> from pytorch3d.renderer import (
>     look_at_view_transform,
>     FoVPerspectiveCameras,
>     FoVOrthographicCameras,
>     Materials,
>     RasterizationSettings,
>     MeshRenderer,
>     MeshRasterizer,
>     SoftPhongShader,
>     TexturesVertex,
>     TexturesAtlas,
>     PointsRenderer,
>     PointsRasterizationSettings,
>     PointsRasterizer
> )
> import matplotlib.pyplot as plt
> import matplotlib
> from utils import Params
> 
> # Set the device
> if torch.cuda.is_available():
>     device = torch.device("cuda:0")
>     torch.cuda.set_device(device)
> else:
>     device = torch.device("cpu")
> 
> # Import parameters
> params = Params("params.json")
> obj_filename = params.obj_filename
> 
> def overlay_image(image_size, dist, device, elev, azim, obj_filename):
> 
>     from pytorch3d.renderer.mesh.renderer import MeshRendererWithFragments
> 
>      # Get vertices, faces, and auxiliary information
>     verts, faces, aux = load_obj(
>         obj_filename,
>         device=device,
>         load_textures=True,
>         create_texture_atlas=True,
>         texture_atlas_size=4,
>         texture_wrap="repeat"
>          )
>     # Create a textures object
>     atlas = aux.texture_atlas
>     # Create Meshes object
>     mesh = Meshes(
>         verts=[verts],
>         faces=[faces.verts_idx],
>         textures=TexturesAtlas(atlas=[atlas]),) 
>      # Initialize the camera with camera distance, elevation, azimuth angle,
>     # and image size
>     R, T = look_at_view_transform(dist=dist, elev=elev, azim=azim)
>     cameras = FoVPerspectiveCameras(device=device, R=R, T=T)
>     raster_settings = RasterizationSettings(
>         image_size=image_size,
>         blur_radius=0.0,
>         faces_per_pixel=1,
>     )
>     # Initialize rasterizer by using a MeshRasterizer class
>     rasterizer = MeshRasterizer(
>         cameras=cameras,
>         raster_settings=raster_settings
>     )
>     # The textured phong shader interpolates the texture uv coordinates for
>     # each vertex, and samples from a texture image.
>     shader = SoftPhongShader(device=device, cameras=cameras)
>     # Create a mesh renderer by composing a rasterizer and a shader
>     renderer = MeshRendererWithFragments(rasterizer, shader)
> 
>     image, fragments = renderer(mesh)
>     print("fragments", fragments)
>     background = cv2.imread('/homelocal/Angle-Finder/assets/AR_Images_4/image_0.jpeg')
>     overlay = cv2.imread('/homelocal/Angle-Finder/out/COW_elev0_azim0.png')  # IMREAD_UNCHANGED => open image with the alpha channel
> 
>     mask = fragments.pix_to_face > -1
>     print("this is mask", mask)
>     img = background * (1.0 - (fragments.pix_to_face[:1, ..., 0] -1).float()) + ((fragments.pix_to_face[:1, ..., 0] -1).float())* overlay
>     composited = torch.stack(channels, axis=2)
>     background[y, x] = composited
> 
>     cv2.imwrite('/homelocal/Angle-Finder/out/new_combined.png', background)
> 
> def main():
>     overlay_image(params.image_size, params.camera_dist, device, params.elevation[0], params.azim_angle[0],params.obj_filename)
>     
> if __name__ == "__main__":
>     main()
> ```
> 
> And this is the output at the terminal.
> 
> ```
> (base) xubuntu@b5ce616211e0:/homelocal/Angle-Finder$ ipython image_overlay.py 
> /home/xubuntu/.local/lib/python3.8/site-packages/pytorch3d/io/obj_io.py:533: UserWarning: Mtl file does not exist: /homelocal/Angle-Finder/models/cow.mtl
>   warnings.warn(f"Mtl file does not exist: {f}")
> fragments Fragments(pix_to_face=tensor([[[[-1],
>           [-1],
>           [-1],
>           ...,
>           [-1],
>           [-1],
>           [-1]],
> 
>          [[-1],
>           [-1],
>           [-1],
>           ...,
>           [-1],
>           [-1],
>           [-1]],
> 
>          [[-1],
>           [-1],
>           [-1],
>           ...,
>           [-1],
>           [-1],
>           [-1]],
> 
>          ...,
> 
>          [[-1],
>           [-1],
>           [-1],
>           ...,
>           [-1],
>           [-1],
>           [-1]],
> 
>          [[-1],
>           [-1],
>           [-1],
>           ...,
>           [-1],
>           [-1],
>           [-1]],
> 
>          [[-1],
>           [-1],
>           [-1],
>           ...,
>           [-1],
>           [-1],
>           [-1]]]], device='cuda:0'), zbuf=tensor([[[[-1.],
>           [-1.],
>           [-1.],
>           ...,
>           [-1.],
>           [-1.],
>           [-1.]],
> 
>          [[-1.],
>           [-1.],
>           [-1.],
>           ...,
>           [-1.],
>           [-1.],
>           [-1.]],
> 
>          [[-1.],
>           [-1.],
>           [-1.],
>           ...,
>           [-1.],
>           [-1.],
>           [-1.]],
> 
>          ...,
> 
>          [[-1.],
>           [-1.],
>           [-1.],
>           ...,
>           [-1.],
>           [-1.],
>           [-1.]],
> 
>          [[-1.],
>           [-1.],
>           [-1.],
>           ...,
>           [-1.],
>           [-1.],
>           [-1.]],
> 
>          [[-1.],
>           [-1.],
>           [-1.],
>           ...,
>           [-1.],
>           [-1.],
>           [-1.]]]], device='cuda:0'), bary_coords=tensor([[[[[-1., -1., -1.]],
> 
>           [[-1., -1., -1.]],
> 
>           [[-1., -1., -1.]],
> 
>           ...,
> 
>           [[-1., -1., -1.]],
> 
>           [[-1., -1., -1.]],
> 
>           [[-1., -1., -1.]]],
> 
> 
>          [[[-1., -1., -1.]],
> 
>           [[-1., -1., -1.]],
> 
>           [[-1., -1., -1.]],
> 
>           ...,
> 
>           [[-1., -1., -1.]],
> 
>           [[-1., -1., -1.]],
> 
>           [[-1., -1., -1.]]],
> 
> 
>          [[[-1., -1., -1.]],
> 
>           [[-1., -1., -1.]],
> 
>           [[-1., -1., -1.]],
> 
>           ...,
> 
>           [[-1., -1., -1.]],
> 
>           [[-1., -1., -1.]],
> 
>           [[-1., -1., -1.]]],
> 
> 
>          ...,
> 
> 
>          [[[-1., -1., -1.]],
> 
>           [[-1., -1., -1.]],
> 
>           [[-1., -1., -1.]],
> 
>           ...,
> 
>           [[-1., -1., -1.]],
> 
>           [[-1., -1., -1.]],
> 
>           [[-1., -1., -1.]]],
> 
> 
>          [[[-1., -1., -1.]],
> 
>           [[-1., -1., -1.]],
> 
>           [[-1., -1., -1.]],
> 
>           ...,
> 
>           [[-1., -1., -1.]],
> 
>           [[-1., -1., -1.]],
> 
>           [[-1., -1., -1.]]],
> 
> 
>          [[[-1., -1., -1.]],
> 
>           [[-1., -1., -1.]],
> 
>           [[-1., -1., -1.]],
> 
>           ...,
> 
>           [[-1., -1., -1.]],
> 
>           [[-1., -1., -1.]],
> 
>           [[-1., -1., -1.]]]]], device='cuda:0'), dists=tensor([[[[-1.],
>           [-1.],
>           [-1.],
>           ...,
>           [-1.],
>           [-1.],
>           [-1.]],
> 
>          [[-1.],
>           [-1.],
>           [-1.],
>           ...,
>           [-1.],
>           [-1.],
>           [-1.]],
> 
>          [[-1.],
>           [-1.],
>           [-1.],
>           ...,
>           [-1.],
>           [-1.],
>           [-1.]],
> 
>          ...,
> 
>          [[-1.],
>           [-1.],
>           [-1.],
>           ...,
>           [-1.],
>           [-1.],
>           [-1.]],
> 
>          [[-1.],
>           [-1.],
>           [-1.],
>           ...,
>           [-1.],
>           [-1.],
>           [-1.]],
> 
>          [[-1.],
>           [-1.],
>           [-1.],
>           ...,
>           [-1.],
>           [-1.],
>           [-1.]]]], device='cuda:0'))
> this is mask tensor([[[[False],
>           [False],
>           [False],
>           ...,
>           [False],
>           [False],
>           [False]],
> 
>          [[False],
>           [False],
>           [False],
>           ...,
>           [False],
>           [False],
>           [False]],
> 
>          [[False],
>           [False],
>           [False],
>           ...,
>           [False],
>           [False],
>           [False]],
> 
>          ...,
> 
>          [[False],
>           [False],
>           [False],
>           ...,
>           [False],
>           [False],
>           [False]],
> 
>          [[False],
>           [False],
>           [False],
>           ...,
>           [False],
>           [False],
>           [False]],
> 
>          [[False],
>           [False],
>           [False],
>           ...,
>           [False],
>           [False],
>           [False]]]], device='cuda:0')
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> /homelocal/Angle-Finder/image_overlay.py in <module>
>     111 
>     112 if __name__ == "__main__":
> --> 113     main()
>     114 
>     115 
> 
> /homelocal/Angle-Finder/image_overlay.py in main()
>     108 
>     109 def main():
> --> 110     overlay_image(params.image_size, params.camera_dist, device, params.elevation[0], params.azim_angle[0],params.obj_filename)
>     111 
>     112 if __name__ == "__main__":
> 
> /homelocal/Angle-Finder/image_overlay.py in overlay_image(image_size, dist, device, elev, azim, obj_filename)
>     100     mask = fragments.pix_to_face > -1
>     101     print("this is mask", mask)
> --> 102     img = background * (1.0 - (fragments.pix_to_face[:1, ..., 0] -1).float()) + ((fragments.pix_to_face[:1, ..., 0] -1).float())* overlay
>     103     composited = torch.stack(channels, axis=2)
>     104     background[y, x] = composited
> 
> TypeError: unsupported operand type(s) for *: 'numpy.ndarray' and 'Tensor'
> ```
> 
> So here are few questions that I still have. I know I may like sound a beginner, which I am:
> 
> 1. Is the fragment output all [-1] correct?
> 2. I dont see the fragments.pix_to_face > -1 output as [0,1[.
> 3. What is the batch_index in the term `1.0 - (fragments.pix_to_face[batch_index, ..., 0] == -1).float()`
> 
> And lastly, any advice would be appreciated that can help me run this code and achieve the results.

@bottler, there is a complete comment on top of my last comment, that shows the result of what you had proposed. I have mentioned you in that comment. Would you like to comment over that as well?

**Comment by shahaamirbader** [comment]
any help here will be appreciated, before this issue gets marked as stale.

**Comment by bottler** [comment]
1. There is nothing surprising in many of the values being `-1` or `-1.0` - these correspond to empty pixels. But the values are not "all -1" - note the `...` in the output.
2. `fragments.pix_to_face > -1` is a boolean tensor, it contains `True` (which is basically the same as `1`) and `False` (which is basically the same as `0`).
3. batch_index is the index of the image you want in the images you rendered. For example if you have a batch of N meshes and a batch of N cameras, then batch_index will be a number between 0 and N-1. As far as I can see in your more recent messages, N is 1 so batch_index needs to be 0.

**Comment by shahaamirbader** [comment]
Tried with batch_index = 0. By looking at the errors and code can you provide a reason as to why the code you proposed is not working, as it should?

**Comment by bottler** [comment]
@shahaamirbader Can you help a bit? If you have worked through our advice and are still having problems you can't understand, can you post your full current code and its output?
