### ISSUE TITLE
ImportError: DLL load failed while importing _C: The specified procedure could not be found.

### ISSUE THREAD

**Issue by steezy18** [facebookresearch/pytorch3d#1165]
Hello, please I ran into this error while I was trying to preprocess the Shapenet dataset. I had it working all along until I re-installed the Pytorch GPU in the Anaconda environment. I will appreciate any help please. I had tried the above suggestion but not working.

(pytorch3d) C:\meshrcnn>python tools/preprocess_shapenet.py --r2n2_dir C:\meshrcnn\datasets\shapenet\ShapeNetRendering --shapenet_dir C:\meshrcnn\datasets\shapenet\ShapeNetCore_v1 --shapenet_binvox_dir C:\meshrcnn\datasets\shapenet\ShapeNetCore.v1.binvox --splits_file C:\meshrcnn\datasets\shapenet\pix2mesh_splits_val05.json --output_dir ./datasets/shapenet/ShapeNetV1processed --zip_output
Traceback (most recent call last):
File "C:\meshrcnn\tools\preprocess_shapenet.py", line 12, in
from pytorch3d.io import load_obj
File "C:\ProgramData\Anaconda3\envs\pytorch3d\lib\site-packages\pytorch3d\io_init_.py", line 8, in
from .obj_io import load_obj, load_objs_as_meshes, save_obj
File "C:\ProgramData\Anaconda3\envs\pytorch3d\lib\site-packages\pytorch3d\io\obj_io.py", line 22, in
from pytorch3d.renderer import TexturesAtlas, TexturesUV
File "C:\ProgramData\Anaconda3\envs\pytorch3d\lib\site-packages\pytorch3d\renderer_init_.py", line 7, in
from .blending import (
File "C:\ProgramData\Anaconda3\envs\pytorch3d\lib\site-packages\pytorch3d\renderer\blending.py", line 11, in
from pytorch3d import _C
ImportError: DLL load failed while importing _C: The specified procedure could not be found.

(pytorch3d) C:\meshrcnn>python tools/preprocess_shapenet.py --output_dir ./datasets/shapenet/ShapeNetprocessed --zip_output
Traceback (most recent call last):
File "C:\meshrcnn\tools\preprocess_shapenet.py", line 12, in
from pytorch3d.io import load_obj
File "C:\ProgramData\Anaconda3\envs\pytorch3d\lib\site-packages\pytorch3d\io_init_.py", line 8, in
from .obj_io import load_obj, load_objs_as_meshes, save_obj
File "C:\ProgramData\Anaconda3\envs\pytorch3d\lib\site-packages\pytorch3d\io\obj_io.py", line 22, in
from pytorch3d.renderer import TexturesAtlas, TexturesUV
File "C:\ProgramData\Anaconda3\envs\pytorch3d\lib\site-packages\pytorch3d\renderer_init_.py", line 7, in
from .blending import (
File "C:\ProgramData\Anaconda3\envs\pytorch3d\lib\site-packages\pytorch3d\renderer\blending.py", line 11, in
from pytorch3d import _C
ImportError: DLL load failed while importing _C: The specified procedure could not be found.

**Comment by steezy18** [comment]
C:\ProgramData\Anaconda3\envs\pytorch3d\Lib\site-packages\pytorch3d>ls
_C.cp39-win_amd64.pyd  __pycache__  datasets  loss  renderer    transforms  vis
__init__.py            common       io        ops   structures  utils

**Comment by bottler** [comment]
PyTorch3D is not installed correctly. Something is wrong with the built file `_C.cp39-win_amd64.pyd`. How did you install? Can you show the output of `conda list` and `pip list`? If you changed/upgraded a dependency between building and using, then something like this may happen.

Opening the file `_C.cp39-win_amd64.pyd` in dependency walker may reveal what libraries it wants to be around. Maybe if you do that within the conda environment then the error symbols (ignoring python itself) will be the actual problem.

**Comment by steezy18** [comment]
# conda environments:
#
base                  *  C:\ProgramData\Anaconda3
TMNet2                   C:\ProgramData\Anaconda3\envs\TMNet2
newpytorch3d             C:\ProgramData\Anaconda3\envs\newpytorch3d
tensorflow               C:\ProgramData\Anaconda3\envs\tensorflow
tf-gpu                   C:\ProgramData\Anaconda3\envs\tf-gpu
tmnet                    C:\ProgramData\Anaconda3\envs\tmnet
tmnet2                   C:\ProgramData\Anaconda3\envs\tmnet2
torch                    C:\ProgramData\Anaconda3\envs\torch

**Comment by bottler** [comment]
Starting over very carefully in a new environment is a good idea. I see above pip list is for `newpytorch3d` but the error was reported for `pytorch3d`. `conda list` should list the packages in the environment, and that's what I want to see along with the error message. (`conda env list` is not so important).

**Comment by steezy18** [comment]
Thank you I was able to create another pytorch3d conda environment and installed all the packages.
I also install detectron2 package. While running the training part of the code, I got this

(pytorch3d) PS C:\meshrcnn> python tools/train_net.py --num-gpus 1 --config-file configs/pix3d/meshrcnn_R50_FPN.yaml
Traceback (most recent call last):
  File "C:\meshrcnn\tools\train_net.py", line 18, in <module>
    import meshrcnn.modeling  # noqa
  File "c:\meshrcnn\meshrcnn\modeling\__init__.py", line 2, in <module>
    from .roi_heads import *  # noqa
  File "c:\meshrcnn\meshrcnn\modeling\roi_heads\__init__.py", line 2, in <module>
    from .roi_heads import MeshRCNNROIHeads  # noqa
  File "c:\meshrcnn\meshrcnn\modeling\roi_heads\roi_heads.py", line 12, in <module>
    from meshrcnn.modeling.roi_heads.mask_head import mask_rcnn_loss
  File "c:\meshrcnn\meshrcnn\modeling\roi_heads\mask_head.py", line 7, in <module>
    from meshrcnn.structures.mask import batch_crop_masks_within_box
  File "c:\meshrcnn\meshrcnn\structures\__init__.py", line 2, in <module>
    from .mesh import MeshInstances
  File "c:\meshrcnn\meshrcnn\structures\mesh.py", line 5, in <module>
    import meshrcnn.utils.shape as shape_utils
  File "c:\meshrcnn\meshrcnn\utils\__init__.py", line 2, in <module>
    from . import model_zoo  # registers pathhandlers
  File "c:\meshrcnn\meshrcnn\utils\model_zoo.py", line 3, in <module>
    from detectron2.utils.file_io import PathHandler, PathManager
ModuleNotFoundError: No module named 'detectron2.utils.file_io'

Checking through, all other modules of detectron2 were installed except - detectron2.utils.file_io
Any help on what I did wrong please.

**Comment by bottler** [comment]
Good to hear PyTorch3D installation has worked.

**Comment by 511lyf** [comment]
> 很高兴听到 PyTorch3D 安装已经成功。

Hello, I installed pytorch3d with PytorCH3D-0.7.6 +pt2.1.0cu121-cp39-cp39-win_amd64.whl and found the same problem, ImportError: DLL load failed while importing _C: The specified program cannot be found. Is this because I didn't install pytorch3d properly? I am using windows11 operating system, but I can't install it correctly using the official installation method, but I can only import it correctly using whl. What should I do to solve the problem that I can't find the specified program? I am looking forward to your reply, thank you very much!

**Comment by bottler** [comment]
Please open a new issue, with details about your setup, if you still need help.

**Comment by 511lyf** [comment]
Hello, ImportError appeared when I installed pytorch3d using PyTorCH3D-0.7.6 +pt2.1.0cu121-cp39-cp39-win_amd64.whl: DLL load failed while importing _C: The specified program cannot be found. There is a _c.cp39-win_amd64. pyd file in the pytorch3d directory. Does this contain the contents of the _C module? Is this problem caused by my incorrect installation of pytorch3d? I am using windows11 operating system, but I can't install it correctly using the official installation method, but I can only import it correctly using whl. What should I do to solve the problem that I can't find the specified program? I am looking forward to your reply, thank you very much!

**Comment by bottler** [comment]
@511lyf Please really open a new issue if you need help. This issue was closed 2 years ago. Do not comment here.
