### ISSUE TITLE
x_lengths / y_lenghts in chamfer_distance loss

### ISSUE THREAD

**Issue by Hiusam** [facebookresearch/pytorch3d#1174]
## ❓ Questions on chamfer_distance

I encountered "nan" loss when using chamfer_distance loss. Could you please give some hints of what may cause the "nan"?

I found that if there is zero point in a cloud, the loss will be "nan". I also tried specifying negative numbers of points in x_lengths / y_lenghts and a larger number of points than it actually is, in both cases the loss is 0.0 rather "nan". 

I wonder what it will behave when x_lengths / y_lenghts is set to be a wrong number (zero, negative, larger than P of [N, P, D]).

Thank you very much!

**Comment by bottler** [comment]
I think there's a bug here. If `point_reduction` is `"mean"` then you will get nans when there's an empty pointcloud. I think a 0 result would be better in this case.

With regard to a wrong input length: if an input length is valid (i.e. non negative) but "too small" then only the specified subset of the input will be used. If it is negative or too big then we can't promise what will happen, the user needs to avoid this. This is "undefined behavior".

**Comment by gkioxari** [comment]
We should catch the cases of empty input pointclouds and return a 0.0, I agree!

**Comment by bottler** [comment]
That commit (on main) should have fixed this.
