### ISSUE TITLE
cmd: Unable to open source file  sigmoid_alpha_blend_cpu.cpp

### ISSUE THREAD

**Issue by cinamon123** [facebookresearch/pytorch3d#1175]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## 🐛 Bugs / Unexpected behaviors

NOTE: Please look at the existing list of Issues tagged with the label ['bug`](https://github.com/facebookresearch/pytorch3d/issues?q=label%3Abug). **Only open a new issue if this bug has not already been reported. If an issue already exists, please comment there instead.**.

## Instructions To Reproduce the Issue:

Please include the following (depending on what the issue is):

1. Any changes you made (`git diff`) or code you wrote
```
<put diff or code here>
```
2. The exact command(s) you ran:
3. What you observed (including the full logs):
```
<put logs here>
```

Please also simplify the steps as much as possible so they do not require additional resources to
   run, such as a private dataset.

**Comment by bottler** [comment]
Could you be hitting a limit on the maximum length of a path in windows? Try using `p` instead of `pytorch3d-master`, or doing the whole thing in a simpler directory.

**Comment by cinamon123** [comment]
Thank you for solving the last question!

However, after this program started to running for almost 1min, a new bug appeared. I believe this bug is not caused by path limitation. Besides, the file 'HT' can be find under 'include', and 'HT.h' is under 'HT'.

[win10]
![image](https://user-images.githubusercontent.com/104305930/165447463-6a744110-8627-48b1-884f-cfd6d82af2db.png)

Could you please help me? Thank you sincerely!

**Comment by bottler** [comment]
I think you are using PyTorch 1.11.0 and the latest PyTorch3D release (0.6.1 = stable). These are incompatible. You need to either use the `main` branch of PyTorch3D or an earlier version of PyTorch.

**Comment by cinamon123** [comment]
Hello! I am running the tutorial code at google colab now. But it still can not install pytorch3d.
![yy](https://user-images.githubusercontent.com/104305930/166109706-da6cf48d-8ed3-4514-9077-0da57466ffe2.png)

**Comment by bottler** [comment]
This has been observed elsewhere. Can you remove the `@stable` from the end of the pip install? (The stable tag hasn't been moved to 0.6.2 yet.)

**Comment by cinamon123** [comment]
Thank you very much!!! I have successfully installed it at google colab!

**Comment by bottler** [comment]
> This has been observed elsewhere. Can you remove the `@stable` from the end of the pip install? (The stable tag hasn't been moved to 0.6.2 yet.)

The stable tag has just been moved and the wheel is made, so the tutorials work again on Colab without building from source.
