### ISSUE TITLE
Small question about R2N2 dataset tutorial

### ISSUE THREAD

**Issue by greeneggsandyaml** [facebookresearch/pytorch3d#1176]
Hello PyTorch3D authors,

Thank you for this library. I had a quick question about the R2N2 dataset. I am following the tutorial in the docs, specifically the last section ([link](https://pytorch3d.org/tutorials/dataloaders_ShapeNetCore_R2N2#5.-Visualize-R2N2-models'-voxels)). My cubified voxel image looks quite strange, but the tutorial online does not show how it should look, so my question is: should the cubified voxels look like this? Is everything correct with how I have set up this dataset? 

The code I'm using is straight from the tutorial:
```
# This all follows the tutorial
r2n2_model = r2n2_dataset[9,[1,2]]
original_rendering = r2n2_model["images"]
image_grid(original_rendering.numpy(), rows=1, cols=2, rgb=True)
vox_render = render_cubified_voxels(r2n2_model["voxels"], device=device)
image_grid(vox_render.cpu().numpy(), rows=1, cols=2, rgb=True)
```

The original rendering looks fine:
![orig](https://raw.githubusercontent.com/greeneggsandyaml/tmptmptmp/main/8108286b-88df-4a06-836e-fdfa5f8029e6.png)

The mesh also looks fine (not shown here). 

The cubified voxels look strange though, as if the voxel grid is not dense: 
![cubified](https://raw.githubusercontent.com/greeneggsandyaml/tmptmptmp/main/a60779f2-c802-4088-b73e-bb6986a33c7a.png)

The images in the R2N2 paper look very different, in particular they look much more dense. I downloaded the voxel data (`ShapeNetVox32.tgz`) from http://3d-r2n2.stanford.edu/. 

Is there some parameter that I am not setting here?

Thank you for your work.

**Comment by greeneggsandyaml** [comment]
Hello, I just wanted to follow up on this issue. Any help would be very much appreciated! 

Thanks again for your work.

**Comment by Zxlan** [comment]
@greeneggsandyaml Hello, I also want to learn this tutorial, can you share your dataset, I can't download it online, thank you very much.

**Comment by greeneggsandyaml** [comment]
@Zxlan The dataset is ShapeNet. You have to sign up and download it here: https://shapenet.org

Regarding the rendering, I have solved this issue on my own -- I needed to change the lighting and my rasterization settings, most importantly by culling backfaces. The rendering issues seem to be a product of bad ShapeNet meshes rather than any issues with the PyTorch3D renderer. 

Thus, I am closing this issue.

**Comment by Zxlan** [comment]
@greeneggsandyaml I have registered an account, but the webmaster has not approved my application so far. That's why I wanted to see if anyone would like to share the dataset, I promise I'm just for learning
