### ISSUE TITLE
Can you change the blending sigma and gamma during the optimization?

### ISSUE THREAD

**Issue by omimo** [facebookresearch/pytorch3d#1179]
## ❓ Questions on how to use PyTorch3D

Hi all,

Is it possible to change the sigma and gamma of the SoftSilhouetteShader/BlendParams after you have initially created your renderer? I want to be able to change these values in the optimization loop.

Thanks for your great work!

**Comment by gkioxari** [comment]
You can do anything you want to do!

Yes! And of course you need to initialize your renderer during the forward pass with your new values (and that should not slow you down)
