### ISSUE TITLE
Difficulty understanding the parameters meaning in pytorch3d.renderer.cameras.look_at_view_transform

### ISSUE THREAD

**Issue by charleschiu2012** [facebookresearch/pytorch3d#118]
In pytorch3d.renderer.cameras.look_at_view_transform function, the parameters explanation of `elev` and `azim` is confusional. [https://github.com/facebookresearch/pytorch3d/blob/6c48ff6ad9005cfc03704c77531a4a25d1c8d843/pytorch3d/renderer/cameras.py#L1018](url)

> elev – angle in degrees or radians. This is the angle between the vector from the object to the camera, and the `horizontal plane.`
azim – angle in degrees or radians. The vector from the object to the camera is projected onto a `horizontal plane y = z = 0`. azim is the angle between the projected vector and a `reference vector at (1, 0, 0)` on the reference plane.

1. Is the horizontal plane equals xz-plane in pytorch3d? (like [https://www.scratchapixel.com](url)  implies)
2. If so, `azim` says that `horizontal plane y = z = 0`, but y = z = 0 is actually a line(x-axis)? 

Maybe replace `horizontal plane y = z = 0` with `horizontal plane y = 0` in `azim`?

**Comment by nikhilaravi** [comment]
@charleschiu2012 the ground plan is indeed xz.  You are right that the comment for azim should say that the horizontal plane is `y=0`.  

Feel free to submit a PR for this documentation fix or we can fix it too.
