### ISSUE TITLE
Questions on basic alignment and orthographic views

### ISSUE THREAD

**Issue by pichtpk** [facebookresearch/pytorch3d#1180]
## ❓ Questions on how to use PyTorch3D
Hi!

Currently I load an OBJ file and create three orthogonal views from this object. But I still have problems of understanding.

1. How is the basic orientation of a body determined? Since my OBJ file does not contain normals, it is very interesting for me to know how the body is aligned in front of a camera so that the same image is generated in each case.

2. How to ensure the orthogonality in the image generation using the class "FoVOrthographicCameras"?

Thank you!

**Comment by patricklabatut** [comment]
1. This completely depends on the object, there is no convention for this and for default camera placement. One typically need to compute the axis-aligned bounding box (or oriented bounding box) of the object (from its vertices) and then place the camera to render specific views (for instance aligned with faces of these bounding boxes).
2. The `FoVOrthographicCameras` cameras are orthographic by construction.
