### ISSUE TITLE
Cameras don't transpose rotation matrix

### ISSUE THREAD

**Issue by jenkspt** [facebookresearch/pytorch3d#1183]
I think there is an issue in `PerspectiveCameras` where the rotation matrix is not transposed
Given intrinsics matrix `K` and extrinsics matrix `[R|t]`, I'm expecting `get_full_projection_transform` to compose these as 
as `P = K * [R | t]`

```python
from pytorch3d.renderer.cameras import PerspectiveCameras

H, W = (100, 100)
K = torch.tensor([
    [555.5555,   0.0000, W/2, 0.0],
    [  0.0000, 555.5555, H/2, 0.0],
    [  0.0000,   0.0000, 0.0, 1.0],
    [  0.0000,   0.0000, 1.0, 0.0]], dtype=torch.float32)

R = torch.tensor([
    [-9.9990e-01, -1.3989e-02, -4.6566e-10],
    [ 4.1922e-03, -2.9966e-01,  9.5404e-01],
    [-1.3346e-02,  9.5394e-01,  2.9969e-01]])

t = torch.tensor([ 0.,  0., -4.])

Rt = torch.cat([torch.cat([R, t.unsqueeze(-1)], 1), torch.tensor([[0, 0, 0, 1]])], 0)
 # here i'm composing my own camera matrix
P1 = K @ Rt
```
```python
# Here i'm using pytorch3d
camera = PerspectiveCameras(
    K=K.unsqueeze(0),
    R=R.unsqueeze(0),
    T=t.unsqueeze(0),
    image_size=[(H, W)], in_ndc=False)


# it appears that `Transform3d` wants transpose matrices -- so untranspose
P2 = camera.get_full_projection_transform().get_matrix().squeeze(0).t()
atol = 1e-4   # being liberal with the tolerance
assert torch.allclose(P1, P2, atol=atol)     # Expecting this to evaluate to true -- but does not
```
so tracking down where there might be a problem

```python
# this works
assert torch.allclose(K, camera.get_projection_transform().get_matrix().squeeze(0).t(), atol=atol)
```

```python
# this doesn't work
assert torch.allclose(Rt, camera.get_world_to_view_transform().get_matrix().squeeze(0).t(), atol=atol)
```

It looks like the rotation matrix isn't being transposed here
if we look at https://github.com/facebookresearch/pytorch3d/blob/2bd65027ca5c3b87b77d4f05b8eacae58d8d106f/pytorch3d/renderer/cameras.py#L1113-L1115
we can see that the intrinsics matrix is transposed

but here:
https://github.com/facebookresearch/pytorch3d/blob/2bd65027ca5c3b87b77d4f05b8eacae58d8d106f/pytorch3d/renderer/cameras.py#L203-L207
here the rotation matrix `R` is not transposed

can verify that I get the expected result if i do transpose R using the helper function:
```python
from pytorch3d.renderer.cameras import get_world_to_view_transform
P3 = get_world_to_view_transform(R.t().unsqueeze(0), t.unsqueeze(0)).compose(camera.get_projection_transform()).get_matrix().squeeze(0).t()
assert torch.allclose(P1, P3, atol=atol)
```

Not sure if I'm missing something here.

**Comment by gkioxari** [comment]
All our transforms assume row-vectors. That is also said in the code you are referencing above:

https://github.com/facebookresearch/pytorch3d/blob/ec9580a1d40b307ab98d89d28f9926a6bc04628d/pytorch3d/renderer/cameras.py#L662

and here, among other places. 

https://github.com/facebookresearch/pytorch3d/blob/ec9580a1d40b307ab98d89d28f9926a6bc04628d/pytorch3d/transforms/transform3d.py#L120-L122 

So it assumes that the R you are providing operates on row-vectors (so it's already transposed based on your code above).

**Comment by jenkspt** [comment]
Thanks for the clarification -- I'm still a little confused by the following code
https://github.com/facebookresearch/pytorch3d/blob/2bd65027ca5c3b87b77d4f05b8eacae58d8d106f/pytorch3d/renderer/cameras.py#L1099-L1116

If I pass my own intrinsics matrix K -- it will be transposed before creating the `Transform3d` so I should pass a column-vector matrix

The extrinsics rotation R should be passed as a row-vector matrix as is convention.
Is this accurate?
