### ISSUE TITLE
PerspectiveCameras + non-symmetric projection + in_ndc=False = wrong camera matrix

### ISSUE THREAD

**Issue by mantiuk** [facebookresearch/pytorch3d#1185]
## 🐛 Bugs / Unexpected behaviors

When a perspective camera is constructed:

PerspectiveCameras(device=device, R=R_all[None, i, ...], T=T_all[None, i, ...], K=K_all[None, i, ...], in_ndc=False, image_size=[image_sizes[i],] )

and K is a custom intrinsic matrix with the principal point that is not in the centre of the image (e.g. cropped camera view), then get_ndc_camera_transform:

https://github.com/facebookresearch/pytorch3d/blob/a51a30082768c566a579c661aaa7229082f6ff49/pytorch3d/renderer/cameras.py#L1159

gives incorrect transformation from the screen to the NDC coordinates. I believe the function assumes that the principal point is in the centre of the image, but this may not be the case for a custom intrinsic matrix K. 

I fixed the issue by overloading get_ndc_camera_transform() so that it flips the sign of the translation part of the matrix instead of using the principal point to correct the translation. 

## Instructions To Reproduce the Issue:

1. Create the camera:

PerspectiveCameras(device=device, R=R_all[None, i, ...], T=T_all[None, i, ...], K=K_all[None, i, ...], in_ndc=False, image_size=[image_sizes[i],] )

with K that has its principal point out of the image centre (e.g., is in one of the corners of the image). 

2. Transform any points that should be inside the camera view.

**Comment by gkioxari** [comment]
Could you please provide a compact code snippet to reproduce the results? What is K, what is R, what is T and what is image size in the camera call above? And then what do you expect to get from the `get_ndc_camera_transform` and what do you actually get? 

Note that our NDC convention might be different than what you expect. Our NDC coordinate system is (+X left, +Y up, +Z from us to screen).

**Comment by xiexh20** [comment]
I have the same issue here. you can use this code to reproduce the error with pytorch=-0.6.2 installed. 

The `PerspectiveCameras` has a different constructor than previous version. And the `in_ndc` has to be manually set to False, which is different from previous version. This may cause problems for backward compatibility. 
[persp-bug.zip](https://github.com/facebookresearch/pytorch3d/files/8709501/persp-bug.zip)

**Comment by mantiuk** [comment]
Ok, I did more testing and figured out that this was not an issue.

The main problem was the non-standard camera coordinates, where +X and +Y were pointing the opposite way than for most software. 

This picture was very helpful: https://user-images.githubusercontent.com/5912647/76094441-8d748180-5fba-11ea-98d0-e0131e2e1d40.png and I wish it was linked somewhere in the documentation of camera classes.
