### ISSUE TITLE
Cannot pip install pytorch3d: No matching distribution found for pytorch3d

### ISSUE THREAD

**Issue by aj96** [facebookresearch/pytorch3d#1186]
I have been using this command to pip install pytorch3d for a while and it always worked until now: pip install --no-index --no-cache-dir pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py38_cu102_pyt1100/download.html

Now when I run this command, I get this error:
ERROR: Could not find a version that satisfies the requirement pytorch3d (from versions: none)
ERROR: No matching distribution found for pytorch3d

It does not matter which wheel version I try to install. I always get this error. Any idea what is wrong?

**Comment by Kautenja** [comment]
Getting the same error. Directly copying the recommended install command from the [INSTALL.md](https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md) does not work. I get the same results as @aj96 where it also fails to work for any version of python or pytorch that I plug into the URL. If this is no longer a supported installation pathway it should be removed from the installation instructions.

```
Looking in links: https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py38_cu102_pyt1110/download.html
ERROR: Could not find a version that satisfies the requirement pytorch3d (from versions: none)
ERROR: No matching distribution found for pytorch3d
```

**Comment by bottler** [comment]
The wheels form a supported pathway for their specific use case. As explained above, cuda 10.2 will not succeed.

**Comment by Kautenja** [comment]
I do see that now; however, the installation instructions indicate that 10.2 should be installable from a wheel, which should be changed if it is no longer the case...

```
We have prebuilt wheels with CUDA for Linux for PyTorch 1.11.0, for each of the supported CUDA versions, for Python 3.7, 3.8 and 3.9. This is for ease of use on Google Colab. These are installed in a special way. For example, to install for Python 3.8, PyTorch 1.11.0 and CUDA 10.2
```
