### ISSUE TITLE
Do volumes support dataparallel?

### ISSUE THREAD

**Issue by stalkerrush** [facebookresearch/pytorch3d#1195]
Hello,

Thank you for your great work on this repo. I tried to learn voxel prediction with the volumes class from pytorch3D, but when I used dataparallel to wrap the model on multiple GPUs, the following error occurs:
ValueError: densities must be either a list or a tensor with shape (batch_size, densities_dim, H, W, D).

This happens when the DataParallel is trying to do gather_map. Note that the learning runs fine when it's only on a single GPU.
So I wonder, do volumes support dataparallel, or is there any bug elsewhere?

Thank you!

**Comment by bottler** [comment]
I don't know of any special reason DataParallel wouldn't work. Can you print out the shape of `densities` before the error? Maybe also the traceback? Note that DistributedDataParallel is normally preferred to DataParallel even on a single maching.
