### ISSUE TITLE
Installation with python3.8 + torch1.7.1 + cu110

### ISSUE THREAD

**Issue by where2go947** [facebookresearch/pytorch3d#1198]
## Installation Questions

I'm trying to install pytorch3d in virtualenv on Ubuntu 20.04. 

I have installed python 3.8 and pytorch1.7.1 with cu110. Install wheels as:
```
pip install --no-index --no-cache-dir pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py38_cu110_pyt171/download.html
```
bur error raised as:
```
ERROR: Could not find a version that satisfies the requirement pytorch3d (from versions: none)
ERROR: No matching distribution found for pytorch3d
```
How could I find the satisfied version or alternative version lists?

Thanks in advance.

**Comment by where2go947** [comment]
Finally, I resolved the installation problem from local clone at [link](https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md#2-install-from-a-local-clone).

The environment has also changed to: `python=3.8, torch=1.8.0, cuda=11.1`

Just a suggestion, could you please list the stable version for wheels on Linux?

**Comment by bottler** [comment]
Currently only for PyTorch 11.1: There's CUDA 11.3 with Python 3.7, 3.8, 3.9 and 3.10. And there's CUDA 11.1 with Python 3.7.

**Comment by where2go947** [comment]
Thanks for the reply.

I mean maybe a list could be seen at the parent directory of `https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py38_cu113_pyt1110/download.html`

like [this](https://download.pytorch.org/whl/torch_stable.html)?

**Comment by where2go947** [comment]
> Using conda is strongly recommended.

Aha yes, I would like to, but previous work limits.
