### ISSUE TITLE
adding light to VolumeRenderer

### ISSUE THREAD

**Issue by fahdx** [facebookresearch/pytorch3d#1203]
this my renderer
`renderer = VolumeRenderer(
    raysampler=raysampler, raymarcher=raymarcher,
)`

I have 3D voxel without textures data (just zeros, ones represent occupancy) shape = [256,256,256]

`
volumes = Volumes(
            densities = shape[None],
            features = shape[None],
            voxel_size=voxel_size,
        )
`

how I can add lights to the scene ?
lights
`
l=lighting.PointLights(ambient_color=((0.5, 0.5, 0.5), ), diffuse_color=((0.3, 0.3, 0.3), ), specular_color=((0.2, 0.2, 0.2), ), location=((0,0,1), ))
l=lighting.AmbientLights(ambient_color=(55.0,55.0,55.0),device='cpu')
`

my render  ( its seems render does not have args for light)
`
rendered_images =renderer(cameras=cameras, volumes=volumes)
`

**Comment by bottler** [comment]
Currently in PyTorch3D the the lighting functionality is only designed to be used in the mesh renderer.
