### ISSUE TITLE
ImportError: /mnt/d/DESKTOP/headnerf/pytorch3d/pytorch3d/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC2ENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

### ISSUE THREAD

**Issue by icegaomu** [facebookresearch/pytorch3d#1207]
## 🐛 Bugs / Unexpected behaviors

i use this code to install torch ,and it's recommand by the paper writer 
`pip3 install torch==1.8.2+cu111 torchvision==0.9.2+cu111 -f https://download.pytorch.org/whl/lts/1.8/torch_lts.html `
and for cuda 11.3 there is only pip way ,no conda way
and install by this way
```
git clone https://github.com/facebookresearch/pytorch3d.git
    cd pytorch3d && pip install -e .
```
then i run my code and get mistakes as below
```
Traceback (most recent call last):
  File "Fitting3DMM/FittingNL3DMM.py", line 9, in <module>
    from NL3DMMRenderer import NL3DMMRenderer
  File "/mnt/d/DESKTOP/headnerf/Fitting3DMM/NL3DMMRenderer.py", line 3, in <module>
    from RenderUtils import ExtractLandMarkPosition, SoftSimpleShader
  File "/mnt/d/DESKTOP/headnerf/Fitting3DMM/RenderUtils.py", line 6, in <module>
    from pytorch3d.renderer import PointLights, Materials
  File "/mnt/d/DESKTOP/headnerf/pytorch3d/pytorch3d/renderer/__init__.py", line 7, in <module>
    from .blending import (
  File "/mnt/d/DESKTOP/headnerf/pytorch3d/pytorch3d/renderer/blending.py", line 11, in <module>
    from pytorch3d import _C
ImportError: /mnt/d/DESKTOP/headnerf/pytorch3d/pytorch3d/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC2ENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```
so i find some answer about the mispair between packages so i trying the follow code but nothing changed ,i don't know is the http right or not if it's false can you give the right way ?
`pip install  pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py38_cu111_pyt182/download.html`
```
Requirement already satisfied: pytorch3d in ./pytorch3d (0.6.2)
Requirement already satisfied: fvcore in /home/csy/anaconda3/envs/headnerf/lib/python3.8/site-packages (from pytorch3d) (0.1.5.post20210915)
Requirement already satisfied: iopath in /home/csy/anaconda3/envs/headnerf/lib/python3.8/site-packages (from pytorch3d) (0.1.9)
Requirement already satisfied: numpy in /home/csy/anaconda3/envs/headnerf/lib/python3.8/site-packages (from fvcore->pytorch3d) (1.22.3)
Requirement already satisfied: yacs>=0.1.6 in /home/csy/anaconda3/envs/headnerf/lib/python3.8/site-packages (from fvcore->pytorch3d) (0.1.8)
Requirement already satisfied: pyyaml>=5.1 in /home/csy/anaconda3/envs/headnerf/lib/python3.8/site-packages (from fvcore->pytorch3d) (5.4.1)
Requirement already satisfied: tqdm in /home/csy/anaconda3/envs/headnerf/lib/python3.8/site-packages (from fvcore->pytorch3d) (4.64.0)
Requirement already satisfied: termcolor>=1.1 in /home/csy/anaconda3/envs/headnerf/lib/python3.8/site-packages (from fvcore->pytorch3d) (1.1.0)
Requirement already satisfied: Pillow in /home/csy/anaconda3/envs/headnerf/lib/python3.8/site-packages (from fvcore->pytorch3d) (9.1.0)
Requirement already satisfied: tabulate in /home/csy/anaconda3/envs/headnerf/lib/python3.8/site-packages (from fvcore->pytorch3d) (0.8.9)
Requirement already satisfied: portalocker in /home/csy/anaconda3/envs/headnerf/lib/python3.8/site-packages (from iopath->pytorch3d) (2.4.0)
```
and the follow is my conda list
```
_libgcc_mutex             0.1                        main    conda-forge
_openmp_mutex             4.5                       1_gnu    defaults
addict                    2.4.0                    pypi_0    pypi
blas                      1.0                         mkl    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
ca-certificates           2022.5.18.1          ha878542_0    conda-forge
certifi                   2022.5.18.1      py38h578d9bd_0    conda-forge
cffi                      1.15.0           py38hd667e15_1    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
charset-normalizer        2.0.12                   pypi_0    pypi
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
cudatoolkit               11.1.1               h6406543_8    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
face-alignment            1.3.5                    pypi_0    pypi
freetype                  2.10.4               h0708190_1    conda-forge
future                    0.18.2           py38h578d9bd_5    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
fvcore                    0.1.5.post20210915            py38    fvcore
idna                      3.3                      pypi_0    pypi
imageio                   2.18.0                   pypi_0    pypi
install                   1.3.5                    pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
iopath                    0.1.9                      py38    iopath
jpeg                      9e                   h7f8727e_0    defaults
kornia                    0.6.4                    pypi_0    pypi
ld_impl_linux-64          2.35.1               h7274673_9    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 9.3.0               h5101ec6_17    defaults
libgomp                   9.3.0               h5101ec6_17    defaults
libpng                    1.6.37               h21135ba_2    conda-forge
libstdcxx-ng              9.3.0               hd4cf53a_17    defaults
libtiff                   4.0.10            hc3755c2_1005    conda-forge
llvmlite                  0.38.0                   pypi_0    pypi
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
mkl                       2021.4.0           h06a4308_640    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
mkl-service               2.4.0            py38h497a2fe_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
mkl_fft                   1.3.1            py38hd3c417c_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
mkl_random                1.2.2            py38h1abd341_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
mmcv-full                 1.2.7                    pypi_0    pypi
ncurses                   6.3                  h7f8727e_2    defaults
networkx                  2.8                      pypi_0    pypi
ninja                     1.7.2                         0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
numba                     0.55.1                   pypi_0    pypi
numpy                     1.21.6                   pypi_0    pypi
numpy-base                1.22.3           py38hf524024_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
nvidiacub                 1.10.0                        0    bottler
olefile                   0.46               pyh9f0ad1d_1    conda-forge
opencv-contrib-python     4.4.0.46                 pypi_0    pypi
opencv-python             4.3.0.36                 pypi_0    pypi
openssl                   1.1.1n               h7f8727e_0    defaults
packaging                 21.3                     pypi_0    pypi
pillow                    9.1.0                    pypi_0    pypi
pip                       21.2.4           py38h06a4308_0    defaults
portalocker               2.4.0            py38h578d9bd_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
pyparsing                 3.0.8                    pypi_0    pypi
pyqt5                     5.15.6                   pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.10.1                  pypi_0    pypi
python                    3.8.8                hdb3f193_5    defaults
python_abi                3.8                      2_cp38    conda-forge
pytorch3d                 0.6.2                     dev_0    <develop>
pywavelets                1.3.0                    pypi_0    pypi
pyyaml                    5.4.1            py38h497a2fe_0    conda-forge
readline                  8.1.2                h7f8727e_1    defaults
requests                  2.27.1                   pypi_0    pypi
scikit-image              0.19.2                   pypi_0    pypi
scipy                     1.8.0                    pypi_0    pypi
setuptools                61.2.0           py38h06a4308_0    defaults
six                       1.16.0             pyh6c4a22f_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
sqlite                    3.38.2               hc218d9a_0    defaults
tabulate                  0.8.9              pyhd8ed1ab_0    conda-forge
termcolor                 1.1.0                      py_2    conda-forge
tifffile                  2022.4.28                pypi_0    pypi
tk                        8.6.11               h1ccaba5_0    defaults
torch                     1.8.2+cu111              pypi_0    pypi
torchaudio                0.10.1+rocm4.1           pypi_0    pypi
torchvision               0.11.2+cu111             pypi_0    pypi
tqdm                      4.64.0             pyhd8ed1ab_0    conda-forge
typing-extensions         4.2.0                hd8ed1ab_1    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
typing_extensions         4.2.0              pyha770c72_1    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
urllib3                   1.26.9                   pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0    defaults
xz                        5.2.5                h7b6447c_0    defaults
yacs                      0.1.8              pyhd8ed1ab_0    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
yapf                      0.32.0                   pypi_0    pypi
zlib                      1.2.12               h7f8727e_2    defaults
zstd                      1.4.9                ha95c52a_0    conda-forge
```
Thanks a lot for answer this questions!
and i try to conda install pytorch3d -c pytorch3d to install but it will install the cpu version pytorch 1.10x which make more error and make the torch version confused

**Comment by sjtuytc** [comment]
I meet the same problem.

**Comment by bottler** [comment]
The install from source seems to have used a different version of PyTorch than the one in the environment where you are trying to run. I think if you try again carefully it will work.

Conda packages depend on conda packages and your torch is a pip install. That is why `conda install pytorch3d -c pytorch3d` tries to install torch (which is not what you want. You could try (in a new environment) installing the versions of torch and torchvision you want, and then pytorch3d.

**Comment by icegaomu** [comment]
Thanks a lot ! I already run my code success ,i used the WSL2 ubuntu 20.04 ,and i think it maybe  also work in other linux system .
the firest thing is get cuda 11.3 which is compare with the pytorch3d the link is here https://developer.nvidia.cn/cuda-11.3.0-download-archive?target_os=Linux  `conda install pytorch3d -c pytorch3d` correct,it's important to add
```
 export PATH="/usr/local/cuda-11.3/bin:$PATH"
export LD_LIBRARY_PATH="/usr/local/cuda-11.3/lib64:$LD_LIBRARY_PATH"
```
to your bashrc then source and use nvcc -V to check if you get the right version
, and then the cudnn  [Download cuDNN v8.2.0 (April 23rd, 2021), for CUDA 11.x](https://developer.nvidia.com/rdp/cudnn-archive#a-collapse820-111) 
 https://developer.nvidia.com/rdp/cudnn-archive  ,final you just need `conda install pytorch3d -c pytorch3d`  and it will work !
And here is my conda list for suggest .
`# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    conda-forge
_openmp_mutex             4.5                       1_gnu    defaults
blas                      1.0                         mkl    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
brotlipy                  0.7.0           py38h497a2fe_1001    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
bzip2                     1.0.8                h7f98852_4    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
certifi                   2021.10.8        py38h578d9bd_2    conda-forge
cffi                      1.15.0           py38hd667e15_1    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
charset-normalizer        2.0.12             pyhd8ed1ab_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
cryptography              35.0.0           py38ha5dfef3_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
cudatoolkit               11.3.1               h2bc3f7f_2    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
face-alignment            1.3.5                    pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
freetype                  2.10.4               h0708190_1    conda-forge
fvcore                    0.1.5.post20210915            py38    fvcore
gmp                       6.2.1                h58526e2_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
gnutls                    3.6.13               h85f3911_1    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
idna                      3.3                pyhd8ed1ab_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
imageio                   2.18.0                   pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
iopath                    0.1.9                      py38    iopath
jpeg                      9e                   h7f8727e_0    defaults
kornia                    0.6.4                    pypi_0    pypi
lame                      3.100             h7f98852_1001    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
ld_impl_linux-64          2.35.1               h7274673_9    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 9.3.0               h5101ec6_17    defaults
libgomp                   9.3.0               h5101ec6_17    defaults
libiconv                  1.16                 h516909a_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libstdcxx-ng              9.3.0               hd4cf53a_17    defaults
libtiff                   4.0.10            hc3755c2_1005    conda-forge
libuv                     1.40.0               h7b6447c_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
llvmlite                  0.38.0                   pypi_0    pypi
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
mkl                       2021.4.0           h06a4308_640    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
mkl-service               2.4.0            py38h497a2fe_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
mkl_fft                   1.3.1            py38hd3c417c_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
mkl_random                1.2.2            py38h1abd341_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
ncurses                   6.3                  h7f8727e_2    defaults
nettle                    3.6                  he412f7d_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
networkx                  2.8                      pypi_0    pypi
numba                     0.55.1                   pypi_0    pypi
numpy                     1.21.6                   pypi_0    pypi
numpy-base                1.22.3           py38hf524024_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
nvidiacub                 1.10.0                        0    bottler
olefile                   0.46               pyh9f0ad1d_1    conda-forge
opencv-python             4.3.0.36                 pypi_0    pypi
openh264                  2.1.1                h780b84a_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
openssl                   1.1.1n               h7f8727e_0    defaults
packaging                 21.3                     pypi_0    pypi
pillow                    9.1.0                    pypi_0    pypi
pip                       21.2.4           py38h06a4308_0    defaults
portalocker               2.4.0            py38h578d9bd_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
pyparsing                 3.0.8                    pypi_0    pypi
pyqt5                     5.15.6                   pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.10.1                  pypi_0    pypi
pysocks                   1.7.1            py38h578d9bd_5    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
python                    3.8.8                hdb3f193_5    defaults
python_abi                3.8                      2_cp38    conda-forge
pytorch                   1.11.0          py3.8_cuda11.3_cudnn8.2.0_0    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytorch3d                 0.6.2           py38_cu113_pyt1110    pytorch3d
pywavelets                1.3.0                    pypi_0    pypi
pyyaml                    5.4.1            py38h497a2fe_0    conda-forge
readline                  8.1.2                h7f8727e_1    defaults
requests                  2.27.1             pyhd8ed1ab_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
scikit-image              0.19.2                   pypi_0    pypi
scipy                     1.8.0                    pypi_0    pypi
setuptools                61.2.0           py38h06a4308_0    defaults
six                       1.16.0             pyh6c4a22f_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
sqlite                    3.38.2               hc218d9a_0    defaults
tabulate                  0.8.9              pyhd8ed1ab_0    conda-forge
termcolor                 1.1.0                      py_2    conda-forge
tifffile                  2022.4.28                pypi_0    pypi
tk                        8.6.11               h1ccaba5_0    defaults
torch                     1.11.0                   pypi_0    pypi
torchaudio                0.11.0               py38_cu113    pytorch
torchvision               0.12.0               py38_cu113    pytorch
tqdm                      4.64.0             pyhd8ed1ab_0    conda-forge
typing_extensions         4.2.0              pyha770c72_1    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
urllib3                   1.26.9             pyhd8ed1ab_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
wheel                     0.37.1             pyhd3eb1b0_0    defaults
xz                        5.2.5                h7b6447c_0    defaults
yacs                      0.1.8              pyhd8ed1ab_0    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zlib                      1.2.12               h7f8727e_2    defaults
zstd                      1.4.9                ha95c52a_0    conda-forge
`
@sjtuytc  if you need help please give more information or trying to follow my pipeline

**Comment by icegaomu** [comment]
the conda pipeline is really suggest

**Comment by FarisHijazi** [comment]
any time you try to install, make sure to add --reinstall or `-U`

try
```
pip install -U pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py38_cu111_pyt182/download.html
```
