### ISSUE TITLE
Texure reconstruction with given mesh, images and camera pose  

### ISSUE THREAD

**Issue by Jiakui** [facebookresearch/pytorch3d#1213]
Dear author , 

In the code base  I saw that we can load and save textured mesh.  I wonder , can we reconstruct texture with given mesh , images and corresponding  camera poses , for example , from the output of  Neus or VolSDF.   

In principle, this means we should be able to make the texture  (the TextureUV object ? )  differenciable when it is rendered with pytorch3d.  I am not sure how to achieve this with pytorch3d .  

For the above purpose, can you teach me how to do it?

Thanks so much !

**Comment by bottler** [comment]
This sounds like the sort of thing you could use PyTorch3D components (all of the relevant ones of which are differentiable) to build a model for. The fit_textured_mesh tutorial is a good thing to understand first. The specifics of modelling in your scenario is not something we can help with.
