### ISSUE TITLE
Is it possible to get depth map while rendering a colored volume

### ISSUE THREAD

**Issue by swwzn714** [facebookresearch/pytorch3d#1216]
Dear pytorch3d team members:

1. I am currently using **VolumeRenderer** to render 2D images from colored **Volumes** object and it works well. However, the output of the renderer is 
![image](https://user-images.githubusercontent.com/41735931/171212952-ca868023-c946-4f70-8099-cc37cbb05239.png)

The first element of the tuple is the RGBA images. I wonder if it is possible to get the depth channel in volumetric rendering? 

2. For those rendered images, is that a method to unproject them back to the **Volumes** object?

Sincerely waiting for you reply!

**Comment by bottler** [comment]
What is the A in RGBA? And which depth do you want (light can be emitted from more than one part of the volume)?
