### ISSUE TITLE
what exactly is the parameters of the camera in pulsar_multiview.py

### ISSUE THREAD

**Issue by lai-pf** [facebookresearch/pytorch3d#1218]
waht exactly is the parameters of the camera in pulsar_multiview.py
![image](https://user-images.githubusercontent.com/32856760/171998344-246f9eaf-04c5-44ba-82ee-97dce25437c8.png)

when I try to reconstruct the teapot with 8 views image, I was confused by the cam_params rotation angle, what is the angle relate to? and the first three components for camera position is also hard to understand.
I think I need some help or specificly doc to understand these params

**Comment by neverix** [comment]
Is [this](https://github.com/facebookresearch/pytorch3d/blob/741777b5b5bdfb498173d3911bdf4978b49a12ec/pytorch3d/renderer/points/pulsar/renderer.py#L390) helpful?

**Comment by lai-pf** [comment]
> 
I try to use my images and angles to reconstruct, result seems not good.
these are my images 
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/32856760/172029685-4bf6c243-20e1-44f9-b457-0786250cb3a6.png">
And this is result that I've got
<img width="863" alt="image" src="https://user-images.githubusercontent.com/32856760/172029742-064a88ab-4b8d-4754-b498-6442df499740.png">
I try it based on the code pulsar_multiview.py. The rotation angle params I set as follows
![image](https://user-images.githubusercontent.com/32856760/172029786-2a7af45b-ef53-414f-b770-1486d7bf76fe.png)
did I use it in the wrong way? or pulsar can only get this result? the performance I need is like pulsar's paper show
<img width="772" alt="image" src="https://user-images.githubusercontent.com/32856760/172029841-5403f414-f22e-4f84-9636-aa76f4d0cfb9.png">
pulsar is an amazing work,I really love it,but it seems need more specific docs and annotation, and if pulsar team can open those code example in paper , that would be helpful

**Comment by neverix** [comment]
I think in your case you need to save the camera positions and angles, then put position in the first 3 values and angles in the next 3. You should also record focal length and sensor width for the next to - the precise values don't matter, the ratio should be correct for the FOV to be the same (correct me if I am wrong)

I am also struggling to get good results optimizing btw.

**Comment by lai-pf** [comment]
> I think in your case you need to save the camera positions and angles, then put position in the first 3 values and angles in the next 3. You should also record focal length and sensor width for the next to - the precise values don't matter, the ratio should be correct for the FOV to be the same (correct me if I am wrong)
> 
> I am also struggling to get good results optimizing btw.

Thanks for your reply, and I've write an email to your Gmail, some question about pulsar lighting. May be we can help each other. Thanks again.
