### ISSUE TITLE
import load_obj raise "ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory"

### ISSUE THREAD

**Issue by Alichua** [facebookresearch/pytorch3d#1224]
Description:
I use Dockerfile to create a container, inside which I install Miniconda. And eventually inside a Conda virtual environment, I install the dependencies of Pytorch3d. All these steps are performed in Dockerfile.
Inside this virtual environment, When I import load_obj, the ERROR raised:

ERROR LOG:
Traceback (most recent call last):
  File "pytorch3d-renderer/my_renderer.py", line 17, in <module>
    from pytorch3d.io import load_obj
  File "/home/conda/envs/chua_env_3d/lib/python3.8/site-packages/pytorch3d/io/__init__.py", line 4, in <module>
    from .obj_io import load_obj, load_objs_as_meshes, save_obj
  File "/home/conda/envs/chua_env_3d/lib/python3.8/site-packages/pytorch3d/io/obj_io.py", line 14, in <module>
    from pytorch3d.renderer import TexturesAtlas, TexturesUV
  File "/home/conda/envs/chua_env_3d/lib/python3.8/site-packages/pytorch3d/renderer/__init__.py", line 3, in <module>
    from .blending import (
  File "/home/conda/envs/chua_env_3d/lib/python3.8/site-packages/pytorch3d/renderer/blending.py", line 9, in <module>
    from pytorch3d import _C
ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory

It seems like the pytorch3d intended to use CUDA 10.1, this is very weird since I force all the CUDA related package to use CUDA 10.2 version. As you can see from the Dockerfile below(torch/torchvison/cudatoolkit/pytorch3d are all asked to be CUDA 10.2 version):

*****Dockerfile:
FROM python3.8

ADD . /home/pytorch3d_renderer

WORKDIR /home

RUN apt-get install -y wget

RUN wget https://github.com/NVIDIA/cub/archive/1.10.0.tar.gz
RUN	tar xzf /home/1.10.0.tar.gz

RUN rm -rf /home/conda && \
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /home/miniconda.sh && \
    /bin/bash /home/miniconda.sh -b -p /home/conda && \
    rm /home/miniconda.sh 

ENV PATH /home/conda/bin:$PATH

RUN conda update conda \
    && conda env create -f /home/pytorch3d_renderer/env_config.yml
    
\# ADD CONDA ENV PATH TO LINUX PATH 
ENV PATH /home/conda/envs/chua_env_3d/bin:$PATH
ENV CONDA_DEFAULT_ENV chua_env_3d

\# MAKE ALL BELOW RUN COMMANDS USE THE NEW CONDA ENVIRONMENT
SHELL ["conda", "run", "-n", "chua_env_3d", "/bin/bash", "-c"]

RUN pip install -r /home/pytorch3d_renderer/pip_requirements.txt

ENV CUB_HOME "/home/cub-1.10.0"

RUN conda install cudatoolkit=10.2 -c anaconda -c nvidia

RUN pip install torch==1.9.0+cu102 -f https://download.pytorch.org/whl/torch_stable.html && \
	pip install torchvision==0.10.0+cu102 -f https://download.pytorch.org/whl/torch_stable.html

ENV FORCE_CUDA 1

RUN pip install pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py38_cu102_pyt190/download.html
*****End of Dockerfile

Also, inside the file "env_config.yml" and "pip_requirements.txt", the packages collected are quite simple, as shown below:

Inside env_config.yml:
name: chua_env_3d
channels:
  \- defaults
dependencies:
  \- pip=21.2.4
  \- python=3.8.13
  \- pip 
 
Inside pip_requirements.txt:
matplotlib
opencv-python
pandas
scikit-image
scipy
tensorboard
torchsummary
tqdm
imageio
plotly

These packages are installed inside the virtual environment, before torch/torchvison/cudatoolkit/pytorch3d are installed.

So, why would pytorch3d look for the "libcudart.so.10.1", since I specify the "py38_cu102_pyt190"? This really has haunted me for a loooong time. Can someone give me any suggestions? Thanks in advance

**Comment by bottler** [comment]
There isn't such a pytorch3d wheel, so you are getting a (probably old) pypi build of pytorch3d.

We recommend you install torch, torchvision and pytorch3d using conda - this is supported and much easier.

**Comment by Alichua** [comment]
> There isn't such a pytorch3d wheel, so you are getting a (probably old) pypi build of pytorch3d.
> 
> We recommend you install torch, torchvision and pytorch3d using conda - this is supported and much easier.

That explains a lot. I receive the success message from docker so I didn't check the installation details, from the log I found that it did install an old version instead. Thanks!

**Comment by neverix** [comment]
@bottler Hello, sorry for pinging on a dead issue. I noticed that there used to be wheels for CUDA 10.2. Have they been removed? https://github.com/facebookresearch/pytorch3d/blob/364a7dcaf4b285cc93c70e0b5d9eb9bbf42389a5/INSTALL.md
