### ISSUE TITLE
Rendering with .mtl file

### ISSUE THREAD

**Issue by ShairozS** [facebookresearch/pytorch3d#123]
I'm following the example outlined in the "Render Textured Meshes" tutorial, and while my .obj file loads fine I'm not sure if or how I'm able to render it with an associated .mtl file present in the same folder? I'm using data downloaded from ShapeNet. Below is a screenshot of what I'm trying:

![temp](https://user-images.githubusercontent.com/14152951/77490063-141cc180-6df7-11ea-9c18-eb31956f667f.png)

**Comment by nikhilaravi** [comment]
Hi @ShairozS, is the name of your `.mtl` file referenced correctly at the top of your `.obj` file? 

To debug you can try loading the `.obj` and seeing if any texture images are loaded:
```
verts, faces, aux = load_obj(f_obj, load_textures=True)
print(aux.texture_images)
``

Also note that many ShapeNet `.obj` files have multiple texture images per mesh -- we currently only support one texture image for the whole mesh. 

We are in currently in the process of adding support for specifying the textures as a texture atlas which will enable ShapeNet meshes to be loaded with full texture - this will be released soon.

**Comment by ShairozS** [comment]
@nikhilaravi 
Thanks for the quick response! Below is the top of the .obj file

![temp](https://user-images.githubusercontent.com/14152951/77543606-2df4ed80-6e65-11ea-8db0-eaa918d58439.png)

the .mtl file
![temp2](https://user-images.githubusercontent.com/14152951/77543637-3816ec00-6e65-11ea-8ec3-21fbcebe9b5e.png)

and the result of the code snippet you posted, which seems to indicate that material properties are actually being loaded.

![temp0](https://user-images.githubusercontent.com/14152951/77543719-4d8c1600-6e65-11ea-8078-dd61170e09e5.png)

To replicate you can download one of the ShapeNet folders, the one I'm using in contained in the following synset:
http://shapenet.cs.stanford.edu/shapenet/obj-zip/02828884.zip

**Comment by nikhilaravi** [comment]
@ShairozS I checked the data you sent and for the model you were had tried in the description of the issue `107c0b6b32282102493c8fb81dc7c4da` -- there isn't an `image` folder and the `.mtl` file only has material properties and no texture image so the output you saw was the expected output. 

I tested loading the textures for the model you mentioned in the comment above  `1a40eaf5919b1b3f3eaa2b95b99dae6` and it worked correctly.  

```
import os
from pytorch3d.io import load_obj
DATA_DIR = "test_shapenet"
f_obj = os.path.join(DATA_DIR, "model.obj")
verts, faces, aux = load_obj(f_obj, load_textures=True)
print("texture images", aux.texture_images)
print("materials", aux.material_colors)
```
Output:
```
texture images {'material_2_1_8': tensor([[[0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039],
         ...,
         [0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039]],

        [[0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039],
         ...,
         [0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039]],

        [[0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039],
         ...,
         [0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039]],

        ...,

        [[0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039],
         ...,
         [0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039]],

        [[0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039],
         ...,
         [0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039]],

        [[0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039],
         ...,
         [0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039]]])}
materials {'material_2_1_8': {'shininess': tensor([96.0784]), 'ambient_color': tensor([0., 0., 0.]), 'diffuse_color': tensor([0.6400, 0.6400, 0.6400]), 'specular_color': tensor([0.5000, 0.5000, 0.5000])}, 'material_0_24': {'shininess': tensor([96.0784]), 'ambient_color': tensor([0., 0., 0.]), 'diffuse_color': tensor([0.4706, 0.2322, 0.0627]), 'specular_color': tensor([0.5000, 0.5000, 0.5000])}}
```

Perhaps it is a path issue? Can you check if you are able to load the texture image by doing this:

```
from pytorch3d.io.obj_io import _read_image
image = _read_image("./images/texture0.jpg")
```

**Comment by wangsen1312** [comment]
It seems you miss the 
`usemtl material`
in the obj file

**Comment by nikhilaravi** [comment]
@ShairozS if you were able to resolve this problem please close the issue.
