### ISSUE TITLE
Why does se3_log_map give strange result?

### ISSUE THREAD

**Issue by ootts** [facebookresearch/pytorch3d#1239]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## 🐛 Bugs / Unexpected behaviors
I have a 4x4 pose matrix A, and se3_exp_map(se3_log_map(A)) is far from A.

## Instructions To Reproduce the Issue:

Please include the following (depending on what the issue is):

1. Any changes you made (`git diff`) or code you wrote
```
pose=torch.tensor([[-0.9881, 0.1425, -0.0576, 0.6478],
                                  [0.1381, 0.6588, -0.7395, 0.1930],
                                  [-0.0674, -0.7387, -0.6707, 0.1009],
                                  [0.0000, 0.0000, 0.0000, 1.0000]])
dof6 = se3_log_map(pose[None].permute(0, 2, 1))[0]
print(dof6)
pose2 = se3_exp_map(dof6[None]).permute(0, 2, 1)[0]
print(pose, pose2)
```
2. What you observed (including the full logs):
```
tensor([ 0.1095,  0.5036,  0.6949,  0.1774,  2.1725, -0.9754])
tensor([[-0.9881,  0.1425, -0.0576,  0.6478],
        [ 0.1381,  0.6588, -0.7395,  0.1930],
        [-0.0674, -0.7387, -0.6707,  0.1009],
        [ 0.0000,  0.0000,  0.0000,  1.0000]]) tensor([[-0.7197,  0.3963,  0.5700,  0.6478],
        [-0.1626,  0.7020, -0.6934,  0.1930],
        [-0.6749, -0.5918, -0.4408,  0.1009],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])


```

Please also simplify the steps as much as possible so they do not require additional resources to
   run, such as a private dataset.

**Comment by tomer-grin** [comment]
Try to play with `eps` and `cos_bound` argument in the functions.

https://pytorch3d.readthedocs.io/en/latest/modules/transforms.html
From the docs:
> Note that for any valid 4x4 transform matrix, the following identity holds: ` se3_exp_map(se3_log_map(transform)) == transform `
> 
> The conversion has a singularity around (transform=I) which is handled by clamping controlled with the eps and cos_bound arguments.


try to decrease these arguments (avoiding singularity on the edges) and see if it works.
