### ISSUE TITLE
Can I render an obj file composed of vertice triangle color(none texture)?

### ISSUE THREAD

**Issue by Chanwooong** [facebookresearch/pytorch3d#124]
## ❓ Questions on how to use PyTorch3D

In the tutorial, it seems that the obj file can be rendered when there is a texture.
However, I am wondering if rendering is possible for obj files composed of (vertices, triangles, and colors.)

Sorry for the frequent questions.

**Comment by Chanwooong** [comment]
By studying more documents, I now kwon how

**Comment by Gaozhongpai** [comment]
Can you provide the information of how to render an obj file composed of vertice triangle color(none texture)?
