### ISSUE TITLE
How can I define my a plane in PyTorch3D ?

### ISSUE THREAD

**Issue by orgicus** [facebookresearch/pytorch3d#1242]
## ❓ How can I define my a plane in PyTorch3D ?

I'm new to PyTorch3D and I'm trying to define a (subdivided) plane.

What I've tried to do is mirror the structure I found in [PyTorch3D's ico_sphere.py](https://github.com/facebookresearch/pytorch3d/blob/main/pytorch3d/utils/ico_sphere.py). 

This is my attempt of tweaking the above for a basic quad plane from 2 triangles:

```python
import torch
from pytorch3d.ops.subdivide_meshes import SubdivideMeshes
from pytorch3d.structures.meshes import Meshes


# Vertex coordinates for a level 0 plane.
_plane_verts0 = [
    [-0.5000,-0.5000, 0.0000], # TL
    [+0.5000,-0.5000, 0.0000], # TR
    [+0.5000,+0.5000, 0.0000], # BR
    [-0.5000,+0.5000, 0.0000]  # BL
]

# Faces for level 0 plane
_plane_faces0 = [
    [2, 1, 0],
    [0, 3, 2]
]


def plane(level: int = 0, device=None):
    """
    Create verts and faces for a unit plane, with all faces oriented
    consistently.

    Args:
        level: integer specifying the number of iterations for subdivision
               of the mesh faces. Each additional level will result in four new
               faces per face.
        device: A torch.device object on which the outputs will be allocated.

    Returns:
        Meshes object with verts and faces.
    """
    if device is None:
        device = torch.device("cpu")
    if level < 0:
        raise ValueError("level must be >= 0.")
    if level == 0:
        verts = torch.tensor(_plane_verts0, dtype=torch.float32, device=device)
        faces = torch.tensor(_plane_faces0, dtype=torch.int64, device=device)

    else:
        mesh = plane(level - 1, device)
        subdivide = SubdivideMeshes()
        mesh = subdivide(mesh)
        verts = mesh.verts_list()[0]
        verts /= verts.norm(p=2, dim=1, keepdim=True)
        faces = mesh.faces_list()[0]
    return Meshes(verts=[verts], faces=[faces])
```

The plane with no subdivision (level=0) seems fine. The issue I'm having is when I subdivide the plane, the result shows holes / flipped normals by the looks of it:

![pytorch3d_subdivided_plane](https://user-images.githubusercontent.com/189031/177364468-ae4279f7-a906-4cdb-bfde-d089a4c69cba.png)

I've tried to change the face indices a bit (offsetting the starting point, using CW vs CCW winding order, etc.), but the result is the same, so I'm not sure if the issue with the **plane geometry** itself, **subdivision**, or **both**.

(I haven't found a good way to visualise face normals. I've tried plotly's Mesh3D option, but as far as I can tell it's doing double sided rendering and I couldn't figure out how to set it's renderer to render triangles single sided only. Any tips on visually debugging are the geometry also welcome)

I've tried something slightly different: copying the vertex and face from a (triangulated) plane drawn in Blender:
```python
'''
# Blender v2.82 (sub 7) OBJ File: ''
# www.blender.org
mtllib plane.mtl
o Plane
v -1.000000 0.000000 1.000000
v 1.000000 0.000000 1.000000
v -1.000000 0.000000 -1.000000
v 1.000000 0.000000 -1.000000
vt 1.000000 0.000000
vt 0.000000 1.000000
vt 0.000000 0.000000
vt 1.000000 1.000000
vn 0.0000 1.0000 0.0000
usemtl None
s off
f 2/1/1 3/2/1 1/3/1
f 2/1/1 4/4/1 3/2/1

obj face indices start at 1
-1 version:
f 1/0/0 2/1/0 0/2/0 -> [1, 2, 0]
f 1/0/0 3/3/0 2/1/0 -> [1, 3, 2]
'''

# Vertex coordinates for a level 0 plane.
_plane_verts0 = [
    [-1.000000, 0.000000, 1.000000],
    [1.000000, 0.000000, 1.000000],
    [-1.000000, 0.000000, -1.000000],
    [1.000000, 0.000000, -1.000000],

]

# Faces for level 0 plane
_plane_faces0 = [
    [1, 2, 0],
    [1, 3, 2]
]
```

This didn't work either.

I would like to understand what the correct face index winding is for PyTorch3D (so I can potentially define other procedural meshes).

Any hints/tips to move forward are greatly appreciated :)

P.S. Thank you for releasing the source code: it's a an awesome project and I can't wait to learn more about 3D ML though it.
(Additionally, I've posted this as a [question on stackoverflow](https://stackoverflow.com/questions/72862446/how-to-define-pytorch3d-plane-geometry) as well)

**Comment by bottler** [comment]
The faces after subdividing are in a consistent order.

For example (based on your code)
```
import torch
from pytorch3d.ops.subdivide_meshes import SubdivideMeshes
from pytorch3d.structures.meshes import Meshes
import plotly.graph_objects as pgo

sm = SubdivideMeshes()

# Vertex coordinates for a level 0 plane.
_plane_verts0 = [
    [-0.5000,-0.5000, 0.0000], # TL
    [+0.5000,-0.5000, 0.0000], # TR
    [+0.5000,+0.5000, 0.0000], # BR
    [-0.5000,+0.5000, 0.0000]  # BL
]

# Faces for level 0 plane
_plane_faces0 = [
    [2, 1, 0],
    [0, 3, 2]
]

a0 = Meshes (verts = [torch.tensor(_plane_verts0)], faces = [torch.tensor(_plane_faces0)])
a1 = sm(a0)

# plot the new vertices
di = {i:j for i,j in zip ("xyz", [a1.verts_list()[0][:,i] for i in range(3)])}
scatter = pgo.Scatter3d(**di, mode="text", text=[str(i) for i in range(a1.verts_list()[0].shape[0])])
axis={"visible":False}
pgo.Figure(data=scatter, layout={"scene":{"xaxis":axis, "yaxis":axis, "zaxis": axis}})

print(a1.verts_list())
print(a1.faces_list())
```

produces
```
[tensor([[-0.5000, -0.5000,  0.0000],
         [ 0.5000, -0.5000,  0.0000],
         [ 0.5000,  0.5000,  0.0000],
         [-0.5000,  0.5000,  0.0000],
         [ 0.0000, -0.5000,  0.0000],
         [ 0.0000,  0.0000,  0.0000],
         [-0.5000,  0.0000,  0.0000],
         [ 0.5000,  0.0000,  0.0000],
         [ 0.0000,  0.5000,  0.0000]])]
[tensor([[2, 7, 5],
         [0, 6, 5],
         [1, 4, 7],
         [3, 8, 6],
         [0, 5, 4],
         [2, 5, 8],
         [4, 5, 7],
         [8, 5, 6]])]
```
and

![image](https://user-images.githubusercontent.com/669761/177388386-16c63124-2b21-459d-b78d-64d40ae021c4.png)

You can see all the faces of the subdivided mesh are clockwise in this case. Normalsl should therefore all end up calculated in the same direction. How did you make your visualisations?

**Comment by orgicus** [comment]
Hi,

Thank you so much for the swift response.

The notes and ready to run snippet is super helpful (and great to learn from).

Interesting! Does this mean it may have something to do with the visualisation then ?

The visualisation is the sihouette rendering from [Fit Mesh via Rendering PyTorch3D tutorial](https://pytorch3d.org/tutorials/fit_textured_mesh) (pasting the relevant code for reference here:

```python
# Rasterization settings for silhouette rendering  
sigma = 1e-4
raster_settings_silhouette = RasterizationSettings(
    image_size=128, 
    blur_radius=np.log(1. / 1e-4 - 1.)*sigma, 
    faces_per_pixel=50, 
)

# Silhouette renderer 
renderer_silhouette = MeshRenderer(
    rasterizer=MeshRasterizer(
        cameras=camera, 
        raster_settings=raster_settings_silhouette
    ),
    shader=SoftSilhouetteShader()
)

# Render silhouette images.  The 3rd channel of the rendering output is 
# the alpha/silhouette channel
silhouette_images = renderer_silhouette(meshes, cameras=cameras, lights=lights)
target_silhouette = [silhouette_images[i, ..., 3] for i in range(num_views)]

# Visualize silhouette images
image_grid(silhouette_images.cpu().numpy(), rows=4, cols=5, rgb=False)
plt.show()
```

`meshes` would be the result of `plane(level=1,device=device)`

I've tried a few more things and realise I didn't really understand how subdivison was used in ico_sphere (and I currently still don't 100% get it):

```python
else:
        mesh = ico_sphere(level - 1, device)
        subdivide = SubdivideMeshes()
        mesh = subdivide(mesh)
        verts = mesh.verts_list()[0]
        verts /= verts.norm(p=2, dim=1, keepdim=True)
        faces = mesh.faces_list()[0]
    return Meshes(verts=[verts], faces=[faces])
```

I feel I need to read/understand more about how SubdivideMeshes/vert_list() and the bit of numpy magic) above works.

In the meantime, I can get the expected output with a slightly different approach:

```python
def plane(level: int = 0, device=None):
    if device is None:
        device = torch.device("cpu")
    if level < 0:
        raise ValueError("level must be >= 0.")
    if level == 0:
        verts = torch.tensor(_plane_verts0, dtype=torch.float32, device=device)
        faces = torch.tensor(_plane_faces0, dtype=torch.int64, device=device)
        return Meshes(verts=[verts], faces=[faces])
    else:
        subdivide = SubdivideMeshes()
        mesh = plane(0, device)
        for x in range(level):
          mesh = subdivide(mesh)
        return mesh
```

For reference I'm attaching a downloaded notebook I've just ran some tests on (including your notes above):
[PyTorch3DPlane.zip](https://github.com/facebookresearch/pytorch3d/files/9049971/PyTorch3DPlane.zip)

These are a few plots of the different subdivision approaches:

![a0 subdivided via iteration](https://user-images.githubusercontent.com/189031/177425862-033ff154-cc8f-4659-abcf-3061fa3f26f2.png)
![a1](https://user-images.githubusercontent.com/189031/177425859-b96a30ae-7f94-4737-88a8-5b06cd58a282.png)
![plane() subdivided a-la ico_sphere](https://user-images.githubusercontent.com/189031/177425857-d038cdc0-e508-4ec0-9da6-bfb4ebb2a754.png)
![plane() subdivided via iteration](https://user-images.githubusercontent.com/189031/177425866-d48e96e7-7816-4275-b68c-a297e3d422a7.png)

**Comment by orgicus** [comment]
@bottler Many thanks for your help and sorry to take your time with this.

After playing with the code a bit more I got reminded of n00b lessons (understand the code you use and RTM :) )

I think with what I was trying to do the culprit is this line: 
```python
verts /= verts.norm(p=2, dim=1, keepdim=True)
```
which I didn't really get, but [read the docs](https://pytorch.org/docs/stable/generated/torch.norm.html).
This note was interesting to spot as well:

> `torch.norm` is deprecated and may be removed in a future PyTorch release. Its documentation and behavior may be incorrect, and it is no longer actively maintained.
> Use [torch.linalg.norm()](https://pytorch.org/docs/stable/generated/torch.linalg.norm.html#torch.linalg.norm), instead, or [torch.linalg.vector_norm()](https://pytorch.org/docs/stable/generated/torch.linalg.vector_norm.html#torch.linalg.vector_norm) when computing vector norms and [torch.linalg.matrix_norm()](https://pytorch.org/docs/stable/generated/torch.linalg.matrix_norm.html#torch.linalg.matrix_norm) when computing matrix norms.
> 
> 

So in theory I can swap 

```python
verts /= verts.norm(p=2, dim=1, keepdim=True)
```
with 
```python
verts /= torch.linalg.norm(verts)
# or
verts /= torch.linalg.vector_norm(verts)
# or
verts /= torch.linalg.matrix_norm(verts)
```        
though in practice the results is slightly different and the vertices get scaled down.

I think it's simpler to omit the call completely:

```python
# plane a-la ico_sphere
def plane(level: int = 0, device=None):
    if device is None:
        device = torch.device("cpu")
    if level < 0:
        raise ValueError("level must be >= 0.")
    if level == 0:
        verts = torch.tensor(_plane_verts0, dtype=torch.float32, device=device)
        faces = torch.tensor(_plane_faces0, dtype=torch.int64, device=device)
    else:
        mesh = plane(level - 1, device)
        subdivide = SubdivideMeshes()
        mesh = subdivide(mesh)
        verts = mesh.verts_list()[0]
        faces = mesh.faces_list()[0]
    return Meshes(verts=[verts], faces=[faces])
```

The code snippets and explanations are much appreciated!
