### ISSUE TITLE
 Can I apply a vertice's (yaw pitch roll) or rotation matrix?

### ISSUE THREAD

**Issue by Chanwooong** [facebookresearch/pytorch3d#125]
## ❓ Questions on how to use PyTorch3D

In the previous method(I used), a rotation matrix was applied to the vertices so the transformed vertices were rendered.

but, I think pytorch3d renders according to camera rotation and position. I'm struggling not to solve these differences.

I searched for tutorials and documentation, but I couldn't find anything related.
Can you tell me if there is a way to apply vertice's (yaw pitch roll) or rotation matrix?
plz...

**Comment by nikhilaravi** [comment]
@Chanwooong the rotation of the camera is different from a transformation of the vertices. The camera rotation is used to align the position of an object with a camera located at a particular position in world coordinates.  

The camera position can be set using the R and T arguments of a Camera - refer to the [`Cameras` docs](https://pytorch3d.readthedocs.io/en/latest/modules/renderer/cameras.html) or one of the [rendering tutorials](https://github.com/facebookresearch/pytorch3d/tree/master/docs/tutorials)

For example you can set the position of the camera using a [`look at` transform](https://pytorch3d.readthedocs.io/en/latest/modules/renderer/cameras.html#pytorch3d.renderer.cameras.camera_position_from_spherical_angles)

You can independently apply a rotation matrix to the vertices and then render them using the same camera. We have several [rotation helper functions](https://pytorch3d.readthedocs.io/en/latest/modules/renderer/cameras.html#pytorch3d.renderer.cameras.camera_position_from_spherical_angles) which you can use for this. The [Transforms3D class](https://pytorch3d.readthedocs.io/en/latest/modules/transforms.html#pytorch3d.transforms.Transform3d) also allows you to easily compose transforms.

**Comment by nikhilaravi** [comment]
@Chanwooong if you were able to resolve your problem please close this issue.
