### ISSUE TITLE
Rendering of depth images

### ISSUE THREAD

**Issue by vineeth2309** [facebookresearch/pytorch3d#1250]
I am working on a model for depth estimation, and want to use Pytorch 3D for forward rendering. Im having a little bit of trouble understanding the coordinate transforms required when working with a different dataset like Kitti. Is there any resource that I can be pointed to that explains how to render an image of a point cloud from a dataset like Kitti.

**Comment by bottler** [comment]
The notes on the website explain our coordinate system. If you are not seeing what you expect, it can be helpful to use our plotly_vis tools to visualise your pointcloud and the camera object you have created.
