### ISSUE TITLE
How to render a textured mesh with my R and T

### ISSUE THREAD

**Issue by YuhsiHu** [facebookresearch/pytorch3d#1256]
Thank you for your great work!
I read the tutorials about [render textured mesh](https://github.com/facebookresearch/pytorch3d/blob/main/docs/tutorials/render_textured_meshes.ipynb) and run it correctly. However, when I import my mesh and params(rotation and translation in COLMAP format) in this file, the rendered image is not what I suppose.

For example, the transform matrix is like:
```
[a,b,c,d]
[e,f,g,h]
[i, j, k, l]
[0,0,0,1]
```
So I extract the rotation matrix R and translation matrix T and send them to cameras:
```
R = torch.from_numpy(pose[0:3,0:3]).unsqueeze(0)
T = torch.from_numpy(pose[0:3,-1]).unsqueeze(0)
cameras = FoVPerspectiveCameras(device=device, R=R, T=T)
```
But the result is not the correct view that I suppose to render. I can only see a little part of the mesh and many other parts are outside of the picture.

**Comment by bottler** [comment]
In general, you need to learn about the camera models of both systems to convert successfully. When you say you see a little part, do you mean that you are looking from the right position but are too zoomed in? If so, maybe you have got R and T correct (the extrinsic parameters = the camera location = the world-to-view conversion) but you haven't got the right intrinsic parameters (focal length, principal point etc.) 

If you just want to experiment, you could try something like `cameras = FoVPerspectiveCameras(fov=x, device=device, R=R, T=T)` where `x` is a number for the field of view in degrees, the default is `60.0` but it sounds like you would prefer something higher.

**Comment by YuhsiHu** [comment]
Thank you for your reply!
I load the extrinsic params from sfm data. The pose, R and T is:
![image](https://user-images.githubusercontent.com/34529345/179514655-8bf5e3fa-2597-4645-a763-8a3c1046e4a8.png)
The mesh is too small (verts coordinates are all <1), so the rendered image is just white background.
Therefore, I scale the mesh file:
```
mesh1 = mesh.scale_verts(25)
images = render(mesh1)
```
The result is:
![image](https://user-images.githubusercontent.com/34529345/179515323-febb4751-8e24-4c6b-bd22-855e9e4ca42a.png)

But, the view of ground truth image should be from the front of the batgirl. It is:
![1658148967754](https://user-images.githubusercontent.com/34529345/179515879-60a75190-62a8-42aa-abdb-49bf0a575b3f.png)

Could you please help me with this issue? Thank you for your time!

**Comment by YuhsiHu** [comment]
Here is my code. I did not make use of intrinsic params from SFM data because it is not shown in tutorial. In tutorial, there is just R and T.

```python
print(pose)

R = torch.from_numpy(pose[0:3,0:3]).unsqueeze(0)
T = torch.from_numpy(pose[0:3,-1]).unsqueeze(0)
print(R, T)

cameras = PerspectiveCameras(device=device, R=R, T=T)

raster_settings = RasterizationSettings(
    image_size=(756,1008), 
    blur_radius=0.0, 
    faces_per_pixel=1, 
)

lights = PointLights(device=device, location=[[0.0, 0.0, -3.0]])

# Create a Phong renderer by composing a rasterizer and a shader. The textured Phong shader will 
# interpolate the texture uv coordinates for each vertex, sample from a texture image and 
# apply the Phong lighting model
renderer = MeshRenderer(
    rasterizer=MeshRasterizer(
        cameras=cameras, 
        raster_settings=raster_settings
    ),
    shader=SoftPhongShader(
        device=device, 
        cameras=cameras,
        lights=lights
    )
)

mesh1 = mesh.scale_verts(25)
images = renderer(mesh1)
# display
plt.figure(figsize=(10, 10))
plt.imshow(images[0, ..., :3].cpu().numpy())
plt.axis("off");

```

**Comment by YuhsiHu** [comment]
Thank you! This solved my problem perfectly.
