### ISSUE TITLE
visibility map?

### ISSUE THREAD

**Issue by wangsen1312** [facebookresearch/pytorch3d#126]
## ❓ Questions on how to use PyTorch3D

Hi, I'd like to know whether the Pytorch3D can produce the visibility map for each vertice when rendering?

**Comment by nikhilaravi** [comment]
@wangsen1312 can you explain what the format of the output should be? Do you mean a boolean indicator if the vertex is visible?

**Comment by wangsen1312** [comment]
@nikhilaravi Thank you for your quick response. 
Your explanation is accurate.

**Comment by nikhilaravi** [comment]
@wangsen1312 you can infer this information from the output of rasterization - we return a named tuple called `fragments` which contains a tensor called `pix_to_face`. This is an `(N, H, W, K)` dimensional tensor which gives the indices of the closest K faces (ordered by Z distance) for each pixel. 

NOTE: the indices in `pix_to_face` refer to the packed faces of `meshes` i.e. the flattened list of faces across all meshes in the batch (which can be retrieved using `meshes.faces_packed()`

You can set K=1 (`faces_per_pixel = 1` in the `RasterizationSettings`) and then use the indices to create a visibility map.  For example, you could do the following:

```
raster_settings = RasterizationSettings(
    image_size=256, 
    blur_radius=0.0,
    faces_per_pixel=1, 
)
rasterizer = MeshRasterizer(
    cameras=cameras, 
    raster_settings=raster_settings
)

# Get the output from rasterization
fragments = rasterizer(meshes)

# pix_to_face is of shape (N, H, W, 1)
pix_to_face = fragments.pix_to_face  

# (F, 3) where F is the total number of faces across all the meshes in the batch
packed_faces = meshes.faces_packed() 
# (V, 3) where V is the total number of verts across all the meshes in the batch
packed_verts = meshes.verts_packed() 
vertex_visibility_map = torch.zeros(packed_verts.shape[0])   # (V,)

# Indices of unique visible faces
visible_faces = pix_to_face.unique()[0]   # (num_visible_faces )

# Get Indices of unique visible verts using the vertex indices in the faces
visible_verts_idx = packed_faces[visible_faces]    # (num_visible_faces,  3)
unique_visible_verts_idx = torch.unique(visible_verts_idx)   # (num_visible_verts, )

# Update visibility indicator to 1 for all visible vertices 
visibility_map[unique_visible_verts_idx] = 1.0
``` 

Note: also be aware that the visibility map will be affected by the setting for `blur_radius` in the `RasterizationSettings` as this increases the boundary region for each face.

**Comment by wangsen1312** [comment]
@nikhilaravi It works for me.

**Comment by endlesswho** [comment]
> @wangsen1312 you can infer this information from the output of rasterization - we return a named tuple called `fragments` which contains a tensor called `pix_to_face`. This is an `(N, H, W, K)` dimensional tensor which gives the indices of the closest K faces (ordered by Z distance) for each pixel.
> 
> NOTE: the indices in `pix_to_face` refer to the packed faces of `meshes` i.e. the flattened list of faces across all meshes in the batch (which can be retrieved using `meshes.faces_packed()`
> 
> You can set K=1 (`faces_per_pixel = 1` in the `RasterizationSettings`) and then use the indices to create a visibility map. For example, you could do the following:
> 
> ```python
> raster_settings = RasterizationSettings(
>     image_size=256, 
>     blur_radius=0.0,
>     faces_per_pixel=1, 
> )
> rasterizer = MeshRasterizer(
>     cameras=cameras, 
>     raster_settings=raster_settings
> )
> 
> # Get the output from rasterization
> fragments = rasterizer(meshes)
> 
> # pix_to_face is of shape (N, H, W, 1)
> pix_to_face = fragments.pix_to_face  
> 
> # (F, 3) where F is the total number of faces across all the meshes in the batch
> packed_faces = meshes.faces_packed() 
> # (V, 3) where V is the total number of verts across all the meshes in the batch
> packed_verts = meshes.verts_packed() 
> vertex_visibility_map = torch.zeros(packed_verts.shape[0])   # (V,)
> 
> # Indices of unique visible faces
> visible_faces = pix_to_face.unique()[0]   # (num_visible_faces )
> 
> # Get Indices of unique visible verts using the vertex indices in the faces
> visible_verts_idx = packed_faces[visible_faces]    # (num_visible_faces,  3)
> unique_visible_verts_idx = torch.unique(visible_verts_idx)   # (num_visible_verts, )
> 
> # Update visibility indicator to 1 for all visible vertices 
> visibility_map[unique_visible_verts_idx] = 1.0
> ```
> 
> Note: also be aware that the visibility map will be affected by the setting for `blur_radius` in the `RasterizationSettings` as this increases the boundary region for each face.
change the following code
visible_faces = pix_to_face.unique()[0]   # (num_visible_faces )
to
visible_faces = pix_to_face.unique()   # (num_visible_faces )
or there is only one vertices in the results.
