### ISSUE TITLE
Failed building wheel for pytorch3d in Google Colabtory 

### ISSUE THREAD

**Issue by libeike** [facebookresearch/pytorch3d#1262]
Hi,
I was able to download pytorch3d successfully on colab before, but today when I downloaded pytorch3d I got the following problem.

> import os
import sys
import torch
need_pytorch3d=False
try:
    import pytorch3d
except ModuleNotFoundError:
    need_pytorch3d=True
if need_pytorch3d:
    if torch.__version__.startswith("1.11.") and sys.platform.startswith("linux"):
        # We try to install PyTorch3D via a released wheel.
        pyt_version_str=torch.__version__.split("+")[0].replace(".", "")
        version_str="".join([
            f"py3{sys.version_info.minor}_cu",
            torch.version.cuda.replace(".",""),
            f"_pyt{pyt_version_str}"
        ])
        !pip install fvcore iopath
        !pip install --no-index --no-cache-dir pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/{version_str}/download.html
    else:
        # We try to install PyTorch3D from source.
        !curl -LO https://github.com/NVIDIA/cub/archive/1.10.0.tar.gz
        !tar xzf 1.10.0.tar.gz
        os.environ["CUB_HOME"] = os.getcwd() + "/cub-1.10.0"
        !pip install 'git+https://github.com/facebookresearch/pytorch3d.git@stable'

On running to the '!pip install `'git+https://github.com/facebookresearch/pytorch3d.git@stable'` , the code stopped at the `Building wheels for collected packages: pytorch3d, fvcore, iopath` and did not move.

**Comment by bottler** [comment]
At the moment, that code is building pytorch3d from source. Unfortunately you have to just wait.

**Comment by libeike** [comment]
> At the moment, that code is building pytorch3d from source. Unfortunately you have to just wait.

OK. Looks like I could go for a sip of coffee.

**Comment by libeike** [comment]
> At the moment, that code is building pytorch3d from source. Unfortunately you have to just wait.

It's still not working, is that normal?

**Comment by santisy** [comment]
Any progress? Recentlly I cannot build from source either. It reported `RuntimeError: Error compiling objects for extension`. I am using the command `pip3 install git+https://github.com/facebookresearch/pytorch3d.git@stable`

**Comment by libeike** [comment]
> Any progress? Recentlly I cannot build from source either. It reported `RuntimeError: Error compiling objects for extension`. I am using the command `pip3 install git+https://github.com/facebookresearch/pytorch3d.git@stable`

I still use the same code as in my previous comment, building wheels takes 10-20 minutes to work.
