### ISSUE TITLE
Support for Chamfer-L1 distance

### ISSUE THREAD

**Issue by monniert** [facebookresearch/pytorch3d#1266]
## 🚀 Feature

Enhance `chamfer_distance` with support for the classical Chamfer-L1 used for 3D reconstruction evaluation

## Motivation

It corresponds to 2 extra lines of code, and this metrics can be preferred over Chamfer-L2 in standard 3D reconstruction benchmarks, e.g. by [Occupancy Networks](https://arxiv.org/pdf/1812.03828.pdf) or [DVR](https://arxiv.org/pdf/1912.07372.pdf)

## Pitch

It amounts to passing an argument `return_L1` and add the following lines [here](https://github.com/facebookresearch/pytorch3d/blob/7978ffd1e4819d24803b01a1147a2c33ad97c142/pytorch3d/loss/chamfer.py#L162):

```
    if return_L1:
        cham_x, cham_y = cham_x.sqrt(), cham_y.sqrt()
```

**Comment by gkioxari** [comment]
Support for `L1` exists!! You need to set `norm=1` in 

https://github.com/facebookresearch/pytorch3d/blob/6b481595f096254817902d1dc0e1ead18e5610ca/pytorch3d/loss/chamfer.py#L80

**Comment by monniert** [comment]
Thanks for the reply! Yes in fact, this "Chamfer-L1" term is a bit misleading, it corresponds to the unsquared Chamfer-L2 distance as stated in https://github.com/autonomousvision/differentiable_volumetric_rendering/issues/10#issuecomment-623574543

But I agree it may be confusing with the current implementation using the L1 distance between points, which makes a bit more sense
