### ISSUE TITLE
Unable to import IO

### ISSUE THREAD

**Issue by silvercondor** [facebookresearch/pytorch3d#1267]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## 🐛 Bugs / Unexpected behaviors

NOTE: Please look at the existing list of Issues tagged with the label ['bug`](https://github.com/facebookresearch/pytorch3d/issues?q=label%3Abug). **Only open a new issue if this bug has not already been reported. If an issue already exists, please comment there instead.**.

## Instructions To Reproduce the Issue:

Error importing IO from the module for reference code in doc

https://pytorch3d.org/docs/io

Please include the following (depending on what the issue is):

1. Any changes you made (`git diff`) or code you wrote

NA

2. The exact command(s) you ran:

`from pytorch3d.io import IO`

3. What you observed (including the full logs):
```
ImportError: cannot import name 'IO' from 'pytorch3d.io' (/mnt/g/Projects/test/venv/lib/python3.8/site-packages/pytorch3d/io/__init__.py)
```

Please also simplify the steps as much as possible so they do not require additional resources to
   run, such as a private dataset.

**Comment by bottler** [comment]
This may be due to a very old version of PyTorch3D?
