### ISSUE TITLE
How to Zoom In - Out.

### ISSUE THREAD

**Issue by PRAN20** [facebookresearch/pytorch3d#1271]
I want to move the object file while I'm rendering it. Is there any solution that I can change the position of object or try translation of camera in y direction or zoom results from the camera???

Thanks a lot in advance :)))

**Comment by kjchalup** [comment]
You can use the look_at_view_transform to move your camera towards/away from the object by changing the "distance" parameter. See PyTorch3D tutorials on how to use the transform: https://pytorch3d.org/tutorials/camera_position_optimization_with_differentiable_rendering.

You can of course also simply move the mesh around, with mesh.offset_verts. See https://pytorch3d.org/tutorials/fit_textured_mesh for example usage.

If this doesn't help, then I'll need a minimal running example to see exactly what you're trying to achieve.

**Comment by bottler** [comment]
Also note
```
    If you want to translate the camera from the origin in camera
    coordinates, this is simple and does not need a separate function.
    In particular, a translation by X = [a, b, c] would cause
    the camera to move a units left, b units up, and c units
    forward. This is achieved by using T-X in place of T.
```
