### ISSUE TITLE
Whether pytorch3d can fit a colored face mesh by an input RGB face mask?

### ISSUE THREAD

**Issue by SwordHolderSH** [facebookresearch/pytorch3d#1273]
![图片1](https://user-images.githubusercontent.com/31804639/181834517-5cd1679e-8a74-43c0-9e0c-815e2af12a6d.jpg)
(The "rendered image" shown in the above figure is the result of covering the rendered mesh image on the target mask.)

I want to optimize the source face mesh according to the target mask. I built a loss between the rendered image and the target mask, however, the mesh and vertices have not changed.

I would like to ask whether pytorch3d can optimize the color face mesh according to the input RGB mask?

**Comment by bottler** [comment]
If you can define the model, you can optimize it. This sounds like a modelling question, which we can't help with, rather than a library question.
