### ISSUE TITLE
Python version error installing with Anaconda

### ISSUE THREAD

**Issue by samhoff20** [facebookresearch/pytorch3d#128]
I'm running python 3.7 in this env but have tried 3.6 and 3.5 with the same result here:
![Screenshot from 2020-03-27 14-17-03](https://user-images.githubusercontent.com/52685675/77787507-086b0e00-7036-11ea-8e27-e5d8eae2b24f.png)
![Screenshot from 2020-03-27 14-18-28](https://user-images.githubusercontent.com/52685675/77787521-0dc85880-7036-11ea-908c-40147ca6bc97.png)

**Comment by nikhilaravi** [comment]
@samhoff20 are you getting the same error about the python version even if you try a new environment which uses python 3.6?

**Comment by samhoff20** [comment]
Yes

**Comment by nikhilaravi** [comment]
What conda version are you using?

**Comment by samhoff20** [comment]
4.8.3

**Comment by samhoff20** [comment]
build 3.18.11

**Comment by nikhilaravi** [comment]
I tried to reproduce this error but I was able to install successfully following the installation instructions in [INSTALL.md](https://github.com/facebookresearch/pytorch3d/blob/master/INSTALL.md) and using python3.6 (conda version is 4.7.1).

cc @bottler if you have any other suggestions.

**Comment by samhoff20** [comment]
I was also able to successfully install with those directions. I don't think I had included `conda install -c conda-forge -c fvcore fvcore`

Thank you so much!
