### ISSUE TITLE
small typo in the LLFF data loader? (os.path.listdir -> os.listdir)

### ISSUE THREAD

**Issue by sergeyprokudin** [facebookresearch/pytorch3d#1280]
Hi folks!

I've just noticed a potential typo in the LLFF data loader:

https://github.com/facebookresearch/pytorch3d/blob/a0f786f4cf600a8b1741ef8b5b24bc99272ab0e7/pytorch3d/implicitron/dataset/load_llff.py#L297

should be os.**listdir** instead of os.**path.listdir** I guess?

P.S. thanks for the amazing work!

**Comment by bottler** [comment]
agreed.

**Comment by bottler** [comment]
(Fixed by you in #1281)
