### ISSUE TITLE
How to convert faces to coresponding x,y,z of the vertices?

### ISSUE THREAD

**Issue by kentdan** [facebookresearch/pytorch3d#1283]
## ❓ How to convert faces to coresponding x,y,z of the vertices 

faces_idx = faces.verts_idx.to(device)
when I print faces_idx it return 

tensor([[   0,    1,    2],
        [   1,    3,    2],
        [   2,    3,    4]])

Is there a way to return in to the coresponding x,y,z of the vertices?

tensor([[  [x0,y0,z0],   [x1,y1,z1],    [x2,y2,z2]],
        [    [x1,y1,z1],   [x3,y3,z3],    [x2,y2,z2]],
        [   [x2,y2,z2],   [x3,y3,z3],    [x4,y4,z4]])

Thank you in advance!

**Comment by bottler** [comment]
This is a torch indexing question. If verts has shape `[V,3]` and `faces` has shape `[F,3]` (i.e. a single mesh) you can get what you want with `verts[faces]` which has shape `[F,3,3]`.

**Comment by kentdan** [comment]
Thank you so much!
