### ISSUE TITLE
Discrepancy between distance from `knn_points` and `torch.cdist`

### ISSUE THREAD

**Issue by Sentient07** [facebookresearch/pytorch3d#1286]
Hello,

I find some inconsistencies between `torch.cdist` and distance to nearest neighbour from `pytorch3d.ops.knn_points`. Here is a toy example. Is there something wrong with my understanding? The absolute difference is at times more than 1e-4 and that's a problem for my use case. Can someone please suggest a more reliable way of estimating nearest neighbour? 

```
from pytorch3d.ops import ball_query, knn_points

samp_1 = torch.randn(50000, 3).cuda().float()
samp_2 = torch.randn(10000, 3).cuda().float()

nn_dist_p3d, _, _ = knn_points(samp_1.unsqueeze(0), samp_2.unsqueeze(0), K=4)
nn_dist_th = torch.cdist(samp_1, samp_2).topk(k=4, dim=1, largest=False).values.mean(dim=1)

torch.allclose(nn_dist_p3d.squeeze().sqrt().mean(dim=1), nn_dist_th)
```

Relevant package versions:

pytorch3d: 0.6.1 , torch: 1.10.0+cu111, Cuda 11.1, Device: A100 Ampere.

Thank you!

**Comment by bottler** [comment]
I'm not using exactly the same versions and hardware, but I'm not seeing what you're seeing.

```
nn_dist_p3d, _, _ = knn_points(samp_1.unsqueeze(0), samp_2.unsqueeze(0), K=4)
nn_dist_th = torch.cdist(samp_1, samp_2).topk(k=4, dim=1, largest=False).values.mean(dim=1)
diff = nn_dist_p3d[0].sqrt().mean(1)-nn_dist_th
print(-diff.min(), diff.max())
```
prints numbers between 1e-6 and 1e-5.

If you need lots more precision, you could try using the torch.cdist method with doubles? PyTorch3D can't do that. You could also find the indices with pytorch3d then recalculate the dists in double precision.

**Comment by Sentient07** [comment]
I think retrieving the index + norm makes sense. Thank you.
