### ISSUE TITLE
Installation command that used to work doesn't work anymore

### ISSUE THREAD

**Issue by MathieuLeclercq** [facebookresearch/pytorch3d#1289]
Hello,

I used to be able to install pytorch3d using this command: 
`pip install --no-index --no-cache-dir pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py39_cu113_pyt1110/download.html`

However this does not work anymore. I cannot use conda or build from source because it takes too long (I need the installation to be relatively quick for my work).
Could you give me a solution or provide me a way to install the .whl file so that I can install it from a local file? 
Thank you

**Comment by YuliangXiu** [comment]
same issue, anyone knows why this happens?

**Comment by abderrahimlaaz** [comment]
you need to make sure that you have cuda11.3 installed in colab(if you're using colab). if you want to install it use the blew commands:

!wget https://developer.download.nvidia.com/compute/cuda/11.3.0/local_installers/cuda-repo-ubuntu1804-11-3-local_11.3.0-465.19.01-1_amd64.deb
!sudo dpkg -i cuda-repo-ubuntu1804-11-3-local_11.3.0-465.19.01-1_amd64.deb
!sudo apt-key add /var/cuda-repo-ubuntu1804-11-3-local/7fa2af80.pub
!apt-get update
!apt-get install cuda-11.3

also you need to have PyTorch 1.12.0 witth pytorch3d==0.7.0 then try to install it again using this lines of code it will work just fine 

pyt_version_str=torch.__version__.split("+")[0].replace(".", "")
version_str="".join([
    f"py3{sys.version_info.minor}_cu",
    torch.version.cuda.replace(".",""),
    f"_pyt{pyt_version_str}"
])
!pip install fvcore iopath
!pip install --no-index --no-cache-dir pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/{version_str}/download.html

**Comment by MathieuLeclercq** [comment]
Thanks for your help. Although I find it strange that the people from pytorch3d are removing wheels because of the update.

**Comment by bottler** [comment]
PyTorch3D's main way of distributing binaries is via conda, which we strongly recommend.

These wheels only exist for supporting colab. When the new version came out, we removed the old wheels and added new ones for the current versions of dependencies used by colab. If we left old ones there for the dependencies we don't need any more, people would unexpectedly install previous versions of PyTorch3D. Colab currently uses PyTorch 1.12.0. We have wheels for PyTorch 1.12.0 with Cuda 11.3 with Python 3.7, 3.8, 3.9 and 3.10. 

It should be easy for us to add wheels for PyTorch 1.11.1 with cuda 11.3with Python 3.8, 3.9 and 3.10 and I hope to do that soon.

**Comment by bottler** [comment]
I have now added those wheels, and also wheels for PyTorch 1.12.1 - because I imagine Colab might update to that very soon. So now the linux wheels available are (Python 3.8, 3.9 and 3.10) ⨉ (PyTorch 1.11.0, 1.12.0 and 1.12.1), as well as Python 3.7 with (PyTorch 1.12.0 and 1.12.1). All are just for CUDA 11.3.
