### ISSUE TITLE
How to make my own data-file(xxx.pth) using initial colmap&LLFF data

### ISSUE THREAD

**Issue by cinamon123** [facebookresearch/pytorch3d#1301]
Hello! 
I am preparing my own datasets **using initial colmap&LLFF data.** 
I have learned the structure of your data dict. 
But I have no idea how to transfer them(below) to the vital dict **'xxx.pth'**
![11](https://user-images.githubusercontent.com/104305930/185570444-5bbe8257-0581-4400-aabe-9e7e7907c36b.PNG)

**Comment by bottler** [comment]
Are you trying to use your data with the nerf project (`projects/nerf`) or with implicitron?

Implicitron is now our preferred system for training NeRF and other models. To use your own dataset you could implement your own DatasetMapProvider class. If your data is organised like the LLFF dataset (which looks to be the case) then you may be able to use our LlffDatasetMapProvider. This doesn't require any pth files.

**Comment by cinamon123** [comment]
Thank you !
As you mentioned, I'm training the 'projects/nerf'
I read the MD for 'projects/implictron' just now.  I have some more questions.
**Is implictron more faster than initial nerf ?
Is the rendered scale better than initial nerf ?**

**Comment by bottler** [comment]
Implicitron is aimed at doing more than just original nerf. There is no particular reason that when configured to do original nerf (and some such config files are provided) it would be faster than the original. There are a few minor speedups we had without changing the calculation, e.g. LinearWithRepeat and using separate cuda streams for color and opacity networks, some of which implicitron had. But it is a framework where implementing faster ideas should be possible, and some are planned.

When do you mean by `better`? Do you mean you want to train an existing design of model at a higher resolution, or you want a different design of model which trains better at higher resolutions, or something else?

**Comment by cinamon123** [comment]
Thank you for your reply! implicitron do faster than old nerf.
From your MRADME, I know implicitron is more flexible for new ideas on rendering.
In my project, resolution is an important index to figure this project is necessary to carry on or not. So I need to know the training effect in advance. Or we will make a wrong conclusion that the existing model is good enough to deal with our project.
Thank you.

**Comment by bottler** [comment]
I haven't experimented with higher resolutions. I think how well different models will work at higher resolutions is a research question we can't answer here.
