### ISSUE TITLE
Implicitron_training: Primary config module 'pytorch3d.implicitron_trainer.configs' not found.

### ISSUE THREAD

**Issue by cinamon123** [facebookresearch/pytorch3d#1304]
HELLO !  As you said, implicitron is a preferred choice on various datasets. Splendid !
When training implicitron with co3d-single-data,  I put :
`dataset_args=data_source_args.dataset_map_provider_JsonIndexDatasetMapProvider_args
pytorch3d_implicitron_runner --config-path configs/ --config-name repro_singleseq_nerf \
    $dataset_args.dataset_root=co3datast $dataset_args.category='apple' \
    $dataset_args.test_restrict_sequence_id=0 test_when_finished=True exp_dir=pytorch3d/projects/implicitron_trainer/checkpoint                                                                                 `

Returned ERROR (the third folder is not the matter) :
![yy](https://user-images.githubusercontent.com/104305930/185797244-5b667533-85e7-4a7d-a48c-c28a67f5cf7e.png)
The directory must be OK. So why  a configs-folder needs `__init__.py` ?  I just can't solve it.

THANKS IN ADVANCE~

**Comment by cinamon123** [comment]
I tried my best these days. Following the tip in terminal, I added an `__init__.py`in configs folder.
And yes, this error disappeared.
Then, new bugs came. They are caused by the inconsistency of args in configs and shell. I suppose you forgot to rewrite the command lines in MarkDown.
The new lines are:
```
dataset_args=data_source_ImplicitronDataSource_args.dataset_map_provider_JsonIndexDatasetMapProvider_args
pytorch3d_implicitron_runner --config-path configs/ --config-name repro_singleseq_nerf \
    $dataset_args.dataset_root=<ROOT> $dataset_args.category='banana' \
    $dataset_args.test_restrict_sequence_id=0 exp_dir=<ROOT>
```
Besides,I delete `test_when_finished`, it is not in `class Experiment` (another error)

Now, I am solving a new bug:
![image](https://user-images.githubusercontent.com/104305930/186176423-d4b6ff36-fd1a-439e-93b0-3f701c0dc57c.png)

I'm confused. Is it caused by my dataset? Or I solved bugs in a wrong way at the beginning?
I want to get some help from you! Thanks

**Comment by cinamon123** [comment]
@bottler Could you please contribute a config for LLFF_data?  It will be more faster and convenient for us to train other datasets, not just CO3D.
Thank you!!!

**Comment by cinamon123** [comment]
Good news! My debugging is finished.
As I just need to train LLFF-datasets in my project and not familiar to Josn_Indes_data, I made the LLFF_config only.  It runs successfully.

**However, there are still some little bugs. Let me write here, helping more people.**
1.  "tuple+list" : Just turn the tuples into lists in key line. 
2.  "subprocess.CalledProcessError: Command 'mogrify -resize 12.5% -format png *.JPG' returned non-zero exit status 127.":  
      It occurs because of some dependency lacking below:
```
pip install imageio
pip install imageio-ffmpeg
apt install imagemagick-6.q16                  # version 8:6.9.10.23+dfsg-2.1ubuntu11.4, or
apt install imagemagick-6.q16hdri              # version 8:6.9.10.23+dfsg-2.1ubuntu11.4
apt install graphicsmagick-imagemagick-compat  # version 1.4+really1.3.35-1
```

If someone want to take my configs as reference, welcome to apply.
Thanks again for your implicitron !!

**Comment by bottler** [comment]
It would be great to hear more details of what configs you used and what code changes you made!.

**Comment by cinamon123** [comment]
Not a big deal, just some little bugs.

For LLFF_data(just some little bugs):
1. **please add an `__init__.py` in configs folder**
2. **load_llff.py line19:** (change tuple into list, this is a strange error)
`def _minify(basedir, path_manager, factors=(), resolutions=()):`
to `def _minify(basedir, path_manager, factors=[], resolutions=[]):`
3. I will try to put my configs on my homepage. This might take some time as I am new in github.
with Training command line: `pytorch3d_implicitron_runner --config-path configs/ --config-name llff_nerf`
4. Please install the dependency as I mentioned above.


For CO3D_data(I am not familiar with the structure of these datasets. So I just solve some bugs, not all)
1. **please add an `__init__.py` in configs folder**
2. **Please change your command line in README as I mentioned above**:
```
dataset_args=data_source_ImplicitronDataSource_args.dataset_map_provider_JsonIndexDatasetMapProvider_args
pytorch3d_implicitron_runner --config-path configs/ --config-name repro_singleseq_nerf \
    $dataset_args.dataset_root=<ROOT> $dataset_args.category='banana' \
    $dataset_args.test_restrict_sequence_id=0 exp_dir=<ROOT>
```
At the same time,  `test_when_finished` can not work for CO3Ddata. I don't know why. But for llff, we don't need this function.

I am new in this field. If some suggestions are wrong, please remind me.  Thanks.

**Comment by cinamon123** [comment]
I upload my files. You can download them by git:
`https://github.com/cinamon123/implicitron-LLFF_data_configs.git`
