### ISSUE TITLE
how to apply pytorch3d to face 3d reconstruction?

### ISSUE THREAD

**Issue by xingmimfl** [facebookresearch/pytorch3d#131]
In this situation, i have got vertex/angles/scale, how can i project this vertex onto 2d images? like this
![WXl](https://user-images.githubusercontent.com/32946466/78028700-fb318480-7391-11ea-9f27-dbef15fed59d.png)

**Comment by nikhilaravi** [comment]
@xingmimfl it sounds like you just need to transform the vertices and then project them onto a 2D image. For this you probably don't need a renderer.  #125 is a related issue. 

You can initialize a Rotation/Translation matrix based on the angles (do you mean euler angles?). Have a look at the [RotateAxisAngle](https://pytorch3d.readthedocs.io/en/latest/modules/transforms.html#pytorch3d.transforms.RotateAxisAngle) class for how to do this. We also have a number of helper functions for initializing rotation matrices in other ways  - see the [rotation helper functions](https://pytorch3d.readthedocs.io/en/latest/modules/renderer/cameras.html#pytorch3d.renderer.cameras.camera_position_from_spherical_angles) and the [`look at` transform](https://pytorch3d.readthedocs.io/en/latest/modules/renderer/cameras.html#pytorch3d.renderer.cameras.camera_position_from_spherical_angles).  The [Transforms3D class](https://pytorch3d.readthedocs.io/en/latest/modules/transforms.html#pytorch3d.transforms.Transform3d) also allows you to easily compose transforms. 

You can then create a [`Cameras](https://pytorch3d.readthedocs.io/en/latest/modules/renderer/cameras.html) class which takes the R/T matrices as input - you can chose from several different camera types and the type of projection you want to apply (orthogonal/perspective).

You can then call the `transform_points` method on a camera which will apply the transformation matrices and project the points onto 2D. 

e.g. pseudo code would look like this:

```python 
from pytorch3d.transforms import RotateAxisAngle, Scale
from pytorch3d.renderer import OpenGLPerspectiveCameras

# vertices (N, V, 3) tensor
# angles  (N, )  e.g. one angle per batch element 
# scales (N, 3) xyz scaling factor per batch element

scale = Scale(scales)
scaled_points = scale.transform_points(vertices)
R = RotateAxisAngle(angle=angles)
camera = OpenGLPerspectiveCameras(R=R)
projected_points = camera.transform_points(scaled_points)
```

Have a look at one of the [rendering tutorials](https://github.com/facebookresearch/pytorch3d/tree/master/docs/tutorials) for example usage of cameras and rotation function.

**Comment by gkioxari** [comment]
Hi @xingmimfl 
I marked your question with a _how to_ label, as it's not an issue or question regarding an implementation in the codebase, but it's a question about how to use PyTorch3D in your project. @nikhilaravi has been kind to provide some tips to help you, which can hopefully get you started. I will be closing this issue though as it's not pertinent to the codebase. Good luck with your project!
