### ISSUE TITLE
Pytorch3D install error

### ISSUE THREAD

**Issue by ilyasyalcin** [facebookresearch/pytorch3d#1313]
## ❓ Pytorch3D Install Error

Hi everybody,

My pytorch version is 1.12.1 cuda 11.6 cudnn is 8.4.

While installing pytorch3d I got an error like in (https://stackoverflow.com/questions/62304087/installing-pytorch3d-fails-with-anaconda-and-pip-on-windows-10).

Then, I ran **pip install "git+https://github.com/facebookresearch/pytorch3d.git"** with my newly added environment variables.

I got this error.

![image](https://user-images.githubusercontent.com/45540638/186873895-57a129e1-522b-4e24-8b62-9874394fb45c.png)

Thank you...

**Comment by PinPointPing** [comment]
Have you perhaps tried updating your torch version?

**Comment by mehdizade** [comment]
Same issue

**Comment by kjchalup** [comment]
Can you all confirm whether this is happening on Windows? A few days ago we enabled C++17 features and used some in iou_utils code. The error is complaining because the CUDA compiler doesn't understand structured bindings. It worked on Linux but maybe something's wrong with the Windows compiler. We'll look into it next week, pls let me know if any of you is using windows, also your pytorch/cuda/cudnn versions.

**Comment by mehdizade** [comment]
I am running that on linux, 
CUDA = 10.2

**Comment by kjchalup** [comment]
@mehdizade It looks like nvcc 10.2 is the last version that doesn't support C++17 (see https://gist.github.com/ax3l/9489132#device-side-c-standard-support). We'd like to be able to use C++17 features, but I'm not sure how long we want to support CUDA < 11. Let me get back to you on that on Monday.

But 11.x should work. @ilyasyalcin can you do nvcc.exe --version and share your nvcc version? (Apparently "starting with CUDA Toolkit 11.0.1, nvcc and CUDA Toolkit versions are not equivalent anymore")

**Comment by ilyasyalcin** [comment]
First of all, thank you your contributions. (@kjchalup )

I have windows platform.

My nvcc version is shown below as screenshot.

**NVCC**

![1](https://user-images.githubusercontent.com/45540638/187014843-c6dfdc90-13a2-49ca-b89c-00e697642cc5.PNG)

**Comment by czy2014hust** [comment]
PlanB: git checkout 5e7707b

**Comment by bottler** [comment]
The main branch has just been updated with 95771985b7ac14dae4606d799e82703b530d4e0c  to remove the use of C++17 features. This specific error should not happen any more.

For a few days recently, the main branch using C++17 features but not setting that with a flag on the compiler, which is likely to have broken linux builds.  @keloee and @mehdizade hopefully that should fix 

The latest release v0.7.0 is still fine. Anyone having problems with the actual released code or new build problems should open a new issue.

@czy2014hust That commit doesn't affect installation of PyTorch3D.

**Comment by JK1201** [comment]
I am using Windows with CUDA=11.7,pytorch=1.9.1
I encountered the following problem:
(ydk_adaBins) PS D:\Git\Git\bin\pytorch3d> python setup.py install
D:\Git\Git\bin\pytorch3d\setup.py:84: UserWarning: The environment variable `CUB_HOME` was not found. NVIDIA CUB is required for compilation and can be downloaded from `https://github.com/NVIDIA/cub/releases`. You can unpack it to a location of your choice and set the environment variable `CUB_HOME` to the folder containing the `CMakeListst.txt` file.
  warnings.warn(
running install
D:\anaconda\envs\ydk_adaBins\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
D:\anaconda\envs\ydk_adaBins\lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing pytorch3d.egg-info\PKG-INFO
writing dependency_links to pytorch3d.egg-info\dependency_links.txt
writing entry points to pytorch3d.egg-info\entry_points.txt
writing requirements to pytorch3d.egg-info\requires.txt
writing top-level names to pytorch3d.egg-info\top_level.txt
reading manifest file 'pytorch3d.egg-info\SOURCES.txt'
adding license file 'LICENSE'
adding license file 'LICENSE-3RD-PARTY'
writing manifest file 'pytorch3d.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
D:\anaconda\envs\ydk_adaBins\lib\site-packages\torch\utils\cpp_extension.py:305: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
building 'pytorch3d._C' extension
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Comment by mrsogib** [comment]
I dont have a amd gpu (Radeon RX Vega 11 Graphics) i didn't installed cuda, rather i installed pytorch with cpu option. Next, when i try to install pytorch3d via github (as instructed on official website). I also see kinda same error, and i can't see a specific error to solve. Can anyone help?
