### ISSUE TITLE
ImportError: libc10.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Fwngry** [facebookresearch/pytorch3d#1316]
I'm so tired of  "ImportError: libc10.so: cannot open shared object file: No such file or directory"  when I use" from pytorch3d import _C"........can anybody help me??  I tried to install pytorch3d 30 times following the issues suggestions and install readme and it never work!!!

**Comment by bottler** [comment]
libc10.so is part of PyTorch. There is something "wrong" with the PyTorch installation e.g. there is a mismatch between the pytorch at run time or the pytorch when pytorch3d was built.

How did you install pytorch? How did you build pytorch3d? Could you use our conda builds?

One thing to try is `import torch` before you try to import any of PyTorch3D.

**Comment by Fwngry** [comment]
thanks for your reply!!! "torch.cuda.is_available()" return "True", "import pytorch3d" is fine. but when i use "from pytorch3d import _C", i got this error..... I tried it in cuda11.0 + ubuntu16.04.

**Comment by Fwngry** [comment]
> thanks for your reply!!! "torch.cuda.is_available()" return "True", "import pytorch3d" is fine. but when i use "from pytorch3d import _C", i got this error..... I tried it in cuda11.0 + ubuntu16.04.

**Comment by JSHZT** [comment]
I also had such an error, please try to **import torchvision** to see if an error is reported, I think it is caused by the mismatch between torch and torchvision versions, **you can try to reinstall**

**Comment by sidsingla** [comment]
No error on importing torchvision for me, but still facing same issue as @Fwngry

**Comment by Samir55** [comment]
Running ``import torch`` before ``from pytorch3d import _C`` works for me!

Thanks to this comment (https://github.com/facebookresearch/pytorch3d/issues/1531#issuecomment-1538198217)  by @bottler
