### ISSUE TITLE
When rendering, I get the below error : CUDA out of memory. Tried to allocate 24.00 GiB

### ISSUE THREAD

**Issue by yesjames4231** [facebookresearch/pytorch3d#1319]
When rendering with MeshRenderer, it requires an unusually large amount of memory.

My rendering class looks like this:

`

    def set_color_renderer(self):        

        at   = self.centroid
        dist = (torch.abs(self.bounds[0][1] - self.bounds[1][1])).to(self.device) * 1.2
        elev = torch.linspace(0, 0, self.cam_views + 1)[:-1]
        azim = torch.linspace(0, 360, self.cam_views + 1)[:-1]
        R, T = look_at_view_transform(dist=dist, elev=elev, azim=azim, at=at)
        self.cameras = FoVPerspectiveCameras(device=device, R=R, T=T)

        self.raster_settings_color = RasterizationSettings(
                image_size = self.res,
                blur_radius = np.log(1.0 / 1e-4 - 1.0) * 1e-7,
                faces_per_pixel = 8,
            )

        self.meshRas = MeshRasterizer(
                cameras=self.cameras, raster_settings=self.raster_settings_color
            )
        blendparam = BlendParams(1e-4, 1e-8, (1.0, 1.0, 1.0))
        self.rgb_renderer = MeshRenderer(
            rasterizer=self.meshRas,
            shader=SoftPhongShader(
                device=self.device,
                cameras=self.cameras,
                blend_params=blendparam,
            ),
            )

    def forward(self, mesh):
        self.scan_mesh = mesh # load_objs_as_meshes([paths['scan']])
        self.centroid = torch.unsqueeze( (self.scan_mesh._verts_list[0].max(dim=0).values + self.scan_mesh._verts_list[0].min(dim=0).values), 0 ) / 2
        self.bounds   = torch.stack((self.scan_mesh._verts_list[0].max(dim=0).values, self.scan_mesh._verts_list[0].min(dim=0).values), 0)
        self.set_color_renderer()

        rendered_imgs = self.rgb_renderer(self.scan_mesh.extend(self.cam_views), cameras=self.cameras)
        
        return rendered_imgs

`

If I try to increase the view_point (self.cam_views) or increase the value of faces_per_pixel, the memory usage goes up to 128GB.

Maybe I did something wrong? Or is there a way to reduce memory usage? The size of my obj file is 10.0MB.

**Comment by masadcv** [comment]
Hi @SangHunHan92, 
How did you resolve this issue? I have the same problem of CUDA out of memory and unsure what is causing it.
