### ISSUE TITLE
How to get the corresponding faces of rendered/rasterized obj file

### ISSUE THREAD

**Issue by kentdan** [facebookresearch/pytorch3d#1321]
## ❓ Questions on how to use PyTorch3D

Dear Authors Thank you for these wonderful tools,

I am wondering how can I get only the corresponding faces shown in the rendered/rasterize image? Like here I only want to get the faces/vertices of the front of the cow

Thanks in Advance!

![Screenshot 2022-09-02 at 10 32 31 AM](https://user-images.githubusercontent.com/63279716/188046150-f0be5b69-daea-435e-9725-b41894dcb373.png)

**Comment by bottler** [comment]
This is in the pix_to_face element of the fragments from the rasterizer. If you use MeshRendererWithFragments, then you will get this in the output of the renderer as well as the images.

**Comment by kentdan** [comment]
Thanks a lot this is what I am looking for!
