### ISSUE TITLE
is it possible to get a displacement map from the fitted mesh?

### ISSUE THREAD

**Issue by chacorp** [facebookresearch/pytorch3d#1322]
Hello 

Thanks for this great project! 

With this project, I want to fit a template mesh to the target mesh and save the displacement of each vertex as a texture format.
I'd like to know whether it's possible to get a displacement map from the fitted mesh.

Thanks!

**Comment by chacorp** [comment]
I think I kinda figured it out by looking into previous issues https://github.com/facebookresearch/pytorch3d/issues/854 and https://github.com/facebookresearch/pytorch3d/issues/889
So I'm closing this issue

**Comment by ohjarwa** [comment]
> 

Hi! I also want to get a displacement map. It seems that you have some idea. Could you please share your solution? Thank you.
