### ISSUE TITLE
Pytorch3d install error(Windows)

### ISSUE THREAD

**Issue by JK1201** [facebookresearch/pytorch3d#1323]
I am using Windows with python 3.8 + cuda 11.7 + pytorch 1.7.1 + torchvision 0.8.2 + cub 1.10.0
I encountered the following problem:
(ydk_adaBins) PS D:\Git\Git\bin\pytorch3d> python setup.py install
D:\Git\Git\bin\pytorch3d\setup.py:84: UserWarning: The environment variable CUB_HOME was not found. NVIDIA CUB is required for compilation and can be downloaded from https://github.com/NVIDIA/cub/releases. You can unpack it to a location of your choice and set the environment variable CUB_HOME to the folder containing the CMakeListst.txt file.
warnings.warn(
running install
D:\anaconda\envs\ydk_adaBins\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
warnings.warn(
D:\anaconda\envs\ydk_adaBins\lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
warnings.warn(
running bdist_egg
running egg_info
writing pytorch3d.egg-info\PKG-INFO
writing dependency_links to pytorch3d.egg-info\dependency_links.txt
writing entry points to pytorch3d.egg-info\entry_points.txt
writing requirements to pytorch3d.egg-info\requires.txt
writing top-level names to pytorch3d.egg-info\top_level.txt
reading manifest file 'pytorch3d.egg-info\SOURCES.txt'
adding license file 'LICENSE'
adding license file 'LICENSE-3RD-PARTY'
writing manifest file 'pytorch3d.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
D:\anaconda\envs\ydk_adaBins\lib\site-packages\torch\utils\cpp_extension.py:305: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
warnings.warn(f'Error checking compiler version for {compiler}: {error}')
building 'pytorch3d._C' extension
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Comment by bottler** [comment]
What versions of visual studio do you have? It looks like the error is telling you to get a newer one.

**Comment by AdorableJiang** [comment]
## Environments

python 3.8
pytorch 1.8.2 LTS
cudatoolkit 11.1
cub 1.16.0
cuda 11.7
cl(compiler) 19.33.31629

## Error message
```bash
D:\ProgramData\conda_envs\dep\lib\site-packages\torch\utils\cpp_extension.py:304: UserWarning: Error checking compiler version for cl: 'utf-8' codec can't decode byte 0xd3 in position 0: invalid continuation byte
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
building 'pytorch3d._C' extension
Emitting ninja build file C:\Users\qsj28\Documents\pytorch3d\build\temp.win-amd64-cpython-38\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/44] cl /showIncludes /nologo /O2 /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -DWITH_CUDA -DTHRUST_IGNORE_CUB_VERSION_CHECK -IC:\Users\qsj28\Documents\pytorch3d\pytorch3d\csrc -ID:\ProgramData\conda_envs\dep\include -ID:\ProgramData\conda_envs\dep\lib\site-packages\torch\include -ID:\ProgramData\conda_envs\dep\lib\site-packages\torch\include\torch\csrc\api\include -ID:\ProgramData\conda_envs\dep\lib\site-packages\torch\include\TH -ID:\ProgramData\conda_envs\dep\lib\site-packages\torch\include\THC -ID:\ProgramData\conda_envs\dep\include -ID:\ProgramData\conda_envs\dep\include -ID:\ProgramData\conda_envs\dep\Include "-Id:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.33.31629\include" "-Id:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-Id:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.33.31629\include" "-Id:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" -c C:\Users\qsj28\Documents\pytorch3d\pytorch3d\csrc\iou_box3d\iou_box3d_cpu.cpp /FoC:\Users\qsj28\Documents\pytorch3d\build\temp.win-amd64-cpython-38\Release\Users\qsj28\Documents\pytorch3d\pytorch3d\csrc\iou_box3d\iou_box3d_cpu.obj -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
FAILED: C:/Users/qsj28/Documents/pytorch3d/build/temp.win-amd64-cpython-38/Release/Users/qsj28/Documents/pytorch3d/pytorch3d/csrc/iou_box3d/iou_box3d_cpu.obj
cl /showIncludes /nologo /O2 /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -DWITH_CUDA -DTHRUST_IGNORE_CUB_VERSION_CHECK -IC:\Users\qsj28\Documents\pytorch3d\pytorch3d\csrc -ID:\ProgramData\conda_envs\dep\include -ID:\ProgramData\conda_envs\dep\lib\site-packages\torch\include -ID:\ProgramData\conda_envs\dep\lib\site-packages\torch\include\torch\csrc\api\include -ID:\ProgramData\conda_envs\dep\lib\site-packages\torch\include\TH -ID:\ProgramData\conda_envs\dep\lib\site-packages\torch\include\THC -ID:\ProgramData\conda_envs\dep\include -ID:\ProgramData\conda_envs\dep\include -ID:\ProgramData\conda_envs\dep\Include "-Id:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.33.31629\include" "-Id:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-Id:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.33.31629\include" "-Id:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" -c C:\Users\qsj28\Documents\pytorch3d\pytorch3d\csrc\iou_box3d\iou_box3d_cpu.cpp /FoC:\Users\qsj28\Documents\pytorch3d\build\temp.win-amd64-cpython-38\Release\Users\qsj28\Documents\pytorch3d\pytorch3d\csrc\iou_box3d\iou_box3d_cpu.obj -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
cl: 命令行 warning D9002 :忽略未知选项“-std=c++14”
```

**Comment by ThakurSarveshGit** [comment]
> 

Hi I am getting the same error. I do not have visual studio installed on my remote ubuntu 18.04. 

My error Log:

`Failed to build pytorch3d
Installing collected packages: pytorch3d
    Running setup.py install for pytorch3d ... error
    ERROR: Command errored out with exit status 1:
     command: /home2/sarvesh.thakur/miniconda3/envs/pytorch3d/bin/python3.6 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-5r5icdzo/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-5r5icdzo/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-_52qi1sc/install-record.txt --single-version-externally-managed --compile --install-headers /home2/sarvesh.thakur/miniconda3/envs/pytorch3d/include/python3.6m/pytorch3d
         cwd: /tmp/pip-req-build-5r5icdzo/
    Complete output (209 lines):
    /tmp/pip-req-build-5r5icdzo/setup.py:74: UserWarning: The environment variable `CUB_HOME` was not found. NVIDIA CUB is required for compilation and can be downloaded from `https://github.com/NVIDIA/cub/releases. You can unpack it to a location of your choice and set the environment variable `CUB_HOME` to the folder containing the `CMakeListst.txt` file.
      "The environment variable `CUB_HOME` was not found. "
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    ... more copying statements ...
    copying pytorch3d/datasets/r2n2/r2n2_synset_dict.json -> build/lib.linux-x86_64-3.6/pytorch3d/datasets/r2n2
    running build_ext
    error: [Errno 2] No such file or directory: '/usr/local/cuda-10.2/bin:/home2/sarvesh.thakur/miniconda3/bin:/home2/sarvesh.thakur/miniconda3/bin:/home2/sarvesh.thakur/miniconda3/bin:/home2/sarvesh.thakur/miniconda3/condabin:/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home2/sarvesh.thakur/.local/bin:/home2/sarvesh.thakur/bin/bin/nvcc': '/usr/local/cuda-10.2/bin:/home2/sarvesh.thakur/miniconda3/bin:/home2/sarvesh.thakur/miniconda3/bin:/home2/sarvesh.thakur/miniconda3/bin:/home2/sarvesh.thakur/miniconda3/condabin:/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home2/sarvesh.thakur/.local/bin:/home2/sarvesh.thakur/bin/bin/nvcc'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home2/sarvesh.thakur/miniconda3/envs/pytorch3d/bin/python3.6 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-5r5icdzo/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-5r5icdzo/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-_52qi1sc/install-record.txt --single-version-externally-managed --compile --install-headers /home2/sarvesh.thakur/miniconda3/envs/pytorch3d/include/python3.6m/pytorch3d Check the logs for full command output.
`

**Comment by Peng2017** [comment]
fix them by adding "utf8" encoder here:
309 version = versionstr.decode(encoding='utf8').strip().split('.')
313 match = re.search(r'(\d+)\.(\d+)\.(\d+)', compiler_info.decode(encoding='utf8').strip())

**Comment by Castrol68** [comment]
> `
do you have solved this problem? I have a same problem.
