### ISSUE TITLE
Render signed distance function

### ISSUE THREAD

**Issue by cajoek** [facebookresearch/pytorch3d#1325]
## ❓ Questions on how to use PyTorch3D

Hi can I render a signed distance function with pytorch3d? I don't need it to be differentiable, I just want to visualize the output of my sdf model.

Thanks!

**Comment by bottler** [comment]
You can look at implicitron/models/renderer/ray_tracing.py, and how it it used in sdf_renderer.py.

**Comment by cajoek** [comment]
Thank you @bottler but I don't really understand what is going on.
I guess there is no documentation so far? Could you maybe provide a brief explanation?

**Comment by bottler** [comment]
From a camera object, you can use a raysampler to get a ray for each pixel. This gives you origins and directions. Add to that a full mask (or whatever you want) and your sdf means you can call the RayTracing object. This gives you the locations of the implicit surface. To make an image of that, you'll need some way to color them.

**Comment by cajoek** [comment]
I have not managed to figure out how to render anything yet. Should I be using the `ImplicitRenderer` from `pytorch3d.renderer`? Or how would the call to `SignedDistanceFunctionRenderer.forward()` look?

**Comment by cajoek** [comment]
I understood `sdf_renderer.py` thanks to this comment https://github.com/facebookresearch/pytorch3d/issues/1338#issue-1376151541
