### ISSUE TITLE
What would happen if specify wrong lengths in CD loss?

### ISSUE THREAD

**Issue by Hiusam** [facebookresearch/pytorch3d#1326]
## What would happen if specifying wrong lengths in CD loss?

Suppose I have point clouds with the shape [N, 15, 3] which means each point cloud has at most 15 points. But I pass the lengths arguments with some values larger than 15. 
For example, x_lenghts is [10, 20, 20] while the shape of point clouds x is x.shape = [3, 15, 3].
How would chamfer distance loss behave?
I have tried this wrong code and found that sometimes "CUDA Error: illegal memory access was encountered." was triggered but sometimes nothing happened, and the program just ran as normal. Is this a possible bug?

I am using pytorch3d 0.6.0.

**Comment by bottler** [comment]
The calculation is not designed to cope with the lengths argument containing values which are too high, like you say. In particular, the CUDA code for the knn calculation, which chamfer uses, will do the wrong thing, which may or may not cause that CUDA error.

**Comment by Hiusam** [comment]
ok, got it!
