### ISSUE TITLE
Only Lego and fern available?

### ISSUE THREAD

**Issue by resurgo97** [facebookresearch/pytorch3d#1328]
Hi, I am looking for nerf-synthetic dataset of other scenes than Lego. (e.g., ficus, mic, ship, drums, ...), 
that can be used in your implementation.
I downloaded Lego dataset from `./nerf/datatset.py`, but I cannot download others.

Is only Lego available at the moment?

**Comment by bottler** [comment]
There are two separate implementations. projects/nerf is the older one uses its own data format and we don't provide other scenes. Implicitron is the new flexible framework for training implicit models. It has more general dataloaders, and can load any of the scenes. It reads the original data.

**Comment by resurgo97** [comment]
Thanks for your reply.
I think I need to stick with the older `nerf`, because what I want is the most accurate reproduction of NeRF (in Pytorch).
As I look into the lego dataset, I could generate other datasets in the same format, so no worries.

Can I ask one more question? I wonder how much faithful this is in terms of reproducibility.
I see it results in 1~2 higher PSNR on Lego, where is this gain from? 

Thanks a lot!

**Comment by resurgo97** [comment]
Never mind, I should have tried running the code before asking.
