### ISSUE TITLE
[Quick Question] Are there any examples of data augmentation for PyTorch3D/Co3D?

### ISSUE THREAD

**Issue by greeneggsandyaml** [facebookresearch/pytorch3d#1335]
### Quick question about data augmentation

---

Hello authors, thanks for the library. Are there any examples of data augmentation using PyTorch3D (e.g. for Co3D or ShapeNet)? This sounds like a trivial question, but it's not completely trivial. For example, when you crop, you have to adjust the camera parameters accordingly, and when you perform color augmentations, you have to adjust the point cloud colors accordingly. 

I was just wondering if anyone has done this before. If not, I'll just write it myself.

Best,

**Comment by bottler** [comment]
PyTorch3D does not support this but it would be a good feature.
