### ISSUE TITLE
Installation error on Windows 10

### ISSUE THREAD

**Issue by cuirq3** [facebookresearch/pytorch3d#1337]
Hi,

I am trying to install Pytorch3D in Windows10 with CUDA 11.1, Pytorch 1.10.1, and VS2019.

I followed the installation guides in issues #172 and #735. I checked all the folders you mentioned and they all exist.

For now, I met these errors below. Maybe you have ideas about what the problems are?

D:\EPFL\SP\NPGB\Pytorch3d\pytorch3d\pytorch3d\csrc\iou_box3d/iou_utils.h(150): warning C4305: 'argument': truncation from 'const double' to 'float'
D:\EPFL\SP\NPGB\Pytorch3d\pytorch3d\pytorch3d\csrc\iou_box3d/iou_utils.h(446): warning C4305: 'argument': truncation from 'const double' to 'float'
D:\EPFL\SP\NPGB\Pytorch3d\pytorch3d\pytorch3d\csrc\iou_box3d/iou_utils.h(511): error C2429: language feature 'structured bindings' requires compiler flag '/std:c++17'
D:\EPFL\SP\NPGB\Pytorch3d\pytorch3d\pytorch3d\csrc\iou_box3d/iou_utils.h(513): error C2512: 'vec3<float,void>': no appropriate default constructor available
D:\EPFL\SP\NPGB\Pytorch3d\pytorch3d\pytorch3d\csrc\iou_box3d/iou_utils.h(65): note: see declaration of 'vec3<float,void>'
D:\EPFL\SP\NPGB\Pytorch3d\pytorch3d\pytorch3d\csrc\iou_box3d/iou_utils.h(514): warning C4305: 'argument': truncation from 'const double' to 'float'
D:\EPFL\SP\NPGB\Pytorch3d\pytorch3d\pytorch3d\csrc\iou_box3d/iou_utils.h(545): error C2429: language feature 'structured bindings' requires compiler flag '/std:c++17'
D:\EPFL\SP\NPGB\Pytorch3d\pytorch3d\pytorch3d\csrc\iou_box3d/iou_utils.h(547): error C2512: 'vec3<float,void>': no appropriate default constructor available
D:\EPFL\SP\NPGB\Pytorch3d\pytorch3d\pytorch3d\csrc\iou_box3d/iou_utils.h(65): note: see declaration of 'vec3<float,void>'
D:\EPFL\SP\NPGB\Pytorch3d\pytorch3d\pytorch3d\csrc\iou_box3d/iou_utils.h(548): warning C4305: 'argument': truncation from 'const double' to 'float'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

Thanks for your help!

**Comment by cuirq3** [comment]
I just solved my problem by myself.

Here is what I did:

1. I downgraded pytorch3d to version 0.6.2, the error above didn't come out again.
2. Then new errors about CUB version came out. I followed its instruction to remove the CUB 1.10 path in PATH to use the CUB from Nvidia.

And then I successfully installed Pytorch3d

Hope it's useful for anyone else :)

**Comment by ra1995** [comment]
Solved the issue by using the following steps:

0) Build nvidia thrust using vs2019 and add it to os environment CUB_HOME='C:/Program files/Thrust/include'
1) Use the x64 Native Tools Command Prompt for VS 2019
2) Check if cl and nvcc commands are working correctly with the required versions and activate python virtualenv/condaenv
3) add os.environ["DISTUTILS_USE_SDK"] = "1" at line 39
4) run python setup.py build install
