### ISSUE TITLE
RuntimeError: index -1 is out of bounds for dimension 1 with size 4096

### ISSUE THREAD

**Issue by QasimKhan5x** [facebookresearch/pytorch3d#1339]
I am getting this error while performing Ball Query on the features of a tensor (point cloud). The expected output should be a tensor of shape `(2, 1024, 16, 4)` but instead I am getting an error. My version of pytorch3d is 0.7.0 and pytorch version is 1.10.1. I have installed from source using the main branch.

### Code to reproduce

    import torch
    from pytorch3d.ops import ball_query, knn_gather, sample_farthest_points
    
    
    def subsample(p, stride=4): return sample_farthest_points(p, K=p.shape[1] // stride)[0]
    
    B = 4
    N = 4096
    C = 4
    # B x N x 3
    p = torch.empty(size=(B, N, 3), device='cpu').normal_(mean=0, std=0.1)
    # B x C x N
    x = torch.empty(size=(B, C, N), device='cpu').normal_(mean=0, std=0.1)
    
    p_fps = subsample(p)
    _, idx, p_nn = ball_query(p_fps, p, K=16, radius=0.1)
    ftrs = x.transpose(1, 2).contiguous()
    out = knn_gather(ftrs, idx)
    print(out.shape)

### Error

    Traceback (most recent call last):
      File "test.py", line 22, in <module>
        out = knn_gather(ftrs, idx)
      File "/home/pytorch3d/pytorch3d/ops/knn.py", line 235, in knn_gather
        x_out = x[:, :, None].expand(-1, -1, K, -1).gather(1, idx_expanded)
    RuntimeError: index -1 is out of bounds for dimension 1 with size 4096

**Comment by bottler** [comment]
Such error checks can slow things down (e.g. because they add synchronization between host and device) so it isn't always a good idea to add them. I think in this case it's not so hard to debug what has gone wrong, so it wouldn't be worth it.
