### ISSUE TITLE
How to convert 3D obj to 2D UV mapping texture?

### ISSUE THREAD

**Issue by nguyenquocduongqnu** [facebookresearch/pytorch3d#1341]
## ❓ How to convert 3D obj to 2D UV mapping texture?

I want to convert [3D obj file](https://drive.google.com/drive/folders/12RPxllBfgSwQQlkjmMIiAc2rADHru3sW?usp=sharing) to 2D UV format. 
Example of a 2D image captured from 3D:
![image](https://user-images.githubusercontent.com/63329565/190981019-cb4cbd02-1353-4908-9086-64d6d1881b54.png)

I expected results like this:

![image](https://user-images.githubusercontent.com/63329565/190981809-780e8a9b-2d02-417b-bba9-e4a654225193.png)

Can someone help me? Many thank.

**Comment by YunnaChen** [comment]
Has this problem been solved?

**Comment by bottler** [comment]
It is unclear what the question is here. If you have a new question,  open a new issue.
