### ISSUE TITLE
Is there any way to quickly calculate the intersection of the ray with the mesh and the signed distance from the point to the mesh?

### ISSUE THREAD

**Issue by caiyongqi** [facebookresearch/pytorch3d#1346]
Is there any way to quickly calculate the intersection of the ray with the mesh and the signed distance from the point to the mesh?
such as:
**https://github.com/fwilliams/point-cloud-utils#ray-mesh-intersection**
**https://github.com/fwilliams/point-cloud-utils#compute-shortest-signed-distances-to-a-triangle-mesh-with-fast-winding-numbers**

**Comment by bottler** [comment]
You could use the renderer for an image with only one pixel.
