### ISSUE TITLE
Installing PyTorch3D from pip onto an Apple Silicon Mac is broken

### ISSUE THREAD

**Issue by jashugan** [facebookresearch/pytorch3d#1348]
## Instructions To Reproduce the Issue:

Using an Apple Silicon Mac.

1. `pip install pytorch3d`
2. open up a Python console and `import pytorch3d`

## Expected behavior

The import statement would work.

## Actual behavior

```
[ins] In [2]: import pytorch3d
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-373ec51d3d6c> in <cell line: 1>()
----> 1 import pytorch3d

ModuleNotFoundError: No module named 'pytorch3d'
```

## Workaround

I was able to follow `INSTALL.md` and install PyTorch3d from source using `MACOSX_DEPLOYMENT_TARGET=10.14 CC=clang CXX=clang++ pip install "git+https://github.com/facebookresearch/pytorch3d.git"`.  

## Analysis

pip claims 0.0.1 is installed:
```
❯ pip freeze | grep pytorch3d
pytorch3d==0.0.1
```

The [wheels in PyPI](https://pypi.org/project/pytorch3d/#modal-close) show that that only x86 architecture wheels have been uploaded. Why is pip installing 0.0.1 when the latest version is 0.7.0? Shouldn't it at least error out saying that no versions could be found? This behavior is surprising and took me some time to figure out what's going on.

**Comment by bottler** [comment]
On pypi, there was an empty pytorch3d package with version number 0.0.1 which was targeting any architecture. I have now removed it so it won't happen again.
