### ISSUE TITLE
Clarification on fragments.zbuf

### ISSUE THREAD

**Issue by yuya737** [facebookresearch/pytorch3d#1349]
A simple clarification: the output from `somerasterizer.forward()` (i.e. the `fragment` in pytorch3d language) and in particular the `fragment.zbuf` tensor should be differentiable with respect to the input parameters like cameras correct?

A beginner here....

**Comment by bottler** [comment]
Yes, all the rasterizers in PyTorch3D except MeshRasterizerOpenGL are differentiable, and for them you should see gradients flowing back from the depths to the cameras.
