### ISSUE TITLE
Access is denied install Pytorch3d - Windows 10

### ISSUE THREAD

**Issue by claragarciamoll** [facebookresearch/pytorch3d#1353]
Hello, I need to install Pytorch3d using Windows 10 as SO. My environment is:
Python 3.7
Pytorch 1.10.2
CUDA toolkit 10.2
CUB 1.10.0
I clone the repository and then execute:

    call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
    set DISTUTILS_USE_SDK=1
    set CUDA_HOME="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2"
    set CUDA_PATH="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2"
    set CUB_HOME="D:/cub-1.10.0”
    cd pytorch3d
    python setup.py install
    And I get the following error:
    running install

Anaconda3\envs\envPytorch3d\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
Anaconda3\envs\envPytorch3d\lib\site-packages\setuptools\command\easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
running bdist_egg
running egg_info
writing pytorch3d.egg-info\PKG-INFO
writing dependency_links to pytorch3d.egg-info\dependency_links.txt
writing entry points to pytorch3d.egg-info\entry_points.txt
writing requirements to pytorch3d.egg-info\requires.txt
writing top-level names to pytorch3d.egg-info\top_level.txt
reading manifest file 'pytorch3d.egg-info\SOURCES.txt'
adding license file 'LICENSE'
adding license file 'LICENSE-3RD-PARTY'
writing manifest file 'pytorch3d.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
error: [WinError 5] Access is denied

**Comment by bottler** [comment]
You cannot install into the global environment (which I don't think you want to do anyhow) if you aren't running as administrator. I think it would be best to create a conda environment or virtual environment or similar, and install inside that.

**Comment by claragarciamoll** [comment]
Thanks for your advise. However, I created the conda environment and install pytorch3d inside that and also run it as administrator and the error is the same.

**Comment by bottler** [comment]
Can you install other packages? This might be beyond what we can help with.
