### ISSUE TITLE
Point cloud to Mesh

### ISSUE THREAD

**Issue by ShairozS** [facebookresearch/pytorch3d#136]
Is there support or plans to support a method for point cloud triangulation (such as Delaunay triangulation) to estimate a mesh from a set of (N,3) points?

**Comment by gkioxari** [comment]
Hi @ShairozS! We have (batched) data structure support for [pointclouds](https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/structures/pointclouds.py) and [meshes](https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/structures/meshes.py). Converting the former to the latter is an important feature. One could apply traditional techniques such as Delaunay or even try to learn the connectivity via other ways, which is an open research problem. It's not in our immediate plan to support Delaunay triangulation as we are focusing on other features, but if you end up implementing something we'd happy to review it and incorporate it to PyTorch3D.

**Comment by gkioxari** [comment]
I will be closing this issue for now as it is not regarding an issue with the codebase.
