### ISSUE TITLE
dl.fbaipublicfiles.com download links no longer working 

### ISSUE THREAD

**Issue by aaroncsolomon** [facebookresearch/pytorch3d#1366]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## 🐛 Bugs / Unexpected behaviors
The download links for pointed to by https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md are no longer working. For example, https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py38_cu113_pyt1110/download.html returns an access denied payload.

NOTE: Please look at the existing list of Issues tagged with the label ['bug`](https://github.com/facebookresearch/pytorch3d/issues?q=label%3Abug). **Only open a new issue if this bug has not already been reported. If an issue already exists, please comment there instead.**.

## Instructions To Reproduce the Issue:
Follow instructs to download Linux wheels

**Comment by bottler** [comment]
This is because we had a new release 0.7.1 yesterday and we removed the previous version's wheels and made new wheels as needed for Colab, which is what primarily the linux wheels are aimed at. In a repeat of #1289 I have just added more builds.  Now the linux wheels available are (Python 3.8, 3.9 and 3.10) ⨉ (PyTorch 1.11.0, 1.12.0 and 1.12.1), as well as Python 3.7 with PyTorch 1.12.1. All are just for CUDA 11.3.

**Comment by BotScutters** [comment]
@bottler 
Is there any public-facing page where we can see what linux wheels are available for download?
Also, if I may ask--why is Colab specifically the priority here? These pre-built wheels are very convenient in many use cases, and in an environment where conda isn't used for anything else, these wheels have sometimes been the only way I've been able to get pytorch3d to successfully install.

**Comment by aaroncsolomon** [comment]
@BotScutters +1 - these wheels are generally quite useful, we have the same use case (non-conda environment) and these are incredibly useful. @bottler would be great to just make them generally available and maintain pointers to the most recent wheels in the install README
