### ISSUE TITLE
Bug in obj_io.py with shapenet

### ISSUE THREAD

**Issue by naifuliang** [facebookresearch/pytorch3d#1368]
## 🐛 Bugs / Unexpected behaviors

Error Information:
```bash
line 635, in _load_obj
    face_material_names = np.array(material_names)[idx]  # (F,)
IndexError: index -1 is out of bounds for axis 0 with size 0
```

## Instructions To Reproduce the Issue:

[https://github.com/facebookresearch/pytorch3d/blob/main/pytorch3d/datasets/shapenet/shapenet_core.py line](https://github.com/facebookresearch/pytorch3d/blob/main/pytorch3d/io/obj_io.py#L648)

```python
        # Create an array of strings of material names for each face.
        # If faces_materials_idx == -1 then that face doesn't have a material.
        idx = faces_materials_idx.cpu().numpy()
        face_material_names = np.array(material_names)[idx]  # (F,)
        face_material_names[idx == -1] = ""
```

If idx ==-1,   np.array(material_names)[-1] will be executed, which causes an error.

**Comment by bottler** [comment]
If this was still an issue then https://github.com/facebookresearch/pytorch3d/commit/9acdd67b831f2d3d9db249b1c46d42139024cebf must have squashed it just now.
