### ISSUE TITLE
How to get the depth image?

### ISSUE THREAD

**Issue by ldepn** [facebookresearch/pytorch3d#137]
## ❓ Questions on how to use PyTorch3D
when i use pytorch3d to render a model, i want to get the depth image, how to do? 

NOTE:

1. If you encountered any errors or unexpected issues while using PyTorch3D and need help resolving them,
   please use the "Bugs / Unexpected behaviors" issue template.

2. We do not answer general machine learning / computer vision questions that are not specific to
	 PyTorch3D, such as how a model works or what algorithm/methods can be
	 used to achieve X.

**Comment by gkioxari** [comment]
Hi @ldepn! 
We provide really detailed [tutorials](https://pytorch3d.readthedocs.io/en/latest/overview.html#tutorials), [notes](https://github.com/facebookresearch/pytorch3d/blob/master/docs/notes/renderer_getting_started.md) and API [documentation](https://pytorch3d.readthedocs.io/en/latest/modules/renderer/index.html) on the rendering tools. This information should be more than enough to allow you to navigate around the tools in PyTorch3D. In addition to that, some fellow users have also raised similar questions, e.g. this issue https://github.com/facebookresearch/pytorch3d/issues/35 should be of help.

**Comment by ldepn** [comment]
@gkioxari  thanks ！

**Comment by theschnitz** [comment]
We are landing a change now that introduces MeshRendererWithFragments that returns images, fragments into the renderer library which you can use in the future.
