### ISSUE TITLE
MORE MESH REGULARITY WHEN DEFORMING A MESH

### ISSUE THREAD

**Issue by JJab0n** [facebookresearch/pytorch3d#1370]
Hello world,

First of all, thank you for releasing this amazing library.
I am trying to deform a source mesh (sphere) to copy the shape of a target mesh following the tutorial available.
Although the result is quite good. I would like to ask if there is an option to get a more regular mesh regarding the tria elements' size. Is there any tool available to achieve this? Or I should program, for example, an error function that measures the amount of variation or dispersion of the triangles' area that form the mesh?

For example, following the tutorial of the dolphin. The size of the elements that form the tail higher than those that form the body.

May be @bottler can help me.
Thanks in advance for your help.

**Comment by bottler** [comment]
This is a research question rather than one about the library, so we can't really help here. It may be that careful use of some of the losses (like laplacian) is useful.
