### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by anna-charlotte** [facebookresearch/pytorch3d#1376]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## 🐛 Bugs / Unexpected behaviors
I am encountering the following import error:

<img width="1548" alt="image" src="https://user-images.githubusercontent.com/73693835/200274696-f20dae33-151f-44b7-9c2e-2e0a96ce6478.png">

## Instructions To Reproduce the Issue:
Running `import pytorch3d.io` in a script, causes this error. I used python 3.7.12

**Comment by sainatarajan** [comment]
Are you running your code in Windows?
