### ISSUE TITLE
in NeRF, how to set the config (.yaml file) and camera setting (.pth file) correctly and optimally?

### ISSUE THREAD

**Issue by BlackPi3** [facebookresearch/pytorch3d#1380]
## ❓ How to set .yaml and .pth files correctly?

Hi @bottler ,

My question has two parts:
1. How to set the **.yaml** config file?
There are some scene-related items in the .yaml config file that I'd like to know how you set them, such as:
- **min_depth** and **max_depth** (how to set which points rays should start and stop?)
- **up** (is it the camera's up? in Lego it's 0,0,1 and in Fern it's 0,1,0. why is that?
- **scene_center** (how do you know where is scene's center is?)
- **trajectory type** and **trajectory scale** (is figure_eight for light field kind of images?)

2. How to set the **.pth** camera setting
[Here](https://github.com/facebookresearch/pytorch3d/issues/820#issuecomment-909378541) you explained the .pth file, but by following your instructions, I couldn't train NeRF correctly. Here is what I mean:
As a test, I wanted to convert **LLFF**'s fern camera setting to pytorch3d camera setting. bmild explains [here ](https://github.com/Fyusion/LLFF/issues/10#issuecomment-514406658)how its **.npy** file works. As a result for camera positions I got:
this is **your camera position**:
![image](https://user-images.githubusercontent.com/16107268/201313678-730efa83-2afc-4eda-b0ac-871a26be499e.png)
this is **my camera positions** (based on LLFF camera positions):
![image](https://user-images.githubusercontent.com/16107268/201313909-84022ff6-6e73-409a-86f3-839257490b3c.png)
the x-y orientation of points is the same, but in your case, they are more packed together. However, the z value of the cameras is not that related.  
I understand that the more packed the cameras are, the more overlaps their rays have in the scene so the question is how do you set it? Is it a single transformation you apply to LLFF camera poses? Also, my camera rotation and yours are also different a bit. Mine is like they're diverging and yours are converging.
Do you also take LLFF data and then convert them? or did you originally derive camera positions from images?

Thank you.

**Comment by davnov134** [comment]
Hi, the Implicitron yaml files contain settings for Blender. Please follow the Implicitron readme to run our NeRF implementation on the Blender Synthetic scenes (the readme describes both training and visualisation):
https://github.com/facebookresearch/pytorch3d/tree/main/projects/implicitron_trainer#nerf
