### ISSUE TITLE
How to render the semantic labels of a 3D model?

### ISSUE THREAD

**Issue by willer94** [facebookresearch/pytorch3d#1381]
## ❓How to render the semantic labels of a 3D model?

Is there a tutorial to render semantic maps given a labelled 3D model? It is widely used in generating synthetic datasets w.r.t  semantic segmentation.

**Comment by willer94** [comment]
Solved by modifying `HardDepthShader`.

**Comment by ForrestPi** [comment]
@willer94 could you share the code?
