### ISSUE TITLE
 Is there a way to return the  RGB value of each barycentric coordinate?

### ISSUE THREAD

**Issue by kentdan** [facebookresearch/pytorch3d#1383]
## ❓ Is there any way to return the XYZ and RGB value of each barycentric coordinate?

After rendering I tried to return a point in the center of each pixel(point in a triangle) which was represented by a barycentric coordinate. Is there a way to return the RGB value of each point?

**Comment by bottler** [comment]
Do you mean for the nearest triangle for each pixel? If so, wouldn't the RGB value you are after be exactly the output of the renderer if you use HardFlatShader? 

And for the XYZ, you can use the fragments (e.g. if you render with MeshRendererWithFragments).

- For each pixel, you can get the barycentric coordinates of the point from fragments.bary_coords. You can get the corners of the corresponding face by indexing into mesh.faces_packed() with fragments.pix_to_face. Then the XYZ is the sum of the products of those two.
