### ISSUE TITLE
Cannot find reference '_C' in '__init__.py' 

### ISSUE THREAD

**Issue by liwenssss** [facebookresearch/pytorch3d#1384]

**Comment by liwenssss** [comment]
I am using the version 0.7.0

**Comment by bottler** [comment]
We need a lot more information to be able to help. What is your setup? How did you install pytorch3d?

**Comment by liwenssss** [comment]
> We need a lot more information to be able to help. What is your setup? How did you install pytorch3d?

Hi @bottler , I install pytorch3d with the code:
```
import sys
import torch
pyt_version_str=torch.__version__.split("+")[0].replace(".", "")
version_str="".join([
    f"py3{sys.version_info.minor}_cu",
    torch.version.cuda.replace(".",""),
    f"_pyt{pyt_version_str}"
])
```
and run "pip install --no-index --no-cache-dir pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/{version_str}/download.html". 
Specifically， I run "pip install --no-index --no-cache-dir pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py37_cu113_pyt1121/download.html" .

**Comment by bottler** [comment]
We still need much more information. Are you using pip/conda? What is your general setup with python? What do you see in `pip list` and, if conda,  `conda list`? Do you know where pytorch3d is installed? If so, what is in its directory? etc.

The source of the error could be that you have an unbuilt source tree of pytorch3d which is being picked up, or you have an installation which doesn't correspond to your version of pytorch or cuda.

**Comment by liwenssss** [comment]
Sorry, but I can't seem to import it into Pycharm. However, when I ran it through the terminal, it was successful. So, do you know how to fix it?

**Comment by bottler** [comment]
Like I said earlier, you need to provide much more information for us to be able to help.
