### ISSUE TITLE
Artifacts when Rendering Mesh of a Specific .obj Exported from Blender 

### ISSUE THREAD

**Issue by karim-eladl** [facebookresearch/pytorch3d#139]
Hi! I'm new to pytorch3d and am working on a project so any help at all is greatly appreciated as I may just not be familiar with some aspects of pytorch3d. 

I'm trying to render a .obj (with .mtl and texture.png) of a plate that I created with Blender. Right now, I just modified the render_textured_meshes.ipynb found on the github under /docs/tutorials to take my .obj. When I test it with the provided cow mesh it works perfectly. When I test it with any other object I create in Blender it works fine. However, with my plate models of varying sizes the pytorch3d has strange black lines that do not appear in the Blender render or when I export an image of my Blender model (attached below). I'm creating the plate in Blender by adding a circle, setting fill to ngon, extruding up, scaling the top face of this cylinder out, extruding up again, scaling the top face out again, and then deleting the top face. The artifacts appear only when I use an object where I scaled the top face out. (renders attached below)

I pretty sure the problem is not with Blender. The pytorch3d script clearly works with all .obj's I made where I didn't do this scaling. I'm really at a loss for why this is a problem and wondering if this has something to do with the different shaders or renderers in pytorch3d. Please let me know any things I should look into or try. Thank you so much!

image of model exported from blender:
![plate](https://user-images.githubusercontent.com/59456868/78459085-98d3cf00-7684-11ea-87bb-653ce16bc878.png)

pytorch3d renders:
![batch_render](https://user-images.githubusercontent.com/59456868/78459107-b739ca80-7684-11ea-8fc8-0597e0719b56.jpg)

**Comment by nikhilaravi** [comment]
Hi @karim-eladl, can you share the `.obj` and `.mtl` file so we can try to reproduce the error?

**Comment by karim-eladl** [comment]
Yes @nikhilaravi, sure! I added .txt so I could attach them. Thanks!

[plate.mtl.txt](https://github.com/facebookresearch/pytorch3d/files/4435281/plate.mtl.txt)
[plate.obj.txt](https://github.com/facebookresearch/pytorch3d/files/4435282/plate.obj.txt)
![plate_texture](https://user-images.githubusercontent.com/59456868/78513290-77540f80-7778-11ea-8cf3-1436e8437794.jpg)

**Comment by nikhilaravi** [comment]
@karim-eladl I had a look into this for you. It seems this is an issue with the vertex uv coordinates not the rasterization i.e. just plotting the output of rasterization gives the correct shape:

<img width="100" alt="Screen Shot 2020-04-29 at 9 02 10 PM" src="https://user-images.githubusercontent.com/5912647/80671101-b0249300-8a5d-11ea-9028-218bbcbdc834.png">

Also as the texture map is all one color if you set the vertex uvs to all be the same value it gives the desired output i.e. 
```
verts_uvs = mesh.textures.verts_uvs_padded()
mesh.textures._verts_uvs_padded[..., :] = verts_uvs[0]
```

<img width="543" alt="Screen Shot 2020-04-29 at 9 17 43 PM" src="https://user-images.githubusercontent.com/5912647/80671502-e31b5680-8a5e-11ea-9915-73f988f70b3d.png">

It seems like there are a few places where the interpolated texture value is empty i.e. rgb (0, 0, 0).  I suggest inspecting the vertex uv coordinates and the interpolated values by printing them here: https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/renderer/mesh/texturing.py#L47.  

If you are still unable to resolve the issue I can take another look later!

**Comment by nikhilaravi** [comment]
@karim-eladl I will close this issue as there has been no response. If you still need help, feel free to reopen the issue.
