### ISSUE TITLE
Which version of the PyTorch3D can I install?

### ISSUE THREAD

**Issue by ALEEEHU** [facebookresearch/pytorch3d#1396]
My PyTorch is 1.10.2+cu113 and my version of cuda is 11.3

I wondered to know which version of the PyTorch3D I can install without the conflicts. 

Please give me some instructions, thanks!

**Comment by bottler** [comment]
Assuming you are on Linux, using conda, and the Python version is 3.7, 3.8 or 3.9 then the latest version 0.7.1 of PyTorch3D has a conda package for you, and you should be able to get it with 

```
conda install -c fvcore -c iopath -c conda-forge fvcore iopath
conda install pytorch3d -c pytorch3d
```

For windows, or for Python 3.10 or later or if you can't rely on conda then you need to build PyTorch3D from source, and the latest version or the main branch is fine.

**Comment by bottler** [comment]
If the `conda install pytorch3d -c pytorch3d` is failing with conflicts then give your `conda list` and `conda info` output here and we might be able to help.

**Comment by ALEEEHU** [comment]
Thanks for your prompt reply and detailed instructions! 

I've solved the issue and found out that using the following code to install the newest version of pytorch3d (pytorch3d   0.7.2) suits well with my circumstances.

`git clone https://github.com/facebookresearch/pytorch3d.git`
`cd pytorch3d && pip install -e .`
