### ISSUE TITLE
Tutorial not working because wheels never finish building

### ISSUE THREAD

**Issue by skmda37** [facebookresearch/pytorch3d#1397]
Hi, I am trying to run the official Pytorch3D tutorials on google colab. After running the first code cell that is supposed to install PyTorch 3D, I don't get past `Building wheels for collected packages: pytorch3d, fvcore, iopath`. Why can I not finish building the wheels?

The Google Colab has

torch__version__ == 1.13.0+cu116
CUDA version 11.2

Thank you so much in advance for any help!

**Comment by bottler** [comment]
Building should take a long time. How long are you waiting?

I'm in the process of making a new release of PyTorch3D, 0.7.2, which will have binaries for colab so that you the tutorials do not need to build from source. This should be done in the next few days.

**Comment by bottler** [comment]
New release is done.
