### ISSUE TITLE
Pretrained Models

### ISSUE THREAD

**Issue by atemysemicolon** [facebookresearch/pytorch3d#14]
## 🚀 Feature
Will pytorch3d plan to support 3D pretrained deep learning models such as Mesh RCNN?

## Motivation
Will be nice to have a bunch of pretrained models to start playing with. Incrememental work would become much easier.

## Pitch
--- None as of now --

**Comment by nikhilaravi** [comment]
Hi @atemysemicolon, thanks for your question. PyTorch3d is a library of reusable components rather than a framework so we don't currently have plans to support pre-trained models. Mesh R-CNN is released as a separate project here: https://github.com/facebookresearch/meshrcnn
