### ISSUE TITLE
unclear installation instructions lead to pytorch cpu only

### ISSUE THREAD

**Issue by xvdp** [facebookresearch/pytorch3d#1403]
The third line of the installation instructions in https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md misleads to accidental installation of pytorch without cuda - an error I failed to notice at first as cudatoolkit is mentioned in said line. 
It should be clearly stated what the installation options are and perhaps reference to pytorch installation site https://pytorch.org/get-started/locally/

replacing 
```conda install -c pytorch pytorch=1.9.1 torchvision cudatoolkit=11.6```
for 
```conda install pytorch torchvision torchaudio pytorch-cuda=11.6 -c pytorch -c nvidia```
--in  my case as im still on 11.6 --- solves the issue

**Comment by Mason-McGough** [comment]
I ran into this issue as well. Somehow the previous instructions ended up installing `cpuonly` on my system. The fix worked for me and is more consistent with the latest instructions on the pytorch website.
