### ISSUE TITLE
About the problem that the installed pytorch3D cannot use the GPU

### ISSUE THREAD

**Issue by xiao-lin-hub** [facebookresearch/pytorch3d#1407]
My pytorch version is 1.8.1,  python version is 3.7.15, cuda version is 11.1. 
I have tried different versions of pytorch3D, but none of them can support GPU operations. I wonder if this is because there is no corresponding pytorch3D-GPU version

**Comment by bottler** [comment]
The latest release of PyTorch3D does not have builds for your versions of Python, CUDA and PyTorch, which are all quite old and the Python and PyTorch are unsupported. Can you use an old build or use newer dependencies?

**Comment by xiao-lin-hub** [comment]
> The latest release of PyTorch3D does not have builds for your versions of Python, CUDA and PyTorch, which are all quite old and the Python and PyTorch are unsupported. Can you use newer dependencies or build from source?

thank you very much! I will try it.
