### ISSUE TITLE
Bundle Asjustment: No module named 'camera_visualisation'

### ISSUE THREAD

**Issue by albertotono** [facebookresearch/pytorch3d#141]
## 🐛 Bugs / Unexpected behaviors
While running the Google Colab notebook (Absolute camera orientation given set of relative camera pairs) I got the following error: 
![image](https://user-images.githubusercontent.com/11828200/78512552-701e0900-775a-11ea-9ce1-e55c05013cc3.png)
--2020-04-05 23:26:49--  https://raw.githubusercontent.com/facebookresearch/pytorch3d/master/docs/tutorials/utils/camera_visualisation.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-04-05 23:26:49 ERROR 404: Not Found.

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-11-21501aefa026> in <module>()
      1 get_ipython().system('wget https://raw.githubusercontent.com/facebookresearch/pytorch3d/master/docs/tutorials/utils/camera_visualisation.py')
----> 2 from camera_visualisation import plot_camera_scene
      3 
      4 get_ipython().system('mkdir data')
      5 get_ipython().system('wget -P data https://raw.githubusercontent.com/facebookresearch/pytorch3d/master/docs/tutorials/data/camera_graph.pth')

ModuleNotFoundError: No module named 'camera_visualisation'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

Any ideas? Thank you so much for the help

**Comment by nikhilaravi** [comment]
@albertotono I checked the filename and it is `camera_visualization.py` (`z` instead of `s`) - please make this change locally and we will update the tutorials. Thanks for pointing this out!
