### ISSUE TITLE
Support with PyTorch 1.13.1

### ISSUE THREAD

**Issue by flyyyyer** [facebookresearch/pytorch3d#1410]

**Comment by bottler** [comment]
The latest release of PyTorch3D (0.7.2) supports PyTorch 1.13.1 and now has conda packages for linux for PyTorch 1.13.1. I think there's nothing more to do.

**Comment by Haobo-Liu** [comment]
> The latest release of PyTorch3D (0.7.2) supports PyTorch 1.13.1 and now has conda packages for linux for PyTorch 1.13.1. I think there's nothing more to do.

Could you tell me how I can install a correct specific version of pytorch3d in conda environment?

**Comment by bottler** [comment]
Set up the environment with the dependencies you need (may help to look in the README at the version you want) then `conda install pytorch3d==1.13.1` or whatever.
