### ISSUE TITLE
FoVPerspectiveCameras transforms unexpected behaviour

### ISSUE THREAD

**Issue by 3a1b2c3** [facebookresearch/pytorch3d#1415]
So i create 2 FoVPerspectiveCameras and draw them with scene_plot(). They are to different scenes using 1 layout
Same translation values, one cam is also rotate 180. 
The result pictured is not what i expect at all, can somebody please help me how to use it?
I would like to match the translates between cameras while still rotating the camera. Is the behavioral described expected? Can i do it another way?

![image](https://user-images.githubusercontent.com/74843139/210747493-c5a86ac1-cc00-4c06-8b93-3016b506c38c.png)

    T = torch.Tensor( [[ 10,  20.2,  30  ] ]).to(torch.float)
    R =  torch.Tensor( [[[1., 0.,  0],
                          [0., 1.,  0],
                          [0., 0.,  -1]]

    torch_cameras_default = FoVPerspectiveCameras( # red 
            # The default world coordinate frame in PyTorch3D has +Z pointing in to the screen whereas in OpenGL, +Z is pointing out of the screen. Both are right handed.
            fov=float(ns_cameras[index].fx.cpu().numpy()[0]), # degrees
            aspect_ratio=ns_cameras[index].width/ns_cameras[index].height,
            T=T, 
            device=device.type
    )
    torch_cameras = FoVPerspectiveCameras( # blue
            # The default world coordinate frame in PyTorch3D has +Z pointing in to the screen whereas in OpenGL, +Z is pointing out of the screen. Both are right handed.
            fov=float(ns_cameras[index].fx.cpu().numpy()[0]), # degrees
            aspect_ratio=ns_cameras[index].width/ns_cameras[index].height,
            R=R,
            T=T, 
            device=device.type
    )

**Comment by Mason-McGough** [comment]
The `R` and `T` camera extrinsics that `FoVPerspectiveCameras` expect define the transformation applied to convert points from world space into the camera space (described [here](https://github.com/facebookresearch/pytorch3d/blob/main/docs/notes/cameras.md)). This example illustrates the difference.

```
from pytorch3d.renderer import (
    look_at_view_transform,
    camera_position_from_spherical_angles,
    FoVPerspectiveCameras
)

R, Tc = look_at_view_transform(dist=-5.0, elev=0, azim=0, eye=None)
Tw = camera_position_from_spherical_angles(distance=-5.0, elevation=0, azimuth=0)
cameras = FoVPerspectiveCameras(R=R, T=Tc)
c = cameras.get_camera_center()
print(f'Tw: {Tw}')  # camera position in world coordinates
print(f'c:  {c}')   # optical center of camera in world coordinates
print(f'Tc: {Tc}')  # world-to-view transform translation
print(f'R:  {R}')   # world-to-view transform rotation
```

The output I get is this:

```
Tw: tensor([[-0., -0., -5.]])
c:  tensor([[ 0.,  0., -5.]])
Tc: tensor([[-0., -0., 5.]])
R:  tensor([[[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]])
```

Above, `Tc` is the translation to convert from world-to-view coordinates whereas `Tw` is the position of the camera in world coordinates (i.e. relative to the origin) and should be the same as `c`. In other words:

* the camera is located at (0, 0, -5) in world space
* a point located at (0, 0, 0) in world space would have to be translated by (0, 0, 5) to convert it into camera/view space

At least that is my understanding. I agree it seems counterintuitive when coming from 3D design software where we are used to specifying camera position/rotation in world coordinates. However, it can be useful to define the exact transformations applied to points being converted into the camera space.

**Comment by 3a1b2c3** [comment]
Thanks, hard to translate from OpenGL but lets try

def look_at_view_transform(
    dist: _BatchFloatType = 1.0,
    elev: _BatchFloatType = 0.0,
    azim: _BatchFloatType = 0.0,
    degrees: bool = True,
    eye: Optional[Union[Sequence, torch.Tensor]] = None,
    at=((0, 0, 0),),  # (1, 3)
    up=((0, 1, 0),),  # (1, 3)
    device: Device = "cpu",
) -> Tuple[torch.Tensor, torch.Tensor]:

**Comment by 3a1b2c3** [comment]
![image](https://user-images.githubusercontent.com/74843139/210932131-ec305bfe-b6d1-45a6-aa0b-c1f400a443f1.png)
getting closer with eye, up and look at
