### ISSUE TITLE
Cannot install pytorch3d in Google Colab: ImportError: libcudart.so.10.1

### ISSUE THREAD

**Issue by Lighfe** [facebookresearch/pytorch3d#1416]
Tried several ways to install pytorch, but I cannot access the pytorch3d.loss after the installation.

I'm reinstalling torch and torchvision with
```
!pip uninstall torch torchvision -y
!pip install torch==1.13.0 torchvision==0.14.0
```

And then install pytorch3d with 
`!pip install pytorch3d`

importing pytorch3d.structures gives no error, but pytorch3d.loss gives the following error:

> ImportError                               Traceback (most recent call last)
> 
> [<ipython-input-10-0ecb66024252>](https://localhost:8080/#) in <module>
> ----> 1 import pytorch3d.loss
> 
> 3 frames
> 
> [/usr/local/lib/python3.8/dist-packages/pytorch3d/ops/graph_conv.py](https://localhost:8080/#) in <module>
>       6 
>       7 # pyre-fixme[21]: Could not find name `_C` in `pytorch3d`.
> ----> 8 from pytorch3d import _C
>       9 from torch.autograd import Function
>      10 from torch.autograd.function import once_differentiable
> 
> ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory

The PyTorch version should be the correct one.

> !pip install pytorch3d
> 
> Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
> Requirement already satisfied: pytorch3d in /usr/local/lib/python3.8/dist-packages (0.3.0)
> Requirement already satisfied: torchvision>=0.4 in /usr/local/lib/python3.8/dist-packages (from pytorch3d) (0.14.0)
> Requirement already satisfied: fvcore in /usr/local/lib/python3.8/dist-packages (from pytorch3d) (0.1.5.post20221221)
> Requirement already satisfied: torch==1.13.0 in /usr/local/lib/python3.8/dist-packages (from torchvision>=0.4->pytorch3d) (1.13.0)
> Requirement already satisfied: requests in /usr/local/lib/python3.8/dist-packages (from torchvision>=0.4->pytorch3d) (2.25.1)
> Requirement already satisfied: typing-extensions in /usr/local/lib/python3.8/dist-packages (from torchvision>=0.4->pytorch3d) (4.4.0)
> Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.8/dist-packages (from torchvision>=0.4->pytorch3d) (7.1.2)
> Requirement already satisfied: numpy in /usr/local/lib/python3.8/dist-packages (from torchvision>=0.4->pytorch3d) (1.21.6)
> Requirement already satisfied: nvidia-cudnn-cu11==8.5.0.96 in /usr/local/lib/python3.8/dist-packages (from torch==1.13.0->torchvision>=0.4->pytorch3d) (8.5.0.96)
> Requirement already satisfied: nvidia-cuda-runtime-cu11==11.7.99 in /usr/local/lib/python3.8/dist-packages (from torch==1.13.0->torchvision>=0.4->pytorch3d) (11.7.99)
> Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in /usr/local/lib/python3.8/dist-packages (from torch==1.13.0->torchvision>=0.4->pytorch3d) (11.7.99)
> Requirement already satisfied: nvidia-cublas-cu11==11.10.3.66 in /usr/local/lib/python3.8/dist-packages (from torch==1.13.0->torchvision>=0.4->pytorch3d) (11.10.3.66)
> Requirement already satisfied: setuptools in /usr/local/lib/python3.8/dist-packages (from nvidia-cublas-cu11==11.10.3.66->torch==1.13.0->torchvision>=0.4->pytorch3d) (57.4.0)
> Requirement already satisfied: wheel in /usr/local/lib/python3.8/dist-packages (from nvidia-cublas-cu11==11.10.3.66->torch==1.13.0->torchvision>=0.4->pytorch3d) (0.38.4)
> Requirement already satisfied: tabulate in /usr/local/lib/python3.8/dist-packages (from fvcore->pytorch3d) (0.8.10)
> Requirement already satisfied: yacs>=0.1.6 in /usr/local/lib/python3.8/dist-packages (from fvcore->pytorch3d) (0.1.8)
> Requirement already satisfied: tqdm in /usr/local/lib/python3.8/dist-packages (from fvcore->pytorch3d) (4.64.1)
> Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.8/dist-packages (from fvcore->pytorch3d) (6.0)
> Requirement already satisfied: iopath>=0.1.7 in /usr/local/lib/python3.8/dist-packages (from fvcore->pytorch3d) (0.1.10)
> Requirement already satisfied: termcolor>=1.1 in /usr/local/lib/python3.8/dist-packages (from fvcore->pytorch3d) (2.1.1)
> Requirement already satisfied: portalocker in /usr/local/lib/python3.8/dist-packages (from iopath>=0.1.7->fvcore->pytorch3d) (2.6.0)
> Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests->torchvision>=0.4->pytorch3d) (4.0.0)
> Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests->torchvision>=0.4->pytorch3d) (1.24.3)
> Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests->torchvision>=0.4->pytorch3d) (2022.12.7)
> Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests->torchvision>=0.4->pytorch3d) (2.10)

Executing the recommended way to install pytorch3d on google colab did not work for me either:
```
import sys
import torch
pyt_version_str=torch.__version__.split("+")[0].replace(".", "")
version_str="".join([
    f"py3{sys.version_info.minor}_cu",
    torch.version.cuda.replace(".",""),
    f"_pyt{pyt_version_str}"
])
!pip install --no-index --no-cache-dir pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/{version_str}/download.html
```

gives the error

> ERROR: Could not find a version that satisfies the requirement iopath (from pytorch3d) (from versions: none)
> ERROR: No matching distribution found for iopath

**Comment by bottler** [comment]
For the recommended way, the dependent libraries have to be there, so `!pip install fvcore iopath` needs to be run first. I'll update INSTALL.md to mention this. Having done that, you should be able to use the recommended installation method to get pytorch3d quickly and easily in to a brand new colab notebook at the moment.

The tutorials do exactly this - you can copy the installation cell from them if you want.

**Comment by bottler** [comment]
INSTALL.md updated in acc60db.
