### ISSUE TITLE
Influence of number of lights on GPU memory?

### ISSUE THREAD

**Issue by fgolemo** [facebookresearch/pytorch3d#1428]
## ❓ Questions on how to use PyTorch3D

(IDK if I was supposed to keep that line above as past of the issue)

Heyhey folks,

So I have this issue where when I render my scene with one point light, but as soon as I add a second light, I run out of memory.
I've made sure that the light parameters (`diffuse_color` and `location`) are indeed [N, 3] lists and when converted to a tensor, they are of shape `torch.Size([3, 3])` if there's 3 light sources.

So I was wondering, is that normal and how does the number of point lights affect memory consumption in general?

Thanks,
Flo

**Comment by bottler** [comment]
PyTorch3D does not support more than one light per scene. `N` here is the batch size, the number of scenes, and needs to match the number of cameras and meshes etc.

**Comment by fgolemo** [comment]
Ah. Sad to hear but that answers my question.
