### ISSUE TITLE
How to obtain the position of point clouds in depth map after projecting

### ISSUE THREAD

**Issue by Zhimin-C** [facebookresearch/pytorch3d#1437]
## ❓ Questions on how to use PyTorch3D
Hi,

I utilize the PointsRasterizer to project point cloud (xyz format) to the depth map. However, I find there are much more valued pixel in depth map than the original point cloud size (1024)        
print(len(torch.where(renderer(point_cloud).idx!=-1)[0])) result is 1144842.

I also tried pix_to_face, but it shows that AttributeError: 'PointFragments' object has no attribute 'pix_to_face'.

How do I obtain the exactly position of original 1024 point cloud in the rendering depth map.

Here is my code

        point_cloud = Pointclouds(points=points.to(torch.float))

        R, T = look_at_view_transform(dist=batch_tensor(dist.T, dim=1, squeeze=True), elev=batch_tensor(
            elev.T, dim=1, squeeze=True), azim=batch_tensor(azim.T, dim=1, squeeze=True))

        cameras = OpenGLOrthographicCameras(device=points.device, R=R, T=T, znear=0.01)

        raster_settings = PointsRasterizationSettings(
            image_size=self.image_size,
            radius=self.points_radius,
            points_per_pixel=self.points_per_pixel,
            bin_size=0
        )
        renderer = PointsRasterizer(cameras=cameras, raster_settings=raster_settings)
        point_cloud = point_cloud.extend(views)
        point_cloud.scale_(batch_tensor(1.0/dist.T, dim=1,
                                        squeeze=True)[..., None][..., None].to(points.device))

**Comment by bottler** [comment]
Pixels are rectangular and points are circles with a given radius, so there's no way to ensure that each point lands in exactly one pixel. Even if there was, you'd still need to deal with clashes.

If you want to match each point with a location (rather than pixel) in the image, you should be able to get that by transforming the points through the camera, without using a renderer.

**Comment by Zhimin-C** [comment]
Thanks!
