### ISSUE TITLE
Create Mesh object with meshes different number of vertices

### ISSUE THREAD

**Issue by YuxuanSnow** [facebookresearch/pytorch3d#1438]
Hi,

i wonder if it is possible to create one mesh object from two meshes, which have different number of vertices and faces `[V1, F1]` and `[V2, F2]. Can we create the [B, V, F] by repeating the vertices and faces information or can we manually set some unusable V and F to fill and align the dimension?

Thanks!

**Comment by bottler** [comment]
The `Meshes` object is designed for exactly this: a heterogenous batch of meshes. Initialize it with lists
e.g. `Meshes(verts=[v1, v2], faces=[f1,f2])` where v1, v2, f1, f2 have shapes `(V1, 3), (V2, 3), (F1, 3) and (F2, 3)` respectively. No need to do the fill yourself.

**Comment by YuxuanSnow** [comment]
Thanks@bottler, this is exactly what i am looking for.
