### ISSUE TITLE
Plotly visualize colored mesh from texture png image 

### ISSUE THREAD

**Issue by 8bitnand** [facebookresearch/pytorch3d#1443]
I want to plot the mesh with colors from texture png image, with plotly_vis, But all i get in a default color for the mesh 

filename = '../sample/texture_mesh_for_inference/0000001.obj'
verts, faces, aux = load_obj(filename)
tex = TexturesUV(verts_uvs=verts_uvs, faces_uvs=faces_uvs, maps=texture_image)
mesh = Meshes(verts=[verts], faces=[faces.verts_idx], textures=tex)

verts_uvs = aux.verts_uvs[None, ...]  # (1, V, 2)
faces_uvs = faces.textures_idx[None, ...]  # (1, F, 3)
tex_maps = aux.texture_images
texture_image = list(tex_maps.values())[0]
texture_image = texture_image[None, ...]

output on plotly 
![image](https://user-images.githubusercontent.com/119727179/218040619-7feba849-cfcc-42f8-b99e-791050500594.png)
texture map
![image](https://user-images.githubusercontent.com/119727179/218040726-e92be46b-f71f-4a6e-810b-9084bfd2e7d8.png)
2d rendering has color 
![image](https://user-images.githubusercontent.com/119727179/218040832-3928efb7-645b-4bcc-8cc9-c25369edfee0.png)

**Comment by bottler** [comment]
I believe plotly doesn't support this. It would be great if we had an easy interactive visualisation for meshes with uv textures.
