### ISSUE TITLE
Volume rendering of depth

### ISSUE THREAD

**Issue by hwjiang1510** [facebookresearch/pytorch3d#1446]
## Motivation

The current volume renders, for example, the one used in this [tutorial](https://pytorch3d.org/tutorials/fit_textured_volume), only support rendering the color and density maps. How about enabling the rendering of depth, which will be a fundamental function and enable a lot of applications, e.g. evaluating or training on data with depth maps? The modification should be quite easy by replacing accumulating colors into accumulating depth.

**Comment by bottler** [comment]
The rendering of density produces depth. It can be made to only produce depth.

**Comment by yaojin17** [comment]
@bottler  Hello! I encountered a similar issue. Could you please provide further explanation? Does the solution involve defining each voxel's depth value as the feature of volume, instead of using colors? Thank you for your time and help!
