### ISSUE TITLE
What's the coords of the light?

### ISSUE THREAD

**Issue by weepiess** [facebookresearch/pytorch3d#1448]
Hi, I want to ask what's the coordinate of the light and how to set the light according to the mesh. (e.g always in front of the mesh).

Thank you in advance.

**Comment by bottler** [comment]
The user sets the coordinates of the lights (if PointLights) manually when constructing it. Only the user knows what is considered the "front" of the mesh.

**Comment by weepiess** [comment]
> The user sets the coordinates of the lights (if PointLights) manually when constructing it. Only the user knows what is considered the "front" of the mesh.

Thank you for your reply. The coordinates of PointLights set by the user are in the world coordinate or the camera coordinate? I found that I use the lights at the same position, and apply the object with the different R\T matrix, I couldn't always light up the side facing the camera.

**Comment by bottler** [comment]
The light location is in world coordinates.
