### ISSUE TITLE
undefined symbol: _ZNK2at6Tensor7is_cudaEv

### ISSUE THREAD

**Issue by dennisushi** [facebookresearch/pytorch3d#1451]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## 🐛 Bugs / Unexpected behaviors

Using pytorch3d throws `undefined symbol: _ZNK2at6Tensor7is_cudaEv`, likely due to mismatch with pytorch/CUDA. My CUDA is 11.7, with torch 11.3 on Python 3.8.10, local Linux machine. The installation instruction point to installing with `wheels/py38_cu113_pyt1110` however there is no wheel `wheels/py38_cu117_pyt1130`. None of the other methods to install appear to fix the issue either. 

NOTE: Please look at the existing list of Issues tagged with the label ['bug`](https://github.com/facebookresearch/pytorch3d/issues?q=label%3Abug). **Only open a new issue if this bug has not already been reported. If an issue already exists, please comment there instead.**.

## Instructions To Reproduce the Issue:

Please include the following (depending on what the issue is):

1. Any changes you made (`git diff`) or code you wrote: N/A
2. The exact command(s) you ran:
```
!pip3 uninstall pytorch3d chamfer_distance -y
!pip3 install --no-index --no-cache-dir pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py38_cu113_pyt1110/download.html
!pip3 install --no-index --no-cache-dir git+'https://github.com/otaheri/chamfer_distance'

import torch
from chamfer_distance import ChamferDistance as chamfer_dist
```

5. What you observed (including the full logs):
```

Cell In [1], line 2
      1 import torch
----> 2 from chamfer_distance import ChamferDistance as chamfer_dist
      3 import time
      5 p1 = torch.rand([10,25,3])

File ~/.local/lib/python3.8/site-packages/chamfer_distance/__init__.py:1
----> 1 from .chamfer_distance import ChamferDistance

File ~/.local/lib/python3.8/site-packages/chamfer_distance/chamfer_distance.py:7
      5 import torch
      6 import torch.nn.functional as F
----> 7 from pytorch3d.ops.knn import knn_gather, knn_points
      8 from pytorch3d.structures.pointclouds import Pointclouds
     11 def _validate_chamfer_reduction_inputs(
     12     batch_reduction: Union[str, None], point_reduction: str
     13 ):

File ~/.local/lib/python3.8/site-packages/pytorch3d/ops/__init__.py:5
      3 from .cameras_alignment import corresponding_cameras_alignment
      4 from .cubify import cubify
----> 5 from .graph_conv import GraphConv
      6 from .interp_face_attrs import interpolate_face_attributes
...
----> 8 from pytorch3d import _C
      9 from torch.autograd import Function
     10 from torch.autograd.function import once_differentiable

ImportError: /home/dennisushi/.local/lib/python3.8/site-packages/pytorch3d/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor7is_cudaEv
```

Please also simplify the steps as much as possible so they do not require additional resources to
   run, such as a private dataset.

**Comment by bottler** [comment]
PyTorch3D is not expected to work if the cuda version, pytorch's built cuda version, and pytorch3d's build cuda version do not match. If you can't find a PyTorch3D build for a combination of dependencies you can use, then you have to build pytorch3d from source.

**Comment by yosun** [comment]
is there a quick way to make sure all of them are the same version

**Comment by bottler** [comment]
We don't have a convenient way to see which dependencies a build was made with.
