### ISSUE TITLE
Questions about chamfer distance implementation

### ISSUE THREAD

**Issue by TLB-MISS** [facebookresearch/pytorch3d#1458]
Hello.

I am questioning the implementation of chamfer distance for normal.
In this [line](https://github.com/facebookresearch/pytorch3d/blob/da7fe2854eee7cdbba8b6c4b68065e857377591e/pytorch3d/loss/chamfer.py#L178), the `abs` function is taken for the cosine similarity when calculating the chamfer distance between sets of normal vectors.
This makes the distance between two normal vectors that are diametrically opposite zero.
Why this way is chosen? 

Thanks

**Comment by bottler** [comment]
I guess, because what might matter is the orientation of the "plane" given by the normals, not the particular orientation.

**Comment by TLB-MISS** [comment]
@bottler 

Thank you for your quick and clear answer!
