### ISSUE TITLE
question:pytorch3d-0.2.0/pytorch3d/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: cudaSetupArgument"

### ISSUE THREAD

**Issue by lixryjz** [facebookresearch/pytorch3d#1460]
When I use the pytorch3d in gpu，it suffer some problems，like "/pytorch3d-0.2.0/pytorch3d/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: cudaSetupArgument",but it shows that have installed successfully,and I can't use it,how to solve it
I installed it are the follow:
![image](https://user-images.githubusercontent.com/95114989/220628273-f3bef285-80e7-45c1-b5a2-1fef8f26b34a.png)

This is my environment：

Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    conda-forge
attrs                     19.3.0                     py_0    conda-forge
backcall                  0.2.0                      py_0    defaults
blas                      1.0                         mkl    conda-forge
bleach                    3.1.5                      py_0    defaults
ca-certificates           2020.7.22                     0    defaults
certifi                   2020.6.20                py38_0    defaults
cudatoolkit               10.2.89              hfd86e86_1    defaults
cycler                    0.10.0                   py38_0    defaults
dbus                      1.13.16              hb2f20db_0    defaults
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
entrypoints               0.3                      py38_0    defaults
expat                     2.2.9                he6710b0_2    defaults
fontconfig                2.13.0               h9420a91_0    defaults
freetype                  2.10.2               h5ab3b9f_0    defaults
future                    0.18.2                   pypi_0    pypi
fvcore                    0.1.1.post20200704            py_0    conda-forge
glib                      2.65.0               h3eb4bd4_0    defaults
gst-plugins-base          1.14.0               hbbd80ab_1    defaults
gstreamer                 1.14.0               hb31296c_0    defaults
h5py                      2.10.0           py38hd6299e0_1    defaults
hdf5                      1.10.6               hb1b8bf9_0    defaults
icu                       58.2                 he6710b0_3    defaults
importlib-metadata        1.7.0                    py38_0    defaults
importlib_metadata        1.7.0                         0    conda-forge
intel-openmp              2020.1                      217    defaults
iopath                    0.1.10                   pypi_0    pypi
ipykernel                 5.3.0            py38h5ca1d4c_0    defaults
ipython                   7.16.1           py38h5ca1d4c_0    defaults
ipython_genutils          0.2.0                    py38_0    defaults
ipywidgets                7.5.1                      py_0    conda-forge
jedi                      0.17.1                   py38_0    defaults
jinja2                    2.11.2                     py_0    defaults
joblib                    0.16.0                     py_0    conda-forge
jpeg                      9b                   h024ee3a_2    defaults
jsonschema                3.2.0                    py38_0    conda-forge
jupyter                   1.0.0                    py38_7    defaults
jupyter_client            6.1.3                      py_0    conda-forge
jupyter_console           6.1.0                      py_0    defaults
jupyter_core              4.6.3                    py38_0    conda-forge
kiwisolver                1.2.0            py38hfd86e86_0    defaults
ld_impl_linux-64          2.33.1               h53a641e_7    conda-forge
libedit                   3.1.20191231         h7b6447c_0    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
libpng                    1.6.37               hbc83047_0    defaults
libsodium                 1.0.18               h7b6447c_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
libtiff                   4.1.0                h2733197_1    defaults
libuuid                   1.0.3                h1bed415_2    defaults
libxcb                    1.14                 h7b6447c_0    defaults
libxml2                   2.9.10               he19cac6_1    defaults
lz4-c                     1.9.2                he6710b0_0    defaults
markupsafe                1.1.1            py38h7b6447c_0    defaults
matplotlib                3.3.1                         0    conda-forge
matplotlib-base           3.3.1            py38h817c723_0    defaults
mistune                   0.8.4           py38h7b6447c_1000    defaults
mkl                       2020.1                      217    defaults
mkl-service               2.3.0            py38he904b0f_0    defaults
mkl_fft                   1.1.0            py38h23d657b_0    defaults
mkl_random                1.1.1            py38h0573a6f_0    defaults
nbconvert                 5.6.1                    py38_0    conda-forge
nbformat                  5.0.7                      py_0    conda-forge
ncurses                   6.2                  he6710b0_1    defaults
ninja                     1.9.0            py38hfd86e86_0    defaults
notebook                  6.0.3                    py38_0    conda-forge
numpy                     1.18.5           py38ha1c710e_0    defaults
numpy-base                1.18.5           py38hde5b4d6_0    defaults
olefile                   0.46                       py_0    conda-forge
openssl                   1.1.1g               h7b6447c_0    defaults
packaging                 20.4                       py_0    defaults
pandoc                    2.9.2.1                       0    conda-forge
pandocfilters             1.4.2                    py38_1    defaults
parso                     0.7.0                      py_0    defaults
pcre                      8.44                 he6710b0_0    defaults
pexpect                   4.8.0                    py38_0    conda-forge
pickleshare               0.7.5                 py38_1000    conda-forge
pillow                    7.1.2            py38hb39fc2d_0    defaults
pip                       20.1.1                   py38_1    defaults
portalocker               1.5.2                    py38_0    conda-forge
prometheus_client         0.8.0                      py_0    defaults
prompt-toolkit            3.0.5                      py_0    defaults
prompt_toolkit            3.0.5                         0    conda-forge
ptyprocess                0.6.0                    py38_0    defaults
pygments                  2.6.1                      py_0    conda-forge
pyparsing                 2.4.7                      py_0    defaults
pyqt                      5.9.2            py38h05f1152_4    defaults
pyrsistent                0.16.0           py38h7b6447c_0    defaults
python                    3.8.3                hcff3b4d_2    defaults
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytorch                   1.5.1           py3.8_cuda10.2.89_cudnn7.6.5_0    pytorch
pytorch3d                 0.2.0                     dev_0    <develop>
pyyaml                    5.3.1            py38h7b6447c_1    defaults
pyzmq                     19.0.1           py38he6710b0_1    defaults
qt                        5.9.7                h5867ecd_1    defaults
qtconsole                 4.7.5                      py_0    defaults
qtpy                      1.9.0                      py_0    conda-forge
readline                  8.0                  h7b6447c_0    defaults
scipy                     1.5.2            py38h0b6359f_0    defaults
send2trash                1.5.0                    py38_0    defaults
setuptools                47.3.1                   py38_0    defaults
sip                       4.19.13          py38he6710b0_0    defaults
six                       1.15.0                     py_0    defaults
sqlite                    3.32.3               h62c20be_0    defaults
tabulate                  0.8.3                    py38_0    defaults
termcolor                 1.1.0                    py38_1    defaults
terminado                 0.8.3                    py38_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tk                        8.6.10               hbc83047_0    defaults
torchvision               0.6.1                py38_cu102    pytorch
tornado                   6.0.4            py38h7b6447c_1    defaults
tqdm                      4.47.0                     py_0    defaults
traitlets                 4.3.3                    py38_0    conda-forge
trimesh                   3.7.7                    pypi_0    pypi
typing-extensions         4.5.0                    pypi_0    pypi
wcwidth                   0.2.5                      py_0    defaults
webencodings              0.5.1                    py38_1    defaults
wheel                     0.34.2                   py38_0    conda-forge
widgetsnbextension        3.5.1                    py38_0    conda-forge
xz                        5.2.5                h7b6447c_0    defaults
yacs                      0.1.6                      py_0    conda-forge
yaml                      0.2.5                h7b6447c_0    defaults
zeromq                    4.3.2                he6710b0_2    defaults
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11               h7b6447c_3    defaults
zstd                      1.4.4                h0b5b093_3    defaults

**Comment by bottler** [comment]
You are using old versions of cuda, pytorch3d and pytorch. cudaSetupArgument is an old API too I think. I don't remember if this combination of versions is meant to work together. Building should be easier with up-to-date versions. 

If you need to stick with old versions, you'll need to dig around. What is using cudaSetupArgument? Perhaps you could attach the full error log?

**Comment by lixryjz** [comment]
I use the chamfer_distance function of pytorch3d to get the similarity of the two point clouds. These versions are based on the environment required by the replicated paper. I haven't tried to upgrade the versions of pythoch3d and pythoch3d. I checked that the import and use of pythoch3d were successful, but when the use function is not available on cuda, my linux server cuda version is 10.2, and pythochcan also work on cuda. Can you give me some suggestions about the combination and replacement of pythoch3d and pythoch3d versions, Is this information enough? If not, I will put the logto get 
Reproduce the paper:
https:// github.com/mikacuy/joint_learning_retrieval_deformation

**Comment by lixryjz** [comment]
> You are using old versions of cuda, pytorch3d and pytorch. cudaSetupArgument is an old API too I think. I don't remember if this combination of versions is meant to work together. Building should be easier with up-to-date versions.
> 
> If you need to stick wi


> You are using old versions of cuda, pytorch3d and pytorch. cudaSetupArgument is an old API too I think. I don't remember if this combination of versions is meant to work together. Building should be easier with up-to-date versions.
> 
> If you need to stick with old versions, you'll need to dig around. What is using cudaSetupArgument? Perhaps you could attach the full error log?

I use the chamfer_distance function of pytorch3d to get the similarity of the two point clouds. These versions are based on the environment required by the replicated paper. I haven't tried to upgrade the versions of pythoch3d and pythoch3d. I checked that the import and use of pythoch3d were successful, but when the use function is not available on cuda, my linux server cuda version is 10.2, and pythochcan also work on cuda. Can you give me some suggestions about the combination and replacement of pythoch3d and pythoch3d versions, Is this information enough? If not, I will put the logto get
Reproduce the paper:
https:// github.com/mikacuy/joint_learning_retrieval_deformation

**Comment by lixryjz** [comment]
![image](https://user-images.githubusercontent.com/95114989/220799258-c5d05f85-9ad4-49e1-9ed0-8c19143aa28e.png)
now is the log information

**Comment by lixryjz** [comment]
I test charmer_distantion on gpu and cpu，I found a bad resolution which both can't work！
![image](https://user-images.githubusercontent.com/95114989/220801443-a1d7d80f-bf90-4c25-97b9-4808c027bdf2.png)
but, I test pytorch3d by command line,don't use the function,which is succeddful,so  what can I to do for it?
![image](https://user-images.githubusercontent.com/95114989/220801985-fda4b681-1ecf-481e-9397-fb6b63dfa2ee.png)

**Comment by lixryjz** [comment]
This is my test code
![image](https://user-images.githubusercontent.com/95114989/220802073-ce97f48e-c369-4ddc-9ab0-e13e2a272a11.png)

**Comment by bottler** [comment]
The build of pytorch3d is incompatible with your installation of pytorch. If you can't use the python workaround I suggested, then please start again from a new empty environment, keeping a record of the commands you run, their output, and the pytorch3d build log. If it still doesn't work, attach them here and we may be able to help.

**Comment by lixryjz** [comment]
> 

I have solved the problem follow the offical operations ,thanks very much for you help!!
