### ISSUE TITLE
Training with point clouds of varying size, how to group them into batches.

### ISSUE THREAD

**Issue by brbr1** [facebookresearch/pytorch3d#1462]
Hello,
I want to have a batch (to work with it to train my model) of point clouds that have not the same size. it will be appreciated if you could give me a code example of this.

Thanks in advance :) .

**Comment by bottler** [comment]
Batches of point clouds with different numbers of points in each is a normal use of the PointClouds object. 

Simple example: If cloud 1 has 17 points, given by locations `p1` (shape `(17, 3)`) and features `f1`  (shape `(17, 3)`) and cloud 2 has 19 points, given by locations `p2` (shape `(19, 3)`) and features `f2`  (shape `(19, 3)`), where all tensors are float32 and are on the same device, you can create a batched Pointclouds of both of them with `Pointclouds(points=[p1, p2], features=[f1, f2])`.

**Comment by adosar** [comment]
@bottler How one is supposed to use the resulting batch? Can a `Pointclouds` obect be used with `torch` layers like `Linear`?
