### ISSUE TITLE
How to get a 2D normal map but not uv map

### ISSUE THREAD

**Issue by zhangyahu1** [facebookresearch/pytorch3d#1469]
Questions on how to get a 2D normal map but not uv map.

Recently, I the code and mesh ([render.zip](https://github.com/facebookresearch/pytorch3d/files/10885860/render.zip)) from @wasahaiah in #1063 to get the normal map. 

The normal map is obtained by:
> pixel_normals = interpolate_face_attributes(fragments.pix_to_face, fragments.bary_coords, faces_normals)
pixel_normals = pixel_normals.reshape(1,512,512,3)

But the result is as below:
![uv](https://user-images.githubusercontent.com/44366284/222823208-f80a6157-e567-4ac1-afb9-b765ae38d5cc.png)

May I know how to the 2D normal map aligned well with the rendered image (as below). Thanks.
<img width="238" alt="rendered image" src="https://user-images.githubusercontent.com/44366284/222823316-a8709f4f-4091-47c5-9894-0643cfcf3f38.png">

**Comment by bottler** [comment]
I don't understand. One thing: the normal map (from the code) is a 3D thing. By "2D normal map", do you mean just some component / angle of the normal rather than the whole normal? Also, what do you mean by "aligned"? The two models here are different, right?

**Comment by zhangyahu1** [comment]
Thanks for your reply! I have fixed it.

**Comment by yejr0229** [comment]
Hi, I wonder have you solve this? I use this code to render normal map:
![image](https://github.com/user-attachments/assets/8f99d9fb-5496-4243-88fd-05a7bfb9351b)

And I get:
![image](https://github.com/user-attachments/assets/0779d7df-2e94-40a2-a6f8-4ea64e0e83f5)

How to render a normal map like this (blue is front, red is left, green is top)?
![image](https://github.com/user-attachments/assets/bd9d0d61-7109-4370-9815-503a80def24e)
