### ISSUE TITLE
The angles of rendered RGB image and silhouette of the same mesh are different

### ISSUE THREAD

**Issue by delaprada** [facebookresearch/pytorch3d#1472]
## 🐛 Bugs / Unexpected behaviors
Hi! 

I'm trying to use pytorch3d to render a 3D hand mesh into an RGB image and a silhouette image, but the hand mesh in the RGB image and the silhouette image are different with the same mesh and camera setting:

Image on the left is the rendered silhouette and image on the right is the rendered RGB:

![image](https://user-images.githubusercontent.com/40078051/223721023-f90abb4f-dfd3-4f23-b894-0805ad651f85.png)

Here is my code:

```
R, T = look_at_view_transform(dist=1.5, elev=0, azim=0)
R = R.to(vertices.device)
T = T.to(vertices.device)

cameras = FoVPerspectiveCameras(device=vertices.device)

raster_settings = RasterizationSettings(
    image_size = self.image_size,
    blur_radius = 0.0, 
    faces_per_pixel = 1, 
)

rasterizer = MeshRasterizer(
    cameras=cameras, 
    raster_settings=raster_settings
)

new_textures = textures.view(textures.shape[0],textures.shape[1], 1, 1, 3)

hand_mesh = Meshes(
    verts=vertices,
    faces=faces,
    textures=TexturesAtlas(atlas=torch.tanh(new_textures)))

shader = SoftPhongShader(device = vertices.device, cameras = cameras)

renderer = MeshRenderer(rasterizer, shader)

sigma = 1e-4
raster_settings_silhouette = RasterizationSettings(
    image_size=self.image_size,
    blur_radius=np.log(1. / 1e-4 - 1.)*sigma, 
    faces_per_pixel=50, 
)

sil_shader = SoftSilhouetteShader()

sil_renderer = MeshRenderer(rasterizer=MeshRasterizer(
    cameras=cameras, 
    raster_settings=raster_settings_silhouette
), shader = sil_shader)

rgb_img = renderer(hand_mesh, R = R, T = T)
sil_img = sil_renderer(hand_mesh, R = R, T = T)
sil_img = sil_img[..., 3]
```

I render the RGB `rgb_img` and silhouette `sil_img` with plt.imshow. 

Could you please help me find out the problem?

Thank you very much!

**Comment by bottler** [comment]
> My guess is that the transform is applied twice. Each time you render, the transform is applied to the mesh. Perhaps try to copy or deepcopy the mesh before rendering. Do the first render on the original and the 2nd render on the copy.

@RKhatib95 rendering doesn't modify the mesh object.

**Comment by delaprada** [comment]
> > My guess is that the transform is applied twice. Each time you render, the transform is applied to the mesh. Perhaps try to copy or deepcopy the mesh before rendering. Do the first render on the original and the 2nd render on the copy.
> 
> @RKhatib95 rendering doesn't modify the mesh object.

Yes, I try to initialize two different mesh to render but still remain this problem.

And I found that it is because I use the wrong permute order to transform RGBA to RGB to calculate the loss, so it causes the up-side down problem.

Thank you very much for your help!
