### ISSUE TITLE
[installation] legacy-install-failure on windows

### ISSUE THREAD

**Issue by jerryliu20d** [facebookresearch/pytorch3d#1477]
On win10, I got error _"[WinError 2] The system cannot find the file specified"_ when installing the pytorch3d. The installed package and dependencies are listed below:
**pytorch**                   1.13.0          py3.9_cuda11.7_cudnn8_0    pytorch
**torchvision**               0.14.0                   pypi_0    pypi
**fvcore**                    0.1.5.post20221221    pyhd8ed1ab_0    conda-forge
**iopath**                    0.1.9                      py39    iopath
**C/C++ for MSVC**: 19.16.27049
**cuda:** 11.7
The detailed log is here. https://drive.google.com/file/d/1QsDqL1nzaRFy0FZnu6CKMMQFd5CdDFmt/view?usp=share_link
Thanks!

**Comment by bottler** [comment]
What happens if you run `G:\anaconda3\envs\test5\python.exe`? I wonder if something has happened to file locations or permissions.

**Comment by jerryliu20d** [comment]
> 

It runs interactive python 3.9. From the log, I have no idea which file is missing.

**Comment by jerryliu20d** [comment]
> What happens if you run `G:\anaconda3\envs\test5\python.exe`? I wonder if something has happened to file locations or permissions.


It runs interactive python 3.9. From the log, I have no idea which file is missing.

**Comment by bottler** [comment]
I don't have any other idea.
