### ISSUE TITLE
Rendered Image with Black dots

### ISSUE THREAD

**Issue by zhangyahu1** [facebookresearch/pytorch3d#1482]
Hi, I am trying to render one .obj file to images. However, the rendered images have black dots. 
I tried to add 'max_faces_per_bin=20000', but it still didn't work. Could you please give me any hint to solve it? 
This is the code and obj file [[code-obj.zip](https://github.com/facebookresearch/pytorch3d/files/10997367/code-obj.zip)].
<img width="395" alt="01" src="https://user-images.githubusercontent.com/44366284/225800838-2a6c9650-a871-436d-9fa4-7874a7992827.png">
<img width="400" alt="02" src="https://user-images.githubusercontent.com/44366284/225800844-973a2acc-44bb-47c4-8dde-aa136841c184.png">

**Comment by zhangyahu1** [comment]
This is the main code:
```
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
image_size = 512 #512
distance = 396
focal_length = ((1497, 1497),)
principal_point = ((256, 256),)

light_pos = -10
lights = PointLights(device=device, location=[[0.0, 0.0, light_pos]])

obj_filename = '01.obj'
verts_inp, faces, aux = load_obj(obj_filename, device=device, load_textures=False)

##### Meshes Rotation #####e
vertices_mean = verts_inp.mean(0)
verts_inp = verts_inp-vertices_mean

verts_min = min(verts_inp[:, 2] - max(verts_inp[:, 2]))
verts_inp[:, 2] = verts_inp[:, 2] - max(verts_inp[:, 2]) - (distance + verts_min)

# Convert to PyTorch3D world system
# (+X left, +Y up, +Z in)
R_to_py3d = torch.tensor(
    [[-1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, -1.0]],
    dtype=torch.float32,
    device=device,
)
verts = torch.mm(verts_inp, R_to_py3d)

# add white color vertex texture
tex = TexturesVertex(
    torch.ones((1, verts.shape[0], 3), device=device, dtype=torch.float32)
)
mesh = Meshes(verts=[verts], faces=[faces.verts_idx], textures=tex)

cameras = PerspectiveCameras(focal_length=focal_length, device=device, in_ndc=False, image_size=((image_size,image_size),), principal_point=principal_point)

raster_settings = RasterizationSettings(
    image_size=image_size, blur_radius=0, faces_per_pixel=1, max_faces_per_bin=20000)

shader=HardGouraudShader(device=device, cameras=cameras, lights=lights)
rasterizer = MeshRendererWithFragments(rasterizer = MeshRasterizer(cameras=cameras, raster_settings=raster_settings), shader=shader)
images, fragments = rasterizer(mesh)


##### image #####
filename_img = "img.png"
rgb = images[0, ..., :3].detach().squeeze().cpu().numpy()
Image.fromarray((rgb * 255).astype(np.uint8)).save(filename_img)
```

**Comment by zhangyahu1** [comment]
Thanks for your reply. I tried many sets of ambient/diffuse/specular components, but the rendered images still have the same black dots, and the diffence of rendered images for different components is the color as shown below: 
<img width="400" alt="1" src="https://user-images.githubusercontent.com/44366284/225934273-a96285dd-93c8-40b8-b6a0-7d9428ca77d0.png">
<img width="350" alt="2" src="https://user-images.githubusercontent.com/44366284/225934295-de8ec9a6-c5b3-4acc-9383-92679f339cdc.png">

**Comment by bottler** [comment]
The dots are red-on-yellow, so they are a green channel phenomenon, so they affect the diffuse component. Is there a weirdness in the calculation of normals at vertices (see use at https://github.com/facebookresearch/pytorch3d/blob/main/pytorch3d/renderer/mesh/shading.py#L152) caused by the way vertices are shared or not between faces? Can you try other shaders?

**Comment by zhangyahu1** [comment]
In addition to HardGouraudShader, I just used these shaders: HardFlatShader, SplatterPhongShader, HardPhongShader, SoftPhongShader]. All of them, except for SoftPhongShader, generated the same image with black dots, even the positions of black dots are the same. For SoftPhongShader, a pure white image was generated.

Besides, these are rendered normal map and height map:
![normal](https://user-images.githubusercontent.com/44366284/225955980-d4a12b35-250b-4b66-9088-931257f40f60.png)
![height](https://user-images.githubusercontent.com/44366284/225956004-1dc2d7dc-be6b-4582-b2f8-8d986e7a44f7.png)

**Comment by bottler** [comment]
So yes, the dots are coming from the normals. And I pointed to how you might investigate why. Perhaps look at the way vertices are shared or not between faces?

**Comment by bottler** [comment]
What exactly is the problem you want to solve? Do you really require diffuse lighting? If so, then what exactly do you want the normals to be? This is sort of a modelling question, not a library question.

**Comment by zhangyahu1** [comment]
I want to render the image and normal map from the provided .obj file (from ShapeNet). The aim is to obtain rendered normal maps and images.

**Comment by zhangyahu1** [comment]
Thanks. I will process the data. BTW, may I know if I can change the format of normal map between opengl and directx?

**Comment by zhangyahu1** [comment]
Thanks for your suggestion. I will try to modify the data.
