### ISSUE TITLE
Support PyTorch 2.0

### ISSUE THREAD

**Issue by amitabe** [facebookresearch/pytorch3d#1483]
## 🚀 Feature

Add support for PyTorch 2.0.

## Motivation and Pitch
The latest pytorch supported version is 1.13. Since PyTorch 2.0 was released in the last week, it'd be great if pytorch3d will support PyTorch 2.0.

**Comment by bottler** [comment]
The nightly builds are currently available for pytorch 2.0.

**Comment by jinfagang** [comment]
Does it on master? I just tried build failed.

**Comment by amitabe** [comment]
Seems v0.7.3 supports pytorch 2.0. Closing this issue.

**Comment by jinfagang** [comment]
@amitabe Please test CUDA11.8 on windows....
