### ISSUE TITLE
possible bug in look_at_view_transform() function

### ISSUE THREAD

**Issue by amit-ruf** [facebookresearch/pytorch3d#1485]
## 🐛 Bugs / Unexpected behaviors
Rotation matrix provided by [look_at_view_transform](https://pytorch3d.readthedocs.io/en/latest/_modules/pytorch3d/renderer/cameras.html#look_at_view_transform) results in non-invertible matrix for certain parameters (det(R)==0)

## Instructions To Reproduce the Issue:
```
import torch
from pytorch3d.renderer.cameras import look_at_view_transform
R,_=look_at_view_transform(eye=torch.tensor([[16.0, -142.0, 64.0]]), at=torch.tensor([[16.0, -141.0, 64.0]]))
assert R.det()!=torch.tensor([0.0]), 'det(R) == 0'
```

platform.platform()
'Windows-10-10.0.19044-SP0'

torch.version
'1.13.1'

pytorch3d.version
'0.7.2'

**Comment by bottler** [comment]
The `up` vector defaults to (0, 1, 0). It doesn't make sense to supply an `up` vector which is parallel to the line between `eye` and `at`. This example has `up` equal to `at-eye`.

**Comment by amit-ruf** [comment]
I agree, however, I would expect R matrix to be unitary (even if its just a random rotation). Failure to do so results in get_camera_center
