### ISSUE TITLE
Windows10 CUDA11.8 build failed

### ISSUE THREAD

**Issue by jinfagang** [facebookresearch/pytorch3d#1487]
![image](https://user-images.githubusercontent.com/21303438/227101229-1d4871d4-3dc1-42e1-b859-61dc74af4898.png)

**Comment by bottler** [comment]
Can you copy the full output? Text is best. And there may be a log file. And please say something about your environment.

**Comment by bottler** [comment]
Please copy the whole output / error message / log file / whatever you have.

**Comment by jinfagang** [comment]
sorry, I said I am unable to get error messages every time. Leave this as an issue if you don't want take any look at the code got error I pasted above.

**Comment by bottler** [comment]
Sorry - I just realised your error is similar to https://github.com/facebookresearch/pytorch3d/issues/1227 . Can you try the solution that worked there, i.e. copying a newer cub into the cuda directory?

Or, if you don't need pulsar, you could comment out the relevant call(s) to cub, which maybe requires seeing more of the output.

**Comment by jinfagang** [comment]
@bottler 
I replaced it but still error.

I am using CUDA11.8 and tried cub 1.17 cub 1.17.1 cub 1.17.2

all fails!!

**Comment by bottler** [comment]
Did the line number change in the error? Was it referring to a location which was changed by you? Can you check if the location in the error makes sense in all the versions? I don't think I can help further, but you might be able to follow this up.

**Comment by cmy-hhxx** [comment]
@bottler  hi, bottler, I've met this error.
I  am using CUDA11.8 and tried cub 1.17 cub and 2.1.0 cub, copying a newer cub into the cuda directory,
but get error: namespace "thrust::cub" has no member "DebugSyncStream", can you offer some suggestions?
![image](https://github.com/facebookresearch/pytorch3d/assets/71922563/7f9a6b08-9106-4d31-8fb5-a1cb9bf52e3d)

**Comment by cmy-hhxx** [comment]
@lucasjinreal  have you fixed your problem?

**Comment by lucasjinreal** [comment]
No, op owner claims it our error, not the lib itself. I think this lib is perfect, should not have any errors
