### ISSUE TITLE
rasterizer fragment -> pix_to_face all -1 

### ISSUE THREAD

**Issue by taeyunwoo** [facebookresearch/pytorch3d#1490]
Hello,

I followed [#126 ](https://github.com/facebookresearch/pytorch3d/issues/126) to generate a visibility map in my project.
However, to me, every fragments.pix_to_face returns -1 at every positions.

I have looked around other issues about this problem [#1138 ] [#602 ] [#1063 ], but I cannot solve this problem.

Also, when I visualize the fragment.zbuf, my mesh's silhouette seems good.

I placed my mesh on NDC coordinate, and below picture is the mesh.
![image](https://user-images.githubusercontent.com/59469419/227773736-56a9135d-937a-4357-840d-cf5240102c27.png)

And, here is the zbuf plot image.
![image](https://user-images.githubusercontent.com/59469419/227773755-cc859de5-dd82-44a8-ad21-da8c8504b8da.png)

my camera setting is followed this code:

```
R = np.array([[-1, 0, 0], [0, -1, 0], [0, 0, 1]]) # x and y are -1 for aligning with the input image
T = np.array([0, 0., 0.])
R = torch.from_numpy(R).float().unsqueeze(0) # for 1 camera to 1 mesh
T = torch.from_numpy(T).float().unsqueeze(0) # for 1 camera to 1 mesh
cameras = PerspectiveCameras(R=R, T=T)

raster_settings = RasterizationSettings(
    image_size=256,
    blur_radius=0.0,
    faces_per_pixel=1,
)
rasterizer = MeshRasterizer(
    cameras=cameras,
    raster_settings=raster_settings
)
```

Can you comment on this issue?
Thank you for reading.

**Comment by bottler** [comment]
Are you saying `fragments.pix_to_face.max()` is `-1`? Can you check? And what is `fragment.zbuf.std()`? It seems unlikely there are actual depth values but nothing useful in pix_to_face.

**Comment by taeyunwoo** [comment]
Thank you for replying.
Yes it is, all of `fragments.pix_to_face` are -1.
Actually, the reason why the depth image looks strange is the value of background is -1, while the part of the hand (black) is bigger than 0.

**Comment by bottler** [comment]
This is very strange. Can you include all the rest of the code where you use the rasterizer? Does the mesh have a very large number of faces?

If you are using GPU, can you try doing the whole calculation on the CPU instead? It will be slow but it might be interesting.

**Comment by taeyunwoo** [comment]
Dear bottler, 
Sorry about the confusion. I re-implement this code, and there is a mistake in the searching `fragments.pix_to_face` max value.

My device is CPU, but the code works well in this environment.
Again, sorry for bothering you about this problem.

Have a nice day.

**Comment by alicedingyueming** [comment]
> Dear bottler, Sorry about the confusion. I re-implement this code, and there is a mistake in the searching `fragments.pix_to_face` max value.
> 
> My device is CPU, but the code works well in this environment. Again, sorry for bothering you about this problem.
> 
> Have a nice day.

I am sorry to bother you. I meet the same problem. I rasterize my own mesh and the fragments.pix_to_face are all -1. May I ask you how to solve this problem?

**Comment by bottler** [comment]
@alicedingyueming Perhaps the camera and the mesh are not oriented the way you are expecting, so the camera isn't looking at anything. You can use plot_batch_individually from plotly_vis to visualize the mesh and the camera and see their relative locations and orientations and maybe diagnose. If you need further help please open a new issue.
