### ISSUE TITLE
Memory Leak in ChamferDistance

### ISSUE THREAD

**Issue by Ilyabasharov** [facebookresearch/pytorch3d#1492]
## 🐛 Bugs / Unexpected behaviors
Im using ChamferDistance several times in train iteration and my GPU memory just increasing. Also im using torch.cuda.empty_cache(); gc.collect() but it did not helped me.

**Comment by bottler** [comment]
This is odd. Can you share the relevant code? Ideally, could you create a minimal example which shows the behaviour? 

Is it that within each training step you do a forwards, creating a graph which includes chamfer, and then backwards through it, which should collapse the autograd graph? And you do many of these steps and usage keeps increasing over a large number of steps?

**Comment by Ilyabasharov** [comment]
@bottler sorry much, the problem was on my side. Thanks for very operative reply! I will close this conversation.
