### ISSUE TITLE
How to draw the normal UV map based on self defined uv coordinates?

### ISSUE THREAD

**Issue by wrk226** [facebookresearch/pytorch3d#1497]
Given an .obj file that contains vertex coordinates (v), uv coordinates (vt), and face indices (f), I want to recreate the corresponding normal uv map. 

Using PyTorch3D, I can easily calculate the normal values for each face and vertex, but when I try to map them to an image based on the uv coordinates(vt), I only get a series of dots:
<img src="https://user-images.githubusercontent.com/7517810/229681023-9cc13609-32fe-460f-a8a8-0f4ea051f810.png" width="300" height="300">

However, what I want to get looks like this:
<img src="https://user-images.githubusercontent.com/7517810/229681099-19162f83-4b67-4989-a1ca-0915870d8ee9.png" width="300" height="300">

I believe that I need to first calculate the barycentric coordinates for each pixel in the uv map and then interpolate the normal values, but I haven't found a suitable method to calculate the barycentric coordinates in uv map. Any guidance on how to tackle this issue would be greatly appreciated.

For reference, I have included both my code and data in this link: [https://drive.google.com/file/d/19k1YNM3ZBuDav2TZHL-Ih8N521eM_PFx/view?usp=sharing](https://drive.google.com/file/d/19k1YNM3ZBuDav2TZHL-Ih8N521eM_PFx/view?usp=sharing)

**Comment by bottler** [comment]
(I would be slightly interested to know if/how you solved this. It looks like some clever indexing is required.)
