### ISSUE TITLE
Is it possible to use BRDF data for rendering based on Pytorch3D

### ISSUE THREAD

**Issue by zhangyahu1** [facebookresearch/pytorch3d#1499]
E.g., Merl dataset provides brdf data. Is there a way to use brdf data for rendering based on Pytorch3D for photometric stereo?

**Comment by bottler** [comment]
You might be able to make some use of this data in a custom shader, but our renderer doesn't have brdf built in.

**Comment by ForrestPi** [comment]
@bottler Hi, is there any plan to add BRDF rendering?

**Comment by bottler** [comment]
No.
