### ISSUE TITLE
Is there support for composing/combining volumes for sampling?

### ISSUE THREAD

**Issue by alexanderswerdlow** [facebookresearch/pytorch3d#1502]
Compositional NeRFs (e.g., object-specific representations) are a common way to represent a scene. Is it possible to specify a volume and perform sampling where a single element in a batch can contain multiple volumes, likely offset in world space relative to each other?

More generally, this doesn't need to be restricted to Volumes, but composing any `volumetric_function`.

**Comment by bottler** [comment]
There isn't a (yet) a ready made structure for this in PyTorch3D.
