### ISSUE TITLE
How can we compute signed distance between points and a mesh with PyTorch3D

### ISSUE THREAD

**Issue by BotScutters** [facebookresearch/pytorch3d#1504]
Is there an efficient way to calculate the signed distance between a mesh and points in a pointcloud?

I see how I can calculate the squared distances using `point_mesh_distance`, or the squared distance along with the indexes by calling `_C.point_face_dist_forward`, as described in #193, but I'm not finding a good method for efficiently getting the signed distance from points to a mesh, similar to the [trimesh.proximity.signed_distance](https://trimsh.org/trimesh.proximity.html#trimesh.proximity.signed_distance) function.

The best option I'm seeing is to calculate the squared distances, then also check whether each point is inside or outside of the mesh using one of the methods described in #343, since it seems like a method to check if points are inside the mesh isn't implemented yet, and finally get the distances as the sqrt of the squared distances with signs applied based on in/out.

**Comment by bottler** [comment]
You're right PyTorch3D doesn't have a concept of watertight meshes or "insideness", so there's no built in way.

**Comment by BotScutters** [comment]
Got it, thank you for the response!
