### ISSUE TITLE
How to understand the rendering of PyTorch3d？

### ISSUE THREAD

**Issue by Fastcnn** [facebookresearch/pytorch3d#1508]
## ❓ Questions on how to use PyTorch3D

How to understand the working process of pytorch3d's differentiable renderer, such as the understanding of z-buffers, alpha-compositing, splats to 2D circle etc.? Are there some intuitive pictures or videos to introduce this process?

**Comment by bottler** [comment]
Perhaps https://www.youtube.com/watch?v=MOBAJb5nJRI is useful, e.g. parts 3, 4 and 7?

**Comment by Fastcnn** [comment]
Thanks !
