### ISSUE TITLE
Installation on Windows 10 RTX 4090 with CUDA11.8 fail 

### ISSUE THREAD

**Issue by Daksitha** [facebookresearch/pytorch3d#1509]
I have a PC with RTX 4090 and is supported by CUDA 11.8 and higher. 

My nvidia-smi output: 
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 531.41                 Driver Version: 531.41       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                      TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090       WDDM | 00000000:01:00.0  On |                  Off |
|  0%   39C    P8               23W / 450W|    538MiB / 24564MiB |     26%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+ 

I tried with both Visual Studio 2019 and 2022. I was not able to build or install using pip. Steps I took: 
1. install VS with SDK and C++ build tools. 
2. Pytorch3D installation
```
conda create -n pytorch3d python=3.8
conda activate pytorch3d
conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
conda install -c fvcore -c iopath -c conda-forge fvcore iopath
````

Then used pip install "git+https://github.com/facebookresearch/pytorch3d.git" to install and also used the local installation and commented out std14++ in the setup.py file. Both failed. 

I tried both Native tools for VS2015 and VS2019. Additionally I set DISTUTILS_USE_SDK=1 and PYTORCH3D_NO_NINJA=1. 

I am left with the below error: 

´´´
ENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 --use-local-env
      C:/Users/Administrator/anaconda3/envs/pytorch3d/lib/site-packages/torch/include\c10/macros/Macros.h(138): warning C4067: unexpected tokens following preprocessor directive - expected a newline
      C:/Users/Administrator/anaconda3/envs/pytorch3d/lib/site-packages/torch/include\c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
                detected during:
                  instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
      (61): here
                  instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
      C:/Users/Administrator/anaconda3/envs/pytorch3d/lib/site-packages/torch/include\c10/core/TensorImpl.h(77): here

      C:/Users/Administrator/anaconda3/envs/pytorch3d/lib/site-packages/torch/include\c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
                detected during:
                  instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=true, <unnamed>=0]"
      (61): here
                  instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=true, <unnamed>=0]"
      C:/Users/Administrator/anaconda3/envs/pytorch3d/lib/site-packages/torch/include\ATen/core/qualified_name.h(73): here

      C:\Users\Administrator\anaconda3\envs\pytorch3d\include\cub\block\specializations/block_reduce_raking.cuh(77): error: class "cub::WarpReduce<cub::KeyValuePair<int64_t, float>, 1, 0>" has no member "InternalWarpReduce"
                detected during:
                  instantiation of class "cub::BlockReduceRaking<T, BLOCK_DIM_X, BLOCK_DIM_Y, BLOCK_DIM_Z, LEGACY_PTX_ARCH> [with T=cub::KeyValuePair<int64_t, float>, BLOCK_DIM_X=1, BLOCK_DIM_Y=1, BLOCK_DIM_Z=1, LEGACY_PTX_ARCH=0]"
      C:\Users\Administrator\anaconda3\envs\pytorch3d\include\cub\block\specializations/block_reduce_raking_commutative_only.cuh(100): here
                  instantiation of union "cub::BlockReduceRakingCommutativeOnly<T, BLOCK_DIM_X, BLOCK_DIM_Y, BLOCK_DIM_Z, LEGACY_PTX_ARCH>::_TempStorage [with T=cub::KeyValuePair<int64_t, float>, BLOCK_DIM_X=1, BLOCK_DIM_Y=1, BLOCK_DIM_Z=1, LEGACY_PTX_ARCH=0]"
      C:\Users\Administrator\anaconda3\envs\pytorch3d\include\cub\util_type.cuh(342): here
                  instantiation of class "cub::AlignBytes<T>::Pad [with T=cub::BlockReduceRakingCommutativeOnly<cub::KeyValuePair<int64_t, float>, 1, 1, 1, 0>::_TempStorage]"
      C:\Users\Administrator\anaconda3\envs\pytorch3d\include\cub\util_type.cuh(349): here
                  instantiation of class "cub::AlignBytes<T> [with T=cub::BlockReduceRakingCommutativeOnly<cub::KeyValuePair<int64_t, float>, 1, 1, 1, 0>::_TempStorage]"
      C:\Users\Administrator\anaconda3\envs\pytorch3d\include\cub\util_type.cuh(402): here
                  instantiation of class "cub::UnitWord<T> [with T=cub::BlockReduceRakingCommutativeOnly<cub::KeyValuePair<int64_t, float>, 1, 1, 1, 0>::_TempStorage]"
      C:\Users\Administrator\anaconda3\envs\pytorch3d\include\cub\util_type.cuh(671): here
                  [ 3 instantiation contexts not shown ]
                  instantiation of class "cub::AlignBytes<T> [with T=cub::BlockReduceRakingCommutativeOnly<cub::KeyValuePair<int64_t, float>, 1, 1, 1, 0>::TempStorage]"
      C:\Users\Administrator\anaconda3\envs\pytorch3d\include\cub\util_type.cuh(402): here
                  instantiation of class "cub::UnitWord<T> [with T=cub::BlockReduceRakingCommutativeOnly<cub::KeyValuePair<int64_t, float>, 1, 1, 1, 0>::TempStorage]"
      C:\Users\Administrator\anaconda3\envs\pytorch3d\include\cub\util_type.cuh(671): here
                  instantiation of class "cub::Uninitialized<T> [with T=cub::BlockReduceRakingCommutativeOnly<cub::KeyValuePair<int64_t, float>, 1, 1, 1, 0>::TempStorage]"
      C:\Users\Administrator\anaconda3\envs\pytorch3d\include\cub\block/block_reduce.cuh(279): here
                  instantiation of class "cub::BlockReduce<T, BLOCK_DIM_X, ALGORITHM, BLOCK_DIM_Y, BLOCK_DIM_Z, LEGACY_PTX_ARCH>::TempStorage [with T=cub::KeyValuePair<int64_t, float>, BLOCK_DIM_X=1, ALGORITHM=cub::BLOCK_REDUCE_RAKING_COMMUTATIVE_ONLY, BLOCK_DIM_Y=1, BLOCK_DIM_Z=1, LEGACY_PTX_ARCH=0]"
      C:\Users\Administrator\AppData\Local\Temp\pip-req-build-52vinhd5\pytorch3d\csrc\sample_farthest_points\sample_farthest_points.cu(34): here
                  instantiation of "void FarthestPointSamplingKernel<block_size>(at::PackedTensorAccessor64<float, 3ULL, at::RestrictPtrTraits>, at::PackedTensorAccessor64<int64_t, 1ULL, at::RestrictPtrTraits>, at::PackedTensorAccessor64<int64_t, 1ULL, at::RestrictPtrTraits>, at::PackedTensorAccessor64<int64_t, 2ULL, at::RestrictPtrTraits>, at::PackedTensorAccessor64<float, 2ULL, at::RestrictPtrTraits>, at::PackedTensorAccessor64<int64_t, 1ULL, at::RestrictPtrTraits>) [with block_size=1U]"
      C:\Users\Administrator\AppData\Local\Temp\pip-req-build-52vinhd5\pytorch3d\csrc\sample_farthest_points\sample_farthest_points.cu(219): here

      C:\Users\Administrator\anaconda3\envs\pytorch3d\include\cub\block\specializations/block_reduce_raking.cuh(103): error: argument list for class template "cub::WarpReduce" is missing
                detected during:
                  instantiation of union "cub::BlockReduceRaking<T, BLOCK_DIM_X, BLOCK_DIM_Y, BLOCK_DIM_Z, LEGACY_PTX_ARCH>::_TempStorage [with T=cub::KeyValuePair<int64_t, float>, BLOCK_DIM_X=1, BLOCK_DIM_Y=1, BLOCK_DIM_Z=1, LEGACY_PTX_ARCH=0]"
      C:\Users\Administrator\anaconda3\envs\pytorch3d\include\cub\util_type.cuh(342): here
                  instantiation of class "cub::AlignBytes<T>::Pad [with T=cub::BlockReduceRaking<cub::KeyValuePair<int64_t, float>, 1, 1, 1, 0>::_TempStorage]"
      C:\Users\Administrator\anaconda3\envs\pytorch3d\include\cub\util_type.cuh(349): here
                  instantiation of class "cub::AlignBytes<T> [with T=cub::BlockReduceRaking<cub::KeyValuePair<int64_t, float>, 1, 1, 1, 0>::_TempStorage]"
      C:\Users\Administrator\anaconda3\envs\pytorch3d\include\cub\util_type.cuh(402): here
                  instantiation of class "cub::UnitWord<T> [with T=cub::BlockReduceRaking<cub::KeyValuePair<int64_t, float>, 1, 1, 1, 0>::_TempStorage]"
      C:\Users\Administrator\anaconda3\envs\pytorch3d\include\cub\util_type.cuh(671): here
                  instantiation of class "cub::Uninitialized<T> [with T=cub::BlockReduceRaking<cub::KeyValuePair<int64_t, float>, 1, 1, 1, 0>::_TempStorage]"
      (109): here
                  [ 8 instantiation contexts not shown ]
                  instantiation of class "cub::AlignBytes<T> [with T=cub::BlockReduceRakingCommutativeOnly<cub::KeyValuePair<int64_t, float>, 1, 1, 1, 0>::TempStorage]"
      C:\Users\Administrator\anaconda3\envs\pytorch3d\include\cub\util_type.cuh(402): here
                  instantiation of class "cub::UnitWord<T> [with T=cub::BlockReduceRakingCommutativeOnly<cub::KeyValuePair<int64_t, float>, 1, 1, 1, 0>::TempStorage]"
      C:\Users\Administrator\anaconda3\envs\pytorch3d\include\cub\util_type.cuh(671): here
                  instantiation of class "cub::Uninitialized<T> [with T=cub::BlockReduceRakingCommutativeOnly<cub::KeyValuePair<int64_t, float>, 1, 1, 1, 0>::TempStorage]"
      C:\Users\Administrator\anaconda3\envs\pytorch3d\include\cub\block/block_reduce.cuh(279): here
                  instantiation of class "cub::BlockReduce<T, BLOCK_DIM_X, ALGORITHM, BLOCK_DIM_Y, BLOCK_DIM_Z, LEGACY_PTX_ARCH>::TempStorage [with T=cub::KeyValuePair<int64_t, float>, BLOCK_DIM_X=1, ALGORITHM=cub::BLOCK_REDUCE_RAKING_COMMUTATIVE_ONLY, BLOCK_DIM_Y=1, BLOCK_DIM_Z=1, LEGACY_PTX_ARCH=0]"
      C:\Users\Administrator\AppData\Local\Temp\pip-req-build-52vinhd5\pytorch3d\csrc\sample_farthest_points\sample_farthest_points.cu(34): here
                  instantiation of "void FarthestPointSamplingKernel<block_size>(at::PackedTensorAccessor64<float, 3ULL, at::RestrictPtrTraits>, at::PackedTensorAccessor64<int64_t, 1ULL, at::RestrictPtrTraits>, at::PackedTensorAccessor64<int64_t, 1ULL, at::RestrictPtrTraits>, at::PackedTensorAccessor64<int64_t, 2ULL, at::RestrictPtrTraits>, at::PackedTensorAccessor64<float, 2ULL, at::RestrictPtrTraits>, at::PackedTensorAccessor64<int64_t, 1ULL, at::RestrictPtrTraits>) [with block_size=1U]"
      C:\Users\Administrator\AppData\Local\Temp\pip-req-build-52vinhd5\pytorch3d\csrc\sample_farthest_points\sample_farthest_points.cu(219): here

      2 errors detected in the compilation of "C:/Users/Administrator/AppData/Local/Temp/pip-req-build-52vinhd5/pytorch3d/csrc/sample_farthest_points/sample_farthest_points.cu".
      sample_farthest_points.cu
      error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.8\\bin\\nvcc.exe' failed with exit code 1
      [end of output]

´´´

Could you help me with the issue? Thank you!

**Comment by rcknowles04** [comment]
`` 2 errors detected in the compilation of "C:/Users/rknowle4/AppData/Local/Temp/2/pip-req-build-9r6716uw/pytorch3d/csrc/sample_farthest_points/sample_farthest_points.cu".
      sample_farthest_points.cu
      error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.7\\bin\\nvcc.exe' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pytorch3d
  Running setup.py clean for pytorch3d
Failed to build pytorch3d

**Comment by rcknowles04** [comment]
` 2 errors detected in the compilation of "C:/Users/rknowle4/AppData/Local/Temp/2/pip-req-build-9r6716uw/pytorch3d/csrc/sample_farthest_points/sample_farthest_points.cu".
      sample_farthest_points.cu
      error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.7\\bin\\nvcc.exe' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pytorch3d
  Running setup.py clean for pytorch3d
Failed to build pytorch3d
`

**Comment by rcknowles04** [comment]
Here are the messages I am getting after what you posted

` 2 errors detected in the compilation of "C:/Users/rknowle4/AppData/Local/Temp/2/pip-req-build
9r6716uw/pytorch3d/csrc/sample_farthest_points/sample_farthest_points.cu".
      sample_farthest_points.cu
      error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.7\\bin\\nvcc.exe' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pytorch3d
  Running setup.py clean for pytorch3d
Failed to build pytorch3d
`

**Comment by Daksitha** [comment]
Hi @rcknowles04, yes, i remove this part to keep the error message short.

**Comment by Choons** [comment]
I'm having the same errors with compilation of sample_farthest_points.cu

the first error:

x86_64-linux/include/cub/block/specializations/block_reduce_raking.cuh(77): error: class "cub::WarpReduce<cub::KeyValuePair<int64_t, float>, 1, 0>" has no member "InternalWarpReduce"

the 2nd error:

x86_64-linux/include/cub/block/specializations/block_reduce_raking.cuh(103): error: argument list for class template "cub::WarpReduce" is missing

**Comment by Choons** [comment]
I finally got it to compile. In sample_farthest_points.cu at line 176, there's something about that "switch (threads)" block that the compiler chokes on. Maybe the formatting on that first case(1024) with the line break? I commented out the switch the block and just used the default value in a redundant little if else statement and it worked:

if (threads == 1024) {
  	FarthestPointSamplingKernel<1024><<<blocks, threads, shared_mem, stream>>>(points_a, lengths_a, K_a, idxs_a, min_point_dist_a, start_idxs_a);
  }
  else {
  	FarthestPointSamplingKernel<1024><<<blocks, threads, shared_mem, stream>>>(points_a, lengths_a, K_a, idxs_a, min_point_dist_a, start_idxs_a);
  }

* and keeping the statements all on one line instead of how it appears here

**Comment by bottler** [comment]
Here are several reports of windows build problems in Farthest Point Sampling, most having something to do with CUB. I don't know what the problem is, and I'm a bit confused that they have just come up, because I don't know what changed recently. I don't know how it could be related to the PyTorch 2.0.0 release. Could it be related to a recent visual studio update?

- Something to check: now CUDA includes a good nvidia CUB library since 11.7 I think, we need to not set CUB_HOME. So best not to download a CUB build and please check the CUB_HOME env var is not set. In particular @Choons report looks a bit like there might be multiple copies of CUB hanging around. 

- A good way to avoid the problem might be to replace the file pytorch3d/csrc/sample_farthest_points/sample_farthest_points.cu with its previous version which doesn't use CUB. You could download [this old version](https://raw.githubusercontent.com/facebookresearch/pytorch3d/f2cf9d4d0be34d3f7ecb4178c356cdfc34b7634c/pytorch3d/csrc/sample_farthest_points/sample_farthest_points.cu) and paste it over the file. This is just negating the effect of [this commit](https://github.com/facebookresearch/pytorch3d/commit/8ea4da293846e64bee5cc99c8cb008888479947f) and pytorch3d should still work fine after it.

- If you don't care about the farthest point sampling functionality you can avoid the problem by deleting stuff - e.g. remove the whole switch block in that file.

**Comment by bottler** [comment]
@Choons This issue is about windows compile problems, which are often only relevant to windows. I missed that your comment was a linux thing. If you are still having problems please open a new issue. That switch statement is in general correct I think.

**Comment by rcknowles04** [comment]
@bottler your suggestion to replace the "sample_farthest_points.cu" with the older version solved the initial error for me. I no longer got the errors I initially posted about and pytorch3d was able to build successfully. 

However, I am now getting an error trying to run:

'from pytorch3d.io import load_obj, save_obj'

The error is as follows:
`from pytorch3d.io import load_obj, save_obj
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2022.3.2\plugins\python\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm 2022.3.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "E:\Conda\envs\Conda_Pytorch3d\lib\site-packages\pytorch3d\io\__init__.py", line 8, in <module>
    from .obj_io import load_obj, load_objs_as_meshes, save_obj
  File "C:\Program Files\JetBrains\PyCharm 2022.3.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "E:\Conda\envs\Conda_Pytorch3d\lib\site-packages\pytorch3d\io\obj_io.py", line 17, in <module>
    from iopath.common.file_io import PathManager
  File "C:\Program Files\JetBrains\PyCharm 2022.3.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "E:\Conda\envs\Conda_Pytorch3d\lib\site-packages\iopath\__init__.py", line 3, in <module>
    from iopath.common import LazyPath, PathManager, file_lock, get_cache_dir
  File "C:\Program Files\JetBrains\PyCharm 2022.3.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "E:\Conda\envs\Conda_Pytorch3d\lib\site-packages\iopath\common\__init__.py", line 3, in <module>
    from iopath.common.file_io import LazyPath, PathManager, file_lock, get_cache_dir
  File "C:\Program Files\JetBrains\PyCharm 2022.3.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "E:\Conda\envs\Conda_Pytorch3d\lib\site-packages\iopath\common\file_io.py", line 27, in <module>
    import portalocker  # type: ignore
  File "C:\Program Files\JetBrains\PyCharm 2022.3.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "E:\Conda\envs\Conda_Pytorch3d\lib\site-packages\portalocker\__init__.py", line 4, in <module>
    from . import portalocker
  File "C:\Program Files\JetBrains\PyCharm 2022.3.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "E:\Conda\envs\Conda_Pytorch3d\lib\site-packages\portalocker\portalocker.py", line 8, in <module>
    import win32con
  File "C:\Program Files\JetBrains\PyCharm 2022.3.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'win32con'`

All the other modules I have tried to import have not given me any issues besides this one. So far. Do you know what the 'win32con' would be referring to?

**Comment by bottler** [comment]
@rcknowles04 I'm surprised by this, because the iopath library has had that import for ages and I don't remember anyone complaining. Can you perhaps do `pip install pywin32` and try again?

**Comment by rcknowles04** [comment]
@bottler that solved it, thank you for the help!

**Comment by lucasjinreal** [comment]
@rcknowles04  Are u windows CUDA118???? How did u solve it ?

**Comment by rcknowles04** [comment]
@lucasjinreal I believe I was using CUDA 11.7, not 11.8 when I was having these issues a few months ago.

**Comment by rcknowles04** [comment]
@lucasjinreal and yes to Windows

**Comment by lucasjinreal** [comment]
@rcknowles04 So, it doesn't **means CUDA11.8 windows solved**,

**Comment by Liaoliaoliaoyh** [comment]
> @lucasjinreal我相信几个月前我使用 CUDA 11.7 时遇到这些问题，而不是 11.8。

Hello, can you provide your Windows installation environment, such as win10 + CUDA 11.7 + py3.x + pytorch1.x + pytorch3d 0.x.  Thanks！

**Comment by Daksitha** [comment]
Hi, I could build from the source, and it is working perfectly. 
- Download the latest release: https://github.com/facebookresearch/pytorch3d/releases/tag/v0.7.3. 
- Open the terminal and set FORCE_CUDA=1
 ```
cd pytorch3d
python3 setup.py install

 ```

**Comment by lucasjinreal** [comment]
@Daksitha Are u using CUDA118?????

**Comment by Liaoliaoliaoyh** [comment]
> 

Thank you very much for your reply, I have installed it successfully

**Comment by Liaoliaoliaoyh** [comment]
> 



> @Daksitha Are u using CUDA118????? Windows???

I don't think CUDA11.8 is currently supported. Compared to CUDA11.7, CUDA11.8 may have some code refactoring, which will have problems when compiling PyTorch3d. So CUDA11.7 can be successful with RTX 4090.

**Comment by Liaoliaoliaoyh** [comment]
> > @lucasjinreal我相信几个月前我使用 CUDA 11.7 时遇到了这些问题，而不是 11.8。
> 
> 您好，能否提供您的Windows安装环境，如win10 + CUDA 11.7 + py3.x + pytorch1.x + pytorch3d 0.x。谢谢！

Maybe it can help others, my environment:
Win10 + RTX 4090 + CUDA 11.7 + Py3.9 + PyTorch1.12 + PyTorch3d 0.7.0 + CUB 1.17.2

**Comment by lucasjinreal** [comment]
@Liaoliaoliaoyh  SO stop saying your are OK with the code on WINDOWS.

You are misleading others. 

We are using CUDA11.8 rather than you can built cuda11.7 can built means cuda11.8 can built....

That's why this issue existed.

Your post make @bottler  think it's not an issue and keeping close my issue on CUDA11.8 and no one really fix this issue any longer. (on windows)

**Comment by lucasjinreal** [comment]
@Liaoliaoliaoyh  

![image](https://github.com/facebookresearch/pytorch3d/assets/21303438/a484cc26-4255-469b-8677-849c253315e6)

![image](https://github.com/facebookresearch/pytorch3d/assets/21303438/da3cf81c-1939-44f0-8d90-d62a7b0e76cc)


Do u lost your mind？？？？ Please look carefully on the title, and DO NOT POST ANY SO CALLED SUCCESFULL INFOMATION UNDER IT!!!!

**Comment by Daksitha** [comment]
> @Daksitha Are u using CUDA118????? Windows???

No I installed 12.1 nightly version

**Comment by zebraNUO** [comment]
I meet a question
win11 + CUDA 11.8 + py3.9 + pytorch2.0.1 + pytorch3d 0.7.7   cub1.17.0
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8/include\thrust/system/cuda/detail/core/agent_launcher.h(524): error:
namespace "thrust::cub" has no member "DebugSyncStream"

1 error detected in the compilation of "C:/Users/pytorch3d-main/pytorch3d/csrc/iou_box3d/iou_box3d.cu".
error: command 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvcc.exe' failed with exit code 2
I have tried cub 1.17.0 1.17.2 1.17.1 1.15.0 all failed，Can you help to solve this？
