### ISSUE TITLE
Seem rendering takes much gpu and  very slow

### ISSUE THREAD

**Issue by xingmimfl** [facebookresearch/pytorch3d#152]
it seems that rendering takes a lot of gpu： i have a nvidia with 12GB, but i have to set batch_size = 8, sinceing batch_size=16 would  cause  "out of gpu memory".  and I'm sure that base network is very small, smaller than resnet18 or mobielnet. 
is this  right ?? :P

**Comment by gkioxari** [comment]
@xingmimfl the information you provide does not contain much information and without any info we can't help you. The format of how issues should be reported can be found [here](https://github.com/facebookresearch/pytorch3d/blob/master/.github/ISSUE_TEMPLATE/questions-help.md). Could you give us a code snippet on how you define the renderer. The memory requirement of the renderer are described [here](https://github.com/facebookresearch/pytorch3d/blob/master/docs/notes/renderer.md) in detail.

**Comment by gkioxari** [comment]
No response, closing this task. @xingmimfl if you believe there is a bug in PyTorch3D then please provide reproducible code that we can run, what you expected to get and what you're getting and your machine's specs.
