### ISSUE TITLE
Where are stored wheels .whl cached files?

### ISSUE THREAD

**Issue by SlimeVRX** [facebookresearch/pytorch3d#1521]
Hi

In Colab, I just installed pytorch 3D. 

```
Created wheel for pytorch3d: filename=pytorch3d-0.7.3-cp39-cp39-linux_x86_64.whl
```

Where are stored wheels .whl cached files?

Thank you very much!

![image](https://user-images.githubusercontent.com/99313947/235285790-7753c4e2-dbf3-4595-85ba-ee0809c4d883.png)

**Comment by 511lyf** [comment]
> 你好
> 
> 在 Colab 中，我刚刚安装了 pytorch 3D。
> 
> ```
> Created wheel for pytorch3d: filename=pytorch3d-0.7.3-cp39-cp39-linux_x86_64.whl
> ```
> 
> 存储的轮子 .whl 缓存文件在哪里？
> 
> 谢谢！
> 
> ![image](https://user-images.githubusercontent.com/99313947/235285790-7753c4e2-dbf3-4595-85ba-ee0809c4d883.png)

Hello, I installed it using Pytorch3D-0.7.6 +pt2.1.0cu121-cp38-cp38-win_amd64.whl. I can import pytorch3d correctly, but I can't find the _C module. What is the problem? I am using windows11 operating system and need help urgently

**Comment by bottler** [comment]
@511lyf This issue isn't about that. Please don't sidetrack existing issues. We can discuss on #1792 or a new issue.

@SlimeVRX That's a question about colab, not PyTorch3D. We can't help here.
