### ISSUE TITLE
how to save obj with uv

### ISSUE THREAD

**Issue by cjlunmh** [facebookresearch/pytorch3d#1522]
I have a mesh with verts,faces,verts_uv without texture. if i want to save it, how can i do.
i try the "save_obj" function, but the output obj file without uv.
`    save_obj(f=path,verts=vertices,faces=faces.verts_idx,verts_uvs=uv[0],faces_uvs=faces.verts_idx)
`

**Comment by bottler** [comment]
Do you mean you don't have an actual texture image? Can you not supply a dummy one (e.g. all zeros)?

**Comment by cjlunmh** [comment]
Thank you for your reply. I have solved this problem by defining a function to save the obj. The obj file I saved now contains the vt and ft.
