### ISSUE TITLE
How do I render an image with N channels from a mesh with N dim vector field defined over it?

### ISSUE THREAD

**Issue by PavanMantripragada** [facebookresearch/pytorch3d#1525]
## ❓ Questions on how to use PyTorch3D
I have a N (>4) dimensional vector field defined over the surface of a mesh. For example, N dimensional vector defined for every vertex of the mesh. I want to render an image with N channels, where ith channel has pixel values as  values of ith dimension of the vector field defined on mesh when viewed from the given camera angle. This rendering clearly doesn't involve any lighting conditions. Can I perform such a render using pytorch3D?

Given a mesh and a camera pose, I want my render output to be a tensor of shape (Batches,Height,Width,N)

**Comment by bottler** [comment]
I think a custom shader would do this fine. Take a look at the current shader objects.

**Comment by PavanMantripragada** [comment]
Hi,
Thanks for your immediate response! 

To load .obj files into meshes the following method is being used
https://github.com/facebookresearch/pytorch3d/blob/ef5f620263562657a022dee419abd63534d123e7/pytorch3d/io/obj_io.py#L236

However, they only provide two types of texture definitions 1) TextureAtlas 2) TextureUV. There is no provision for TextureVertex
https://github.com/facebookresearch/pytorch3d/blob/ef5f620263562657a022dee419abd63534d123e7/pytorch3d/io/obj_io.py#L274-L286

I would have used TextureUV type but it doesn't have a provision to load more than 3 channels (RGB), one can conclude this from the following lines.
https://github.com/facebookresearch/pytorch3d/blob/ef5f620263562657a022dee419abd63534d123e7/pytorch3d/io/obj_io.py#L283-L286

I have an .obj file with no material and texture properties and a numpy array describing the mesh texture. The array is of shape (num_of_vertices, num_of_tex_channels). I intend to use these to create a tex object of type TextureVertex. Later, use tex to generate mesh object. Is there any way I can achieve this through the existing classes and methods?

**Comment by PavanMantripragada** [comment]
Thanks for your help!
