### ISSUE TITLE
renders mesh but get incomplete images

### ISSUE THREAD

**Issue by surheaven** [facebookresearch/pytorch3d#1530]
## ❓ Questions on how to use PyTorch3D

pytorch3d renders the complete mesh using the renderer and gets an incomplete image.
py3.8_cuda11.3_cudnn8.2.0_0
pytorch3d: 0.4.0 

code like this:
# maskrender
raster_settings_silhouette = RasterizationSettings(
		image_size=(dataset.H,dataset.W),
		blur_radius=0.,
		bin_size=int(2 ** max(np.ceil(np.log2(max(dataset.H,dataset.W))) - 4, 4)),
		faces_per_pixel=1,
		perspective_correct=True,
		clip_barycentric_coords=False,
		cull_backfaces=False
)
renderer = MeshRendererWithFragments(
		rasterizer=MeshRasterizer(
			cameras=cameras,
			raster_settings=raster_settings_silhouette
		),
		shader=SoftSilhouetteShader()
     )
self.maskRender=renderer 
focals,princeple_ps,Rs,Ts,H,W=self.dataset.get_camera_parameters(frame_ids.numel(),device)
cameras=RectifiedPerspectiveCameras(focals,princeple_ps,Rs,Ts,image_size=[(W, H)]).to(device)
new_raster_settings_silhouette = RasterizationSettings(
				image_size=(H, W),
				blur_radius=0.,
				bin_size=int(2 ** max(np.ceil(np.log2(max(H, W))) - 4, 4))+10,
				faces_per_pixel=1,
				perspective_correct=True,
				clip_barycentric_coords=False,
				cull_backfaces=False
			)
self.maskRender.rasterizer.cameras=cameras
self.maskRender.rasterizer.raster_settings = new_raster_settings_silhouette
imgs,frags=self.maskRender(defMeshes)	

There is a problem with the rendered image. The image rendered under the current camera has strange mutilated dots (left image), but the image rendered from a different viewpoint is also fine (right image)：
![image](https://user-images.githubusercontent.com/89247297/236399668-c3f9188b-d705-4915-aa86-562083b56098.png)
View mesh, mesh is complete：
![image](https://user-images.githubusercontent.com/89247297/236400042-ff8b32cc-01be-4a4a-ba3d-378de3376f44.png)
Modify the bin_size inside new_raster_settings_silhouette and found that it can solve the problem of the current image rendering error (the left picture is the original, the right picture is the rendering result after changing the bin_size).：
![image](https://user-images.githubusercontent.com/89247297/236400427-65b93b9d-ebbf-49b2-8063-b8a29d73ac64.png)
However, it still fails on other images, and there is still the problem of incomplete rendering.

**Comment by bottler** [comment]
If you set `bin_size=0` does everything work?

**Comment by surheaven** [comment]
Yes！Thanks a lot！
