### ISSUE TITLE
euler_angles_to_matrix and matrix_to_euler_angles is not consistant?

### ISSUE THREAD

**Issue by densechen** [facebookresearch/pytorch3d#155]
Hi, 
I use following code to convert a matrix to euler and back,
`
BEFORE = MATRIX
EULER = matrix_to_euler_angles(BEFORE, "XYZ")
AFTER = euler_angles_to_matrix(EULER, "XYZ" )
`

And got that:
`
AFTER tensor([[[ 0.8888,  0.0357, -0.4569],  
         [-0.4552,  0.1834, -0.8713],
         [ 0.0528,  0.9824,  0.1793]]], device='cuda:0',)
BEFORE tensor([[[ 0.8888,  0.1516, -0.4325],
         [-0.4552,  0.1834, -0.8713],
         [ 0.0528, -0.9713, -0.2321]]], device='cuda:0')`
The rotation matix has been changed after this opratiom. It is that I miss something, or the convertion method "XYZ" is wrong?

**Comment by bottler** [comment]
The original `MATRIX`, `BEFORE`, is not a rotation matrix. Its determinant is approximately -1. It therefore does not make sense to express it in euler angles.

**Comment by densechen** [comment]
Thanks! That is right!

**Comment by FavorMylikes** [comment]
Emmm，Could you help me to look at this?

```python
matrix_to_euler_angles(euler_angles_to_matrix(torch.Tensor([100,100,100])/180*np.pi, "XYZ"), "XYZ")/np.pi*180
```

the result is `tensor([-80.0000,  80.0000, -80.0000])`

There is some math formula inside the code, But when I try input those angles into `unity` to visualize it, they are not equivalent

**Comment by bottler** [comment]
The two sets of Euler angles (100°,100°,100°) and (-80°, 80°, -80°) represent the same rotation in the given convention.
