### ISSUE TITLE
Is it possible to render objects with shininess maps (map_Ns in .mtl/.obj format)?

### ISSUE THREAD

**Issue by David-Yan1** [facebookresearch/pytorch3d#1555]
I am importing textured meshes in the .obj/.mtl format with multiple diffuse color maps and shininess maps. Getting multiple textures onto different meshes was achievable by using the `TexturesAtlas` class, but it seems that there isn't a way of applying a shininess map to each mesh so that different parts of the mesh might have varying strengths of shininess. `pytorch3d.renderer.materials` allows for some control over shininess, but the renderer only accepts one material per batch element, so all meshes in the render would have the same shininess and the shininess would also be uniform across the mesh. Is there a way to render _multiple_ meshes with different shininess _maps_?

**Comment by bottler** [comment]
PyTorch3D doesn't support shininess maps at all, I'm afraid.
