### ISSUE TITLE
Surface to volume registration

### ISSUE THREAD

**Issue by lodeguns** [facebookresearch/pytorch3d#156]
## ❓ Surface to volume registration

Dear staff, is it possible to align a 3D surface with respect to a 3D volume (such as surface to volume registration), possibly looking for where the surface area is on the solid surface while minimizing its distance? 
Such for example, is it possible to align a brain surface fragment with an irregular shape to a whole-brain volume?

Thank you in advance for your reply

**Comment by gkioxari** [comment]
I think you can do it! So if I understand correctly you have 3D voxel (a grid of shape `HxWxD`) and you want to find how to displace a 3D surface (in the form of a mesh?). 

I see two options:
* You convert the 3D voxel to a mesh (e.g. use `cubify`) and then compute the distance between two meshes e.g. you can use `chamfer` after you `sample_points_from_meshes` to differentiably convert the meshes into points. Or you can use some of our point specific ops such as ICP found in [`points_alignment.py`](https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/ops/points_alignment.py)
* You can convert the 3D voxel to a pointcloud (e.g. `cubify` -> `sample_points_from_meshes`) and then you can compute `point_mesh_distance` between the pointcloud and the mesh. 

I hope that helps!

**Comment by lodeguns** [comment]
Thanks a lot for the answer, you caught the problem and it will be very useful for my research. In general, you are right, traditional techniques would use ICP or even better iterative point to surface alignments (which are faster), but I want to figure out if your tool could be useful for solving a more complex problem that could be the "tracking of the deformations" measuring the variations in the chamfer distance along the epochs and not only, such as in ICP, with a "static" fitting measure. Thank you for your help!!!

**Comment by gkioxari** [comment]
Sounds reasonable! I think learning the deformation of your surface such that it minimizes chamfer distance seems like a path forward. Note that this is what we do in Mesh R-CNN too! Good luck with your project!

**Comment by gkioxari** [comment]
I will close this issue for now! Feel free to re-open if you have follow up questions!
