### ISSUE TITLE
Cuda build errors in Windows 10 and 11 using VS 2022

### ISSUE THREAD

**Issue by alevonian** [facebookresearch/pytorch3d#1567]
Can anyone help me resolve these cuda errors?
The setup goes for for a long time then I eventually error out.
I am not using ninja in the setup.py
---------------------------------------------------------------------
C:/Program Files (x86)/Windows Kits/10//include/10.0.19041.0//um\combaseapi.h(356): warning #174-D: expression has no effect

C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.7/include\cub/device/dispatch/dispatch_segmented_sort.cuh(338): error: invalid combination of type specifiers

C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.7/include\cub/device/dispatch/dispatch_segmented_sort.cuh(338): error: expected an identifier

C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.7/include\cub/device/dispatch/dispatch_segmented_sort.cuh(379): error: expected a member name

3 errors detected in the compilation of "C:/Projects/pytorch3d/pytorch3d/csrc/pulsar/cuda/renderer.backward.gpu.cu".
error: command 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin\nvcc.exe' failed with exit code 2
PS C:\Projects\pytorch3d>

**Comment by artths** [comment]
Just had the same error when building with CUDA 11.8 under Windows 11.
Add the "-DWIN32_LEAN_AND_MEAN" to the nvcc_args in setup.py.
Base on this https://github.com/microsoft/onnxruntime/pull/11578

**Comment by bottler** [comment]
This is similar to https://github.com/facebookresearch/pytorch3d/issues/1227 which might help you fix.

**Comment by artths** [comment]
> This is similar to #1227 which might help you fix.

Not sure about CUDA 11.7, but it doesn't work for 11.8. 
It's not a CUB version issue either way. Following https://github.com/microsoft/onnxruntime/pull/11578 fix: "A Windows SDK header #defines small, which clashes with a typedef in the CUDA 11.6 (and possibly other versions) headers."

**Comment by TerryLiu007** [comment]
> > This is similar to #1227 which might help you fix.
> 
> Not sure about CUDA 11.7, but it doesn't work for 11.8. It's not a CUB version issue either way. Following [microsoft/onnxruntime#11578](https://github.com/microsoft/onnxruntime/pull/11578) fix: "A Windows SDK header #defines small, which clashes with a typedef in the CUDA 11.6 (and possibly other versions) headers."

Built on Windows10 with cuda 11.8 and torch 2.4.1. Adding  "-DWIN32_LEAN_AND_MEAN" flag to the nvcc_args in setup.py solves the problem.
