### ISSUE TITLE
Load ply with texture png example

### ISSUE THREAD

**Issue by limarta** [facebookresearch/pytorch3d#1569]
Hi,

I tried reading in a mesh from a ply file with the associated texture stored as a png file. Following some advice from #904 and the tutorial https://pytorch3d.org/tutorials/render_textured_meshes, I ran
`load_mesh(mesh.ply)` to pass in auxiliary data to `TexturesUV`, but it seems that the structure doesn't contain information about uv textures. The documentation doesn't seem to indicate a way to grab this data if the file is a `.ply`

I finally attempted converted the ply to an obj+mtl file, but still ran into the same no texture error which indicates that I am clearly doing something wrong. 

The ply file is actually the same as mentioned in #904. Here is the header:
```ply
format ascii 1.0
comment VCGLIB generated
comment TextureFile obj_000001.png
element vertex 9951
property float x
property float y
property float z
property float nx
property float ny
property float nz
property float texture_u
property float texture_v
element face 15728
property list uchar int vertex_indices
end_header
```

How would I go about accomplishing this? Thanks.

**Comment by limarta** [comment]
I came up with this though I wonder if there is anything native to pytorch3d.
```
device = torch.device("cuda:0")

import trimesh
import torch

# Read the PLY file using trimesh
mesh = trimesh.load_mesh("assets/bop/ycbv/models/obj_000001.ply")
vertices = torch.FloatTensor(mesh.vertices)
faces = torch.Tensor(mesh.faces)
faces = faces.type(torch.int32)
uv_coordinates = torch.FloatTensor(mesh.visual.uv)

vertices = vertices.to(device)
faces = faces.to(device)
uv_coordinates = uv_coordinates.to(device)

verts_uvs = uv_coordinates[None,...]
faces_uvs = faces[None,...]

texture = transforms.ToTensor()(Image.open("assets/bop/ycbv/models/obj_000001.png"))
texture = torch.unsqueeze(texture.to(device), 0)
texture = torch.permute(texture, (0, 2, 3, 1))

from pytorch3d.renderer import TexturesUV
tex = TexturesUV(maps=texture, faces_uvs=faces_uvs, verts_uvs=verts_uvs)
meshes = Meshes(verts=[vertices], faces=[faces], textures=tex)
```

**Comment by bottler** [comment]
Sorry, this feature hasn't been added to pytorch3d. I explained in that other issue how it might be done if someone wanted to send a PR.

**Comment by xuzhuang1996** [comment]
> 

I run your code, and get error: IndexError: tensors used as indices must be long, byte or bool tensors

Do you know what the reason is?

thanks!

**Comment by sunshineywz123** [comment]
> > 
> 
> I run your code, and get error: IndexError: tensors used as indices must be long, byte or bool tensors
> 
> Do you know what the reason is?
> 
> thanks!

I'm having the same problem, may I ask how you finally solved it?

**Comment by bottler** [comment]
```
faces = faces.type(torch.int32)
```
should be 
```
faces = faces.type(torch.int64)
```

And also the TextureFile functionality has now been implemented for PLY.
