### ISSUE TITLE
Error when installing pytorch3d

### ISSUE THREAD

**Issue by bubuton** [facebookresearch/pytorch3d#1576]
Hi, I was installing the pytorch3d following the installation guide (https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md). 
Below is the problem that I was get into when running  "pip install -e ." in step 2. Install from a local clone.
![image](https://github.com/facebookresearch/pytorch3d/assets/60136695/e9de644f-e557-485b-adc7-5acde269c076)

I was running on a conda environement as python version of 3.10 on windows. The cuda installed in the environment should be 11.6, however in the error message it is mentioning 11.1 which is the cuda I installed locally, not sure if that cause the problem. Also, I followed the instruction where to set CUB_HOME="the directory where the cmakelist is". The error message suggest that I do not need to use my own checkout of cub, should I just ignore it? The image below is the directory of the cmakelist
![image](https://github.com/facebookresearch/pytorch3d/assets/60136695/81ce23e6-c94b-4b90-b45f-f22293f28347)
![image](https://github.com/facebookresearch/pytorch3d/assets/60136695/eca11ce8-0759-4863-9043-ea14e59a6a22)

Thank you.

**Comment by bottler** [comment]
Have you set CUDA_HOME to point at the cuda installation (11.6) which you want it to use?

**Comment by bubuton** [comment]
Not yet I will have a try now, thank you

**Comment by bubuton** [comment]
There is a new error after I set the CUDA_HOME to the 11.6, which is error checking compiler version for cl
![image](https://github.com/facebookresearch/pytorch3d/assets/60136695/9fb1cd1c-58de-48e5-889f-aa6149f292b1)

**Comment by bubuton** [comment]
The error message after it is the same as https://github.com/facebookresearch/pytorch3d/issues/1329, which is The system cannot find the file specified

**Comment by bottler** [comment]
Ah ok. You need to have visual studio installed and you need to be in the right visual studio command prompt. Is that the case? As mentioned on the other issue, this is not a pytorch3d-specific problem.

**Comment by bubuton** [comment]
Here is the error log, I did have visual studio installed, so to solve the problem I should activate conda in visual studio command prompt?
https://docs.google.com/document/d/1F5pL-12eCYi01GgeIIsb9uITucIfAui9FzsFyoEx5Ts/edit?usp=sharing

**Comment by bubuton** [comment]
> Here is the error log, I did have visual studio installed, so to solve the problem I should activate conda in visual studio command prompt? https://docs.google.com/document/d/1F5pL-12eCYi01GgeIIsb9uITucIfAui9FzsFyoEx5Ts/edit?usp=sharing

I used the visual studio 2019 prompt to run it, there is no cl warning for now but the error log is still the same. Below is the error log.
https://docs.google.com/document/d/1KcHr0T0g6BNgYSvIkgltXVAjcS04yHsz249k5qvtmYM/edit?usp=sharing

On the other hand, I tried the install from github method using this line 
"pip install "git+https://github.com/facebookresearch/pytorch3d.git" 
This raise a new error of pyproject, is this related to this step "Installing prebuilt binaries for PyTorch3D" as I am running on windows, I just ignored the content in it.
![image](https://github.com/facebookresearch/pytorch3d/assets/60136695/c3a0ddca-7df6-4506-9d6b-d09bd5c2c435)

**Comment by bottler** [comment]
Sorry - I'm a bit confused. Yes you need to activate conda and your conda environment in the prompt.  The two google docs are not useful logs - they don't show what went wrong. There should be other logs or other output on the console.

**Comment by bubuton** [comment]
This is the error message in the console. It has this error of The system cannot find the file specified but not knowing what is missing exactly.
https://docs.google.com/document/d/1oRJnFlvIMul9_xWGeQT-jhORHat9tRYSfov8bs0X55M/edit?usp=sharing

**Comment by bottler** [comment]
Could you be missing some visual studio components like windows sdks? Also it's worth checking through the other issues which include "The system cannot find the file specified". We've had a few.
