### ISSUE TITLE
Weights calculating for Alpha Compositing 

### ISSUE THREAD

**Issue by huohuohuohuohuohuohuohuo** [facebookresearch/pytorch3d#1579]
In the pytorch3d.renderer.points.renderer (line 56), the weights are calculated with dists2. However, in the corresponding compositing.py (line 19-22), the notes indicate that the weights are related to z-buf, i,e, the distance between the pixel and points. I dont know if this is inconsistent. Looking forward to your reply.

**Comment by bottler** [comment]
This is deliberate. See section 3.2 of "SynSin: End-to-end View Synthesis from a Single Image" https://arxiv.org/pdf/1912.08804.pdf . The docstrings have recently been updated to make this clearer.
