### ISSUE TITLE
how can i get the Vertex coordinates in the render images?

### ISSUE THREAD

**Issue by Dian-Yi** [facebookresearch/pytorch3d#158]
i meet some case needing the vertex coordinates in different angle. i want the rende images same coordinates correspond to obj obj mode. so how can i get it?

**Comment by nikhilaravi** [comment]
Do you mean the world coordinates of the mesh vertices corresponding to the faces which are rendered?

**Comment by Dian-Yi** [comment]
> Do you mean the world coordinates of the mesh vertices corresponding to the faces which are rendered?

yes , for example： i draw a 3d triangle and it has 3  mesh vertices. when i get render images from this 3d mode, how can i konw the 3 vertices coordinates in 2d triangle images ?

**Comment by nikhilaravi** [comment]
@Dian-Yi, you can get the 2d projections of all the mesh vertices onto the image plane from the output of applying the camera projection matrix. 

```
verts_world = meshes_world.verts_padded()
verts_screen = cameras.transform_points(verts_world)
```

See [here](https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/renderer/mesh/rasterizer.py#L90-L93) in rasterizer.py for more context on where this is done in the rendering pipeline.

**Comment by nikhilaravi** [comment]
@Dian-Yi if this answers your question please close this issue.
