### ISSUE TITLE
VS Studio Build Tool Requirements

### ISSUE THREAD

**Issue by FlimFlamm** [facebookresearch/pytorch3d#1584]
## ❓ 

What are all the required build-tools (the add-ons) for VS studio, for installing pytorch3d from a local clone or directly from the repo?

I am encountering a similar problem as this issue https://github.com/facebookresearch/pytorch3d/issues/1122 which was recently closed; the OP mentioned that after installing VS 2022 and the "build tools" that his problem resolved.

I assume these are the culprits, but which?

![image](https://github.com/facebookresearch/pytorch3d/assets/24987395/99d1c89e-90e5-45bd-9b55-945d4aa9a799)

**Comment by bottler** [comment]
I don't know for sure, but I think unity should not be needed, and the rest of those should be enough. It's possible that the ".net desktop" one is needed, but I hope not.

**Comment by FlimFlamm** [comment]
I think I can confirm the above, although there are some individual components within the Desktop Development with C++ tool that may or may not be required (likely the standard install of it will be sufficient). Thanks for the clarification!
