### ISSUE TITLE
Compilation problems

### ISSUE THREAD

**Issue by domef** [facebookresearch/pytorch3d#1588]
## 🐛 Bugs / Unexpected behaviors

I have 2 different PCs and I have some issues when compiling pytorch3d from source on a PC and using it on the other PC. 

These are my 2 PCs:
- OS: Ubuntu 22.04.2 LTS
CPU: Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
GPU: NVIDIA GeForce RTX 2080 Ti
- OS: Ubuntu 20.04.4 LTS
CPU: Intel(R) Core(TM) i9-10920X CPU @ 3.50GHz
GPU: NVIDIA GeForce RTX 3090

This is the code I will run in the following examples:

```python
import torch
from pytorch3d.ops import sample_farthest_points
from pytorch3d.loss import chamfer_distance

xyz = torch.rand(1, 10, 3)
num_points = 5
sampled_points_cpu, indices_cpu = sample_farthest_points(
    xyz,
    K=num_points,
    random_start_point=True,
)
xyz_cuda = xyz.cuda()
sampled_points_cuda, indices_cuda = sample_farthest_points(
    xyz_cuda,
    K=num_points,
    random_start_point=True,
)
print("sample_farthest_points CPU")
print(indices_cpu)
print(sampled_points_cpu)
print("sample_farthest_points CUDA")
print(indices_cuda)
print(sampled_points_cuda)

tensor1 = torch.rand(1, 10, 3)
tensor2 = torch.rand(1, 10, 3)
loss_chamfer_cpu, _ = chamfer_distance(tensor1, tensor2)
tensor1_cuda = tensor1.cuda()
tensor2_cuda = tensor2.cuda()
loss_chamfer_cuda, _ = chamfer_distance(tensor1_cuda, tensor2_cuda)
print("chamfer_distance CPU")
print(loss_chamfer_cpu)
print("chamfer_distance CUDA")
print(loss_chamfer_cuda)
```

If I install pytorch3d from a pre-built release the program works correctly on both devices:

```
python3.9 -m venv .venv
source .venv/bin/activate
pip install -U pip setuptools
pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117
pip install fvcore iopath
pip install --no-index --no-cache-dir pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py39_cu117_pyt1131/download.html
```

If I manually compile on a PC the program works correctly on the PC where I compiled:

```
python3.9 -m venv .venv
source .venv/bin/activate
pip install -U pip setuptools
pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117
pip install fvcore iopath wheel
git clone https://github.com/facebookresearch/pytorch3d
cd pytorch3d
git checkout tags/v0.7.3
sudo apt install ninja-build
export CUDA_HOME=/usr/local/cuda-11.7
IS_WHEEL=1 python setup.py bdist_wheel
pip install dist/pytorch3d-0.7.3-cp39-cp39-linux_x86_64.whl
```

If I manually compile on a PC and run on the other PC I have some issues:

```
python3.9 -m venv .venv
source .venv/bin/activate
pip install -U pip setuptools
pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117
pip install fvcore iopath
pip install path/to/wheel
```

Compiling on PC1 and running on PC2 (an error is raised when importing pytorch3d):

```
Traceback (most recent call last):
  File "/tmp/pytorch3d_tests/program.py", line 2, in <module>
    from pytorch3d.ops import sample_farthest_points
  File "/tmp/pytorch3d_tests/.venv/lib/python3.9/site-packages/pytorch3d/ops/__init__.py", line 7, in <module>
    from .ball_query import ball_query
  File "/tmp/pytorch3d_tests/.venv/lib/python3.9/site-packages/pytorch3d/ops/ball_query.py", line 10, in <module>
    from pytorch3d import _C
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/pytorch3d_tests/.venv/lib/python3.9/site-packages/pytorch3d/_C.cpython-39-x86_64-linux-gnu.so)
```

Compiling on PC2 and running on PC1 (the results on CUDA are always 0):

```
sample_farthest_points CPU
tensor([[1, 9, 2, 8, 3]])
tensor([[[0.7359, 0.9982, 0.8795],
         [0.7044, 0.0650, 0.2164],
         [0.7323, 0.9491, 0.0417],
         [0.2319, 0.7995, 0.9024],
         [0.9693, 0.9966, 0.4895]]])
sample_farthest_points CUDA
tensor([[-1, -1, -1, -1, -1]], device='cuda:0')
tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]], device='cuda:0')
chamfer_distance CPU
tensor(0.2762)
chamfer_distance CUDA
tensor(0., device='cuda:0')
```
The only related issue I found is https://github.com/facebookresearch/pytorch3d/issues/1439.

As I mentioned, the pre-built release works fine, so the question is: is there a way to compile pytorch3d so that it works on different PCs?

**Comment by bottler** [comment]
The sample_farthest_points failing looks like a problem to do with nvidia CUB: sometimes, with the wrong version, all calls to CUB functions do nothing.

"version `GLIBC_2.32' not found" is a difference in C libraries. This is a general linux thing to understand.

It may be helpful to look at the build process we do in docker, in the packaging directory, and do something similar. The linux_wheels one is maybe easier to understand but slightly out of date.

**Comment by domef** [comment]
Do you have any up to date script you use to compile pytorch3d (such that it is compatible on different os/hardwares) given the versions of pytorch3d, pytorch, cuda and python?

**Comment by bottler** [comment]
I've just updated https://github.com/facebookresearch/pytorch3d/tree/main/packaging/linux_wheels which is what built the latest official linux wheels. I'm using official docker containers like pytorch's build, which avoids some environment differences.

**Comment by domef** [comment]
I just tried to build with docker and the new script and it works. Thank you!
