### ISSUE TITLE
Error 'pytorch3d' has no attribute 'ops'

### ISSUE THREAD

**Issue by ardianumam** [facebookresearch/pytorch3d#1590]
Hi,

I install pytorch3d on Ubuntu 20.04 machine via `pip install pytorch3d`, with CPU only and Python 3.9.15. The installation is successful. However, when I call `pytorch3d.ops.sample_farthest_points`, it gets me error `Error 'pytorch3d' has no attribute 'ops'`. Is the any direction to solve this?

Thanks,
Ardian

**Comment by whao22** [comment]
> Hi,
> 
> I install pytorch3d on Ubuntu 20.04 machine via `pip install pytorch3d`, with CPU only and Python 3.9.15. The installation is successful. However, when I call `pytorch3d.ops.sample_farthest_points`, it gets me error `Error 'pytorch3d' has no attribute 'ops'`. Is the any direction to solve this?
> 
> Thanks, Ardian

I had the same problem, and i find the following code is useful.

```
import pytorch3d.ops as ops
ops.sample_farthest_points()
```
