### ISSUE TITLE
windows11 install

### ISSUE THREAD

**Issue by gkadntmd** [facebookresearch/pytorch3d#1591]
This error occurs while installing in the Windows 11 conda environment
python=3.9
cuda=11.7

  building 'pytorch3d._C' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pytorch3d
  Running setup.py clean for pytorch3d
Failed to build pytorch3d
ERROR: Could not build wheels for pytorch3d, which is required to install pyproject.toml-based projects

However, I have installed all the latest build tools. Before installing in this environment, it was installed well in other environments, but this problem occurs in the newly created virtual environment.

halp me !!

**Comment by bottler** [comment]
Are you using the right command prompt? I think you need to be working in a visual studio command prompt, which is with the relevant version of visual studio in "program files" or something.

**Comment by dhruva-pathak** [comment]
does your PATH include the Visual Studio build tools path?  For me, I found I had to include 
`C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\Hostx64\x64` in my PATH variable,

**Comment by gkadntmd** [comment]
The problem was the environment variable that I set the other day. thank you!
