### ISSUE TITLE
How to render part of huge image?

### ISSUE THREAD

**Issue by jasam-sheja** [facebookresearch/pytorch3d#1596]
Hi,
Thanks a lot for the great work you have done with Pytorch3D!

Is there a way to render part of the image but not all of it?
A big image would take a considerable amount of memory and time.
Tuning bin_size dramatically improves the performance, but there is room for improvement.

The use case is there is a fixed camera in a virtual scene.
The object can fit in 256x256 pixels, but the image is FHD.
I already know where the object in the image is.
Rendering the rest of the image is wasting resources.

Is there a way to manipulate the `MeshRenderer` for this target, or maybe the camera itself?

Thank you!

**Comment by bottler** [comment]
You can create a specific camera object for the part of the image you care about. Easiest case if that if you only care about a particular axis-aligned rectangle in the image, you can render exactly that rectangle's pixels via a new camera object.

**Comment by jasam-sheja** [comment]
Thank you for your reply. Specification changed, and the bounding box is variable for each render.
I ended up modifying the Cuda code to limit the processing for-loops to the bounding box.
