### ISSUE TITLE
error: namespace "thrust::cub" has no member "DebugSyncStream" 

### ISSUE THREAD

**Issue by yydxlv** [facebookresearch/pytorch3d#1604]
OS: Windows 11
cuda: 11.8
compiler:  VS2022
I have tried  cub 2.1.0, cub 2.2.2,  cub-1.17.2,  1.17.1
But got the error:

C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8/include\thrust/system/cuda/detail/core/agent_launcher.h(524): error:
namespace "thrust::cub" has no member "DebugSyncStream"

1 error detected in the compilation of "C:/Users/pytorch3d-main/pytorch3d/csrc/iou_box3d/iou_box3d.cu".
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.8\\bin\\nvcc.exe' failed with exit code 2

can you help me, thank you!

**Comment by pzc163** [comment]
i meet the same error
OS: Windows 10
cuda: 11.8
compiler: VS2019
I have tried cub 2.1.0 and cub-1.17.0 all failed，is there anyone can help me to fix it？

**Comment by wyyyz1937365497** [comment]
i meet the same error
OS: Windows 11
cuda: 11.8
vs2019
can u tell me how to fix it?

**Comment by zebraNUO** [comment]
> 我遇到了同样的错误 OS：Windows 10 cuda：11.8 编译器：VS2019 我尝试过 cub 2.1.0 和 cub-1.17.0 都失败了，有谁可以帮我修复
Did you solve it?can you help me？
