### ISSUE TITLE
Error in torch version 1.13.1and pytorch3d version 0.5.0

### ISSUE THREAD

**Issue by 1ssb** [facebookresearch/pytorch3d#1607]
Hi everyone, I am encountering this error, has anyone encountered this as of yet: ImportError: /home/users/xxxx/anaconda3/envs/pixelsynth_replicate/lib/python3.7/site-packages/pytorch3d/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZTIN3c1021AutogradMetaInterfaceE

Trying to run the following: 
# installing Pytorch 1.7.1 and Pytorch3D 0.4.0
conda install -c pytorch pytorch=1.7.1 torchvision
conda install -c fvcore -c iopath -c conda-forge fvcore iopath
conda install -c bottler nvidiacub
git clone https://github.com/facebookresearch/pytorch3d.git
cd pytorch3d && pip install -e . && cd ..

**Comment by 1ssb** [comment]
I have been trying to make the pixelsynth work which seems to be outdated
or not maintained. But its supposed to work with the pytorch3d .5 version.
Does this mean that its not feasible to make this run?

**Comment by bottler** [comment]
It might just work with the latest pytorch3d. If not it should be possible to make it work. (Perhaps someone has already tried and posted how somewhere.)

**Comment by 1ssb** [comment]
Yeah...about that couldn't find one. Do you suppose I should get the latest Pytorch 3d and then download the remaining they offer? Also, could you point to the exact code to be used for Linux machines in the conda environment? I found multiple of them and they all seemed to be alternatives to one another..... if you check their original install file it goes like: # installing Pytorch 1.7.1 and Pytorch3D 0.4.0
conda install -c pytorch pytorch=1.7.1 torchvision
conda install -c fvcore -c iopath -c conda-forge fvcore iopath
conda install -c bottler nvidiacub
git clone https://github.com/facebookresearch/pytorch3d.git
cd pytorch3d && pip install -e . && cd ..

Which should not be an issue right?

**Comment by 1ssb** [comment]
Thanks, I'll check it out. If it works I will make sure to close the issue.

**Comment by 1ssb** [comment]
This worked: 
`conda install -c pytorch pytorch=1.7.1 torchvision
conda install -c bottler nvidiacub
conda install -c fvcore -c iopath -c conda-forge fvcore iopath
git clone https://github.com/facebookresearch/pytorch3d.git
cd pytorch3d && pip install -e . && cd ..`
