### ISSUE TITLE
ImportError: /home/fwj/anaconda3/envs/pyfwj/lib/python3.10/site-packages/pytorch3d/_C.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZNK3c1010TensorImpl18compute_contiguousEv

### ISSUE THREAD

**Issue by spider-fly** [facebookresearch/pytorch3d#1608]
>>> import torch
>>> import pytorch3d
>>> from pytorch3d import _C
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/fwj/anaconda3/envs/pyfwj/lib/python3.10/site-packages/pytorch3d/_C.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZNK3c1010TensorImpl18compute_contiguousEv

**Comment by bottler** [comment]
This looks like the kind of thing which would happen if pytorch3d was built with a different version of pytorch than the one you are using. How did you install?

`from pytorch3d import _C` is not something the user is expected to do, by the way, so I am not certain that anything is wrong here. What's the actual error and how did you get it?

**Comment by spider-fly** [comment]
thanks for very much, I have solve the problem by installing new a conda virtual environment ，and according to the md file
