### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by zyuanbing** [facebookresearch/pytorch3d#161]
Hi, all,

I got the following import error:
```
>>> import torch
>>> import pytorch3d
>>> from pytorch3d import _C
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/code/.conda/envs/conda_venv/lib/python3.7/site-packages/pytorch3d/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c106Symbol14fromQualStringERKSs
```
And my config is pytorch=1.4.0, torchvision=0.5.0, cudatoolkit=10.0
I install pytorch3d by `pip install pytorch3d` as [INSTALL.md](https://github.com/facebookresearch/pytorch3d/blob/master/INSTALL.md#3-install-from-a-local-clone)
I tried method in  #33 but doesn't work. Any hints to help?
THANKS

**Comment by bottler** [comment]
As you are using conda and have cuda, it might be better to install with conda, and this would be more consistent with your pytorch installation. Can you do `pip uninstall fvcore pytorch3d` and then `conda install -c pytorch3d pytorch3d`?

Failing that, can you give the complete output of `conda list` please?

**Comment by zyuanbing** [comment]
thanks @bottler , I follow your uninstall command and `conda install` the downloaded package from [here](https://anaconda.org/pytorch3d/pytorch3d/files), but same problem happened again.
this is the output of `conda list`
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_pytorch_select           0.2                       gpu_0  
_tflow_select             2.3.0                       mkl  
absl-py                   0.9.0                    py37_0  
appdirs                   1.4.3                     <pip>
asn1crypto                1.3.0                    py37_0  
astor                     0.8.0                    py37_0  
attrs                     19.3.0                     py_0  
backcall                  0.1.0                    py37_0  
black                     19.10b0                   <pip>
blas                      1.0                         mkl  
bleach                    3.1.3                     <pip>
bleach                    3.1.4                      py_0  
blinker                   1.4                      py37_0  
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.15.0            h7b6447c_1001  
ca-certificates           2020.1.1                      0  
cachetools                3.1.1                      py_0  
certifi                   2020.4.5.1               py37_0  
cffi                      1.14.0           py37h2e261b9_0  
chardet                   3.0.4                 py37_1003  
click                     7.1.1                      py_0  
cloudpickle               1.3.0                      py_0  
cmake                     3.14.0               h52cb24c_0  
cryptography              2.8              py37h1ba5d50_0  
cudatoolkit               10.0.130                      0  
cudnn                     7.6.5                cuda10.0_0  
cycler                    0.10.0                   py37_0  
cytoolz                   0.10.1           py37h7b6447c_0  
dask-core                 2.11.0                     py_0  
dbus                      1.13.12              h746ee38_0  
decorator                 4.4.1                      py_0  
defusedxml                0.6.0                     <pip>
defusedxml                0.6.0                      py_0  
dominate                  2.4.0                      py_0    conda-forge
entrypoints               0.3                      py37_0  
entrypoints               0.3                       <pip>
expat                     2.2.6                he6710b0_0  
flake8                    3.7.9                     <pip>
flake8-bugbear            20.1.4                    <pip>
flake8-comprehensions     3.2.2                     <pip>
fontconfig                2.13.0               h9420a91_0  
freetype                  2.9.1                h8a8886c_1  
fvcore                    0.1.dev200325              py_0    conda-forge
gast                      0.2.2                    py37_0  
glib                      2.63.1               h5a9c865_0  
gmp                       6.1.2                h6c8ec71_1  
google-auth               1.11.2                     py_0  
google-auth-oauthlib      0.4.1                      py_2  
google-pasta              0.1.8                      py_0  
grpcio                    1.27.2           py37hf8bcb03_0  
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
h5py                      2.10.0           py37h7918eee_0  
hdf5                      1.10.4               hb1b8bf9_0  
icu                       58.2                 h9c2bf20_1  
idna                      2.9                        py_1    conda-forge
imageio                   2.6.1                    py37_0  
importlib_metadata        1.5.0                    py37_0  
intel-openmp              2019.4                      243  
ipykernel                 5.1.4            py37h39e3cac_0  
ipython                   7.13.0           py37h5ca1d4c_0  
ipython-genutils          0.2.0                     <pip>
ipython_genutils          0.2.0                    py37_0  
ipywidgets                7.5.1                      py_0  
isort                     4.3.21                    <pip>
jedi                      0.16.0                   py37_1  
jinja2                    2.11.1                     py_0  
joblib                    0.14.1                    <pip>
jpeg                      9b                   h024ee3a_2  
jsonschema                3.2.0                    py37_0  
jupyter                   1.0.0                    py37_7  
jupyter-client            6.0.0                     <pip>
jupyter_client            6.1.2                      py_0  
jupyter_console           6.1.0                      py_0  
jupyter_core              4.6.3                    py37_0  
keras                     2.3.1                         0  
keras-applications        1.0.8                      py_0  
keras-base                2.3.1                    py37_0  
keras-preprocessing       1.1.0                      py_1  
kiwisolver                1.1.0            py37he6710b0_0  
krb5                      1.17.1               h173b8e3_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libcurl                   7.68.0               h20c2e04_0  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libprotobuf               3.11.4               hd408876_0  
libsodium                 1.0.17               h516909a_0    conda-forge
libssh2                   1.8.2                h1ba5d50_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_0  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.9                hea5a465_1  
markdown                  3.1.1                    py37_0  
markupsafe                1.1.1            py37h7b6447c_0  
matplotlib                3.1.3                    py37_0  
matplotlib-base           3.1.3            py37hef1b27d_0  
mccabe                    0.6.1                     <pip>
mistune                   0.8.4            py37h7b6447c_0  
mkl                       2020.0                      166  
mkl-include               2020.0                      166  
mkl-service               2.3.0            py37he904b0f_0  
mkl_fft                   1.0.15           py37ha843d7b_0  
mkl_random                1.1.0            py37hd6b4f25_0  
nbconvert                 5.6.1                    py37_0  
nbformat                  5.0.4                      py_0  
ncurses                   6.2                  he6710b0_0  
networkx                  2.4                        py_0  
ninja                     1.9.0            py37hfd86e86_0  
notebook                  6.0.3                    py37_0  
numpy                     1.18.1           py37h4f9e942_0  
numpy-base                1.18.1           py37hde5b4d6_1  
oauthlib                  3.1.0                      py_0  
olefile                   0.46                       py_0  
opencv-contrib-python     4.2.0.32                  <pip>
openssl                   1.1.1g               h7b6447c_0  
opt_einsum                3.1.0                      py_0  
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py37_1  
parso                     0.6.2                      py_0  
pathspec                  0.8.0                     <pip>
pcre                      8.43                 he6710b0_0  
pexpect                   4.8.0                    py37_0  
pickleshare               0.7.5                     <pip>
pickleshare               0.7.5                    py37_0  
pillow                    6.1.0            py37h34e0f95_0  
pip                       20.0.2                   py37_1  
portalocker               1.7.0            py37hc8dfbb8_0    conda-forge
prometheus_client         0.7.1                      py_0  
prompt-toolkit            3.0.4                      py_0  
prompt_toolkit            3.0.4                         0  
protobuf                  3.11.4           py37he6710b0_0  
ptyprocess                0.6.0                    py37_0  
ptyprocess                0.6.0                     <pip>
pyasn1                    0.4.8                      py_0  
pyasn1-modules            0.2.7                      py_0  
pycodestyle               2.5.0                     <pip>
pycparser                 2.19                       py_0  
pyflakes                  2.1.1                     <pip>
pygments                  2.6.1                      py_0  
pyjwt                     1.7.1                    py37_0  
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.6                      py_0  
pyqt                      5.9.2            py37h05f1152_2  
pyrsistent                0.15.7                    <pip>
pyrsistent                0.16.0           py37h7b6447c_0  
pysocks                   1.7.1                    py37_0  
python                    3.7.6                h0371630_2  
python-dateutil           2.8.1                      py_0  
python_abi                3.7                     1_cp37m    conda-forge
pytorch                   1.4.0           cuda100py37h75a84eb_0  
pytorch3d                 0.1.1                     <pip>
pywavelets                1.1.1            py37h7b6447c_0  
pyyaml                    5.3              py37h7b6447c_0  
pyzmq                     19.0.0           py37h1768529_0    conda-forge
qt                        5.9.7                h5867ecd_1  
qtconsole                 4.7.1                     <pip>
qtconsole                 4.7.3                      py_0  
qtpy                      1.9.0                      py_0  
readline                  7.0                  h7b6447c_5  
regex                     2020.4.4                  <pip>
requests                  2.23.0                   py37_0    conda-forge
requests-oauthlib         1.3.0                      py_0  
rhash                     1.3.8                h1ba5d50_0  
rsa                       4.0                        py_0  
scikit-image              0.16.2           py37h0573a6f_0  
scikit-learn              0.22.2.post1              <pip>
scipy                     1.4.1            py37h0b6359f_0  
Send2Trash                1.5.0                     <pip>
send2trash                1.5.0                    py37_0  
setuptools                45.2.0                   py37_0  
sip                       4.19.8           py37hf484d3e_0  
six                       1.14.0                   py37_0  
soft-renderer             1.0.0                     <pip>
sqlite                    3.31.1               h7b6447c_0  
tabulate                  0.8.7              pyh9f0ad1d_0    conda-forge
tbb                       2020.0               hfd86e86_0  
tbb4py                    2020.0           py37hfd86e86_0  
tensorboard               1.14.0           py37hf484d3e_0  
tensorflow                1.14.0          mkl_py37h45c423b_0  
tensorflow-base           1.14.0          mkl_py37h7ce6ba3_0  
tensorflow-estimator      1.14.0                     py_0  
termcolor                 1.1.0                    py37_1  
terminado                 0.8.3                    py37_0  
terminado                 0.8.3                     <pip>
testpath                  0.4.4                      py_0  
tk                        8.6.8                hbc83047_0  
toml                      0.10.0                    <pip>
toolz                     0.10.0                     py_0  
torchfile                 0.1.0                      py_0    conda-forge
torchvision               0.5.0                     <pip>
torchvision               0.2.1                    py37_0  
tornado                   6.0.3            py37h7b6447c_3  
tqdm                      4.42.1                     py_0  
traitlets                 4.3.3                    py37_0  
typed-ast                 1.4.1                     <pip>
typing                    3.6.4                    py37_0  
urllib3                   1.25.8                   py37_0  
visdom                    0.1.8.9                       0    conda-forge
wcwidth                   0.1.8                     <pip>
wcwidth                   0.1.9                      py_0  
webencodings              0.5.1                    py37_1  
webencodings              0.5.1                     <pip>
websocket-client          0.56.0                   py37_0  
werkzeug                  1.0.0                      py_0  
wheel                     0.34.2                   py37_0  
widgetsnbextension        3.5.1                    py37_0  
wrapt                     1.12.1           py37h7b6447c_1  
xz                        5.2.4                h14c3975_4  
yacs                      0.1.6                      py_0    conda-forge
yaml                      0.1.7                had09818_2  
zeromq                    4.3.2                he1b5a44_2    conda-forge
zipp                      2.2.0                      py_0  
zipp                      3.1.0                     <pip>
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0 
```

**Comment by bottler** [comment]
Your conda environment is in a strange state. You have two copies of torchvision: one via conda which is very old (and cannot be used by pytorch3d) and one via pip. You are currently, as discussed, trying to install the conda was. You also have fvcore (and its dependency yacs) installed from conda-forge, which I think is an old version.

Can you try starting from scratch in a new conda environment, installing everything from conda in the recommended way?

**Comment by zyuanbing** [comment]
thanks @bottler ,
I tried starting from a new conda environment.
my commands:
```
conda create -n pytorch3d python=3.7
conda activate pytorch3d
conda install pytorch=1.4.0 cudatoolkit=10.0
conda install -c pytorch torchvision
conda install -c pytorch3d pytorch3d
```
and output of `conda list`
 ```# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_pytorch_select           0.2                       gpu_0  
blas                      1.0                         mkl  
ca-certificates           2020.1.1                      0  
certifi                   2020.4.5.1               py37_0  
cffi                      1.14.0           py37h2e261b9_0  
cudatoolkit               10.0.130                      0  
cudnn                     7.6.5                cuda10.0_0  
freetype                  2.9.1                h8a8886c_1  
intel-openmp              2020.0                      166  
jpeg                      9b                   h024ee3a_2  
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_0  
mkl                       2020.0                      166  
mkl-service               2.3.0            py37he904b0f_0  
mkl_fft                   1.0.15           py37ha843d7b_0  
mkl_random                1.1.0            py37hd6b4f25_0  
ncurses                   6.2                  he6710b0_0  
ninja                     1.9.0            py37hfd86e86_0  
numpy                     1.18.1           py37h4f9e942_0  
numpy-base                1.18.1           py37hde5b4d6_1  
olefile                   0.46                       py_0  
openssl                   1.1.1g               h7b6447c_0  
pillow                    7.0.0            py37hb39fc2d_0  
pip                       20.0.2                   py37_1  
pycparser                 2.20                       py_0  
python                    3.7.7           hcf32534_0_cpython  
pytorch                   1.4.0           cuda100py37h75a84eb_0  
pytorch3d                 0.1.1                py37_cu100    <unknown>
readline                  8.0                  h7b6447c_0  
setuptools                46.1.3                   py37_0  
six                       1.14.0                   py37_0  
sqlite                    3.31.1               h62c20be_1  
tk                        8.6.8                hbc83047_0  
torchvision               0.5.0                py37_cu100    <unknown>
wheel                     0.34.2                   py37_0  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0```
```
where [pytorch3d](https://anaconda.org/pytorch/torchvision/files) and [torchvision](https://anaconda.org/pytorch3d/pytorch3d/files) are installed manually due to the network issue.

but it still does't work.

**Comment by bottler** [comment]
Do you still get the same error? This environment looks much healthier.

**Comment by ShairozS** [comment]
I am also getting this error with a fresh install on Linux. 
The following are the relevant packages I have installed. 

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_pytorch_select           0.2                       gpu_0
cudatoolkit               10.1.243             h6bb024c_0
cudnn                     7.6.5                cuda10.1_0
fvcore                    0.1.dev200325              py_0    conda-forge
python                    3.6.10               hcf32534_1
pytorch                   1.4.0           cuda101py36h02f0884_0
pytorch3d                 0.1.1                py36_cu101    pytorch3d

**Comment by bottler** [comment]
@ShairozS I think your problem might not be the same. Yours could be a mismatch in the compiler options for pytorch. Did you install the packages in the manner given in our INSTALL.md? I wonder if you could have a pytorch coming from somewhere else. Have you modified your path?

(I notice you don't have torchvision or yacs in your list, but maybe you just missed the end. pytorch3d shouldn't have installed without them.

**Comment by zyuanbing** [comment]
thanks @bottler,
I solve the problem by reinstall pytorch using
`conda install -c pytorch pytorch=1.4.0`
instead
`conda install pytorch=1.4.0`
I noticed these two `pytorch` versions are different as they both are `1.4.0`

**Comment by ShairozS** [comment]
@bottler I have torchvision and used INSTALL.md to do the install. I've got it working fine using that method on a seperate machine but not sure what's going on here. I have gcc 7.5.0 and my CUDA_HOME env variable is set using a standalone install of CUDA (this was needed to get Kaolin working on the same environment). Below is my full conda environment. 

> _libgcc_mutex             0.1                        main
_pytorch_select           0.2                       gpu_0
alabaster                 0.7.12                   pypi_0    pypi
attrs                     19.3.0                     py_0
autopep8                  1.5.2                    pypi_0    pypi
babel                     2.8.0                    pypi_0    pypi
backcall                  0.1.0                    py36_0
blas                      1.0                         mkl
bleach                    3.1.4                      py_0
ca-certificates           2020.1.1                      0
certifi                   2020.4.5.1               py36_0
cffi                      1.14.0           py36h2e261b9_0
chardet                   3.0.4                    pypi_0    pypi
coverage                  5.1                      pypi_0    pypi
cudatoolkit               10.1.243             h6bb024c_0
cudnn                     7.6.5                cuda10.1_0
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.15          py36he6710b0_0
dbus                      1.13.12              h746ee38_0
decorator                 4.4.2                      py_0
defusedxml                0.6.0                      py_0
docutils                  0.16                     pypi_0    pypi
entrypoints               0.3                      py36_0
expat                     2.2.6                he6710b0_0
flake8                    3.8.0a2                  pypi_0    pypi
fontconfig                2.13.0               h9420a91_0
freetype                  2.9.1                h8a8886c_1
glib                      2.63.1               h5a9c865_0
gmp                       6.1.2                h6c8ec71_1
gst-plugins-base          1.14.0               hbbd80ab_1
gstreamer                 1.14.0               hb453b48_1
icu                       58.2                 h9c2bf20_1
idna                      2.9                      pypi_0    pypi
imageio                   2.8.0                    pypi_0    pypi
imagesize                 1.2.0                    pypi_0    pypi
importlib_metadata        1.5.0                    py36_0
intel-openmp              2020.0                      166
ipykernel                 5.1.4            py36h39e3cac_0
ipython                   7.13.0           py36h5ca1d4c_0
ipython_genutils          0.2.0                    py36_0
ipywidgets                7.5.1                      py_0
jedi                      0.16.0                   py36_1
jinja2                    2.11.1                     py_0
jpeg                      9b                   h024ee3a_2
json5                     0.9.4                    pypi_0    pypi
jsonschema                3.2.0                    py36_0
jupyter                   1.0.0                    py36_7
jupyter_client            6.1.2                      py_0
jupyter_console           6.1.0                      py_0
jupyter_core              4.6.3                    py36_0
jupyterlab                2.1.1                    pypi_0    pypi
jupyterlab-server         1.1.1                    pypi_0    pypi
kiwisolver                1.2.0                    pypi_0    pypi
ld_impl_linux-64          2.33.1               h53a641e_7
libedit                   3.1.20181209         hc058e9b_0
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 9.1.0                hdf63c60_0
libgfortran-ng            7.3.0                hdf63c60_0
libpng                    1.6.37               hbc83047_0
libsodium                 1.0.16               h1bed415_0
libstdcxx-ng              9.1.0                hdf63c60_0
libtiff                   4.1.0                h2733197_0
libuuid                   1.0.3                h1bed415_2
libxcb                    1.13                 h1bed415_1
libxml2                   2.9.9                hea5a465_1
markupsafe                1.1.1            py36h7b6447c_0
matplotlib                2.2.5                    pypi_0    pypi
mccabe                    0.6.1                    pypi_0    pypi
mistune                   0.8.4            py36h7b6447c_0
mkl                       2020.0                      166
mkl-service               2.3.0            py36he904b0f_0
mkl_fft                   1.0.15           py36ha843d7b_0
mkl_random                1.1.0            py36hd6b4f25_0
more-itertools            8.2.0                    pypi_0    pypi
nbconvert                 5.6.1                    py36_0
nbformat                  5.0.4                      py_0
ncurses                   6.2                  he6710b0_0
networkx                  2.4                      pypi_0    pypi
ninja                     1.9.0            py36hfd86e86_0
notebook                  6.0.3                    py36_0
numpy                     1.18.1           py36h4f9e942_0
numpy-base                1.18.1           py36hde5b4d6_1
olefile                   0.46                     py36_0
openssl                   1.1.1g               h7b6447c_0
packaging                 20.3                     pypi_0    pypi
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py36_1
parso                     0.6.2                      py_0
pcre                      8.43                 he6710b0_0
pexpect                   4.8.0                    py36_0
pickleshare               0.7.5                    py36_0
pillow                    6.2.2                    pypi_0    pypi
pip                       20.0.2                   py36_1
pluggy                    0.13.1                   pypi_0    pypi
portalocker               1.5.2                    py36_0
pptk                      0.1.0                    pypi_0    pypi
prometheus_client         0.7.1                      py_0
prompt-toolkit            3.0.4                      py_0
prompt_toolkit            3.0.4                         0
ptyprocess                0.6.0                    py36_0
py                        1.8.1                    pypi_0    pypi
pycodestyle               2.6.0a1                  pypi_0    pypi
pycparser                 2.20                       py_0
pyflakes                  2.2.0                    pypi_0    pypi
pygments                  2.6.1                      py_0
pyparsing                 3.0.0a1                  pypi_0    pypi
pyqt                      5.9.2            py36h05f1152_2
pyrsistent                0.16.0           py36h7b6447c_0
pytest                    5.4.1                    pypi_0    pypi
pytest-cov                2.8.1                    pypi_0    pypi
python                    3.6.10               hcf32534_1
python-dateutil           2.8.1                      py_0
python_abi                3.6                     1_cp36m    conda-forge
pytorch                   1.4.0           cuda101py36h02f0884_0
pytorch3d                 0.1.1                py36_cu101    pytorch3d
pytz                      2019.3                   pypi_0    pypi
pywavelets                1.1.1                    pypi_0    pypi
pyyaml                    5.3.1            py36h7b6447c_0
pyzmq                     18.1.1           py36he6710b0_0
qt                        5.9.7                h5867ecd_1
qtconsole                 4.7.3                      py_0
qtpy                      1.9.0                      py_0
readline                  8.0                  h7b6447c_0
requests                  2.23.0                   pypi_0    pypi
scikit-image              0.16.2                   pypi_0    pypi
scipy                     1.4.1                    pypi_0    pypi
send2trash                1.5.0                    py36_0
setuptools                46.1.3                   py36_0
shapely                   1.7.0                    pypi_0    pypi
sip                       4.19.8           py36hf484d3e_0
six                       1.14.0                   py36_0
snowballstemmer           2.0.0                    pypi_0    pypi
sphinx                    2.2.0                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    1.0.3                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.4                    pypi_0    pypi
sqlite                    3.31.1               h62c20be_1
tabulate                  0.8.3                    py36_0
termcolor                 1.1.0                    py36_1
terminado                 0.8.3                    py36_0
testpath                  0.4.4                      py_0
tk                        8.6.8                hbc83047_0
torchvision               0.5.0                py36_cu101    pytorch
tornado                   6.0.4            py36h7b6447c_1
tqdm                      4.45.0                     py_0
traitlets                 4.3.3                    py36_0
trimesh                   3.6.33                   pypi_0    pypi
urllib3                   1.25.9                   pypi_0    pypi
wcwidth                   0.1.9                      py_0
webencodings              0.5.1                    py36_1
wheel                     0.34.2                   py36_0
widgetsnbextension        3.5.1                    py36_0
xz                        5.2.5                h7b6447c_0
yacs                      0.1.6                      py_0    conda-forge
yaml                      0.1.7                had09818_2
zeromq                    4.3.1                he6710b0_3
zipp                      2.2.0                      py_0
zlib                      1.2.11               h7b6447c_3
zstd                      1.3.7                h0b5b093_0

**Comment by bottler** [comment]
@ShairozS I think you have installed pytorch in a strange way, so that it isn't the normal one from the pytorch channel. In particular, I think it is built with a different C++ABI flag from normal.

**Comment by ShairozS** [comment]
@bottler Yep that solved the problem, thanks!
