### ISSUE TITLE
Read a mesh that have scalar values for each vertex.

### ISSUE THREAD

**Issue by mohamed-seyam** [facebookresearch/pytorch3d#1618]
I'm attempting to read a .vtk file containing scalar values for individual vertices. Since pytorch3d doesn't support .vtk files, I converted it to .ply format. Now, I'm aiming to access the resulting scalar values. Is there a method to achieve this?

**Comment by bottler** [comment]
It's relatively easy to customize our PLY reading code to pull in extra data. If you want, you can share the PLY header here and we can suggest how to get the extra values.

**Comment by mohamed-seyam** [comment]
here is the header data.

ply
format binary_little_endian 1.0
comment VTK generated PLY File
obj_info vtkPolyData points and polygons: vtk4.0
element vertex 180225
property float x
property float y
property float z
element face 359917
property list uchar int vertex_indices
end_header

**Comment by bottler** [comment]
That looks like a normal PLY file with vertices and faces. There's no extra data. PyTorch3D should load this fine.

```
    from pytorch3d.io import IO

    mesh = IO().load_mesh("myfile.ply")
```

the "scalar values for individual vertices" will then be in `mesh.verts_padded()`.
