### ISSUE TITLE
Empty rendered image in official tutorial "deform_source_mesh_to_target_mesh"

### ISSUE THREAD

**Issue by aruiplex** [facebookresearch/pytorch3d#1625]
Hi! I am new to Pytorch3d and I am learning the [tutorial](https://pytorch3d.org/tutorials/deform_source_mesh_to_target_mesh). 

## 🐛 Bugs / Unexpected behaviors

But I find that there are empty outputs in these two lines:

```python
plot_pointcloud(trg_mesh, "Target mesh")
plot_pointcloud(src_mesh, "Source mesh")
```

I tried on Colab and the local environment. Here are the screenshots:

The local env:

![image](https://github.com/facebookresearch/pytorch3d/assets/40193711/428099e5-2b74-4e67-8d11-d80ef89b084a)

The Colab:

![image](https://github.com/facebookresearch/pytorch3d/assets/40193711/3c6ab9cb-3586-4b00-b342-030ba74ac933)

It seems like all the outputs in this tutorial not working.

**Comment by aruiplex** [comment]
I find if I change the function to

```python
def plot_pointcloud(mesh, title=""):
    # Sample points uniformly from the surface of the mesh.
    points = sample_points_from_meshes(mesh, 5000)
    x, y, z = points.clone().detach().cpu().squeeze().unbind(1)
    fig = plt.figure(figsize=(5, 5))
    ax = fig.add_subplot(projection='3d')
    ax.scatter(x, -y, z)
    ax.set_xlabel('x')
    ax.set_ylabel('z')
    ax.set_zlabel('y')
    ax.set_title(title)
    ax.view_init(190, 30)
    plt.show()
```
It works, but not that beautiful.

**Comment by bottler** [comment]
I think this is a browser resources thing.
