### ISSUE TITLE
from pytorch3d import _C ImportError: cannot import name '_C' from 'pytorch3d' (unknown location)

### ISSUE THREAD

**Issue by tyq996** [facebookresearch/pytorch3d#1629]
cuda10.1+python3.8+torch1.8.0
I download the zip file directly to my conda env, but there is no _C for pytorch3d, what's wrong with it?

**Comment by 511lyf** [comment]
> cuda10.1+python3.8+torch1.8.0 我将 zip 文件直接下载到我的 conda env，但是 pytorch3d 没有_C，这是怎么回事？

Hello, did you finally solve the problem? Can you help me see what the problem is? I have the same problem. I installed it using Pytorch3D-0.7.6 +pt2.1.0cu121-cp38-cp38-win_amd64.whl, which can import pytorch3d correctly, but I cannot find the _C module, so I urgently seek help

**Comment by bottler** [comment]
@511lyf Once more - please do not sidetrack issues. (This issue seems may be abandoned.)

**Comment by 511lyf** [comment]
> 我在使用时遇到同样的问题 然后，当我运行时，它会报告缺少_C的错误。我曾经通过从本地克隆安装为“pip install -e ”解决了这个问题，但此时它只是卡住了，直到取消。谁能帮忙？`conda install pytorch3d -c conda-forge.``import pytorch.ops`

I used whl file to download pytorch3d directly, just need to keep the version consistent with your cuda and other Settings, it can be used normally. If you have any other questions, you can add my wechat zwz_0511, I can provide the method I use, I hope it can help you

**Comment by LeeKeyu** [comment]
> > 我在使用时遇到同样的问题 然后，当我运行时，它会报告缺少_C的错误。我曾经通过从本地克隆安装为“pip install -e ”解决了这个问题，但此时它只是卡住了，直到取消。谁能帮忙？`` conda install pytorch3d -c conda-forge.``import pytorch.ops ``
> 
> I used whl file to download pytorch3d directly, just need to keep the version consistent with your cuda and other Settings, it can be used normally. If you have any other questions, you can add my wechat zwz_0511, I can provide the method I use, I hope it can help you

Thanks for your suggestion but the wheel provided by INSTALL.md did not suit my environment (cuda 12.1, python 3.10, pytorch 2.2.0). I have re-downloaded the package and tried `pip install -e.` and it finnally works after waiting for a long time...

**Comment by forestsen** [comment]
我也遇到这些问题，就算pip install -e .也会遇到_C找不到。我的环境是ubuntu 18.04 python3.9 cuda11.3, torch1.10.2, 找了好多版本的pytorch3d，最后定位在了pytorch3d 0.6.1和cub 1.10.0。安装前首先得配置CUB_HOME的环境。然后，我没有pip install -e.，我用PyCham打开pytorch3d这个文件夹，然后以setup.py配置了个运行环境，先setup.py build, 然后 setup.py install。然后_C就没这个问题了。然后我在不更改CUB_HOME的情况下，也试了pytorch3d0.7.2和0.7.8,也都可以安装到我的环境里，没有_C的问题。
