### ISSUE TITLE
Can I use pytorch3d to deform mesh using only depth image?

### ISSUE THREAD

**Issue by Wang-Tianyu** [facebookresearch/pytorch3d#163]
Thanks for this great and powerful library!

My question is: If I have depth images of some objects but I don't have the meshes and I am trying to reconstruct those object meshes by deforming a sphere. The loss is the difference between the rendered depth image and the ground truth depth image.
Is it possible to do that with pytorch3d?

Thanks

**Comment by gkioxari** [comment]
Hi @Wang-Tianyu. 
From a practical point of view, all of our operators are differentiable so in terms of what you can or can't do, there is no restriction. Sky is the limit! Empirically, you will have to experiment and see whether your idea will result to the desired output. I think your idea is interesting and you should give it a try!

Having said that, note that the issues for PyTorch3D refer to issues regarding the library, such as bug reports, feature requests or clarification questions. This is also explicitly mentioned [here](https://github.com/facebookresearch/pytorch3d/blob/master/.github/ISSUE_TEMPLATE/questions-help.md). Unfortunately, we don't have the time to be consultants for users' projects, no matter how interesting the ideas are. 

I will be closing this issue! Good luck with your project!! <3
