### ISSUE TITLE
Why pytorch3d render a mesh mask to different colors (i.e., surfaces are white, edges are gray)?

### ISSUE THREAD

**Issue by SwordHolderSH** [facebookresearch/pytorch3d#1632]
We would like to ask that why pytorch3d render a mesh mask to different colors (i.e., surfaces are white, edges are gray)?

As shown in the following Figure, in the rendered mask, the rendered surfaces are white and the rendered edges are gray. 

Could you please tell me how to render the mesh mask to the ideal mask (rendered surfaces and edges are all white) in the Figure?

![sample](https://github.com/facebookresearch/pytorch3d/assets/31804639/5ad8b9ea-654c-4ab3-927d-e10c73ab9243)

**Comment by bottler** [comment]
Is the mesh watertight? If it is, perhaps you are seeing the edges due to soft blending. Can you try using a BlendParams with a lower sigma?

Feel free to share how you initialize the renderer.

**Comment by SwordHolderSH** [comment]
> Is the mesh watertight? If it is, perhaps you are seeing the edges due to soft blending. Can you try using a BlendParams with a lower sigma?
> 
> Feel free to share how you initialize the renderer.

Thank you for your kind help!  

We found that this is caused by the soft blending in Soft-Rasterizer, and gray edges can be avoided by reducing sigma.

**Comment by unlugi** [comment]
Could you please provide a code sample that solves this issue? thank you.
