### ISSUE TITLE
Create Mesh from faces and vertices

### ISSUE THREAD

**Issue by juliuskuehn1** [facebookresearch/pytorch3d#1633]
Hello, 

I want to visualize meshes. I only have their faces and vertices in arrays.
So, is it possible to create a mesh with pytorch3d that is not being loaded from file (like an .obj) but only from their faces and vertices?

**Comment by bottler** [comment]
Yes, this is very easy. See the doc in pytorch3d/structures/meshes.py.

Basically you need to make pytorch tensors from your arrays. Then if faces are a (N,3) int64 tensor and verts are (V, 3) float32 tensor you can write
`mesh = Meshes(verts=[verts], faces=[faces])`.

You can visualise with plotly with `plot_batch_individually(mesh)`

**Comment by juliuskuehn1** [comment]
Thank you
