### ISSUE TITLE
UnsatisfiableError  on Ubuntu 16.04, with CUDA 10.2

### ISSUE THREAD

**Issue by prash6392** [facebookresearch/pytorch3d#164]
Hello,

I'm on a Ubuntu 16.04 machine with the following specs

- CUDA 10.2
- pytorch 1.5
- gcc 5.4

I get the following error on running `conda install pytorch3d -c pytorch3d`

![image](https://user-images.githubusercontent.com/5812386/80308949-0bdaec00-87d2-11ea-9246-7482b41493fb.png)

Any help towards this is appreciated ! :)

**Comment by bottler** [comment]
Have you already got cudatoolkit, pytorch and torchvision installed? 
Can you paste the entire output of `conda list` please?

**Comment by prash6392** [comment]
Yes, here the output of `conda list` 

`
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
blas                      1.0                         mkl    anaconda
ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
certifi                   2020.4.5.1       py37hc8dfbb8_0    conda-forge
cloudpickle               1.3.0                      py_0    anaconda
cudatoolkit               10.2.89              hfd86e86_0  
cycler                    0.10.0                   py37_0    anaconda
cytoolz                   0.10.1           py37h7b6447c_0    anaconda
dask-core                 2.14.0                     py_0    anaconda
dbus                      1.13.12              h746ee38_0  
decorator                 4.4.2                      py_0    anaconda
expat                     2.2.6                he6710b0_0    anaconda
fontconfig                2.13.0               h9420a91_0    anaconda
freetype                  2.9.1                h8a8886c_1    anaconda
fvcore                    0.1.dev200424            pypi_0    pypi
glib                      2.63.1               h5a9c865_0  
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
icu                       58.2                 h9c2bf20_1  
imageio                   2.8.0                      py_0    conda-forge
intel-openmp              2020.0                      166    anaconda
joblib                    0.14.1                     py_0    anaconda
jpeg                      9b                   h024ee3a_2  
kiwisolver                1.1.0            py37he6710b0_0    anaconda
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0    anaconda
libpng                    1.6.37               hbc83047_0    anaconda
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_0    anaconda
libuuid                   1.0.3                h1bed415_2    anaconda
libxcb                    1.13                 h1bed415_1    anaconda
libxml2                   2.9.9                hea5a465_1    anaconda
matplotlib                3.1.3                    py37_0    anaconda
matplotlib-base           3.1.3            py37hef1b27d_0    anaconda
mkl                       2019.4                      243    anaconda
mkl-service               2.3.0            py37he904b0f_0    anaconda
mkl_fft                   1.0.15           py37ha843d7b_0    anaconda
mkl_random                1.1.0            py37hd6b4f25_0    anaconda
ncurses                   6.2                  he6710b0_0  
networkx                  2.4                        py_0    anaconda
ninja                     1.10.0               hc9558a2_0    conda-forge
numpy                     1.18.1           py37h4f9e942_0    anaconda
numpy-base                1.18.1           py37hde5b4d6_1    anaconda
olefile                   0.46                     py37_0    anaconda
openssl                   1.1.1g               h516909a_0    conda-forge
pandas                    1.0.3            py37h0573a6f_0    anaconda
pcre                      8.43                 he6710b0_0    anaconda
pillow                    7.0.0            py37hb39fc2d_0    anaconda
pip                       20.0.2                   py37_1  
plyfile                   0.7.2              pyh9f0ad1d_0    conda-forge
portalocker               1.7.0            py37hc8dfbb8_0    conda-forge
pyparsing                 2.4.6                      py_0    anaconda
pyqt                      5.9.2            py37h22d08a2_1    anaconda
python                    3.7.7           hcf32534_0_cpython  
python-dateutil           2.8.1                      py_0    anaconda
python_abi                3.7                     1_cp37m    conda-forge
pytorch                   1.5.0           py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch
pytz                      2019.3                     py_0    anaconda
pywavelets                1.1.1            py37h7b6447c_0    anaconda
pyyaml                    5.3.1                    pypi_0    pypi
qt                        5.9.7                h5867ecd_1  
readline                  8.0                  h7b6447c_0  
scikit-image              0.16.2           py37h0573a6f_0    anaconda
scikit-learn              0.22.1           py37hd81dba3_0    anaconda
scipy                     1.4.1            py37h0b6359f_0    anaconda
seaborn                   0.10.0                     py_0    anaconda
setuptools                46.1.3                   py37_0  
sip                       4.19.13          py37he6710b0_0    anaconda
six                       1.14.0                   py37_0    anaconda
sqlite                    3.31.1               h62c20be_1  
tabulate                  0.8.7              pyh9f0ad1d_0    conda-forge
termcolor                 1.1.0                    pypi_0    pypi
tk                        8.6.8                hbc83047_0  
toolz                     0.10.0                     py_0    anaconda
torchvision               0.6.0                py37_cu102    pytorch
tornado                   6.0.4            py37h7b6447c_1    anaconda
tqdm                      4.45.0             pyh9f0ad1d_0    conda-forge
wheel                     0.34.2                   py37_0  
xz                        5.2.5                h7b6447c_0  
yacs                      0.1.7                    pypi_0    pypi
yaml                      0.2.4                h516909a_0    conda-forge
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0    anaconda
`

**Comment by bottler** [comment]
I should have spotted the problem originally. Our current release of pytorch3d, 0.1.1, does not have builds available for pytorch 1.5 or cuda 10.2. We are planning to release a new version very soon which will.

In the meantime, can you try installing the current nightly build with `conda install -c pytorch3d-nightly pytorch3d`. I think that will be fine.

**Comment by prash6392** [comment]
Just tried that and I can confirm that switching to the nightly build fixed my problem.

Thanks a lot :)
