### ISSUE TITLE
How to transfer vertex colors (features) to texture map (UV Space) using pytorch3d?

### ISSUE THREAD

**Issue by zhongjinluo** [facebookresearch/pytorch3d#1647]
Suppose I know the following information:

vertices, faces and
uv and uv_faces and vertex colors (features)

How can I render/interpolate vertex colors (features) to a texture map? Such as,

![1](https://github.com/facebookresearch/pytorch3d/assets/22856460/4c9f62f3-db3b-48e2-a07c-b6681673fa5b)

**Comment by bottler** [comment]
With careful pytorch indexing, the vertex uvs, face uvs and vertex colors determine a 2D point cloud which you can find. You then just need to interpolate it into an image.
