### ISSUE TITLE
when i install in windows10 x64, vs2017,cuda10, i meet "Faces have invalid indices".

### ISSUE THREAD

**Issue by Dian-Yi** [facebookresearch/pytorch3d#165]
i run the tests  command "python3 -m unittest discover -p *.py", show the warnings:
c:\AppData\anaconda3\lib\site-packages\pytorch3d-0.1.1-py3.7-win-amd64.egg\pytorch3d\io\obj_io.py:70: UserWarning: Faces have invalid indices
  warnings.warn("Faces have invalid indices")

i run the  Render a textured mesh tutorial  from 'https://pytorch3d.org/tutorials/render_textured_meshes'.  
it also show " UserWarning: Faces have invalid indices warnings.warn("Faces have invalid indices")"
and dont show the output images

**Comment by nikhilaravi** [comment]
I just tried running this tutorial on Google Colab and it worked correctly. The warning should not affect the rendering output.   Can you share a screenshot of your notebook and what is being show in the output cell?

**Comment by Dian-Yi** [comment]
there is only show the warnings infos , no other infomations in the scree,.

**Comment by nikhilaravi** [comment]
@Dian-Yi what is the output of 
```
from pytorch3d.io import load_obj
verts, faces, aux = load_obj(obj_filename, load_textures=True)

print(verts)
print(faces.verts_idx)
```

Are the verts and faces being loaded correctly despite the warning? Please inspect the verts/faces to check.

**Comment by JMingKuo** [comment]
Hi,

The **_load** function In pytorch3d/pytorch3d/io/obj_io.py 
Seems always be true for 
```
len(faces_normals_idx) > 0
len(faces_textures_idx) > 0
len(faces_materials_idx) > 0
```
as those of them would filled by -1 during **_parse_face**.

Given the faces_indices of -1s and max_index=0, **_format_faces_indices** will
raise the warning for **normal** and **texture** with **torch.any(faces_indices < 0)**.

However, this should not cause any problem for normal usage.

**Comment by Dian-Yi** [comment]
> @Dian-Yi what is the output of
> 
> ```
> from pytorch3d.io import load_obj
> verts, faces, aux = load_obj(obj_filename, load_textures=True)
> 
> print(verts)
> print(faces.verts_idx)
> ```
> 
> Are the verts and faces being loaded correctly despite the warning? Please inspect the verts/faces to check.

i run the above code. the 3d mode is cow. but  i run the textured mesh tutorial, i can seen the render cow in my screen and only showing warning.
the  above code output:
tensor([[ 0.3488, -0.3350, -0.0832],
        [ 0.3131, -0.3991,  0.8812],
        [ 0.2668,  0.1816,  0.1227],
        ...,
        [-0.0132, -0.0889,  1.0422],
        [-0.0137, -0.0943,  1.0340],
        [-0.0137, -0.0796,  1.0469]])
tensor([[ 738,  734,  735],
        [ 188,  735,  734],
        [ 191,  737,  736],
        ...,
        [1855,  107, 2929],
        [2927, 2929,  733],
        [2923,  733, 2929]])

**Comment by Dian-Yi** [comment]
thanks for u answers. i figure out the reason why there is nothing in my screen. the tutorial cant use 'plt.show()' to  show the render image

**Comment by nikhilaravi** [comment]
The warning about `faces have invalid indices` has been fixed by https://github.com/facebookresearch/pytorch3d/commit/a3932960b31ff07e942a54e4608eae6ba12bf40a. It was an issue with the normals/texture indices for the faces, not the face vertex indices.
