### ISSUE TITLE
ImportError: cannot import name 'Volumes' from 'pytorch3d.structures'

### ISSUE THREAD

**Issue by Li-weiyan** [facebookresearch/pytorch3d#1652]
## ❓ Questions on how to use PyTorch3D

This is my code:
```python
from pytorch3d.structures import Pointclouds, Volumes
```
but error:
```
ImportError: cannot import name 'Volumes' from 'pytorch3d.structures'
```
how to handle this?my pytorch3d version is 0.2.5

**Comment by bottler** [comment]
PyTorch3D version 0.2.5 is very old. Volumes probably did not exist in that version.

**Comment by kano-Aki** [comment]
> PyTorch3D version 0.2.5 is very old. Volumes probably did not exist in that version.

Hello,I also encounter this problem.
This is my dependences version
pytorch                   2.0.1           py3.8_cuda11.7_cudnn8.5.0_0    pytorch
pytorch-cuda              11.7                 h778d358_5    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytorch3d                 0.3.0                    pypi_0    pypi

**Comment by bottler** [comment]
This is not something that can be fixed. If you need new features, you need to use new versions of pytorch3d.
