### ISSUE TITLE
Pytorch3d for old environments.

### ISSUE THREAD

**Issue by Hafez-Jamshidi** [facebookresearch/pytorch3d#1655]
Hello, I am trying to create an environment with some fairly old and outdated libraries on the windows.
This is the list of the dependencies for this environment:
python 3.6.13
torch==1.6.0 torchvision==0.7.0 CUDA=10.1
What I found was that the appropriate pytorch3d library for this environment is version 0.2.5.
But it seems that no repository of this version are available for windows right now, and I could not install any such/ other versions of pytorch3d in this environment. 
All the pytorch3d packages I found were only available for Linux or Mac. 
Could you please help me here and send me the appropriate version/ link which I should install?
Thank you for your help and support.

**Comment by Hafez-Jamshidi** [comment]
@bottler 
Please sir,  give me some answer. It is really important.
I know what I'm asking maybe really basic and even repetitive, but please give me some simple guidance for here please. If it is just suggest some of the old issues to me which I did not read. I will be forever grateful for it.

**Comment by bottler** [comment]
On Windows, you have to build pytorch3d from source, we have never had prebuilt packages. It should still be possible to build version 0.2.5 from source.
