### ISSUE TITLE
Link problem when installing pytorch3d on windows system

### ISSUE THREAD

**Issue by anleleaaa** [facebookresearch/pytorch3d#1660]
Is there any kind-hearted person who can help me solve the windows installation problem? After a few minutes of compilation, this problem finally occurred:
  Creating library E:\AI_hub\pytorch3d-0.7.2\build\temp.win-amd64-cpython-39\Release\AI_hub\pytorch3d-0.7.2\pytorch3d\csrc\ball_query\_C.cp39-win_amd64.lib and Object E:\AI_hub\pytorch3d-0.7.2\build\temp.win-amd64-cpython-39\Release\AI_hub\pytorch3d-0.7.2\pytorch3d\csrc\ball_query\_C.cp39-win_amd64.exp
ball_query_cpu.obj : error LNK2001: unresolved external symbol __imp___tls_offset_?init@?1??lazy_init_num_threads@internal@at@@YAXXZ@4_NA
marching_cubes.obj : error LNK2001: unresolved external symbol __imp___tls_offset_?init@?1??lazy_init_num_threads@internal@at@@YAXXZ@4_NA
ball_query_cpu.obj : error LNK2001: unresolved external symbol __imp___tls_index_?init@?1??lazy_init_num_threads@internal@at@@YAXXZ@4_NA
marching_cubes.obj : error LNK2001: unresolved external symbol __imp___tls_index_?init@?1??lazy_init_num_threads@internal@at@@YAXXZ@4_NA
build\lib.win-amd64-cpython-39\pytorch3d\_C.cp39-win_amd64.pyd : fatal error LNK1120: 2 unresolved external commands
error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\link.exe' failed with exit code 1120

**Comment by bottler** [comment]
This looks like https://stackoverflow.com/questions/74366357/updating-to-visual-studio-17-4-0-yields-linker-errors-related-to-tls
