### ISSUE TITLE
Colab examples failing

### ISSUE THREAD

**Issue by jmjava** [facebookresearch/pytorch3d#1665]
![image](https://github.com/facebookresearch/pytorch3d/assets/591751/6e413250-16b1-41c9-8202-fc878d3c32b7)

**Comment by alejandroHdzV** [comment]
I'm experiencing the same issue. Colab examples used to work perfectly.

**Comment by bottler** [comment]
This should now work again, following release 0.7.5 of pytorch3d just now.
