### ISSUE TITLE
How could I use PyTorch3D load SMPL model and change the pose?

### ISSUE THREAD

**Issue by snowmint** [facebookresearch/pytorch3d#1681]
## ❓ Questions on how to use PyTorch3D

I am currently working on applying my generated 3D coordinate human joint keypoints to the SMPL model with texture. I came across an article about Densepose and applying the SMPL model, which can be found at this link: https://pytorch3d.org/tutorials/render_densepose.
However, I am confused about how to adjust the model's pose.

The images below depict my generated keypoints. Currently, when using PyTorch3D, I am only able to achieve the default T-pose. My goal is to pose the PyTorch3D SMPL model to match the desired pose shown in Image 1.

Image 1: Generated body keypoints
![image](https://github.com/facebookresearch/pytorch3d/assets/7868828/977fece4-40e4-40ab-9fc6-094c452ca714)

Image 2: I am struggling to figure out how to pose the SMPL model to match the desired pose shown in Image 1.
![image](https://github.com/facebookresearch/pytorch3d/assets/7868828/d9163351-7a55-4fa3-92a5-333ff3155a91)

Thank you for taking the time to read my question. I appreciate your assistance and welcome any advice you may have. If there is an alternative approach to achieve this, I would greatly appreciate your insights and suggestions.

**Comment by bottler** [comment]
There's no built-in method in PyTorch3D to do this, you need to work from first principles.
