### ISSUE TITLE
Computing chamfer loss with mahalanobis distance

### ISSUE THREAD

**Issue by HarshitGupta29** [facebookresearch/pytorch3d#1685]
### Discussed in https://github.com/facebookresearch/pytorch3d/discussions/1684

<div type='discussions-op-text'>

<sup>Originally posted by **HarshitGupta29** November  9, 2023</sup>
Hi,

I have a gaussian point cloud and a point cloud. I want to compute chamfer loss between them, but using normal chamfer loss is not accurate. I want to replace euclidean distance with mahalanobis distance. Both point clouds are pretty large so I am hesistant to write my own function. 

I can find whitening matrices for gaussian point cloud and then multiply it with the difference ||W(x-p)||. Any tricks I could use to compute this ?

Any ideas or help is appreciated!</div>

**Comment by bottler** [comment]
There are no particular tricks. Is the problem that transforming the input and using our function runs out of memory? Could you use an inplace operation to transform it?

**Comment by HarshitGupta29** [comment]
I implemented it and the code is available here: [https://github.com/HarshitGupta29/3D-Chamfer-Loss-with-Mahalanobis-Distance](https://github.com/HarshitGupta29/3D-Chamfer-Loss-with-Mahalanobis-Distance)
