### ISSUE TITLE
Does pytorch3d support polygonal-light rendering?

### ISSUE THREAD

**Issue by imxtx** [facebookresearch/pytorch3d#1693]
Does pytorch3d support polygonal-light rendering like this?

<img width="781" alt="image" src="https://github.com/facebookresearch/pytorch3d/assets/93981430/3ff37b7c-cd17-43f5-b6bc-6eae75b5e8ae">

I want the light source to be a polygonal-light, is it possible?

**Comment by bottler** [comment]
This is not implemented in PyTorch3D, where the provided lights are point lights, directional lights and ambient lights. I don't know how hard this would be to implement for yourself.

**Comment by imxtx** [comment]
I see thank you. ---- Replied Message ----FromJeremy ***@***.***>Date12/11/2023 21:09 ***@***.***> CcT.X. ***@***.***>***@***.***>SubjectRe: [facebookresearch/pytorch3d] Does pytorch3d support polygonal-light rendering? (Issue #1693)
This is not implemented in PyTorch3D, where the provided lights are point lights, directional lights and ambient lights. I don't know how hard this would be to implement for yourself.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/facebookresearch/pytorch3d/issues/1693#issuecomment-1850049030",
"url": "https://github.com/facebookresearch/pytorch3d/issues/1693#issuecomment-1850049030",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
