### ISSUE TITLE
Questions on Camera Configurations (Focal Length, FoV, etc)

### ISSUE THREAD

**Issue by The-Nerd-AI** [facebookresearch/pytorch3d#1695]
After reading the [document](https://pytorch3d.org/docs/cameras), I have questions on camera configurations in PyTorch3D.

Suppose ```image_resolution=(256,256)``` and ```focal_length_ndc_space=1.0```.  When I use ```PerspectiveCameras```,

(1) ```focal_length_screen_space==128```, right? What is the unit of the value? Is it ```mm```? For example, the default focal length is ```50mm``` in blender.

(2) What is the FoV (Field of View) in this case? The default FoV value is ```60``` in ```FoVPerspectiveCameras```.  In the above setting, what is the value of FoV in ```PerspectiveCameras```?

(3) What is the sensor size(mm) in ```PerspectiveCameras```?

(4) When I obtain ```R``` and ```T``` from ```look_at_view_transform(dist=1.0)```, what is the distance of the camera from the object? Is it ```1m```? What is the unit of the distance value?

Thank you for this amazing project!

**Comment by bottler** [comment]
It's the second possibility, i.e. whatever unit the objects are described in.
