### ISSUE TITLE
ImportError: /home/chengxuan/anaconda3/envs/DECA/lib/python3.8/site-packages/pytorch3d/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK3c107SymBool10guard_boolEPKcl

### ISSUE THREAD

**Issue by Dratlan** [facebookresearch/pytorch3d#1698]
Something wrong happened while I can't find the solution in other issues. Can you help me? I install pytorch3d with CUDA support from Anaconda Cloud

**Comment by bottler** [comment]
can you share the output of `conda info`, `conda list`, `pip list` and perhaps what command you ran to install?

**Comment by Dratlan** [comment]
> can you share the output of `conda info`, `conda list`, `pip list` and perhaps what command you ran to install?

Thank you for your quickly reply, I write them down in the txt[
[command_log.txt](https://github.com/facebookresearch/pytorch3d/files/13635838/command_log.txt)
](url)

**Comment by bottler** [comment]
The conda list is showing pytorch3d has come from conda-forge, and that is not one of our packages. Somehow `conda install pytorch3d -c pytorch3d` didn't work?

Can you start from a fresh environment? You need to install torch through conda if you want to install pytorch3d through conda, which is recommended.

**Comment by Dratlan** [comment]
> The conda list is showing pytorch3d has come from conda-forge, and that is not one of our packages. Somehow `conda install pytorch3d -c pytorch3d` didn't work?
> 
> Can you start from a fresh environment? You need to install torch through conda if you want to install pytorch3d through conda, which is recommended.

Thank you for your suggestions, I don't know why -c pytorch3d didn't work, and install torch through conda (the same as pytorch3d) matters. Thank you.
