### ISSUE TITLE
Implementation of differentiable renderers❓ 

### ISSUE THREAD

**Issue by NotAnyMike** [facebookresearch/pytorch3d#170]
##  Is there any resource explaining in details the differentiable renderers implemented here❓

I have read through the readme and documentation, I also have used the library several times but I haven't been able to find a good source that explains the implementation details or approach of the differentiable renderers implemented here. Is there any such source (e.g. blog, paper, etc.)?

I appreciate all your effort guys. Thank you :blush:

**Comment by nikhilaravi** [comment]
@NotAnyMike The differentiable renderer is for the most part inspired by the `SoftRasterizer` implementation. There here are several places where the PyTorch3D implementation is documented:

1) [renderer_getting_started.md](https://github.com/facebookresearch/pytorch3d/blob/master/docs/notes/renderer_getting_started.md) has an architecture diagram of the entire pipeline, the coordinate system conventions and information about the shading options. [renderer.md](https://github.com/facebookresearch/pytorch3d/blob/master/docs/notes/renderer.md) has an explanation of the implementation of the rasterizer and the different rasterization settings.
2) Code comments and function docstrings - we have endeavored to add extensive documentation for each of the functions as well as comments throughout the code. If there are any sections which need further documentation, please let us know.  Most of the mesh rendering code can be found under `pytorch3d/renderer/mesh` and `pytorch3d/csrc/rasterize_meshes`.

**Comment by NotAnyMike** [comment]
Thanks for answering. I still think some sort of paper will be useful but certainly your efforts on documenting it has been outstanding. thanks for listing all the sources here (:
