### ISSUE TITLE
Adding a plane in renderer

### ISSUE THREAD

**Issue by santurini** [facebookresearch/pytorch3d#1704]
Hello,
I would like to render a motion with pytorch3d renderer.  My motion consists in a folder of .obj files, each containing a body mesh. I would like to place a plane mesh in the environment that has to be present in every frame. How can I achieve that?

Up to now I am able to obtain this results (no plane, just body mesh):
![motion00-mgpt](https://user-images.githubusercontent.com/91251307/291619583-726415cd-3a97-4217-9737-03e2de0b2945.gif)

But instead I would like to have something like this (underlying plane):
![002103_pred_t2m_16](https://user-images.githubusercontent.com/91251307/291619832-efd08b33-0f0c-4be0-81e3-6c52f1427eb3.gif)

**Comment by bottler** [comment]
You can construct the plane as a mesh with two triangles. Then each time you want to render the body mesh you will use pytorch3d.structures.join_meshes_as_scene to make a mesh of the body plus the plane and then you render that.

See https://github.com/facebookresearch/pytorch3d/blob/main/pytorch3d/structures/meshes.py#L1707
