### ISSUE TITLE
Is there a way to use my own images in "Fit a mesh via rendering"?

### ISSUE THREAD

**Issue by hadillivvy** [facebookresearch/pytorch3d#1705]
I ran the demo provided in the collab (https://pytorch3d.org/tutorials/fit_textured_mesh) to fit a mesh to images rendered from an input mesh but I want to fit a mesh by providing it my own images (not rendered from a mesh). Is that possible using pytorch3d? I have a way of getting the camera's rotation (R) and translation (T) but I'm not sure how to change the code so that it takes my own images and get silhouette based on these images. Can anyone help?

**Comment by bottler** [comment]
I think you need to work through the tutorial making sure you understand every step. You'll need to construct `target_images` and `target_rgb` from your own images and change a few other things.
