### ISSUE TITLE
Installation error in Mac M3

### ISSUE THREAD

**Issue by ivanlen** [facebookresearch/pytorch3d#1708]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## 🐛 Bugs / Unexpected behaviors
I am trying to install pytorch3d running 
```
MACOSX_DEPLOYMENT_TARGET=10.14 CC=clang CXX=clang++ pip install "git+https://github.com/facebookresearch/pytorch3d.git"
```
or 
```
MACOSX_DEPLOYMENT_TARGET=11.0 CC=clang CXX=clang++ pip install "git+https://github.com/facebookresearch/pytorch3d.git"
```

and installation fails.

In logs I can find lots of errors like this:
```
      /private/var/folders/8c/wl5hy01d5cl7zkcv10tbh9mw0000gn/T/pip-req-build-6ohuoryp/pytorch3d/csrc/pulsar/host/../include/./math.h:90:10: error: use of undeclared identifier 'make_float3'
        return make_float3(a.x * b.x, a.y * b.y, a.z * b.z);
               ^
      /private/var/folders/8c/wl5hy01d5cl7zkcv10tbh9mw0000gn/T/pip-req-build-6ohuoryp/pytorch3d/csrc/pulsar/host/../include/./math.h:111:10: error: use of undeclared identifier 'make_float3'
        return make_float3(
               ^
      /private/var/folders/8c/wl5hy01d5cl7zkcv10tbh9mw0000gn/T/pip-req-build-6ohuoryp/pytorch3d/csrc/pulsar/host/../include/./math.h:127:10: error: use of undeclared identifier 'make_float3'
        return make_float3(
               ^
      12 errors generated.
```

For some reason I am having problems with `make_float3`. Any ideas?

**Comment by bottler** [comment]
I suspect the recent commit https://github.com/facebookresearch/pytorch3d/commit/6b8766080d2c331a05abbddbf3c7332dbb9df791 broke it. Can you try reverting that locally?

We need to work out what the proper fix is for non-cuda builds.

**Comment by ivanlen** [comment]
Yes, thanks. I was able to install it from commit [c373a84](https://github.com/facebookresearch/pytorch3d/commit/c373a84400328d9236226b6aef40bb2bde413cd0).

Happy to test any new release in mac. Just ping me.

**Comment by MrBenGriffin** [comment]
I had the same problem. Install worked following ivanlen but I also had to find the ninja build file, run ninja manually, and then it was ok.

**Comment by bottler** [comment]
This should be fixed on main now, by https://github.com/facebookresearch/pytorch3d/commit/3621a36494db27336a89503dded7ca896bb059d7 .
