### ISSUE TITLE
Hi guys!Could anybody help me with the warning"integer conversion resulted in a change of sign"?

### ISSUE THREAD

**Issue by mswwd** [facebookresearch/pytorch3d#1711]
## 🐛 Unexpected behaviors
While installing pytorch3d,I got a warning"integer conversion resulted in a change of sign",whereas "the warnings can be suppressed with "-diag-suppress <warning-number>" ".Does the warning make a difference in using pytorch3d?

here are the details:

The warnings can be suppressed with "-diag-suppress <warning-number>"
E:\anacoda\envs\pytorch3d\Lib\site-packages\pytorch3d-0.7.5\pytorch3d\csrc\knn knn.cu(500)  warring:integer conversion resulted in a change of sign
if (p2_idx == -1) {

**Comment by bottler** [comment]
This warning doesn't matter but I agree it should be fixed.
