### ISSUE TITLE
Mesh gets cut while rendering

### ISSUE THREAD

**Issue by abhimanyuchadha96** [facebookresearch/pytorch3d#1714]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## 🐛 Bugs / Unexpected behaviors

As seen in the images below, the mesh gets cut while getting rendered from different angles.

GLB file in viewer:-

<img width="802" alt="Screenshot 2024-01-08 at 2 49 49 PM" src="https://github.com/facebookresearch/pytorch3d/assets/37940438/15c4a7fd-beb4-4437-8876-90c19337d27a">

Rendered Image from PyTorch3D:-
![render_1](https://github.com/facebookresearch/pytorch3d/assets/37940438/60325572-62bb-4a07-8164-5f4ce7fa0a5a)
![render_2](https://github.com/facebookresearch/pytorch3d/assets/37940438/abf5e862-ceb2-491a-9740-5b975b38568a)

NOTE: Please look at the existing list of Issues tagged with the label ['bug`](https://github.com/facebookresearch/pytorch3d/issues?q=label%3Abug). **Only open a new issue if this bug has not already been reported. If an issue already exists, please comment there instead.**.

## Instructions To Reproduce the Issue:

`R, T = look_at_view_transform(elev=50, dist=230, azim=180)`
Tried other options like `at = ((1, 1, 1),) `but the results were the same.

All other camera parameters are default taken from https://colab.research.google.com/github/facebookresearch/pytorch3d/blob/stable/docs/tutorials/render_textured_meshes.ipynb#scrollTo=CDQKebNNfBMI

**Comment by bottler** [comment]
Can you try playing with the znear and zfar inputs to the init of the FoVPerspectiveCameras ? Things too near or too far from the camera are deliberately ignored, but you can change what is "too near/far".
