### ISSUE TITLE
how to use nerf in projects/nerf?

### ISSUE THREAD

**Issue by lancibe** [facebookresearch/pytorch3d#1716]
- I have some problems in using nerf.
- First, I can train and test the 'lego' examples using train\_nerf.py and test\_nerf.py.
- However, when I use my dataset (I have made the data format like lego's), I encounter two problems:
    1. When training, I can decrease the losses to about 0.016, while lego's can be less than 0.003.
    2. When testing, I choose the 'export\_video' mode, but I can only get full black images.
- You have any solutions please?

**Comment by bottler** [comment]
This seems to be a modelling question rather than a software question, and we can't really help.
