### ISSUE TITLE
Camera position optimisation 'diverging' issue.

### ISSUE THREAD

**Issue by arv8315** [facebookresearch/pytorch3d#1717]
I have taken the camera position optimisation with differentiable rendering notebook and made efforts to adapt it as follows given my circumstances. My circumstances are that I have a 3D model (.obj) and a corresponding 2D target image of that 3D model (rather that having to make one. I do not want to do that and use my a-priori 2D images). I want to determine the camera pose for that 2D image which I do not have. 

1. Here is my 3D object's 2D image raster:
![image](https://github.com/facebookresearch/pytorch3d/assets/11643561/628bd391-beaf-428e-8ca0-1e41605bcc49)

3. Here is the same object resized with background removed. (Lots of background removal tools out there). I used opencv to load the image, used numpy.pad to resize the image and then removed the background. Here is the outcome.

![image](https://github.com/facebookresearch/pytorch3d/assets/11643561/9a8d7e16-e63d-4f96-bcba-c21b03d5df7b)

using cv2 results in the img being loaded being a numpy.ndarray by default. I simply had to call expand_dims to end up with a shape of (1, 256, 256, 4) which is the same as the reference image. I also introduced an alpha channel to make it 4 channels rather than 3 like the reference image had by default. Now, in place of the original reference image, I substituted in my numpy array. Then, when I ran the code that compares the starting point with reference image silhouette, obtained the following:
![image](https://github.com/facebookresearch/pytorch3d/assets/11643561/9dc6f20e-392f-4194-b3e1-82b2224db42f)

Note that I had to change the Model code to remove all zeros (blacks) instead of whites (1)

However, when I run the optimisation, it ends up shrinking and not iteratively improving the camera pose until it matches the one that would have resulted in the target silhouette. So far not sure why this is happening. Any suggestions?

![image](https://github.com/facebookresearch/pytorch3d/assets/11643561/859eeaff-ebec-4bd6-86b9-7d02ff6d0348)

**Comment by arv8315** [comment]
Is the artefact around the edge of the silhouette confusing the solver? I will attempt to remove that artefact and try again.

**Comment by bottler** [comment]
I'm afraid this is a modelling question rather than a software question and we probably can't help.

**Comment by arv8315** [comment]
Oh, it got closed! Finding equivalency between pre-existing images and the rendered reference image  (e.g. silhouette match) might help if there is solver limitation with using images other than the other generated via reference to the 3D model itself (like what is there in this tutorial). If the equivalency is found, can use the rendered camera views now. The solver works when working with the rendered camera views.

**Comment by arv8315** [comment]
Perhaps then, it is solving it twice. anyhow, know what to try out
