### ISSUE TITLE
How to do ray casting on meshes / point clouds / voxels?

### ISSUE THREAD

**Issue by poodarchu** [facebookresearch/pytorch3d#1721]
is there any function in pytorch3d that can implement operations similar to ray casting (omit some rays from an origin to some meshes / point clouds, then return the index where intersection)?

**Comment by bottler** [comment]
If your `some rays` are all the pixels in some camera object (either one of our simple ones or a specialised one you might make) then yes, that's exactly what our rasterizers do. The idea is that your object can be moved into screen space and then the rasterizer doesn't need to know anything about the viewpoint.

But in general, I don't think so. Our rasterizers can't work with an arbitrary ray bundle object.

**Comment by bottler** [comment]
(You mention voxels in the title as well. For that implictron has a lot of functionality for ray casting from an arbitrary ray bundle.)
