### ISSUE TITLE
Ray tracing and roadmap to the future

### ISSUE THREAD

**Issue by HongLouyemeng** [facebookresearch/pytorch3d#1726]
## 🚀 Feature

Real-time ray tracing has ignited a wave of movie and TV-grade gaming. torch3D is based on torch and implements cuda acceleration on data structures, multiple algorithms, but rasterization looks like it's entering its endgame at the moment.

## Motivation

I noticed that in 2020 there were 2 questions mentioning ray tracing, now after 4 years I have researched the code structure of pytorch3D and I found that the functionality is still relatively less, I would like to ask what is the goal of torch3D, is it used as a rendering pipeline, is it or is it used as a tool for 3D Deep Learning, and will it support state-of-the-art rendering methods in the future.
## Pitch

NOTE: we only consider adding new features if they are useful for many users.

**Comment by bottler** [comment]
There are no current plans to make big updates to mesh rendering, e.g. adding ray tracing.
