### ISSUE TITLE
Change Color of Mesh Vertices? with torch.ones_like(verts)[None]?

### ISSUE THREAD

**Issue by karim-eladl** [facebookresearch/pytorch3d#173]
Hi! I have a super quick question but somehow I can't figure it out based on the tutorials and forums.

I'm rendering a set of objects that are saved as one set of vertices and faces but are not connected. I'd like to set one of these objects to be not white.

I'd use verts_rgb = torch.ones_like(verts[0:100])[None] to set vertices 0 through 100 to white. How do I set say verts[101:200] to another color?

Thank you so much!

**Comment by bottler** [comment]
Do you want something like
```
verts_rgb = torch.ones_like(verts)[None]
verts_rgb[0,101:200,:]=torch.tensor([red_level, green_level, blue_level])
```

**Comment by karim-eladl** [comment]
yes thank you!
