### ISSUE TITLE
result from `marching_cubes` has identical vertex indices

### ISSUE THREAD

**Issue by Khoa-NT** [facebookresearch/pytorch3d#1731]
## 🐛 Bugs / Unexpected behaviors

The result from marching_cubes on  GPU is not correct

## Instructions To Reproduce the Issue:

pytorch3D installed from commit c292c71
Previous test result is in https://github.com/facebookresearch/pytorch3d/issues/1641#issuecomment-1913169684

```python
import torch
from pytorch3d.ops.marching_cubes import marching_cubes, marching_cubes_naive
from pytorch3d.io import save_obj

from skimage import measure
from skimage.draw import ellipsoid

# Generate a level set about zero of two identical ellipsoids in 3D
ellip_base = ellipsoid(50, 60, 16, levelset=True)
ellip_base_pt = torch.from_numpy(ellip_base).unsqueeze(0).float() # (N, D, H, W)


### 1) Run on CPU with marching_cubes_naive
verts_cpu_naive, faces_cpu_naive = marching_cubes_naive(ellip_base_pt, 0)
save_obj('marching_cubes_naive.obj', verts_cpu_naive[0], faces_cpu_naive[0])

### 2) Run on CPU with marching_cubes
verts_cpu, faces_cpu = marching_cubes(ellip_base_pt, 0)
save_obj('marching_cubes_cpu.obj', verts_cpu[0], faces_cpu[0])

### 3) Run on CUDA with marching_cubes
verts_cuda, faces_cuda = marching_cubes(ellip_base_pt.cuda(), 0)
save_obj('marching_cubes_cuda.obj', verts_cuda[0], faces_cuda[0])
```

View from meshlab

### 1) Run on CPU with marching_cubes_naive
![image](https://github.com/facebookresearch/pytorch3d/assets/12138158/0366a4dc-8b0c-4556-be1d-f3a2d7725a73)

### 2) Run on CPU with marching_cubes
![image](https://github.com/facebookresearch/pytorch3d/assets/12138158/62dd368a-b799-472d-8c46-b87f68e3cd66)

### 3) Run on CUDA with marching_cubes
<img width="459" alt="image" src="https://github.com/facebookresearch/pytorch3d/assets/12138158/48aecb90-8494-481a-bb77-1139e662e6c2">

![image](https://github.com/facebookresearch/pytorch3d/assets/12138158/e78740f8-7f3d-4173-a6d1-7502dd61723c)

**Comment by roym899** [comment]
I have the same problem on `0.7.6`

**Comment by JaapSuter** [comment]
I believe this to be fixed by https://github.com/facebookresearch/pytorch3d/commit/7566530669203769783c94024c25a39e1744e4ed, I ran your repro locally and it succeeded. Do let me know if it's still broken for you. Thanks!

**Comment by roym899** [comment]
I can confirm this is working again on main.
