### ISSUE TITLE
Reflective Cylinder

### ISSUE THREAD

**Issue by VaibhavSanjay** [facebookresearch/pytorch3d#1732]
I am trying to render a cylinder with reflective properties into Pytorch3D. I would like to be able to render it with other objects in the scene, so I can see their reflections in the cylinder based on the position of the camera (Like a mirror). 

Since my cylinder does not have a texture, I am not even able to render it in Pytorch3D. Adding any texture (such as a single color one) makes it so the reflective property isn't active. 
![image](https://github.com/facebookresearch/pytorch3d/assets/39975088/a17d30b2-e919-470b-9de3-838be1c7651e)

I have attached the cylinder obj and mtl I created in Blender. It appears reflective in Blender. How can I make it so that this cylinder can be rendered and is reflective in Pytorch3D?
[cylinder.zip](https://github.com/facebookresearch/pytorch3d/files/14319937/cylinder.zip)

**Comment by bottler** [comment]
This isn't supported in PyTorch3D - e.g. there is no raytracing for meshes.
