### ISSUE TITLE
windows 10 install problem

### ISSUE THREAD

**Issue by karaokenoway** [facebookresearch/pytorch3d#1742]
hi, i use cuda 11.8 pytorch 2.0.1 and install pytorch3d from local clone in windows10. 
It failed with this:
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8/include\cub/device/dispatch/dispatch_segmented_sort.cuh(338): error: invalid combination of type specifiers

C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8/include\cub/device/dispatch/dispatch_segmented_sort.cuh(338): error: expected an identifier

C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8/include\cub/device/dispatch/dispatch_segmented_sort.cuh(379): error: expected a member name

3 errors detected in the compilation of "F:/Github/AdaMPI/pytorch3d-0.7.4/pytorch3d-0.7.4/pytorch3d/csrc/pulsar/cuda/renderer.backward.gpu.cu".
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.8\\bin\\nvcc.exe' failed with exit code 2

what should i do plz!

**Comment by bottler** [comment]
Please see https://github.com/facebookresearch/pytorch3d/issues/1567 and https://github.com/facebookresearch/pytorch3d/issues/1631.

**Comment by karaokenoway** [comment]
Thanks @bottler , I have add the flag  to the nvcc_args in setup.py. like  #1567  but it still don't work. 
i also change the cub for 1.17.2 but it comes the same error....

**Comment by bottler** [comment]
We're going to be able to help much. Are you on the latest version of Visual Studio?

**Comment by karaokenoway** [comment]
I use vs2019

**Comment by bottler** [comment]
Recently people have been reporting successes with 2022. eg #1659

**Comment by karaokenoway** [comment]
After using pytorch3d 0.7.5 and with cuda11.8, it's ok right now. i even don't why, but it works, thanks!
