### ISSUE TITLE
Prebuilt wheels for python 3.10 ?

### ISSUE THREAD

**Issue by Ruishenl** [facebookresearch/pytorch3d#1748]
Is there any prebuilt wheels for python 3.10 with cuda ? If my environment uses python3.10 + cuda 11.8,  what is the best way to install pytorch3d ?
I've been trying to build my environment with pre-built wheels like https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py310_cu118_pyt210/pytorch3d-0.7.5-cp310-cp310-linux_x86_64.whl, but i haven't been able to find a download link for a newer version. Is there any plan to release more pre-built wheels for cuda environment ?

**Comment by bottler** [comment]
Please use conda if you possibly can. It is the recommended and supported installation method. The wheels only really exist for convenience on google colab. There's a list of wheels available in #1401 .

**Comment by MiroPsota** [comment]
You can try my repository for building packages and PyPI simple index and see if it works for you:
https://github.com/facebookresearch/pytorch3d/discussions/1752
