### ISSUE TITLE
lighting clone returns hardcoded class type - prohibits inheritance 

### ISSUE THREAD

**Issue by yifita** [facebookresearch/pytorch3d#178]
## 🐛 Bugs / Unexpected behaviors
`lighting.py`'s `clone` methods hardcoded its class. 
https://github.com/facebookresearch/pytorch3d/blob/686c8666d31d932ed42d3cd7319f249fc75e89a9/pytorch3d/renderer/lighting.py#L188
This prohibits the developers to create a child class which calls `super().clone(other)`.

## Instructions To Reproduce the Issue:

1. Create child class
```
from pytorch3d.renderer import lighting
class ChildLighting(lighting.DirectionalLights):
    {some code overriding e.g. diffuse method}

```

2. The exact command(s) you ran:
```python
lights = ChildLighting()
new_lights = lights.clone()
isinstance(new_lights, type(lights))
```
3. What you observed (including the full logs):
`new_lights` is an instance of the parent `DirectionalLights` instead of the modified child class...

**Comment by nikhilaravi** [comment]
@yifita thanks for pointing this out. I will look at your PR.

**Comment by yifita** [comment]
Thanks!
BTW i don't think this issue is an "enhancement".  It surely looks like a bug to me.

**Comment by yifita** [comment]
I'm sorry to reopen this, I just found similar patterns in
`meshes.py`, `pointclouds.py` etc. So probably all the clone method should be updated with the same fix? 

Sorry, i'm not sure whether i should open an new issue or reopen this one.

**Comment by bottler** [comment]
Do you actually want to inherit from those classes? They are not designed to be inherited from.

It would be interesting to hear what you are trying to do.

**Comment by yifita** [comment]
Yeah I'm trying to inherit those to create some auxiliary functions such as batchwise rotation, preprocessing of points before before initialization.

I'd also like to augment the `lighting.py`, so that multiple light sources for each batch is allowed.

I think regardless of what the users' intention is, since python language allows inheritance, then the pytorch3d classes should also behave according to convention...
