### ISSUE TITLE
How to continuous control of the camera based on the R_init and T_init.

### ISSUE THREAD

**Issue by aruiplex** [facebookresearch/pytorch3d#1791]
## ❓ Questions on how to use PyTorch3D to continuous control of the camera.

Based on the initial Camera `R`, `T`, I want to use the `r`, `elev`, and `azim` to control the camera around the object.

I make my question to the figure, making it more easy to understand. 

![Frame 1 (1)](https://github.com/facebookresearch/pytorch3d/assets/40193711/5dba2ec9-ce5a-4349-9d49-e5941381f9f5)

**Comment by bottler** [comment]
The camera_to_eye_at_up function and its docstring should explain enough: see https://github.com/facebookresearch/pytorch3d/blob/main/pytorch3d/renderer/camera_utils.py#L17 .
