### ISSUE TITLE
Any plan to support `torch.func`?

### ISSUE THREAD

**Issue by xhsonny** [facebookresearch/pytorch3d#1796]
I am trying to compute full jacobian using `jacrev` or `jacfwd` from `torch.func`.  Part of the loss function uses `_PointFaceDistance`. Out of the box, `pytorch3d` does not support `torch.func`. The closest references I can find so far are https://github.com/facebookresearch/pytorch3d/issues/1636 and https://github.com/facebookresearch/pytorch3d/issues/1533. 

The problems I am having are
- With `jacrev`, it throws an exception `RuntimeError: Cannot access data pointer of Tensor that doesn't have storage` at the line of `_C.point_face_dist_backward`.
      - I followed https://github.com/facebookresearch/pytorch3d/issues/1533 and implemented `vmap` for `_PointFaceDistance`, but `jacrev` still hits the line of `_C.point_face_dist_backward` first, so same error. #1533 happened in the forward path, so actually same error but different cause.
- with `jacfwd`, it throws an exception of missing `jvp` method.
      - I don't quite know how to implement `jvp` as I have not found much info on what exactly should go in to this function.

The only working method is to call `torch.autograd.functional.jacobian(vectorize=False)` which is very slow. And when turn on `vectorize=True`, it runs into the same issues as above.

My questions are:
1. is there a plan to officially support `torch.func` ? If I can get some guidance from `pytorch3d` team, I am happy to collaborate on this. 
2. Any idea how to make this work? Any workarounds?

Thanks!

**Comment by bottler** [comment]
We aren't planning torch.func support. It seems to me that the method in #1533 should work fine for _PointFaceDistance - feel free to post the code you have and maybe we can figure out what's wrong.

**Comment by xhsonny** [comment]
@bottler Thanks for the reply!

The error msg `"RuntimeError: Cannot access data pointer of Tensor that doesn't have storage"` from #1533 happened in the forward pass `"idx, dists = _C.knn_points_idx(p1, p2, lengths1, lengths2, norm, K, version)`. I don't know how #1533 is computing the jacobian. In my case, neither forward mode nor backward mode work with following errors:

- With backward mode `jacrev`, the same error msg happens at the time when calling `_C.point_face_dist_backward` inside of `backward`.
- With forward mode `jacfwd`, it complains about missing `jvp` method.

I did follow #1533 to modify the class with `setup_context` etc. I also added `vmap` but `vmap` method is never called before hitting two errors above.

**Comment by TimoRST** [comment]
Just in intuition based on the traceback, especially here:

> File "/usr/local/anaconda3/envs/pytorch3d_torch2_v2/lib/python3.10/site-packages/theseus/core/cost_function.py", line 341, in _compute_autograd_jacobian_vmap
>     return vmap(jacrev(jac_fn, argnums=0))(optim_tensors, aux_tensors)

I think that jac_fn will be called in the same way that the forward path is called with vmap. So, there might be an error in the jac_fn function's vmapping, which you might specify in the same way as you did for the forward path.

**Comment by xhsonny** [comment]
@TimoRST Thanks for the inputs! I never thought of it and will look into it.

Just one follow up, `jac_fn` is either the `cost_function` which is  `th.AutoDiffCostFunction` or the `error_fn` I wrote that I used to compute the loss values. Do you know how to add `vmap` to those functions? They are not `torch.autograd.Function`.

Thanks!

**Comment by TimoRST** [comment]
I don't know that. I would first debug into that function to see if it really is called with those batched tensors which cause the error. 
After verifying you might just make an autodiff function out of that function?

**Comment by xhsonny** [comment]
@TimoRST Thanks. I will try it out.

Can I ask what your use case was to use `knn` and `theseus`? Was it also used in the context of an optimization that needed a jacobian?

Thanks!

**Comment by TimoRST** [comment]
I wanted to implement something like WGICP (https://arxiv.org/abs/2209.09777), but I couldn't scale it because my graphics card was too small, so I didn't get comparable results. 
I didn't use the Jacobian, so it was enough to ensure correct vmapping in the forward path.

**Comment by xhsonny** [comment]
Here are some findings. Conclusion: `_C.point_face_dist_backward` cannot take in `grad_dists` that is a 2D `BatchedVector` which is created by `vmap/jacrev`.

- When calling `torch.autograd.functional.jacobian`, it computes jacobian row-by-row. `grad_dists` is a 1D vector. Everything works fine.
- When calling `jacrev`, internally it uses `vmap`, and it makes `grad_dists` to be a batched version, meaning 2D `BatchedVector`, which makes sense because the vectorized version pushes the for loop into C++ code. And `_C.point_face_dist_backward` is called with this kind of 2D `grad_dists`, it throws `RuntimeError: Cannot access data pointer of Tensor that doesn't have storage`.

Here is a hacked version to verify my point though the math is probably wrong. When using `jacrev`, "un-vmap" the `v_grad_dists` and hack it with a for loop to compute row-by-row. It works fine. Then when it returns, `pytorch3d` complains the returned `grad_points` has wrong shape.
```
 @staticmethod
    @once_differentiable
    def backward(ctx, grad_dists, grad_idxs):
        grad_dists = grad_dists.contiguous()
        points, tris, idxs = ctx.saved_tensors
        min_triangle_area = ctx.min_triangle_area

        # https://discuss.pytorch.org/t/save-batchedtensor-to-a-pickle-file/170561/4
        v_points = torch._C._functorch.get_unwrapped(points)
        v_tris = torch._C._functorch.get_unwrapped(tris)
        v_idxs = torch._C._functorch.get_unwrapped(idxs)
        v_grad_dists = torch._C._functorch.get_unwrapped(grad_dists)

        grad_points = []
        grad_tris = None
        for v_grad_dists_v in v_grad_dists:
           v_grad_points, v_grad_tris = _C.point_face_dist_backward(
               v_points, v_tris, v_idxs, v_grad_dists_v, min_triangle_area
           )
           grad_points.append(v_grad_points)
           if grad_tris is not None:
               grad_tris = grad_tris + v_grad_tris
           else:
               grad_tris = v_grad_tris

        grad_points = torch.cat(grad_points, dim=1)
        return grad_points, None, grad_tris, None, None, None
```

@bottler would you be able to confirm what I said above is correct? And if this is the case, it seems changing internal code of `_C.point_face_dist_backward` is the only option?

Thanks!

**Comment by bottler** [comment]
I don't know enough I'm afraid about functorch
