### ISSUE TITLE
knn_points - different return values order in code vs. documentation

### ISSUE THREAD

**Issue by mbanani** [facebookresearch/pytorch3d#180]
Hello, just a heads up, I noticed that the return values of [knn_points](https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/ops/knn.py#L89) don't match the documentation. Specifically, it returns `p1_dists, p1_idx, p2_nn` while the documentation indicates the ordering is `p1_idx, p1_dists, p2_nn`.

**Comment by nikhilaravi** [comment]
@mbanani thanks for pointing this out. The output of `knn_points` is actually [named tuple](https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/ops/knn.py#L12) which has fields `dists`, `idx` and `knn`. 

If you don't access thee values via the named tuple, you can still get the three values as 
`dist, idx, nn = knn_points(...)` and you are correct that in this case the documentation for the return values of this function has the values in the wrong order.

Feel free to make a PR to fix this documentation or we can add a TODO to fix it.
