### ISSUE TITLE
How to add a spot light (cone light) in PyTorch3D for projecting a 2D pattern onto 3D surfaces?

### ISSUE THREAD

**Issue by SherlockSimon** [facebookresearch/pytorch3d#1816]
or how to simulate a projector (a reverse camera) in PyTorch3D?

**Comment by SherlockSimon** [comment]
or how to simulate a projector (a reverse camera) in PyTorch3D?

**Comment by ForrestPi** [comment]
same question

**Comment by bottler** [comment]
There's no functionality for this - it would have to be done from first principles I think. I can't help.
