### ISSUE TITLE
how to apply pytorch3d to reconstruct 3d face pointclouds using the rgb and deepmap of one face (both got from pytorch3d)

### ISSUE THREAD

**Issue by yxwktdk** [facebookresearch/pytorch3d#1828]
I have got the rgb as well as deepmap of a face by the following code:
```R, T = look_at_view_transform(dist=2.0, elev=0, azim=180,up=((0, -1, 0),)) 
cameras = PerspectiveCameras(device=device, R=R, T=T)

raster_settings = RasterizationSettings(
    image_size=1024, 
    blur_radius=0.0, 
    faces_per_pixel=1, 
)

lights = PointLights(device=device, location=[[0.0, 0.0, -3.0]])

rasterizer = MeshRasterizer(
        cameras=cameras, 
        raster_settings=raster_settings
    )
renderer = MeshRendererWithDepth(
    rasterizer,
    shader=SoftPhongShader(
        device=device, 
        cameras=cameras,
        lights=lights
    )
)

images, depths = renderer(mesh)
```
And now I want to use these information for reconstructing a face pointcloud. Can I realize this with Pytorch3d? If not, other method may need the information of camera like'scaling factor',how can I get scaling factor of the camera? Please help me solve this question, thanks!

**Comment by yxwktdk** [comment]
`help`

**Comment by bottler** [comment]
RGBD images can be converted to pointcloud with `get_rgbd_point_cloud` from `pytorch3d.implicitron.tools.point_cloud_utils` . But if you have the mesh you may prefer to use sample_points_from_meshes. "scaling factor" may mean different things in different places - you need to look at the camera classes themselves.
