### ISSUE TITLE
ModuleNotFoundError: No module named 'pytorch3d.structures'

### ISSUE THREAD

**Issue by nothonfz** [facebookresearch/pytorch3d#1836]
![947037b9d49b08b16e5756add18e097](https://github.com/user-attachments/assets/7659eb0c-4cfb-408f-81a1-d38ece93b543)

I create a env named step10 with python 3.9.

I use pip install torch==2.1.0 torchvision==0.16.0 torchaudio==2.1.0 --index-url https://download.pytorch.org/whl/cu121 to install pytorch. 
And I install the pytorch3d from source with following commands
1. conda install -c fvcore -c iopath -c conda-forge fvcore iopath
2. cd pytorch3d
3. pip install -e .

Finally, the pytorch3d of version 0.7.7 exists in my env.
![1721119845470](https://github.com/user-attachments/assets/76f7d011-1e09-4dd5-b6fe-bd8cdc65f907)

But when the code imports the Module, it failed.
![73dbad806ed016d6d4e527cf2a04fc4](https://github.com/user-attachments/assets/8f1d3c6c-e4de-4823-8dc6-772491c97172)

Has anyone encountered this problem?

**Comment by bottler** [comment]
Something very basic has gone wrong, maybe the environment has changed. I suggest rebuilding the environment.
