### ISSUE TITLE
the normal map is different form blender normal map

### ISSUE THREAD

**Issue by yejr0229** [facebookresearch/pytorch3d#1840]
I use the phong_normal_shading() to render a normal map:

```
def phong_normal_shading(meshes, fragments) -> torch.Tensor:
    faces = meshes.faces_packed()  # (F, 3)
    vertex_normals = meshes.verts_normals_packed()  # (V, 3)
    faces_normals = vertex_normals[faces]
    pixel_normals = interpolate_face_attributes(
        fragments.pix_to_face, fragments.bary_coords, faces_normals
    )
    return pixel_normals
```

and I get:
![image](https://github.com/user-attachments/assets/5422f81a-2af5-433f-b40b-fc2953f03fd1)

But the colormap it's different from the controlnet normal map:
![image](https://github.com/user-attachments/assets/17076368-775e-40f5-98df-59a9cd207788)

how can I render a normal like controlnet in pyorch3d?

**Comment by bottler** [comment]
There's probably some simple mapping between the two versions of the color channels. I think you are best positioned to work this out manually for yourself, maybe by looking at some values.

**Comment by yejr0229** [comment]
Thanks for replying, could you please tell me how to find this mapping more specially?

**Comment by bottler** [comment]
@yejr0229 (Please do not repost this question on other issues.) Your question is not specifically about PyTorch3D, and you shouldn't expect an answer here. It's an arithmetic question. We won't help. You could investigate the specific definition of the controlnet normal map, but more productive would just be to look at values.
