### ISSUE TITLE
Does pytorch3d work with python3.11?

### ISSUE THREAD

**Issue by Ryang20718** [facebookresearch/pytorch3d#1842]
## ❓ Questions on how to use PyTorch3D

When will pytorch3d work with python3.11/ What would be needed to support python3.11?

Based on install https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md#core-library, I see pytorch3d only supports 3.10.

When will pytorch3d support python3.11?

On python 3.11 I see
```
from pytorch3d import _C
....
ImportError: undefined symbol: _ZNK3c105Error4whatEv
```

**Comment by Ryang20718** [comment]
On python3.10, everything just works :)

**Comment by Khoa-NT** [comment]
It looks like `iopath` only supports python 3.9
![image](https://github.com/user-attachments/assets/ab193db4-365e-44fe-833b-b6a26acd5f78)
