### ISSUE TITLE
How to save mesh as tetrahedron in pytorch3d?

### ISSUE THREAD

**Issue by yejr0229** [facebookresearch/pytorch3d#1844]
I use the QuadriFlow(https://github.com/hjwdzh/QuadriFlow?tab=readme-ov-file#quadriflow-a-scalable-and-robust-method-for-quadrangulation) to transfer a triangle mesh to tetrahedron with quad_idx. 
Before I ues save_obj() to save triangle mesh:
![image](https://github.com/user-attachments/assets/97867532-9326-4716-a321-b7239dd7f154)
Now how can I pass the 'quad_idx' parameters to this function and save a quad mesh?

**Comment by bottler** [comment]
PyTorch3D's meshes are only triangular meshes. You might be able to adapt code from that file, but what you want to do is not supported.
