### ISSUE TITLE
Does PyTorch3D support AMD Radeon W7900? (gfx1100)

### ISSUE THREAD

**Issue by yttbgf** [facebookresearch/pytorch3d#1845]
Does PyTorch3D support AMD Radeon W7900? (gfx1100) 
I see the code include at::cuda::CUDAGuard (*.cu) and commands.h include #include <cub/cub.cuh>
I want to know whether is can port to AMD ROCm with HIP?
Does it use inline assemble (asm） or OPENGL like nvdiffrast-main

**Comment by bottler** [comment]
Inline assembly is not used. The compiled parts of pytorch3d do not use opengl, but there is a mesh renderer in python which uses opengl. AMD is not supported but you might be able to get it to work.
