### ISSUE TITLE
A valid wheel for the current colab?

### ISSUE THREAD

**Issue by colt18** [facebookresearch/pytorch3d#1848]
Hi,
There seems no prebuilt wheels for the current colab (August,2024) as the installation script installs from source and it takes eternity on colab instances? Neither downgrading python version on colab is a smooth process. Any tips on this?

**Comment by bottler** [comment]
Should work now - I just pushed a wheel for py310_cu121_pyt231

**Comment by kira-pareser** [comment]
> Should work now - I just pushed a wheel for py310_cu121_pyt231

can you redirect you update here pls? i can't find it

**Comment by bottler** [comment]
@py310_cu121_pyt240

**Comment by bottler** [comment]
done
