### ISSUE TITLE
Compatibility Issues with PyTorch3D, GCC, and CUDA on Red Hat Linux

### ISSUE THREAD

**Issue by Razbolt** [facebookresearch/pytorch3d#1850]
## 🐛 Bugs / Unexpected behaviors

Hello PyTorch3D Team,

I am experiencing compatibility issues with PyTorch3D when using different versions of GCC and CUDA on a Red Hat Linux system. Depending on the GCC and CUDA versions loaded, I encounter different problems that prevent PyTorch3D from working properly.

Environment Details:
Operating System: Red Hat Linux (exact version)
Python Version: 3.10

CUDA Version: 11.2
GCC Versions: Tested with 10.3 and 11.2
PyTorch3D Version: Installed directly from the GitHub repository

## Issue Description
- With CUDA 11.2 AND GCC 10.3
 Error Message :` ImportError: /opt/gridware/depots/b26e1471/el7/pkg/compilers/gcc/10.3.0/lib64/libstdc++.so.6: version GLIBCXX_3.4.29' not found (required by /users/adfx762/.pyenv/versions/nfr_env/lib/python3.10/site-packages/pytorch3d/_C.cpython-310-x86_64-linux-gnu.so)
`
- With Cuda 11.2 AND GCC 11.2
Error Message :  `[Output indicating module loading and unloading]
...
RuntimeError: Error building extension 'fused': [1/2] /opt/gridware/depots/b26e1471/el7/pkg/libs/nvidia-cuda/11.2.0/bin/bin/nvcc ...
[Error details]
/opt/gridware/depots/b26e1471/el7/pkg/libs/nvidia-cuda/11.2.0/bin/include/crt/host_config.h:139:2: error: #error -- unsupported GNU version! gcc versions later than 10 are not supported! `

Context: This error occurs because CUDA 11.2 does not officially support GCC versions later than 10. The error message explicitly warns against using GCC versions later than 10 and suggests using the -allow-unsupported-compiler flag as a risky workaround.
Note: I've already tried flagging -allow-unsupported-compiler and it does not work at all !

**Following .sh script is used:**

 #!/bin/bash
#SBATCH --job-name reenact
#SBATCH --partition=preemptgpu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=90GB
#SBATCH --time=48:00:00
#SBATCH --gres=gpu:1
#SBATCH -e results/%x_%j.e
#SBATCH -o results/%x_%j.o
#SBATCH --error reenact.err
#SBATCH --output reenact.output
#SBATCH --constraint=cuda12

source /opt/flight/etc/setup.sh
flight env activate gridware
module purge
module load gnu
module load libs/nvidia-cuda/11.2.0
module load compilers/gcc/10.3.0
module load mpi/openmpi/4.1.1/gcc-10.3.0
export TORCH_CUDA_ARCH_LIST="7.5"
python --version
echo $LD_LIBRARY_PATH
export https_proxy=http://hpc-proxy00.city.ac.uk:3128
python reenact.py --source-image=examples/18128.jpg --target-image=examples/18090.jpg
`

The full log of GCC 11.2 is to long so only attached the GCC 10.3.0

```
  File "/mnt/scratch/users/adfx762/myfolder/NFR-Dataset-Augmentor-dev/reenact.py", line 10, in <module>
    from lib.face_models.landmarks_estimation import LandmarksEstimation
  File "/mnt/scratch/users/adfx762/myfolder/NFR-Dataset-Augmentor-dev/lib/__init__.py", line 8, in <module>
    from lib.deca.estimate_DECA import DECA_model
  File "/mnt/scratch/users/adfx762/myfolder/NFR-Dataset-Augmentor-dev/lib/deca/estimate_DECA.py", line 3, in <module>
    from .decalib.deca import DECA
  File "/mnt/scratch/users/adfx762/myfolder/NFR-Dataset-Augmentor-dev/lib/deca/decalib/deca.py", line 27, in <module>
    from .utils.renderer import SRenderY
  File "/mnt/scratch/users/adfx762/myfolder/NFR-Dataset-Augmentor-dev/lib/deca/decalib/utils/renderer.py", line 23, in <module>
    from pytorch3d.io import load_obj
  File "/users/adfx762/.pyenv/versions/nfr_env/lib/python3.10/site-packages/pytorch3d/io/__init__.py", line 10, in <module>
    from .obj_io import load_obj, load_objs_as_meshes, save_obj
  File "/users/adfx762/.pyenv/versions/nfr_env/lib/python3.10/site-packages/pytorch3d/io/obj_io.py", line 24, in <module>
    from pytorch3d.renderer import TexturesAtlas, TexturesUV
  File "/users/adfx762/.pyenv/versions/nfr_env/lib/python3.10/site-packages/pytorch3d/renderer/__init__.py", line 9, in <module>
    from .blending import (
  File "/users/adfx762/.pyenv/versions/nfr_env/lib/python3.10/site-packages/pytorch3d/renderer/blending.py", line 12, in <module>
    from pytorch3d import _C
ImportError: /opt/gridware/depots/b26e1471/el7/pkg/compilers/gcc/10.3.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /users/adfx762/.pyenv/versions/nfr_env/lib/python3.10/site-packages/pytorch3d/_C.cpython-310-x86_64-linux-gnu.so)
```

## Questions/Requests:

1- Are there known compatibility issues with these versions of GCC and CUDA when used with PyTorch3D?
2- Could you provide guidance or a workaround for using PyTorch3D with GCC versions newer than 10 when CUDA 11.2 is also required?
3- Any recommendations for settings or environment configurations that could resolve these issues?

Thank you for your assistance

**Comment by bottler** [comment]
Which pytorch version(s) are you trying with? This will make a big difference. (It is necessary to ensure this matches between when you build PyTorch3D and run it.) And is pytorch working (e.g. does `import torch; torch.tensor(1, device="cuda:1")` run?).

Can you share your `conda list` if you are using conda?

**Comment by Razbolt** [comment]
Hi @bottler, 

I would rather use pyenv; I can show you the pip freeze so you can have a look at the pytorch version(s) as well with pytorch3D.
Based on other question, I include the following script in .sh `python -c "import torch; print(torch.tensor(1, device='cuda:0'))"`
and the output is tensor `(1, device='cuda:0')`. I reckon Pytorch is working.
Do you have any recommendations on what to do next ?

Following is the output of pip freeze, its a bit long but you can check torch version(s):

asttokens==2.4.1
build==1.2.1
certifi==2024.7.4
charset-normalizer==3.3.2
chumpy==0.70
clip @ git+https://github.com/openai/CLIP.git@dcba3cb2e2827b402d2701e7e1c7d9fed8a20ef1
comm==0.2.2
contourpy==1.2.1
cycler==0.12.1
debugpy==1.8.2
decorator==5.1.1
exceptiongroup==1.2.1
executing==2.0.1
face-alignment==1.4.1
facenet-pytorch==2.5.3
filelock==3.15.4
fonttools==4.53.1
fsspec==2024.6.1
ftfy==6.2.0
fvcore==0.1.5.post20221221
huggingface-hub==0.23.4
idna==3.7
imageio==2.34.2
importlib_metadata==8.0.0
iopath==0.1.10
ipykernel==6.29.5
ipython==8.26.0
ipywidgets==8.1.3
jedi==0.19.1
Jinja2==3.1.4
joblib==1.4.2
jupyter_client==8.6.2
jupyter_core==5.7.2
jupyterlab_widgets==3.0.11
kiwisolver==1.4.5
kornia==0.7.3
kornia_rs==0.1.4
lazy_loader==0.4
llvmlite==0.43.0
MarkupSafe==2.1.5
matplotlib==3.9.1
matplotlib-inline==0.1.7
mpmath==1.3.0
nest-asyncio==1.6.0
networkx==3.3
ninja==1.11.1.1
numba==0.60.0
numpy==1.23.1
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==9.1.0.70
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.20.5
nvidia-nvjitlink-cu12==12.6.20
nvidia-nvtx-cu12==12.1.105
open_clip_torch==2.26.1
opencv-python==4.10.0.84
opencv-python-headless==4.10.0.84
packaging==24.1
parso==0.8.4
pexpect==4.9.0
pillow==10.4.0
platformdirs==4.2.2
portalocker==2.10.0
prompt_toolkit==3.0.47
psutil==6.0.0
ptyprocess==0.7.0
pure-eval==0.2.2
Pygments==2.18.0
pyparsing==3.1.2
pyproject_hooks==1.1.0
python-dateutil==2.9.0.post0
pytorch3d @ git+https://github.com/facebookresearch/pytorch3d.git@51fd114d8b8eed19226870ee7fd12dba1e25d550
PyYAML==6.0.1
pyzmq==26.0.3
regex==2024.5.15
requests==2.32.3
safetensors==0.4.3
scikit-image==0.24.0
scikit-learn==1.5.1
scipy==1.13.1
six==1.16.0
stack-data==0.6.3
sympy==1.13.1
tabulate==0.9.0
termcolor==2.4.0
threadpoolctl==3.5.0
tifffile==2024.7.2
timm==1.0.7
tomli==2.0.1
torch==2.4.0
torchaudio==2.4.0
torchvision==0.19.0
tornado==6.4.1
tqdm==4.66.4
traitlets==5.14.3
triton==3.0.0
typing_extensions==4.12.2
urllib3==2.2.2
wcwidth==0.2.13
widgetsnbextension==4.0.11
xformers==0.0.27.dev850
yacs==0.1.8
zipp==3.19.2

**Comment by bottler** [comment]
You are mixing CUDA 11.2 (for the pytorch3d build) with cuda 12 (in your environment, in your pytorch build I guess). This can't work. If you have to use CUDA 11.2, then I think you should use an old pytorch. If you can use a supported cuda version (like 11.8) then do everything with that perhaps.

**Comment by Razbolt** [comment]
Sorry, I couldn't follow all. Unfortunately, I work under  HPC and don't have administrative access. 

Are you trying to say CUDA 11.2 (toolkit) is incompatible with the CUDA 12 environment? In this case, which Pytorch version do you think would work?

Besides If I can able to upgrade cuda toolkit to 11.8 or upper, would I face with following issue : `/opt/gridware/depots/b26e1471/el7/pkg/libs/nvidia-cuda/11.2.0/bin/include/crt/host_config.h:139:2: error: #error -- unsupported GNU version! gcc versions later than 10 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
  139 | #error -- unsupported GNU version! gcc versions later than 10 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
      |  ^~~~~
ninja: build stopped: subcommand failed.`


In order to make it eaiser for you I also run following scripts to see the outputs as well:
### Job.sh
```
--- run_job.sh--
module purge
module load gnu
module load libs/nvidia-cuda/11.2.0
module load compilers/gcc/11.2.0


module list
python --version
echo "Checking NVCC version:"
nvcc --version
echo "Checking NVIDIA GPU details:"
nvidia-smi
python -c "import torch; print(torch.version.cuda)"
```


### Output 

```
Python 3.10.0
Checking NVCC version:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Nov_30_19:08:53_PST_2020
Cuda compilation tools, release 11.2, V11.2.67
Build cuda_11.2.r11.2/compiler.29373293_0
Checking NVIDIA GPU details:
Sun Aug 11 17:04:29 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Quadro RTX 8000                Off | 00000000:AF:00.0 Off |                    0 |
| N/A   33C    P0              25W / 250W |      0MiB / 46080MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
12.1
```

**Comment by bottler** [comment]
Do you have a module available with cuda 12.2 (look at `module list`?) E.g. something like `module load libs/nvidia-cuda/12.2.0`. That would let you do everything with 12.2. Could you switch to conda and use our prebuilt packages? Could you do the build elsewhere (e.g. in a docker container: you can follow the ideas in https://github.com/facebookresearch/pytorch3d/tree/main/packaging/linux_wheels and you don't need to do that on a GPU machine. Otherwise I think this is beyond what we can help with.

**Comment by Razbolt** [comment]
Hi @bottler,
Unfortunately, I don't see nvidia-cuda/12.2.0 in the module list. I don't have administrative access, but I have requested that it be updated to 12.1. I will let you know once I try with CUDA 12.1 
What shall I do about gcc versions though?
Do you think I will not see any error with the new CUDA version?

**Comment by bottler** [comment]
Ideally, whoever manages the cluster should ensure that when they add a cuda module there is a compiler module compatible with it. They might build and run a cuda example as part of verifying the module.

If you can use docker (or singularity or similar) you might be able to work independently of the cluster admin. 

I don't know whether 12.1 will solve everything.

**Comment by Razbolt** [comment]
> Ideally, whoever manages the cluster should ensure that when they add a cuda module there is a compiler module compatible with it. They might build and run a cuda example as part of verifying the module.
> 
> If you can use docker (or singularity or similar) you might be able to work independently of the cluster admin.
> 
> I don't know whether 12.1 will solve everything.

Do you think I should update it to 12.2  rather than 12.1?

If these don't work, then I will look for a docker solution.

**Comment by bottler** [comment]
12.2 would be ideal, because that is what your nvidia-smi has (i.e. the driver) and is also what latest pytorch has a build for.

**Comment by Razbolt** [comment]
@bottler, Thanks for your help. I have requested an upgrade to 12.2.2, and it's working fine with gcc 11.2.0.
