### ISSUE TITLE
How to use Pytorch3d to render a uv normal map for a given mesh?

### ISSUE THREAD

**Issue by yejr0229** [facebookresearch/pytorch3d#1853]
I wonder how to use Pytorch3d to render a uv normal map for a given mesh? Like this one:
![image](https://github.com/user-attachments/assets/02ca5d90-9765-47eb-a40d-855d7ac7febd)

**Comment by bottler** [comment]
I think you will need to work out the maths for this for yourself. for each face in the mesh, you can find both its normal and it's location in the UV map. The logic for the latter ican be adapted from the centers_for_image function. You can then fill in a colored image with all these data.
