### ISSUE TITLE
Can't install Pytorch3D

### ISSUE THREAD

**Issue by nairouzshehata** [facebookresearch/pytorch3d#1857]
**To reproduce:**
```
conda create -n pytorch3d_env python=3.9
conda activate pytorch3d_env
```

From [here](https://pytorch.org/get-started/previous-versions/) I got the below:
`conda install pytorch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 pytorch-cuda=11.8 -c pytorch -c nvidia`

```
conda install -c fvcore -c iopath -c conda-forge fvcore iopath
conda install -c bottler nvidiacub
```

Then I did `source /path/to/cuda11.8.0/setup.sh` then to double check `nvcc --version`
Got the below:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```
Then I did:
```
export CUDA_HOME=/path/to/cuda11.8.0/
export PATH=$CUDA_HOME/bin:$PATH
export LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH
```

Only then I attempted installing pytorch3d:
`pip install "git+https://github.com/facebookresearch/pytorch3d.git"`

**Sadly the error I'm getting:**
```
 Error limit reached.
      100 errors detected in the compilation of "/tmp/pip-req-build-c9t_rkxj/pytorch3d/csrc/pulsar/cuda/renderer.backward.gpu.cu".
      Compilation terminated.
      error: command '/vol/cuda/11.8.0/bin/nvcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pytorch3d
  Running setup.py clean for pytorch3d
Failed to build pytorch3d
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pytorch3d)

```

**Comment by nairouzshehata** [comment]
conda install pytorch3d -c pytorch3d seems to work instead but I still need to try running the code

**Comment by nairouzshehata** [comment]
**Now getting**
```
Traceback (most recent call last):
  File "/vol/biomedic3/nsm116/Aorta_Repo/downsample_establish_corr_DL.py", line 4, in <module>
    from pytorch3d.loss import (
  File "/vol/biomedic3/nsm116/miniconda3/envs/pytorch3d_env/lib/python3.9/site-packages/pytorch3d/loss/__init__.py", line 10, in <module>
    from .chamfer import chamfer_distance
  File "/vol/biomedic3/nsm116/miniconda3/envs/pytorch3d_env/lib/python3.9/site-packages/pytorch3d/loss/chamfer.py", line 13, in <module>
    from pytorch3d.ops.knn import knn_gather, knn_points
  File "/vol/biomedic3/nsm116/miniconda3/envs/pytorch3d_env/lib/python3.9/site-packages/pytorch3d/ops/__init__.py", line 9, in <module>
    from .ball_query import ball_query
  File "/vol/biomedic3/nsm116/miniconda3/envs/pytorch3d_env/lib/python3.9/site-packages/pytorch3d/ops/ball_query.py", line 12, in <module>
    **from pytorch3d import _C**
ImportError: /vol/biomedic3/nsm116/miniconda3/envs/pytorch3d_env/lib/**python3.9/site-packages/pytorch3d/_C.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN3c1021throwNullDataPtrErrorEv**
```

**Comment by gg22mm** [comment]
conda install pytorch3d -c pytorch3d
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.                                                                                                                                                                                                                                                                                    failed                                                                                                                                                                                                                                                                                                                                     

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pytorch3d -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0']

Your python: python=3.10

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__cuda==12.0=0
  - feature:/linux-64::__glibc==2.31=0
  - feature:|@/linux-64::__cuda==12.0=0
  - python=3.10 -> libgcc-ng[version='>=11.2.0'] -> __glibc[version='>=2.17']
  - pytorch3d -> torchvision[version='>=0.5'] -> __cuda[version='>=11.8']
  - pytorch3d -> torchvision[version='>=0.5'] -> __glibc[version='>=2.17,<3.0.a0']

Your installed version is: 12.0

**Comment by bottler** [comment]
@gg22mm Please paste the whole output of `conda list`. It may also be worth trying `conda install pytorch3d -c pytorch3d -c conda-forge`. Also best to open a new issue.
