### ISSUE TITLE
question of pytorch3d.loss.chamfer_distance

### ISSUE THREAD

**Issue by congyang12345** [facebookresearch/pytorch3d#186]
When I installed pytorch3d（version 0.1.1） and run the program (meshrcnn) in my workstation，everything is OK. But when I installed pytorch 3d (version 0.2.0) in another workstation and run the same program，an error has occurred. 

File "/home/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/pytorch3d/loss/chamfer.py", line 111, in chamfer_distance
    x, x_lengths, x_normals = _handle_pointcloud_input(x, x_lengths, x_normals)
  File "/home/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/pytorch3d/loss/chamfer.py", line 50, in _handle_pointcloud_input
    raise ValueError("Expected lengths to be of shape (N,)")
ValueError: Expected lengths to be of shape (N,)

The other installation and configuration of the two workstations are almost the same, and there is no difference between the programs and dataset in two workstations. Is this due to the different versions of pytorch3d?

**Comment by bottler** [comment]
There are some changes to the chamfer_distance function in version 0.2.0 to cope with heterogenous point clouds. The latest meshrcnn code on github is compatible with both.

**Comment by gkioxari** [comment]
Hi @congyang12345 
The commit https://github.com/facebookresearch/meshrcnn/commit/32dfa7ff9e321b08a250f550ac65b9effd80dd1c in meshrcnn has made the code compatible with the 0.2.0 version of PyTorch3D, which mostly include the change in the chamfer distance.

**Comment by congyang12345** [comment]
@gkioxari @bottler I got it. Thank you!
