### ISSUE TITLE
Issue while Installing pytorch3d from local clone

### ISSUE THREAD

**Issue by roshanbiswanath** [facebookresearch/pytorch3d#1860]
Running the following command leads to error from nvcc
`cd pytorch3d`
`python setup.py install`

Error:

```
16 errors detected in the compilation of "C:/Users/PC/Biswanath/Machine Learning/3D/ROMP_resnet/ROMP/pytorch3d/pytorch3d/csrc/pulsar/cuda/renderer.backward.gpu.cu".
renderer.backward.gpu.cu
```
The Entire Log can be found here
[log.txt](https://github.com/user-attachments/files/16847132/log.txt)

My NVCC version is
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Fri_Jun_14_16:44:19_Pacific_Daylight_Time_2024
Cuda compilation tools, release 12.6, V12.6.20
Build cuda_12.6.r12.6/compiler.34431801_0
```

And CUDA version is 12.6

My PyTorch Installation is
torch==2.4.0+cu124
torchaudio==2.4.0+cu124
torchvision==0.19.0+cu124

**Comment by bottler** [comment]
You might be the first person to report building with cuda 12.6. Your error is

```
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.6/include\cuda/std/__tuple_dir/vector_types.h(88): error: expected a ">"
```

I wonder if you are using a compiler version supported by that particular version of cuda. perhaps you need a new version of visual studio. But we can't help with specifics. Other Windows users might be able to help.

**Comment by roshanbiswanath** [comment]
I am using Visual Studio Build Tools 2022

**Comment by bottler** [comment]
Is it fully updated?

**Comment by WindVChen** [comment]
> Running the following command leads to error from nvcc `cd pytorch3d` `python setup.py install`
> 
> Error:
> 
> ```
> 16 errors detected in the compilation of "C:/Users/PC/Biswanath/Machine Learning/3D/ROMP_resnet/ROMP/pytorch3d/pytorch3d/csrc/pulsar/cuda/renderer.backward.gpu.cu".
> renderer.backward.gpu.cu
> ```
> 
> The Entire Log can be found here [log.txt](https://github.com/user-attachments/files/16847132/log.txt)
> 
> My NVCC version is
> 
> ```
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2024 NVIDIA Corporation
> Built on Fri_Jun_14_16:44:19_Pacific_Daylight_Time_2024
> Cuda compilation tools, release 12.6, V12.6.20
> Build cuda_12.6.r12.6/compiler.34431801_0
> ```
> 
> And CUDA version is 12.6
> 
> My PyTorch Installation is torch==2.4.0+cu124 torchaudio==2.4.0+cu124 torchvision==0.19.0+cu124

Same error +1

**Comment by WindVChen** [comment]
Finally, installed another CUDA 12.4 on my computer and it works smoothly.

**Comment by Ryuukeisyou** [comment]
Seems that some changes in cuda 12.6 made it incompatible. I tried 12.4 with torch 2.4.1+cu124 and it built smoothly.
