### ISSUE TITLE
Support Pytorch2.4

### ISSUE THREAD

**Issue by lmelinda** [facebookresearch/pytorch3d#1863]
latest version on PyTorch is 2.4, but according to pytorch3d's `INSTALL.md` we don't support it yet. Could we add the support?

**Comment by bottler** [comment]
It’s supported, just prebuilt packages are not available. They won’t be
made available instantly, similar to previous releases.

**Comment by lmelinda** [comment]
so if we run with `setup.py` that wouldn't be supported yet? what would be the roughly timeline for this to come?

and if prebuilt is not, what is the recommended way to build it now?

**Comment by seigeweapon** [comment]
Is there prebuilt package on pytorch 2.3.1 cu11.8? Or, can I find the list for such packages somewhere? Thanks

**Comment by bottler** [comment]
You can see available packages at https://anaconda.org/pytorch3d/pytorch3d/files which includes the one you're asking for.
