### ISSUE TITLE
Long compiling time

### ISSUE THREAD

**Issue by grgkopanas** [facebookresearch/pytorch3d#187]
## ❓ Questions on how to use PyTorch3D

I am using pytorch3d in Windows 10 and every time I do a change in the cpp code the compilation takes around 10-15min.
I recompile using 'python setup.py install' command as suggested in the readme for compiling from sources.

Is this the best flow I can have? Is the compiling time reasonable?

**Comment by bottler** [comment]
This is interesting. Can you tell from the output whether just your modified cpp is recompiled or every cpp file (and perhaps every cu file) is being recompiled?

If you are using pytorch 1.5, is it using ninja (the default I think) or the traditional single-threaded build? I hope you can force the traditional build in your terminal with `set PYTORCH3D_NO_NINJA=1`.

**Comment by grgkopanas** [comment]
it recompiled everything and that's why it takes so long.
My pytorch version is 1.4.0

The beginning of the compilation logs look like this:

running install
running bdist_egg
running egg_info
writing pytorch3d.egg-info\PKG-INFO
writing dependency_links to pytorch3d.egg-info\dependency_links.txt
writing requirements to pytorch3d.egg-info\requires.txt
writing top-level names to pytorch3d.egg-info\top_level.txt
reading manifest file 'pytorch3d.egg-info\SOURCES.txt'
writing manifest file 'pytorch3d.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
building 'pytorch3d._C' extension
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DWITH_CUDA -IE:\gkopanas\python_projects\DeepLearning_IBR\pytorch3d\pytorch3d\csrc -IE:\gkopanas\python_projects\envs\DL_IBR2\lib\site-packages\torch\include -IE:\gkopanas\python_projects\envs\DL_IBR2\lib\site-packages\torch\include\torch\csrc\api\include -IE:\gkopanas\python_projects\envs\DL_IBR2\lib\site-packages\torch\include\TH -IE:\gkopanas\python_projects\envs\DL_IBR2\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -IE:\gkopanas\python_projects\envs\DL_IBR2\include -IE:\gkopanas\python_projects\envs\DL_IBR2\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /EHsc /TpE:\gkopanas\python_projects\DeepLearning_IBR\pytorch3d\pytorch3d\csrc\ext.cpp /Fobuild\temp.win-amd64-3.7\Release\gkopanas\python_projects\DeepLearning_IBR\pytorch3d\pytorch3d\csrc\ext.obj /MD /wd4819 /EHsc -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0
ext.cpp
E:\gkopanas\python_projects\envs\DL_IBR2\lib\site-packages\torch\include\c10/util/Exception.h(28): warning C4275: non dll-interface class 'std::exception' used as base for dll-interface class 'c10::Error'

**Comment by bottler** [comment]
I think incremental building should work, and I don't have any leads. It will be a while before I can experiment with this.

It may be that using pytorch 1.5 and allowing ninja to work will fix the problem.

**Comment by grgkopanas** [comment]
I'll try that, do you think there is any other information I can give so any person that might pick this up will be able to reproduce?

**Comment by bottler** [comment]
Not that I can think of. I am thinking this is a general problem rather than something specific to your machine. (A bad clock in a computer would be a specific thing that could cause this, but that seems unlikely.)

**Comment by grgkopanas** [comment]
I can confirm that pytorch 1.5 with ninja fixes the issue in windows. But for 1.4 it's still there

**Comment by bottler** [comment]
In that case there isn't a problem with pytorch3d itself to fix here.
