### ISSUE TITLE
How to get a more smooth normal rendering?

### ISSUE THREAD

**Issue by yejr0229** [facebookresearch/pytorch3d#1870]
Hi, I use blender and pytorch3d to render a normal map, and I get:
![image](https://github.com/user-attachments/assets/463bd7d4-8c16-481d-a7bb-0aacd8a9cc89)
![image](https://github.com/user-attachments/assets/220b9ca5-9794-48ca-9495-73d5d6927d31)
Here pytorch3d has a more obvious patchy and jagged feeling, how can I make pytorch3d get the same result as blender?
Here is my code for rendering normal:
![image](https://github.com/user-attachments/assets/62178183-cba8-48e7-aaab-374e2d82185e)

**Comment by bottler** [comment]
I don't think we can help here. Does blender have a different, smoothed version of the mesh? You might need to work out what interpolation and smoothing you want to do.
