### ISSUE TITLE
Laplacian Loss does not smooth the shape

### ISSUE THREAD

**Issue by MartensCedric** [facebookresearch/pytorch3d#1887]
## 🐛 Bugs / Unexpected behaviors

The Laplacian Loss does not smooth the shape. I am referring to the laplacian loss: https://pytorch3d.readthedocs.io/en/latest/modules/loss.html

I started with a cow mesh, therefore I expected a sphere optimizing only for the Laplacian Loss. What I got is a very spiky cow.

![image](https://github.com/user-attachments/assets/ce31145d-f239-46a7-83ad-9d017d268049)

![image](https://github.com/user-attachments/assets/e3287828-d5f3-4c24-9f91-a3dffdfa56f9)

I expected something similar to this: 
![image](https://github.com/user-attachments/assets/5c2e3341-2fbc-4555-ad7d-0ef5c61a844b)

## Instructions To Reproduce the Issue:

Starting with a code really similar to: https://pytorch3d.org/tutorials/fit_textured_mesh

I simply changed the starting mesh to be a cow too, and changed the losses to only use laplacian loss. I did not get what I expected.

Here is the code: 
[ipynb_and_py.zip](https://github.com/user-attachments/files/17297839/ipynb_and_py.zip)

Simply run and you should get the same results as me.

This used Pytorch 2.4.1+cu121 and pytorch3d-0.7.8 (latest) (ran in Google Colab)

**Comment by bottler** [comment]
This is a modelling question not a question about the library. We can't help.
