### ISSUE TITLE
已经解决了win10下关于pytorch3d下训练自己数据集的问题，如有不了解的，可以交流

### ISSUE THREAD

**Issue by QQ1282898768** [facebookresearch/pytorch3d#190]
关于pytorch3d，可加群857449786 注明（pytorch3d）共同学习，谢谢

已经解决了win10下关于pytorch3d下训练自己数据集的问题，如有不了解的，可以交流

**Comment by gkioxari** [comment]
I am closing this since we don't understand what's going on.
