### ISSUE TITLE
Distance in look_at_view_transform not acting with respect to object

### ISSUE THREAD

**Issue by Ishan-Kumar2** [facebookresearch/pytorch3d#191]
The documentation for [pytorch3d.renderer.cameras.look_at_view_transform](https://pytorch3d.readthedocs.io/en/latest/modules/renderer/cameras.html?highlight=look%20at%20view#pytorch3d.renderer.cameras.look_at_view_transform) says distance coordinate is distance of camera **from** object. 

I tried using a 2d mesh of a triangle with (XYZ)coordinates-
[0,10,-10],[0,0,-10],[10,0,-10] (basically a right angle triangle on z=-10). 

When I set the dist=10, I get an image (call it *img1*), but setting the dist=-10 I dont get an image at all. This is probably because it is taking distance from origin which leads to -10 being at the triangle only. 

Even a distance of -20 which means camera is 20 units behind relative to object *doesn't* give the same image as dist=10(img1).

Same image as inverted img1 is obtained from distance=-30. This can be only explained by distance being relative to [0,0,0] instead of object which is at [0,0,-10]. That way both 10,-30 are 20 units away from -10

Am I going wrong somewhere because this function seems to work fine with 3D meshes, maybe its a issue with 2D shape or non zero centered meshes.

The azim and elev are kept 0 throughout
I am using the OpenGLPerspectiveCameras
#### Code for the Mesh
```
verts_triangle=torch.tensor(([0,10,-10],
                  [0,0,-10],
                  [10,0,-10]))

faces_triangle=torch.tensor([[1,2,0]])
verts_rgb=torch.ones_like(verts_triangle.to(device).float())[None]
textures = Textures(verts_rgb=verts_rgb.to(device))

triangle_mesh = Meshes(
    verts=[verts_triangle.to(device).float()],   
    faces=[faces_triangle.to(device)], 
    textures=textures
)
```

R,T=look_at_view_transform(dist=10,elev=0,azim=0)
Change the value of dist to -10,-20, -30

**Comment by nikhilaravi** [comment]
@Ishan-Kumar2 you're absolutely correct - the `look_at_view_transform` function calls [`camera_position_from_spherical_angles`](https://pytorch3d.readthedocs.io/en/latest/modules/renderer/cameras.html#pytorch3d.renderer.cameras.camera_position_from_spherical_angles) and the documentation of both functions needs to be changed to say that `dist` refers to the  "distance of the camera from the origin". We don't use any information about the object when positioning the camera with the look at transform.  Feel free to submit a PR to fix this.

**Comment by Ishan-Kumar2** [comment]
Hi @nikhilaravi I have submitted the PR [here](https://github.com/facebookresearch/pytorch3d/pull/246)

**Comment by nikhilaravi** [comment]
This has been fixed by https://github.com/facebookresearch/pytorch3d/pull/230.
