### ISSUE TITLE
complied error in complying the kernel code file

### ISSUE THREAD

**Issue by fyyfang** [facebookresearch/pytorch3d#1913]
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\include\sm_32_intrinsics.hpp(123): error: asm operand type size(8) does not match type/size implied by constraint 'r'
  static __declspec(__device__) __inline unsigned short __ldg(const unsigned short *ptr) { unsigned short ret; asm volatile ("ld.global.nc.u16 %0, [%1];"  : "=h"(ret) : "r" (ptr)); return ret; }
                                                                                                                                                                         ^

Error limit reached.
100 errors detected in the compilation of "D:/java/TEXTDATA/src/GPU/kernels/JCudaVectorAddKernel.cu".
Compilation terminated.

**Comment by bottler** [comment]
This appears to be unrelated to pytorch3d.
