### ISSUE TITLE
AttributeError: module 'pytorch3d' has no attribute 'io'

### ISSUE THREAD

**Issue by fwzdev1** [facebookresearch/pytorch3d#1918]
Hi，

I think the pictures here would express my confusion well:
![image](https://github.com/user-attachments/assets/0d09d4ed-edba-4b70-9278-8e432ece27cb)
![image](https://github.com/user-attachments/assets/819bf28f-455b-4438-a455-ca0751cbe4c9)
![image](https://github.com/user-attachments/assets/c9374e41-be70-466e-bfdb-4a70e35fc4fd)

I saw a solution in passing issue, said to use pytorch3d.ops instead of pytorch3d. So I import pytorch3d.ops as pytorch3d here. But it didn't work using original pytorch3d either. So please just ignore it.

And here is a part of my conda list:
pytorch                   1.13.1          py3.10_cuda11.7_cudnn8.5.0_0    pytorch
pytorch-cuda              11.7                 h778d358_5    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytorch3d                 0.7.8                    pypi_0    pypi
torchaudio                0.13.1              py310_cu117    pytorch
torchsummary              1.5.1                    pypi_0    pypi
torchvision               0.14.1              py310_cu117    pytorch

Besides, I used `pip install "git+https://github.com/facebookresearch/pytorch3d.git@stable"` installing pytorch3D. 
Thanks!

**Comment by bottler** [comment]
`import pytorch3d.ops as pytorch3d` would not be a good idea in any situation I can think of, and would cause an error like this.

What happens if you try `import pytorch3d.io` and then use `pytorch3d.io.load_ply`? That would be a usual way to use the library. It doesn't import everything on `import pytorch3d`.

**Comment by fwzdev1** [comment]
> `import pytorch3d.ops as pytorch3d` would not be a good idea in any situation I can think of, and would cause an error like this.
> 
> What happens if you try `import pytorch3d.io` and then use `pytorch3d.io.load_ply`? That would be a usual way to use the library. It doesn't import everything on `import pytorch3d`.

Yeah that works! Thanks a lot!
