### ISSUE TITLE
Unexpected rendering when using batch lights

### ISSUE THREAD

**Issue by Agent-INF** [facebookresearch/pytorch3d#192]
## 🐛 Bugs / Unexpected behaviors

Hey!
I'm trying to render different meshes with different lights, and process them in batches. However, I found the results are not what I was expected.
To simplify the steps as much as possible, let's try a simple case:

`   

    ambient_color = torch.FloatTensor([[0.0, 0.0, 0.0]]).to(self.device)
    diffuse_color = torch.FloatTensor([[1.0, 1.0, 1.0]]).to(self.device)
    specular_color = torch.FloatTensor([[0.0, 0.0, 0.0]]).to(self.device)
    direction = torch.FloatTensor([[1, 0, 0]]).to(self.device)
    lights = DirectionalLights(ambient_color=ambient_color,
                               diffuse_color=diffuse_color,
                               specular_color=specular_color,
                               direction=direction,
                               device=self.device)
    shader = TexturedSoftPhongShader(device=self.device, cameras=self.cameras, lights=lights)
    renderer = MeshRenderer(rasterizer=self.rasterizer, shader=shader)
    render_image = renderer(meshes) # there are 2 meshes to be rendered 
`
In this case, the arguments of DirectionalLights are tensor of shape (1, 3), and the results seem OK.
![renders0 - Copy](https://user-images.githubusercontent.com/20737400/81662244-ddb30880-946f-11ea-826e-2fa889bd7953.png) ![renders1 - Copy](https://user-images.githubusercontent.com/20737400/81662265-e3a8e980-946f-11ea-91a5-ae6cc8043cbd.png)

However, if I change the shape of arguments of DirectionalLights to (2, 3), the results are wired:
`   

    ambient_color = torch.FloatTensor([[0.0, 0.0, 0.0]]).to(self.device).repeat(2, 1)
    diffuse_color = torch.FloatTensor([[1.0, 1.0, 1.0]]).to(self.device).repeat(2, 1)
    specular_color = torch.FloatTensor([[0.0, 0.0, 0.0]]).to(self.device).repeat(2, 1)
    direction = torch.FloatTensor([[1, 0, 0]]).to(self.device).repeat(2, 1)
    lights = DirectionalLights(ambient_color=ambient_color,
                               diffuse_color=diffuse_color,
                               specular_color=specular_color,
                               direction=direction,
                               device=self.device)
`
![renders1](https://user-images.githubusercontent.com/20737400/81662861-c0326e80-9470-11ea-83ff-21492dfabf4a.png)![renders3](https://user-images.githubusercontent.com/20737400/81662874-c32d5f00-9470-11ea-9bf3-dbb826f1d02b.png)

Theoretically, the results should be the same as before, so I looked into the code and found the problem may be caused by broadcasting issue in 
https://github.com/facebookresearch/pytorch3d/blob/6a365d203fff6b10c53e7483b33eac48d067055b/pytorch3d/renderer/mesh/shading.py#L82
In my case, the shape of ambient is (2, 3) and diffuse is (2, 256, 256, 1, 3).
And I believe this line could be fixed as:
`
    colors = (ambient[:, None, None, None] + diffuse) * texels + specular
`
It produces the right results for me, but I'm not sure if this is the best way.

P.S. I also found similar broadcasting issues in:
https://github.com/facebookresearch/pytorch3d/blob/6a365d203fff6b10c53e7483b33eac48d067055b/pytorch3d/renderer/lighting.py#L251
https://github.com/facebookresearch/pytorch3d/blob/6a365d203fff6b10c53e7483b33eac48d067055b/pytorch3d/renderer/lighting.py#L255
and I think those should be:
`
        direction = self.location[:, None, None, None] - points
`

**Comment by michele-arrival** [comment]
I wish to add to the above that i have had a problem with the lighting too (shapes not broadcasting correctly with each other and failing with

```
  File "[...]\lib\site-packages\pytorch3d-0.2.0-py3.7-win-amd64.egg\pytorch3d\renderer\lighting.py", line 67, in diffuse
    angle = F.relu(torch.sum(normals * direction, dim=-1))
RuntimeError: The size of tensor a (4) must match the size of tensor b (16777216) at non-singleton dimension 0
```

having a batch size of 4 in meshes, and camera T+R.

however with the fixes above (or by removing the explicit batch size from the PointLights), the forward function didn't fail anymore

**Comment by nikhilaravi** [comment]
@Edward-Lin, @michele-arrival thanks for pointing this out. We will look into this issue - feel free to submit a PR with a fix.

**Comment by nikhilaravi** [comment]
This issue should now be fixed by https://github.com/facebookresearch/pytorch3d/commit/bc8361fa471e39280b1c5e3717309167b08ffed5.
