### ISSUE TITLE
Pulsar Renderer: Support two focal lengths fx, fy.

### ISSUE THREAD

**Issue by axbycc-mark** [facebookresearch/pytorch3d#1925]
## 🚀 Feature
The Pulsar renderer is currently the fastest way to render pointclouds using pytorch3d. However, it only supports one focal length. 

## Motivation

It would be nice to support two focal lengths so that we can do inference with calibrated cameras from real life, which often have different fx and fy. This would enable some pose refinement / SLAM applications.

**Comment by bottler** [comment]
We aren't planning to work on this kind of thing soon. Even fixing and merging #1369 is not currently being worked on. Maybe you or someone else might do this?

**Comment by axbycc-mark** [comment]
Thanks. Can't work on that fix you mentioned currently, but for anyone else seeing this, here is a workaround.

Use the Pulsar renderer as an idealized virtual camera plane with some fixed focal length and size. Then the transform from the virtual camera plane to a focal-length corrected camera image is simply a homogeneous transform, which can be achieved by F.grid_sample.
