### ISSUE TITLE
How can I get the closest point on mesh of given points?

### ISSUE THREAD

**Issue by linpeisensh** [facebookresearch/pytorch3d#193]
Thank you for your excellent work!

Here is my problems:

Is there function in pytorch3d returns closest point on mesh of given points? 

If not, is there function returns the distance between all points on mesh and given points?

Is there any advises to my title problem?

Thank you for your time!

**Comment by bottler** [comment]
The function loss.point_mesh_distance.point_face_distance gives you the distances of closest points on a mesh to the given points, and the indices of the faces which contain those closest points.

**Comment by linpeisensh** [comment]
Thank you for your reply!

After get these faces, should I use sample from these faces and get the closest point?

> The function loss.point_mesh_distance.point_face_distance gives you the distances of closest points on a mesh to the given points, and the indices of the faces which contain those closest points.

**Comment by linpeisensh** [comment]
Sorry, I run the function loss.point_mesh_distance.point_mesh_edge_distance and only get a distance (as I read in your readthedocs), I have no idea how to use it to get the closest point on mesh of given points.

**Comment by gkioxari** [comment]
Hi @linpeisensh 
The `point_mesh_distance` returns the squared euclidian distance of a point in a pointcloud to the closest face in the meshes. It doesn't expose the index of that face. However, `PointFaceDistanceForward` does

https://github.com/facebookresearch/pytorch3d/blob/6a365d203fff6b10c53e7483b33eac48d067055b/pytorch3d/csrc/point_mesh/point_mesh_face.h#L51

So you will have to call `_C.point_face_dist_forward` in your code. 

https://github.com/facebookresearch/pytorch3d/blob/6a365d203fff6b10c53e7483b33eac48d067055b/pytorch3d/csrc/ext.cpp#L56

Here is an example how:

https://github.com/facebookresearch/pytorch3d/blob/6a365d203fff6b10c53e7483b33eac48d067055b/pytorch3d/loss/point_mesh_distance.py#L51

**Comment by linpeisensh** [comment]
@gkioxari 
Thank you for your reply!
I can get this index now.
What I want to get is the closest point on the mesh of given points,.
So I should create a new mesh (only this face) and sample from it to get the closest point. Do you think this works or do you have any better solution.
Thank you!

**Comment by gkioxari** [comment]
If I understand correctly, your mesh has only one face? If yes, then yeah you can create a tiny mesh consisting of 3 vertices and one triangular face and pass it through this function, along with the points.

**Comment by linpeisensh** [comment]
I have an idea now.

Thank you for your reply!

Best

**Comment by gkioxari** [comment]
Good luck! I am closing this issue :)

**Comment by Gaozhongpai** [comment]
> @gkioxari
> Thank you for your reply!
> I can get this index now.
> What I want to get is the closest point on the mesh of given points,.
> So I should create a new mesh (only this face) and sample from it to get the closest point. Do you think this works or do you have any better solution.
> Thank you!

Hi, do you know how to obtain the closest points on the mesh of given points, not just the distances and indices? Thank you very much.

**Comment by HelloRicky123** [comment]
> > @gkioxari
> > Thank you for your reply!
> > I can get this index now.
> > What I want to get is the closest point on the mesh of given points,.
> > So I should create a new mesh (only this face) and sample from it to get the closest point. Do you think this works or do you have any better solution.
> > Thank you!
> 
> Hi, do you know how to obtain the closest points on the mesh of given points, not just the distances and indices? Thank you very much.

Hi, have you found any solution? Pytorch3d is 100 times faster than trimesh, but I do not know how to get the location here.

**Comment by gkioxari** [comment]
Please check the reply to the issue https://github.com/facebookresearch/pytorch3d/issues/1016
