### ISSUE TITLE
Rendering textured and untextured meshes in same scene

### ISSUE THREAD

**Issue by karim-eladl** [facebookresearch/pytorch3d#194]
Hi!
 
Based on the render_textured_meshes tutorial I'm able to render a scene with one textured mesh from an .obj file. Based on the camera_position_optimization_with_differentiable_rendering tutorial I can render a scene with one untextured mesh where I can set the rgb color of the points. 

However, I haven't been able to figure out how to render a scene containing (1) multiple .obj files and (2) each mesh having a different texture. Basically, I want to render a scene with a textured mesh and an untextured mesh (or differently textured mesh). 

Any tips would be greatly appreciated! Thank you!

**Comment by nikhilaravi** [comment]
The texture types need to be the same for all meshes in a batch. So if you use `uv` textures for one mesh and `rgb` textures for the other mesh as you described (from the `render_textured_meshes` tutorial and the `camera_position_optimization_with_differentiable_rendering ` tutorials) you would not be able to combine them into one mesh or into one batch. 

For your use case you can do the following: for the untextured mesh  create a uniform white texture in the same texture type as the textured mesh e.g. if you are using uv coordinates, simply create a white texture map which has the same dimensions as the texture map of the textured mesh and set all the uv coordinates for the vertices to e.g. [0, 0].

**Comment by karim-eladl** [comment]
Okay thank you so much! Is there by any chance more of an existing code base other than the tutorials that exemplifies how to load several meshes in this way. Thank you again and sorry for the many basic questions.

**Comment by nikhilaravi** [comment]
@karim-eladl we don't have any examples of batches of mixed textures but it should not be difficult to implement. Create two separate meshes with textures: 
- `mesh1` where the texture map is loaded from a file and you use that to initialize a `Textures` class
- `mesh2` where you initialize a `Textures` class as I described in the comment above.

You can then use the the function `join_meshes_as_batch`:

https://github.com/facebookresearch/pytorch3d/blob/6a365d203fff6b10c53e7483b33eac48d067055b/pytorch3d/structures/meshes.py#L1376

For example:
```
meshes_batch = join_meshes_as_batch(mesh1, mesh2, include_textures=True)
```

This will work providing the textures for both meshes are the same i.e. either both uv maps or both vertex textures.

**Comment by karim-eladl** [comment]
great, thank you @nikhilaravi!
