### ISSUE TITLE
How do Compose global pose SE3 with related pose se3

### ISSUE THREAD

**Issue by fangxu622** [facebookresearch/pytorch3d#195]
Purpose: Compose global pose **Tg** with related pose **xi**

Tg is a SE3 pose represented with 7 parameters (x, y, z, ww, wx, wy, wz)

xi is a se3 pose represented with 6 parameters (rho1, rho2, rho3, omega_x, omega_y, omega_z)

The Tg we can convert into SfMPerspectiveCameras object using transform api.

but how can compose they?

**Comment by davnov134** [comment]
Hi, I am not 100% sure what is the actual representation of the se3 pose?
More specifically, is this a concatenation of an axis angle representation and a 3d camera translation vector?

**Comment by fangxu622** [comment]
@davnov134 
Hi， thanks for your reply. I'm sorry for the indistinct description.
For clarifying these points.  The se(3)  is the lie algebra. the SE(3) is the  exponential map of se(3).  

So.
**Situation 1:**

if related pose **xi**  is a concatenation of an axis angle representation and a 3d camera translation vector. it can be  easily conerted into SfMPerspectiveCameras object by using transform API.

*global pose of point A  (SfMPerspectiveCameras object) :   Ta **
** relative pose from A to B  (SfMPerspectiveCameras object) :   Xi **

the point B global pose: **Tb**  ( SE3 4*4 matrix)
  Tb = Tg.get_world_to_view_transform().compose(Xi.get_world_to_view_transform())

Is it correct?

**Situation 2:**

the SE(3) is the  exponential map of se(3).  the se3 is a six dimension vector. but I think it is not  a concatenation of an axis angle representation and a 3d camera translation vector.

*global pose of point A  (SfMPerspectiveCameras object) :   Ta ** ( SE3 4*4 matrix )
** relative pose from A to B  (SfMPerspectiveCameras object) :   R_Pose_A_2_B ** ( se3 )

So how to compose them to get global pose **Tb** ?

or how to convert SE3 to se3 or vice versa ?

**Comment by fangxu622** [comment]
Hi， My bro ~ how do you think?@davnov134

**Comment by fangxu622** [comment]
Hi, My bro @davnov134, Where is he going? @nikhilaravi, Do you know? Is everything ok?

**Comment by davnov134** [comment]
Hi my bro @fangxu622,

all good here, no need to worry. I am sorry for a late response.

I agree for the situation 1 where you can just compose the two transforms if they are both in the matrix form.

For situation 2, if your se(3) is of the following form:
```
[t_x, t_y, t_z, r_x, r_y, r_z]
```
i.e. a 6d vector where `t_<coord>` is the translation component and `r_<coord>` is an element of the axis-angle representation (= a logarithm of the SO3 rotation matrix), you can do the following to convert the 6d vector to a camera:

```
R = pytorch3d.ops.so3_exponential_map([r_x, r_y, r_z])
camera = SfMPerspectiveCameras(T=[t_x, t_y, t_z], R=R)
```
i.e. you first exponentiate the log_rotation and use the result in place of the rotation matrix in the camera.

Let me know if this helps!

**Comment by fangxu622** [comment]
@davnov134  Yeah! Thank U. se3 is 6d vector but not [t_x, t_y, t_z, r_x, r_y, r_z] .. the case of your description is in line with *Situation 1*. However, I have solved my problem with the lib [liegroups](https://github.com/utiasSTARS/liegroups). 

I still use SfMPerspectiveCameras object and BA (from pytorch3d tutorial) to optimize pose(visual odometry ).  and I'm very interest in your research(TPAMI 2018).  I think it will give me some inspiration to my work.
