### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by tchaton** [facebookresearch/pytorch3d#20]
## ❓ Questions on how to use PyTorch3d

Dear people of Pytorch3D,

We are actively working on a project called Pytorch Deep Point Cloud Benchmark, with hydra as our core configuration tool. 

I thought it could be of any interest

Here is the repo link: https://github.com/nicolas-chaulet/deeppointcloud-benchmarks 
and its associated cuda / cpp library: https://github.com/nicolas-chaulet/torch-points

Maybe, it could be possible to imagine future possible collaboration.

Best regards,
Thomas Chaton.

NOTE:

1. If you encountered any errors or unexpected issues while using PyTorch3d and need help resolving them,
   please use the "Bugs / Unexpected behaviors" issue template.

2. We do not answer general machine learning / computer vision questions that are not specific to
	 PyTorch3d, such as how a model works or what algorithm/methods can be
	 used to achieve X.

**Comment by nikhilaravi** [comment]
@tchaton Thanks for sharing your codebase. We will definitely take a look :)
