### ISSUE TITLE
light intensity

### ISSUE THREAD

**Issue by alex-helm** [facebookresearch/pytorch3d#200]
Is there a way to control the intensity of point lights? I'm trying to make the lighting less diffuse and shadows more defined.

**Comment by wangxuewen99** [comment]
I have this problem too.

**Comment by nikhilaravi** [comment]
Have you tried setting the `diffuse_color` value in `PointLights` as the `intensity x color`?

**Comment by nikhilaravi** [comment]
@alex-helm did you try this suggestion? Do you still need help with this issue?

**Comment by gkioxari** [comment]
No response. Closing this. Feel free to reopen if you have more questions.

**Comment by jonilaserson** [comment]
Re-opening, since I'm having issues lighting meshes:

@nikhilaravi, What do you mean by intensity x color?
Can the diffuse_color have values that are larger than 1?

Often when I play with the ambient_color and the diffuse_color values, the renderer generates RGB values that are much greater than 1.  Is this the expected behavior?

**Comment by bottler** [comment]
In normal use of the renderer you would set total lighting to 1.0 or less, and the output of the renderer would be between 0 and 1. However, there is nothing to stop you setting total lighting higher than that, and potentially therefore getting output which is above 1 ("brighter than white"). If you wanted to visualise this output with matplotlib.imshow or similar, you would need to map the values back to 1 or less, e.g. with rescaling or clamping.  PyTorch3D does not clamp automatically; if it did it might ruin important gradient information.

**Comment by jonilaserson** [comment]
What do you mean by "total lighting"? How is it set/computed?

**Comment by bottler** [comment]
By total lighting, I just mean, for each color channel, the sum of the types of lighting e.g. ambient+specular+diffuse.
