### ISSUE TITLE
About the 'tests' path

### ISSUE THREAD

**Issue by ss24cs** [facebookresearch/pytorch3d#206]
## ❓ Questions on how to use PyTorch3D
Hi, buddy, I'm a facebookrearch fan, and download pytorch3D files. 
Here, How can I use the test_xx.py in 'pytorch3d-master/tests' path to test the example images?
Thank you.

**Comment by nikhilaravi** [comment]
Hi @ss24cs i'm not sure what you mean by "test the example images"? Can you explain a bit more what you want to do?

**Comment by ss24cs** [comment]
I'm sorry, forget about  "test the example images". Can you tell me how to run images belong to the 'pytorch3d-master/tests/data'  with 'python ./tests/test_ply_io.py'? Thx.

**Comment by bottler** [comment]
If you have pytorch3d installed, and you go to the `tests` directory of a checkout of the code, then you should be able to run that file with 
```
python -m unittest -v test_ply_io
```

**Comment by ss24cs** [comment]
> If you have pytorch3d installed, and you go to the `tests` directory of a checkout of the code, then you should be able to run that file with
> 
> ```
> python -m unittest -v test_ply_io
> ```

Thank you buddy. Have nice day!

**Comment by nikhilaravi** [comment]
@ss24cs if this answers your question, please close the issue.
