### ISSUE TITLE
Why does blending use zbuf in  world coordinate? 

### ISSUE THREAD

**Issue by JudyYe** [facebookresearch/pytorch3d#210]
Hi, 

Thank you for writing such a good framework for 3D vision community! Really neat!

I have a question regarding blending. 
https://github.com/facebookresearch/pytorch3d/blob/f0ba4c53e58f20ab13db5f4f3a283b5f03b8d8ed/pytorch3d/renderer/blending.py#L152

According to my understanding, the weights are assigned by the depth according to the camera. The closer (the lower fragment.zbuf) to the camera, the higher weight is assigned. However, the fragment.zbuf seems in [world coordinate](https://github.com/facebookresearch/pytorch3d/blob/master/docs/notes/renderer_getting_started.md#fragments), which usually are not consistent with view space. 

I feel it's also similar to issue #95 #167 and commit f0ba4c53e58f20ab13db5f4f3a283b5f03b8d8ed @nikhilaravi

**Comment by JudyYe** [comment]
Follow up: 
I also realized that if commit f0ba4c53e58f20ab13db5f4f3a283b5f03b8d8ed were effective, then  `fragment.zbuf` returned would be in view space. This induce two consquences: 

1. the blending issue I mentioned here seems fixed. i.e. the weight are based on zbuf in view space.  
2. It would contradict with [doc](https://github.com/facebookresearch/pytorch3d/blob/master/docs/notes/renderer_getting_started.md#fragments) since z.buf would be in view space then. (which appears more reasonable to me.)

**Comment by nikhilaravi** [comment]
Hi @JudyYe yes in https://github.com/facebookresearch/pytorch3d/commit/f0ba4c53e58f20ab13db5f4f3a283b5f03b8d8ed we fixed the issue with the zbuf that you mentioned. You are correct that the docs need to be updated! Feel free to submit a PR to fix this.

**Comment by JudyYe** [comment]
Thank you for the clarification and your prompt response!
