### ISSUE TITLE
Half precision rendering?

### ISSUE THREAD

**Issue by PartlyFluked** [facebookresearch/pytorch3d#215]
I am using pytorch3d for an adversarial network I am training at the moment. While the discriminator can be easily autocast to half precision and almost halve it's GPU memory usage, the renderer still takes up the majority of the memory.

Is there a point in the timeline for allowing half precision for pytorch3d? Is it as "simple" as templating csrc/rasterize_meshes/rasterize_meshes.cu (and others) with half types or does it require explicit SIMD vectorising. Alternatively are there caveats that stop these attempts from being able to utilize tensor cores / is the full precision absolutely required for acceptable rasterizer results?

**Comment by nikhilaravi** [comment]
@PartlyFluked before thinking about half precision, you might be able to reduce your memory usage in easier ways e.g. by reducing the value of `faces_per_pixel` that you use for rasterization e.g. see [here](https://github.com/facebookresearch/pytorch3d/blob/master/docs/notes/renderer.md) for an explanation of the memory usage.

**Comment by gkioxari** [comment]
No response so I am closing this issue. Feel free to re-open if issues arise.
