### ISSUE TITLE
Invalid rotation matrix when number of camera position is equal to 3

### ISSUE THREAD

**Issue by guanming001** [facebookresearch/pytorch3d#219]
When trying to create rotation matrix using `look_at_rotation` with **3** camera positions, it will result in invalid rotation matrix

```python
import torch
from pytorch3d.renderer import look_at_rotation

N = 3 # Number of cameras
camera_position = torch.zeros(N, 3)
camera_position[:,2] = 1.0 # Set camera z axis to a distance of one
R = look_at_rotation(camera_position)

print('Output of R:\n', R)
```
```
Output of R:
 tensor([[[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0., -1.]],

        [[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0., -1.]],

        [[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0., -1.]]])

```
Expected output should be: 
(which can be obtained by changing the N to any numbers other than 3)
```
Output of R:
 tensor([[[-1.,  0.,  0.],
         [ 0.,  1.,  0.],
         [ 0.,  0., -1.]]])
...
```

I think the error occurs due to the use of `torch.cross` in the function `look_at_rotation` https://github.com/facebookresearch/pytorch3d/blob/3c6f9220fc061a527c6fb3533f5244c30c64ef47/pytorch3d/renderer/cameras.py#L881

As `torch.cross` [defaults to the first dimension found with the size 3](https://pytorch.org/docs/master/generated/torch.cross.html)

When number of cameras is three, the first dimension of the variables (up, z_axis, x_axis) is also 3 and it will result in unexpected error when computing x_axis and y_axis using `torch.cross`
https://github.com/facebookresearch/pytorch3d/blob/3c6f9220fc061a527c6fb3533f5244c30c64ef47/pytorch3d/renderer/cameras.py#L919
https://github.com/facebookresearch/pytorch3d/blob/3c6f9220fc061a527c6fb3533f5244c30c64ef47/pytorch3d/renderer/cameras.py#L920

If dimension is specified for `torch.cross` it could eliminate the above error.
```python
x_axis = F.normalize(torch.cross(up, z_axis, dim=1), eps=1e-5)
y_axis = F.normalize(torch.cross(z_axis, x_axis, dim=1), eps=1e-5)
```

**Comment by nikhilaravi** [comment]
@guanming001 good catch! Thanks for pointing this out. We will fix it soon or if you are able to submit a PR for the fix we can review it!
