### ISSUE TITLE
Problems about Camera position optimization using differentiable rendering

### ISSUE THREAD

**Issue by sbyNiceBlowJob** [facebookresearch/pytorch3d#224]
I 'm working on Windows 10 and I 'm trying the example of Camera position optimization using differentiable rendering. I use phong_renderer to render the object and the background is white but I notice that your pictures have a black background. Can you tell me how to change the background? Thanks a lot!

**Comment by gkioxari** [comment]
We have added support of a variety of background colors defined in `BlendParams`

https://github.com/facebookresearch/pytorch3d/blob/e5ac38aa87efd440b356cb8d8e2d424efac3d523/pytorch3d/renderer/blending.py#L18-L21

This allows you to specify the color of the background.
