### ISSUE TITLE
Confused about parameter faces_per_pixel

### ISSUE THREAD

**Issue by FrankZhang0309** [facebookresearch/pytorch3d#225]
## ❓ Question about how to choose faces_per_pixel in RasterizationSettings

I'm trying to use pytorch3d for camera position optimization with differentiable rendering.

I ran your sample code about it, then I figure out the GPU Memory usage is so high(about more than 10GB) if I want to render a higher resolution image and to camera position optimization.
for example, 1024x1024 resolution, then I tried to know the reason.

As I observed, the faces_per_pixel parameter now is 100 for SoftSilhouetteShader, and if I change it to 1, the rendered image goes wrong, looks like only has the border, which I don't know why. 

with 1:
![1](https://user-images.githubusercontent.com/39019938/83964673-2039fa80-a8e1-11ea-9e77-d827ca390b26.png)
with 100:
![2](https://user-images.githubusercontent.com/39019938/83964684-262fdb80-a8e1-11ea-9e8e-de375e7fb9ad.png)

Furthermore, what if I want to render a rectangle image instead of a squared image?

I want to know the meaning of this parameter, and the way to choose it. Looking forward to the answer. Thx a lot.

**Comment by gkioxari** [comment]
I urge you to read the documents we have for the rendering pipeline
* https://github.com/facebookresearch/pytorch3d/blob/master/docs/notes/renderer.md
* https://github.com/facebookresearch/pytorch3d/blob/master/docs/notes/renderer_getting_started.md

Based on your explanation and memory usage, I suspect you are using the naive rasterization settings. Could you provide a code snippet so that we can further answer your questions?

**Comment by FrankZhang0309** [comment]
> I urge you to read the documents we have for the rendering pipeline
> 
> * https://github.com/facebookresearch/pytorch3d/blob/master/docs/notes/renderer.md
> * https://github.com/facebookresearch/pytorch3d/blob/master/docs/notes/renderer_getting_started.md
> 
> Based on your explanation and memory usage, I suspect you are using the naive rasterization settings. Could you provide a code snippet so that we can further answer your questions?

Thanks for your kind reply, and here is my code:
```
raster_settings = RasterizationSettings(
    image_size=512, 
    blur_radius=np.log(1. / 1e-4 - 1.) * blend_params.sigma, 
    faces_per_pixel=100, 
)

# Create a silhouette mesh renderer by composing a rasterizer and a shader. 
silhouette_renderer = MeshRenderer(
    rasterizer=MeshRasterizer(
        cameras=cameras, 
        raster_settings=raster_settings
    ),
    shader=SoftSilhouetteShader(blend_params=blend_params)
)
```
The GPU memory usage looks like be proportional to `faces_per_pixel`. I want to know how to reduce the GPU memory usage and increase the backward speed.

**Comment by gkioxari** [comment]
From the links I provided above (I presume you haven't read them!) you would see that our rasterizer outputs 4 output tensors. Three of them have size BxHxWxK and the other one has BxHxWxKx3. This means that memory usage is proportional to the batch size, the height and width of your rendering resolution and K (or else known as `faces_per_pixel`). The first link I provide gives you exact mathematical formulations for the memory usage. 

If you want to reduce the memory, then you can reduce either either one of these parameters. I would try with reducing `faces_per_pixel` which is correlated to the size of your mesh.

**Comment by FrankZhang0309** [comment]
> From the links I provided above (I presume you haven't read them!) you would see that our rasterizer outputs 4 output tensors. Three of them have size BxHxWxK and the other one has BxHxWxKx3. This means that memory usage is proportional to the batch size, the height and width of your rendering resolution and K (or else known as `faces_per_pixel`). The first link I provide gives you exact mathematical formulations for the memory usage.
> 
> If you want to reduce the memory, then you can reduce either either one of these parameters. I would try with reducing `faces_per_pixel` which is correlated to the size of your mesh.

Thanks, I am the very beginner of pytorch, I will try to reduce `faces_per_pixel` to a proper value for mesh rendering and reducing GPU memory.

And I am still curious about when`faces_per_pixel = 1`, why the alpha channel of the rendered image with `SoftSilhouetteShader` looks like I showed in my issue? In my concern, as your document said, `faces_per_pixel` in fact means the number of **top points** saved for every pixel. If the model is fine, every pixel may save many points, these points may consist of many faces. When `faces_per_pixel = 1`, we will lose the information of these faces and can't draw them, that's the reason why the rendered image looks strange. Am I right?

It would be so appreciated for your patient reply~

**Comment by gkioxari** [comment]
When `faces_per_pixel` is 1 then you only render the nearest face per pixel resulting in very sparse information to be rendered. This will not be good for learning either. You want to propagate information to more faces. I suggest setting `faces_per_pixel` to 20 to start with. The value of `faces_per_pixel` correlates with the image size and the mesh size. But start with 20 and see what you get.

**Comment by FrankZhang0309** [comment]
> When `faces_per_pixel` is 1 then you only render the nearest face per pixel resulting in very sparse information to be rendered. This will not be good for learning either. You want to propagate information to more faces. I suggest setting `faces_per_pixel` to 20 to start with. The value of `faces_per_pixel` correlates with the image size and the mesh size. But start with 20 and see what you get.

I think your answer is very helpful. I will try by myself. Thanks so much. XD

**Comment by gkioxari** [comment]
Sounds good. I will be closing this but feel free to re-open if you have more questions.
