### ISSUE TITLE
How to render textured meshes with UV coordinate of DensePose's result

### ISSUE THREAD

**Issue by leoyzhang** [facebookresearch/pytorch3d#227]
## How to render textured meshes with UV coordinate of DensePose's result
I'm trying to use pytorch3d to create a Texture and Mesh object to render an image.

The Texture object initializes with maps、faces_uvs、verts_uvs. So I used DensePose's(https://github.com/facebookresearch/DensePose) result to create it.
The  maps( atlas.png) likes:
![image](https://user-images.githubusercontent.com/26193836/84105391-c5bcad80-aa4a-11ea-911a-1b6134884606.png)
The faces_uvs and verts_uvs get from https://github.com/facebookresearch/DensePose/blob/master/DensePoseData/get_densepose_uv.sh
the code is:
```
verts, _ = smpl() 
ALP_UV = loadmat('data/UV_Processed.mat')

face = np.array(ALP_UV['All_Faces'])[np.newaxis, :, :]
u = np.array(ALP_UV['All_U'])[np.newaxis, :, :]
v = np.array(ALP_UV['All_V'])[np.newaxis, :, :]
uvs = np.concatenate((u,v), axis = 2)
maps = cv2.imread('data/atlas.png')[np.newaxis, :, :, :] # the texture map
texture = Textures(torch.from_numpy(maps).cuda().float(), face , torch.from_numpy(uvs).cuda().float())

mesh = Meshes(verts, face, texture)
```
The UV coordinate from DensePose show in a background like this, U in [0, 1600], V in [0, 1100]
![image](https://user-images.githubusercontent.com/26193836/84105745-cb66c300-aa4b-11ea-9af4-c59499f91d20.png)

Then I render like the example https://github.com/facebookresearch/pytorch3d/blob/master/docs/tutorials/render_textured_meshes.ipynb
But the result is error

![image](https://user-images.githubusercontent.com/26193836/84112430-526f6780-aa5b-11ea-9892-ad583362f86c.png)

So how to get the relationship of the texture map with the UV coordinate of Densepose?

**Comment by raincrash** [comment]
@leoyzhang could you figure out the issue?

**Comment by leoyzhang** [comment]
> @leoyzhang could you figure out the issue?

I can render the image, but it is mirrored.

**Comment by nikhilaravi** [comment]
@leoyzhang do you mean it is flipped in the X axis? This could just be due to the different world space conventions. In PyTorch3D the world coordinate system is +X to the left, +Y up, +Z in to the page. If you are familiar with Meshlab, this is the same convention.

**Comment by dvirginz** [comment]
@leoyzhang Hi!
Have you managed to solve the issue?

**Comment by leoyzhang** [comment]
> @leoyzhang do you mean it is flipped in the X axis? This could just be due to the different world space conventions. In PyTorch3D the world coordinate system is +X to the left, +Y up, +Z in to the page. If you are familiar with Meshlab, this is the same convention.

Thanks, I have solved the issue.
