### ISSUE TITLE
Mesh Fitting *without* target mesh point cloud?

### ISSUE THREAD

**Issue by luanfujun** [facebookresearch/pytorch3d#228]
Hello, 

I wonder if there is any existing tutorial on fitting geometry without the access to target mesh. 

For example, this PyTorch3D tutorial actually samples a point cloud from target mesh: https://pytorch3d.org/tutorials/deform_source_mesh_to_target_mesh

Would it still be possible to optimize geometry in that case? Look forward to your reply!

Thanks

**Comment by gkioxari** [comment]
We provide differentiable renderers and extensive documentation that should be helpful in understanding how to solve your issue. 
Check out the tutorials: https://github.com/facebookresearch/pytorch3d/tree/master/docs/tutorials
And the notes: https://github.com/facebookresearch/pytorch3d/tree/master/docs/notes

Please let us know if you don't understand anything regarding the renderer. However, we have extensive documentation in the code and the functions to help you understand our renders. In particular, check out the notes
* https://github.com/facebookresearch/pytorch3d/blob/master/docs/notes/renderer_getting_started.md

* https://github.com/facebookresearch/pytorch3d/blob/master/docs/notes/renderer.md

As a side note, we have decided that questions regarding "how do I use PyTorch3D to do my project" will have low priority. We prioritize concrete bug report which come with reproducible code. Everything else receives much lower priority and will not be addressed in a timely manner.

**Comment by luanfujun** [comment]
Alright... I was just wondering if there is a tutorial that does mesh fitting without access to ground truth. I went through the tutorials and notes, and there doesn't seem to have an example for that.

**Comment by simonMoisselin** [comment]
If you have access to the points cloud of the target surface, you can directly use that instead of sampling from the mesh ?

In other way, remove this line from the tutorial:
```python
sample_trg = sample_points_from_meshes(trg_mesh, 5000)
```
