### ISSUE TITLE
cameras.look_at_view_transform documentation possibly incorrect

### ISSUE THREAD

**Issue by eduardohenriquearnold** [facebookresearch/pytorch3d#229]
Hi, I was checking the source code for cameras.look_at_view_transform and the description says that 
```azim is the angle between the projected vector and a reference vector at (1, 0, 0) on the reference plane (the horizontal plane).```
https://github.com/facebookresearch/pytorch3d/blob/4b78e95eeb2d83bd9c8b2f7a5c89e7e4346b7227/pytorch3d/renderer/cameras.py#L946

However, considering the OpenGL right-hand coordinate system and the definition of [cameras.camera_position_from_spherical_angles](https://pytorch3d.readthedocs.io/en/latest/_modules/pytorch3d/renderer/cameras.html#camera_position_from_spherical_angles), I believe it should be ```angle between the projected vector and a reference vector at (0, 0, 1) on the reference plane (the horizontal plane).``` I.e. the angle between the project vector and the Z axis, not the X axis.

I am happy to change the documentation and submit a pull request if this is confirmed.

**Comment by hangg7** [comment]
Can also confirm this in my experience. In face, this is a clear indiscrepency in doc & implementation if you look at [these lines](https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/renderer/cameras.py#L872-L874).

**Comment by nikhilaravi** [comment]
@eduardohenriquearnold, @hangg7  thanks for pointing this out.  You are correct that it should be the angle from `(0, 0, 1)`. Feel free to submit a PR to change the documentation!
