### ISSUE TITLE
how to render with self-defined background like black？

### ISSUE THREAD

**Issue by achao2013** [facebookresearch/pytorch3d#232]
I render the textured mesh to image using meshrenderer，the default background is white. How to change it to any other color like black?

**Comment by gkioxari** [comment]
You can set the background color to anything you wish in the `blend_params` which the blending functions then uses. 

https://github.com/facebookresearch/pytorch3d/blob/7f1e63aed1252ba8145d4a66ce2272331d60cdae/pytorch3d/renderer/blending.py#L19

**Comment by nikhilaravi** [comment]
This functionality was added in https://github.com/facebookresearch/pytorch3d/commit/65620e716c184ec162df04df2f3fe08351a957f5.  I'll close this issue but if you have any further questions feel free to reopen it.
