### ISSUE TITLE
How to capture hidden depth map of a point cloud/mesh?

### ISSUE THREAD

**Issue by jsaisagar** [facebookresearch/pytorch3d#240]
I am following the tutorial https://github.com/facebookresearch/pytorch3d/blob/master/docs/tutorials/render_colored_points.ipynb
and modifying code to capture visible and hidden (depth map of points which are behind visible points w.r.t camera viewpoint) depth map of a point cloud. However, results are not as expected. Can we do this using pytorch3D?

I am using the following settings:
raster_settings = PointsRasterizationSettings(
    image_size=512,
    radius = 0.003,
    #radius = 0.003,
    points_per_pixel = 2,
    bin_size=0
)
rasterizer = PointsRasterizer(cameras=cameras, raster_settings=raster_settings)
depth_ = rasterizer(point_cloud)
depth_map = depth_.squeeze()[..., 1] 
plt.imshow(depth_map.cpu().numpy(),cmap='gray')

Thanks,

**Comment by gkioxari** [comment]
The rasterizer, as described here https://github.com/facebookresearch/pytorch3d/blob/master/docs/notes/renderer_getting_started.md, returns a few tensors. pix_to_face in particular returns the indices of the K (=points_per_pixel) closest points to the image plane for each pixel in a NxHxWxK tensor. I am not quite sure what you want to compute, but with the 4 outputs of the rasterizer (again see the note I attach) you can compute what you say you want.

**Comment by gkioxari** [comment]
No follow up so I am closing this issue. Feel free to re-open if you run into an issue.

**Comment by theschnitz** [comment]
We are landing a change now that introduces MeshRendererWithFragments that returns images, fragments into the renderer library which you can use in the future.

**Comment by tumble-weed** [comment]
In case someone else stumbles upon this post. I think the original post was intending to get the depth from the point cloud and not the mesh. similar to the ```MeshRasterizer``` as pointed out by @gkioxari , the ```PointsRasterizer``` also returns a ```PointFragment``` object, which contains the ```zbuf``` attribute that can be used for depth. (https://github.com/facebookresearch/pytorch3d/blob/7aeedd17a4140eef139987e946a7017df7a97433/pytorch3d/renderer/points/rasterizer.py#L145).
For the format of ```zbuf```, have a look here: https://github.com/facebookresearch/pytorch3d/blob/7aeedd17a4140eef139987e946a7017df7a97433/pytorch3d/renderer/points/rasterize_points.py#L75

concept of z-buffers explained here: https://www.scratchapixel.com/lessons/3d-basic-rendering/rasterization-practical-implementation/visibility-problem-depth-buffer-depth-interpolation.html
