### ISSUE TITLE
Support for multiple lighting source for rendering

### ISSUE THREAD

**Issue by hangg7** [facebookresearch/pytorch3d#241]
## Motivation

Currently the renderer forward method only support one lighting per batch, this limits the usage of this library for more complex neural rendering training. 

For example, to obtain a visually appealing rendering of a object with smooth texturing, it is not effective to contrast shadows with a single lighting source.

Multi-lighting configuration is also a common functionality in OpenGL and its related third-party libararies, such as pyrender.

## Pitch

Having not digged too much about this feature, but to me, it seems like the easiest way of adding this new feature is to construct a multi-lighting class that accecpt currently lighting objects as a list.
```python
lights = MultiLights([
	directional_lights_a,
	point_lights_b,
])
shader = shader_cls(..., lights=lights)
```
This would require modifying current diffuse and specular functions, but should be doable. In fact, this feature, hopefully, seems to be a [TODO](https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/renderer/lighting.py#L46) on this library's developing plan. 

Also see https://github.com/facebookresearch/pytorch3d/issues/178 for similar discussion.

**Comment by mh-nyris** [comment]
@nikhilaravi, I wanted to ask whether this is still on the TODO list?

**Comment by hangg7** [comment]
@nikhilaravi I am closing this now due to no response.

**Comment by patrikhuber** [comment]
I think there are two different scenarios:

1) Two (or more) different types of lights - for example, one `PointLights` and one `DirectionalLights`. From what I gather, PyTorch3D does not support this as of today.

2) One _type_ of lights, but multiple of them: For example, two or more point lights. I've been looking into this today, but the (unclear/lack of) documentation makes it really hard to figure out what is supported and what the code does. `PointLights` is plural, suggesting multiple lights, and it can take a tensor of values, for example the follow code is possible:

```
ambient_colors  = torch.tensor([[0.5, 0.5, 0.5],[0.6, 0.6, 0.6]], dtype=torch.float32, device=device)
diffuse_colors  = torch.tensor([[0.3, 0.3, 0.3],[0.4, 0.4, 0.4]], dtype=torch.float32, device=device)
specular_colors = torch.tensor([[0.1, 0.1, 0.1],[0.2, 0.2, 0.2]], dtype=torch.float32, device=device)
light_locations = torch.tensor([[1.0, 2.0, 3.0],[4.0, 5.0, 6.0]], dtype=torch.float32, device=device)

lights = pytorch3d.renderer.lighting.PointLights(device=device,
												 ambient_color=ambient_colors,
												 diffuse_color=diffuse_colors,
												 specular_color=specular_colors,
												 location=light_locations)
```
But when rendering, on even a small resolution, this then crashes with an out-of-memory error, trying to allocate 24 GB of VRAM, whereas it works fine with just one light. And @bottler wrote here https://github.com/facebookresearch/pytorch3d/issues/784#issuecomment-892462254 that this is not supported, although that was in 2021. I've tried looking at the code, but I'm not sure if this is supposed to work or not, as PyTorch3D usually uses `N` (or `P`) as the batch dimension. And it is not clear to me how the batch dimension plays together with the above definition of multiple lights - the code may or may not be trying to do the correct thing.

@gkioxari @nikhilaravi @bottler might you be able to offer any insights? What does it do if you specify multiple elements when defining a `PointLights` as in the code above, is this supposed to work or does it do something unexpected with the batch dimension?

Thanks a lot.

**Comment by patrikhuber** [comment]
> Multiple point lights in a scene is not supported. The plural name PointLights is just because it represents one light in each scene of the batch of scenes.

Thanks a lot Jeremy. Do you think there's a chance of implementing multiple point lights with a custom Phong shader, based on the SoftPhongShader, without too much effort?
