### ISSUE TITLE
Rasterize points in non-square images

### ISSUE THREAD

**Issue by phongnhhn92** [facebookresearch/pytorch3d#242]
Hello,
I am interested in using this function to rasterize 3D point cloud of features to the features itself but the current implementation only support square feature maps. Is there any plan that you guys can support non-square image ? 
I am willing to help to edit the C++ source code if possible.

https://github.com/facebookresearch/pytorch3d/blob/2ea6a7d8ad219c7b0a8b557b1ddcc2bfba450875/pytorch3d/renderer/points/rasterize_points.py#L15

**Comment by gkioxari** [comment]
As mentioned in this issue: https://github.com/facebookresearch/pytorch3d/issues/17. 
We plan on adding support for non-square images in rasterization in the future

**Comment by nikhilaravi** [comment]
This feature is now available in PyTorch3D. Please read [this note](https://github.com/facebookresearch/pytorch3d/blob/master/docs/notes/renderer_getting_started.md#rasterizing-non-square-images) for details on how to set the (H, W) correctly for rasterizing non square images.
