### ISSUE TITLE
Rendering texture mesh that has multiple texture maps, with different width, height image

### ISSUE THREAD

**Issue by manhha1402** [facebookresearch/pytorch3d#245]
Hi,
I tested the rendering of texture mesh in the tutorial:
https://github.com/facebookresearch/pytorch3d/blob/master/docs/tutorials/render_textured_meshes.ipynb
I think it is not possible to read and render texture mesh that has multiple texture maps. It it right?

And the rendering algorithm, the rasterization only support image width = image height, for example, image_size=512
raster_settings = RasterizationSettings(
    image_size=512, 
    blur_radius=0.0, 
    faces_per_pixel=1, 
) 
How can I render texture mesh which produces image height different from image width?
Thank you.

**Comment by nikhilaravi** [comment]
Hi @manhha1402 - currently you can load a mesh which has multiple texture maps into a meshes object (use the `create_texture_atlas=True` flag in `load_obj`). The texture atlas (of shape `(F, R, R, 3)`) is available from `aux.texture_atlas` in the outputs of `load_obj`.  Here is the full documentation for the `load_obj` function: https://pytorch3d.readthedocs.io/en/latest/modules/io.html

You are correct that currently we only support rendering images with the same height and width. We are planning to add support for non square images soon.

**Comment by manhha1402** [comment]
Hi @nikhilaravi ,
Thank you for your support. 
In this case, if I load obj_file as `verts, faces, aux = load_obj(obj_file,load_textures=True,create_texture_atlas=True)`. Do you know how can I convert `verts,faces,aux` elements to a `texture_mesh` that is loaded by the function `texture_mesh = load_objs_as_meshes([obj_file], device=device)`. So that I can use it for rendering the texture mesh?

**Comment by nikhilaravi** [comment]
Hi @manhha1402 here is a complete example of how to load the textures as an atlas, create a mesh and and render it: https://github.com/facebookresearch/pytorch3d/blob/master/tests/test_render_meshes.py#L468. 

I am closing this issue but feel free to reopen it if you have any problems.
