### ISSUE TITLE
Voxel renderer

### ISSUE THREAD

**Issue by imlixinyang** [facebookresearch/pytorch3d#247]
Will pytorch3d support voxel renderer in the future?

**Comment by gkioxari** [comment]
Yes!

**Comment by nikhilaravi** [comment]
Volume rendering is in our roadmap! We can leave this issue open until this feature is available in master.

**Comment by unlugi** [comment]
Has there been any progress for a voxel renderer?

**Comment by kjchalup** [comment]
Hi, long time no update :) But yes we have a VolumeRenderer now, see https://github.com/facebookresearch/pytorch3d/blob/main/pytorch3d/renderer/implicit/renderer.py#L200

The renderer.implicit module has a few raymarchers and raysamplers you can try out. Also, the recently released [Implicitron](https://ai.facebook.com/blog/implicitron-a-new-modular-extensible-framework-for-neural-implicit-representations-in-pytorch3d/) project adds many more tools that might be useful in this direction!
