### ISSUE TITLE
Textured mesh rendering using per face texture map

### ISSUE THREAD

**Issue by tejank10** [facebookresearch/pytorch3d#248]
Hello there,

I am porting my existing code from SoftRas to Pytorch3D. I am trying to do textured rendering in surface texture mode, where the textures are of the form 'F x Tex_res*Tex_res x 3'. It denotes a texture map for each face, which is of spatial dimension `Tex_res x Tex_res'. 

However, `Textures` structure of PyTorch3D accepts textures in a different format. That requires me to have a texture map for the whole mesh and also face and vertex uvs, which I am not having.
Can you please point me to the right direction in order to achieve similar behavior as that of SoftRas by using PyTorch3D? 
Thanks in advance.

**Comment by nikhilaravi** [comment]
@tejank10 we have a new textures API coming very soon which will enable rendering with the per face textures. We will try to get this into master ASAP.

**Comment by nikhilaravi** [comment]
@tejank10 support for texture atlassing has now been added. Here is a complete example of how to load the textures as an atlas, create a mesh and and render it: https://github.com/facebookresearch/pytorch3d/blob/master/tests/test_render_meshes.py#L468.

**Comment by tejank10** [comment]
Thanks @nikhilaravi !
