### ISSUE TITLE
cuda errors

### ISSUE THREAD

**Issue by sinanmut** [facebookresearch/pytorch3d#25]
Hi, 
I tried to install the package with "python3 setup.py install --user" but I got a few errors:
- pytorch3d/csrc/nearest_neighbor_points/nearest_neighbor_points.cu(231): error: a pointer to a bound function may only be used to call the function
- pytorch3d/csrc/nearest_neighbor_points/nearest_neighbor_points.cu(231): error: type name is not allowed
- pytorch3d/csrc/nearest_neighbor_points/nearest_neighbor_points.cu(231): error: expected an expression

and same errors for line 245. Is it related to the cuda version, the version I have is 10.0?

Thanks in advance.

**Comment by bottler** [comment]
Cuda 10.0 should be fine. Can you give some more details about your environment: which operating system are you running on? Are you using a new conda environment? Thanks

**Comment by sinanmut** [comment]
Hi, 
Thanks for the quick reply. I am on CentOS 7 (Linux 3.10.0-957.27.2.el7.x86_64) and I am behind a firewall so I don't have direct internet access. The gcc version on my desktop is 5.5.0. The specific cuda version: release 10.0, V10.0.130

Thanks a lot

**Comment by sinanmut** [comment]
Hi, 
It was my mistake that my pytorch version was older than 1.4. It is solved now. 
Thanks again

**Comment by nikhilaravi** [comment]
@sinanmut glad you resolved the issue. I will close this issue!
