### ISSUE TITLE
Undersampled images in documentation

### ISSUE THREAD

**Issue by eliemichel** [facebookresearch/pytorch3d#255]
Particularily [transformations_overview.png](https://github.com/facebookresearch/pytorch3d/blob/master/docs/notes/assets/transformations_overview.png) is close to being unreadable. On other images it is more a problem of some lines using a very small font.

**Comment by gkioxari** [comment]
Thank you for the feedback. We will try to release higher resolution images.

**Comment by nikhilaravi** [comment]
Thanks for pointing this out and for reading the documentation! I will update the images!

**Comment by gkioxari** [comment]
We have updated the images with higher resolution versions. Closing this!
