### ISSUE TITLE
Not compiled with gpu support error while installing on system. 

### ISSUE THREAD

**Issue by rohitdavas** [facebookresearch/pytorch3d#257]
Hi, 
I have been trying to install the pytorch3d on my system.

1. using conda : the python version error throws. which I can fix by using a virtual environment and using older version of python
2. using pip from `!pip install 'git+https://github.com/facebookresearch/pytorch3d.git@stable'  ` installs it in the current environment but later while using renderer, **it throws error that it is not compiled with gpu support** .

I want to mention that I am using WSL2, where cuda is installed and able to use for torch. I checked it with` torch.cuda.is_available` and it's there. 

Can you suggest something. 

Here is the error : 

RuntimeError: Not compiled with GPU support (RasterizeMeshesCoarse at /tmp/pip-req-build-2pqcx156/pytorch3d/csrc/rasterize_meshes/rasterize_meshes.h:275)
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6d (0x7f5c4c246e7d in /home/rohit/anaconda3/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x13ba0 (0x7f5be5dabba0 in /home/rohit/anaconda3/lib/python3.7/site-packages/pytorch3d/_C.cpython-37m-x86_64-linux-gnu.so)
frame #2: RasterizeMeshes(at::Tensor const&, at::Tensor const&, at::Tensor const&, int, float, int, int, int, bool, bool) + 0x70 (0x7f5be5db9c30 in /home/rohit/anaconda3/lib/python3.7/site-packages/pytorch3d/_C.cpython-37m-x86_64-linux-gnu.so)
frame #3: <unknown function> + 0x370ee (0x7f5be5dcf0ee in /home/rohit/anaconda3/lib/python3.7/site-packages/pytorch3d/_C.cpython-37m-x86_64-linux-gnu.so)
frame #4: <unknown function> + 0x31174 (0x7f5be5dc9174 in /home/rohit/anaconda3/lib/python3.7/site-packages/pytorch3d/_C.cpython-37m-x86_64-linux-gnu.so)
frame #5: _PyMethodDef_RawFastCallKeywords + 0x264 (0x5599342ddc94 in /home/rohit/anaconda3/bin/python)
frame #6: _PyCFunction_FastCallKeywords + 0x21 (0x5599342dddb1 in /home/rohit/anaconda3/bin/python)
frame #7: _PyEval_EvalFrameDefault + 0x4dee (0x5599343495be in /home/rohit/anaconda3/bin/python)
frame #8: _PyEval_EvalCodeWithName + 0x2f9 (0x55993428d2b9 in /home/rohit/anaconda3/bin/python)
frame #9: _PyFunction_FastCallDict + 0x1d5 (0x55993428e3e5 in /home/rohit/anaconda3/bin/python)
frame #10: THPFunction_apply(_object*, _object*) + 0xa26 (0x7f5c35466826 in /home/rohit/anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #11: _PyMethodDef_RawFastCallKeywords + 0x1e0 (0x5599342ddc10 in /home/rohit/anaconda3/bin/python)
frame #12: _PyCFunction_FastCallKeywords + 0x21 (0x5599342dddb1 in /home/rohit/anaconda3/bin/python)
frame #13: _PyEval_EvalFrameDefault + 0x4dee (0x5599343495be in /home/rohit/anaconda3/bin/python)
frame #14: _PyEval_EvalCodeWithName + 0x2f9 (0x55993428d2b9 in /home/rohit/anaconda3/bin/python)
frame #15: _PyFunction_FastCallKeywords + 0x387 (0x5599342dd497 in /home/rohit/anaconda3/bin/python)
frame #16: _PyEval_EvalFrameDefault + 0x14ea (0x559934345cba in /home/rohit/anaconda3/bin/python)
frame #17: _PyEval_EvalCodeWithName + 0x2f9 (0x55993428d2b9 in /home/rohit/anaconda3/bin/python)
frame #18: _PyFunction_FastCallDict + 0x1d5 (0x55993428e3e5 in /home/rohit/anaconda3/bin/python)
frame #19: _PyObject_Call_Prepend + 0x63 (0x5599342acb93 in /home/rohit/anaconda3/bin/python)
frame #20: PyObject_Call + 0x6e (0x55993429f95e in /home/rohit/anaconda3/bin/python)
frame #21: _PyEval_EvalFrameDefault + 0x1d4a (0x55993434651a in /home/rohit/anaconda3/bin/python)
frame #22: _PyEval_EvalCodeWithName + 0x2f9 (0x55993428d2b9 in /home/rohit/anaconda3/bin/python)
frame #23: _PyFunction_FastCallDict + 0x1d5 (0x55993428e3e5 in /home/rohit/anaconda3/bin/python)
frame #24: _PyObject_Call_Prepend + 0x63 (0x5599342acb93 in /home/rohit/anaconda3/bin/python)
frame #25: <unknown function> + 0x16c16a (0x5599342e416a in /home/rohit/anaconda3/bin/python)
frame #26: PyObject_Call + 0x6e (0x55993429f95e in /home/rohit/anaconda3/bin/python)
frame #27: _PyEval_EvalFrameDefault + 0x1d4a (0x55993434651a in /home/rohit/anaconda3/bin/python)
frame #28: _PyEval_EvalCodeWithName + 0x2f9 (0x55993428d2b9 in /home/rohit/anaconda3/bin/python)
frame #29: _PyFunction_FastCallDict + 0x1d5 (0x55993428e3e5 in /home/rohit/anaconda3/bin/python)
frame #30: _PyObject_Call_Prepend + 0x63 (0x5599342acb93 in /home/rohit/anaconda3/bin/python)
frame #31: PyObject_Call + 0x6e (0x55993429f95e in /home/rohit/anaconda3/bin/python)
frame #32: _PyEval_EvalFrameDefault + 0x1d4a (0x55993434651a in /home/rohit/anaconda3/bin/python)
frame #33: _PyEval_EvalCodeWithName + 0x2f9 (0x55993428d2b9 in /home/rohit/anaconda3/bin/python)
frame #34: _PyFunction_FastCallDict + 0x1d5 (0x55993428e3e5 in /home/rohit/anaconda3/bin/python)
frame #35: _PyObject_Call_Prepend + 0x63 (0x5599342acb93 in /home/rohit/anaconda3/bin/python)
frame #36: <unknown function> + 0x16c16a (0x5599342e416a in /home/rohit/anaconda3/bin/python)
frame #37: _PyObject_FastCallKeywords + 0x48b (0x5599342e500b in /home/rohit/anaconda3/bin/python)
frame #38: _PyEval_EvalFrameDefault + 0x49b6 (0x559934349186 in /home/rohit/anaconda3/bin/python)
frame #39: _PyEval_EvalCodeWithName + 0x2f9 (0x55993428d2b9 in /home/rohit/anaconda3/bin/python)
frame #40: PyEval_EvalCodeEx + 0x44 (0x55993428e1d4 in /home/rohit/anaconda3/bin/python)
frame #41: PyEval_EvalCode + 0x1c (0x55993428e1fc in /home/rohit/anaconda3/bin/python)
frame #42: <unknown function> + 0x1dc2ed (0x5599343542ed in /home/rohit/anaconda3/bin/python)
frame #43: _PyMethodDef_RawFastCallKeywords + 0xe9 (0x5599342ddb19 in /home/rohit/anaconda3/bin/python)
frame #44: _PyCFunction_FastCallKeywords + 0x21 (0x5599342dddb1 in /home/rohit/anaconda3/bin/python)
frame #45: _PyEval_EvalFrameDefault + 0x46c4 (0x559934348e94 in /home/rohit/anaconda3/bin/python)
frame #46: _PyGen_Send + 0x2a2 (0x5599342e5cb2 in /home/rohit/anaconda3/bin/python)
frame #47: _PyEval_EvalFrameDefault + 0x1a87 (0x559934346257 in /home/rohit/anaconda3/bin/python)
frame #48: _PyGen_Send + 0x2a2 (0x5599342e5cb2 in /home/rohit/anaconda3/bin/python)
frame #49: _PyEval_EvalFrameDefault + 0x1a87 (0x559934346257 in /home/rohit/anaconda3/bin/python)
frame #50: _PyGen_Send + 0x2a2 (0x5599342e5cb2 in /home/rohit/anaconda3/bin/python)
frame #51: _PyMethodDef_RawFastCallKeywords + 0x8d (0x5599342ddabd in /home/rohit/anaconda3/bin/python)
frame #52: _PyMethodDescr_FastCallKeywords + 0x4f (0x5599342e4aef in /home/rohit/anaconda3/bin/python)
frame #53: _PyEval_EvalFrameDefault + 0x4bac (0x55993434937c in /home/rohit/anaconda3/bin/python)
frame #54: _PyFunction_FastCallKeywords + 0xfb (0x5599342dd20b in /home/rohit/anaconda3/bin/python)
frame #55: _PyEval_EvalFrameDefault + 0x416 (0x559934344be6 in /home/rohit/anaconda3/bin/python)
frame #56: _PyFunction_FastCallKeywords + 0xfb (0x5599342dd20b in /home/rohit/anaconda3/bin/python)
frame #57: _PyEval_EvalFrameDefault + 0x6a0 (0x559934344e70 in /home/rohit/anaconda3/bin/python)
frame #58: _PyEval_EvalCodeWithName + 0x2f9 (0x55993428d2b9 in /home/rohit/anaconda3/bin/python)
frame #59: _PyFunction_FastCallDict + 0x400 (0x55993428e610 in /home/rohit/anaconda3/bin/python)
frame #60: _PyObject_Call_Prepend + 0x63 (0x5599342acb93 in /home/rohit/anaconda3/bin/python)
frame #61: PyObject_Call + 0x6e (0x55993429f95e in /home/rohit/anaconda3/bin/python)
frame #62: _PyEval_EvalFrameDefault + 0x1d4a (0x55993434651a in /home/rohit/anaconda3/bin/python)
frame #63: _PyEval_EvalCodeWithName + 0x5da (0x55993428d59a in /home/rohit/anaconda3/bin/python)

If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## 🐛 Bugs / Unexpected behaviors

NOTE: Please look at the existing list of Issues tagged with the label ['bug`](https://github.com/facebookresearch/pytorch3d/issues?q=label%3Abug). **Only open a new issue if this bug has not already been reported. If an issue already exists, please comment there instead.**.

## Instructions To Reproduce the Issue:

Please include the following (depending on what the issue is):

1. Any changes you made (`git diff`) or code you wrote
```
<put diff or code here>
```
2. The exact command(s) you ran:
3. What you observed (including the full logs):
```
<put logs here>
```

Please also simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

**Comment by MoyGcc** [comment]
I also met the same problem when I was trying to run the tutorial code on Colab. If I upload the code directly from GitHub, then it's ok. But if I copy-paste all the code to a new .ipynb file and run it, the "Runtime Error: Not compiled with GPU support" will occur. I checked the Notebook setting and the difference is whether the runtime type is pytorch3d (local) or Python 3. Could someone help with this issue? Thanks in advance!

**Comment by qyzdao** [comment]
Hi, I have similar issue "Not compiled with GPU support" while torch.cuda.is_available() returns True. I solve this problem by upgrading pytorch version from 1.4 to 1.5.1. Pytorch 1.5.0 doesn't work either. My environment is RTX 2080ti and CUDA10.1.

**Comment by hiyyg** [comment]
Does pytorch3d support pytorch 1.4? I also met this problem.

**Comment by bottler** [comment]
I think the various people commenting here are suffering different things. The latest release (which is the stable tag) of pytorch3d supports pytorch 1.4.0, 1.5.0 and 1.5.1. The current master branch of pytorch3d supports pytorch 1.4.0, 1.5.0, 1.5.1, and 1.6.0, and you can get conda builds of it from the pytorch3d-nightly channel.

@MoyGcc On colab, when you create a new notebook, you may need to manually choose to have a GPU available.

@rohitdavas I recommend trying again in conda. Create a new conda environment (I think this is what you mean by virtual environment) and activate it and install pytorch3d's dependencies. You can use python 3.6 or 3.7 or 3.8. You can then install pytorch3d either release or nightly.

**Comment by rohitdavas** [comment]
thanks.

**Comment by Flock1** [comment]
@bottler, I am getting the error `RuntimeError: Not compiled with GPU support.` when I run the plotting cell in `deform_source_mesh_to_target_mesh.ipynb` tutorial. 

I have CUDA 10.1, pytorch 1.5.1 (1.6 is not working with pytorch3d), torchvisin 0.6.1 and python 3.8. Can you help me?

**Comment by bottler** [comment]
@Flock1 Please open a new issue for a new problem. It isn't good that this issue has been hijacked from the original post. To help, we need to know all about how you installed pytorch3d (and the new issue template will remind you of this.)

**Comment by Flock1** [comment]
Hey @bottler, thank you. I have created a new issue.

**Comment by bottler** [comment]
I'm closing this issue because it contains a mix of threads, which seem to be resolved or dormant.
