### ISSUE TITLE
How can I do a faster rendering?

### ISSUE THREAD

**Issue by densechen** [facebookresearch/pytorch3d#259]
Hi,
    When I use pytorch3d to do a rendering of 640x480 RGBD image, it takes almost 1 second to do that on a TITANX GPU.
How can I speed up this process?

**Comment by nikhilaravi** [comment]
Can you share what rasterization settings you are using and the size of the mesh?

**Comment by densechen** [comment]
@nikhilaravi The size of model is about 2000 vertexs and 2000 faces. We use the following settings for obtaining a mask and rgbd image:
`

def define_camera(image_size=640,
                  image_height=480,
                  image_width=640,
                  fx=500,
                  fy=500,
                  cx=320,
                  cy=240,
                  device="cuda:0"):
    # define camera
    cameras = OpenGLRealPerspectiveCameras(
        focal_length=((fx, fy), ),  # Nx2
        principal_point=((cx, cy),),  # Nx2
        # x0=cx - 6 - image_width / 2,
        x0=0,
        y0=0,
        w=image_size,
        h=image_size,
        znear=0.01,
        zfar=10.0,
        device=device)

    # To blend the 100 faces we set a few parameters which control the opacity and the sharpness of edges. Refer to blending.py for more details.
    blend_params = BlendParams(sigma=1e-4, gamma=1e-4)

    # Define the settings for rasterization and shading. Here we set the output image to be of size 640x640. To form the blended image we use 100 faces for each pixel. Refer to rasterize_meshes.py for an explanation of this parameter.
    silhouette_raster_settings = RasterizationSettings(
        image_size=image_size,  # longer side or scaled longer side
        # blur_radius=np.log(1. / 1e-4 - 1.) * blend_params.sigma,
        blur_radius=0.0,
        # The nearest faces_per_pixel points along the z-axis.
        faces_per_pixel=100,
        bin_size=0)

    # Create a silhouette mesh renderer by composing a rasterizer and a shader
    silhouete_renderer = MeshRenderer(
        rasterizer=MeshRasterizer(cameras=cameras,
                                  raster_settings=silhouette_raster_settings),
        shader=SoftSilhouetteShader(blend_params=blend_params)).to(device)

    # We will also create a phong renderer. This is simpler and only needs to render one face per pixel.
    phong_raster_settings = RasterizationSettings(image_size=image_size,
                                                  blur_radius=0.0,
                                                  faces_per_pixel=1,
                                                  bin_size=0)

    # We can add a point light in front of the object.
    lights = PointLights(device=device, location=((
        2.0,
        2.0,
        -2.0,
    ), ))
    phong_renderer = MeshRendererDepth(
        rasterizer=MeshRasterizer(cameras=cameras,
                                  raster_settings=phong_raster_settings),
        shader=TexturedSoftPhongShader(device=device,
                                       lights=lights)).to(device)

    return silhouete_renderer, phong_renderer

`

**Comment by jcjohnson** [comment]
There are two easy things you can change in your `RasterizationSettings` that should give you a good speedup:

1. Change `bin_size`; by setting `bin_size=0` you are invoking the naive rasterizer, which is quite slow; the coarse-to-fine rasterizer should be much faster. The easiest fix is setting `bin_size=None` which will invoke the coarse-to-fine rasterizer using our built-in heuristics for bin size. You can also try manually tuning the bin size (try different powers of two) for your application, which might work better than the built-in heuristics. These changes should give you the same rendered images as your current settings, but faster.
2. Reduce `faces_per_pixel` from 100 to something smaller (maybe 50 or 10). This will result in images that are different than your current settings, so this may affect the performance of your downstream task.

**Comment by densechen** [comment]
@jcjohnson Thanks a lot. The advice is useful.
