### ISSUE TITLE
Texture mesh based on a reference image. 

### ISSUE THREAD

**Issue by vikashranjan** [facebookresearch/pytorch3d#265]
## ❓ Questions on how to use PyTorch3D

In the tutorial notebook render_textured_meshes.ipynb cow_mesh/cow.obj has textures. I would like to know if an untextured mesh can be textured using a reference image.

For example https://github.com/hiroharu-kato/neural_renderer

**Comment by gkioxari** [comment]
Hi @vikashranjan 

Yes, the texture representation and functions we provide are not specific to particular textured images. So you could use any texture image. I think your question could be better rephrased as "What texture representations do you allow and how can I define textures for 3D objects". Currently, we support a few texture representations 
* UV images: In this representation, an image is used as a texture and uv coordinates index to the texture image to assign the RGB colors for each vertex. This is the representation used for the cow example. The choice of the texture image is not relevant and it can be anything. But note that the uv coordinates matter when indexing and assigning texture to vertices.  This is also the example in NMR that you reference with the teapot

* Vertex textures: A mesh is defined by vertices of shape Vx3 which denote the 3D coordinates of vertices, and faces of shape Fx3 which are used to index into the vertices to form the triangles. In addition, verts texture of shape Vx3 hold the RGB values for each vertex in the mesh which at rendering time are interpolated and projected to 2D (based on your choice of shader and blending).

**Comment by vikashranjan** [comment]
Thanks for your response !

**Comment by nikhilaravi** [comment]
@vikashranjan we have recently added a new tutorial on [fitting a mesh with texture](https://github.com/facebookresearch/pytorch3d/blob/master/docs/tutorials/fit_textured_mesh.ipynb). 

The texture API restructuring has also now been landed. Here is a diagram of the different texturing options now available:
 
![texturing](https://user-images.githubusercontent.com/5912647/88949750-817aac00-d248-11ea-8308-376ba54cc38d.png)

**Comment by vikashranjan** [comment]
thanks @nikhilaravi
