### ISSUE TITLE
All vertex share the same faces, how to save gpu memory

### ISSUE THREAD

**Issue by fanfanda** [facebookresearch/pytorch3d#266]
## ❓ Questions on how to call func pytorch3d.structures.Meshes

Nice work! However, I have some problem in func Meshes. In my code, I use batch rendering. So when I call the Meshes function, I pass in parameters verts = [batch_size, verts_num, 3], faces = [batch_size, faces_num, 3] and textures = [batch_size, verts_num, 3]. Because all verts share the same faces structure, so the gpu memory is wasted. But if I pass faces = [1, faces_num, 3] will cause an error. I would like to ask if there is any way to solve it? Thanks you~

**Comment by bottler** [comment]
If `faces` has shape `[1,faces_num,3]` you can create a tensor `expanded_faces = faces.expand(batch_size,faces_num,3)` which means a tensor of the required shape without using more memory. It works by having multiple parts of the same tensor point to the same place in the original tensor. You can pass `expanded_faces` to `Meshes`. Does that help?

**Comment by fanfanda** [comment]
Yes, I got it~ Thank you so much!
