### ISSUE TITLE
How to transform an input point to the coordinate of the rendered image?

### ISSUE THREAD

**Issue by Gaozhongpai** [facebookresearch/pytorch3d#269]
![image](https://user-images.githubusercontent.com/4093624/87276201-6f8fce00-c512-11ea-9d60-ec944c246c62.png)

How to transform the input point `(p_x, p_y, p_z)` to rendered image`(I_x, I_y)`

I found this: 
```
output = cameras.transform_points(input)
```
But this doesn't seem right.

**Comment by Gaozhongpai** [comment]
I found this:

https://github.com/facebookresearch/pytorch3d/blob/f358b9b14dbc1414c588f308b35f55705d777873/pytorch3d/csrc/rasterize_meshes/rasterize_meshes_cpu.cpp#L12-L15

I implement NdcToPix as 
```
    def NdcToPix(xy, S):
        return ((xy + 1) * S - 1.0) / 2
```

Is it correct to do the transformation as 
`output = NdcToPix(cameras.transform_points(input), 256)
`

**Comment by gkioxari** [comment]
This question is not related to PyTorch3D. The answer you are looking for is in the codebase. Also, please read Andrew Zisserman and Richard Hartley textbook on Multi-view Geometry to understand the math. Closing this.

**Comment by Gaozhongpai** [comment]
> This question is not related to PyTorch3D. The answer you are looking for is in the codebase. Also, please read Andrew Zisserman and Richard Hartley textbook on Multi-view Geometry to understand the math. Closing this.

Why this is not related to PyTorch3D. Transformation from input points to rendered image is important for many situations. I suggest please add this feature to Pytorch3D. Plus, I believe the NDC coordinate is flipped. I did several tests. It seems that I need to flip the NDC coordinate first to make it right, as below. 

```
def NdcToPix(xy, S):
        return ((-xy + 1) * S - 1.0) / 2
```

**Comment by Gaozhongpai** [comment]
I wondered whether the flipped issue https://github.com/facebookresearch/pytorch3d/issues/78#issue-568293716 is related.
