### ISSUE TITLE
Unexpceted when rendering a textureed mesh

### ISSUE THREAD

**Issue by BaldrLector** [facebookresearch/pytorch3d#270]
#144  🐛 Bugs / Unexpected behaviors

There is my code:

any the files

## Instructions To Reproduce the Issue:

```
import numpy as np
import torch
from PIL import Image
from pytorch3d.renderer import (
    look_at_view_transform,
    SfMOrthographicCameras,
    DirectionalLights,
    RasterizationSettings,
    MeshRenderer,
    MeshRasterizer,
    TexturedSoftPhongShader, OpenGLOrthographicCameras, OpenGLPerspectiveCameras
)
from pytorch3d.structures import Meshes, Textures
device = torch.device("cuda:0")
torch.cuda.set_device(device)

def loadmesh(obj, texture):
    verts, faces, aux = load_obj(obj, load_textures=False)
    center = torch.mean(verts, dim=0)
    verts -= center
    verts_uvs = aux.verts_uvs[None, ...]  # (1, V, 2)
    faces_uvs = faces.textures_idx[None, ...]  # (1, F, 3)
    image = np.array(Image.open(texture)) / 255.0
    image = torch.from_numpy(image).unsqueeze(0).float()
    tex = Textures(verts_uvs=verts_uvs, faces_uvs=faces_uvs, maps=image)
    mesh = Meshes(verts=[verts], faces=[faces.verts_idx], textures=tex)
    return mesh.cuda()


def run():
    R, T = look_at_view_transform(1000, 0, 0)
    cameras = OpenGLPerspectiveCameras(znear=0.001, zfar=30.0, aspect_ratio=1.0,
                                       fov=13, degrees=True, R=R, T=T,
                                       device=device)

    raster_settings = RasterizationSettings(
        image_size=1024,
        blur_radius=0,  # or set 1e-8 for Render people
        faces_per_pixel=1,
        cull_backfaces=True,
    )

    lights = DirectionalLights(device=device,
                               ambient_color=((1, 1, 1),),
                               diffuse_color=((0, 0, 0),),
                               specular_color=((0, 0, 0),),
                               direction=((1, 1, 1),))

    rasterizer = MeshRasterizer(
        cameras=cameras,
        raster_settings=raster_settings
    )
    shader = TexturedSoftPhongShader(
        device=device,
        cameras=cameras,
        lights=lights
    )
    renderer = MeshRenderer(
        rasterizer=rasterizer,
        shader=shader
    )
    mesh = loadmesh(None, None)
    image = renderer(mesh)
    image[:, :, :, -1] = (image[:, :, :, -1] > 0)
    img = image[0].cpu().numpy() * 255
    img = img[:, :, :3]
    Image.fromarray(img.astype(np.uint8), 'RGB').show()

```
Then I get a rendered image like this
![image](https://user-images.githubusercontent.com/19874480/87290686-e3d96a00-c530-11ea-9204-f5959e1eaa8c.png)
it seems there is seam in the texture joint regions.

files:
texture : https://www.dropbox.com/s/y8g2omw20vp8ts2/30_0_00.jpg?dl=0
obj: https://www.dropbox.com/s/9kvvljma3rneb3f/BMan0006-HD2-O01P05-S.obj?dl=0

**Comment by gkioxari** [comment]
Can you increase the `blur_radius` in the settings and report back?

**Comment by BaldrLector** [comment]
> Can you increase the `blur_radius` in the settings and report back?

Thanks for your reply, here is results with different `blur_radius `

`blur_radius=1e-4`
![image](https://user-images.githubusercontent.com/19874480/87371345-b5eb3880-c5b7-11ea-9e7f-185d9b4c0c7c.png)

`blur_radius=1e-5`
![image](https://user-images.githubusercontent.com/19874480/87371297-9a802d80-c5b7-11ea-8c1c-e2214e4c011d.png)

`blur_radius=1e-6`
![image](https://user-images.githubusercontent.com/19874480/87371323-a966e000-c5b7-11ea-8ee6-48c9a602c494.png)

it seems `blur_radius ` is may not help to tackle this issue.

**Comment by gkioxari** [comment]
I looked into it. It's a problem with the mesh and the obj & texture, not with PyTorch3D. Here is the visualization using MeshLab. 

![with_meshlab00](https://user-images.githubusercontent.com/4369065/87445994-951de580-c5ad-11ea-9b33-67ca0b801207.png)

**Comment by gkioxari** [comment]
Closing issue.
