### ISSUE TITLE
UnsatisfiableError

### ISSUE THREAD

**Issue by zhengmingzhang** [facebookresearch/pytorch3d#273]
## how to install pytorch3d
i follow the install.md to install pytorch3d
when i run :conda install pytorch3d -c pytorch3d-nightly 
it occured 
"""
UnsatisfiableError: The following specifications were found to be in conflict:
  - pytorch3d
Use "conda info <package>" to see the dependencies for each package.
"""
here is my conda list
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
blas                      1.0                         mkl    defaults
ca-certificates           2020.6.24                     0    defaults
certifi                   2020.6.20                py38_0    defaults
cudatoolkit               10.0.130                      0    defaults
freetype                  2.10.2               h5ab3b9f_0    defaults
fvcore                    0.1.1.post20200711            py_0    conda-forge
intel-openmp              2020.1                      217    defaults
jpeg                      9b                   h024ee3a_2    defaults
lcms2                     2.11                 h396b838_0    defaults
ld_impl_linux-64          2.33.1               h53a641e_7    defaults
libedit                   3.1.20191231         h14c3975_1    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.3.0                hdf63c60_0    defaults
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libpng                    1.6.37               hbc83047_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
libtiff                   4.1.0                h2733197_1    defaults
lz4-c                     1.9.2                he6710b0_0    defaults
mkl                       2020.1                      217    defaults
mkl-service               2.3.0            py38he904b0f_0    defaults
mkl_fft                   1.1.0            py38h23d657b_0    defaults
mkl_random                1.1.1            py38h0573a6f_0    defaults
ncurses                   6.2                  he6710b0_1    defaults
ninja                     1.9.0            py38hfd86e86_0    defaults
numpy                     1.18.5           py38ha1c710e_0    defaults
numpy-base                1.18.5           py38hde5b4d6_0    defaults
olefile                   0.46                       py_0    defaults
openssl                   1.1.1g               h7b6447c_0    defaults
pillow                    7.2.0            py38hb39fc2d_0    defaults
pip                       20.1.1                   py38_1    defaults
portalocker               1.7.0            py38h32f6830_0    conda-forge
python                    3.8.3                hcff3b4d_2    defaults
python_abi                3.8                      1_cp38    conda-forge
pytorch                   1.4.0           py3.8_cuda10.0.130_cudnn7.6.3_0    pytorch
pyyaml                    5.3.1            py38h1e0a361_0    conda-forge
readline                  8.0                  h7b6447c_0    defaults
setuptools                47.3.1                   py38_0    defaults
six                       1.15.0                     py_0    defaults
sqlite                    3.32.3               h62c20be_0    defaults
tabulate                  0.8.7              pyh9f0ad1d_0    conda-forge
termcolor                 1.1.0                      py_2    conda-forge
tk                        8.6.10               hbc83047_0    defaults
torchvision               0.5.0                py38_cu100    pytorch
tqdm                      4.47.0             pyh9f0ad1d_0    conda-forge
wheel                     0.34.2                   py38_0    defaults
xz                        5.2.5                h7b6447c_0    defaults
yacs                      0.1.6                      py_0    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zlib                      1.2.11               h7b6447c_3    defaults
zstd                      1.4.4                h0b5b093_3    defaults

**Comment by bottler** [comment]
Can you try `conda install -v -c pytorch3d-nightly pytorch3d`. It might detail more about the conflict. Maybe also paste the output of `conda info`.

The particular package which should work, I think, is https://anaconda.org/pytorch3d-nightly/pytorch3d/0.2.0/download/linux-64/pytorch3d-0.2.0-py38_cu100_pyt14.tar.bz2 . With that one I can't see why you would have a conflict.

There should be some way to get conda to try this package first/only, but I don't know exactly how.

You could download that package and then conda install the local file.

**Comment by zhengmingzhang** [comment]
thank you very much!I try your method, and i installed successfully☺️
