### ISSUE TITLE
How to get the 3d vertex coordinates from the render image?

### ISSUE THREAD

**Issue by silence401** [facebookresearch/pytorch3d#274]
## ❓How to get the 3d vertex coordinates from the render image?
I try to get 3d points from the render image and it's depth, but I am confused about the input of cameras.unproject_points(). I input the coordinate of screen space. （XYD，x in [0,w] and y in [0,h]). But it get the wrong result, which is show in the follow image is the output points and gt points.
![image](https://user-images.githubusercontent.com/29566012/87397762-6b81b000-c5e7-11ea-8a18-b53c48f4463c.png)

**Comment by nikhilaravi** [comment]
Can you provide a code example so we can reproduce the error?

**Comment by silence401** [comment]
> Can you provide a code example so we can reproduce the error?

thanks for your reply, I solved this problem by input the NDC  coordinate
