### ISSUE TITLE
Mesh optimization using differentiable rendering to fit target image

### ISSUE THREAD

**Issue by odie2630463** [facebookresearch/pytorch3d#285]
There has a tutorial about camera position optimization using differentiable rendering , but I want to know how to optimize mesh to render target image ? 

Thanks

**Comment by gkioxari** [comment]
We will be adding a tutorial very soon!

**Comment by sbranson** [comment]
A tutorial was just added: https://github.com/facebookresearch/pytorch3d/blob/master/docs/tutorials/fit_textured_mesh.ipynb

**Comment by gkioxari** [comment]
Closing issue!
