### ISSUE TITLE
__init__() got an unexpected keyword argument 'composite_params'

### ISSUE THREAD

**Issue by oaishi** [facebookresearch/pytorch3d#288]
Hello, I was trying to run the demo "render_colored_points.ipynb" in Google Colab. However, I got this error message :

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-3bbad19562fa> in <module>()
     17 renderer = PointsRenderer(
     18     rasterizer=PointsRasterizer(cameras=cameras, raster_settings=raster_settings),
---> 19     compositor=AlphaCompositor(composite_params=None)
     20 )

TypeError: __init__() got an unexpected keyword argument 'composite_params'
```

**Comment by gkioxari** [comment]
Hi @oaishi 
We removed `composite_params` as it wasn't actually used in this commit https://github.com/facebookresearch/pytorch3d/commit/3d7dea58e150dae8070b3fea2f1deaf6f8c55106. We will update the tutorial to remove `composite_params`from the tutorial. For now, feel free to just remove the input when you call `AlphaCompositor`.

**Comment by oaishi** [comment]
Thank you so much for your helpful reply.
