### ISSUE TITLE
Wrong render results with OpenGLPerspectiveCameras

### ISSUE THREAD

**Issue by raywzy** [facebookresearch/pytorch3d#289]
Given one obj file, corresponding camera **extrinsics (R T)** and **intrinsics**, I want to render the image with Pytorch3D. Using pyrender which is based on OpenGL, I could get the right rendered results. However, the results of OpenGLPerspectiveCameras of pytorch 3D seems wrong.

**Reuslts of [pyrender](https://github.com/hjwdzh/pyRender) :**
![diffuse](https://user-images.githubusercontent.com/5800781/88673649-72e2a680-d11b-11ea-9df8-129bef61bdb5.png)

**Results of OpenGLPerspectiveCameras :**
![color0_yuanshi](https://user-images.githubusercontent.com/5800781/88673969-cb19a880-d11b-11ea-8a5a-613edac3b17d.png)

**The origin objects:**
![00000_color](https://user-images.githubusercontent.com/5800781/88674052-e84e7700-d11b-11ea-9d34-7a1349a363ec.png)

It seems that the coordinates are all right-hand based, so currently I am a little confused what should I do to solve this problem. I also have tried the **[OpenGLRealPerspectiveCamera](https://gist.github.com/wangg12/32250e352671c7f8c9a42ddb437142a6)**, which allow me to set the intrinsics, but the results still don's seem right:
![color0](https://user-images.githubusercontent.com/5800781/88674574-90fcd680-d11c-11ea-82aa-2b8251119214.png)

**Comment by gkioxari** [comment]
When using rendering engines one question you should always ask yourself and figure out is what the world coordinate system is for that engine. Different engines make different conventions and you can't just plug and play different engines hoping it will work. Our world coordinate system is different than OpenGL. You should figure out the transformation and reflect that in the R,T.

**Comment by nikhilaravi** [comment]
Here is a reference for the coordinate system conventions in PyTorch3D: ![](https://raw.githubusercontent.com/facebookresearch/pytorch3d/master/docs/notes/assets/world_camera_image.png)

If you no longer need help, please close this issue.

**Comment by raywzy** [comment]
@gkioxari @nikhilaravi 
Thanks for your responses. I have fixed this issue :)

**Comment by wangg12** [comment]
@raywzy How did you solve the problem?

**Comment by wangg12** [comment]
Hi @raywzy , how did you fix this issue?

**Comment by raywzy** [comment]
> Hi @raywzy , how did you fix this issue?

@wangg12  Hi Gu, I solve the problem by using your provided projection function :)
