### ISSUE TITLE
meshes.py fails to import in colab notebooks

### ISSUE THREAD

**Issue by yoDon** [facebookresearch/pytorch3d#29]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## Instructions To Reproduce the Issue:

1. Open the [Fit Mesh](https://pytorch3d.org/tutorials/deform_source_mesh_to_target_mesh) tutorial page
1. Click the [Open in Colab](https://colab.research.google.com/github/facebookresearch/pytorch3d/blob/master/docs/tutorials/deform_source_mesh_to_target_mesh.ipynb) link at the top of the page
1. Add a cell to install torchvision and pytorch3d as described in [the tutorial overview](https://pytorch3d.org/tutorials/) and as corrected in https://github.com/facebookresearch/pytorch3d/pull/27 (if not yet merged/published)
1. Run the cell to install torch vision and pytorch3d
1. Run the cell immediately below *0. Import Modules* which includes the line `from pytorch3d.structures import Meshes`

Expected behavior:

Cell succeeds

Actual behavior:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-14-d743ebcdab4d> in <module>()
      2 import torch
      3 from pytorch3d.io import load_obj, save_obj
----> 4 from pytorch3d.structures import Meshes
      5 from pytorch3d.utils import ico_sphere
      6 from pytorch3d.ops import sample_points_from_meshes

1 frames
/usr/local/lib/python3.6/dist-packages/pytorch3d/structures/meshes.py in <module>()
      4 import torch
      5 
----> 6 from pytorch3d import _C
      7 
      8 from . import utils as struct_utils

ImportError: /usr/local/lib/python3.6/dist-packages/pytorch3d/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _Z24RasterizeMeshesNaiveCudaRKN2at6TensorES2_S2_ifib

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

Please include the following (depending on what the issue is):

1. Any changes you made (`git diff`) or code you wrote
```
<put diff or code here>
```
2. The exact command(s) you ran:
3. What you observed (including the full logs):
```
<put logs here>
```

Please also simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

**Comment by sinanmut** [comment]
Hi, 
I have the same error: ImportError: /usr/local/lib/python3.6/dist-packages/pytorch3d/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _Z24RasterizeMeshesNaiveCudaRKN2at6TensorES2_S2_ifib

Is there any solution for this error?
Thanks

**Comment by nikhilaravi** [comment]
While we fix the issue in the installation to get unblocked with the colab notebooks, you can use the anaconda cloud package.  In the first cell few cells in the colab notebook run the following steps:

1) Install anaconda cloud 
Either install miniconda
```
!wget https://repo.continuum.io/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh && bash Miniconda3-4.5.4-Linux-x86_64.sh -bfp /usr/local
```

**OR** Install Anaconda 3.5
```
!wget https://repo.anaconda.com/archive/Anaconda3-5.2.0-Linux-x86_64.sh && bash Anaconda3-5.2.0-Linux-x86_64.sh -bfp /usr/local
```

2) Set path:
```
import sys
sys.path.append('/usr/local/lib/python3.6/site-packages')
```

3) Install pytorch, torchvision and fvcore:
```
!conda install -c pytorch pytorch torchvision cudatoolkit=10.0
!conda install -c conda-forge -c fvcore fvcore
```

4) Install pytorch3d
```
!conda install pytorch3d -c pytorch3d
```

We will resolve the issue on master soon. If you still have questions please let us know.

**Comment by nikhilaravi** [comment]
This is issue now fixed on master so `pip install 'git+https://github.com/facebookresearch/pytorch3d.git'` will work in a colab notebook.
