### ISSUE TITLE
How to optimize the verts_uvs of the mesh texture?

### ISSUE THREAD

**Issue by FengQiaojun** [facebookresearch/pytorch3d#290]
Suppose we have a textured mesh loaded from an obj file using [load_objs_as_meshes()](https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/io/obj_io.py#L230). There is an image as the texture map and the [verts_uvs](https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/structures/textures.py#L125) maps each vertex of the mesh to a uv coordinate on the texture mesh and a color. 

Suppose we fix the mesh faces as well as the texture face uvs [(faces_uvs)](https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/structures/textures.py#L124). Also the texture map remains the same. We want to optimize the verts_uvs based on some image rendering loss, i.e., we change the association from the mesh to the texture map. It should be similar to [deform_source_mesh_to_target_mesh.ipynb](https://github.com/facebookresearch/pytorch3d/blob/master/docs/tutorials/deform_source_mesh_to_target_mesh.ipynb) but the variable is the verts_uvs instead of verts. Is there an existing function like [offset_verts_()](https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/structures/meshes.py#L1222) to change the verts_uvs? If not, will this be added in the future?

Thanks!

**Comment by gkioxari** [comment]
Hi @FengQiaojun 
Your question does not seem to be related to an issue with the codebase but is rather a RnD question. Unfortunately, we can't help with those otherwise that's all we would be doing in our time. We prioritize helping out with bug reports and issues that come with reproducible code. Sorry about that and good luck with your project!

**Comment by raywzy** [comment]
Hi @FengQiaojun
Have you solved this problem? I also want to achieve similar function :)

**Comment by FengQiaojun** [comment]
Hi @raywzy 
Sorry I didn't go further on this. It seems like this is a function that hasn't be implemented yet and it is neither on the near future plan. It would be great if you can explore a bit.

**Comment by FengQiaojun** [comment]
Hi @raywzy, 
I tried again and got some initial results. I followed the [fit_textured_mesh.ipynb](https://github.com/facebookresearch/pytorch3d/blob/master/docs/tutorials/fit_textured_mesh.ipynb) and added deformation to the vertices uv coordinates in the texture. Here is a demo result. The left is the reference RGB image. The middle is the uvs being optimized. The right is their differences. You can see the light diagonals don't move so the mesh vertices are not moving but their uvs on the texture map is changing.
![demo_opt_uv](https://user-images.githubusercontent.com/32551664/90183059-bff38900-dd67-11ea-9ab4-f3bcc0e26f5b.gif)
I put a link to the script that generate this figure and hope this can help!
[demo_opt_uv.py](https://drive.google.com/file/d/1auc_tvFPvAvLzEfRQbWLEp555GKkBNtL/view?usp=sharing)
Thanks.

**Comment by raywzy** [comment]
Hi @FengQiaojun 
Thank you so much! I will try it later :)
