### ISSUE TITLE
Add earth mover's distance in losses?

### ISSUE THREAD

**Issue by wzic** [facebookresearch/pytorch3d#291]
## Motivation

Earth mover's distance is a commonly used metric in calculating the difference between two point clouds. It will be nice if it could be included in the losses. Thank you!

## Pitch

NOTE: we only consider adding new features if they are useful for many users.

**Comment by gkioxari** [comment]
Here is our response to a similar question: https://github.com/facebookresearch/pytorch3d/issues/211

**Comment by wzic** [comment]
Thank you
