### ISSUE TITLE
How does PyTorch3D different from e3nn

### ISSUE THREAD

**Issue by xuzhang5788** [facebookresearch/pytorch3d#292]
Can PyTorch3D  perform the same things as e3nn did? Does PyToch3D only focus on surface data type? How can it be apply to molecules which are not solid inside the volume ( for shape recognition, we only pay attention to the surface of the volume because inside the volume is always solid, we cab ignore it).

**Comment by gkioxari** [comment]
If I understand correctly e3nn is a library that introduces E(3) equivariant neural networks and operations. PyTorch3D is orthogonal to that. You can use the operators introduced by e3nn and use them with PyTorch3D data structures or our renderer the same way you can use any op in PyTorch e.g. `torch.sum()` and use it with PyTorch3D.
