### ISSUE TITLE
Create smpl texture map from Densepose in pytorch3d renderer

### ISSUE THREAD

**Issue by dvirginz** [facebookresearch/pytorch3d#295]
I'm trying to complete a pipeline that I feel a lot of other friends here try to accomplish as well.
Given a smpl model, and a uv map generated from it, I'm trying to apply the texture mapping and rendering using pytorch3d with no success.
When working with the "normal texture map" I.e : 
![image](https://user-images.githubusercontent.com/31047807/90374330-ff79e800-e07b-11ea-80df-8d44dc1c996f.png)

and for example the following texture map
![image](https://user-images.githubusercontent.com/31047807/90374392-19b3c600-e07c-11ea-8f5f-779a0a0bcef0.png)

I get a good rendering:
![image](https://user-images.githubusercontent.com/31047807/90374421-2801e200-e07c-11ea-829a-d00e22b5b021.png)

Unfortunately, when trying to work with other uv maps (as provided by facebook in densepose):
![image](https://user-images.githubusercontent.com/31047807/90374497-410a9300-e07c-11ea-8f88-6b7ed4c49b69.png)
I'm getting a completely black rendered output, even when setting
`tex = torch.ones_like(tex)`
![image](https://user-images.githubusercontent.com/31047807/90374572-5c759e00-e07c-11ea-9b14-1cc03d9eb30e.png)

Here are the aligned texture and uv to make sure they indeed match:
![image](https://user-images.githubusercontent.com/31047807/90374949-f3daf100-e07c-11ea-873f-7f9c8f90565a.png)

My code:
```

tex = torch.from_numpy(atlas_from_file).float().cuda().unsqueeze(0) # torch.Size([1, 1300, 860, 3])
faces = torch.from_numpy(faces.astype(np.int64)).long().cuda().unsqueeze(0) #torch.Size([1, 13774, 3])
v_template= torch.from_numpy(v_template).float().cuda().unsqueeze(0) #torch.Size([1, 7829, 3])
atlas_uv = torch.from_numpy(atlas_uv.transpose(1,0)).float().cuda().unsqueeze(0) #torch.Size([1, 7829, 2])


texture = TexturesUV(maps=(tex / 255.), faces_uvs=faces , verts_uvs=atlas_uv)
mesh = Meshes(v_template, faces , texture)

R, T = look_at_view_transform(dist=2, elev=0, azim=0, up=((0, 1, 0),),)
cameras = OpenGLPerspectiveCameras(R=R, T=T, device=faces .device)
raster_settings = RasterizationSettings(image_size=512, blur_radius=0.0, faces_per_pixel=5,)
lights = PointLights(location=[[0.0, 0.0, 3.0]], device=faces .device)

renderer = MeshRenderer(
    rasterizer=MeshRasterizer(cameras=cameras, raster_settings=raster_settings),
    shader=SoftPhongShader(cameras=cameras, lights=lights, device=v_template.device)
)
images = renderer(mesh)
```

**Comment by nikhilaravi** [comment]
@dvirginz what is the format of the uv coordinates? Do the uv maps range from 0 to 1 with (0,0) as the top left and (1,1) as the bottom right?

**Comment by nikhilaravi** [comment]
@dvirginz where are you getting the vertex UV coordinates from?

**Comment by dvirginz** [comment]
Hi, I've edited the question with a full example and explanation, Thanks!

**Comment by dvirginz** [comment]
> @dvirginz where are you getting the vertex UV coordinates from?

I'm closing this issue as I managed to fix it, it was totally my bug!
thanks:)

**Comment by nikhilaravi** [comment]
@dvirginz that's great! What was the bug?

**Comment by nikhilaravi** [comment]
We now have a new tutorial showing how to render Densepose data with the PyTorch3d differentiable renderer: https://github.com/facebookresearch/pytorch3d/blob/master/docs/tutorials/render_densepose.ipynb.
