### ISSUE TITLE
A simple depth camera to take depth images of simple meshes?

### ISSUE THREAD

**Issue by wzic** [facebookresearch/pytorch3d#296]
Hi! I want to know whether we can use the cameras in pytorch3d to take the depth images of meshes? Here I only want the (x, y, depth) image. No texture on meshes. No light for shading. No complicated rendering. 

For example, some codes like this:
mesh = ...
camera = DepthCamera(camera_pose)
depth_image = camera.take_depth_image(mesh, height, width) # size: (height, width, 1)

Thank you

**Comment by wzic** [comment]
Hi! Does anybody have any thought on this issue?

**Comment by gkioxari** [comment]
Hi @wzic 
Two comments. First, we are here to address issues with the codebase (bug reports with reproducible code). We cannot unfortunately provide answers to how-tos for all users who wish to use the library. So please open an issue if there is a bug in the library that you wish us to fix. Second, and regarding your question, if you want a depth map use our rasterizer and renderer which provides that info. Please read the code/documentation or tech report.

**Comment by wzic** [comment]
Thanks
