### ISSUE TITLE
How to restore 3D model use Pytorch3d

### ISSUE THREAD

**Issue by qiji77** [facebookresearch/pytorch3d#299]
## ❓ Questions on how to use PyTorch3D

First, thank you for this great API! How to restore 3D model from known camera matrix and image? What is the corresponding relationship between pixel and model point in pytorch3d? Can a model point be projected onto multiple pixels I try to restore the model by transforming the matrix of the generated image and depth map, but the number of generated points is far more than that of the original model. What should I do use pytorch3d？

**Comment by nikhilaravi** [comment]
@qiji77 what do you mean by "model point"? Are you referring to a 3D point cloud? Can you provide a full code example of what you are trying to achieve?

The image generated by the Pytorch3D pointcloud renderer is created by blending across the top K closest points which intersect with that pixel in the z direction - the top K values are available in the `fragment` data output from the `PointsRasterizer`. Each point can contribute to the color of multiple pixels.

**Comment by qiji77** [comment]
yes,I don't know how to express myself clearly. For example，I have a mesh with 2306 vertices，and I use MeshRasterizer to  render a image and a zbuf,then,I want to restore this mesh but the restore mesh has more vertices than 2306.So,I want to know how to restore a mesh with 2306 vertices.Thanks for your reply.

**Comment by gkioxari** [comment]
The mesh should remain unchanged after being passed through the rasterizer. So I don't understand what you mean frankly. Could you provide a code snippet with the data that we could use to reproduce your error?

**Comment by gkioxari** [comment]
No response. Closing this issue.
