### ISSUE TITLE
RuntimeError: Not compiled with GPU support

### ISSUE THREAD

**Issue by Flock1** [facebookresearch/pytorch3d#300]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## 🐛 Bugs / Unexpected behaviors

I installed the library and I was running one of the examples `deform_source_mesh_to_target_mesh.ipynb`.
All the libraries have been installed properly but as soon as I reach the visualizing the mesh cell, I get the following error:
```
RuntimeError                              Traceback (most recent call last)
<ipython-input-9-5d95d9be9588> in <module>
      1 get_ipython().run_line_magic('matplotlib', 'notebook')
----> 2 plot_pointcloud(trg_mesh, "Target mesh")
      3 plot_pointcloud(src_mesh, "Source mesh")

<ipython-input-6-2b3f0e41d941> in plot_pointcloud(mesh, title)
      1 def plot_pointcloud(mesh, title=""):
      2     # Sample points uniformly from the surface of the mesh.
----> 3     points = sample_points_from_meshes(mesh, 5000)
      4     x, y, z = points.clone().detach().cpu().squeeze().unbind(1)
      5     fig = plt.figure(figsize=(5, 5))

~/anaconda3/envs/work/lib/python3.8/site-packages/pytorch3d/ops/sample_points_from_meshes.py in sample_points_from_meshes(meshes, num_samples, return_normals)
     54     # Only compute samples for non empty meshes
     55     with torch.no_grad():
---> 56         areas, _ = mesh_face_areas_normals(verts, faces)  # Face areas can be zero.
     57         max_faces = meshes.num_faces_per_mesh().max().item()
     58         areas_padded = packed_to_padded(

~/anaconda3/envs/work/lib/python3.8/site-packages/pytorch3d/ops/mesh_face_areas_normals.py in forward(ctx, verts, faces)
     40 
     41         ctx.save_for_backward(verts, faces)
---> 42         areas, normals = _C.face_areas_normals_forward(verts, faces)
     43         return areas, normals
     44 

RuntimeError: Not compiled with GPU support.
```
My specs are:

GPU: NVIDIA RTX 2070 Super
CUDA: 10.1
Pytorch: 1.5.1
Python: 3.8
OS: Ubuntu 18.04

What am I doing wrong?

**Comment by bottler** [comment]
How did you install? Can you print the output of `pip list` and, if you are using conda, `conda list`?

**Comment by Flock1** [comment]
I installed it using pip because conda wasn't installing it. 
```
pytorch                   1.5.1           py3.8_cuda10.1.243_cudnn7.6.3_0    pytorch
pytorch3d                 0.2.0                    pypi_0    pypi
torchvision               0.6.1                py38_cu101    pytorch
```

**Comment by bottler** [comment]
If you install `pytorch3d` with `pip install pytorch3d` you will get a version without gpu support. This is detailed in the installation instructions. You need to overcome the conda problems or install from source.

**Comment by Flock1** [comment]
Thanks. I have created a new conda environment and followed the exact steps as mentioned on the installation page. Here are some of the problems I faced:

1) When I tried to install using conda, I ran into this problem:
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```
How should I solve this?

**Comment by bottler** [comment]
If you have installed all the dependencies recently, and this is an error from `conda install pytorch3d -c pytorch3d` (or similar), and you are on linux, then the problem is that you have the new version of torch which is newer than (and not supported by) the latest release of Pytorch3D. I recommend installing the nightly build with `conda install pytorch3d -c pytorch3d-nightly` instead.

**Comment by Flock1** [comment]
Hello. When I try to install the nightly version, I get the following:
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pytorch3d -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your CUDA driver:

  - feature:/linux-64::__cuda==11.0=0

Your installed CUDA driver is: 11.0
```
The reason why it's saying `11.0` is because, on the system, I have NVIDIA driver 450 which installed CUDA 11. But in my environment, I have cuda 10.1 installed. 

So I also tried to install from github and I have attached the error [log](https://gist.github.com/Flock1/a4ca89c3d8d2a7d78fb386e14b466e51)

**Comment by bottler** [comment]
When you say you have cuda 10.1 installed, do you mean full CUDA toolkit or just some drivers?

The error log in the gist is saying `which g++` failed, meaning it cannot find `g++`, which is a C++ compiler. You need to set up your build tools (this may be a case of setting environment variables to find them, or actually installing them). For example on a basic ubuntu install you might install a package like `build-essential` to get this. I think it wouldn't make sense to have any cuda toolkit installed if you didn't have a C++ compiler though.

For conda, can you paste the output of `conda list` and `conda info`? Thanks.

**Comment by Flock1** [comment]
Yes. `cudatoolkit` installed through anaconda. 

I think I realized the problem. While installing `fvcore`, I only used it once instead of twice as mentioned in the instructions and I didn't realize the error message and moved on to the next step. I can't believe I did that. 

But after going back to that step, I was able to install the nightly version.

**Comment by RAJA-PARIKSHAT** [comment]
> If you have installed all the dependencies recently, and this is an error from `conda install pytorch3d -c pytorch3d` (or similar), and you are on linux, then the problem is that you have the new version of torch which is newer than (and not supported by) the latest release of Pytorch3D. I recommend installing the nightly build with `conda install pytorch3d -c pytorch3d-nightly` instead.

What about if I am using google colab with pytorch==1.5.1 and torchvision==0.6.1 and want to get pytorch3d==0.2.0 otherwise it would give error. Please help @bottler

**Comment by bottler** [comment]
@RAJA-PARIKSHAT Please please open a new issue for a new question. This is an old closed issue.
