### ISSUE TITLE
PackagesNotFoundError: The following packages are not available from current channels:

### ISSUE THREAD

**Issue by ashwath98** [facebookresearch/pytorch3d#302]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## 🐛 Bugs / Unexpected behaviors

NOTE: Please look at the existing list of Issues tagged with the label ['bug`](https://github.com/facebookresearch/pytorch3d/issues?q=label%3Abug). **Only open a new issue if this bug has not already been reported. If an issue already exists, please comment there instead.**.

## Instructions To Reproduce the Issue:
I'm using a windows system with conda version 4.8.3 and python 3.8 
Please include the following (depending on what the issue is):

1. Any changes you made (`git diff`) or code you wrote
```
None
```
2. The exact command(s) you ran:
```
I ran the installation specified in (https://github.com/facebookresearch/pytorch3d/blob/master/INSTALL.md) and they worked perfectly fine.
only when I ran 
conda install pytorch3d -c pytorch3d
I got this issue
```
3. What you observed (including the full logs):
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - pytorch3d

Current channels:

  - https://conda.anaconda.org/pytorch3d/win-64
  - https://conda.anaconda.org/pytorch3d/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

```

I found some other issues describing this, but it was closed with a solution where user built from source, does the conda install method not work for windows and is building from source the only option?

**Comment by bottler** [comment]
Pytorch3D does not currently have prebuilt packages for windows, on conda or otherwise. Building from source is the way forward, unless you can use Windows Subsystem for Linux etc.

**Comment by ashwath98** [comment]
Sure

**Comment by ashwath98** [comment]
Hey I was able to install pytorch3d after following this https://github.com/facebookresearch/pytorch3d/issues/172#issuecomment-620855810

but unfortunately when I run the following import 
from pytorch3d.structures import Textures

I get the following error

ImportError: cannot import name 'Textures' from 'pytorch3d.structures' (C:\Users\shett\anaconda3\envs\pytorch3d\lib\site-packages\pytorch3d-0.2.0-py3.8-win-amd64.egg\pytorch3d\structures\__init__.py)

what do you think is causing this?

I am setting up WSL and trying the conda install technique rn , but is there anyway to fix this?

**Comment by bottler** [comment]
I assume you have the built the latest code, not the release. The `Textures` object has been deprecated and has also moved from `pytorch3d.structures` to `pytorch3d.renderer`.

**Comment by ashwath98** [comment]
ahhh.. got it

thanks for replying
