### ISSUE TITLE
Installing on CPU - from pytorch3d import _C gives undefined symbol error

### ISSUE THREAD

**Issue by NagabhushanSN95** [facebookresearch/pytorch3d#303]
## 🐛 Bugs / Unexpected behaviors
I'm trying to install cpu version. I followed the steps given in [install](https://github.com/facebookresearch/pytorch3d/blob/master/INSTALL.md) file. Still, I'm getting this error.
I noticed there are similar issues, but they're all for GPU versions.

## Instructions To Reproduce the Issue:
I installed as follows:

```
conda create -n pytorch3d python=3.8
conda activate pytorch3d
conda install -c pytorch pytorch torchvision cpuonly
conda install -c conda-forge -c fvcore fvcore

pip install pytorch3d
python
>>> import torch
>>> import pytorch3d
>>> from pytorch3d import _C
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /media/nagabhushan/Data02/SoftwareFiles/Anaconda/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/pytorch3d/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceISt7complexIfEEEPKNS_6detail12TypeMetaDataEv
```

**Comment by bottler** [comment]
pytorch has had a couple of new releases since the latest release of pytorch3d. Maybe if you replace the third line with `conda install -c pytorch pytorch=1.5.0 torchvision cpuonly` you'll get pytorch 1.5.0 which will be compatible.

**Comment by NagabhushanSN95** [comment]
That worked! Thanks. I'll verify everything once and close the issue
