### ISSUE TITLE
How to change the texture map in a textured mesh?

### ISSUE THREAD

**Issue by Eckert-ZJB** [facebookresearch/pytorch3d#304]
Is it possible to change the texture map in a textured mesh? Or there're any call function can be used for the texture optimization?

**Comment by gkioxari** [comment]
Yes! The mesh textures are stored as a data structure and are a property of the mesh. In your case, you have texture maps so the `TexturesUV` class is the one relevant for you. 

https://github.com/facebookresearch/pytorch3d/blob/7944d24d4872bdb01b821450840049e28d0ce12b/pytorch3d/renderer/mesh/textures.py#L521

The map is stored in that data structure and you can change it or learn to optimize it and in general do whatever you do with neural networks. It's just another tensor.

**Comment by gkioxari** [comment]
No response in a while! Closing this. Feel free to reopen if you have more questions.

**Comment by nikhilaravi** [comment]
@elcronos please explain your problem in more detail and give a code example. What texture do you want to replace? As @gkioxari mentioned you can replace the texture map easily in the `TexturesUV` class by replacing the `maps` tensor on initialization.

**Comment by gkioxari** [comment]
Hi @elcronos 
We appreciate your post here. We have different texture types that encode textures in different ways. Please read more in [textures.py](https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/renderer/mesh/textures.py). These texture types either encode texture as a UV map, or as face texture images or carry texture for each vertex in a mesh. All these texture types are really nicely documented in the code. Please read through the code carefully and choose the texture type that works for you. 

We'd love to help out with your problem and offer solutions. However, we don't quite have the time to do this as then we would spend all our time being consultants to people's projects. Instead, use github issues to report actual issues or bugs you find in the codebase. We are more than happy to address those.

**Comment by roipony** [comment]
> Hi @nikhilaravi,
> 
> Please find my code below. I am new to 3d rendering so I might be a bit confused with some concepts. But this is what I want to do:
> 
> 1. Getting the original texture of the textured object that I loaded as an RGB Image.
> 2. Modify that texture by adding a patch to it.
> 3. Replace the original texture with the new one on the mesh.
> 
> The code below allow me to get the RGB Image and then modified. I just do not understand how to change the original by the new one. I hope the code make sense.
> 
> ```
> def display_texture(texture, fig_size=5):
>     plt.figure(figsize=(fig_size,fig_size))
>     plt.imshow(texture.squeeze().cpu().numpy())
>     plt.grid("off");
>     plt.axis('off');
>     plt.show()
>     
> def add_patch_texture(texture, p, x_l, y_l):
>     patch = torch.zeros_like(texture)
>     mask = torch.ones_like(texture)
>     size_patch = p.shape[1]
>     patch[:,y_l:y_l+size_patch,x_l:x_l+size_patch,:] = p
>     mask[:,y_l:y_l+size_patch,x_l:x_l+size_patch,:]  = 0
>     return (mask*texture) + patch
> 
> obj_filename = os.path.join(DATA_DIR, "lexus/lexus.obj")
> # Load obj file
> mesh = load_objs_as_meshes([obj_filename], device=device)
> texture_image=mesh.textures.maps_padded()
> # 1. Get Original Texture
> display_texture(texture_image)
> # New Texture
> size_patch = 60
> x_l = 500
> y_l = 450
> print('Patch')
> p = torch.rand((size_patch,size_patch,3))
> plt.imshow(p.numpy())
> plt.show()
> # 2. Create New Texture
> applied_patch = add_patch_texture(texture_image,p, x_l, y_l)[0]
> display_texture(applied_patch)
> 
> # 3. Replace old texture in original mesh??
> ```

Hi,
I face the same problem of changing the texture, have you been able to find a solution?

Thanks

**Comment by mark-at-hypothetic** [comment]
The instructions by @gkioxari are quite good. In case you have a TexturesUV instance: For anyone who needs a code example:

```
# get the original texture map
texture_map = mesh.textures.maps_padded()

# do whatever with it. Making it all black
new_map = torch.zeros_like(texture_map)

# you'll need to instantiate  a new TexturesUV. Import the class
from pytorch3d.renderer.mesh.textures import TexturesUV

# and instantiate it with the old faces and verts uv's
new_texture = TexturesUV(maps=new_map, 
                         faces_uvs=mesh.textures.faces_uvs_padded(), 
                         verts_uvs=mesh.textures.verts_uvs_padded())

# assign it to your meshes object
mesh.textures = new_texture
```
