### ISSUE TITLE
How to get which faces or vertices is occluded/rendered during  rendering in pytorch3d

### ISSUE THREAD

**Issue by BaldrLector** [facebookresearch/pytorch3d#307]
Hi,
During rendering, one concerned problem is which vertices or faces is actual rendered, so i can optimize the rendered faces or vertices.
We can compare the z-coordinate of vertices with corresponding depth value to  tackle this issue.
However, the z-coordinate of  projected points is un-normalized, the procedure of norm seems in the  ```_C.rasterize_meshes```, i wander how z-axis is normalized.
Or there are other solutions in pytorch3d? 

Another problem is the z coordinate, pytorch3d retains view space z coordinate,   but cameras.get_world_to_view_transform actually provided projected a depth,  why retains it? 
And the depth channel of rendered image should compare with  z of verts_view or verts_screen?

Thanks, your reply will be vary appreciated.

**Comment by gkioxari** [comment]
Please read the response in https://github.com/facebookresearch/pytorch3d/issues/311.
