### ISSUE TITLE
Potential bug in the "transform3d.py"

### ISSUE THREAD

**Issue by MoyGcc** [facebookresearch/pytorch3d#308]
Hi,

When we construct a "Rotate" object, **no transpose** has been made for the rotation matrix and it would lead to an issue after the "Rotate" object has been composed with a "Translate" object. The function transform_points() will give incorrect transformed points. https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/transforms/transform3d.py#L313

I would suggest you can pre-transpose the rotation matrix before doing the batch multiplication between the original points and the homogenous transformation matrix (that change gave me the desired results).

Best

**Comment by gkioxari** [comment]
Could you provide a code snippet that will allow us to reproduce the issue and see what is the expected result and what we actually output?

**Comment by MoyGcc** [comment]
Hi, thank you for your reply and sorry for the confusion. Unfortunately, the used model and dataset are licensed and I might need some time to reproduce a toy example (not convenient for me currently). Here I wrote the potential mathematical mistake (in the step converting the points in world frame to the camera frame) and you only need to have a look at how the calculations are executed (it origins from https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/renderer/mesh/rasterizer.py#L102 and https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/transforms/transform3d.py#L313).

![7a7b79fd43af26f09f26f48a14241d7](https://user-images.githubusercontent.com/29098423/89937011-ccb39800-dc14-11ea-8610-d5989ab79a7f.jpg)


`SfMPerspectiveCameras(focal_length=self.f, R=self.cam_R, T=self.cam_T, device=self.device)` I used the SfMPerspectiveCameras

**Comment by MoyGcc** [comment]
> Could you provide a code snippet that will allow us to reproduce the issue and see what is the expected result and what we actually output?

I think it's just because of different conventions in terms of the extrinsic parameters. Sorry for the bother. I'm gonna close this issue.
