### ISSUE TITLE
Visible vertexes and faces after rendering

### ISSUE THREAD

**Issue by silverbulletmdc** [facebookresearch/pytorch3d#311]
## 🚀 Feature

Get the visible vertexes and faces after rendering
 
NOTE: Please look at the existing list of Issues tagged with the label ['enhancement`](https://github.com/facebookresearch/pytorch3d/issues?q=label%3Aenhancement). **Only open a new issue if you do not see your feature request there**.

## Motivation

I want to generate a texture map for a 3D model from a 2D photo. I can get the camera parameters by camera optimization. 
Then I can project the 3D vertexes to the 2D image to get the uv coordinate.
But some of the vertexes and faces may be invisible in the image,
I want to find them and set them with a black mask.
Is there any function to find the invisible vertexes in pytorch3d?
Or can you provide some insights to implement this?

## Pitch

It should be like this

```python
def get_visible_vertexes(mesh, camera):
    ...
    return visible_vertexes_idxs 
```
NOTE: we only consider adding new features if they are useful for many users.

**Comment by gkioxari** [comment]
@silverbulletmdc 
The rasterizer spits out fragment data. There you can find various details of the faces that are rendered in the image. In particular, fragments contains `pix_to_face` which provides the indices of the faces that are rendered in decreasing order of depth for each pixel in the image. `zbuf` contains the distance of the face in Z. 
So the information you are requesting is there and is stored in fragment data.
