### ISSUE TITLE
Sampling function for UV space to vertex space conversion 

### ISSUE THREAD

**Issue by ForrestPi** [facebookresearch/pytorch3d#312]
## ❓ Questions on how to use PyTorch3D

Hi! I'm new to pytorch3d and I am looking for a  sampling function for UV space to vertex space conversion and vertex space to UV map which is differentiable  

Thanks, your reply will be vary appreciated.

**Comment by gkioxari** [comment]
We provide texture sampling functions with maps and uv coordinates. 

https://github.com/facebookresearch/pytorch3d/blob/f03aa5803bcdba3b9447a8c2ffdc77e693d51c87/pytorch3d/renderer/mesh/textures.py#L543

**Comment by gkioxari** [comment]
No response! Closing this issue.
