### ISSUE TITLE
How to render textured .ply file

### ISSUE THREAD

**Issue by ashwath98** [facebookresearch/pytorch3d#315]
## ❓ Questions on how to use PyTorch3D

Hey I was looking through the API I noticed there does not exist load_ply_as_mesh function like it does for obj files. If I wanted to do a similar operation with ply files as you have guys have done in the rendered_texture_meshes.ipynb example. how will I go about doing this?

**Comment by bottler** [comment]
We do not have a specific function to do this, but it may be very easy based on what we have. Do you know what format the textures are in the file? Can you post the header part of the PLY file (the beginning of the file up to `end_header`) here?

**Comment by ashwath98** [comment]
Hey thanks for replying
The header is 
"ply
format binary_little_endian 1.0
comment VCGLIB generated
element vertex 130664
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
property uchar alpha
element face 260082
property list uchar int vertex_indices
end_header"
I saw in this issue : https://github.com/facebookresearch/pytorch3d/issues/112 there is a way to render by creating the texture object with rgb vertices parameter. I can access the vertices (np array of shape (1330664,3)), faces (np array of shape(260082,3) and vertex colours (np array of shape (1330664,3)) of the mesh through MPI's mesh library. Can I pass them directly to create a mesh object as specified in the solution to the issue or would some other preprocessing be required?

**Comment by bottler** [comment]
Yes. You can use them directly and I recommend that as the easy way forward.

If you are using pytorch3d built from source or the nightly build, you can do something like

```
verts = torch.from_numpy(np_vertices)[None]
faces = torch.from_numpy(np_faces)[None]
features = torch.from_numpy(np_vertex_colors)[None]
tex = TexturesVertex(verts_features=features)
mesh = Meshes(verts=verts, faces=faces, textures = tex)
```

If you have the latest release, the fourth line would be more like `tex=Textures(verts_rgb=features)`.

**Comment by ashwath98** [comment]
Hey when I was able to succesfully create the mesh object, but when I try to render I get this error thrown at me "
**"RuntimeError: expected scalar type Double but found Float"**

**Code Snippet for Mesh Creation** (for context mesh.v,mesh.f,mesh.vc are numpy arrays of vertexes,faces and vertex colours with datatype float64,uint32 and float64 respectively)

`verts = torch.from_numpy(np.array(mesh.v,dtype='double'))[None]

faces = torch.from_numpy(np.array(mesh.f,dtype='int64'))[None]

features = torch.from_numpy(np.array(mesh.vc,dtype='double'))[None]

tex = TexturesVertex(verts_features=features)

mesh = Meshes(verts=verts, faces=faces, textures = tex)`


**Code Snippet for renderer Initialization**


`R, T = look_at_view_transform(2.7, 0, 180) 
cameras = OpenGLPerspectiveCameras(device=device, R=R, T=T)
raster_settings = RasterizationSettings(
    image_size=512, 
    blur_radius=0.0, 
    faces_per_pixel=1, 
)

lights = PointLights(device=device, location=[[0.0, 0.0, -3.0]])
renderer = MeshRenderer(
    rasterizer=MeshRasterizer(
        cameras=cameras, 
        raster_settings=raster_settings
    ),
    shader=SoftPhongShader(
        device=device, 
        cameras=cameras,
        lights=lights
    )
)
`
when I run images = renderer(mesh)
this is the the stack trace of the error I get
RuntimeError                              Traceback (most recent call last)
<ipython-input-49-e454a24aad6f> in <module>
----> 1 images = renderer(mesh)
      2 plt.figure(figsize=(10, 10))
      3 plt.imshow(images[0, ..., :3].cpu().numpy())
      4 plt.grid("off");
      5 plt.axis("off");

~/mesh-body/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    720             result = self._slow_forward(*input, **kwargs)
    721         else:
--> 722             result = self.forward(*input, **kwargs)
    723         for hook in itertools.chain(
    724                 _global_forward_hooks.values(),

~/Desktop/pytorch3d/pytorch3d/renderer/mesh/renderer.py in forward(self, meshes_world, **kwargs)
     46         the range for the corresponding face.
     47         """
---> 48         fragments = self.rasterizer(meshes_world, **kwargs)
     49         images = self.shader(fragments, meshes_world, **kwargs)
     50 

~/mesh-body/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    720             result = self._slow_forward(*input, **kwargs)
    721         else:
--> 722             result = self.forward(*input, **kwargs)
    723         for hook in itertools.chain(
    724                 _global_forward_hooks.values(),

~/Desktop/pytorch3d/pytorch3d/renderer/mesh/rasterizer.py in forward(self, meshes_world, **kwargs)
    118             Fragments: Rasterization outputs as a named tuple.
    119         """
--> 120         meshes_screen = self.transform(meshes_world, **kwargs)
    121         raster_settings = kwargs.get("raster_settings", self.raster_settings)
    122         # TODO(jcjohns): Should we try to set perspective_correct automatically

~/Desktop/pytorch3d/pytorch3d/renderer/mesh/rasterizer.py in transform(self, meshes_world, **kwargs)
    100         # TODO: Revisit whether or not to transform z coordinate to [-1, 1] or
    101         # [0, 1] range.
--> 102         verts_view = cameras.get_world_to_view_transform(**kwargs).transform_points(
    103             verts_world
    104         )

~/Desktop/pytorch3d/pytorch3d/transforms/transform3d.py in transform_points(self, points, eps)
    311 
    312         composed_matrix = self.get_matrix()
--> 313         points_out = _broadcast_bmm(points_batch, composed_matrix)
    314         denom = points_out[..., 3:]  # denominator
    315         if eps is not None:

~/Desktop/pytorch3d/pytorch3d/transforms/transform3d.py in _broadcast_bmm(a, b)
    679         if len(b) == 1:
    680             b = b.expand(len(a), -1, -1)
--> 681     return a.bmm(b)
    682 
    683 

RuntimeError: expected scalar type Double but found Float

**Comment by bottler** [comment]
You need the verts and colors to be "float32" / "float". You have the faces as "int64" which is fine.

**Comment by ashwath98** [comment]
Hey Thanks, It's working now. It takes a lot of time to render(around 15-20 minutes (probably because of cpu) but it's working perfectly fine)
