### ISSUE TITLE
Weird result when render dense point cloud

### ISSUE THREAD

**Issue by niujinshuchong** [facebookresearch/pytorch3d#316]
## Instructions To Reproduce the Issue:
```
import os
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
from skimage.io import imread

# Util function for loading point clouds
import numpy as np

# Data structures and functions for rendering
from pytorch3d.structures import Pointclouds
from pytorch3d.renderer import (
    look_at_view_transform,
    OpenGLOrthographicCameras, 
    PointsRasterizationSettings,
    PointsRenderer,
    PointsRasterizer,
    AlphaCompositor,
    NormWeightedCompositor
)

# Setup
if torch.cuda.is_available():
    device = torch.device("cuda:0")
    torch.cuda.set_device(device)
else:
    device = torch.device("cpu")
    
#device = torch.device("cpu")

# Initialize an OpenGL perspective camera.
R, T = look_at_view_transform(20, 10, 0)
cameras = OpenGLOrthographicCameras(device=device, R=R, T=T, znear=0.01)

# Define the settings for rasterization and shading. Here we set the output image to be of size
# 512x512. As we are rendering images for visualization purposes only we will set faces_per_pixel=1
# and blur_radius=0.0. Refer to rasterize_points.py for explanations of these parameters. 
raster_settings = PointsRasterizationSettings(
    image_size=512, 
    radius = 0.02,
    points_per_pixel = 8
)


# Create a points renderer by compositing points using an weighted compositor (3D points are
# weighted according to their distance to a pixel and accumulated using a weighted sum)
renderer = PointsRenderer(
    rasterizer=PointsRasterizer(cameras=cameras, raster_settings=raster_settings),
    compositor=NormWeightedCompositor()
)

scale = 0.05
points = torch.randn((256*256, 3)).float().to(device) * scale
color = torch.ones_like(points) * torch.Tensor([0.1, 0.5, 1.0]).view(-1, 3).to(device)
point_cloud = Pointclouds(points=[points], features=[color])

images = renderer(point_cloud)
plt.figure(figsize=(10, 10))
plt.imshow(images[0, ..., :3].cpu().numpy())
plt.grid("off") 
plt.axis("off");

```
The resulting image is as follows:

![r](https://user-images.githubusercontent.com/13434986/90312403-d3a11a00-df36-11ea-8baa-d9560a24a810.png)

However, setting scale to 0.1 or higher or device to cpu gets normal results like:

![rr](https://user-images.githubusercontent.com/13434986/90312480-6346c880-df37-11ea-9442-074c1f65f1ce.png)

**Comment by sbranson** [comment]
Thanks for the easily reproducible example.  This is a bug with the coarse-to-fine renderer.  When the number of points is large relative to the `raster_settings.max_points_per_bin`  parameter setting, an overflow problem can occur.  If you increase `max_points_per_bin` to 50000

`raster_settings = PointsRasterizationSettings(image_size=512, radius = 0.02, points_per_pixel = 8, max_points_per_bin=50000)`

the image should render correctly.  You can also disable coarse-to-fine rendering by setting `max_points_per_bin=0`, but this will slow things down.  We will add a fix to the overflow issue by instead outputting a warning to increase max_points_per_bin.  You can see the post by @gkioxari for a related issue https://github.com/facebookresearch/pytorch3d/issues/348 for a more detailed description of the problem.

**Comment by niujinshuchong** [comment]
Got it. Thanks for the explanation.
