### ISSUE TITLE
 warnings.warn("Faces have invalid indices")

### ISSUE THREAD

**Issue by zhang-heng-shu** [facebookresearch/pytorch3d#319]
after installing successful
when testing :
from pytorch3d.utils import ico_sphere
from pytorch3d.io import load_obj
from pytorch3d.structures import Meshes
from pytorch3d.ops import sample_points_from_meshes
from pytorch3d.loss import chamfer_distance

# Use an ico_sphere mesh and load a mesh from an .obj e.g. model.obj
sphere_mesh = ico_sphere(level=3)
verts = load_obj("D:\pytorch3d\\0.2.0\pytorch3d-0.2.0\\box.obj")
verts = load_obj("C:\\Users\zhangheng\Desktop\\jingguan.obj")
test_mesh = Meshes(verts=[verts], faces=[faces.verts_idx])

# Differentiably sample 5k points from the surface of each mesh and then compute the loss.
sample_sphere = sample_points_from_meshes(sphere_mesh, 5000)
sample_test = sample_points_from_meshes(test_mesh, 5000)
loss_chamfer, _ = chamfer_distance(sample_sphere, sample_test)

it shows:
D:\Anaconda\envs\kaolin\lib\site-packages\pytorch3d-0.2.0-py3.6-win-amd64.egg\pytorch3d\io\obj_io.py:70: UserWarning: Faces have invalid indices
  warnings.warn("Faces have invalid indices")

how to slove this problem?

**Comment by nikhilaravi** [comment]
What version of PyTorch3D are you using? Are you using a conda package? See https://github.com/facebookresearch/pytorch3d/issues/165#issuecomment-669608960. This is an incorrect warning about the normals/texture indices for the faces and can be ignored. It has been fixed in master.
