### ISSUE TITLE
Keep meeting interger division problem when calling pytorch3d.ops.cubify

### ISSUE THREAD

**Issue by RuanYue** [facebookresearch/pytorch3d#320]
## 🐛 Bugs / Unexpected behaviors

cubified_voxels = cubify(voxels, CUBIFY_THRESH).to(device)
/usr/local/lib/python3.6/dist-packages/pytorch3d/ops/cubify.py in unravel_index(idx, dims)
     19         raise ValueError("Expects a 4-element list.")
     20     N, H, W, D = dims
---> 21     n = torch.div(idx, (H * W * D))
     22     h = torch.div((idx - n * H * W * D), (W * D))
     23     w = torch.div((idx - n * H * W * D - h * W * D), D)

RuntimeError: Integer division of tensors using div or / is no longer supported, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.

I've changed all `torch.div` to `torch.true_divide`. But the error has not been solved.

**Comment by gkioxari** [comment]
Hi @RuanYue! You seem to have an older version of PyTorch3D. We have made the changes to be compatible with PyTorch and have changed `torch.div` to `//` as was the intended use case. 

https://github.com/facebookresearch/pytorch3d/blob/8e9ff15faff8acf6bf5c13e19a7e2790e61af470/pytorch3d/ops/cubify.py#L21

**Comment by RuanYue** [comment]
Thanks!
