### ISSUE TITLE
How can I get 3D vertices consistent with image field？

### ISSUE THREAD

**Issue by TheshowN** [facebookresearch/pytorch3d#324]
What I'm doing now is to reconstruct a 3dmm face model from a single face image with Pytorch3D, and I want to sample texture from the original image. So I need to get the vertices in the image field, which have the same X and Y coordinates with the corresponding image pixels. But such vertices seem to be encapsulated in render().

Thus, I want to ask if there is an interface to sample textures from the original image, or how can I get vertices with the same X and Y coordinates as the original pixels?

Thanks in advance！

**Comment by nikhilaravi** [comment]
@TheshowN if I understand correctly, you want to get the value of the 3D vertices projected on to the XY plane?

You can easily do this by applying the transform from the `renderer.rasterizer.transform` - this will transform the input mesh and project it onto the image plane. 

```
mesh_on_screen = renderer.rasterizer.transform(mesh)
```

Issue https://github.com/facebookresearch/pytorch3d/issues/353 is about the same question.

**Comment by AmosZhu** [comment]
After getting the vertices you need the visibility on each view as well

**Comment by gkioxari** [comment]
We do not expose the transformed vertices, you are right. However, the modular implementation in PyTorch3D allows you to write your own custom renderer and rasterizer class that will allow you to expose whatever you wish for your project based on its needs. This is the beauty of a modular implementation and the intended use in PyTorch3D; namely users should write custom classes to expose and perform whatever they need while we take care of the heavy lifting of the rasterization process, etc. 
This way the transform of the vertices will only happen once!
