### ISSUE TITLE
Device mismatch in loading UV/Atlas textures

### ISSUE THREAD

**Issue by naoto0804** [facebookresearch/pytorch3d#326]
## 🐛 Bugs / Unexpected behaviors

As I show the codes below, when I pass/don't pass `create_texture_atlas=True` option in `pytorch3d.io.load_objs_as_meshes` to load a mesh, the resulting textures of meshes seem to be on a different device. This difference results in throwing errors (e.g., `RuntimeError: Expected object of device type cuda but got device type cpu`) in latter operations like rendering.
I'm not sure this is a bug or expected behavior due to some undocumented reason (memory?), that's why I post here. 

## Instructions To Reproduce the Issue:

1. Any changes you made (`git diff`) or code you wrote
```
import torch
from pytorch3d.io import load_objs_as_meshes

device = torch.device("cuda:0")
torch.cuda.set_device(device)
obj_filename = "data/cow_mesh/cow.obj"

mesh_uv = load_objs_as_meshes([obj_filename], device=device)
mesh_atlas = load_objs_as_meshes([obj_filename], device=device, create_texture_atlas=True)
print(mesh_uv.textures.device)
print(mesh_atlas.textures.device)
```
2. The exact command(s) you ran:
3. What you observed (including the full logs):
```
cuda:0
cpu
```

I guess this is caused because the information of the device is not passed in creating TexturesAtlas instance at [here](https://github.com/facebookresearch/pytorch3d/blob/6d76336501918e29b9cc15b5b4fe6d0f18818d67/pytorch3d/io/obj_io.py#L256)
```
tex = TexturesAtlas(atlas=[aux.texture_atlas])
```
, while it is passed in creating TexturesUV instance at [here](https://github.com/facebookresearch/pytorch3d/blob/6d76336501918e29b9cc15b5b4fe6d0f18818d67/pytorch3d/io/obj_io.py#L261-L266)
```
verts_uvs = aux.verts_uvs.to(device)  # (V, 2)
faces_uvs = faces.textures_idx.to(device)  # (F, 3)
image = list(tex_maps.values())[0].to(device)[None]
tex = TexturesUV(
    verts_uvs=[verts_uvs], faces_uvs=[faces_uvs], maps=image
)
```

**Comment by gkioxari** [comment]
This has now been fixed in master and you shouldn't be seeing this error

https://github.com/facebookresearch/pytorch3d/blob/de77e426eb34e078dac073e6220fee9d6307934a/pytorch3d/io/obj_io.py#L256

I will close this issue. If you still have issues feel free to reopen it.

**Comment by naoto0804** [comment]
Glad to see it fixed, thanks a lot!
