### ISSUE TITLE
Installation on linux : Solving environment: failed with initial frozen solve. Retrying with flexible solve.

### ISSUE THREAD

**Issue by qmlu-cn** [facebookresearch/pytorch3d#337]
## ERROR
(pytorch3d) root@lqm:~# conda install pytorch3d -c pytorch3d
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.                                                         failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__cuda==10.1=0
  - feature:|@/linux-64::__cuda==10.1=0

Your installed version is: 10.1

## conda list
(pytorch3d) root@lqm:~# conda list
packages in environment at /root/anaconda3/envs/pytorch3d:

Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
blas                      1.0                         mkl
ca-certificates           2020.7.22                     0
certifi                   2020.6.20                py38_0
cudatoolkit               10.1.243             h6bb024c_0
freetype                  2.10.2               h5ab3b9f_0
fvcore                    0.1.1.post20200716            py_0    conda-forge
intel-openmp              2020.1                      217
jpeg                      9b                   h024ee3a_2
lcms2                     2.11                 h396b838_0
ld_impl_linux-64          2.33.1               h53a641e_7
libedit                   3.1.20191231         h14c3975_1
libffi                    3.3                  he6710b0_2
libgcc-ng                 9.1.0                hdf63c60_0
libpng                    1.6.37               hbc83047_0
libstdcxx-ng              9.1.0                hdf63c60_0
libtiff                   4.1.0                h2733197_1
lz4-c                     1.9.2                he6710b0_1
mkl                       2020.1                      217
mkl-service               2.3.0            py38he904b0f_0
mkl_fft                   1.1.0            py38h23d657b_0
mkl_random                1.1.1            py38h0573a6f_0
ncurses                   6.2                  he6710b0_1
ninja                     1.10.0           py38hfd86e86_0
numpy                     1.19.1           py38hbc911f0_0
numpy-base                1.19.1           py38hfa32c7d_0
olefile                   0.46                       py_0
openssl                   1.1.1g               h7b6447c_0
pillow                    7.2.0            py38hb39fc2d_0
pip                       20.2.2                   py38_0
portalocker               2.0.0                    py38_0
python                    3.8.5                hcff3b4d_0
pytorch                   1.5.1           py3.8_cuda10.1.243_cudnn7.6.3_0    pytorch
pyyaml                    5.3.1            py38h7b6447c_1
readline                  8.0                  h7b6447c_0
setuptools                49.6.0                   py38_0
six                       1.15.0                     py_0
sqlite                    3.33.0               h62c20be_0
tabulate                  0.8.7                    py38_0
termcolor                 1.1.0                    py38_1
tk                        8.6.10               hbc83047_0
torchvision               0.6.1                py38_cu101    pytorch
tqdm                      4.48.2                     py_0
wheel                     0.35.1                     py_0
xz                        5.2.5                h7b6447c_0
yacs                      0.1.6                      py_0    conda-forge
yaml                      0.2.5                h7b6447c_0
zlib                      1.2.11               h7b6447c_3
zstd                      1.4.5                h9ceee32_0

## cuda vision and driver version
(pytorch3d) root@lqm:~# nvidia-smi
Wed Aug 26 03:32:12 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.40       Driver Version: 430.40       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+

**Comment by bottler** [comment]
You have pytorch 1.5.1 which is newer than the latest release 0.2.0 of pytorch3d. It is possible to force the released conda build to work together with pytorch 1.5.1 as discussed in issue #243.

I recommend you use the nightly build of pytorch3d instead, `conda install pytorch3d -c pytorch3d-nightly`.

**Comment by qmlu-cn** [comment]
The problem is resolved. Thank you for your quick response.
