### ISSUE TITLE
In the version 0.2.5  "from pytorch3d import _C" can not work

### ISSUE THREAD

**Issue by ShengrenNiu** [facebookresearch/pytorch3d#339]
The line  "from pytorch3d import _C" can not work, error with "No such file or directory" in version 0.2.5 linux cpuonly, no matter what version of pytorch (1.5.1 or 1.6.0).
If I use pytorch3d 0.2.0 with pytorch 1.5.1, there is no error.

**Comment by bottler** [comment]
How did you install?

**Comment by bottler** [comment]
Note that `from pytorch3d import _C` can only work after you have already done `import torch`. The PyTorch3D python code ensures that this is the case when you use its interface.

**Comment by ShengrenNiu** [comment]
I install the pytorch3d through the terminal command "pip install pytorch3d" on a ubuntu 18LST virtual machine. The packages used is "pytorch3d-0.2.5-cp36-cp36m-manylinux1_x86_64.whl"
I've already done `import torch` before `from pytorch3d import _C`. The same code works fine with pytorch (1.5.1) and pytorch3D (0.2.0).

**Comment by ShengrenNiu** [comment]
Does pytorch3D(0.2.5) have to work with Pytorch (1.6.0)? I've tred this combination, but it still gives the error.

**Comment by bottler** [comment]
Ah. We have changed the pip PyPI package in version 0.2.5 to use cuda, specifically cuda 10.1, so it requires the torch for cuda 10.1. (I think it can work even if you don't have a GPU, but you need cuda support in torch.) You are running cpu-only. May be easiest to build from source or use conda?

**Comment by bottler** [comment]
> Does pytorch3D(0.2.5) have to work with Pytorch (1.6.0)? I've tred this combination, but it still gives the error.

(I wrote the previous reply before I saw this.) Pytorch3d 0.2.5 source code can work with pytorch 1.4, 1.5.0, 1.5.1 and 1.6.0. If you build from source then you will be fine with any of them. There can only be one build on PyPI - it only works with Pytorch 1.6.0. 

I think the problem you're having is because of cuda.

**Comment by ShengrenNiu** [comment]
oh, if the cuda is necessary, there is no problem to be sovlved. Because I just try the pytorch3d in a virtual machine, so I just install the cpu-only version (pytorch and pytorch3d). I thought I could use the CPU-only version with  pip installation. I've tried to built from source code, but met some problems. Maybe I'll do another question on that later. Many thanks for your answer.

**Comment by ShengrenNiu** [comment]
I reinstall the pytorch (1.6.0) and install the pytorch3D 0.2.5 from the source code. Both the packages works fine.

**Comment by raphaelrk** [comment]
Still running into this while trying to run this colab: https://colab.research.google.com/drive/1g0FmDBlL-bXSJJuzKhuecQGZT14_PUY0

![image](https://user-images.githubusercontent.com/3377845/145150831-0a35eddf-e218-47ca-b38d-dc31ebe4f266.png)

**Comment by bottler** [comment]
@raphaelrk Please open a new issue for a new question and don't adapt an old resolved issue.
