### ISSUE TITLE
Blur rendering BUG, when I let create_texture_atlas=True and blur_radius>0

### ISSUE THREAD

**Issue by qmlu-cn** [facebookresearch/pytorch3d#342]
**Load obj stage**
`mesh = load_objs_as_meshes(obj_path, device=args.device, create_texture_atlas=True, texture_atlas_size=4)`
Here I let `create_texture_atlas=True`
**Rendering stage**
```
       raster_settings = RasterizationSettings(
            image_size=299,
            blur_radius=1e-5, 
            faces_per_pixel=1, 
        )
```
Here I let `blur_radius>0`

Then I run the code:
```
    mesh = load_objs_as_meshes(obj_path, device=args.device, create_texture_atlas=True, texture_atlas_size=4)
    renderer = Renderer(args)
    image = renderer(mesh)
```
## ERROR Info
-sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1591914886554/work/aten/src/ATen/native/cuda/IndexKernel.cu:60: operator(): block: [75,0,0], thread: [20,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1591914886554/work/aten/src/ATen/native/cuda/IndexKernel.cu:60: operator(): block: [75,0,0], thread: [21,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1591914886554/work/aten/src/ATen/native/cuda/IndexKernel.cu:60: operator(): block: [75,0,0], thread: [22,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1591914886554/work/aten/src/ATen/native/cuda/IndexKernel.cu:60: operator(): block: [75,0,0], thread: [23,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1591914886554/work/aten/src/ATen/native/cuda/IndexKernel.cu:60: operator(): block: [75,0,0], thread: [24,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "/opt/data/private/lqm/adv3d/main.py", line 132, in <module>
    print_ori(['./data/cow_mesh/cow.obj'])
  File "/opt/data/private/lqm/adv3d/main.py", line 117, in print_ori
    image = renderer(mesh)
  File "/opt/data/private/lqm/adv3d/render/render.py", line 76, in __call__
    std_image = self.renderer(std_mesh)
  File "/root/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/pytorch3d/renderer/mesh/renderer.py", line 49, in forward
    images = self.shader(fragments, meshes_world, **kwargs)
  File "/root/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/pytorch3d/renderer/mesh/shader.py", line 112, in forward
    colors = phong_shading(
  File "/root/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/pytorch3d/renderer/mesh/shading.py", line 71, in phong_shading
    vertex_normals = meshes.verts_normals_packed()  # (V, 3)
  File "/root/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/pytorch3d/structures/meshes.py", line 684, in verts_normals_packed
    self._compute_vertex_normals()
  File "/root/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/pytorch3d/structures/meshes.py", line 808, in _compute_vertex_normals
    if self.isempty():
RuntimeError: CUDA error: device-side assert triggered

**In #327 , you suggest user doing `clip_barycentric_coords=True`. After I did this, the error still occured.**

**Comment by gkioxari** [comment]
You error is a CUDA error and has nothing to do with the renderer or the rasterization. The information you provide is not enough for us to help you.

**Comment by nikhilaravi** [comment]
Can you please provide a complete code example include the obj file (with the material/texture) so that we can try to reproduce the error?

**Comment by qmlu-cn** [comment]
[tank_t90.zip](https://github.com/facebookresearch/pytorch3d/files/5206621/tank_t90.zip)

Here is a example.

```
from pytorch3d.io import load_objs_as_meshes, load_obj
# Data structures and functions for rendering
from pytorch3d.structures import Meshes
from pytorch3d.renderer import (
    look_at_view_transform,
    FoVPerspectiveCameras, 
    PointLights, 
    DirectionalLights, 
    Materials, 
    RasterizationSettings, 
    MeshRenderer, 
    MeshRasterizer,  
    SoftPhongShader,
    TexturesUV
)

device = 'cuda:0'
raster_settings = RasterizationSettings(
    image_size=299,
    blur_radius=1e-5, 
    faces_per_pixel=1, 
    clip_barycentric_coords=True,
    # perspective_correct=True,
    cull_backfaces=True,
)
dist=7
elev=30
azim=90

R, T = look_at_view_transform(dist, elev, azim, device=device) 
cameras = FoVPerspectiveCameras(device=device, R=R, T=T)

lights = PointLights(device=device, location=[[1000.0, 1000.0, -500.0]])
renderer = MeshRenderer(
    rasterizer=MeshRasterizer(
        cameras=cameras, 
        raster_settings=raster_settings
    ),
    shader=SoftPhongShader(
        device=device, 
        cameras=cameras,
        lights=lights
    )
)
mesh = load_objs_as_meshes(['./tank_t90/T-90.obj'],device=device,create_texture_atlas=True)
image = renderer(mesh)

```

**Comment by gkioxari** [comment]
Hi @qmlu-cn 
Thank you for providing data and code to reproduce the problem. We have identified the issue and will provide a solution soon. In short the issue lies in the `sample_textures` for TextureAtlas. Another user had a similar issue and I am explaining the problem there: https://github.com/facebookresearch/pytorch3d/issues/327. We will have a fix soon!

**Comment by nikhilaravi** [comment]
This issue has now been resolved by https://github.com/facebookresearch/pytorch3d/commit/01759d8ffb4899de1157398e4052f76a13c56527. Here is an example of the output image using the settings from your code example. 
![tank](https://user-images.githubusercontent.com/5912647/102497989-3cf08100-402e-11eb-86c2-2fddbf200f10.jpg)
**Note**: Your `.obj` needs to be loaded using the following code. i.e. the `texture_wrap` needs to be set to repeat as some of the vertex uv values are outside the range [0, 1]

```
verts, faces, aux = load_obj(
    obj_filename,
    device=device,
    load_textures=True,
    create_texture_atlas=True,
    texture_atlas_size=4,
    texture_wrap="repeat",
)

atlas = aux.texture_atlas
mesh = Meshes(
    verts=[verts],
    faces=[faces.verts_idx],
    textures=TexturesAtlas(atlas=[atlas]),
)
```
