### ISSUE TITLE
Mesh faces with some of the vertices behind the camera are not being rendered by MeshRasterizer

### ISSUE THREAD

**Issue by vevenom** [facebookresearch/pytorch3d#345]
Dear Pytorch3d team,

First of all, I really appreciate your efforts on developing the really nice library. Thanks for that.

###  Issue: Rendering mesh faces when some vertices are behind the camera.

Currently, the MeshRasterizer does not seem to support rendering faces for which some of the vertices are located behind the camera. According to a comment in `rasterize_meshes_python` function:

> Faces with at least one vertex behind the camera won't render correctly and should be removed or clipped before calling the rasterizer

**Is there some workaround for this issue? Is there maybe an easy way of clipping the faces before feeding them to the rasterizer like suggested in the comment?**

### My current workaround

I have tried subdividing the triangle mesh into larger number of meshes. After few iterations of these, the number of faces for individual meshes increases from 2 to 256, and the results are perfect. However, this workaround slows down the pipeline by a lot. Rendering in multi-view setting takes 0.8s compared to 0.08s before subdividing.

### Motivation

I believe this to be a large issue especially in room layout estimation, where planar surfaces like walls can be easily represented by a small number of triangles (typically 2) and hence the rendering pipeline should be really fast.

Thank you for your reply.

Kind regards,
Sinisa

**Comment by sbranson** [comment]
We are working on a full fix to this issue, by clipping triangles to the portion in front of the camera.  This is slightly non-trivial because the clipping is view dependent, and we need to make sure that gradients are preserved correctly.  I think a fix will probably come in the next couple of weeks.

**Comment by vevenom** [comment]
I see. Thanks a lot for the feedback.

**Comment by garylidd** [comment]
I'm also facing this problem. Is this bug exists in original implementation? Has any progress been made?

**Comment by nikhilaravi** [comment]
@garylidd we are working on the full fix!

**Comment by nikhilaravi** [comment]
This was fixed in the PyTorch3D 0.4 release.
