### ISSUE TITLE
windows installation testcase error

### ISSUE THREAD

**Issue by jiangolder** [facebookresearch/pytorch3d#346]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## 🐛 Bugs / Unexpected behaviors

I install with torch-1.4.0 cuda-10.1 pytorch3d-0.2.5

## Instructions To Reproduce the Issue:

Please include the following (depending on what the issue is):

1. Any changes you made (`git diff`) or code you wrote
I follow the [install instruction](https://github.com/facebookresearch/pytorch3d/blob/master/INSTALL.md) and this [fix](https://github.com/facebookresearch/pytorch3d/pull/203/files)

2. The exact command(s) you ran: python -m unittest discover -p *.py
3. What you observed (including the full logs):

D:\pytorch3d\tests>python -m unittest discover -p *.py
.....C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\renderer\cameras.py:862: PendingDeprecationWarning: SfMOrthographicCameras is deprecated,
        Use OrthographicCameras instead.
        SfMOrthographicCameras will be removed in future releases.
  PendingDeprecationWarning,
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\points_alignment.py:319: UserWarning: The size of one of the point clouds is <= dim+1. corresponding_points_alignment cannot return a unique rotation.
  + "corresponding_points_alignment cannot return a unique rotation."
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\renderer\cameras.py:296: PendingDeprecationWarning: OpenGLPerspectiveCameras is deprecated,
        Use FoVPerspectiveCameras instead.
        OpenGLPerspectiveCameras will be removed in future releases.
  PendingDeprecationWarning,
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\renderer\cameras.py:510: PendingDeprecationWarning: OpenGLOrthographicCameras is deprecated,
        Use FoVOrthographicCameras instead.
        OpenGLOrthographicCameras will be removed in future releases.
  PendingDeprecationWarning,
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\renderer\cameras.py:702: PendingDeprecationWarning: SfMPerspectiveCameras is deprecated,
        Use PerspectiveCameras instead.
        SfMPerspectiveCameras will be removed in future releases.
  PendingDeprecationWarning,
.................................E..E.D:\pytorch3d\tests\test_obj_io.py:460: UserWarning: cow_texture_atlas_softras.pt not found, download from https://dl.fbaipublicfiles.com/pytorch3d/data/tests/cow_texture_atlas_softras.pt, save it at the path D:\pytorch3d\tests\data\cow_texture_atlas_softras.pt, and rerun
  warnings.warn(msg)
.EEEEEEEEE....EEEEE.EEEEEEE.E........................E..............C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 21.69% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 22.29% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 29.17% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 4.17% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 1.04% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 19.79% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 18.75% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 16.25% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 10.00% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 3.75% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 2.50% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 25.00% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 17.50% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 28.75% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 29.69% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 4.69% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 32.81% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 31.25% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 26.56% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 7.81% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 34.38% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 40.62% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
.C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 44.12% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 38.38% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 50.44% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 42.86% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 48.96% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 36.70% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 48.94% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 43.69% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 40.95% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 47.12% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 32.65% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 24.20% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
...........................EE.C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\points_alignment.py:319: UserWarning: The size of one of the point clouds is <= dim+1. corresponding_points_alignment cannot return a unique rotation.
  + "corresponding_points_alignment cannot return a unique rotation."
..C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\points_alignment.py:336: UserWarning: Excessively low rank of cross-correlation between aligned point clouds. corresponding_points_alignment cannot return a unique rotation.
  + "corresponding_points_alignment cannot return a unique rotation."
.................................................................C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\renderer\cameras.py:862: PendingDeprecationWarning: SfMOrthographicCameras is deprecated,
        Use OrthographicCameras instead.
        SfMOrthographicCameras will be removed in future releases.
  PendingDeprecationWarning,
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\renderer\cameras.py:296: PendingDeprecationWarning: OpenGLPerspectiveCameras is deprecated,
        Use FoVPerspectiveCameras instead.
        OpenGLPerspectiveCameras will be removed in future releases.
  PendingDeprecationWarning,
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\renderer\cameras.py:510: PendingDeprecationWarning: OpenGLOrthographicCameras is deprecated,
        Use FoVOrthographicCameras instead.
        OpenGLOrthographicCameras will be removed in future releases.
  PendingDeprecationWarning,
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\renderer\cameras.py:702: PendingDeprecationWarning: SfMPerspectiveCameras is deprecated,
        Use PerspectiveCameras instead.
        SfMPerspectiveCameras will be removed in future releases.
  PendingDeprecationWarning,
...........................................................F.......E.......................................................E.E..E.D:\pytorch3d\tests\test_obj_io.py:460: UserWarning: cow_texture_atlas_softras.pt not found, download from https://dl.fbaipublicfiles.com/pytorch3d/data/tests/cow_texture_atlas_softras.pt, save it at the path D:\pytorch3d\tests\data\cow_texture_atlas_softras.pt, and rerun
  warnings.warn(msg)
.EEEEEEEEE....EEEEE...............C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 21.69% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 22.29% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 29.17% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 4.17% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 1.04% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 19.79% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 18.75% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 16.25% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 10.00% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 3.75% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 2.50% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 25.00% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 17.50% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 28.75% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 29.69% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 4.69% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 32.81% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 31.25% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 26.56% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 7.81% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 34.38% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 40.62% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
.C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 44.12% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 38.38% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 50.44% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 42.86% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 48.96% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 36.70% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 48.94% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 43.69% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 40.95% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 47.12% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 32.65% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\perspective_n_points.py:154: UserWarning:
EPnP: 24.20% points have z<0.
  warnings.warn("\nEPnP: %2.2f%% points have z<0." % (neg_rate * 100.0))
.EEEEEEE.E..........................EE.C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\points_alignment.py:319: UserWarning: The size of one of the point clouds is <= dim+1. corresponding_points_alignment cannot return a unique rotation.
  + "corresponding_points_alignment cannot return a unique rotation."
..C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\ops\points_alignment.py:336: UserWarning: Excessively low rank of cross-correlation between aligned point clouds. corresponding_points_alignment cannot return a unique rotation.
  + "corresponding_points_alignment cannot return a unique rotation."
...sssssss.............................EEEEEEEEEEEEEED:\pytorch3d\tests\test_render_points.py:87: UserWarning: pointcloud.npz not found, download from https://dl.fbaipublicfiles.com/pytorch3d/data/PittsburghBridge/pointcloud.npz, save it at the path D:\pytorch3d\docs\tutorials\data\PittsburghBridge\pointcloud.npz, and rerun
  warnings.warn(msg)
.EEC:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\renderer\utils.py:114: UserWarning: Arg x with type <class 'NoneType'> is not broadcastable
  warnings.warn(msg % (k, type(v)))
C:\Users\think\Anaconda3\lib\site-packages\pytorch3d-0.2.5-py3.6-win-amd64.egg\pytorch3d\renderer\utils.py:114: UserWarning: Arg y with type <class 'NoneType'> is not broadcastable
  warnings.warn(msg % (k, type(v)))
..E..E...........EETHCudaCheck FAIL file=C:\w\1\s\windows\pytorch\torch/csrc/generic/serialization.cpp line=148 error=719 : unspecified launch failure
E

**Comment by bottler** [comment]
There is not enough information here - we can see the warnings and the error, but not anything else. In particular I have no idea which test produces that error. Maybe adding a `-v` option will help. Can you try ` python -m unittest discover -p *.py -v`? Thanks
