### ISSUE TITLE
How to do the camera coordinate system transfer

### ISSUE THREAD

**Issue by jiaxiangshang** [facebookresearch/pytorch3d#347]
##  Questions on how to use PyTorch3D

I have rotation matrix and translation that defined by image plane coordinate(Y+ down, X+ right, Z+ point in the screen).

When I convert this rotation matrix/translation(R,T) to OpenGL coordinate(like do some axis flip, matmul a rotation matrix like below), 
`   
    # -1 for x axis and y axis flip(this is for pytorch3d flip)
    mtx_inv = torch.eye(3).to(device)
    mtx_inv[0, 0] = -1
    mtx_inv[1, 1] = -1
    mtx_inv[2, 2] = 1
`
it can render the right images.
However, when I try to convert this (R,T) to fit pytorch3d's setting, it do not work.

I check all the related issues, but it does not have a solution. Can you just give an easy example to illuminate this? By the way, I read the note/camera carefully, it really good and clear. However, it can not teach me to find the bug.

Really thanks your excellent work, really thanks your help.

**Comment by gkioxari** [comment]
Hi @jiaxiangshang 
Our coordinate system assumptions are indeed different that the one in OpenGL. We have written extensive notes on the coordinate systems we assume for rendering purposes here: 

* https://github.com/facebookresearch/pytorch3d/blob/master/docs/notes/cameras.md
* https://github.com/facebookresearch/pytorch3d/blob/master/docs/notes/renderer_getting_started.md

**Comment by jiaxiangshang** [comment]
Hi @gkioxari 
I have read this carefully, but flip or rotate x axis and y axis not work for me(as we have x,y axis different from pyt3d)/
Thanks your quick reply.

**Comment by jiaxiangshang** [comment]
https://github.com/facebookresearch/pytorch3d/issues/294#issue-668787976
I close this because ZJB locates the problem.

**Comment by nikhilaravi** [comment]
Can we close this issue?

**Comment by jiaxiangshang** [comment]
@nikhilaravi Yes, thanks again for your good work.
