### ISSUE TITLE
How to implement Spherical Harmonics Lighting in the pytorch3d pipline ?

### ISSUE THREAD

**Issue by tuanhui-li** [facebookresearch/pytorch3d#349]
I find that there are only directional light and pointlight in the lighting function file, how to use the Spherical Harmonics Lighting in pytorch3d ?

**Comment by Agent-INF** [comment]
Hi, I also want to know whether PyTorch3D supports Spherical Harmonics Lighting?
I'm planning to render UV textures (not vertex textures) with Spherical Harmonics Lighting, have you found a way to implement this?

**Comment by tuanhui-li** [comment]
I changed to tf-mesh-render, but I think you can send the diffuse after sh light as the uv texture in pytorhc3d.-------- 原始邮件 --------发件人： Agnet-INF <notifications@github.com>日期： 2020年9月17日周四 10:42收件人： facebookresearch/pytorch3d <pytorch3d@noreply.github.com>抄送： tuanhui-li <lth17@mails.tsinghua.edu.cn>, State change <state_change@noreply.github.com>主    题： Re: [facebookresearch/pytorch3d] How to implement Spherical Harmonics Lighting in the pytorch3d pipline ? (#349)
Hi, I also want to know whether PyTorch3D supports Spherical Harmonics Lighting?
I'm planning to render UV textures (not vertex textures) with Spherical Harmonics Lighting, have you found a way to implement this?

**Comment by Agent-INF** [comment]
Thanks for your advice!

**Comment by xungeer29** [comment]
> I changed to tf-mesh-render, but I think you can send the diffuse after sh light as the uv texture in pytorhc3d.

There seems to be no  Spherical Harmonics Lighting  in tf-mesh-render, or I didn’t find it.
