### ISSUE TITLE
Seems to find a simple bug in a class PointLights.

### ISSUE THREAD

**Issue by WonwoongCho** [facebookresearch/pytorch3d#351]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## 🐛 Bugs / Unexpected behaviors

While doing my research, I just found out an unexpected bug in a light module. The reason was very simple, so if it is unexpected behavior, please update the code.

To elaborate,I was doing a batch process, so that all the input tensor of the light class were size of (B, 3). e.g., location=(B,3)
The problem that I encountered was caused by unmatched dimensions within normals and direction at line 67 in a script named lighting.py. After some struggles, I just noticed that it comes from an unexpected broadcasting when obtaining a direction vector (at line 263 in the lighting script). For the better understanding on my words, please refer to the picture below.

![Screen Shot 2020-09-09 at 3 25 12 PM](https://user-images.githubusercontent.com/20943085/92564308-e7c90480-f2b3-11ea-902e-891b87a52f4b.png)

As can be seen in the bottom of the above picture, the third dimension (from zero) of the direction vector has a size of 64, which seems to be an unanticipated one.

 As an ad hoc way to settle, I just put the location vector of size (B,1,1,1,3), and this results in a direction vector of which size is (B,H,W,1,3).

If it is an unintended behavior, please update this.
Thank you! 

NOTE: Please look at the existing list of Issues tagged with the label ['bug`](https://github.com/facebookresearch/pytorch3d/issues?q=label%3Abug). **Only open a new issue if this bug has not already been reported. If an issue already exists, please comment there instead.**.

## Instructions To Reproduce the Issue:

Please include the following (depending on what the issue is):

1. Any changes you made (`git diff`) or code you wrote
```
PointLights(location=(l_param[:,:3].reshape(l_param.size(0),1,1,1,3)))
```
2. The exact command(s) you ran:
3. What you observed (including the full logs):
```
  File "/home/workspace/_3Dface.py", line 129, in forward
    self.rendering(id_param, exp_param, textures, angles, translation, img)
  File "/home/workspace/_3Dface.py", line 183, in rendering
    projected_img = self.phong_renderer(meshes_world=mesh, cameras=self.camera)
  File "/opt/conda/envs/3d/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/envs/3d/lib/python3.7/site-packages/pytorch3d/renderer/mesh/renderer.py", line 49, in forward
    images = self.shader(fragments, meshes_world, **kwargs)
  File "/opt/conda/envs/3d/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/envs/3d/lib/python3.7/site-packages/pytorch3d/renderer/mesh/shader.py", line 70, in forward
    materials=materials,
  File "/opt/conda/envs/3d/lib/python3.7/site-packages/pytorch3d/renderer/mesh/shading.py", line 81, in phong_shading
    pixel_coords, pixel_normals, lights, cameras, materials
  File "/opt/conda/envs/3d/lib/python3.7/site-packages/pytorch3d/renderer/mesh/shading.py", line 28, in _apply_lighting
    light_diffuse = lights.diffuse(normals=normals, points=points)
  File "/opt/conda/envs/3d/lib/python3.7/site-packages/pytorch3d/renderer/lighting.py", line 265, in diffuse
    return diffuse(normals=normals, color=self.diffuse_color, direction=direction)
  File "/opt/conda/envs/3d/lib/python3.7/site-packages/pytorch3d/renderer/lighting.py", line 67, in diffuse
    angle = F.relu(torch.sum(normals * direction, dim=-1))
RuntimeError: The size of tensor a (64) must match the size of tensor b (268435456) at non-singleton dimension 
```

Please also simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

**Comment by nikhilaravi** [comment]
@WonwoongCho I think this is related to another existing issue: https://github.com/facebookresearch/pytorch3d/issues/94. 
We will add a fix for this!

**Comment by unlugi** [comment]
Is there an update for this issue?
