### ISSUE TITLE
How to get the positions of 2d verts  after render  from  the  3D  verts

### ISSUE THREAD

**Issue by ForrestPi** [facebookresearch/pytorch3d#353]
Hi, I am now using pytorch3d  on 3D face reconstruction, but there are some small problems, I  cannot  get 2D landmarks from 3D vertexs
the codes follows blew:

verts, faces, aux = load_obj(trg_obj)
mesh = Meshes([verts], [faces.verts_idx], face_color)
images = renderer(mesh)

but how to  get 2d verts after render  from  the  3D  verts

Thanks

**Comment by matsuren** [comment]
Hi, if you want to get the vertices on screen, you can just use `transform` in the rasterizer.

```python
verts, faces, aux = load_obj(trg_obj)
mesh = Meshes([verts], [faces.verts_idx], face_color)
mesh_on_screen = renderer.rasterizer.transform(mesh)

# Visualize vetex positions on screen
verts_on_screen = mesh_on_screen.verts_packed().detach().cpu().numpy()
plt.plot(verts_on_screen[:, 0], verts_on_screen[:, 1], 'ro')
```

Thanks,

**Comment by nikhilaravi** [comment]
Thanks @matsuren for replying to this! Yes you can transform the 3D vertices using the `rasterizer.transform` which will apply the camera transformations passed into the `rasterizer`.

**Comment by ForrestPi** [comment]
@matsuren  thanks

**Comment by gkioxari** [comment]
Closing this issue! Feel free to reopen if you have more questions.
