### ISSUE TITLE
Strange gap between triangle meshes

### ISSUE THREAD

**Issue by matsuren** [facebookresearch/pytorch3d#355]
## 🐛 Bugs / Unexpected behaviors
When I rendered two triangle meshes, there was a strange gap between the meshes as shown in the image below.
![gap_between_meshes](https://user-images.githubusercontent.com/10295060/92921020-476b0f80-f46e-11ea-8d31-a92a75b41d3d.png)

Two triangle meshes were connected, so there should be no gap between them.

## Instructions To Reproduce the Issue:
The code to reproduce the issue:

```python
import torch
import numpy as np
from skimage.io import imread, imsave

from pytorch3d.structures import Meshes
# rendering components
from pytorch3d.renderer import (
    look_at_view_transform,
    FoVPerspectiveCameras, 
    PointLights, 
    RasterizationSettings, 
    MeshRenderer, 
    MeshRasterizer,  
    HardPhongShader,
    TexturesVertex,
    BlendParams
)

device = torch.device("cuda:0")

# Create two triangle meshes
vertices = torch.from_numpy(
    np.array(
        [[1, 1, 0], [-1, 1, 0], 
         [-1, -1, 0], [1, -1, 0]],
        dtype=np.float32))

faces = torch.from_numpy(np.array([
    [0, 1, 2],
    [0, 2, 3],
]))

#
verts_rgb = torch.ones_like(vertices)[None] 
textures = TexturesVertex(verts_features=verts_rgb.to(device))

# Construct mesh
mesh = Meshes(
    verts=[vertices.to(device)], faces=[faces.to(device)], textures=textures)

# Setup renderer
R, T = look_at_view_transform(2.0, 0, 0, device=device)
cameras = FoVPerspectiveCameras(R=R, T=T, device=device)
lights = PointLights(device=device, location=[[0.0, 0.0, 3.0]])
raster_settings = RasterizationSettings(image_size=64)

blend_params = BlendParams(background_color=(0.,0.,0.), sigma=0.0, gamma=0.0)
renderer = MeshRenderer(
    rasterizer=MeshRasterizer(
        cameras=cameras, 
        raster_settings=raster_settings
    ),
    shader=HardPhongShader(
        device=device, 
        cameras=cameras,
        lights=lights,
        blend_params=blend_params
    )
)

# render image
images = renderer(mesh)
image = images.detach().cpu().numpy()[0][...,:3]
imsave('gap_between_meshes.png', (255*image).astype(np.uint8))
```

## Suspicious lines that might cause the issue:
I think the issue occurs when rasterized pixels are perfectly on the edge of the triangles. When I moved the mesh a little bit as shown bellow, the gap disapeared.
```python
offset_x = 0.0
offset_y = 0.01
offset = torch.zeros_like(mesh.verts_packed())
offset[:, 0] = offset_x
offset[:, 1] = offset_y
new_mesh = mesh.offset_verts(offset)
```
A suspicious line that might cause the issue is [here](https://github.com/facebookresearch/pytorch3d/blob/f2eb34dc7a133b319d01d0fe0e208f385498f009/pytorch3d/renderer/mesh/rasterize_meshes.py#L399). So, when I changed this line to `if not inside and (dist-kEpsilon) >= blur_radius:`, the gap was gone. 

Can I change to `if not inside and (dist-kEpsilon) >= blur_radius:`? Or are there any bad effects?
(I know I need to change cuda code for the implementation, but I'd like to make sure the logic first using `rasterize_meshes_python`.)

**Comment by gkioxari** [comment]
The change you made is essentially equivalent to setting `blur_radius=kEpsilon` and that is correct. You should set your `blur_radius` to something so that the rendering is smooth. Otherwise it's expected to see such lines especially in lower resolutions.

**Comment by matsuren** [comment]
Oh, I see. Thank you!
