### ISSUE TITLE
R2N2 Dataloader SPLITS_PATH

### ISSUE THREAD

**Issue by unlugi** [facebookresearch/pytorch3d#356]
Hello, thank you for the great library!

I am following the Dataloaders tutorial, however I couldn't figure out what the input is to SPLITS_PATH? I know ShapeNet has some pre-determined train/val/splits from previous challenges: is there something for R2N2, as well? 

     r2n2_dataset = R2N2("train", SHAPENET_PATH, R2N2_PATH, SPLITS_PATH, return_voxels=True)

Looking through the code I know that a json file is needed but I am stuck!
        # Store synset and model ids of objects mentioned in the splits_file.

Thanks!

**Comment by gkioxari** [comment]
@unlugi 
It refers to the R2N2 split which you can fetch from here: https://github.com/facebookresearch/meshrcnn/blob/master/datasets/shapenet/download_shapenet.sh#L16

**Comment by unlugi** [comment]
@gkioxari 
Thank you!

**Comment by nikhilaravi** [comment]
We will update the tutorial with this link!
