### ISSUE TITLE
Install through PyPI

### ISSUE THREAD

**Issue by anandijain** [facebookresearch/pytorch3d#36]
I am wondering why the package is not on PyPI. I am thinking it is because of some of the dependencies, but I'm not sure.

Installing through PyPI without conda makes it much easier for anyone to get started.
This is useful for many users.

**Comment by nikhilaravi** [comment]
@anandijain this is on our roadmap! We hope to release a PyPi package soon.

**Comment by bottler** [comment]
pytorch3d is now available on pypi for Mac and Linux. These are CPU-only builds - they don't use cuda.
