### ISSUE TITLE
Single image 3D face fitting demo

### ISSUE THREAD

**Issue by HavenFeng** [facebookresearch/pytorch3d#360]
## 🚀 Feature

The demo provides an analysis-by-synthesis framework to fit a textured 3DMM model ([FLAME](https://flame.is.tue.mpg.de/)) to a single image. 
It can be found [here](https://github.com/HavenFeng/photometric_optimization).

## Motivation
- We use this repo to build the FLAME texture space from in-the-wild images, which covers a large range of ethnicities, age groups, etc.

- [People are asking for it](https://github.com/facebookresearch/pytorch3d/issues/324#issue-681048815), so we think it would be useful if it can be integrated into pytorch3d.
## Pitch
Currently, our repo is mainly using the differentiable rasterizer of PyTorch3D, other modules (texture, light, camera, etc.) are custom implementations. 
More details about the demo can be found [here.](https://github.com/HavenFeng/photometric_optimization)

**Comment by gkioxari** [comment]
Hi @HavenFeng 
Thanks for reaching out to us! It seems you are providing a link to an existing demo that you have built. Is this correct? What is your request exactly?

**Comment by HavenFeng** [comment]
Hi @gkioxari,
Thank you for your reply. Yes, the demo code uses the differentiable rasterizer of PyTorch3D. The main motivation for this demo is that the non-rigid deformation of a parametric 3D model (e.g. of faces, bodies, etc) to an image is a frequently requested application in the field of computer vision and computer graphics and plenty of people have been approaching us for such an application. TensorFlow graphics also included such a 3D face model fitting demo in their roadmap (https://twitter.com/_TFGraphics_/status/1261321871368294400?s=20). However we believe that a much broader audience might be interested in such a 3D model fitting application than the few people visiting our repository. Further, having such a solution aside from the main PyTorch3D repository is challenging as PyTorch3D is rapidly evolving and hence the demo might soon not work anymore after some updates. So we think it could be useful to natively support the fitting to images with the parametric model in PyTorch3D. This could be by 

- either as a tutorial demo that demonstrates how to fit the 3D face model to images and how to render it, or

- a native function (maybe similar to camera alignment in ops), such that people can directly do the non-rigid fitting to an image without requiring outside functionality.

We would be happy to support such an attempt. What do you think about this?

**Comment by gkioxari** [comment]
Hi @HavenFeng 
I looked at your repo and it looks great and a great application of PyTorch3D! Including a demo on this in PyTorch3D would be great. However, because of the nature of your project and the use of data of human faces, we would have to conduct our own legal review of that data before including it in PyTorch3D. For this reason, we have to politely decline your offer. 
We hope that in the future we can include a demo on deformable shape fitting! 

Thanks again for your post and bringing your work to our attention!

**Comment by HavenFeng** [comment]
Hi @gkioxari 
Thanks a lot for your attention! It's a pity but we understand the concerns due to face data. It would be great to see a deformable shape fitting demo in PyTorch3D later on.
 
 
> because of the nature of your project

Could you elaborate a bit more about this? Do you mean extracting 3D face shapes from in-the-wild images? 
Maybe we should also be aware of it.

**Comment by gkioxari** [comment]
"nature of project" here refers purely to the use of face data and face images which for us would require intense legal review before publishing anything even on this repo.
