### ISSUE TITLE
.ply loading is broken for files with additional point properties

### ISSUE THREAD

**Issue by classner** [facebookresearch/pytorch3d#363]
## 🐛 Bugs / Unexpected behaviors

.ply files with additional point properties can't be loaded with the `load_ply` function.

## Instructions To Reproduce the Issue:

Consider a file with the following header:

```
ply
format ascii 1.0
element vertex 1
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
end_header
0.0 0.0 0.0 0 0 0
```

This will trigger the ValueError at https://github.com/facebookresearch/pytorch3d/blob/61121b9f2ce29601406d470468abffe2fb76057f/pytorch3d/io/ply_io.py#L656, even though this is a perfectly valid point according to spec and header. This goes for binary as well as ascii formats. The parsing of the points works in the first place, but this ValueError prevents successful completion of the method.

It's another question on how additional properties should be handled. I think it would be fair to emit a warning and drop them if PyTorch3D doesn't want to support them; or they could be returned in an additional dictionary[str, torch.Tensor] with one entry per property or similar.

**Comment by bottler** [comment]
There are a few things which need to change to allow pointclouds to be loaded from PLY files. For example I think you've already had to bypass `"The ply file has no face element."` We are working on this.

**Comment by bottler** [comment]
This is now implemented https://github.com/facebookresearch/pytorch3d/commit/95707fba1c8eff99757691468f440f9ce63c8027 .

You have to use the new interface to get it. I.e. `pointcloud = IO().load_pointcloud("filename.ply")`.

**Comment by lorinczszabolcs** [comment]
The current implementation works for colors, but if I am not mistaken, other properties are still left out. Consider for example a LiDAR scan containing intensity information for each point. In that case, the "intensity" property is not returned. Am I missing something?

Thank you in advance!
