### ISSUE TITLE
pytorch3d only read pointcloud by numpy？

### ISSUE THREAD

**Issue by Junwei-LV** [facebookresearch/pytorch3d#364]
from the doc, pytorch3d read the pointcloud by npz. 
I wanna ask that if there can be more examples to read pointcloud in other forms.

**Comment by gkioxari** [comment]
The output from our IO functions is a torch tensor. In the case of pointclouds, the tensor has shape Px3. Could you be more specific as to what formats or forms you'd like for us to support?

**Comment by Junwei-LV** [comment]
> The output from our IO functions is a torch tensor. In the case of pointclouds, the tensor has shape Px3. Could you be more specific as to what formats or forms you'd like for us to support?

thanks for answering, because of my fresh year in this field, so i want to know how to get sample from obj, and then put the pointcloud into the pointrenderer. (I also wonder if there is rgb data in the points after getting sample from obj)

**Comment by gkioxari** [comment]
We have functions for all this
`sample_points_from_meshes` samples points on the surface of a mesh. You can then create a Pointclouds object with the sampled points (and the normals if applicable) and pass it through the renderer. Follow our tutorials for help with the Pointcloud renderer.
