### ISSUE TITLE
Saving Predicted Texture with Mesh

### ISSUE THREAD

**Issue by sjcv** [facebookresearch/pytorch3d#365]
I am experimenting with the fit_textured_mesh tutorial, and while exporting the mesh as .obj file, I am looking to save/export the predicted texture as well. Is there any method in Pytorch3d that allow this? Thanks!

**Comment by gkioxari** [comment]
If you want to visualize the texture, you can visualize the textured renderings of the shape, as we show in the tutorial, from many viewpoints, which is the only way to inspect textured shapes.

**Comment by sjcv** [comment]
Thanks @gkioxari.
