### ISSUE TITLE
Error following INSTALL.md guidelines on windows

### ISSUE THREAD

**Issue by Timothy-Bellaiche** [facebookresearch/pytorch3d#367]
## 🐛 Bugs / Unexpected behaviors
I face the following error building wheel for pytorch3d when following the install instructions on windows  
ERROR: Command errored out with exit status 1:

## Instructions To Reproduce the Issue:

`conda create -n pytorch3d python=3.8`
`conda activate pytorch3d`
`conda install -c pytorch pytorch=1.6.0 torchvision cudatoolkit=10.2` 
`conda install -c conda-forge -c fvcore fvcore`
`pip install "git+https://github.com/facebookresearch/pytorch3d.git@stable"`

This error has been encountered with cuda 11, cuda 10.2 and cuda 10.1 (currently cuda 11 is installed)  
I tried to apply the changes to the module.h file described in the INSTALL.md file but it appears that it was supposed to be fixed in this PR : https://github.com/pytorch/pytorch/pull/40676/files

## Full logs
[error_logs.txt](https://github.com/facebookresearch/pytorch3d/files/5249241/error_logs.txt)

**Comment by bottler** [comment]
The error is `error: a member with an in-class initializer must be const`. The compiler is too old, or is acting too old, to build pytorch3d or pytorch. The warning `cl : Command line warning D9002 : ignoring unknown option '-std=c++14'` is also informative.

(This is windows I think.) Which compiler and version is this? You need one which supports c++14. Can you use the latest visual studio compiler?

**Comment by Timothy-Bellaiche** [comment]
I updated to Visual Build Tools 2019 v16.7.3 (latest), I now have the following error : 
`C:\Users\Windows\anaconda3\envs\pytorch3d\lib\site-packages\torch\include\pybind11\cast.h(1449): error: expression must be a pointer to a complete object type`
`1 error detected in the compilation of "C:/Users/Windows/AppData/Local/Temp/pip-req-build-0nyg1j22/pytorch3d/csrc/blending/sigmoid_alpha_blend.cu".` 

Here is the line in question in cast.h
`1448    explicit operator type*() { return this->value; }`
`1449    explicit operator type&() { return *(this->value); }`
`1450    explicit operator holder_type*() { return std::addressof(holder); }`


Full logs :
[error_logs_v2.txt](https://github.com/facebookresearch/pytorch3d/files/5256187/error_logs_v2.txt)



Here is my config of Visual Build Tools
![image](https://user-images.githubusercontent.com/9440659/93782023-57cb7900-fc2a-11ea-86be-824338a43ce0.png)

**Comment by bottler** [comment]
To compile on windows you have to make some changes to some files in the torch install directory. These are originally explained in Install.md. For pytorch 1.6 I think the updated version of the changes are given in issue #323.

**Comment by nikhilaravi** [comment]
@Timothy-Bellaiche please follow the instructions shared by @bottler. If you still have questions you can reopen this issue.
