### ISSUE TITLE
how to render an obj with per-vertex color without light

### ISSUE THREAD

**Issue by kalyo-zjl** [facebookresearch/pytorch3d#369]
Thank you for sharing pytorch3d, a very useful rendering engine, and mesh library. I have a problem when using it, and can you give me some suggestions? 
I have an obj file with vertex color, how can I set a proper light and shader to render the desired image?
To be specific, I have another render code in the following. It seems that in this code, the per-pixel value of the rendered image is only the linear combination of the vertex color, and it's nothing to do with the light. However, in pytorch3d, you need to specify the light in the shader. How can I set the light or shader or something else to render the desired image as the following code? I have tried various shader and (Point and Directional) light (ambient_color, diffuse_color, specular_color) in pytorch3d, but none of them has the same effect. If I set intensity values to `(0, 0, 0)` when initializing the `Lights` class, the rendered image will be all black.
    
    The another render code without light is as follows.
    def _get_gen_texture(self, Vs, Rs):
        batch_size = Vs.size(0)
        self._get_render_info_th_gpu(Vs)
        illegal_ids = self.gpu_xy_tri_ids < 0 # !!! 
        self.gpu_imgs_mask.fill_(1)
        self.gpu_imgs_mask[illegal_ids] = 0
        self.gpu_xy_tri_ids[illegal_ids] = 0
        
        # each pixel in a triangle
        Vids = self.model_F[self.gpu_xy_tri_ids.view(-1).cpu().numpy(), :]
       
        Vs = Vs.view(batch_size, -1, 3)
        Rs = Rs.view(batch_size, -1, 3)

        ids = self.rep_img3_ids 
        Vids = Vids.reshape(-1)
        # p(Vs.size(), ids.shape, Vids.shape)

        # each pixel in a trangle which has three vertices and each vertice has x, y, z
        sel_Vs = Vs[ids, Vids].view(-1, 3, 3)
        sel_Rs = Rs[ids, Vids].view(-1, 3, 3)

        ids = self.gpu_imgs_mask.view(-1) == 0

        # Remove associations (no need to be auto differentiation)
        sel_Vs[ids] = 0
        sel_Rs[ids] = 0

        sel_Vs2d = sel_Vs[:, :, :2]
        u, v, w = calc_barycentric(self.gpu_bxy_index_table.view(-1, 2), sel_Vs2d[:, 0], sel_Vs2d[:, 1], sel_Vs2d[:, 2])

        # n_mix, 3 (n_mix is all the pixels of batch)
        th_bary = torch.stack((u, v, w), 1)

        #  n*1*3 x n*3*1 (n=b*imgw*imgh)  
        gen_color_BGR = torch.bmm(th_bary.unsqueeze(1), sel_Rs).view(batch_size, self.imgh, self.imgw , 3)
        # ocv
        return gen_color_BGR

**The simplest solution is to set all the intensity values to `(0, 0, 0)` when initializing the `Lights` class.  A cleaner approach would be to define your own shader which does not apply lighting e.g.** 

_Originally posted by @nikhilaravi in https://github.com/facebookresearch/pytorch3d/issues/278#issuecomment-659799688_

**Comment by jiaxiangshang** [comment]
So, what is the final solution? (:

**Comment by gkioxari** [comment]
You can write your own custom shader to do whatever you want. Phong and Gouraud shading use light by definition. But if you wish to not use lighting then you can construct your own shader. Here is an example:

```
class myShader(torch.nn.Module):

    def __init__(
        self, device="cpu", cameras=None, blend_params=None
    ):
        super().__init__()
        self.cameras = cameras
        self.blend_params = blend_params if blend_params is not None else BlendParams()

    def forward(self, fragments, meshes, **kwargs) -> torch.Tensor:
        cameras = kwargs.get("cameras", self.cameras)
        if cameras is None:
            msg = "Cameras must be specified either at initialization \
                or in the forward pass of TexturedSoftPhongShader"
            raise ValueError(msg)
        # get renderer output
        blend_params = kwargs.get("blend_params", self.blend_params)
        texels = meshes.sample_textures(fragments)
        images = softmax_rgb_blend(texels, fragments, blend_params)

        return images
```

**Comment by nikhilaravi** [comment]
@kalyo-zjl defining your own custom shader will be the cleanest solution. You could also just have ambient lighting and turn off specular/diffuse lighting (set to 0) if you want to use an existing shader.

**Comment by jiaxiangshang** [comment]
> @kalyo-zjl defining your own custom shader will be the cleanest solution. You could also just have ambient lighting and turn off specular/diffuse lighting (set to 0) if you want to use an existing shader.

This work for me, thanks.

**Comment by kalyo-zjl** [comment]
@gkioxari @nikhilaravi Got it, many thanks!
