### ISSUE TITLE
ModuleNotFoundError: No module named 'pytorch3d'

### ISSUE THREAD

**Issue by jinfagang** [facebookresearch/pytorch3d#37]
```
pip install pytorch3d
```

have that installed but still can not import.

**Comment by bottler** [comment]
The pytorch3d library is currently not available through `PyPI`, so `pip install pytorch3d` does not install it. Can you install in one of the ways suggested in [INSTALL.md](https://github.com/facebookresearch/pytorch3d/blob/master/INSTALL.md)?
