### ISSUE TITLE
The Docs of FoVPerspectiveCameras produce a mistake.

### ISSUE THREAD

**Issue by TsukamotoShuchi** [facebookresearch/pytorch3d#370]
The doc of FoVPerspectiveCameras says(refer to https://pytorch3d.readthedocs.io/en/latest/modules/renderer/cameras.html):
f1 = -(far + near)/(far−near)
f2 = -2*far*near/(far-near)
h1 = (max_y + min_y)/(max_y - min_y)
w1 = (max_x + min_x)/(max_x - min_x)
tanhalffov = tan((fov/2))
s1 = 1/tanhalffov
s2 = 1/(tanhalffov * (aspect_ratio))

P = [
        [s1,   0,   w1,   0],
        [0,   s2,   h1,   0],
        [0,    0,   f1,  f2],
        [0,    0,    1,   0],
]

but in source code(refer to https://pytorch3d.readthedocs.io/en/latest/_modules/pytorch3d/renderer/cameras.html#FoVPerspectiveCameras.__init__):
        P[:, 0, 0] = 2.0 * znear / (max_x - min_x)
        P[:, 1, 1] = 2.0 * znear / (max_y - min_y)
        P[:, 0, 2] = (max_x + min_x) / (max_x - min_x)
        P[:, 1, 2] = (max_y + min_y) / (max_y - min_y)
        P[:, 3, 2] = z_sign * ones

        # NOTE: This maps the z coordinate from [0, 1] where z = 0 if the point
        # is at the near clipping plane and z = 1 when the point is at the far
        # clipping plane.
        P[:, 2, 2] = z_sign * zfar / (zfar - znear)
        P[:, 2, 3] = -(zfar * znear) / (zfar - znear)

f1 and f2 is wrong in doc.

**Comment by nikhilaravi** [comment]
@TsukamotoShuchi thanks for raising this issue. We will update the documentation.

**Comment by gkioxari** [comment]
Fixed by https://github.com/facebookresearch/pytorch3d/commit/e5ac38aa87efd440b356cb8d8e2d424efac3d523. Thank you @TsukamotoShuchi for bringing this to our attention. Closing this!
