### ISSUE TITLE
The performance for back face rendering seems look strange

### ISSUE THREAD

**Issue by lishang6257** [facebookresearch/pytorch3d#374]
Thank you for sharing pytorch3d, a very useful 3D library. when using pytorch3d to render a synthetic face scan(code has pushed on [issue_for_torch3d](https://github.com/lishang6257/issue_for_torch3d)), i find the back faces have be rendered in Pic.1(the region marked by red circle) .
![face](https://user-images.githubusercontent.com/26080906/93900379-e376ff80-fd27-11ea-9ff0-8119314a2024.png)
Can you give me some advice  to solve this problem?

**Comment by nikhilaravi** [comment]
@lishang6257 glad to hear you have found PyTorch3D useful for your work. Yes there is a back face culling setting:

https://github.com/facebookresearch/pytorch3d/blob/f34f4073f0287ec961f43dd451d9470baf0db557/pytorch3d/renderer/mesh/rasterizer.py#L41

By default it is turned off so when you are initializing the `raster_settings` for the renderer simply set `cull_backfaces=True`.

**Comment by lishang6257** [comment]
Thanks very much for your reply. However, I has tried this settting before, it cannot meet my need. Fig.1 is the result when cull_backfasces=False, while Fig.2 is true. I find the the pixels marked in red circle  bewteen Fig.1 and Fig.2 are the same, but the region in Fig.1 shouldnot be rendered(i think they are back faces in this case). Hope for your reply.
![image](https://user-images.githubusercontent.com/26080906/93951774-cd922a80-fd79-11ea-8eab-dab8f5fcbbd0.png)
![image](https://user-images.githubusercontent.com/26080906/93951788-d97dec80-fd79-11ea-9fa7-c754cbfee16f.png)

**Comment by lishang6257** [comment]
Can you give me suggestions to fix this problem?

**Comment by gkioxari** [comment]
Hi @lishang6257 
I can't reproduce your issue. I am running your code with `cull_backfaces=True` in the rasterization settings (I also uncommented the lines here: https://github.com/lishang6257/issue_for_torch3d/blob/b3abe9742d529603eb23f445fc17895781c19958/test/test_render_meshes.py#L79-L81). 
In the code you provide two configurations for R, T. I ran both and I get the following outputs:

![img3](https://user-images.githubusercontent.com/4369065/94198413-15917a00-fe6c-11ea-82dd-4bb9743867d8.png)
![img2](https://user-images.githubusercontent.com/4369065/94198417-16c2a700-fe6c-11ea-9966-c555ac3fc97c.png)

I also visualize the mesh with MeshLab (and turned cull to On) and the result seems consistent.

**Comment by lishang6257** [comment]
Can share the version of pytorch3d you used for your test, thanks.

**Comment by gkioxari** [comment]
I am using the PyTorch3D master.

**Comment by lishang6257** [comment]
Thanks very much for your advice
