### ISSUE TITLE
Using Deprecated CircleCI Xcode Images

### ISSUE THREAD

**Issue by zpao** [facebookresearch/pytorch3d#375]
CircleCI is deprecating some Xcode images. See https://discuss.circleci.com/t/deprecation-notice-xcode-9-0-1-and-xcode-9-3-1/37382

Here's the usage: https://github.com/facebookresearch/pytorch3d/blob/f34f4073f0287ec961f43dd451d9470baf0db557/.circleci/config.yml#L187-L188

**Comment by nikhilaravi** [comment]
@zpao thanks for letting us know. We will update the config.

**Comment by nikhilaravi** [comment]
This has now been updated by @bottler.
