### ISSUE TITLE
finding external surface sample_points_from_meshes

### ISSUE THREAD

**Issue by grogdrinker** [facebookresearch/pytorch3d#376]
## ❓ Questions on how to use PyTorch3D

Hello,
I am trying to use pytorch3d to get the external surface of an object in a grid. 
Here what I currently do:
-I start from a NxLxLxL batched grid. Every cube has a float value describing the "probability" of being full
- I use cubify to get meshes from it
- I use sample_points_from_meshes to sample points on the surface

sample_points_from_meshes samples points on every surface, even the internal ones. Lets say I have a sphere with a hole in the middle, sample_points_from_meshes will sample points in the centre of the sphere as well. Is there a way to find the external surface only? alternatively, is there a way to get a list of non-connected surfaces?
Thanks in advance,
Gabriele

**Comment by gkioxari** [comment]
Hi @grogdrinker 
`sample_points_from_meshes` will sample points from all faces of the mesh, regardless of other properties (external vs internal, location, etc.). 

The definition of external surface is not very clear especially when meshes can have many disconnected components, any genus etc. To get a list of disconnected components, you can simply group the faces of the mesh such that no faces that belong to the different groups share an edge. That should be easy to do.
