### ISSUE TITLE
How to set different fov values in a batch images

### ISSUE THREAD

**Issue by ForrestPi** [facebookresearch/pytorch3d#378]
## ❓ Questions on how to use PyTorch3D
In my task, I have a problem, every image has different fov value, So how to set a batch of different fov value in FoVPerspectiveCameras

**Comment by gkioxari** [comment]
If you have 2 images in your batch then

```
cameras = FoVPerspectiveCameras(fov=(10.0, 60.0))
```

The projection matrix `cameras.get_projection_transform().get_matrix()` will be of shape `2x4x4` with the corresponding fov values.

**Comment by nikhilaravi** [comment]
To expand on @gkioxari's comment, in general all the inputs to the cameras can be batched. We have an example of how to render a batch on meshes each of which has different camera parameters - have a look at the last section of this tutorial: https://github.com/facebookresearch/pytorch3d/blob/master/docs/tutorials/render_textured_meshes.ipynb

**Comment by gkioxari** [comment]
Closing this!
