### ISSUE TITLE
ModuleNotFoundError: No module named 'pytorch3d.visualization'

### ISSUE THREAD

**Issue by OOF-dura** [facebookresearch/pytorch3d#385]
When I finish the installation and ran some codes, I got:

```
ModuleNotFoundError: No module named 'pytorch3d.visualization'
```
According to the pycharm, there are some module can not be found:
![image](https://user-images.githubusercontent.com/22954901/95010777-a5020e80-065e-11eb-9781-ce4a3944544d.png)

I am following the install.md https://github.com/facebookresearch/pytorch3d/blob/master/INSTALL.md

There is no error when I made the installation.

System info:
- Ubuntu 16.04
- CUDA 10.0
- python 3.6.12 |Anaconda, Inc.
- I am using conda

**Comment by OOF-dura** [comment]
To make it clear, my commends are:
```
conda create -n Pytorch3D python=3.6
conda activate Pytorch3D
conda install -c pytorch pytorch=1.4.0 torchvision cudatoolkit=10.0
conda install -c conda-forge -c fvcore fvcore
conda install jupyter
pip3 install scikit-image matplotlib imageio plotly
pip3 install black 'isort<5' flake8 flake8-bugbear flake8-comprehensions
conda install pytorch3d -c pytorch3d
```

I want pytorch3D to work with CUDA.


Thank you in advance!

**Comment by bottler** [comment]
What do you mean by "according to the pycharm". The latest release of pytorch3d, which you appear to have successfully installed, does not contain a module called "pytorch3d.visualization". The bleeding-edge main branch does.

**Comment by nikhilaravi** [comment]
Are you trying to run one of the tutorials? As @bottler mentioned, we have several features in the master branch which are not yet available in the conda packages, visualization is one of these features. If you want to run this notebook please install PyTorch3D from GitHub following the instructions in INSTALL.md.
