### ISSUE TITLE
Python 3d


### ISSUE THREAD

**Issue by Monoane** [facebookresearch/pytorch3d#387]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## 🐛 Bugs / Unexpected behaviors

NOTE: Please look at the existing list of Issues tagged with the label ['bug`](https://github.com/facebookresearch/pytorch3d/issues?q=label%3Abug). **Only open a new issue if this bug has not already been reported. If an issue already exists, please comment there instead.**.

## Instructions To Reproduce the Issue:

Please include the following (depending on what the issue is):

1. Any changes you made (`git diff`) or code you wrote
```
<put diff or code here>
```
2. The exact command(s) you ran:
3. What you observed (including the full logs):
```
<put logs here>
```

Please also simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

**Comment by gkioxari** [comment]
Incomplete/non-existent description.
