### ISSUE TITLE
More Point Sampling Methods from meshes

### ISSUE THREAD

**Issue by hansen7** [facebookresearch/pytorch3d#39]
## 🚀 Feature
More Point Sampling Methods from meshes

## Motivation

It would be great if I could have more options on how to get the set of surface point with different point samplings, such as 

- Furthest Point Sampling [referred paper](https://papers.nips.cc/paper/7095-pointnet-deep-hierarchical-feature-learning-on-point-sets-in-a-metric-space.pdf)
- Poisson Disk Sampling  [referred paper](https://dl.acm.org/doi/10.1145/3272127.3275110)

## Pitch

More sampling options will enable us to have better understanding on how our model will perform under different situations :)

If you think its necessary, I can submit a P.R

**Comment by nikhilaravi** [comment]
@hansen7 thanks for the suggestion! :)

Could share some more details about your proposed implementation for either of the two methods you mentioned above? 

Please be aware that for new features to PyTorch3D we require:
1)  CPU and GPU implementations 
2) Comprehensive unit tests and benchmark tests (following the format in the `tests` folder)
3) All style checks and unit tests must pass 
4) Any changes to the public API to be discussed first in this issue (i.e please follow the API format from the current [`sample_points_from_meshes`](https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/ops/sample_points_from_meshes.py#L16) function)

As a first step you can also submit a PR with the PyTorch implementation of one of the methods which we can review.  Let us know if you have any questions.

**Comment by williamljb** [comment]
Hi Nikhila Ravi,

If it is not too complicated, it would be great if the current sampling algorithm can have an option to smooth the normals sampled.

Thank you for the great work!

**Comment by nikhilaravi** [comment]
@williamljb FYI farthest point sampling is now available in pytorch3d:

```
from pytorch3d.ops import sample_farthest_points
```

**Comment by williamljb** [comment]
> @williamljb FYI farthest point sampling is now available in pytorch3d in the main branch on GitHub (not yet in a release):
> 
> ```
> from pytorch3d.ops import sample_farthest_points
> ```

Great! Thanks!
