### ISSUE TITLE
How to render an animal with clothes?

### ISSUE THREAD

**Issue by Frank-Dz** [facebookresearch/pytorch3d#390]
For example, I have a cartoon cat: **cat.obj, cat.mtl, cat_texture.png.**
And I design a shirt and a pant for her. both in:
**pant.obj, pant.mtl, pant_texture.png.**
**shirt.obj, shirt.mtl, shirt_texture.png.**
That means I need to load them with pant and shirt outside the cat body mesh and render them at one time.

How can do this?
Can pytorch3d support this?
Thanks!

Best,
Frank

**Comment by Frank-Dz** [comment]
That is to say, how to cover a layer of mesh (cat body) with another layer of mesh (its clothes)?

**Comment by bottler** [comment]
You can load all the meshes, possibly move them manually, and then you can merge them into a single mesh with the function `join_meshes_as_scene`. Then you can render all the objects together. Is that what you are looking for?

**Comment by Frank-Dz** [comment]
> You can load all the meshes, possibly move them manually, and then you can merge them into a single mesh with the function `join_meshes_as_scene`. Then you can render all the objects together. Is that what you are looking for?

Yes, It is. But are there any demos to show this?

Thank you very much!

**Comment by Frank-Dz** [comment]
I just figure it out! Thank you!

**Comment by haiderasad** [comment]
HI @Frank-Dz can you please tell how you added clothes? i am trying to do the same on just simple human body
