### ISSUE TITLE
A transparent result is generated, and the position of the obj cannot be controlled.

### ISSUE THREAD

**Issue by Frank-Dz** [facebookresearch/pytorch3d#392]
- A transparent result is generated.

I am using the demo code to render my own obj:
But I got the result which is pretty transparent.
![a](https://user-images.githubusercontent.com/55009565/95421289-bd7c6c80-096f-11eb-9fe6-7f0d66226d18.png)

Plus, I follow the tutorial and rendered the model  cow:
```
R, T = look_at_view_transform(2.7, 0, 180) 
cameras = FoVPerspectiveCameras(device=device, R=R, T=T)

raster_settings = RasterizationSettings(
    image_size=512, 
    blur_radius=0.0, 
    # faces_per_pixel=1, 
)

lights = PointLights(device=device, location=[[0.0, 0.0, -3.0]])

renderer = MeshRenderer(
    rasterizer=MeshRasterizer(
        cameras=cameras, 
        raster_settings=raster_settings
    ),
    shader=SoftPhongShader(
        device=device, 
        cameras=cameras,
        lights=lights
    )
)

lights.location = torch.tensor([0.0, 0.0, +1.0], device=device)[None]
images = renderer(mesh, lights=lights)
plt.figure(figsize=(10, 10))
plt.imsave('cow.png',images[0, ..., :3].cpu().numpy())
plt.grid("off");
plt.axis("off")
plt.close()
```
The result is not transparent:
![image](https://user-images.githubusercontent.com/55009565/95422346-b9e9e500-0971-11eb-989b-5688e61a1890.png)

-  the position of the obj cannot be controlled.
I want to make the obj to be centered at the image:
However, no matter how I change the parameter: ```elev```
```
R, T = look_at_view_transform(dist=1.8, azim = azim, elev = -15)
```

elev  = -15
![image](https://user-images.githubusercontent.com/55009565/95421412-0502f880-0970-11eb-9923-5c2933a2fd65.png)
elev = 5
![image](https://user-images.githubusercontent.com/55009565/95421607-4eebde80-0970-11eb-87ed-0b427c02e904.png)
elev = 10
![image](https://user-images.githubusercontent.com/55009565/95421653-6e830700-0970-11eb-904d-dbdb01f59b6d.png)

What I really want to achieve is making the obj move to the center of the image without changing the view of the camera.

**Comment by Frank-Dz** [comment]
As for my transparent result, the render setting:
```
import torch
import os
import matplotlib.pyplot as plt
from skimage.io import imread
import matplotlib
matplotlib.use('Agg')
# Util function for loading meshes
from pytorch3d.io import load_objs_as_meshes, load_obj
# Data structures and functions for rendering
from pytorch3d.structures import Meshes
# from pytorch3d.visualization import AxisArgs, plot_meshes
from pytorch3d.renderer import (
    look_at_view_transform,
    FoVPerspectiveCameras, 
    PointLights, 
    DirectionalLights, 
    Materials, 
    RasterizationSettings, 
    MeshRenderer, 
    MeshRasterizer,  
    SoftPhongShader,
    HardPhongShader,
    TexturesUV,
    TexturesVertex
)
from pytorch3d.structures.meshes import (
    Meshes,
    join_meshes_as_batch,
    join_meshes_as_scene,
)
import sys
import os
sys.path.append(os.path.abspath(''))
if torch.cuda.is_available():
    device = torch.device("cuda:0")
    torch.cuda.set_device(device)
else:
    device = torch.device("cpu")

DATA_DIR = "./data"


obj_filename0 = os.path.join(DATA_DIR, "human_mesh/0.obj")
mesh0 = load_objs_as_meshes([obj_filename0], device=device)
texture_image0=mesh0.textures.maps_padded()


mesh = join_meshes_as_scene([mesh0])

batch_size = 8
meshes = mesh.extend(batch_size)

azim = torch.linspace(0, 360, batch_size)
R, T = look_at_view_transform(dist=1.8, azim = azim, elev = 10)
cameras = FoVPerspectiveCameras(device=device, R=R, T=T)



raster_settings = RasterizationSettings(
    image_size=512, 
    blur_radius=0.0, 
)
lights = PointLights(device=device)
lights.location = torch.tensor([[0.0, 0.0, -3.0]], device=device)
renderer = MeshRenderer(
    rasterizer=MeshRasterizer(
        cameras=cameras, 
        raster_settings=raster_settings
    ),
    shader=SoftPhongShader(device=device, cameras=cameras)

)

images = renderer(meshes, cameras=cameras, lights=lights)

counter = 1
for i in images:
    plt.figure(figsize=(512, 512))
    plt.imsave('./batch_output/figure%d.png'%counter, i.cpu().numpy())
    plt.grid("off");
    plt.axis("off");
    plt.close()
    counter = counter+1

print("all tasks finished.")

**Comment by bottler** [comment]
You're saving `i.cpu().numpy()` and you probably mean to save `i[..., :3].cpu().numpy()` right? You aren't wanting to see the alpha channel, which matplotlib is interpreting as transparency.

**Comment by Frank-Dz** [comment]
> You're saving `i.cpu().numpy()` and you probably mean to save `i[..., :3].cpu().numpy()` right? You aren't wanting to see the alpha channel, which matplotlib is interpreting as transparency.

Wow. Yes. It is. 
Thank you for your kind help.

![image](https://user-images.githubusercontent.com/55009565/95471527-9d22d100-09b4-11eb-885f-72886ac1a34b.png)

BTW, if I wanna move this object up under the same view, how can we achieve this?

The tutorial suggests that we should change the value of **elev**. But as you can see what I mentioned above, whenever I change the elev, the view of the camera also changed.

Is this the only way that we move the add a global transition to our obj rather than change the view of our camera?

Thank you!

**Comment by nikhilaravi** [comment]
@Frank-Dz the `look_at_transform` moves the camera on a spherical path at a fixed radius. This is only one option for the world to view transformation applied by the camera. You could set the R & T matrices directly as well. You can also combine transforms e.g. use the `look_at_transform` and then add a vertical translation. 

Depending on what your use case is, shifting the mesh might not be the best solution (e.g. if the vertices need to be in the [-1, 1] range and you shift it out of this range).

**Comment by Frank-Dz** [comment]
> @Frank-Dz the `look_at_transform` moves the camera on a spherical path at a fixed radius. This is only one option for the world to view transformation applied by the camera. You could set the R & T matrices directly as well. You can also combine transforms e.g. use the `look_at_transform` and then add a vertical translation.
> 
> Depending on what your use case is, shifting the mesh might not be the best solution (e.g. if the vertices need to be in the [-1, 1] range and you shift it out of this range).

Ok. I see.


Another question is:
```
lights = PointLights(device=device)
lights.location = torch.tensor([0.0, 0.0, +200.0], device=device)[None]
```
When I tried to move the point light to very far, I found there is no difference.

And I also want to know how to set the strengths of the light?

Thank you.

Hope there are some more detailed tutorials we can provide since I only get some ideas from the demo and codes in repo.

**Comment by Frank-Dz** [comment]
If it is possible to set the light rotating just like the camera which can be controlled by the viewing angle ```azim = torch.linspace(0, 360, batch_size)```?
