### ISSUE TITLE
How to do GraphConv in batches?

### ISSUE THREAD

**Issue by Agent-INF** [facebookresearch/pytorch3d#394]
Hey.
Thanks for the great project!

I'm trying to do graph convolution on batches of meshes, however, the docs of GraphConv.forward() says:
```
forward(self, verts, edges)
        Args:
            verts: FloatTensor of shape (V, input_dim) where V is the number of
                vertices and input_dim is the number of input features
                per vertex. input_dim has to match the input_dim specified
                in __init__.
            edges: LongTensor of shape (E, 2) where E is the number of edges
                where each edge has the indices of the two vertices which
                form the edge.

        Returns:
            out: FloatTensor of shape (V, output_dim) where output_dim is the
            number of output features per vertex.
```
My question is, how to efficiently process meshes that in batches, the Args are verts=[batch_size, V, input_dim] and edges=[batch_size, E, 2]. By the way, in my case, the meshes share the same topology, so the edges could be [1, E, 2] or just [E, 2].
Thanks a lot!

**Comment by nikhilaravi** [comment]
@Agent-INF all PyTorch3D operators are designed to support batched inputs! Have you looked at the [`Meshes` datastructure in PyTorch3D for batching meshes](https://github.com/facebookresearch/pytorch3d/blob/master/docs/notes/batching.md)? For GraphConv you want to use the `packed` representation of the batched meshes where the vertices and faces are vertically stacked to remove the batch dimension.  In your case you can simply reshape the verts and edges to: `verts = (B*V, input_dim)` and `edges = (B*E, 2)`however you need to be careful to offset the indices in the edges such that they refer to the correct vertices. 

A simpler way is to use the Meshes datastructure to initialize the mesh. Internally it will do all the bookkeeping and reshaping for you. 

```
# verts = (batch_size, V, input_dim)
# faces = (batch_size, F, 3)
meshes_batch = Meshes(verts=verts, faces=faces)
verts_packed = meshes_batch.verts_packed()  # (B*V, input_dim)
edges_packed = meshes_batch.edges_packed() # (B*E, 2)

# conv
conv = GraphConv(input_dim, output_dim)
y. = conv(verts_packed, edges_packed)
```

**Comment by Agent-INF** [comment]
Thanks for your quick reply, it is very helpful!
