### ISSUE TITLE
Antialiasing boundary

### ISSUE THREAD

**Issue by naoto0804** [facebookresearch/pytorch3d#399]
🐛 Bugs / Unexpected behaviors

```
<svg width="16" height="16" xmlns="http://www.w3.org/2000/svg">
  <path d="M 12 6 L 8 12 L 4 10 L 8 4" fill="black"/>
</svg>
```
I render a simple rectangle shown below by two faces in a very low-resolution image, and have a question on `blur_radius` parameter in `RasterizationSettings`. I want the rendered rectangle to look antialiased (like the leftmost figure below). However, in PyTorch3D, even I set `blur_radius > 0.0`, the result doesn't look like an antialiased (or blurred) one. Is there any way to do that?

(Please ignore lines around the image boundary, due to taking a screenshot in high resolution to see better.)

|Expected|blur_radius=0.0|blur_radius>0.0|
|---|---|---|
|![expected](https://user-images.githubusercontent.com/7067992/95674667-9b435280-0bec-11eb-9b29-97a35821891b.png)|![no_blur](https://user-images.githubusercontent.com/7067992/95674665-9aaabc00-0bec-11eb-94ee-80a6197ad895.png)|![w_blur](https://user-images.githubusercontent.com/7067992/95674664-98e0f880-0bec-11eb-9671-198805082244.png)|

## Instructions To Reproduce the Issue:

The code (let's say main.py) to reproduce
```
import torch
import numpy as np
from skimage.io import imread, imsave

from pytorch3d.structures import Meshes
# rendering components
from pytorch3d.renderer import (
    look_at_view_transform,
    FoVOrthographicCameras,
    PointLights,
    RasterizationSettings,
    MeshRenderer,
    MeshRasterizer,
    HardPhongShader,
    TexturesVertex,
    BlendParams
)

device = torch.device("cuda:0")

# Create two triangle meshes
vertices = torch.from_numpy(np.array([
    [0.5, 0.25, 0.0],
    [0.0, 0.5, 0.0],
    [-0.5, -0.25, 0.0],
    [0.0, -0.5, 0.0]
], dtype=np.float32))

faces = torch.from_numpy(np.array([
    [0, 1, 2],
    [0, 2, 3],
]))


verts_rgb = torch.zeros_like(vertices)[None]
textures = TexturesVertex(verts_features=verts_rgb.to(device))

# Construct mesh
mesh = Meshes(
    verts=[vertices.to(device)], faces=[faces.to(device)], textures=textures)

# Setup renderer
R, T = look_at_view_transform(2.0, 0, 0, device=device)
cameras = FoVOrthographicCameras(R=R, T=T, device=device)
lights = PointLights(
    device=device,
    location=[[0.0, 0.0, 3.0]],
    ambient_color=((1.0, 1.0, 1.0), ),
    diffuse_color=((0.0, 0.0, 0.0), ),
    specular_color=((0.0, 0.0, 0.0), )
)
raster_settings = RasterizationSettings(
    image_size=16,
    blur_radius=np.log(1. / 1e-4 - 1.) * 1e-4,
    # blur_radius=0.0
)

# blend_params = BlendParams(background_color=(0.,0.,0.), sigma=0.0, gamma=0.0)
blend_params = BlendParams()
renderer = MeshRenderer(
    rasterizer=MeshRasterizer(
        cameras=cameras,
        raster_settings=raster_settings
    ),
    shader=HardPhongShader(
        device=device,
        cameras=cameras,
        lights=lights,
        blend_params=blend_params
    )
)

# render image
images = renderer(mesh)
image = images.detach().cpu().numpy()[0][..., :3]
imsave('gap_between_meshes.png', (255 * image).astype(np.uint8))

```

2. The exact command(s) you ran:
PyTorch version: 0.2.5
```
$ python3 main.py
```

3. What you observed (including the full logs):
Discussed above.

**Comment by jcjohnson** [comment]
Thanks for the detailed explanation and reproducible code @naoto0804!

This is not a bug -- blur_radius isn't meant to be used for antialiasing; instead setting blur_radius>0 instructs the rasterizer to assign pixels *outside* of triangle boundaries to the triangle, up to the specified radius. This functionality is used to achieve differentiable rendering by having triangles become partially transparent outside their boundaries; to achieve this effect you'd have to use a `SoftPhongShader` instead of a `HardPhongShader`, and fiddle with the `sigma` and `gamma` values in `blend_params`.

However if you just want antialiased edges, the easiest way is to use supersampling antialiasing: render the image at a higher resolution than you actually want, then use average pooling to reduce back to your target resolution. This is easy to implement:

```python
import torch
import torch.nn.functional as F
import numpy as np
from skimage.io import imread, imsave

from pytorch3d.structures import Meshes
# rendering components
from pytorch3d.renderer import (
    look_at_view_transform,
    FoVOrthographicCameras,
    PointLights,
    RasterizationSettings,
    MeshRenderer,
    MeshRasterizer,
    HardPhongShader,
    TexturesVertex,
    BlendParams
)

device = torch.device("cpu")

# Create two triangle meshes
vertices = torch.from_numpy(np.array([
    [0.5, 0.25, 0.0],
    [0.0, 0.5, 0.0],
    [-0.5, -0.25, 0.0],
    [0.0, -0.5, 0.0]
], dtype=np.float32))

faces = torch.from_numpy(np.array([
    [0, 1, 2],
    [0, 2, 3],
]))


verts_rgb = torch.zeros_like(vertices)[None]
textures = TexturesVertex(verts_features=verts_rgb.to(device))

# Construct mesh
mesh = Meshes(
    verts=[vertices.to(device)], faces=[faces.to(device)], textures=textures)

# Use supersampling antialiasing
aa_factor = 3

# Setup renderer
R, T = look_at_view_transform(2.0, 0, 0, device=device)
cameras = FoVOrthographicCameras(R=R, T=T, device=device)
lights = PointLights(
    device=device,
    location=[[0.0, 0.0, 3.0]],
    ambient_color=((1.0, 1.0, 1.0), ),
    diffuse_color=((0.0, 0.0, 0.0), ),
    specular_color=((0.0, 0.0, 0.0), )
)
raster_settings = RasterizationSettings(
    image_size=16 * aa_factor,
)

# blend_params = BlendParams(background_color=(0.,0.,0.), sigma=0.0, gamma=0.0)
blend_params = BlendParams()
renderer = MeshRenderer(
    rasterizer=MeshRasterizer(
        cameras=cameras,
        raster_settings=raster_settings
    ),
    shader=HardPhongShader(
        device=device,
        cameras=cameras,
        lights=lights,
        blend_params=blend_params
    )
)

# render image
images = renderer(mesh)
images = images.permute(0, 3, 1, 2)  # NHWC -> NCHW
images = F.avg_pool2d(images, kernel_size=aa_factor, stride=aa_factor)
images = images.permute(0, 2, 3, 1)  # NCHW -> NHWC
print(images.shape, images.dtype)
image = images.detach().cpu().numpy()[0][..., :3]
imsave('aa3.png', (255 * image).astype(np.uint8))
```

Here are some results with `aa_factor` = 1, 2, and 3:
![image](https://user-images.githubusercontent.com/2718714/95803421-116bb600-0cce-11eb-819c-5ed7ee6a875c.png)
![image](https://user-images.githubusercontent.com/2718714/95803431-192b5a80-0cce-11eb-8fa6-6c951cb0b9b9.png)
![image](https://user-images.githubusercontent.com/2718714/95803444-221c2c00-0cce-11eb-9b18-0dad4ba9445b.png)

**Comment by naoto0804** [comment]
Wow, it makes sense, thank you for the explanation! I should've read the docs carefully;
