### ISSUE TITLE
Available for Windows ?

### ISSUE THREAD

**Issue by claireroman** [facebookresearch/pytorch3d#40]
Hi, 

We can remark that this package is only available for Linux and MacOS. Can we have a version for Windows ? Thank you for answering.

**Comment by nikhilaravi** [comment]
@claireroman thanks for raising this issue. Windows support is on our roadmap! Stay tuned!

**Comment by claireroman** [comment]
Great :) Thank you !

**Comment by WMF1997** [comment]
Hello, I manage to compile it on Windows 10 (1909 version). but failed. 

I use Microsoft Visual Studio 2019's MSVC compiler (19.00.24245), instead of GNU GCC >=4.9 compiler, to compile. And this is the only difference between my installation environment and recommended installation environment. 

finally, it raises errors like this. 
```
5 errors detected in the compilation of "C:/Users/wmf997/AppData/Local/Temp/tmpxft_00007924_00000000-10_rasterize_meshes.cpp1.ii".
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\bin\\nvcc.exe' failed with exit status 1
```
And I wonder what is the problem? 

yours sincerely, 
@wmf1997

**Comment by yuanluxu** [comment]
@WMF1997 Check and clone my fork and all MSVC build issues should be fixed. https://github.com/yuanluxu/pytorch3d

**Comment by nikhilaravi** [comment]
This will be fixed by #9. Thanks @yuanluxu for adding this.

**Comment by CorentinJ** [comment]
@yuanluxu Can you help me figure out why my build is failing? I followed your instructions [here](https://github.com/yuanluxu/pytorch3d/blob/master/INSTALL.md#2-install-from-a-local-clone).

[build_output.txt](https://github.com/facebookresearch/pytorch3d/files/4384371/build_output.txt)

**Comment by yuanluxu** [comment]
@CorentinJ, could check this issue https://github.com/pytorch/pytorch/issues/30886 and double check your VS version? It seems to be a similar error. This error is more related to pytorch instead of pytorch3d and very unclear what it actually complains about.

**Comment by CorentinJ** [comment]
But your instructions relate to a precompiled version of pytorch? I shouldn't have to compile pytorch myself, right?

Also, how do I to check my VS version?

**Comment by yuanluxu** [comment]
@CorentinJ , precompiled pytorch 1.4 + torchvision 0.5 should work. The error seems to come from compatibility of different VS version, as mentioned in the above issue. You can search "x64 native tools command prompt for VS 2019" and find your version information there. I would suggest to upgrade your VS to the latest version and re-compile. If this still does not work, please consider create an issue on pytorch.
