### ISSUE TITLE
softmax_rgb_blend V.S. sigmoid_alpha_blend

### ISSUE THREAD

**Issue by LuckyDC** [facebookresearch/pytorch3d#400]
The output of both SoftPhonShader and  SoftSilhouetteShader contains a alpha channel that indicate the silhouette.
The two shaders invoke softmax_rgb_blend and sigmoid_alpha_blend, respectively.
In the code, softmax_rgb_blend and sigmoid_alpha_blend differ in the implementation of alpha channel computation.
I wonder whether the two shaders lead to the same result when I use them to optimize model silhouette.

**Comment by nikhilaravi** [comment]
@LuckyDC they both compute the alpha channel using the same formula - the `sigmoid_alpha_blend` uses a CUDA implementation whereas the `softmax_rgb_blend` does the computation in PyTorch as we had been working on a CUDA implementation for this function as well. If you are concerned about having the same implementation you can create your own version of `softmax_rgb_blend` which uses the cuda function for computing alpha - simply replace line 182 in blending.py https://github.com/facebookresearch/pytorch3d/blob/f5383a7e5a79bd9e912af0fb0199c557b9987877/pytorch3d/renderer/blending.py#L182

with

```
alpha = _sigmoid_alpha(fragments.dists, fragments.pix_to_face, blend_params.sigma)
```

**Comment by nikhilaravi** [comment]
Closing this issue. If you still have questions, please reopen the issue!
