### ISSUE TITLE
How can I render images with multi-gpu?

### ISSUE THREAD

**Issue by lishang6257** [facebookresearch/pytorch3d#401]
When i try to render images by using multi-gpus, errors happened as follow:
1>RuntimeError: Caught RuntimeError in replica 0 on device 0.
2>RuntimeError: arguments are located on different GPUs at /opt/conda/conda-bld/pytorch_1579027003190/work/aten/src/THC/generic/THCTensorMathBlas.cu:540

The code which used for reproducing the issue is [here](https://github.com/lishang6257/issue-for-pytorch3d)

Hope for your replay!

**Comment by nikhilaravi** [comment]
@lishang6257 I get "Page Not Found" when trying to open the link. 

Please can you also provide information about how you have installed PyTorch3D (e.g. from conda or from cloning the GitHub repo). 

You should be able to render on another device by simply calling `renderer.to(device)` which should move all the internal tensors for rendering onto the desired `device`.

**Comment by lishang6257** [comment]
Sorrry for the invlid link, I have republished the link [here](https://github.com/lishang6257/issue-for-pytorch3d); The pytorch3d version I used is the master branch cloned from github. I have tried to use renderer.to(device) method,(https://github.com/lishang6257/issue-for-pytorch3d/blob/main/test.py#L98) but it cannot solve the problem. Hope for your replay.

**Comment by nikhilaravi** [comment]
@lishang6257 OK thanks for providing the code. What did you do to try and debug where the error is coming from? Are the textures also on the same device as the verts?

**Comment by lishang6257** [comment]
Thanks for your replay! The verts and the texs and verts are at the same device which be controlled by  `nn.DataParallel`. I comment the code block(https://github.com/lishang6257/issue-for-pytorch3d/blob/main/test.py#L104-L106) ,I find something  strange, the device for the render maynot change to the verts.device in some loops.
![image](https://user-images.githubusercontent.com/26080906/95941875-5994f080-0e14-11eb-8b1a-151e2a5294f9.png)

**Comment by nikhilaravi** [comment]
I was able to reproduce the error using your code. First note that you don't need to move the "tris" to verts.device. "tris" are a parameter of the module so `DataParallel` will move it to the correct device for you.  

There is another issue which is very related here: https://github.com/facebookresearch/pytorch3d/issues/213.

**Comment by lishang6257** [comment]
I haved read issue #213 before, and then i try to use DistributedDataParallel, but it also have the same problem if i define the meshrender in the __init__ function and change device with render.to(device) method in the forward processing, do you any idea for this?

**Comment by lishang6257** [comment]
Thanks for your patient replay. I have solved this issue by your advice. Thanks.
