### ISSUE TITLE
In render_colored_points.ipynb .vis - no Module named

### ISSUE THREAD

**Issue by albertotono** [facebookresearch/pytorch3d#403]
## 🐛 Bugs / Unexpected behavior

On the tutorial https://github.com/facebookresearch/pytorch3d/blob/master/docs/tutorials/render_colored_points.ipynb, now that the name has changed from "visualization' to 'vis' there is a `_ModuleNotFoundError: No module named 'pytorch3d.vis'_`

## Instructions To Reproduce the Issue:

<from pytorch3d.visualization import AxisArgs, plot_pointclouds>
```
<import os
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
from skimage.io import imread

import numpy as np

from pytorch3d.structures import Pointclouds
from pytorch3d.vis import AxisArgs, plot_pointclouds
from pytorch3d.renderer import (
    look_at_view_transform,
    FoVOrthographicCameras, 
    PointsRasterizationSettings,
    PointsRenderer,
    PointsRasterizer,
    AlphaCompositor,
    NormWeightedCompositor
)>
```
1. Any changes you made (`git diff`) or code you wrote 
I saw this commit https://github.com/facebookresearch/pytorch3d/commit/5d65a0cf8c9a1fb755fd09ce098bcedb0c670d80#diff-9ff2a09cd7b2a583e030b1aa0376b3ce7d8a39723e098e1b4e727487fd1bf279 so I changed to 

```
<from pytorch3d.visualization import AxisArgs, plot_pointclouds>
```
2. But still same error

```
<ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-445b2bac4bbb> in <module>()
     10 # Data structures and functions for rendering
     11 from pytorch3d.structures import Pointclouds
---> 12 from pytorch3d.visualization import AxisArgs, plot_pointclouds
     13 from pytorch3d.renderer import (
     14     look_at_view_transform,

ModuleNotFoundError: No module named 'pytorch3d.visualization'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.>
```

**Comment by nikhilaravi** [comment]
Are you running the tutorial after cloning the github repo or on Colab?

**Comment by albertotono** [comment]
I am installing from Google Colab, 
I run this before
`
!pip install torch torchvision
import sys
import torch
if torch.__version__=='1.6.0+cu101' and sys.platform.startswith('linux'):
    !pip install pytorch3d
else:
    !pip install 'git+https://github.com/facebookresearch/pytorch3d.git@stable'`

**Comment by nikhilaravi** [comment]
As explained in [this issue](https://github.com/facebookresearch/pytorch3d/issues/385#issuecomment-704485523), we have several experimental features in the master branch but not in the conda package - the `stable` tag references the commit which was used to build the conda package. If you want to use the code available in master you need to remove the `@stable` tag at the end of the pip install command.

**Comment by albertotono** [comment]
Thanks @nikhilaravi for the reference,

I followed your suggestion and I used this line 

`!pip install 'git+https://github.com/facebookresearch/pytorch3d.git'` instead of the usual 

'''
!pip install torch torchvision
import sys
import torch
if torch.__version__=='1.6.0+cu101' and sys.platform.startswith('linux'):
    !pip install pytorch3d
else:
    !pip install 'git+https://github.com/facebookresearch/pytorch3d.git@stable'
'''

it took around 7min

and then `Successfully built pytorch3d`

unfortunately I still have the same error 

`ModuleNotFoundError: No module named 'pytorch3d.vis'`

**Comment by DuaneNielsen** [comment]
Looking at 0.2.5, which as of today is the version currently in pypi

https://github.com/facebookresearch/pytorch3d/tree/v0.2.5/pytorch3d

v0.2.5 definately does not contain pytorch.vis

building from source using pip also didn't work for me

**Comment by nikhilaravi** [comment]
@DuaneNielsen @albertotono ok I will take a look at this and get back to you!

**Comment by bottler** [comment]
The change was from `pytorch3d.visualization` to `pytorch3d.vis`, not the other way around.

I think there's something strange about pip installing from github in to colab. Several times, I tried
```
!pip install 'git+https://github.com/facebookresearch/pytorch3d.git'
from pytorch3d.vis import AxisArgs, plot_pointclouds
```
in a blank colab notebook. It should work, and it usually did, but it did raise your error once, maybe due to a caching issue.

Can you maybe restart and try again?

**Comment by albertotono** [comment]
Thank you all, confirmed that restarting the runtime didn't work , but using a new notebook worked perfectly!  I am closing this issue. Thank you so much.
