### ISSUE TITLE
Can I fill black color if a triangle of obj file is facing backside?

### ISSUE THREAD

**Issue by okdalto** [facebookresearch/pytorch3d#404]
Hello, I noticed that the soft Phong shader fills texture color when the ambient color value is over zero even if a triangle of obj file is facing backside. 

Can I fill black color if a triangle of obj file is facing backside?

**Comment by nikhilaravi** [comment]
You can enable backface culling - `cull_backfaces` is an option in `raster_settings`. By default it is set to `False` so you will need to set it to `True` when initializing the rasterizer.

**Comment by okdalto** [comment]
Thank you so much! Have a nice day!
