### ISSUE TITLE
Axis-angle rotation representation

### ISSUE THREAD

**Issue by adizhol** [facebookresearch/pytorch3d#405]
## 🚀 Feature
Transformations from rotation matrices and axis-angle representation, and vice-versa.
https://en.wikipedia.org/wiki/Axis%E2%80%93angle_representation

This seems to be a useful representation in some recent papers.
I'm not sure I understand enough of the math to write the conversions myself...

**Comment by gkioxari** [comment]
I believe @bottler is going to land this soon, if it's not landed yet!

**Comment by bottler** [comment]
We now have functions `axis_angle_to_matrix` and `matrix_to_axis_angle`. They will be in the next release or you can install from github. https://github.com/facebookresearch/pytorch3d/commit/c93c4dd7b2b68db92997f65e11d7b08acecce891
