### ISSUE TITLE
Render a point_cloud from a set of points sampled from meshes ['NoneType' object has no attribute 'permute']

### ISSUE THREAD

**Issue by albertotono** [facebookresearch/pytorch3d#408]
## ❓ Questions on how to use PyTorch3D

I was playing around with t[his tutorial ](https://github.com/facebookresearch/pytorch3d/blob/master/docs/tutorials/render_colored_points.ipynb) **Render_colored_points.** 

In my case I would like to render initially white or black points, not from a point_cloud but from a set of points sampled from a mesh. After that I would like to classify those points to identify individual parts and then used these colored masks for the part recognition. 

Specifically 

```
trg_obj = "/file location of the mesh in .obj format"
verts, faces, aux = load_obj(trg_obj)
faces_idx = faces.verts_idx.to(device)
verts = verts.to(device)
```
then I do 

```
trg_mesh = Meshes(verts=[verts], faces=[faces_idx])
**points = sample_points_from_meshes(trg_mesh, 5000)**
point_cloud = Pointclouds(points=points, features=None)
```
Not that I have my point_cloud I created the Renderer and when I try to visualize

```
images = renderer(point_cloud)
plt.figure(figsize=(10, 10))
plt.imshow(images[0, ..., :3].cpu().numpy())
plt.grid("off")
plt.axis("off");
```
Then I am receiving this error 

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-27-04e35948d5f4> in <module>
----> 1 images = renderer(point_cloud)
      2 plt.figure(figsize=(10, 10))
      3 plt.imshow(images[0, ..., :3].cpu().numpy())
      4 plt.grid("off")
      5 plt.axis("off");

~/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    720             result = self._slow_forward(*input, **kwargs)
    721         else:
--> 722             result = self.forward(*input, **kwargs)
    723         for hook in itertools.chain(
    724                 _global_forward_hooks.values(),

~/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/pytorch3d/renderer/points/renderer.py in forward(self, point_clouds, **kwargs)
     48             fragments.idx.long().permute(0, 3, 1, 2),
     49             weights,
---> 50             point_clouds.features_packed().permute(1, 0),
     51             **kwargs
     52         )

AttributeError: 'NoneType' object has no attribute 'permute'
```

I tried  passing rgb value in this way 

```
rgb = torch.ones_like(verts)[None]
point_cloud = Pointclouds(points=[points], features=[rgb])
# 
# or point_cloud = Pointclouds(points=points, features=[rgb])
```
but I got 

```
Clouds in list must be of shape Px3 or empty
or 
A cloud has mismatched numbers of points and inputs
```

Any help would be much appreciated.

PS: Nice presentation @gkioxari today https://www.youtube.com/watch?v=gXLpy3jd2mQ&feature=youtu.be and thank you for sharing that.

**Comment by nikhilaravi** [comment]
@albertotono - as you correctly identified, the `NoneType` error is because the `features` were set to `None` when you initialized the  `Pointclouds` object. The first dimension of the `features` must be the same as the `points`, and they must both be in either `list` or `tensor` representation i.e. `point_cloud = Pointclouds(points=points, features=[rgb])` will not work as one is a `list` and the other is a `tensor`. 

From your example above, it looks like `points` is of shape `(5000, 3)` as you are sampling these points . The `features` also need to also have the same first dimension (i.e. ``(5000, C)` where C can be 3 for RGB colors). 

Instead you can try something like this:
```
trg_mesh = Meshes(verts=[verts], faces=[faces_idx])
points = sample_points_from_meshes(trg_mesh, 5000)
features = torch.ones_like(points)
point_cloud = Pointclouds(points=points, features=features)
```

**Comment by albertotono** [comment]
Thanks @nikhilaravi for the quick reply, it solved my problem perfectly, thanks for the kind explaination. While I am able to visualize the points with matplotlib

```
%matplotlib inline
fig = plt.figure(figsize=(5, 5))
ax = Axes3D(fig)
ax.scatter3D(x, z, -y)
ax.view_init(160, 45)
#plt.grid("off");
plt.axis("off");
plt.show()

```
![image](https://user-images.githubusercontent.com/72926609/96900714-405cf700-1447-11eb-9600-734f800a2946.png)


I am having hard time with Pytorch3D renderer both 

```
R, T = look_at_view_transform(20, 10, 0)
cameras = FoVOrthographicCameras(device=device, R=R, T=T, znear=0.01)

raster_settings = PointsRasterizationSettings(
    image_size=512, 
    radius = 0.003,
    points_per_pixel = 10
)

renderer = PointsRenderer(
    rasterizer=PointsRasterizer(cameras=cameras, raster_settings=raster_settings),
    compositor=AlphaCompositor()
)
images = renderer(point_cloud)
plt.figure(figsize=(5, 5))
plt.imshow(images[0, ..., :3].cpu().numpy())
plt.grid("off")
plt.axis("off");

```
and 

```
renderer = PointsRenderer(
    rasterizer=PointsRasterizer(cameras=cameras, raster_settings=raster_settings),
    compositor=AlphaCompositor(background_color=(0, 0, 1))
)
images = renderer(point_cloud)
plt.figure(figsize=(5, 5))
plt.imshow(images[0, ..., :3].cpu().numpy())
plt.grid("off")
plt.axis("off");
```
gives me this image below

![image](https://user-images.githubusercontent.com/72926609/96901303-f0326480-1447-11eb-8d7e-77efcac52ae8.png)

even if I tried to change the color of the points to all zeros. 

`features = torch.zeros_like(points)`

but at the end, I saw that you also introduced plot_scene from .vis 
and this works well for interactive navigation, and it is awesome. 

```
plot_scene({
    "Pointcloud": {
        "person": point_cloud
    }
})
```
![Screenshot from 2020-10-22 09-39-09](https://user-images.githubusercontent.com/11828200/96903260-764faa80-144a-11eb-92e8-8eeadb803aac.png)

but when I run the other notebook I am having this 

![image](https://user-images.githubusercontent.com/11828200/96903455-ba42af80-144a-11eb-98c8-1d1508387331.png)

I went ahead and recreate from scratch. 

[Test Render PointCloud.zip](https://github.com/facebookresearch/pytorch3d/files/5424256/Test.Render.PointCloud.zip)

I was checking 
PointsRenderer??
PointsRasterizationSettings??
It seems that there is no lights for them. 

But while they displayed correctly here, 

![image](https://user-images.githubusercontent.com/11828200/96904411-ef033680-144b-11eb-87fe-ba395bc93f3a.png)

I am not sure why they don't in my example. Also the background doesn't change. 

Since it solved me previous problem, I will close this issue. 

Any further suggestions will be much appreciated.

**Comment by albertotono** [comment]
I played around with that. it was due to the camera position. I modify the `distance` from camera to object, and not I can see it.

**Comment by albertotono** [comment]
Problem solved. 

![image](https://user-images.githubusercontent.com/11828200/97018795-6a282380-1504-11eb-8026-cd00e88ec72c.png)
I scaled the mesh

```
verts, faces, aux = load_obj(trg_obj)
faces_idx = faces.verts_idx.to(device)
verts = verts.to(device)
center = verts.mean(0)
verts = verts - center
scale = max(verts.abs().max(0)[0])
verts = verts / scale
verts_rgb = torch.ones_like(verts)[None]  # (1, V, 3)  ones_like to create white "texture" all vertices white
textures = TexturesVertex(verts_features=verts_rgb.to(device))
chair_mesh = Meshes(verts=[verts], faces=[faces_idx], textures=textures )
```
Sampled
```
points = sample_points_from_meshes(chair_mesh, 5000)
features = torch.ones_like(points)
point_cloud = Pointclouds(points=points, features=features)
```

and rendered 
```

dist = 3 
elev = 5.0   
azim = 180.0 

R, T = look_at_view_transform(dist, elev, azim, device=device)
cameras = FoVOrthographicCameras(device=device, R=R, T=T, znear=0.01)

raster_settings = PointsRasterizationSettings(
    image_size=512, 
    radius = 0.003,
    points_per_pixel = 10
)

renderer = PointsRenderer(
    rasterizer=PointsRasterizer(cameras=cameras, raster_settings=raster_settings),
    compositor=AlphaCompositor()
)
image = renderer(point_cloud)
plt.figure(figsize=(5, 5))
plt.imshow(image[0].cpu().numpy())
plt.grid("off")
plt.axis("off");
```

**Comment by alexalex12345678-gffh** [comment]
Hi! I need help! Please help me! 

Error:
# ComfyUI Error Report
## Error Details
- **Node ID:** 51
- **Node Type:** ImageCASharpening+
- **Exception Type:** AttributeError
- **Exception Message:** 'NoneType' object has no attribute 'permute'
## Stack Trace
```
  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)


  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    

  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)

  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
      

  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_essentials\image.py", line 808, in execute
    img = F.pad(image.permute([0,3,1,2]), pad=(1, 1, 1, 1))
