### ISSUE TITLE
Fit Mesh sample fails in Colab due to missing mesh

### ISSUE THREAD

**Issue by REscanDon** [facebookresearch/pytorch3d#41]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## Instructions To Reproduce the Issue:

1. Browse to [Fit Mesh tutorial](https://pytorch3d.org/tutorials/deform_source_mesh_to_target_mesh)
1. Click on the "Open in Colab" button
1. Manually add a cell to import pytorch3d per instructions [here](https://pytorch3d.org/tutorials/) and [here](https://github.com/facebookresearch/pytorch3d/issues/28)
```
!pip install torch torchvision
!pip install 'git+https://github.com/facebookresearch/pytorch3d.git'
```
1. Step through the cells in the tutorial

EXPECTED RESULT

Tutorial completes without error

ACTUAL RESULT

The 2nd cell under "Load an OBJ file ..." throws an error:

```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-7-a2f61d370091> in <module>()
----> 1 verts, faces, aux = load_obj(trg_obj)
      2 
      3 # verts is a FloatTensor of shape (V, 3) where V is the number of vertices in the mesh
      4 # faces is an object which contains the following LongTensors: verts_idx, normals_idx and textures_idx
      5 # For this tutorial, normals and textures are ignored.

1 frames
/usr/local/lib/python3.6/dist-packages/pytorch3d/io/obj_io.py in _open_file(f)
     82     if isinstance(f, str):
     83         new_f = True
---> 84         f = open(f, "r")
     85     elif isinstance(f, pathlib.Path):
     86         new_f = True

FileNotFoundError: [Errno 2] No such file or directory: './data/doplhin/10014_dolphin_v2_max2011_it2.obj'
```

Please include the following (depending on what the issue is):

1. Any changes you made (`git diff`) or code you wrote
```
<put diff or code here>
```
2. The exact command(s) you ran:
3. What you observed (including the full logs):
```
<put logs here>
```

Please also simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

**Comment by nikhilaravi** [comment]
@REscanDon you will need to follow the instructions in the tutorial to download the dolphin obj:

<img width="884" alt="Screen Shot 2020-02-10 at 9 06 55 AM" src="https://user-images.githubusercontent.com/5912647/74172270-cb150300-4be4-11ea-858d-85e4b2302730.png">

```
download https://free3d.com/3d-model/-dolphin-v1--12175.html and save in ./data/dolphin
```
Then upload it to the google drive folder where you have the notebook. 

<img width="340" alt="Screen Shot 2020-02-10 at 9 06 35 AM" src="https://user-images.githubusercontent.com/5912647/74172290-d0724d80-4be4-11ea-9ca6-5d7498a6d99c.png">

**Comment by REscanDon** [comment]
May I recommend adding those steps to the tutorial instructions rather than to a bug that's presumably about to be closed? I'm sure I'm not the only person trying to work through the tutorials who doesn't know how to download data into a colab notebook.

**Comment by nikhilaravi** [comment]
@REscanDon sure we can update the tutorial with instructions on how to do this. Thanks for flagging this.

**Comment by nikhilaravi** [comment]
@REscanDon the tutorial has now been updated with a `wget` command to retrieve the necessary data. You can just run this notebook cell and do not need to do anything manually.
