### ISSUE TITLE
## ❓ How to render an object with serveral types materials export from file?

### ISSUE THREAD

**Issue by ZhaoJinHA** [facebookresearch/pytorch3d#411]
## ❓ How to render an object with serveral types materials export from file?

I want to render a model from Blender into a the following result:

![00008](https://user-images.githubusercontent.com/28822074/97084144-8aacc680-1647-11eb-989a-01ee753682e1.png)
this .obj contains no texture.

I explored some issures discussing the similar thing.However, the Texture class is descreped. 
I just wonder if there is any simplest way to do this task for now? Thand you!

**Comment by ZhaoJinHA** [comment]
Updating:
I write a function to get the material of every verts:
`def get_verts_material_idx(objname):
    f_obj = open(objname, 'r')
    lines = [line.strip() for line in f_obj]
    f_obj.close()
    verts_material_idx = []
    v_n_list = []
    mtl_list = []
    v_n = 0
    # startswith expects each line to be a string. If the file is read in as
    # bytes then first decode to strings.
    if lines and isinstance(lines[0], bytes):
        lines = [el.decode("utf-8") for el in lines]

    for line in lines:
        if line.startswith("v "):
            # Line is a vertex.
            v_n += 1
        elif len(line.split()) != 0 and line.split()[0] == "usemtl":
            material_name = line.split()[1]
            # materials are often repeated for different parts
            # of a mesh.
            v_n_list.append(v_n)
            v_n = 0
            mtl_list.append(material_name)
    for v_n, mtl in zip(v_n_list, mtl_list):
        verts_material_idx.extend([mtl] * v_n)
    return verts_material_idx`
with this function, I can assign every verts with its materia from the exported obj and mtl file.
then the mesh can be created like:
`DATA_DIR = "../obj_export"
obj_filename = os.path.join(DATA_DIR, "*.obj")
mesh_ori = load_objs_as_meshes([obj_filename], device=device)
verts_padded = mesh_ori.verts_padded()
faces_padded = mesh_ori.faces_padded()
_, _, aux = load_obj(obj_filename, load_textures=True)
mtl_list = aux.material_colors
verts_material_idx = get_verts_material_idx(obj_filename)
verts_rgb = torch.ones_like(verts_padded, device=device)
for i, idx in enumerate(verts_material_idx):
    verts_rgb[0, i, :] = mtl_list[idx]['diffuse_color']
print(verts_rgb)
textures = TexturesVertex(verts_features=verts_rgb)
mesh = Meshes(verts=verts_padded, faces=faces_padded, textures=textures)`
![Screenshot from 2020-10-25 16-24-10](https://user-images.githubusercontent.com/28822074/97102202-95666a80-16de-11eb-9ec4-96e343220c82.png)
But I still wonder is there any simpler way?

**Comment by ZhaoJinHA** [comment]
Updating:
I write a function to get the material of every verts:
`def get_verts_material_idx(objname):
    f_obj = open(objname, 'r')
    lines = [line.strip() for line in f_obj]
    f_obj.close()
    verts_material_idx = []
    v_n_list = []
    mtl_list = []
    v_n = 0
    # startswith expects each line to be a string. If the file is read in as
    # bytes then first decode to strings.
    if lines and isinstance(lines[0], bytes):
        lines = [el.decode("utf-8") for el in lines]

    for line in lines:
        if line.startswith("v "):
            # Line is a vertex.
            v_n += 1
        elif len(line.split()) != 0 and line.split()[0] == "usemtl":
            material_name = line.split()[1]
            # materials are often repeated for different parts
            # of a mesh.
            v_n_list.append(v_n)
            v_n = 0
            mtl_list.append(material_name)
    for v_n, mtl in zip(v_n_list, mtl_list):
        verts_material_idx.extend([mtl] * v_n)
    return verts_material_idx`

with this function, I can assign every verts with its materia from the exported obj and mtl file.
then the mesh can be created like:
DATA_DIR = "../obj_export" obj_filename = os.path.join(DATA_DIR, "*.obj") mesh_ori = load_objs_as_meshes([obj_filename], device=device) verts_padded = mesh_ori.verts_padded() faces_padded = mesh_ori.faces_padded() _, _, aux = load_obj(obj_filename, load_textures=True) mtl_list = aux.material_colors verts_material_idx = get_verts_material_idx(obj_filename) verts_rgb = torch.ones_like(verts_padded, device=device) for i, idx in enumerate(verts_material_idx): verts_rgb[0, i, :] = mtl_list[idx]['diffuse_color'] print(verts_rgb) textures = TexturesVertex(verts_features=verts_rgb) mesh = Meshes(verts=verts_padded, faces=faces_padded, textures=textures)
Screenshot from 2020-10-25 16-24-10
But I still wonder is there any simpler way?

**Comment by ZhaoJinHA** [comment]
Updating:
I write a function to get every vert's material:
`def get_verts_material_idx(objname):
    f_obj = open(objname, 'r')
    lines = [line.strip() for line in f_obj]
    f_obj.close()
    verts_material_idx = []
    v_n_list = []
    mtl_list = []
    v_n = 0
    if lines and isinstance(lines[0], bytes):
        lines = [el.decode("utf-8") for el in lines]

    for line in lines:
        if line.startswith("v "):
            v_n += 1
        elif len(line.split()) != 0 and line.split()[0] == "usemtl":
            material_name = line.split()[1]
            v_n_list.append(v_n)
            v_n = 0
            mtl_list.append(material_name)
    for v_n, mtl in zip(v_n_list, mtl_list):
        verts_material_idx.extend([mtl] * v_n)
    return verts_material_idx`

By this function, I can assign every verts with the material from the obj file. The the mesh can be create like this:
`DATA_DIR = "../obj_export"
obj_filename = os.path.join(DATA_DIR, "tongji_framework_design_model_fine_subdivide_base.obj")
mesh_ori = load_objs_as_meshes([obj_filename], device=device)
verts_padded = mesh_ori.verts_padded()
faces_padded = mesh_ori.faces_padded()
_, _, aux = load_obj(obj_filename, load_textures=True)
mtl_list = aux.material_colors
verts_material_idx = get_verts_material_idx(obj_filename)
verts_rgb = torch.ones_like(verts_padded, device=device)
for i, idx in enumerate(verts_material_idx):
    verts_rgb[0, i, :] = mtl_list[idx]['diffuse_color']
print(verts_rgb)
textures = TexturesVertex(verts_features=verts_rgb)
mesh = Meshes(verts=verts_padded, faces=faces_padded, textures=textures)`

And the render result is:
![Screenshot from 2020-10-25 16-24-10](https://user-images.githubusercontent.com/28822074/97102335-7916fd80-16df-11eb-83dc-2150a5302817.png)

But I still wonder is this the right way to do the task?

**Comment by ZhaoJinHA** [comment]
Updating:
I write a function to get every vert's material:
`def get_verts_material_idx(objname):
    f_obj = open(objname, 'r')
    lines = [line.strip() for line in f_obj]
    f_obj.close()
    verts_material_idx = []
    v_n_list = []
    mtl_list = []
    v_n = 0
    if lines and isinstance(lines[0], bytes):
        lines = [el.decode("utf-8") for el in lines]

    for line in lines:
        if line.startswith("v "):
            v_n += 1
        elif len(line.split()) != 0 and line.split()[0] == "usemtl":
            material_name = line.split()[1]
            v_n_list.append(v_n)
            v_n = 0
            mtl_list.append(material_name)
    for v_n, mtl in zip(v_n_list, mtl_list):
        verts_material_idx.extend([mtl] * v_n)
    return verts_material_idx`
By this function, I can assign every verts with the material from the obj file. The the mesh can be create like this:
`if torch.cuda.is_available():
    device = torch.device("cuda:0")
    torch.cuda.set_device(device)
else:
    device = torch.device("cpu")
DATA_DIR = "../obj_export"
obj_filename = os.path.join(DATA_DIR, "tongji_framework_design_model_fine_subdivide_base.obj")
mesh_ori = load_objs_as_meshes([obj_filename], device=device)
verts_padded = mesh_ori.verts_padded()
faces_padded = mesh_ori.faces_padded()
_, _, aux = load_obj(obj_filename, load_textures=True)
mtl_list = aux.material_colors
verts_material_idx = get_verts_material_idx(obj_filename)
verts_rgb = torch.ones_like(verts_padded, device=device)
for i, idx in enumerate(verts_material_idx):
    verts_rgb[0, i, :] = mtl_list[idx]['diffuse_color']
textures = TexturesVertex(verts_features=verts_rgb)
mesh = Meshes(verts=verts_padded, faces=faces_padded, textures=textures)
verts = verts_padded[0, ...]
center = verts.mean(0)
scale = max((verts - center).abs().max(0)[0])
mesh.offset_verts_(-center.expand(N, 3))
mesh.scale_verts_((1.0 / float(scale)))`

And the render result is:
![Uploading Screenshot from 2020-10-25 16-24-10.png…]()


But I still wonder is this the right way to do the task?

**Comment by ZhaoJinHA** [comment]
Updating:
I write a function to get every vert's material:
![Screenshot from 2020-10-25 16-35-26](https://user-images.githubusercontent.com/28822074/97104036-7b7f5480-16eb-11eb-9207-17ae82402cd2.png)

By this function, I can assign every verts with the material from the obj file. The the mesh can be create like this:
![Screenshot from 2020-10-25 17-56-36](https://user-images.githubusercontent.com/28822074/97104042-85a15300-16eb-11eb-96cf-44f0f8a61998.png)

And the render result is:
![Screenshot from 2020-10-25 16-24-10](https://user-images.githubusercontent.com/28822074/97104044-8afe9d80-16eb-11eb-9311-fbff2305e3e5.png)

But I still wonder is this the right way to do the task?

**Comment by nikhilaravi** [comment]
You can get the material index for each faces from https://github.com/facebookresearch/pytorch3d/blob/2084160b16131c2e35c74ced2466d3965cc32591/pytorch3d/io/obj_io.py#L152-L159. 

Then as you know the vertices for each of the faces you can get the material index for each vertex. So you don't need to define your own function for getting the vertex material index. 

An alternative option is to set `create_texture_atlas=True` in the call to `load_obj`. This will create a per face texture map of shape (N, F, R, R) where R is a texture resolution you can define with the flag e.g. `texture_atlas_size=4`. 

This will set the color of each face to the diffuse color of the material. 

e.g.
```
verts, faces, aux = load_obj(mesh_path, load_textures=True, create_texture_atlas=True, texture_atlas_size=4)
mesh = Meshes(
    verts=[verts],
    faces=[faces.verts_idx],
    textures=TexturesAtlas(atlas=[aux.texture_atlas]),
)
```

You can render this in the same with as any other type of texture and you don't have to change anything in the renderer.

**Comment by ZhaoJinHA** [comment]
> You can get the material index for each faces from
> 
> https://github.com/facebookresearch/pytorch3d/blob/2084160b16131c2e35c74ced2466d3965cc32591/pytorch3d/io/obj_io.py#L152-L159
> 
> .
> Then as you know the vertices for each of the faces you can get the material index for each vertex. So you don't need to define your own function for getting the vertex material index.
> 
> An alternative option is to set `create_texture_atlas=True` in the call to `load_obj`. This will create a per face texture map of shape (N, F, R, R) where R is a texture resolution you can define with the flag e.g. `texture_atlas_size=4`.
> 
> This will set the color of each face to the diffuse color of the material.
> 
> e.g.
> 
> ```
> verts, faces, aux = load_obj(mesh_path, load_textures=True, create_texture_atlas=True, texture_atlas_size=4)
> mesh = Meshes(
>     verts=[verts],
>     faces=[faces.verts_idx],
>     textures=TexturesAtlas(atlas=[aux.texture_atlas]),
> )
> ```
> 
> You can render this in the same with as any other type of texture and you don't have to change anything in the renderer.

Thank you very much for you detailed answer! Both of them are better choice for me.
