### ISSUE TITLE
Is the renderer only works with vertex feature vector in the range [0,1]?

### ISSUE THREAD

**Issue by Yumin-Sun-00** [facebookresearch/pytorch3d#415]
The color is in the range [0,1]

does the renderer only works with vertex feature vector in the range [0,1]?

**Comment by gkioxari** [comment]
If your vertex feature is a RGB color then yes, it should be within [0, 1] and a float, as per rgb conventions.

You can render any feature vector of any dimensionality (not just C=3 as in the case of RGB) and any value range.
