### ISSUE TITLE
Can I render 9 channels image?

### ISSUE THREAD

**Issue by Yumin-Sun-00** [facebookresearch/pytorch3d#419]
I want to have a shadeless shader that can render arbitrary channels. If I have 3 channels images as target, I could simply use the HardGouraudShader with ambient color 1.0,1.0,1.0 and other materials parameters to be (0.0,0.0,0.0). But for more than 3 channels, the shape is not matched anymore. Could I get an advice? Also, is there a way to render a non-square image?

If you have to ask the reason why I do this, because the image is not RGB at all, just some custome feature maps stacked together.

**Comment by gkioxari** [comment]
You can render textures of any dimensions, not just RGB. Our textures and samplers work for arbitrary C-dimensional features (C=3 for RGB). 

The shaders implemented in PyTorch3D like Phong and Gouraud are example cases and do indeed assume RGB textures as their definition is very specific. See their wiki entries ([gouraud](https://en.wikipedia.org/wiki/Gouraud_shading), [phong](https://en.wikipedia.org/wiki/Phong_shading)). You will need to write your own shader that is tailored to whatever you are doing, and you can use the existing shader implementation as guides. Note that the intended use in PyTorch3D is for users to write their own shaders which are specific for the task they are tackling, and that is why we worked hard to make the library modular and flexible. 

Regarding, non square rasterization, this feature will be added soon!

**Comment by Yumin-Sun-00** [comment]
> You can render textures of any dimensions, not just RGB. Our textures and samplers work for arbitrary C-dimensional features (C=3 for RGB).
> 
> The shaders implemented in PyTorch3D like Phong and Gouraud are example cases and do indeed assume RGB textures as their definition is very specific. See their wiki entries ([gouraud](https://en.wikipedia.org/wiki/Gouraud_shading), [phong](https://en.wikipedia.org/wiki/Phong_shading)). You will need to write your own shader that is tailored to whatever you are doing, and you can use the existing shader implementation as guides. Note that the intended use in PyTorch3D is for users to write their own shaders which are specific for the task they are tackling, and that is why we worked hard to make the library modular and flexible.
> 
> Regarding, non square rasterization, this feature will be added soon!

Thank you, that is exactly how I do it now.
