### ISSUE TITLE
How to use it with cuda11 and rtx3090?

### ISSUE THREAD

**Issue by jiang25262** [facebookresearch/pytorch3d#421]

**Comment by albertotono** [comment]
What messages are you receiving during the installation?

**Comment by jiang25262** [comment]
> What messages are you receiving during the installation?

I can install it and python can run 'import pytorch3d', but it can't run 'from pytorch3d.structures import Meshes'.

**Comment by albertotono** [comment]
Do you mind copy here the message that you received?

**Comment by jiang25262** [comment]
> Do you mind copy here the message that you received?

Now I only have my laptop with me. I'll show it to you in a few hours.

**Comment by jiang25262** [comment]
Python 3.8.6 (default, Oct  6 2020, 03:22:36) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

 from pytorch3d.structures import Meshes
>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jiang/.local/lib/python3.8/site-packages/pytorch3d/structures/__init__.py", line 4, in <module>
    from .pointclouds import Pointclouds
  File "/home/jiang/.local/lib/python3.8/site-packages/pytorch3d/structures/pointclouds.py", line 5, in <module>
    from .. import ops
  File "/home/jiang/.local/lib/python3.8/site-packages/pytorch3d/ops/__init__.py", line 5, in <module>
    from .graph_conv import GraphConv
  File "/home/jiang/.local/lib/python3.8/site-packages/pytorch3d/ops/graph_conv.py", line 8, in <module>
    from pytorch3d import _C
ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory

**Comment by jiang25262** [comment]
> Do you mind copy here the message that you received?

Python 3.8.6 (default, Oct  6 2020, 03:22:36) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
 from pytorch3d.structures import Meshes
>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jiang/.local/lib/python3.8/site-packages/pytorch3d/structures/__init__.py", line 4, in <module>
    from .pointclouds import Pointclouds
  File "/home/jiang/.local/lib/python3.8/site-packages/pytorch3d/structures/pointclouds.py", line 5, in <module>
    from .. import ops
  File "/home/jiang/.local/lib/python3.8/site-packages/pytorch3d/ops/__init__.py", line 5, in <module>
    from .graph_conv import GraphConv
  File "/home/jiang/.local/lib/python3.8/site-packages/pytorch3d/ops/graph_conv.py", line 8, in <module>
    from pytorch3d import _C
ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory

**Comment by albertotono** [comment]
I don't think it is a problem of 3090 GPU. Did you follow the instructions on how to install pytorch3D? https://github.com/facebookresearch/pytorch3d/blob/master/INSTALL.md?

**Comment by jiang25262** [comment]
> I don't think it is a problem of 3090 GPU. Did you follow the instructions on how to install pytorch3D? https://github.com/facebookresearch/pytorch3d/blob/master/INSTALL.md?
Can Pytorch1.7 (CUDA11) only be installed with Conda? I install it with pip.

**Comment by jiang25262** [comment]
> I don't think it is a problem of 3090 GPU. Did you follow the instructions on how to install pytorch3D? https://github.com/facebookresearch/pytorch3d/blob/master/INSTALL.md?

Can Pytorch1.7 (CUDA11) only be installed with Conda? I install it with pip.

**Comment by albertotono** [comment]
Yes. You can install pytorch1.7 with conda. But you should ask this question on the pytorch github page. ;-)

**Comment by bottler** [comment]
With cuda 11, you have to use pytorch 1.7, as I think you know. The latest release of pytorch3d was earlier than pytorch 1.7. Unless you want to build pytorch3d from source, you need to use the nightly build of pytorch3d (which does have a builds with pytorch 1.7 and cuda 11). I recommend you start again in a new conda environment, to avoid much confusion.

```
conda create -n pytorch3d_new python=3.8
conda activate pytorch3d_new
conda install -c pytorch pytorch=1.7.0 torchvision cudatoolkit=11.0
conda install -c conda-forge -c fvcore fvcore
conda install -c pytorch3d-nightly pytorch3d
```

**Comment by jiang25262** [comment]
> Yes. You can install pytorch1.7 with conda. But you should ask this question on the pytorch github page. ;-)

Thanks！

**Comment by jiang25262** [comment]
> With cuda 11, you have to use pytorch 1.7, as I think you know. The latest release of pytorch3d was earlier than pytorch 1.7. Unless you want to build pytorch3d from source, you need to use the nightly build of pytorch3d (which does have a builds with pytorch 1.7 and cuda 11). I recommend you start again in a new conda environment, to avoid much confusion.
> 
> ```
> conda create -n pytorch3d_new python=3.8
> conda activate pytorch3d_new
> conda install -c pytorch pytorch=1.7.0 torchvision cudatoolkit=11.0
> conda install -c conda-forge -c fvcore fvcore
> conda install -c pytorch3d-nightly pytorch3d
> ```

Thanks！

**Comment by cczarnocki** [comment]
Okay tried these exact steps and am still getting an issue installing pytorch3d with a CUDA 11 and an RTX3090. 
Here is my conda list: 
![Screenshot from 2021-05-04 14-12-41](https://user-images.githubusercontent.com/36641909/117070648-e3d67080-ace2-11eb-9b52-839f399ba016.png)
And error I get on the last step:
![Screenshot from 2021-05-04 14-13-04](https://user-images.githubusercontent.com/36641909/117070667-efc23280-ace2-11eb-8d10-da4673b3cfed.png)

Any help would be greatly appreciated. Thanks!

**Comment by bottler** [comment]
@cczarnocki In future, please err on the side of opening a new issue whenever you have a new problem.
There are instructions in this thread which are out of date.

You don't have the prerequisites of PyTorch3D installed. Most significantly, you don't have iopath. This wasn't a requirement until fairly recently.
If you set up a new environment with PyTorch1.7.0 and cudatoolkit 11.0 in the way described in Install.md you should then be able to install the nightly build of PyTorch3D.
If not, please open a new issue and give all the details.

**Comment by OOF-dura** [comment]
> @cczarnocki In future, please err on the side of opening a new issue whenever you have a new problem.
> There are instructions in this thread which are out of date.
> 
> You don't have the prerequisites of PyTorch3D installed. Most significantly, you don't have iopath. This wasn't a requirement until fairly recently.
> If you set up a new environment with PyTorch1.7.0 and cudatoolkit 11.0 in the way described in Install.md you should then be able to install the nightly build of PyTorch3D.
> If not, please open a new issue and give all the details.

Error:
```
Collecting package metadata (current_repodata.json): done                                                                                                                     Solving environment: failed with initial frozen solve. Retrying with flexible solve.                                                                                          Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.                                                                   Collecting package metadata (repodata.json): done                                                                                                                             Solving environment: failed with initial frozen solve. Retrying with flexible solve.                                                                                          Solving environment: -                                                                                                                                                        Found conflicts! Looking for incompatible packages.                                                                                                                           This can take several minutes.  Press CTRL-C to abort.                                                                                                                        failed                                                                                                                                                                                                                                                                                                                                                      UnsatisfiableError: The following specifications were found to be incompatible with each other:                                                                                                                                                                                                                                                             Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:                                                                                                                                                                                                                         - feature:/linux-64::__glibc==2.31=0                                                                                                                                          - feature:|@/linux-64::__glibc==2.31=0                                                                                                                                                                                                                                                                                                                    Your installed version is: 2.31          
```
```

**Comment by bottler** [comment]
@OOF-dura If you are still experiencing that error and want some help please open a new issue with the details.
