### ISSUE TITLE
Is it possible to deform base mesh to ground truth mesh given some other input list?

### ISSUE THREAD

**Issue by evanvlane** [facebookresearch/pytorch3d#428]
Hi all,
Thanks for a fantastic library!

I'm trying to understand how to use pytorch3d for my application.

I have a list of 96 scalar values representing sensor readings that correspond to deformations of a physical surface.

I have meshed scans of that deformed surface to act as a ground truth set, as well as a mesh of the rest state.

I would like to use pytorch3d to learn a network that will output a deformed mesh or something I can use to deform the rest state mesh to the deformed state.

I'm not sure how to proceed though. I'm new to pytorch3d and would love some pointers as to how to best structure this problem. 

Thanks!

**Comment by gkioxari** [comment]
Hi @evanvlane 
Have you taken a look at the PyTorch3D tutorials. Especially this tutorial might be useful for your use case:

https://github.com/facebookresearch/pytorch3d/blob/master/docs/tutorials/deform_source_mesh_to_target_mesh.ipynb
