### ISSUE TITLE
Support for .gltf/glb file formats

### ISSUE THREAD

**Issue by markstrefford** [facebookresearch/pytorch3d#429]
## 🚀 Feature

.gltf/glb formats are becoming widely supported, for example in AR and 3D graphics renderers such as three.js. Currently I don't see support for this format in the documentation or code. 

## Motivation

Being able to manipulate and/or generate objects in this format will open up a wider range of use-cases and compatible libraries. It is possible to use .obj/.mtl with three.js etc. but .gltf can often simplify the process.

**Comment by gkioxari** [comment]
This feature request is actually in our roadmap!

**Comment by albertotono** [comment]
Is the roadmap public?

**Comment by gkioxari** [comment]
@albertotono 
Great point! I don't think we have an official roadmap released but I will chat with the team to see if we should start doing releasing that.

**Comment by noufalsalim** [comment]
any updates on this?
