### ISSUE TITLE
DataSet

### ISSUE THREAD

**Issue by csverma610** [facebookresearch/pytorch3d#43]
Hello,

Is it possible to provide the dataset used in the examples? I think, the dolphine
data is not available in the data folder.

Thanks.

**Comment by nikhilaravi** [comment]
@csverma610 please follow the instructions in the tutorials for downloading the dolphin data: 

<img width="884" alt="Screen Shot 2020-02-10 at 9 06 55 AM" src="https://user-images.githubusercontent.com/5912647/74183480-dfafc600-4bf9-11ea-9c35-6838ecb7148e.png">
