### ISSUE TITLE
Issue with pytorch3d.vis - module not found in python

### ISSUE THREAD

**Issue by pankaja0285** [facebookresearch/pytorch3d#430]
@nikhilaravi - I followed the steps in [https://github.com/facebookresearch/pytorch3d/blob/master/docs/tutorials/render_colored_points.ipynb](url)
1. I installed the pytorch3d 
2. When I am importing pytorch3d.vis 
`from pytorch3d.vis.plotly_vis import AxisArgs, plot_batch_individually, plot_scene`

I get this error
_<ipython-input-59-6317e731193a> in <module>
      2 from pytorch3d.structures import Pointclouds
      3 #from pytorch3d.vis import AxisArgs, plot_pointclouds
----> 4 from pytorch3d.vis.plotly_vis import AxisArgs, plot_batch_individually, plot_scene
      5 from pytorch3d.renderer import (
      6     look_at_view_transform,

ModuleNotFoundError: No module named 'pytorch3d.vis'_
 
In addition for import of PulsarPointsRenderer, I get error for this as well
----> 5 from pytorch3d.renderer import (
      6     look_at_view_transform,
      7     FoVOrthographicCameras,

ImportError: cannot import name 'PulsarPointsRenderer'

The reason I am am following the link mentioned above is because my source is a pointcloud - **.pcd** file. Please advise. 

NOTE: I am trying this in Azure ml workspace.

**Comment by albertotono** [comment]
How did you install pytorch3D? There are other similar issues closed here, did you see those?!

**Comment by pankaja0285** [comment]
Yes I did, I even copied the install instructions from https://github.com/facebookresearch/pytorch3d/issues/403
And still the same. I am as I said working in Azure ML workspace for my project.

**Comment by bottler** [comment]
It's best if you can use the tutorial from the stable tag, which corresponds to the latest release of pytorch3d, which is probably what you have installed. It is at https://github.com/facebookresearch/pytorch3d/blob/stable/docs/tutorials/render_colored_points.ipynb .
Then you will have your build and your notebook in sync with each other.

We have made some changes on the main/master branch since the release, which includes adding `pytorch3d.vis` and `PulsarPointsRenderer`. These new features are already demonstrated in that notebook. This is all preparation for a future release. Temporarily it is slightly difficult to build the main branch.

**Comment by pankaja0285** [comment]
@bottler 
I did follow that notebook and I have two issues, with the pytorch3d.vis and PulsarPointsRenderer
hence I was looking at the closed issue github link and trying that install of pytorch3d

  Please read the steps I took to arrive here. 

@nikhilaravi  
Also I am having issues in the Create Renderer block, none of the plt lines are working I get the
error --  Invalid shape (512, 512, 1) for image data

---> 12 plt.imshow(images[0, ..., :3].cpu().numpy())
     13 plt.grid("off")
     14 plt.axis("off")

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/matplotlib/pyplot.py in imshow(X, cmap, norm, aspect, interpolation, alpha, vmin, vmax, origin, extent, shape, filternorm, filterrad, imlim, resample, url, data, **kwargs)
   2649         filternorm=filternorm, filterrad=filterrad, imlim=imlim,
   2650         resample=resample, url=url, **({"data": data} if data is not
-> 2651         None else {}), **kwargs)
   2652     sci(__ret)
   2653     return __ret

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/matplotlib/__init__.py in inner(ax, data, *args, **kwargs)
   1563     def inner(ax, *args, data=None, **kwargs):
   1564         if data is None:
-> 1565             return func(ax, *map(sanitize_sequence, args), **kwargs)
   1566 
   1567         bound = new_sig.bind(ax, *args, **kwargs)

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/matplotlib/cbook/deprecation.py in wrapper(*args, **kwargs)
    356                 f"%(removal)s.  If any parameter follows {name!r}, they "
    357                 f"should be pass as keyword, not positionally.")
--> 358         return func(*args, **kwargs)
    359 
    360     return wrapper

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/matplotlib/cbook/deprecation.py in wrapper(*args, **kwargs)
    356                 f"%(removal)s.  If any parameter follows {name!r}, they "
    357                 f"should be pass as keyword, not positionally.")
--> 358         return func(*args, **kwargs)
    359 
    360     return wrapper

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/matplotlib/axes/_axes.py in imshow(self, X, cmap, norm, aspect, interpolation, alpha, vmin, vmax, origin, extent, shape, filternorm, filterrad, imlim, resample, url, **kwargs)
   5613                               resample=resample, **kwargs)
   5614 
-> 5615         im.set_data(X)
   5616         im.set_alpha(alpha)
   5617         if im.get_clip_path() is None:

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/matplotlib/image.py in set_data(self, A)
    697                 or self._A.ndim == 3 and self._A.shape[-1] in [3, 4]):
    698             raise TypeError("Invalid shape {} for image data"
--> 699                             .format(self._A.shape))
    700 
    701         if self._A.ndim == 3:

TypeError: Invalid shape (512, 512, 1) for image data

@nikhilaravi please look into this. I have to do a benchmark by at least getting through this tutorial once successfully.

**Comment by bottler** [comment]
As I mentioned in my previous comment, the instructions in #403 are (temporarily) no longer correct. In particular the master branch will not install cleanly from pip.

I see a contradiction between your first comment and your latest comment. In your first comment you suggest you were looking at  https://github.com/facebookresearch/pytorch3d/blob/master/docs/tutorials/render_colored_points.ipynb , whereas in your latest comment you suggest you had already been following https://github.com/facebookresearch/pytorch3d/blob/stable/docs/tutorials/render_colored_points.ipynb (which I mentioned above). Note the difference between `master` and `stable` in the urls. The latter does not mention pytorch3d.vis or PulsarPointsRenderer, so I think it might be worth checking again. You should not hit any problems with pytorch3d.vis or PulsarPointsRenderer because you should not have code importing them. 

With regard to the invalid shape problem, can you share your code / an example. In particular, what are you passing in as the `features` value when you create the Pointclouds? How many channels? If `images[0, ..., :3].cpu().numpy()` is producing something of shape `(512,512,1)` it looks like maybe you only have one channel. Maybe instead you could do something like `plt.imshow(images[0, ..., 0].cpu().numpy(), cmap='gray')` so that you pass shape `(512,512)` instead.

**Comment by pankaja0285** [comment]
@bottler  thanks for getting back to me. 
1. I was able to re-install according to what you said from [https://github.com/facebookresearch/pytorch3d/blob/stable/docs/tutorials/render_colored_points.ipynb ](url)
  - so I went past
2. But the issue with 512,512 - error still occurs. 
Due to sensitivity of data I can't give you the entire code but will give the gist
 - a) I read from a pcd file 
`from pyntcloud.io import read_pcd
pointcloud = read_pcd(filename)
print('pointcloud',pointcloud) 
#which gives me 
#pointcloud {'points':               x         y         z         c
#0     -0.588727 -0.532933  1.233257  0.142857
#[36413 rows x 4 columns]
`
 Then I convert to vertices and rgb as
`points_xyz = pointcloud["points"][["x","y","z"]].values
points_rgb = pointcloud["points"][["c"]].values
verts = torch.Tensor(points_xyz).to(device)
        
rgb = torch.Tensor(points_rgb).to(device)
point_cloud = Pointclouds(points=[verts], features=[rgb])`

And when I print point_cloud, I get
<pytorch3d.structures.pointclouds.Pointclouds at 0x7f8ab9ddefd0>

So, then after that I do, as per the tutorial -->

`# Initialize a camera.
R, T = look_at_view_transform(20, 10, 0)
cameras = FoVOrthographicCameras(device=device, R=R, T=T, znear=0.01)

# Define the settings for rasterization and shading. Here we set the output image to be of size
# 512x512. As we are rendering images for visualization purposes only we will set faces_per_pixel=1
# and blur_radius=0.0. Refer to raster_points.py for explanations of these parameters. 
raster_settings = PointsRasterizationSettings(
    image_size=512, 
    radius = 0.003,
    points_per_pixel = 10
)


# Create a points renderer by compositing points using an alpha compositor (nearer points
# are weighted more heavily). See [1] for an explanation.
renderer = PointsRenderer(
    rasterizer=PointsRasterizer(cameras=cameras, raster_settings=raster_settings),
    compositor=AlphaCompositor()
)`
--this runs fine
`images = renderer(point_cloud)
images.shape`
outputs as 
torch.Size([1, 512, 512, 1])

Then as per tutorial if I use 
`images = renderer(point_cloud)
plt.figure(figsize=(10, 10))
plt.imshow(images[0, ..., :3].cpu().numpy())
plt.grid("off")
plt.axis("off");`
I get error --> TypeError: Invalid shape (512, 512, 1) for image data

so if I do as you suggested which is 
`plt.figure(figsize=(10, 10))
plt.imshow(images[0, ..., 0].cpu().numpy(), cmap='gray')

plt.grid("off")
plt.axis("off")`

I get the output as
(-0.5, 511.5, 511.5, -0.5)
I don't see any image.

Same thing happens for the next block of plt as well, after doing the weighted compositing.

Please advise.

**Comment by bottler** [comment]
I know nothing about Azure ML workspace. Is it just like a jupyter notbook? How might it be different? I wonder if your problem here could just be a question of how Azure ML interacts with matplotlib, for which this is the wrong place to ask. Do you need `%matplotlib inline`?

What do you see when you plot a simple graph with `plt`? 

Can you send a screenshot of what you see when you don't see an image, and what you see from a simple plot?

**Comment by pankaja0285** [comment]
1. In our project all out pointcloud images (.pcd s) are a from a **google Tango** camera - all these images are sensitive data so I cannot attach the image file here. I read the data with PyntCloud and extract the xyz, rgb separately and assemble the verts and create the point_cloud that your tutorial needs.
2. Attaching the screenshots of the pointcloud and its shape.
3. Then next I do create the renderer as per the tutorial
4. Next when I run the plt I get error if I use  plt.imshow(images[0, ..., :3].cpu().numpy(), cmap='gray'), so you suggested to do this instead plt.imshow(images[0, ..., 0].cpu().numpy(), cmap='gray') and the last file in the attachment is what I see - no image.
<img width="425" alt="pointcloud_data" src="https://user-images.githubusercontent.com/54913075/98704168-5543f080-234a-11eb-9a4d-84c4352410cd.PNG">
<img width="402" alt="points_dtls" src="https://user-images.githubusercontent.com/54913075/98704186-59700e00-234a-11eb-9af4-b4804464142a.PNG">
<img width="402" alt="plt_image_no_image" src="https://user-images.githubusercontent.com/54913075/98704191-5bd26800-234a-11eb-8e84-287a8f96a0ed.PNG">

**Comment by bottler** [comment]
I suspect your problem now is not with pytorch3d. You need to ensure matplotlib is working, and I gave some suggestions in my previous comment.

**Comment by pankaja0285** [comment]
I do see other plots for e.g. when I do with matplotlib with a regular **rgb** image file.
I have attached a file which I plotted with matplotlib.pyplot  imshow - pasting here
<img width="227" alt="pltimage_normal" src="https://user-images.githubusercontent.com/54913075/98707130-ad302680-234d-11eb-885b-db0fa7861b90.PNG">

**Comment by bottler** [comment]
Is that screenshot of an imshow from the same notebook where the other imshow is not showing?

Can you compare the data types you are calling imshow with.

No, if imshow is not showing anything when you send it an array, that doesn't sound like a pytorch3d problem.

**Comment by pankaja0285** [comment]
Yes its from the same notebook, I added just for testing, the imshow of one of our .jpg file ...
Do you think the camera settings, renderer - something is amiss?

**Comment by nikhilaravi** [comment]
@pankaja0285 yes the shape of the output image should be `[batch_size, H, W, C]` where C is the feature dimension you are using for the points. 

Were you able to resolve your matlab issues?

**Comment by nikhilaravi** [comment]
Closing this issue as there have been no further questions. Feel free to reopen it if needed.
