### ISSUE TITLE
PyTorch 1.7 now supports `ccbin` argument for nvcc

### ISSUE THREAD

**Issue by cdeepali** [facebookresearch/pytorch3d#436]
PyTorch v1.7.0 added support to pass `ccbin` to `nvcc` in commit https://github.com/pytorch/pytorch/commit/4134b7abfa60a659de27736704c62277ecf291d2.

So I think now we can remove code to do the same at - https://github.com/facebookresearch/pytorch3d/blob/master/setup.py#L53

**Comment by bottler** [comment]
At the moment we are still trying to support pytorch back to version 1.4, so we can't rely on this new feature. But thanks for letting us know - we hope to change the comment to mention that 1.7 has an easier way.
