### ISSUE TITLE
error: identifier "atomicAdd_block" is undefined

### ISSUE THREAD

**Issue by cdeepali** [facebookresearch/pytorch3d#437]
I want to build PyTorch3d from source with CUDA 10.2. 
However I am not sure which CUB version to choose from, I tried the latest CUB version but I am seeing errors like:

`error: identifier "atomicAdd_block" is undefined`

Could someone point me to the correct CUB version for CUDA 10.2.

**Comment by cdeepali** [comment]
I tried with cub commit - https://github.com/NVlabs/cub/tree/d106ddb991a56c3df1b6d51b2409e36ba8181ce4 as well. 
But I continue to see the build error:

```
<mypath>/pytorch3d/pytorch3d/csrc/pulsar/cuda/../include/./renderer.render.device.h(178): error: identifier "atomicAdd_block" is undefined

<mypath>/pytorch3d/pytorch3d/csrc/pulsar/cuda/../include/./renderer.render.device.h(281): error: identifier "atomicAdd_block" is undefined
```

**Comment by bottler** [comment]
Everything should be all right on the stable tag / the released version.

On the main/master branch, we are right now working on fixing the build in various ways, including to deal with this issue. 
The short answer is to change the first line of 
```
#if (CUDART_VERSION >= 10000)
#define ATOMICADD_B(PTR, VAL) atomicAdd_block((PTR), (VAL))
#else
#define ATOMICADD_B(PTR, VAL) ATOMICADD(PTR, VAL)
#endif
```
which is around line 190 of `pytorch3d/csrc/pulsar/cuda/commands.h`, to
```
#if (CUDART_VERSION >= 10000) && (__CUDA_ARCH__ >= 600)
```

The latest CUB version (1.10.0) is fine, but if you are using CUDA 11.0 and you want to use the new pulsar point rendering part of the library you need to be careful to ensure that it overrides the CUB which is inbuilt into the cudatoolkit. Soon we will make this easier, so best to wait.

**Comment by cdeepali** [comment]
Thanks @bottler. I tried with` v0.2.5` and it built fine.
