### ISSUE TITLE
Incorrect command - conda install -c cub

### ISSUE THREAD

**Issue by cdeepali** [facebookresearch/pytorch3d#438]
In the last part of the section https://github.com/facebookresearch/pytorch3d/blob/master/INSTALL.md#core-library the command `conda install -c cub` is observed.

**Comment by bottler** [comment]
Correct. As I mentioned in #437 we are currently fixing the build on the main/master branch, and that includes fixing problems with the documentation in various places. It seems like this particular thing isn't holding you up because you have downloaded cub separately as mentioned in that issue.

**Comment by cdeepali** [comment]
Yes, it is not blocking me. Thanks @bottler.

**Comment by jperaire** [comment]
@bottler the 
`curl -O https://github.com/NVIDIA/cub/archive/1.10.0.tar.gz
tar xzf 1.10.0.tar.gz
export CUB_HOME=$PWD/cub-1.10.0`

Block doesn't work. (In particular - the second line outputs:

`gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now`

**Comment by bottler** [comment]
Sorry. At least on some systems it needs to be `curl -LO https://github.com/NVIDIA/cub/archive/1.10.0.tar.gz` . The extra option lets curl follow redirects.
