### ISSUE TITLE
Wrong renderer result.

### ISSUE THREAD

**Issue by JobAtom** [facebookresearch/pytorch3d#439]
When I render a square with defined faces. 

![image](https://user-images.githubusercontent.com/10276145/98678308-505a5d80-2399-11eb-8ae6-3fc4ebabe47c.png)

I set my renderer as follows. 

```
raster_settings = RasterizationSettings(
            image_size=self.image_size,
            blur_radius=0.0,
            faces_per_pixel=self.resolution,
            #perspective_correct=True,
        )


        self.lights = PointLights(device=self.device)
        blend_params = BlendParams(background_color=(1.0, 0.0, 0.0))
        self.renderer = MeshRenderer(
            rasterizer=MeshRasterizer(
                cameras=self.cameras,
                raster_settings=raster_settings
            ),
            shader=SoftPhongShader(device=self.device, cameras=self.cameras, lights=self.lights, blend_params=blend_params)
        )
```
The result seems wrong with some missing pixel(blue colored as black ground color).  
![image](https://user-images.githubusercontent.com/10276145/98677604-310f0080-2398-11eb-8b1b-ec3da11a1bf3.png)

**Comment by gkioxari** [comment]
It's because the pixels on the black lines intersect the edges of your faces. You should increase your `blur_radius` and they will go away.

**Comment by nikhilaravi** [comment]
@JobAtom there are several prior issues which explain this too: https://github.com/facebookresearch/pytorch3d/issues/355, https://github.com/facebookresearch/pytorch3d/issues/399
