### ISSUE TITLE
How to fast calculate the vertice curvature of mesh

### ISSUE THREAD

**Issue by lith0613** [facebookresearch/pytorch3d#445]
## ❓ Questions on how to use PyTorch3D

I want to calculate the vertice curvature of mesh fastly, is there a function doing this in Pytorch3d ?

**Comment by gkioxari** [comment]
You are not providing much information about what exactly you want to compute.

**Comment by lith0613** [comment]
> You are not providing much information about what exactly you want to compute.

I just want to calculate the mean curvature of a mesh surface. I could not found a pytorch API function in the pytorch3d, can you show me how to do that ? I have found a python function in pymesh as follows:
```
import trimesh
mesh = trimesh.Trimesh(vertices=verts, faces=tris)
mean_curv = trimesh.curvature.discrete_mean_curvature_measure(mesh, verts.tolist(), 0.01)
```
But this function is too slow to do this, is there any API function in pytorch3d ?

**Comment by gkioxari** [comment]
We don't have a function that computes directly what you want. Our focus in PyTorch3D is mostly on operators that would be useful for learning and optimization (and thus also admit gradients). However, we have some functionality that might be relevant. In particular, [mesh_laplacian_smoothing.py](https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/loss/mesh_laplacian_smoothing.py#L127-L141) we compute the laplacian with cotangents to capture curvature. 

https://github.com/facebookresearch/pytorch3d/blob/ddb0b1b6528b7b0e90b0ccb68e612755463bf1f6/pytorch3d/loss/mesh_laplacian_smoothing.py#L127-L141

**Comment by lith0613** [comment]
> We don't have a function that computes directly what you want. Our focus in PyTorch3D is mostly on operators that would be useful for learning and optimization (and thus also admit gradients). However, we have some functionality that might be relevant. In particular, [mesh_laplacian_smoothing.py](https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/loss/mesh_laplacian_smoothing.py#L127-L141) we compute the laplacian with cotangents to capture curvature.
> 
> https://github.com/facebookresearch/pytorch3d/blob/ddb0b1b6528b7b0e90b0ccb68e612755463bf1f6/pytorch3d/loss/mesh_laplacian_smoothing.py#L127-L141

Thanks for your great help ! Can you share me more clearly ? how to get the mean curvature with the Laplacian cotangent weights ? Appreciate you !

**Comment by gkioxari** [comment]
Unfortunately, I have not spent enough time to study what you need and give you step by step instructions. However, it should be rather simple to implement if you understand what it is you need to compute. 

I am closing this for now, as it's not related to an issue/bug in the codebase.

**Comment by JianqiangDing** [comment]
@gkioxari Hi，

If I am not mistaken, It seems that the code does not fill diagonal entries of the resulting Laplacian matrix? 
Did I miss something? check the following link for your reference.
[Laplacian matrix (triangle mesh)](http://rodolphe-vaillant.fr/?e=101)

**Comment by gahahaaA** [comment]
> > 您没有提供有关要计算的确切内容的太多信息。
> 
> 我只想计算网格表面的平均[曲率](https://en.wikipedia.org/wiki/Mean_curvature)。我在 pytorch3d 中找不到 pytorch API 函数，你能告诉我如何做到这一点吗？我在pymesh中找到了一个python函数，如下所示：
> 
> ```
> import trimesh
> mesh = trimesh.Trimesh(vertices=verts, faces=tris)
> mean_curv = trimesh.curvature.discrete_mean_curvature_measure(mesh, verts.tolist(), 0.01)
> ```
> 
> 但是这个函数太慢了，做不到，pytorch3d有没有API函数？

Do you find a fast method to calculate the vertice curvature of mesh ？
