### ISSUE TITLE
ShapeNet load_textures to False

### ISSUE THREAD

**Issue by Flegyas** [facebookresearch/pytorch3d#450]
## 🐛 Bugs / Unexpected behaviors
There's a little bug in the `_load_mesh` method in [shapenet_base.py](https://github.com/facebookresearch/pytorch3d/blob/ddb0b1b6528b7b0e90b0ccb68e612755463bf1f6/pytorch3d/datasets/shapenet_base.py#L88).
## Instructions To Reproduce the Issue:
1. Set the field `load_textures` to `False` 

The code tries to return the value of `textures` before it is assigned (since it happens only when the field is enabled) resulting in a `UnboundLocalError: local variable 'textures' referenced before assignment`.

It should be initialized in advance or not returned at all when the field is disabled.

**Comment by albertotono** [comment]
@Flegyas , I had a similar problem here https://github.com/facebookresearch/pytorch3d/issues/444

**Comment by Flegyas** [comment]
I'm so sorry for the duplicate! I searched before opening the issue and I saw yours, but I thought it wasn't related to mine. 
I should've read the last part too!
