### ISSUE TITLE
Multiple gpu data split

### ISSUE THREAD

**Issue by zshyang** [facebookresearch/pytorch3d#453]
Hi, 

Thanks for providing this powerful tool for 3D deep learning.

I tried to use this package on multiple GPUs. For the collate function of the dataset, I pass a Mesh structure. It seems that the nn.parallel module does not split Mesh with size 4 into Mesh with size 2 and 2 on a 2 GPU machine. 

Could you help me with how to make this split happening?

Best!

**Comment by nikhilaravi** [comment]
You could load the `verts` and `faces` as batched tensors e.g of shape `verts.shape = (B, V, 3)` and `faces.shape = (B, F, 3)` and then construct the `Meshes object` on each GPU.

**Comment by zshyang** [comment]
Thanks!
