### ISSUE TITLE
Does PyTorch3D support half precision through apex?

### ISSUE THREAD

**Issue by BrknKybrd** [facebookresearch/pytorch3d#454]
Good day everyone,

I am trying to use pytorch3d together with pytorch_lighting and apex and 16 bit training. In a naive try, I am getting an error from 
pytorch3d/renderer/mesh/rasterize_meshes that _C.rasterize_meshes expected Float but got Half.

So, before I dive into this issue myself, I would like to ask whether pytorch3d should be able / should not be able to support half precision calculations, and whether this even would be a good idea.

Best regards

**Comment by bottler** [comment]
This is similar to the question of amp in issue #297. We don't support half precision at the moment.
