### ISSUE TITLE
For the graph convolution.

### ISSUE THREAD

**Issue by zshyang** [facebookresearch/pytorch3d#455]
When the edge has shape [0, 2] as input to the graph Conv layer, currently, it gives an error. Because nothing to be gathered.
But theoretically, the layer should give an output just like an FC layer.

**Comment by gkioxari** [comment]
So you have a mesh that's merely a collection of vertices. So not really a mesh. In that case, the notion of graph convolution is not defined. Merely making it into an FC layer in that case will be problematic because weights `w1` will have no gradients and PyTorch will complain.

**Comment by zshyang** [comment]
Hi gkioxari, thanks for the reply. Here is the case. I am using some vertices pooling layer in my model and some vertices will be removed. In this case, I could no longer guarantee that the graph is a mesh and some vertex may no longer have neighbors. 
I agree with you that we could no longer call it to mesh and apply graph conv to it.

**Comment by gkioxari** [comment]
In that case, you need to do a workaround. I can see two solutions if a mesh is no longer a mesh (called here non-mesh mesh):
* For the non-mesh mesh, you don't call graph conv but a different layer that you have implemented that is using the weights of the graph conv layer (assuming you want to share the computation across all meshes), i.e. `w0` or `w1` depending on what you want to do, or
* For the verts of the non-mesh mesh, you create dummy edges which are loops, i.e. (v0, v0) for each v0 in non-mesh mesh, and call graph conv. This basically is equivalent to a FC layer with weight `w0 + w1`.

**Comment by zshyang** [comment]
Thanks! I think these two should solve the problem.
