### ISSUE TITLE
Type hint not fully correct

### ISSUE THREAD

**Issue by AndresCasado** [facebookresearch/pytorch3d#456]
https://github.com/facebookresearch/pytorch3d/blob/fc7a4cacc36ecf2b8feb996bdfb1203dee5d836b/pytorch3d/renderer/lighting.py#L227

This type hint makes the IDE think that it needs a `str` object only, when a `pytorch.device` object is valid too

**Comment by gkioxari** [comment]
Yes that's true! We can fix it but I don't believe it should be causing any issues when using it.

**Comment by AndresCasado** [comment]
Yes, it works perfectly fine. It's just a minor detail when using an IDE like PyCharm.

**Comment by nikhilaravi** [comment]
@AndresCasado, thanks I noticed it in a few other places as well. We will fix it!

**Comment by patricklabatut** [comment]
Proper type hints and handling of devices (as either `str` or `torch.device`) have just been introduced on the master branch across the codebase ([example](https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/renderer/lighting.py#L162)). So closing this issue as fixed, thanks for reporting it!
