### ISSUE TITLE
Issue with Pulsar for n_points > 512

### ISSUE THREAD

**Issue by nkolot** [facebookresearch/pytorch3d#457]
The GPU version of Pulsar produces incorrect results when I render more than 512 points.

## Instructions To Reproduce the Issue:

I was experimenting with pulsar and I've been using the example code provided [here](https://github.com/facebookresearch/pytorch3d/blob/master/docs/examples/pulsar_basic.py).
In this particular example, I tried to modify the `n_points` variable to render a different number of points. This can be done in [Line 28](https://github.com/facebookresearch/pytorch3d/blob/fc7a4cacc36ecf2b8feb996bdfb1203dee5d836b/docs/examples/pulsar_basic.py#L28).
For `n_points <= 512` the rendered image looks as expected. However for `n_points > 512` the results are not correct. This error seems to appear only when I run it on the GPU. The CPU results are ok.

`n_points = 512`
![126015026_134835251385645_4431024899022237248_n](https://user-images.githubusercontent.com/31786013/99837318-12ff8800-2b70-11eb-8b31-3c00c9b69bf5.png)
`n_points = 513`
![126303961_3369385319796692_4148760630183677205_n](https://user-images.githubusercontent.com/31786013/99837341-1eeb4a00-2b70-11eb-9c19-18d2ee17746f.png)

System details:
OS: Ubuntu 18.04.3
GPU: Tesla V100 16GB, Driver version: 440.100, CUDA version: 10.2
PyTorch version: 1.7.0
PyTorch3D version: 0.3.0

**Comment by gkioxari** [comment]
Tagging @classner until we can properly assign issues to him.

**Comment by classner** [comment]
Hi @nkolot ,

Thanks for reporting! Did you use a pre-built wheel of PyTorch3D or did you build it yourself? In case you built it yourself, what was the CUB version you used? We have been observing a couple of issues related to problematic CUB versions...

**Comment by classner** [comment]
I can not reproduce with a self-built version. :-/ We need to find out more about your specific system configuration.

**Comment by classner** [comment]
This is my output for 2550 points on the GPU, which is what is expected.

![basic](https://user-images.githubusercontent.com/731387/99861792-5516d280-2b4c-11eb-8bea-b9c7923437da.png)

**Comment by nkolot** [comment]
Hi Christoph,
Thanks for looking into it!

So, I built pytorch3d from source.
The CUB version I used is 1.10.0.

**Comment by nkolot** [comment]
I also tried to install the prebuilt binaries you provide in a clean conda environment. In this case it works fine.

**Comment by classner** [comment]
Very interesting! The CUB and CUDA version is fine; I used CUDA 10.2 and CUB 1.10.0 for a working build. So there must be a flaky part in the build process we don't yet understand. @nkolot, could you please provide us with your host compiler and its version?

@bottler, do you have a hunch what this could be? I think this is the same problem we faced with the native build on CircleCI.

**Comment by nkolot** [comment]
I am using gcc (version 7.5.0). The nvcc version is 10.1 (V10.1.243).

**Comment by classner** [comment]
Any idea whether this could be connected to the gcc version, @bottler?

**Comment by bottler** [comment]
We know that when we build on plain Ubuntu 16.04, which has GCC 4.9, with cuda 10.2, we have problems with the output. I think our release builds are done with GCC 7.3.1 and we often also use GCC 7.4 internally and I think they both work. If you have an issue with 7.5 that would be different to the problem we know about.

**Comment by gkioxari** [comment]
Closing this as it seems to have been resolved. Feel free to open if more discussion is needed.
