### ISSUE TITLE
Unable to install using Conda

### ISSUE THREAD

**Issue by AZadora** [facebookresearch/pytorch3d#461]
I am trying to install PyTorch3D using the following command:
`conda install -c pytorch3d pytorch3d`

I have PyTorch 1.7.0 with Cuda 11.0 installed and the latest NVIDIA driver for my graphics card.

However, I am getting the following error:
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your CUDA driver:

  - feature:/linux-64::__cuda==11.0=0
  - feature:|@/linux-64::__cuda==11.0=0

Your installed CUDA driver is: 11.0

If I install PyTorch3D from git it's successfully installed but I receive Runtime errors like "PyTorch3D was built without GPU support".

Here is the complete output of
`conda list`:

Package                       Version
----------------------------- -------------------
addict                        2.3.0
argon2-cffi                   20.1.0
astroid                       2.4.2
async-generator               1.10
attrs                         20.2.0
backcall                      0.2.0
backports.functools-lru-cache 1.6.1
bleach                        3.2.1
certifi                       2020.11.8
cffi                          1.14.3
cycler                        0.10.0
decorator                     4.4.2
defusedxml                    0.6.0
entrypoints                   0.3
fvcore                        0.1.2.post20201030
igl                           2.2.1
importlib-metadata            2.0.0
install                       1.3.4
ipydatawidgets                4.1.0
ipykernel                     5.3.4
ipython                       7.18.1
ipython-genutils              0.2.0
ipywidgets                    7.5.1
isort                         5.6.4
jedi                          0.17.2
Jinja2                        2.11.2
joblib                        0.17.0
jsonschema                    3.2.0
jupyter-client                6.1.7
jupyter-core                  4.6.3
jupyterlab-pygments           0.1.2
kiwisolver                    1.3.0
lazy-object-proxy             1.4.3
MarkupSafe                    1.1.1
matplotlib                    3.3.2
mccabe                        0.6.1
meshplot                      0.3.3
mistune                       0.8.4
mkl-fft                       1.2.0
mkl-random                    1.1.1
mkl-service                   2.3.0
nbclient                      0.5.1
nbconvert                     6.0.7
nbformat                      5.0.8
nest-asyncio                  1.4.1
networkx                      2.5
notebook                      6.1.4
numpy                         1.19.1
olefile                       0.46
open3d                        0.11.0
opencv-python                 4.4.0.44
openpyscad                    0.4.0
packaging                     20.4
pandas                        1.1.3
pandocfilters                 1.4.2
parso                         0.7.1
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        8.0.0
pip                           20.2.4
plyfile                       0.7.2
portalocker                   1.7.0
POT                           0.7.0
prometheus-client             0.8.0
prompt-toolkit                3.0.8
ptyprocess                    0.6.0
pycparser                     2.20
pyembree                      0.1.6
pyglet                        1.5.8
Pygments                      2.7.1
pylint                        2.6.0
pyparsing                     2.4.7
pyrsistent                    0.17.3
python-dateutil               2.8.1
pythreejs                     2.2.1
pytorch3d                     0.3.0
pytz                          2020.1
PyYAML                        5.3.1
pyzmq                         19.0.2
rope                          0.18.0
Rtree                         0.9.4
scikit-learn                  0.23.2
scipy                         1.5.3
seaborn                       0.11.0
Send2Trash                    1.5.0
setuptools                    50.3.0.post20201006
Shapely                       1.7.1
six                           1.15.0
tabulate                      0.8.7
termcolor                     1.1.0
terminado                     0.9.1
testpath                      0.4.4
threadpoolctl                 2.1.0
toml                          0.10.1
torch                         1.8.0.dev20201021
torchvision                   0.8.0.dev20201021
tornado                       6.0.4
tqdm                          4.52.0
traitlets                     5.0.5
traittypes                    0.2.1
trimesh                       3.8.11
typing-extensions             3.7.4.3
wcwidth                       0.2.5
webencodings                  0.5.1
wheel                         0.35.1
widgetsnbextension            3.5.1
wrapt                         1.11.2
yacs                          0.1.6
zipp                          3.3.1

**Comment by bottler** [comment]
I am confused by that `conda list` output because it doesn't show `cudatoolkit` or `python`. Could it be a `pip list` not a `conda list`?

You don't really have pytorch 1.7. You have development versions of torchvision and pytorch - e.g. pytorch 1.8.0.dev20201021 - and I don't know much about these. Are these nightlies? conda doesn't know that pytorch3d's released packages are compatible with this.
If you are following PyTorch development and you are confident that your versions are actually binary compatible with PyTorch 1.7.0 (because little has changed) then you could download the relevant PyTorch3D conda package from https://anaconda.org/pytorch3d/pytorch3d/0.3.0/download/linux-64/pytorch3d-0.3.0-py38_cu110_pyt170.tar.bz2
(if you have Python 3.8 - I can't tell - otherwise change the `py38` to `py37` or `py36` as needed) and then force conda to install it, ignoring the dependencies. This is living dangerously.

I think it will be easier for you to play safe, either by 1) starting a new environment for pytorch3d work where you use released versions of PyTorch and torchvision. Follow the instructions in INSTALL.md. Or 2) building pytorch3d from source.

**Comment by AZadora** [comment]
> I am confused by that `conda list` output because it doesn't show `cudatoolkit` or `python`. Could it be a `pip list` not a `conda list`?
> 
> You don't really have pytorch 1.7. You have development versions of torchvision and pytorch - e.g. pytorch 1.8.0.dev20201021 - and I don't know much about these. Are these nightlies? conda doesn't know that pytorch3d's released packages are compatible with this.
> If you are following PyTorch development and you are confident that your versions are actually binary compatible with PyTorch 1.7.0 (because little has changed) then you could download the relevant PyTorch3D conda package from https://anaconda.org/pytorch3d/pytorch3d/0.3.0/download/linux-64/pytorch3d-0.3.0-py38_cu110_pyt170.tar.bz2
> (if you have Python 3.8 - I can't tell - otherwise change the `py38` to `py37` or `py36` as needed) and then force conda to install it, ignoring the dependencies. This is living dangerously.
> 
> I think it will be easier for you to play safe, either by 1) starting a new environment for pytorch3d work where you use released versions of PyTorch and torchvision. Follow the instructions in INSTALL.md. Or 2) building pytorch3d from source.

Thank you for reply! Actually, yes, this is PyTorch nightly version. I think I will install release version.
Regarding `cuda-toolkit`, pip list doesn't show this either. It's weird because I installed PyTorch with `cudatoolkit 11.0` and PyTorch shows that CUDA is enabled. Maybe it's better to reinstall PyTorch.

**Comment by bottler** [comment]
There is no problem with the cudatoolkit thing and you shouldn't worry about your install. cudatoolkit is a conda package but it is not a python library, so it makes sense that `conda list` will include it and `pip list` won't. I only mentioned it to illustrate my reasoning about your message, not to say something about your environment.

However I agree that you might as well start again in a new conda environment because you want a new pytorch.

**Comment by nikhilaravi** [comment]
@AZadora Has this issue now been resolved?

**Comment by AZadora** [comment]
> @AZadora Has this issue now been resolved?

Yes!

**Comment by nikhilaravi** [comment]
Ok I will close the issue.
