### ISSUE TITLE
RuntimeError: CUDA error: invalid device function

### ISSUE THREAD

**Issue by lishang6257** [facebookresearch/pytorch3d#464]
When i had installed the Pytorch3d on ubuntu(16.04 LTS) following the official [install tutorial](https://github.com/facebookresearch/pytorch3d/blob/fc7a4cacc36ecf2b8feb996bdfb1203dee5d836b/INSTALL.md) (install from local clone) and tested my code(which is allright for old server with Tian xp), bugs appeared for new server(more information can be seen in pic).
![image](https://user-images.githubusercontent.com/26080906/100099027-cf6f8b80-2e99-11eb-9d66-b0e53415f555.png)
![image](https://user-images.githubusercontent.com/26080906/100099578-9be13100-2e9a-11eb-9bd5-eb68b033bf7c.png)
The issuse is similiar to [issue 234](https://github.com/facebookresearch/pytorch3d/issues/234), so i tried the solution, but it didn't work.

> NVCC_FLAGS="-gencode=arch=compute_75,code=sm_75" pip install -e .

Hope for your reply. Thanks.

**Comment by bottler** [comment]
Can you tell us more about your setup please? Did you rebuild PyTorch3D on the new system, or are you using what you built on the old server? What version of CUDA are you using, and what version of the nvidia driver do you have?

Are you using conda? If so, please paste the output of `conda list`. If you didn't install PyTorch via conda, how did you get it?

Thanks

**Comment by lishang6257** [comment]
I install pytorch3d by using the same method described in the following pic, instead of copying the old conda env from old server.
![image](https://user-images.githubusercontent.com/26080906/100198811-4f97fe80-2f37-11eb-8ddd-d50e4cd61ba9.png)
![image](https://user-images.githubusercontent.com/26080906/100199052-9b4aa800-2f37-11eb-8491-362eebfec103.png)
the repo i used is the master branch,
![image](https://user-images.githubusercontent.com/26080906/100199445-29269300-2f38-11eb-99d1-23172106482a.png)
and the conda list in the new server is here.
![image](https://user-images.githubusercontent.com/26080906/100200930-4bb9ab80-2f3a-11eb-8b93-d15daf42fbfe.png)
The driver version is here
![image](https://user-images.githubusercontent.com/26080906/100201095-920f0a80-2f3a-11eb-85a3-cd9893a907e6.png)
Hope for your reply. Thanks.

**Comment by bottler** [comment]
I have no idea here.

Can you try making another new environment with just the dependencies installed and installing the prebuilt conda package for pytorch3d and see if that works? If it does, we might conclude it's something to do with the build. If it doesn't, we might conclude it's something to do with the environment.

**Comment by lishang6257** [comment]
I have tried install pytorch3d form conda channel but the errors also existed.
