### ISSUE TITLE
Rendering textured mesh from ply - no error but nothing is visible

### ISSUE THREAD

**Issue by pankaja0285** [facebookresearch/pytorch3d#468]
I followed the issue #315 details, one thing to note as per @bottler I can't use tex=Textures(verts_rgb=features) as I get the error 
TypeError: __init__() got an unexpected keyword argument 'verts_rgb' 

Here's my code block
` 
import plyfile
import numpy as np

pltFilename = './output/bpa_mesh.ply'
data = plyfile.PlyData.read(pltFilename)['vertex']
print(data)
`output/bpa_mesh.ply
data  element vertex 37104
property double x
property double y
property double z
property double nx
property double ny
property double nz
property uchar red
property uchar green
property uchar blue`

if data is not None:
    np_vertices = np.c_[data['x'], data['y'], data['z']]
    np_vertex_colors = np.c_[data['red'], data['green'], data['blue']]
    np_faces = np.c_[data['nx'], data['ny'], data['nz']]

    print('np_vertices ', np_vertices)
    verts = torch.from_numpy(np.array(np_vertices, dtype='float32'))[None]
    faces = torch.from_numpy(np.array(np_faces,dtype='int64'))[None]
    features = torch.from_numpy(np.array(np_vertex_colors,dtype='float32'))[None]
    tex = TexturesVertex(verts_features=features)
    mesh = Meshes(verts=verts, faces=faces, textures = tex)
    print('mesh ', mesh)

# Initialize a camera
R, T = look_at_view_transform(2.7, 0, 180) 
cameras = FoVPerspectiveCameras(device=device, R=R, T=T)

#raster settings
raster_settings = RasterizationSettings(
    image_size=512, 
    blur_radius=0.0, 
    faces_per_pixel=1, 
)
# Place a point light in front of the object.
lights = PointLights(device=device, location=[[0.0, 0.0, -3.0]])

# apply the Phong lighting model
renderer = MeshRenderer(
    rasterizer=MeshRasterizer(
        cameras=cameras, 
        raster_settings=raster_settings
    ),
    shader=SoftPhongShader(
        device=device, 
        cameras=cameras,
        lights=lights
    )
)
images = renderer(mesh)
plt.figure(figsize=(10, 10))
plt.imshow(images[0, ..., :3].cpu().numpy())
plt.grid("off");
plt.axis("off")

`
What am I doing wrong? Image is not visible.
Please advice.

**Comment by bottler** [comment]
I don't know why `verts_rgb` didn't work, but you were right to switch to the non-deprecated `TexturesVertex` instead of the `Textures` class. 

The simplest reason why you aren't seeing anything could be that the camera is not actually facing the object. Can you look at where the mesh is, perhaps by printing `verts.min(dim=1)` and `verts.max(dim=1)`? If you can install plotly, it also might be worth plotting the camera and the mesh together in one 3d plot as follows - this should help you diagnose oddities both with the mesh itself and the camera location. 
```
from pytorch3d.vis.plotly_vis import plot_batch_individually
plot_batch_individually([cow_mesh, cameras])
```

**Comment by pankaja0285** [comment]
@bottler I tried the following as per your suggestion
print('verts.min(dim=1) ', verts.min(dim=1))
print('verts.max(dim=1) ', verts.max(dim=1))

and the outputs are 
verts.min(dim=1)  torch.return_types.min(
values=tensor([[-0.4860, -0.6335,  0.5315]]),
indices=tensor([[32101,   109, 17189]]))
verts.max(dim=1)  torch.return_types.max(
values=tensor([[0.6623, 0.6381, 1.5374]]),
indices=tensor([[31652, 37017, 36044]]))

2. Next installed plotly and tried to plot camera and mesh together
import plotly.graph_objects as go

**Comment by bottler** [comment]
It looks like there is no mesh. 

You are not loading the faces correctly from the ply file. They don't come from the "vertex" element, they should come from another element - you can look at our ply_io functions for where they might live. I think the `nx, ny, nz` values are actually normals, and they become zero after rounding, so you probably have one [0,0,0] face repeated. In this case of colors being stored with the vertices our ply file reader will currently not load this efficiently, so you are right to use the other library, you just need to be careful.

**Comment by pankaja0285** [comment]
@bottler just tried what you suggested and I get this error

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-42-fc4d1340b323> in <module>
----> 1 verts, faces = load_ply(pltFilename)

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/pytorch3d/io/ply_io.py in load_ply(f)
    664         not isinstance(vertex, np.ndarray) or vertex.ndim != 2 or vertex.shape[1] != 3
    665     ):
--> 666         raise ValueError("Invalid vertices in file.")
    667     verts = _make_tensor(vertex, cols=3, dtype=torch.float32)
    668 

ValueError: Invalid vertices in file.

**Is there an api in PyTorch3D to convert pcd to ply or pcd to mesh directly - if so what is it?**

FYI, in my case I used a few steps to achieve the mesh here's my code snippet

a)using PyPcd to load the pcd file
# First of all we get all columns again
new_cloud_data = cloud.pc_data.view(np.float32).reshape(cloud.pc_data.shape + (-1,))

rgbs = new_cloud_data[:, [3]]
print(rgbs)

xyzs = new_cloud_data[:, [0,1,2]]
print(xyzs)
# split the rgb column into three columns: red, green and blue
rgb_columns = pypcd.decode_rgb_from_pcl(rgbs.reshape(1, -1))

# normalize the rgb values (they should be between [0, 1])
rgb_columns = (rgb_columns / 255.0).astype(np.float)

b) Using open3d 
 import open3d as o3d 
 #Format to open3d usable objects
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(xyzs)
pcd.colors = o3d.utility.Vector3dVector(rgb_columns)

c) Computing the mesh and decimating with open3d
#radius determination
distances = pcd.compute_nearest_neighbor_distance()
avg_dist = np.mean(distances)
radius = 3 * avg_dist
#computing the mesh
bpa_mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_ball_pivoting(pcd,o3d.utility.DoubleVector([radius, radius * 2]))
#decimating the mesh
dec_mesh = bpa_mesh.simplify_quadric_decimation(100000)

dec_mesh.remove_degenerate_triangles()
dec_mesh.remove_duplicated_triangles()
dec_mesh.remove_duplicated_vertices()
dec_mesh.remove_non_manifold_edges()

d)Cropping
#cropping
bbox = pcd.get_axis_aligned_bounding_box()
p_mesh_crop = poisson_mesh.crop(bbox)

e)writing the output to ply file
#export
bpaResult = o3d.io.write_triangle_mesh(output_path+"bpa_mesh.ply", dec_mesh)

So this ply file is what I loaded with plyfile and the rest about extracting the vertices etc. is already in my original message where I have given that code.

I also created a poisson mesh and exported to a ply file. Same issue.

Please let me know if I can use a PyTorch3d api to read the pcd from a .pcd file and create a mesh and use it to plot.
TIA.

**Comment by bottler** [comment]
I'm confused. I said in the previous message that you were right to try to use an external library (ie plyfile) to load this particular ply file because our current functionality would fail with it. You successfully loaded the verts and colors in your code in the first post. You just need to tweak your original code to get the faces correctly from the plyfile object.

I suggested you look in our ply_io code for a hint as to how to load the actual faces data. Don't worry about that now. In particular, if `x` is `plyfile.PlyData.read(pltFilename)` then you are correct in your original code reading the colors and verts from `x[vertex]`. I think you will find the face data in `x['face']` as its only member.
Can you try looking there?

**Comment by pankaja0285** [comment]
@bottler  I totally get what you are saying I did extract the face - x['face'] as well and tried using it to generate the mesh and still it wouldn't plot.

**Comment by bottler** [comment]
This leaves us hanging - I can't help you unless you give me more details. It sounds like you did the right thing. Can you print the shape and some values from the thing you supplied as `faces`?

**Comment by pankaja0285** [comment]
faces = np.array([f[0] for f in data["face"].data])
print(faces)

prints the following
[[     0     43      1]
 [    44     45      3]
 [     3      2     44]
 ...
 [118491 118397 118398]
 [118398 118494 118491]
 [118391 118388 118487]]

**Comment by bottler** [comment]
That looks fine. If you use that like np_faces in the original code you should have a good mesh which the plotly command should show.

**Comment by pankaja0285** [comment]
Yes that works with both pytorch3d visualization individually and with doing with matplotlib.pyplot imshow. Only thing is the mesh is not so great. What are your suggestions to tweak the meshes and also be able to plot as  a true triangle shaped mesh image of the subject (here its a human)? Please advice.

**Comment by bottler** [comment]
I don't quite understand what is "not so great". Originally this issue was about loading a mesh and rendering it with pytorch3d's renderer. It sounds like you have now succeeded in getting the plotly visualization to work. Have you got the renderer to work - if you still want to? Are you asking how to "improve" the visualization, or the rendering, or the mesh itself, and in what way?

**Comment by pankaja0285** [comment]
No I did get it working. My question was the visualization quality is poor and also the meshes are not that clear. Agreed the mesh depends on the ply image (in my case I am converting .pcd to ply and then doing the textured mesh visualization). So I was asking for any suggestions or technique that you might have.

**Comment by bottler** [comment]
Can you be more specific about "quality is poor"? Maybe screenshots of what you see and a description of what you want to see.

**Comment by pankaja0285** [comment]
@bottler - sorry got caught up doing some work that I had to finish. Anyway, here's the code for the plot
`
# extend the batch to have 4 meshes
mesh_4 = mesh_batch.extend(2)

# visualize the batch in different subplots, 2 per row
fig = plot_batch_individually(mesh_4)
# we can update the figure height and width
fig.update_layout(height=1000, width=500)
fig.show()

`
So attaching the output here - I zoomed some before snapping the screenshot...
<img width="409" alt="mesh_plot" src="https://user-images.githubusercontent.com/54913075/100813694-de13f080-340d-11eb-8a23-d7f3df744fe3.PNG">

**Comment by bottler** [comment]
I still don't understand what you're asking about. What is it about that plot which you expect to be different? Is it something about the mesh itself or about the way plotly is showing it? If it's plotly, there are lots of options available so you could change its behaviour, or feel free to use a different visualization method if you want. Perhaps the mottled quality of the surface is surprising and it might be a lighting thing; you might supply your own `lighting` argument to `plot_batch_individually`. If it's the mesh itself, then we need more information.

**Comment by nikhilaravi** [comment]
Closing this issue as there have been no further questions. Feel free to reopen the issue if needed.
