### ISSUE TITLE
Does conversion between Euler angle and matrix consider unstable situations?

### ISSUE THREAD

**Issue by Xiaoming-Zhao** [facebookresearch/pytorch3d#473]
Hi, thanks a lot for this great tool! I just checked the [implementation](https://github.com/facebookresearch/pytorch3d/blob/7e986cfba8e8e09fbd24ffc1cbfef2914681e02c/pytorch3d/transforms/rotation_conversions.py#L216) about conversion between Euler and rotation matrix and have a question with it: I am wondering whether PyTorch3D's implementation considers singularities/unstable situations when going from rotation matrix to Euler angles?

For example, when the central angle is close to `pi/2` or `-pi/2`, `cos(central_angle)` locates really close to 0 and will result in instability of `arctan2` when computing the other two angles. Such singularities are considered in (see ref [2] in [SciPy's doc](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.as_euler.html) and [its implementation](https://github.com/scipy/scipy/blob/v1.5.4/scipy/spatial/transform/rotation.py#L132)). Any guidance will be appreciated. Thanks

**Comment by bottler** [comment]
As you can see, the code doesn't treat the region around gimbal lock specially, and you are correct the other angles may be unstable. I can't currently see the article scipy cites right now, or see other implementations which follow the article. 

I would hope that someone would use Euler angles only when they knew they could avoid the difficult zone. Do you have a use case?

**Comment by Xiaoming-Zhao** [comment]
@bottler Thanks a lot for you reply!

FYI: the ref [2] in scipy's documentary can be found [here](https://www.researchgate.net/publication/238189035_General_Formula_for_Extracting_the_Euler_Angles).

I just played around via applying scipy's  [unittest 1](https://github.com/scipy/scipy/blob/v1.5.4/scipy/spatial/transform/tests/test_rotation.py#L498) and [unittest 2](https://github.com/scipy/scipy/blob/v1.5.4/scipy/spatial/transform/tests/test_rotation.py#L535) to PyTorch3d. It seems like this may not be a big issue as I thought before:

```python
from scipy.spatial.transform import Rotation

seq = "xyz"
angles = [45, 90, 35]

# for SciPy
rotation = Rotation.from_euler(seq, angles, degrees=True)
mat_expected = rotation.as_matrix()
print(mat_expected)

angle_estimates = rotation.as_euler(seq, degrees=True)
mat_estimated = Rotation.from_euler(seq, angle_estimates, degrees=True).as_matrix()
print(angle_estimates)
print(mat_estimated)

# for PyTorch3d
import torch
from pytorch3d import transforms

angle_estimates_pytorch3d = transforms.rotation_conversions.matrix_to_euler_angles(torch.Tensor(mat_expected), convention="XYZ")
print(angle_estimates_pytorch3d / np.pi * 180)

mat_estimated_pytorch3d = transforms.rotation_conversions.euler_angles_to_matrix(angle_estimates_pytorch3d, convention="XYZ")
print(mat_estimated_pytorch3d)
```

Any thoughts about this? Thanks
