### ISSUE TITLE
Volumetric Analysis using Pytorch3D

### ISSUE THREAD

**Issue by Hemantr05** [facebookresearch/pytorch3d#474]
With the help of Pytorch3D, is it possible to have an understanding of the volume of a given mesh/voxel or a component of the mesh?
For example, I have a .obj/.ply file for an entire room, which consists of cabinets, shelves, etc.. is it possible to determine the volume of a particular cabinet or shelf using the existing functionality of pytorch3D?

**Comment by nikhilaravi** [comment]
@Hemantr05 currently we don't have any functions in PyTorch3D to calculate the enclosed volume of a mesh. If the meshes are watertight you could try using relevant functions from trimesh to calculate the volume e.g. https://trimsh.org/trimesh.base.html?highlight=volume#trimesh.base.Trimesh.volume

**Comment by Hemantr05** [comment]
Would it be helpful feature if I work on a module to compute the volume of a mesh? @nikhilaravi
