### ISSUE TITLE
Import Error in tutorial deform_source_mesh_to_target_mesh

### ISSUE THREAD

**Issue by jsaluja** [facebookresearch/pytorch3d#475]
## 🐛 Bugs / Unexpected behaviors

Import Error in tutorial deform_source_mesh_to_target_mesh
## Instructions To Reproduce the Issue:

Please include the following (depending on what the issue is):

1. Any changes you made (`git diff`) or code you wrote
```
NA
```
2. The exact command(s) you ran:
import os
import torch
from pytorch3d.io import load_obj, save_obj

3. What you observed (including the full logs):
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-7-8e269cdc882c> in <module>
      1 import os
      2 import torch
----> 3 from pytorch3d.io import load_obj, save_obj

~/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/pytorch3d/io/__init__.py in <module>
      2 
      3 
----> 4 from .obj_io import load_obj, load_objs_as_meshes, save_obj
      5 from .ply_io import load_ply, save_ply
      6 

~/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/pytorch3d/io/obj_io.py in <module>
     12 from pytorch3d.io.mtl_io import load_mtl, make_mesh_texture_atlas
     13 from pytorch3d.io.utils import _check_faces_indices, _make_tensor, _open_file
---> 14 from pytorch3d.renderer import TexturesAtlas, TexturesUV
     15 from pytorch3d.structures import Meshes, join_meshes_as_batch
     16 

~/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/pytorch3d/renderer/__init__.py in <module>
      1 # Copyright (c) Facebook, Inc. and its affiliates. All rights reserved.
      2 
----> 3 from .blending import (
      4     BlendParams,
      5     hard_rgb_blend,

~/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/pytorch3d/renderer/blending.py in <module>
      7 
      8 # pyre-fixme[21]: Could not find name `_C` in `pytorch3d`.
----> 9 from pytorch3d import _C
     10 
     11 

ImportError: dlopen(/Users/jssaluja/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/pytorch3d/_C.cpython-38-darwin.so, 2): Symbol not found: __ZN3c104impl23ExcludeDispatchKeyGuardC1ENS_11DispatchKeyE
  Referenced from: /Users/jssaluja/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/pytorch3d/_C.cpython-38-darwin.so
  Expected in: /Users/jssaluja/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/torch/lib/libc10.dylib
 in /Users/jssaluja/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/pytorch3d/_C.cpython-38-darwin.so
```

Please also simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

Installed pytorch3d
conda activate pytorch3d
jupyter notebook

**Comment by jsaluja** [comment]
$ conda list
 packages in environment at /Users/jssaluja/anaconda3/envs/pytorch3d:

 Name                    Version                   Build  Channel
appdirs                   1.4.4                    pypi_0    pypi
appnope                   0.1.2           py38hecd8cb5_1001  
argon2-cffi               20.1.0           py38haf1e3a3_1  
async_generator           1.10                       py_0  
attrs                     20.3.0             pyhd3eb1b0_0  
backcall                  0.2.0                      py_0  
black                     20.8b1                   pypi_0    pypi
blas                      1.0                         mkl  
bleach                    3.2.1                      py_0  
ca-certificates           2020.10.14                    0  
certifi                   2020.11.8        py38hecd8cb5_0  
cffi                      1.14.4           py38h2125817_0  
click                     7.1.2                    pypi_0    pypi
cudatoolkit               9.0                  h41a26b3_0    anaconda
cycler                    0.10.0                   pypi_0    pypi
dataclasses               0.6                      pypi_0    pypi
dbus                      1.13.18              h18a8e69_0  
decorator                 4.4.2                      py_0  
defusedxml                0.6.0                      py_0  
entrypoints               0.3                      py38_0  
expat                     2.2.10               hb1e8313_2  
flake8                    3.8.4                    pypi_0    pypi
flake8-bugbear            20.11.1                  pypi_0    pypi
flake8-comprehensions     3.3.0                    pypi_0    pypi
freetype                  2.10.4               h3f75d11_0    conda-forge
future                    0.18.2                   pypi_0    pypi
fvcore                    0.1.2.post20201204    pyhd8ed1ab_0    conda-forge
gettext                   0.19.8.1             hb0f4f8b_2  
glib                      2.66.1               h9bbe63b_0  
icu                       58.2                 h0a44026_3  
imageio                   2.9.0                    pypi_0    pypi
importlib-metadata        2.0.0                      py_1  
importlib_metadata        2.0.0                         1  
intel-openmp              2019.4                      233  
ipykernel                 5.3.4            py38h5ca1d4c_0  
ipython                   7.19.0           py38h01d92e1_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                7.5.1                      py_1  
isort                     4.3.21                   pypi_0    pypi
jedi                      0.17.2           py38hecd8cb5_1  
jinja2                    2.11.2                     py_0  
jpeg                      9d                   hbcb3906_0    conda-forge
jsonschema                3.2.0                      py_2  
jupyter                   1.0.0                    py38_7  
jupyter_client            6.1.7                      py_0  
jupyter_console           6.2.0                      py_0  
jupyter_core              4.7.0            py38hecd8cb5_0  
jupyterlab_pygments       0.1.2                      py_0  
kiwisolver                1.3.1                    pypi_0    pypi
lcms2                     2.11                 h11f7e16_1    conda-forge
libcxx                    10.0.0                        1  
libedit                   3.1.20191231         h1de35cc_1  
libffi                    3.3                  hb1e8313_2  
libiconv                  1.16                 h1de35cc_0  
libpng                    1.6.37               h7cec526_2    conda-forge
libsodium                 1.0.18               h1de35cc_0  
libtiff                   4.1.0                h2ae36a8_6    conda-forge
libuv                     1.40.0               haf1e3a3_0  
libwebp-base              1.1.0                hbcb3906_3    conda-forge
lz4-c                     1.9.2                h4a8c4bd_1    conda-forge
markupsafe                1.1.1            py38h1de35cc_1  
matplotlib                3.3.3                    pypi_0    pypi
mccabe                    0.6.1                    pypi_0    pypi
mistune                   0.8.4           py38h1de35cc_1001  
mkl                       2019.4                      233  
mkl-service               2.3.0            py38hfbe908c_0  
mkl_fft                   1.2.0            py38hc64f4ea_0  
mkl_random                1.1.1            py38h959d312_0  
mypy-extensions           0.4.3                    pypi_0    pypi
nbclient                  0.5.1                      py_0  
nbconvert                 6.0.7                    py38_0  
nbformat                  5.0.8                      py_0  
ncurses                   6.2                  h0a44026_1  
nest-asyncio              1.4.3              pyhd3eb1b0_0  
networkx                  2.5                      pypi_0    pypi
ninja                     1.10.2           py38hf7b0b51_0  
notebook                  6.1.4                    py38_0  
numpy                     1.19.2           py38h456fd55_0  
numpy-base                1.19.2           py38hcfb5961_0  
olefile                   0.46               pyh9f0ad1d_1    conda-forge
opencv-python             4.4.0.46                 pypi_0    pypi
openssl                   1.1.1h               haf1e3a3_0  
packaging                 20.7               pyhd3eb1b0_0  
pandoc                    2.11                 h0dc7051_0  
pandocfilters             1.4.3            py38hecd8cb5_1  
parso                     0.7.0                      py_0  
pathspec                  0.8.1                    pypi_0    pypi
pcre                      8.44                 hb1e8313_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    8.0.1            py38h565d989_0    conda-forge
pip                       20.3             py38hecd8cb5_0  
plotly                    4.13.0                   pypi_0    pypi
portalocker               1.7.0            py38h32f6830_1    conda-forge
prometheus_client         0.9.0              pyhd3eb1b0_0  
prompt-toolkit            3.0.8                      py_0  
prompt_toolkit            3.0.8                         0  
ptyprocess                0.6.0              pyhd3eb1b0_2  
pycodestyle               2.6.0                    pypi_0    pypi
pycparser                 2.20                       py_2  
pyflakes                  2.2.0                    pypi_0    pypi
pygments                  2.7.2              pyhd3eb1b0_0  
pyparsing                 2.4.7                      py_0  
pyqt                      5.9.2            py38h655552a_2  
pyrsistent                0.17.3           py38haf1e3a3_0  
python                    3.8.5                h26836e1_1  
python-dateutil           2.8.1                      py_0  
python_abi                3.8                      1_cp38    conda-forge
pytorch                   1.7.0                   py3.8_0    pytorch
pytorch3d                 0.3.0                    pypi_0    pypi
pywavelets                1.1.1                    pypi_0    pypi
pyyaml                    5.3.1            py38h94c058a_1    conda-forge
pyzmq                     20.0.0           py38h23ab428_1  
qt                        5.9.7                h468cd18_1  
qtconsole                 4.7.7                      py_0  
qtpy                      1.9.0                      py_0  
readline                  8.0                  h1de35cc_0  
regex                     2020.11.13               pypi_0    pypi
retrying                  1.3.3                    pypi_0    pypi
scikit-image              0.17.2                   pypi_0    pypi
scipy                     1.5.4                    pypi_0    pypi
send2trash                1.5.0                    py38_0  
setuptools                50.3.2           py38hecd8cb5_2  
sip                       4.19.8           py38h0a44026_0  
six                       1.15.0           py38hecd8cb5_0  
sqlite                    3.33.0               hffcf06c_0  
tabulate                  0.8.7              pyh9f0ad1d_0    conda-forge
termcolor                 1.1.0                      py_2    conda-forge
terminado                 0.9.1                    py38_0  
testpath                  0.4.4                      py_0  
tifffile                  2020.11.26               pypi_0    pypi
tk                        8.6.10               hb0a8c7a_0  
toml                      0.10.2                   pypi_0    pypi
torchvision               0.8.1                  py38_cpu    pytorch
tornado                   6.0.4            py38h1de35cc_1  
tqdm                      4.54.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.0.5                      py_0  
typed-ast                 1.4.1                    pypi_0    pypi
typing_extensions         3.7.4.3                    py_0  
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    py38_1  
wheel                     0.35.1             pyhd3eb1b0_0  
widgetsnbextension        3.5.1                    py38_0  
xz                        5.2.5                h1de35cc_0  
yacs                      0.1.6                      py_0    conda-forge
yaml                      0.2.5                haf1e3a3_0    conda-forge
zeromq                    4.3.3                hb1e8313_3  
zipp                      3.4.0              pyhd3eb1b0_0  
zlib                      1.2.11               h1de35cc_3  
zstd                      1.4.5                h0384e3a_1    conda-forge

**Comment by bottler** [comment]
(This is a mac question.)

I think you have installed pytorch3d from PyPI with `pip install pytorch3d`. The packages which we provide for mac are only compatible with pytorch 1.6.0. The latest release of pytorch is 1.7.0 which is what you have. Can you set up a new conda environment with pytorch 1.6.0 as below, and then you should be alright?

```
conda create -n pytorch3d python=3.8
conda activate pytorch3d
conda install -c pytorch pytorch=1.6.0 torchvision
conda install -c conda-forge -c fvcore fvcore
pip install pytorch3d
```
 
If you don't want to do that, I think you will need to install pytorch3d from source.

**Comment by jsaluja** [comment]
@bottler Thank you for the suggestion

I executed your steps, and get exception at
import torch

ModuleNotFoundError: No module named 'torch'

**Comment by jsaluja** [comment]
$ conda list
# packages in environment at /Users/jssaluja/anaconda3/envs/pytorch3d:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl
ca-certificates           2020.12.5            h033912b_0    conda-forge
certifi                   2020.12.5        py38h50d1736_0    conda-forge
freetype                  2.10.4               ha233b18_0
future                    0.18.2                   pypi_0    pypi
fvcore                    0.1.2.post20201204    pyhd8ed1ab_0    conda-forge
intel-openmp              2019.4                      233
jpeg                      9b                   he5867d9_2
lcms2                     2.11                 h92f6f08_0
libcxx                    10.0.0                        1
libedit                   3.1.20191231         h1de35cc_1
libffi                    3.3                  hb1e8313_2
libpng                    1.6.37               ha441bb4_0
libtiff                   4.1.0                hcb84e12_1
lz4-c                     1.9.2                h79c402e_3
mkl                       2019.4                      233
mkl-service               2.3.0            py38h9ed2024_0
mkl_fft                   1.2.0            py38hc64f4ea_0
mkl_random                1.1.1            py38h959d312_0
ncurses                   6.2                  h0a44026_1
ninja                     1.10.2           py38hf7b0b51_0
numpy                     1.19.2           py38h456fd55_0
numpy-base                1.19.2           py38hcfb5961_0
olefile                   0.46                       py_0
openssl                   1.1.1h               haf1e3a3_0    conda-forge
pillow                    8.0.1            py38h5270095_0
pip                       20.3.1           py38hecd8cb5_0
portalocker               1.7.0            py38h32f6830_1    conda-forge
python                    3.8.5                h26836e1_1
python_abi                3.8                      1_cp38    conda-forge
pytorch                   1.6.0                   py3.8_0    pytorch
pytorch3d                 0.3.0                    pypi_0    pypi
pyyaml                    5.3.1            py38h94c058a_1    conda-forge
readline                  8.0                  h1de35cc_0
setuptools                51.0.0           py38hecd8cb5_2
six                       1.15.0           py38hecd8cb5_0
sqlite                    3.33.0               hffcf06c_0
tabulate                  0.8.7              pyh9f0ad1d_0    conda-forge
termcolor                 1.1.0                      py_2    conda-forge
tk                        8.6.10               hb0a8c7a_0
torchvision               0.7.0                  py38_cpu    pytorch
tqdm                      4.54.1             pyhd8ed1ab_0    conda-forge
wheel                     0.36.1             pyhd3eb1b0_0
xz                        5.2.5                h1de35cc_0
yacs                      0.1.6                      py_0    conda-forge
yaml                      0.2.5                haf1e3a3_0    conda-forge
zlib                      1.2.11               h1de35cc_3
zstd                      1.4.5                h41d2c2f_0

**Comment by jsaluja** [comment]
@bottler Thank you for the suggestion

I tried your steps, and run into exception on
import torch

ModuleNotFoundError: No module named 'torch'

I encounter above exception when using jupyter notebook

I can complete these imports on terminal without any issues

(base) jssaluja-mbp:~ jssaluja$ conda activate pytorch3d
(pytorch3d) jssaluja-mbp:~ jssaluja$ python -V
Python 3.8.5
(pytorch3d) jssaluja-mbp:~ jssaluja$ python
Python 3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> import torch
>>> from pytorch3d.io import load_obj, save_obj
>>> from pytorch3d.structures import Meshes
>>> from pytorch3d.utils import ico_sphere
>>> from pytorch3d.ops import sample_points_from_meshes
>>> from pytorch3d.loss import (
...     chamfer_distance, 
...     mesh_edge_loss, 
...     mesh_laplacian_smoothing, 
...     mesh_normal_consistency,
... )
>>> import numpy as np
>>> from tqdm.notebook import tqdm

**Comment by bottler** [comment]
You need to start jupyter notebook (with `jupyter notebook` or `jupyter start` or whatever) when the `pytorch3d` environment is activated - i.e. when the prompts is showing `(pytorch3d) jssaluja-mbp:~ jssaluja$`.

If that doesn't work, the solution is to install jupyter in that environment (e.g. with `conda install jupyter` at that prompt), not to try to run outside the environment.

**Comment by jsaluja** [comment]
Thanks @bottler 

Documenting the solution for posterity

> the solution is to install jupyter in that environment (e.g. with `conda install jupyter` at that prompt), not to try to run outside the environment.

^^ Worked

> You need to start jupyter notebook (with jupyter notebook or jupyter start or whatever) when the pytorch3d environment is activated - i.e. when the prompts is showing (pytorch3d) jssaluja-mbp:~ jssaluja$

^^ Did not work. I tried this before posting the issue here
