### ISSUE TITLE
_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c104impl23ExcludeDispatchKeyGuardC1ENS_11DispatchKeyE

### ISSUE THREAD

**Issue by sunbin1357** [facebookresearch/pytorch3d#476]
1、python3 -m pip install pytorch3d
![image](https://user-images.githubusercontent.com/47880903/101277136-26a42300-37ed-11eb-82b8-d89c90104a93.png)
2、  python3  smal_fitter/optimize_to_joints.py
![image](https://user-images.githubusercontent.com/47880903/101277140-3459a880-37ed-11eb-99a6-eb385f4e81be.png)
/opt/conda/lib/python3.6/site-packages/pytorch3d/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c104impl23ExcludeDispatchKeyGuardC1ENS_11DispatchKeyE

How to solve this problem？

my python is 3.6.

![image](https://user-images.githubusercontent.com/47880903/101277184-9dd9b700-37ed-11eb-9646-fac7ee4ba07c.png)

from the image we can see that "import pytorch3d" is ok.

**Comment by bottler** [comment]
The prebuilt wheels on PyPI for pytorch3d are only for a particular version of pytorch, specifically pytorch 1.6.0 at the moment. I suspect you have a different version of pytorch - maybe the latest, 1.7.0. Getting this wrong is likely to produce and error like the one you see. Additionally, if you want pytorch3d to work with your GPU, you also have to have the right cuda version. The details are given [here](https://github.com/facebookresearch/pytorch3d/blob/master/INSTALL.md).  If you can use conda to install everything then there is full flexibility on these versions and it is automatic to get everything right. Alternatively building pytorch3d from source also gives you full flexibility.

If you want more advice on what is wrong here, please paste the output of `pip list`.

**Comment by nikhilaravi** [comment]
@sunbin1357 were you able to resolve this issue using the suggestions from @bottler? If you don't have any further questions please close this issue.
