### ISSUE TITLE
mesh annotation

### ISSUE THREAD

**Issue by Yumin-Sun-00** [facebookresearch/pytorch3d#477]
## 🚀 Feature
I think it is helpful, if the library could provide a way to load the annotated meshes (labeled by each face or each vertex) and render such annotation images. Right now, I try to have such annotation by loading the labels as vertex features and interpolate.

**Comment by nikhilaravi** [comment]
@Yumin-Sun-00 what is the format of the annotations? Are they saved in the save file as the mesh verts/faces data or separately? In general in PyTorch3D we provide general purpose functions which you can extend.  If the annotations are saved separately then you can create your own wrapper function.

**Comment by nikhilaravi** [comment]
@Yumin-Sun-00 do you still need help with this question or can I close the issue?

**Comment by Yumin-Sun-00** [comment]
Hi, thanks for asking, we can close it, found out a way to colorize the face by using the fragements from the rasterizer.
