### ISSUE TITLE
Find correspondences between vertices and their projections?

### ISSUE THREAD

**Issue by ysig** [facebookresearch/pytorch3d#478]
Hi,

I am trying to implement the paper [Pixel2Mesh](https://openaccess.thecvf.com/content_ECCV_2018/papers/Nanyang_Wang_Pixel2Mesh_Generating_3D_ECCV_2018_paper.pdf) and I am trying to use entirely operations from Pytorch3D.
In there there is an operation (Perceptual feature pooling layer page 6) which projects a mesh to an image and then updates the feature of the vertex given the features that are at the location where it is projected inside the image.
I was curious whether it is possible to see the correspondences between vertices and their 2d projected values when using the pytorch3d render?
Additionally is there a way to obtain the 3d coordinates of vertices and to alter them with new ones?

Thank you

**Comment by jcjohnson** [comment]
The perceptual feature pooling from Pixel2Mesh is called `vert_align` in PyTorch3D:

https://pytorch3d.readthedocs.io/en/latest/modules/ops.html#pytorch3d.ops.vert_align

I don't think we have any built-in support for visualizing the alignment, but a quick and dirty trick is to use vert_align to sample color values from the original RGB image; this can help you debug alignment issues.

For examples of updating the 3D positions of points, I'd recommend you to check out the implementation of the Mesh Refinement Head from Mesh R-CNN:

https://github.com/facebookresearch/meshrcnn/blob/master/shapenet/modeling/heads/mesh_head.py

**Comment by ysig** [comment]
Thank you for you really informative answer!
