### ISSUE TITLE
Render an object without a texture

### ISSUE THREAD

**Issue by ysig** [facebookresearch/pytorch3d#479]
Hi,

Is there a way to render an object as a mesh, without a texture?
I tried to render the icosphere, but in the sample example you have with the cow, but I got an error related with the mesh not being assigned to its texture.

Thank you

**Comment by gkioxari** [comment]
To render objects, you need to define a texture. If you don't have one, You can define the texture to white by setting the texture rgb values to (1.0, 1.0, 1.0) for all vertices. Alternatively, you can render the object's silhouette using the `SoftSilhoutteShader` which doesn't require a texture on the mesh.

**Comment by ysig** [comment]
I will try this. Thanks a lot!

**Comment by ysig** [comment]
Sorry for opening this again but I did as you instructed and it didn't work.
So let me create a minimum reproducible example:

```
import os
import sys
import torch
import pytorch3d
import torch 
import torch.nn as nn
import numpy as np
import torch
from torch.nn import functional as F

from pytorch3d.datasets import ShapeNetCore
from pytorch3d.io import load_objs_as_meshes, load_obj, save_obj

# Data structures and functions for rendering
from pytorch3d.structures import Meshes
from pytorch3d.ops import GraphConv, SubdivideMeshes, vert_align
from pytorch3d.renderer import (
    look_at_view_transform,
    FoVPerspectiveCameras, 
    PointLights, 
    DirectionalLights, 
    Materials, 
    RasterizationSettings, 
    MeshRenderer, 
    MeshRasterizer,  
    HardPhongShader,
    TexturesUV,
    TexturesVertex,
    SoftSilhouetteShader
)
from pytorch3d.structures import Meshes
from torch.utils.data import DataLoader
from pytorch3d.datasets.shapenet_base import ShapeNetBase

from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import matplotlib as mpl
mpl.rcParams['savefig.dpi'] = 80
mpl.rcParams['figure.dpi'] = 80

class ShapeNetCat(ShapeNetBase):
  def __init__(self, data_dir, synset='02958343', version: int = 1, load_textures: bool = True, texture_resolution: int = 4):
    super().__init__()
    self.shapenet_dir = data_dir
    self.load_textures = load_textures
    self.texture_resolution = texture_resolution
    self.model_dir = "models/model_normalized.obj"
    self.synset = synset

    for model in os.listdir(os.path.join(data_dir, synset)):
        self.model_ids.append(os.path.join(data_dir, synset, model))
        self.synset_ids.append(synset)
    model_count = 0
    self.synset_num_models[synset] = model_count
    cameras = FoVPerspectiveCameras().to(device)
    self.renderer = MeshRenderer(rasterizer=MeshRasterizer(cameras=cameras, raster_settings=RasterizationSettings()),  shader=SoftSilhouetteShader(),)

  def __getitem__(self, idx):
    """
    Read a model by the given index.

    Args:
        idx: The idx of the model to be retrieved in the dataset.

    Returns:
        dictionary with following keys:
        - verts: FloatTensor of shape (V, 3).
        - faces: LongTensor of shape (F, 3) which indexes into the verts tensor.
        - synset_id (str): synset id
        - model_id (str): model id
        - label (str): synset label.
    """
    model = self._get_item_ids(idx)
    model_path = os.path.join(model["model_id"], self.model_dir)
    print('model_path', model_path)
    verts, faces, _ = self._load_mesh(model_path)
    print('verts.size()', verts.size())
    print('faces.size()', faces.size())

    mesh = Meshes(verts.unsqueeze(0).to(device), faces.unsqueeze(0).to(device)).to(device)
    return self.renderer(mesh), mesh

dataset = ShapeNetCat('shapenet-test')
image, mesh = dataset[0]
im = image.squeeze(0).cpu().numpy()
plt.imshow(im)
plt.imshow(im[:,:,[1,2,3]])
```

I get the following output for an input that should look like this:
![image](https://user-images.githubusercontent.com/28439529/101542572-9eb84780-39ab-11eb-9518-065dd18d231a.png)
which seems really wrong.

Extract the attached zip [shapenet-test.zip](https://github.com/facebookresearch/pytorch3d/files/5662008/shapenet-test.zip) which contains an obj file that looks like this: 
![image](https://user-images.githubusercontent.com/28439529/101542951-3453d700-39ac-11eb-81ab-1b409b3b9e2a.png).
I am trying to understand how I will retrieve something similar to this snapshot (even in much lower quality).

Also I don't understand how I can simply change the view of the **camera** by parameters.


I use pytorch3d==0.2.5 in GoogleCollab (as 0.3.0 doesn't yet work). And I install it by:
```
!pip install 'torch==1.6.0+cu101' -f https://download.pytorch.org/whl/torch_stable.html
!pip install 'torchvision==0.7.0+cu101' -f https://download.pytorch.org/whl/torch_stable.html
!pip install 'pytorch3d==0.2.5'
```

**Comment by gkioxari** [comment]
Can you work through the tutorials and the working examples to familiarize yourself with the library.

**Comment by ysig** [comment]
I use the exact same settings you have for ShapeNetBase render function https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/datasets/shapenet_base.py#L155 for rendering. The only thing I have changed is the shader to the one you instructed (from HardPhongShader to SoftSilhouetteShader) - so it doesn't need textures.

**Comment by gkioxari** [comment]
The output of the silhouette renderer is a NxHxWx4 tensor (N = batch size, for  you it's 1). The silhouette is in the 4th channel, so `silh = img[0, :, :, 3]`

**Comment by ysig** [comment]
This is the result I get when I take `silh = img[0, :, :, 3]`
![image](https://user-images.githubusercontent.com/28439529/101632899-301ccd80-3a2f-11eb-934b-5c1306f39e54.png)

**Comment by jasonyzhang** [comment]
It looks like some of the faces in the mesh have normals that are oriented in the wrong direction. You can fix this in MeshLab

**Comment by nikhilaravi** [comment]
@ysig glad you got it working from following the tutorial. @jasonyzhang thanks for jumping in to help! The faces are all expected to be wound in an anticlockwise manner in the `.obj` file - if this is correct then the face normals will be automatically calculated correctly in the `Meshes` datastructure.
