### ISSUE TITLE
A small typo on website "pytorch3d.org/tutorials"

### ISSUE THREAD

**Issue by rlawns324** [facebookresearch/pytorch3d#48]
I found a small typo on [pytorch3d.org tutorial](https://pytorch3d.org/tutorials/)

<img width="950" alt="Screen Shot 2020-02-11 at 9 14 25 PM" src="https://user-images.githubusercontent.com/28533936/74236521-bafc4100-4d14-11ea-8b01-f2ad1562ad4a.png">
As I mentioned on screenshot above, 
the command   

`!pip install 'git+https://github.com/facebookresearch/pytorch3d.git`  
should be fixed to
` !pip install 'git+https://github.com/facebookresearch/pytorch3d.git'`  
or
` !pip install git+https://github.com/facebookresearch/pytorch3d.git`  

I know it is such a trivial but typo is typo...

**Comment by nikhilaravi** [comment]
Thanks for raising this as an issue. This change has already been made and we will update the website soon!
