### ISSUE TITLE
MeshRenderer.to(device) does not return self

### ISSUE THREAD

**Issue by tomforge** [facebookresearch/pytorch3d#481]
`MeshRenderer`, the various shaders and rasterizers all override the `to` function of `nn.Module`, but do not return `self`, which causes code like ```self.renderer = MeshRenderer(...).to(device)``` to break.

This seems to be against prevailing conventions of `to` as defined in `Tensor` and `nn.Module`

**Comment by nikhilaravi** [comment]
@tomforge we will update it to return `self`.  If you are blocked you can use the inplace version e.g. 
```
renderer = MeshRenderer(...)
renderer.to(device)
```

Note that you can actually specify the device directly when initializing the rasterizer and the shader which are the two input args for the `MeshRenderer` so you don't have to call the `.to` method on initialization of the `MeshRenderer`.

**Comment by nikhilaravi** [comment]
This has now been fixed.
