### ISSUE TITLE
Does the rendering lose the aspect ratio and many shape details? 

### ISSUE THREAD

**Issue by cmis91** [facebookresearch/pytorch3d#482]
I used a 3D scanner to scan a teapot and rendered it using Blender and Pytorch3d respectively. 
Blender render: 
![teapot_on_table4](https://user-images.githubusercontent.com/9816523/101845549-cfab9000-3b03-11eb-8446-66b51b54138b.png)
Pytorch3D render
![image](https://user-images.githubusercontent.com/9816523/101846051-f6b69180-3b04-11eb-9913-26e2035c7cbf.png)

1) why does rasterization rendering have such a low resolution and lose a lot of teapot details? I am using faces_per_pixel=100. Are there any knobs I need to turn to make it better? 
2) No matter what image size/ aspect ratio I specify, why does it always return a squeezed square teapot? Any parameters I miss here? 

Thank you in advance.

**Comment by gkioxari** [comment]
You don't specify the settings you are using to render, such as the shader type, blend parameters the lighting position, etc etc. These details are extremely important when rendering. 

Could you provide the file of the scanned teapot so that we could look into it?

**Comment by cmis91** [comment]
Please see the attached .obj file. I indeed didn't pay attention to choose the right shader or lighting. Without too much knowledge about computer graphics, what common setup is generally sufficient for an amateur to view the 3d model scanned from a real object with fidelity? 

Also, is there a way to prevent squeezing the teapot to a square in the rendered image (preserve the aspect ratio)? 
You may use the following camera and pose to render the image above after you load the teapot .obj file. I appreciate your kind help here. 
```
cameras = PerspectiveCameras(focal_length=827,image_size=((640, 480),),principal_point=((320,240),),device=device)
R= euler_angles_to_matrix(torch.tensor([2.18166,0,0],dtype=torch.float32,device=device),"XYZ")
T=torch.tensor([0, 0,350],dtype=torch.float32,device=device)
```
[teapot.obj.zip](https://github.com/facebookresearch/pytorch3d/files/5677426/teapot.obj.zip)

**Comment by gkioxari** [comment]
Here is the teapot rendered with PyTorch3D

![teapot](https://user-images.githubusercontent.com/4369065/101937870-4776ca80-3b97-11eb-9499-8db85449e883.png)

and the code to reproduce it. Play around with the lighting position if you want to get 

```python
device = torch.device("cuda:1")

obj_filename = "/tmp/output/teapot.obj"
verts, faces, aux = load_obj(obj_filename, device=device, load_textures=False)

raster_settings = RasterizationSettings(
    image_size=640, blur_radius=0, faces_per_pixel=1
)

R = euler_angles_to_matrix(
    torch.tensor([[2.18166, 0.0, 0.0]], dtype=torch.float32, device=device), "XYZ"
)
T = torch.tensor([[0, 0, 350]], dtype=torch.float32, device=device)

lights = PointLights(
    device=device,
    location=((0.0, 30.0, 200.0),),
)

cameras = PerspectiveCameras(device=device, focal_length=3.5, R=R, T=T)
renderer = MeshRenderer(
    rasterizer=MeshRasterizer(cameras=cameras, raster_settings=raster_settings),
    shader=HardGouraudShader(device=device, lights=lights, cameras=cameras),
)

textures = TexturesVertex(
    torch.ones((1, verts.shape[0], 3), device=device, dtype=torch.float32)
)
mesh = Meshes(verts=[verts], faces=[faces.verts_idx], textures=textures)

image = renderer(mesh)

filename = "/tmp/output/teapot.png"
rgb = image[0, ..., :3].detach().squeeze().cpu()
Image.fromarray((rgb.detach().cpu().numpy() * 255).astype(np.uint8)).save(filename)
```

> Aspect ratio
Your settings in the camera caused the aspect ratio change. By defining non square image size you essentially told the camera that the NDC space corresponds to a non square view volume and thus the teapot was stretched to fit to it. The example above keeps the aspect ratio intact.

**Comment by cmis91** [comment]
Super! This is exactly what I want to see. Thank you for the quick response. Two small follow up questions: 
1. Both raster_setting and cameras have the image_size. I am confused here. Do they have to be the same? I understand that image size in raster_setting decides the resolution of the rendered image. But what's the purpose of the image_size in cameras, only to derive the fx, fy in the world coordinate? 
2. Why are the alpha channel in the rendered image all ones? Is this the nature of HardGouraudShader?

**Comment by gkioxari** [comment]
> 1. Cameras and Rasterizer
The `image_size` in the camera setting and in the rasterizer do not communicate for now. This is because currently our rasterizer only supports square image rasterization. We will add non-square rasterization soon and also connect cameras and rasterization via their parameters. Also note that our cameras by default assume intrinsics in NDC space but we support providing them in screen space (via defining `image_size`) and internally convert them to NDC. 

> 2. Alpha channel
For the `GouraudShader`, the RGB channels contain the output while the 4th channel is empty. If you need the silhoutte of the object and support for differentiability you can extend the `GouraudShader` with the output of the `SoftSilhoutteShader`.
