### ISSUE TITLE
Failed building wheel for pytorch3d in Google Colabtory

### ISSUE THREAD

**Issue by HuiXiao01** [facebookresearch/pytorch3d#483]
Hi :)

I tried pip install 'git+https://github.com/facebookresearch/pytorch3d.git@stable' in Google Colab. It has worked well until about three weeks ago but now I have been getting " ERROR: Failed building wheel for pytorch3d". Below is the full error message I get on Google Colab. I also tried pip install 'git+https://github.com/facebookresearch/pytorch3d.git' but I have been getting the same error message. Is there any way I can get pytorch3D work on my Google Colab again? Thank you!

Building wheels for collected packages: pytorch3d, fvcore, pyyaml, iopath
  Building wheel for pytorch3d (setup.py) ... error
  ERROR: Failed building wheel for pytorch3d
  Running setup.py clean for pytorch3d
  Building wheel for fvcore (setup.py) ... done
  Created wheel for fvcore: filename=fvcore-0.1.2.post20201213-cp36-none-any.whl size=40711 sha256=430a1d1f7b5d09b1b50ed37d158ab675bf7e043eead676e9ce6e0d11da3ddfe1
  Stored in directory: /root/.cache/pip/wheels/20/eb/f9/b537cf42e3b4c57fe2a49aecad264c775df2d89e0ffbf5b17d
  Building wheel for pyyaml (setup.py) ... done
  Created wheel for pyyaml: filename=PyYAML-5.3.1-cp36-cp36m-linux_x86_64.whl size=44620 sha256=f1d33f0cc0b480b0e56cfc2a0830b4be83b89ffaad300fab4dcdf840b56f5fbf
  Stored in directory: /root/.cache/pip/wheels/a7/c1/ea/cf5bd31012e735dc1dfea3131a2d5eae7978b251083d6247bd
  Building wheel for iopath (setup.py) ... done
  Created wheel for iopath: filename=iopath-0.1.2-cp36-none-any.whl size=10505 sha256=41fa8210f7aa5a538d66dff53870f68a7f26bc7f2dd48313061b571e73e08d11
  Stored in directory: /root/.cache/pip/wheels/9e/01/e4/1b68f5a2a6b9450ea4246d91840a77e1169f7d4722d76bbc47
Successfully built fvcore pyyaml iopath
Failed to build pytorch3d
Installing collected packages: pyyaml, yacs, portalocker, iopath, fvcore, pytorch3d
  Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13
    Running setup.py install for pytorch3d ... error
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-44dtbcex/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-44dtbcex/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-4ala4um8/install-record.txt --single-version-externally-managed --compile Check the logs for full command output

**Comment by bottler** [comment]
Are you using one of our tutorials or your own notebook? The latest pytorch3d (0.3.0) has a new build-time dependency, nvidia cub. The code for installing it from source in a colab notebook now looks as follows (this is copied from our tutorials). 

```
import os
!curl -LO https://github.com/NVIDIA/cub/archive/1.10.0.tar.gz
!tar xzf 1.10.0.tar.gz
os.environ["CUB_HOME"] = os.getcwd() + "/cub-1.10.0"
!pip install 'git+https://github.com/facebookresearch/pytorch3d.git@stable'
```

**Comment by HuiXiao01** [comment]
Thank you for the clarification - it works! By the way, are you refering to https://github.com/facebookresearch/pytorch3d/blob/master/INSTALL.md for the tutorials? Thank you!

**Comment by bottler** [comment]
By "tutorials", I mean any of the notebooks we provide [here](https://github.com/facebookresearch/pytorch3d/tree/stable/docs/tutorials). They are also directly linked on pytorch3d.org.

**Comment by lelouedec** [comment]
Hi, 

I am encountering a similar error. I switched from colab to colab pro+ and suddenly it was impossible to import pytorch3d and build it. I am getting the following errors : 

```
Building wheels for collected packages: pytorch3d, fvcore
  Building wheel for pytorch3d (setup.py) ... error
  ERROR: Failed building wheel for pytorch3d
```


and 


`ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-mwcebagf/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-mwcebagf/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-gga0i4mf/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7/pytorch3d Check the logs for full command output.`

I am importing/installing the same way as it is done in the tutorials, like : 
```

need_pytorch3d=False
try:
    import pytorch3d
except ModuleNotFoundError:
    need_pytorch3d=True
print(torch.__version__)
if need_pytorch3d:
    if torch.__version__.startswith("1.10.") and sys.platform.startswith("linux"):
        # We try to install PyTorch3D via a released wheel.
        pyt_version_str=torch.__version__.split("+")[0].replace(".", "")
        version_str="".join([
            f"py3{sys.version_info.minor}_cu",
            torch.version.cuda.replace(".",""),
            f"_pyt{pyt_version_str}"
        ])
        !pip install fvcore iopath
        !pip install --no-index --no-cache-dir pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/{version_str}/download.html
    else:
        # We try to install PyTorch3D from source.
        !curl -LO https://github.com/NVIDIA/cub/archive/1.10.0.tar.gz
        !tar xzf 1.10.0.tar.gz
        os.environ["CUB_HOME"] = os.getcwd() + "/cub-1.10.0"
        !pip install 'git+https://github.com/facebookresearch/pytorch3d.git@stable'
```
