### ISSUE TITLE
multiple light sources for a single rendering

### ISSUE THREAD

**Issue by ajhamdi** [facebookresearch/pytorch3d#485]
is it possible to add **multiple** light sources in the same scene rendering a single image by the `pytorch3d.renderer.MeshRenderer` class?

**Comment by nikhilaravi** [comment]
Hi @ajhamdi, currently we don't have support for this feature!

**Comment by nikhilaravi** [comment]
This is a duplicate of #241. I'll close this task - please follow the discussion on the other task.
