### ISSUE TITLE
Image feature detection module 

### ISSUE THREAD

**Issue by andrewldesousa** [facebookresearch/pytorch3d#487]
## 🚀 Image feature detection module 
Image feature detection module (for example, Shi & Tomasi and FAST)

## Motivation
Image features detection is used in MVG to match corresponding points in order to apply some classical techniques in 3D reconstruction

**Comment by andrewldesousa** [comment]
Also, a comment was made earlier about releasing the road map for PyTorch3D but I haven't been able to find it. Would it be possible to share this?

**Comment by nikhilaravi** [comment]
@andrewldesousa we didn't publish the roadmap in the end. In January we can potentially share details of the features planned for next year. 

Regarding your question about image feature detection, I'm not sure this fits into PyTorch3D as the goal of the library is to support functions specific to 3D data - could you explain more about why you would want this functionality in PyTorch3D specifically?
