### ISSUE TITLE
How to use  pytorch3d renderer

### ISSUE THREAD

**Issue by ForrestPi** [facebookresearch/pytorch3d#488]
Thanks providing the great differential renderer library.
But I met some  problems when using pytorch3d  to  train  3d face reconstruction.
![image1](https://user-images.githubusercontent.com/12846142/102455517-b6ae5c00-407a-11eb-8c49-2bb149f61f5d.png)

the rendered images looks strange

But when I use [SoftRas](https://github.com/ShichenLiu/SoftRas) ,  the rendered image looks  normal

**Comment by nikhilaravi** [comment]
@ForrestPi please provide a detailed code example with test data otherwise it is very difficult for us to provide any support.

**Comment by gkioxari** [comment]
No response. Closing this.
