### ISSUE TITLE
UnsatisfiableError on Ubuntu 18.04, with CUDA 10.1

### ISSUE THREAD

**Issue by koeglfryderyk** [facebookresearch/pytorch3d#490]
Hello,

I'm using ubuntu 18.04 and when I'm trying to install pytorch3d with `conda install pytorch3d -c pytorch3d` I get the following error:

>Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed
\
UnsatisfiableError: The following specifications were found to be incompatible with each other:
\
Output in format: Requested package -> Available versions

I already installed cudatoolkit, pytorch and torchvision. This is the output of `conda list`:
![error](https://user-images.githubusercontent.com/49393975/102728800-141e0380-432e-11eb-9932-90313753e5c3.png)

Any help would be appreciated a lot

**Comment by bottler** [comment]
The latest release 1.7.1 of pytorch, which you have, is newer than the latest release of pytorch3d, and so there isn't a release build of pytorch3d supporting it.

Our nightly builds do support PyTorch 1.7.1, so you should be able to install with `conda install -c pytorch3d-nightly pytorch3d`.
