### ISSUE TITLE
maps_padded issue in texture_image

### ISSUE THREAD

**Issue by ayush-angelium** [facebookresearch/pytorch3d#492]
## 🐛 Bugs / Unexpected behaviors

This is the code we used
```
if torch.cuda.is_available():
    device = torch.device("cuda:0")
    torch.cuda.set_device(device)
else:
    device = torch.device("cpu")

# Set paths
DATA_DIR = "./custom_data"
obj_filename = os.path.join(DATA_DIR, "man1/body.obj")  # we are loading custom obj file 

# Load obj file
mesh = load_objs_as_meshes([obj_filename], device=device)

plt.figure(figsize=(7,7))
texture_image=mesh.textures.maps_padded() # this line create an error
plt.imshow(texture_image.squeeze().cpu().numpy())
plt.grid("off");
plt.axis("off");

```
Here is the main issue when I run this code
AttributeError: 'NoneType' object has no attribute 'maps_padded'
```
Is there any idea about how to load obj, mtl and texture img for custom values.
```

**Comment by bottler** [comment]
No textures are present in `mesh` after it has been loaded. Do you get any warnings? Is there an `mtl` file?

**Comment by nikhilaravi** [comment]
@ayush-angelium yes as @bottler mentioned please check that the `.mtl` file is present at the correct location referenced in the `.obj` file and the image file used for the texture map is also available.

**Comment by ayush-angelium** [comment]
@nikhilaravi @bottler I have all files what we needed such as obj, mtl and texture file. But still I am facing that issue.

**Comment by nikhilaravi** [comment]
Can you provide a zip folder with the data so we can try to reproduce the error?

**Comment by nikhilaravi** [comment]
Closing this issue as there have been no further comments. @ayush-angelium if you still need help, please reopen the issue.

**Comment by vi-kumar** [comment]
maps_padded() method is not available at meshes.py. Pytorch3d version- 0.4.0

**Comment by bottler** [comment]
@vi-kumar If you have a question or issue about PyTorch3D please feel free to open a new issue and explain it. I am not sure what you mean. This issue is closed and is from before version 0.4.0.

**Comment by Yougrianes** [comment]
Perhaps the tutorial is still using maps_padded()，see https://pytorch3d.org/tutorials/render_textured_meshes :-<

**Comment by bottler** [comment]
@Yougrianes There is nothing wrong with that.  Again, please open a new issue for a new question. This issue is specific to a particular set of data!
