### ISSUE TITLE
Rendering Objects with Multiple Texture Images (multiple .png textures)

### ISSUE THREAD

**Issue by adelekuzmiakova** [facebookresearch/pytorch3d#493]
## ❓ Rendering Objects with Multiple Texture Images (multiple .png textures)

Hi Nikhila,

I would like to render meshes with multiple texture images (multiple .png/.jpg textures). I wasn't sure if this feature was already implemented and I looked at the past issues, like [this](https://github.com/facebookresearch/pytorch3d/issues/381), as well. In any case, I'd be so grateful for any comments or suggestions you might have on this :)  

I would like to render the following `.obj` file with its associated `.mtl` file:
- `adam-v1.obj` and `adam-v1.mtl` found [here](https://github.com/adelekuzmiakova/render-mesh-pytorch3d/tree/main/data/person)
- `adam-v1.mtl` specifies different groups with `newmtl` statement, such as `newmtl adamhead`. For every group, there's a corresponding texture image, e.g. `average head_skin_hi.jpg`

 I was doing the following:

```
import os
import torch
import matplotlib.pyplot as plt
from skimage.io import imread

# Util function for loading meshes
from pytorch3d.io import load_objs_as_meshes, load_obj

# Data structures and functions for rendering
from pytorch3d.structures import Meshes
from pytorch3d.vis.plotly_vis import AxisArgs, plot_batch_individually, plot_scene
from pytorch3d.vis.texture_vis import texturesuv_image_matplotlib
from pytorch3d.renderer import (
    look_at_view_transform,
    FoVPerspectiveCameras, 
    PointLights, 
    DirectionalLights, 
    Materials, 
    RasterizationSettings, 
    MeshRenderer, 
    MeshRasterizer,  
    SoftPhongShader,
    TexturesUV,
    TexturesVertex
)

# Set paths
DATA_DIR = "./data"
obj_filename = os.path.join(DATA_DIR, "person/adam-v1.obj")

# Load the .obj file
mesh = load_objs_as_meshes([obj_filename], load_textures = True, device=device)

# Get the texture tensor and convert it to the numpy array:
texture_image = mesh.textures.maps_padded()
texture_image_numpy = texture_image.squeeze().cpu().numpy()
```

But isn't that `texture_image` getting only the first texture?

Because when I plot this, I seem to get only the first texture image:

```
plt.figure(figsize=(10, 10))
plt.imshow(texture_image_numpy)
plt.grid("off")
```

I also render the mesh but seem to get only one texture image rendered. This code is also at the bottom of my jupyter notebook [here](https://github.com/adelekuzmiakova/render-mesh-pytorch3d/blob/main/render-meshes.ipynb):

```R, T = look_at_view_transform(dist = 3, elev = 0, azim = 0) 
cameras = FoVPerspectiveCameras(device = device, R = R, T = T)


raster_settings = RasterizationSettings(
    image_size = 256, 
    blur_radius = 0.0, 
    faces_per_pixel = 1, 
)

lights = PointLights(device=device, location=[[0.0, 0.0, -3.3]])

images = renderer(mesh, cameras = cameras)
plt.figure(figsize=(10, 10))
plt.imshow(images[0, ..., :3].cpu().numpy())
plt.grid("off")

```
When I try to render different texture images in Blender, I have to select each group (e.g. head or eye and change the base color individually for each group). Here is a [screenshot](https://github.com/adelekuzmiakova/render-mesh-pytorch3d/blob/main/data/person/blender-multiple-textures.pdf) from my Blender and this is what I would want the meshes to look like.

Is there a way I can do this in PyTorch3D? If you have any comments or thoughts on this, I'd be grateful!!

Or do I have to supply exactly one texture image? I think in Blender there is a way to bake different textures together.

In any case, thank you very much for any comments or thoughts you might have :)

**Comment by nikhilaravi** [comment]
Hi @adelekuzmiakova thanks for explaining your question in detail and providing a code example. Currently the `TexturesUV` class only supports a single texture map per mesh - so this is only suitable for the case where you have one texture map in the `.mtl` file. 

If you want to load a mesh which contains multiple texture maps then you need to use the `TextureAtlas` format - this will create an `RxR` texture map per face in the mesh and can be constructed from multiple texture maps. 
The different texturing options are explained [here](https://github.com/facebookresearch/pytorch3d/blob/master/docs/notes/renderer_getting_started.md#texturing-options).

Here is an example of how to load a mesh using this format: 

```
        verts, faces, aux = load_obj(
            obj_filename,
            device=device,
            load_textures=True,
            create_texture_atlas=True,
            texture_atlas_size=8,
            texture_wrap=None,
        )
        atlas = aux.texture_atlas
        mesh = Meshes(
            verts=[verts],
            faces=[faces.verts_idx],
            textures=TexturesAtlas(atlas=[atlas]),
        )
```

Any of the texture formats can be used with the rendering pipeline without needing to make any changes to the renderer set up.

**Comment by adelekuzmiakova** [comment]
Awesome! Thank you very much for your tip and quick reply! For some reason the option in `load_obj(..., texture_wrap=None)` didn't work for me so I changed it to `load_obj(..., texture_wrap="repeat")`. Anyways, here's the full code, which produces the rendered image:

```
dist=35
elev=0
azim=90

R, T = look_at_view_transform(dist, elev, azim) 
cameras = FoVPerspectiveCameras(device=device, R=R, T=T)

lights = PointLights(device=device, location=[[1000.0, 1000.0, -500.0]])
renderer = MeshRenderer(
    rasterizer=MeshRasterizer(
        cameras=cameras, 
        raster_settings=raster_settings
    ),
    shader=SoftPhongShader(
        device=device, 
        cameras=cameras,
    )
)

DATA_DIR = "data/person"
obj_filename = os.path.join(DATA_DIR, "adam-v1.obj")

verts, faces, aux = load_obj(
    obj_filename,
    device=device,
    load_textures=True,
    create_texture_atlas=True,
    texture_atlas_size=4,
    texture_wrap="repeat",
)

atlas = aux.texture_atlas
mesh = Meshes(
    verts=[verts],
    faces=[faces.verts_idx],
    textures=TexturesAtlas(atlas=[atlas]),
)

image = renderer(mesh)
print(image.shape)

plt.figure(figsize=(10, 10))
plt.imshow(image[0, ..., :3].cpu().numpy())
plt.grid("off")
```
Data is [here](https://github.com/adelekuzmiakova/render-mesh-pytorch3d/tree/main/data/person)

<img width="527" alt="man" src="https://user-images.githubusercontent.com/16421538/103344242-5366f580-4a8e-11eb-9f53-ec9c09da6a72.png">
