### ISSUE TITLE
import error in: from pytorch3d import _C -- undefined symbol: 

### ISSUE THREAD

**Issue by DSLituiev** [facebookresearch/pytorch3d#495]
## 🐛 Bugs / Unexpected behaviors
import error in: `from pytorch3d import _C` -- undefined symbol

## Instructions To Reproduce the Issue:

Please include the following (depending on what the issue is):

Code:
```
from pytorch3d.structures import Pointclouds
from pytorch3d.renderer import (
    look_at_view_transform,
    FoVOrthographicCameras, 
    PointsRasterizationSettings,
    PointsRenderer,
    PulsarPointsRenderer,
    PointsRasterizer,
    AlphaCompositor,
    NormWeightedCompositor
)
```
Error
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-e32ed8381ff7> in <module>
     11 from pytorch3d.structures import Pointclouds
     12 # from pytorch3d.vis.plotly_vis import AxisArgs, plot_batch_individually, plot_scene
---> 13 from pytorch3d.renderer import (
     14     look_at_view_transform,
     15     FoVOrthographicCameras,

~/.conda/envs/torch3d/lib/python3.7/site-packages/pytorch3d/renderer/__init__.py in <module>
      1 # Copyright (c) Facebook, Inc. and its affiliates. All rights reserved.
      2 
----> 3 from .blending import (
      4     BlendParams,
      5     hard_rgb_blend,

~/.conda/envs/torch3d/lib/python3.7/site-packages/pytorch3d/renderer/blending.py in <module>
      7 
      8 # pyre-fixme[21]: Could not find name `_C` in `pytorch3d`.
----> 9 from pytorch3d import _C
     10 
     11 

ImportError: /home/dlituiev/.conda/envs/torch3d/lib/python3.7/site-packages/pytorch3d/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c104impl23ExcludeDispatchKeyGuardC1ENS_11DispatchKeyE
```
##Environment:
- Ubuntu 20.04
- conda
- python3.7
- cudatoolkit=11.0.3
- `pip install pytorch3d`

**Comment by DSLituiev** [comment]
I saw [this issue](https://github.com/facebookresearch/pytorch3d/issues/161) and tried to install from conda repository to no avail:
```
 conda install -c pytorch3d pytorch3d
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                       

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pytorch3d -> python[version='>=2.7,<2.8.0a0|>=3.9,<3.10.0a0|>=3.5,<3.6.0a0']

Your python: python=3.7

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.
```

**Comment by DSLituiev** [comment]
same error comes up for `python=3.8` and `3.9`

**Comment by bottler** [comment]
This is a bit complicated. If you paste the output of `conda list` and `pip list` I could be more specific. The obvious question is what version of PyTorch do you have, and how is it installed?

`pip install pytorch3d` will never be a good idea unless you have exactly the right CUDA and PyTorch versions specified in INSTALL.md, which you don't.

If you have the latest PyTorch, i.e. 1.7.1, then you won't be able to install or use binaries from the latest release of PyTorch3D, which is older than PyTorch 1.7.1. You would need to either build from source or install a nightly build with `conda install -c pytorch3d-nightly pytorch3d`.

If you have PyTorch 1.7.0 and you have installed the other dependencies of PyTorch3D via conda, then it isn't obvious to me why `conda install -c pytorch3d pytorch3d`.

Note that the error messages of the conda solver can be quite remote from what we would consider the problem to be.

**Comment by DSLituiev** [comment]
This time I'm starting fresh:

`conda list`

``
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
ca-certificates           2020.12.8            h06a4308_0  
certifi                   2020.12.5        py39h06a4308_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
ncurses                   6.2                  he6710b0_1  
openssl                   1.1.1i               h27cfd23_0  
pip                       20.3.3           py39h06a4308_0  
python                    3.9.1                hdb3f193_2  
readline                  8.0                  h7b6447c_0  
setuptools                51.0.0           py39h06a4308_2  
sqlite                    3.33.0               h62c20be_0  
tk                        8.6.10               hbc83047_0  
tzdata                    2020d                h14c3975_0  
wheel                     0.36.2             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  
```
`pip list`

```
---------- -------------------
certifi    2020.12.5
pip        20.3.3
setuptools 51.0.0.post20201207
wheel      0.36.2
```

**Comment by bottler** [comment]
I assume you still have cuda 11.0.3 and it is installed properly. Do you need Python 3.9? It would be much easier if you could start again in a Python 3.8 environment. There are no release builds of PyTorch3D against Python 3.9, because the latest PyTorch3D release is older than PyTorch 1.7.1, which is the first PyTorch to support Python 3.9.

You should be able to use the following sequence of commands to start from scratch in a new environment, just like in INSTALL.md

```
conda create -n pytorch3d python=3.8
conda activate pytorch3d
conda install -c pytorch pytorch=1.7.0 torchvision cudatoolkit=11.0
conda install -c conda-forge -c iopath fvcore iopath
conda install -c pytorch3d pytorch3d
```

If you need python 3.9, then you can start in your current environment, but it'll be complicated. Maybe
```
conda install -c pytorch pytorch=1.7.0 torchvision cudatoolkit=11.0
pip install fvcore 
```
will get the dependencies. But right now you won't be able to get fvcore from conda. Then you would proceed with building pytorch3d from source (start by installing CUB).

**Comment by DSLituiev** [comment]
this worked. Thank you!
I don't need python 3.9, but as it complained about 3.7 and 3.8, I went all the way up.

However, I couldn't find pulsar backend and decided to update to a nightly release -- and now getting the same error that the python version is not supported. It sounds like this is a misleading error message about the Python version -- something else is happening here

**Comment by DSLituiev** [comment]
I've noticed that `conda` has been using a package from `~/.local/lib/python3.8/site-packages/pytorch3d/`. I removed that folder, removed the whole environment: `conda env remove -n pytorch3d` and reinstalled it again

```
conda create -n pytorch3d python=3.8
conda activate pytorch3d
conda install -c pytorch pytorch=1.7.0 torchvision cudatoolkit=11.0
conda install -c conda-forge -c iopath fvcore iopath
conda install -c pytorch3d pytorch3d
```

unfortunately I am running again into the import error `from pytorch3d import _C`
```
ImportError: ~/.conda/envs/pytorch3d/lib/python3.8/site-packages/pytorch3d/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda12device_countEv
```

**Comment by bottler** [comment]
Does that mean you are sorted? It sounds like a step happened outside the environment and the base environment got involved, which causes confusion.

**Comment by DSLituiev** [comment]
it's sorted out. thank you.
not sure whether this is the conda environment issue, but off-the-shelf conda package didn't work.

**Comment by bobiblazeski** [comment]
I'm having a same problem installing pytorch3d on a fresh environment fallowing installation  instructions:

> conda create -n pytorch3d python=3.8
> conda activate pytorch3d
> conda install -c pytorch pytorch=1.7.0 torchvision cudatoolkit=10.2
> conda install -c conda-forge fvcore iopath

It complains about python version being 3.8

> (pytorch3d) bobi@strix:~/Desktop/po$ conda install pytorch3d -c pytorch3d
> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: \ 
> Found conflicts! Looking for incompatible packages.
> This can take several minutes.  Press CTRL-C to abort.
> failed                                                                                                                          
> 
> UnsatisfiableError: The following specifications were found
> to be incompatible with the existing python installation in your environment:
> 
> Specifications:
> 
>   - pytorch3d -> python[version='>=2.7,<2.8.0a0|>=3.9,<3.10.0a0|>=3.5,<3.6.0a0']
> 
> Your python: python=3.8
> 
> If python is on the left-most side of the chain, that's the version you've asked for.
> When python appears to the right, that indicates that the thing on the left is somehow
> not available for the python version you are constrained to. Note that conda will not
> change your python version to a different minor version unless you explicitly specify
> that.

The result of conda list 

> (pytorch3d) bobi@strix:~/Desktop/po$ conda list
> # packages in environment at /home/bobi/miniconda3/envs/pytorch3d:
> #
> # Name                    Version                   Build  Channel
> _libgcc_mutex             0.1                        main  
> blas                      1.0                         mkl  
> ca-certificates           2020.12.8            h06a4308_0  
> certifi                   2020.12.5        py38h06a4308_0  
> cudatoolkit               10.2.89              hfd86e86_1  
> freetype                  2.10.4               h5ab3b9f_0  
> intel-openmp              2020.2                      254  
> jpeg                      9b                   h024ee3a_2  
> lcms2                     2.11                 h396b838_0  
> ld_impl_linux-64          2.33.1               h53a641e_7  
> libedit                   3.1.20191231         h14c3975_1  
> libffi                    3.3                  he6710b0_2  
> libgcc-ng                 9.1.0                hdf63c60_0  
> libpng                    1.6.37               hbc83047_0  
> libstdcxx-ng              9.1.0                hdf63c60_0  
> libtiff                   4.1.0                h2733197_1  
> libuv                     1.40.0               h7b6447c_0  
> lz4-c                     1.9.2                heb0550a_3  
> mkl                       2020.2                      256  
> mkl-service               2.3.0            py38he904b0f_0  
> mkl_fft                   1.2.0            py38h23d657b_0  
> mkl_random                1.1.1            py38h0573a6f_0  
> ncurses                   6.2                  he6710b0_1  
> ninja                     1.10.2           py38hff7bd54_0  
> numpy                     1.19.2           py38h54aff64_0  
> numpy-base                1.19.2           py38hfa32c7d_0  
> nvidiacub                 1.10.0                        0    bottler
> olefile                   0.46                       py_0  
> openssl                   1.1.1i               h27cfd23_0  
> pillow                    8.1.0            py38he98fc37_0  
> pip                       20.3.3           py38h06a4308_0  
> python                    3.8.5                h7579374_1  
> pytorch                   1.7.0           py3.8_cuda10.2.89_cudnn7.6.5_0    pytorch
> readline                  8.0                  h7b6447c_0  
> setuptools                51.1.2           py38h06a4308_4  
> six                       1.15.0           py38h06a4308_0  
> sqlite                    3.33.0               h62c20be_0  
> tk                        8.6.10               hbc83047_0  
> torchvision               0.8.1                py38_cu102    pytorch
> typing_extensions         3.7.4.3                    py_0  
> wheel                     0.36.2             pyhd3eb1b0_0  
> xz                        5.2.5                h7b6447c_0  
> zlib                      1.2.11               h7b6447c_3  
> zstd                      1.4.5                h9ceee32_0

**Comment by bottler** [comment]
@bobiblazeski Please open a new issue if you have a new problem. You're symptom is nothing to do with this issue anyway.

The previous lines you ran probably did not succeed. Notice that you say you ran `conda install -c conda-forge fvcore iopath` but neither fvcore and iopath are present in your conda list.

**Comment by basujindal** [comment]
This is my output of conda list and **it works, no error**.

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
blas                      1.0                         mkl  
ca-certificates           2021.4.13            h06a4308_1  
certifi                   2020.12.5        py38h06a4308_0  
cudatoolkit               10.2.89              hfd86e86_1  
cycler                    0.10.0                   py38_0  
dbus                      1.13.18              hb2f20db_0  
expat                     2.4.1                h2531618_2  
fontconfig                2.13.1               h6c09931_0  
freetype                  2.10.4               h5ab3b9f_0  
future                    0.18.2                   pypi_0    pypi
fvcore                    0.1.5.post20210518            py38    fvcore
glib                      2.68.2               h36276a3_0  
gst-plugins-base          1.14.0               h8213a91_2  
gstreamer                 1.14.0               h28cd5cc_2  
icu                       58.2                 he6710b0_3  
intel-openmp              2021.2.0           h06a4308_610  
iopath                    0.1.8                      py38    iopath
jpeg                      9b                   h024ee3a_2  
kiwisolver                1.3.1            py38h2531618_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_1  
libuuid                   1.0.3                h1bed415_2  
libuv                     1.40.0               h7b6447c_0  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.10               hb55368b_3  
lz4-c                     1.9.3                h2531618_0  
matplotlib                3.3.4            py38h06a4308_0  
matplotlib-base           3.3.4            py38h62a2d02_0  
mkl                       2021.2.0           h06a4308_296  
mkl-service               2.3.0            py38h27cfd23_1  
mkl_fft                   1.3.0            py38h42c9631_2  
mkl_random                1.2.1            py38ha9443f7_2  
ncurses                   6.2                  he6710b0_1  
ninja                     1.10.2               hff7bd54_1  
numpy                     1.20.2           py38h2d18471_0  
numpy-base                1.20.2           py38hfae3a4d_0  
nvidiacub                 1.10.0                        0    bottler
olefile                   0.46                       py_0  
openssl                   1.1.1k               h27cfd23_0  
pandas                    1.2.4            py38h2531618_0  
pcre                      8.44                 he6710b0_0  
pillow                    8.2.0            py38he98fc37_0  
pip                       21.1.1           py38h06a4308_0  
portalocker               1.7.0            py38h578d9bd_1    conda-forge
pyparsing                 2.4.7              pyhd3eb1b0_0  
pyqt                      5.9.2            py38h05f1152_4  
python                    3.8.10               hdb3f193_7  
python-dateutil           2.8.1              pyhd3eb1b0_0  
python_abi                3.8                      1_cp38    conda-forge
pytorch3d                 0.2.5                    pypi_0    pypi
pytz                      2021.1             pyhd3eb1b0_0  
pyyaml                    5.3.1            py38h8df0ef7_1    conda-forge
qt                        5.9.7                h5867ecd_1  
readline                  8.1                  h27cfd23_0  
setuptools                52.0.0           py38h06a4308_0  
sip                       4.19.13          py38he6710b0_0  
six                       1.15.0           py38h06a4308_0  
sqlite                    3.35.4               hdfb4753_0  
tabulate                  0.8.9              pyhd8ed1ab_0    conda-forge
termcolor                 1.1.0                      py_2    conda-forge
tk                        8.6.10               hbc83047_0  
torch                     1.6.0+cu101              pypi_0    pypi
torchvision               0.7.0+cu101              pypi_0    pypi
tornado                   6.1              py38h27cfd23_0  
tqdm                      4.61.0             pyhd8ed1ab_0    conda-forge
typing_extensions         3.7.4.3            pyha847dfd_0  
wheel                     0.36.2             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
yacs                      0.1.6                      py_0    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.9                haebb681_0  

I have downgraded pytorch to 1.6.0+cu101 using these commands.

conda create -n pytorch3d python=3.8
conda activate pytorch3d
conda install -c fvcore -c iopath -c conda-forge fvcore iopath

pip install 'torch==1.6.0+cu101' -f https://download.pytorch.org/whl/torch_stable.html
pip install 'torchvision==0.7.0+cu101' -f https://download.pytorch.org/whl/torch_stable.html
pip install 'pytorch3d==0.2.5'

And output of nvidia-smi:
NVIDIA-SMI 460.73.01    Driver Version: 460.73.01    CUDA Version: 11.2

**Comment by bottler** [comment]
@basujindal I am afraid I don't understand what you are saying. This issue is closed. Are you following up on it? Are you asking a question / reporting something new (e.g. that you are seeing a similar error)? If so, please open a new issue.

For everyone else: please don't comment on this issue unless you are sure you want to talk directly about this issue, which is very unlikely. If you want to talk about an error you are seeing, open a new issue!

**Comment by basujindal** [comment]
> @basujindal I am afraid I don't understand what you are saying. This issue is closed. Are you following up on it? Are you asking a question / reporting something new (e.g. that you are seeing a similar error)? If so, please open a new issue.
> 
> For everyone else: please don't comment on this issue unless you are sure you want to talk directly about this issue, which is very unlikely. If you want to talk about an error you are seeing, open a new issue!

I was facing the same issue but none of the solutions mentioned here worked for me, so after a few tries I got it to work, and thought I should comment about how it was fixed for me, it may help someone facing the same issue.
