### ISSUE TITLE
pulsar render core dumped

### ISSUE THREAD

**Issue by sxsong1207** [facebookresearch/pytorch3d#496]
## 🐛 Bugs / Unexpected behaviors

I have created conda env following INSALL.md from  scratch. All features of pytorch3d look good except the last section **Using the pulsar backend** of render_colored_points.ipynb. The jupyter said kernel been shutdown without any useful error message.

I download some python scripts from the repo and data, see it in below. **[1]    3454 floating point exception (core dumped)  python pulsar_optimization.py** is the only message I got. The exception was raised from renderer() function.

My system: Linux Mint(20) equivalent to Ubuntu 20.04 LTS Kernel 5.4.0-58-generic
Conda w/ python 3.7 (3.8) both not working.

Other functions working.
  
## Instructions To Reproduce the Issue:

$ python pulsar_multiview.py 
INFO:__main__:Loading reference...
INFO:__main__:Writing video to `multiview.avi`.
**[1]    2954 floating point exception (core dumped)  python pulsar_multiview.py**
 
$ python pulsar_optimization.py 
INFO:__main__:Loading reference...
INFO:__main__:Optimizing...
**[1]    3454 floating point exception (core dumped)  python pulsar_optimization.py**

$ python pulsar_basic.py 
INFO:__main__:Rendering on GPU...
INFO:__main__:Writing image to `basic.png`.
INFO:__main__:Done.

**Comment by classner** [comment]
I have no idea what would cause this. @bottler, this is probably a similar build issue. Does this happen on CPU as well as GPU? Are we maybe not building the for the correct instruction set of the GPU at hand (@sxsong1207 which GPU model is this?)? Did you try using the conda-built version as well?

**Comment by bottler** [comment]
Looking at that error message online, it seems to come from undefined behavior in numerical C++ code on the CPU. Even though it says "floating point", it can come from integer division by 0.
