### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by LuckyDC** [facebookresearch/pytorch3d#497]
Hello,
I am using pytorch 1.7.1 and cudatoolkit 10.2. The installation is failed when I install pytorch3d by `conda install -c pytorch3d-nightly pytorch3d`, 
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                     

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.23=0
  - pytorch3d -> cudatoolkit[version='>=11.0,<11.1'] -> __glibc[version='>=2.17,<3.0.a0']

Your installed version is: 2.23
```

**Comment by bottler** [comment]
If you are using python 3.9 in the environment, can you try again in a python 3.8 environment? If this is python 3.9 I would expect something to go wrong.

Otherwise, can you paste the output of `conda list`?

**Comment by LuckyDC** [comment]
Here is the output of conda list. I am using python3.6. I downgrade pytorch to 1.7.0 and succeed to install pytorch3d from stable channel. However, the installation still fails from pytorch3d-nightly channel
```
# packages in environment at /home/chuanchen_luo/anaconda3/envs/3d-vision:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
absl-py                   0.11.0                   pypi_0    pypi
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
blas                      1.0                         mkl    defaults
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
cachetools                4.2.0                    pypi_0    pypi
cairo                     1.14.12              he6fea26_5    conda-forge
certifi                   2020.12.5        py36h5fab9bb_0    conda-forge
chardet                   4.0.0                    pypi_0    pypi
chumpy                    0.69                     pypi_0    pypi
coolname                  1.1.0                    pypi_0    pypi
cudatoolkit               10.2.89              h8f6ccaa_6    conda-forge
dataclasses               0.7                pyhe4b4509_6    conda-forge
decorator                 4.4.2                      py_0    conda-forge
easydict                  1.9                      pypi_0    pypi
efficientnet-pytorch      0.6.3                    pypi_0    pypi
ffmpeg                    4.0.2                ha0c5888_2    conda-forge
fontconfig                2.13.1            he4413a7_1000    conda-forge
freeglut                  3.2.1                h58526e2_0    conda-forge
freetype                  2.10.4               h7ca028e_0    conda-forge
future                    0.18.2                   pypi_0    pypi
gettext                   0.19.8.1          h0b5b191_1005    conda-forge
glib                      2.55.0                        0    conda-forge
gmp                       6.1.2             hf484d3e_1000    conda-forge
gnutls                    3.5.19               h2a4e5f8_1    conda-forge
google-auth               1.24.0                   pypi_0    pypi
google-auth-oauthlib      0.4.2                    pypi_0    pypi
graphite2                 1.3.13            h58526e2_1001    conda-forge
grpcio                    1.34.0                   pypi_0    pypi
harfbuzz                  1.9.0                h08d66d9_0    conda-forge
hdf5                      1.10.2               hc401514_3    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.10                     pypi_0    pypi
imageio                   2.9.0                    pypi_0    pypi
importlib-metadata        3.3.0                    pypi_0    pypi
iopath                    0.1.2                    pypi_0    pypi
ipython                   7.12.0           py36h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jasper                    2.0.14               habb8e15_1    conda-forge
jedi                      0.18.0           py36h5fab9bb_1    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
kaolin                    0.9.0                     dev_0    <develop>
kornia                    0.4.1                    pypi_0    pypi
lcms2                     2.11                 hcbb858e_1    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_1    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h5dbcf3e_17    conda-forge
libgfortran               3.0.0                         1    conda-forge
libglu                    9.0.0             he1b5a44_1001    conda-forge
libiconv                  1.15              h516909a_1006    conda-forge
libopencv                 3.4.2                hb342d67_1    defaults
libpng                    1.6.37               h21135ba_2    conda-forge
libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
libtiff                   4.2.0                hdc55705_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libuv                     1.40.0               h7f98852_0    conda-forge
libwebp-base              1.1.0                h36c2ea0_3    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.9                h13577e0_2    conda-forge
llvm-openmp               11.0.0               hfc4b9b4_1    conda-forge
lz4-c                     1.9.2                he1b5a44_3    conda-forge
markdown                  3.3.3                    pypi_0    pypi
mkl                       2020.4             h726a3e6_304    conda-forge
mkl-service               2.3.0            py36h8c4c3a4_2    conda-forge
mkl_fft                   1.2.0            py36h68bb277_1    conda-forge
mkl_random                1.2.0            py36h7c3b610_1    conda-forge
munch                     2.5.0                    pypi_0    pypi
ncurses                   6.2                  h58526e2_4    conda-forge
nettle                    3.3                           0    conda-forge
ninja                     1.10.2               h4bd325d_0    conda-forge
numpy                     1.19.2           py36h54aff64_0    defaults
numpy-base                1.19.2           py36hfa32c7d_0    defaults
oauthlib                  3.1.0                    pypi_0    pypi
olefile                   0.46               pyh9f0ad1d_1    conda-forge
opencv                    3.4.2            py36h6fd60c2_1    defaults
openh264                  1.8.0             hdbcaa40_1000    conda-forge
openssl                   1.1.1i               h7f98852_0    conda-forge
parso                     0.8.1              pyhd8ed1ab_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.0.1            py36h10ecd5c_0    conda-forge
pip                       20.3.3             pyhd8ed1ab_0    conda-forge
pixman                    0.34.0            h14c3975_1003    conda-forge
pretrainedmodels          0.7.4                    pypi_0    pypi
prompt-toolkit            3.0.8              pyha770c72_0    conda-forge
prompt_toolkit            3.0.8                hd8ed1ab_0    conda-forge
protobuf                  3.14.0                   pypi_0    pypi
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py-opencv                 3.4.2            py36hb342d67_1    defaults
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pygments                  2.7.3              pyhd8ed1ab_0    conda-forge
python                    3.6.12          hffdb5ce_0_cpython    conda-forge
python_abi                3.6                     1_cp36m    conda-forge
pytorch                   1.7.0           py3.6_cuda10.2.89_cudnn7.6.5_0    pytorch
readline                  8.0                  he28a2e2_2    conda-forge
requests                  2.25.1                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.6                      pypi_0    pypi
runx                      0.0.10                   pypi_0    pypi
scipy                     1.5.2                    pypi_0    pypi
segmentation-models-pytorch 0.1.3                    pypi_0    pypi
setuptools                49.6.0           py36h9880bd3_2    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
smplx                     0.1.26                   pypi_0    pypi
sqlite                    3.34.0               h74cdb3f_0    conda-forge
tensorboard               2.4.0                    pypi_0    pypi
tensorboard-plugin-wit    1.7.0                    pypi_0    pypi
tensorboardx              2.1                      pypi_0    pypi
timm                      0.3.2                    pypi_0    pypi
tk                        8.6.10               h21135ba_1    conda-forge
torchaudio                0.7.0                      py36    pytorch
torchgeometry             0.1.2                    pypi_0    pypi
torchvision               0.8.1                py36_cu102    pytorch
tqdm                      4.55.0                   pypi_0    pypi
traitlets                 4.3.3            py36h9f0ad1d_1    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
urllib3                   1.26.2                   pypi_0    pypi
usd-core                  20.11                    pypi_0    pypi
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
x264                      1!152.20180806       h14c3975_0    conda-forge
xorg-fixesproto           5.0               h14c3975_1002    conda-forge
xorg-inputproto           2.3.2             h14c3975_1002    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.12               h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxfixes            5.0.3             h516909a_1004    conda-forge
xorg-libxi                1.7.10               h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zipp                      3.4.0                    pypi_0    pypi
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.5                h6597ccf_2    conda-forge
```

**Comment by ZhiyuanChen** [comment]
> Here is the output of conda list. I am using python3.6. I downgrade pytorch to 1.7.0 and succeed to install pytorch3d from stable channel. However, the installation still fails from pytorch3d-nightly channel
> 
> ```
> # packages in environment at /home/chuanchen_luo/anaconda3/envs/3d-vision:
> #
> # Name                    Version                   Build  Channel
> _libgcc_mutex             0.1                 conda_forge    conda-forge
> _openmp_mutex             4.5                      1_llvm    conda-forge
> absl-py                   0.11.0                   pypi_0    pypi
> backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
> backports                 1.0                        py_2    conda-forge
> backports.functools_lru_cache 1.6.1                      py_0    conda-forge
> blas                      1.0                         mkl    defaults
> bzip2                     1.0.8                h7f98852_4    conda-forge
> ca-certificates           2020.12.5            ha878542_0    conda-forge
> cachetools                4.2.0                    pypi_0    pypi
> cairo                     1.14.12              he6fea26_5    conda-forge
> certifi                   2020.12.5        py36h5fab9bb_0    conda-forge
> chardet                   4.0.0                    pypi_0    pypi
> chumpy                    0.69                     pypi_0    pypi
> coolname                  1.1.0                    pypi_0    pypi
> cudatoolkit               10.2.89              h8f6ccaa_6    conda-forge
> dataclasses               0.7                pyhe4b4509_6    conda-forge
> decorator                 4.4.2                      py_0    conda-forge
> easydict                  1.9                      pypi_0    pypi
> efficientnet-pytorch      0.6.3                    pypi_0    pypi
> ffmpeg                    4.0.2                ha0c5888_2    conda-forge
> fontconfig                2.13.1            he4413a7_1000    conda-forge
> freeglut                  3.2.1                h58526e2_0    conda-forge
> freetype                  2.10.4               h7ca028e_0    conda-forge
> future                    0.18.2                   pypi_0    pypi
> gettext                   0.19.8.1          h0b5b191_1005    conda-forge
> glib                      2.55.0                        0    conda-forge
> gmp                       6.1.2             hf484d3e_1000    conda-forge
> gnutls                    3.5.19               h2a4e5f8_1    conda-forge
> google-auth               1.24.0                   pypi_0    pypi
> google-auth-oauthlib      0.4.2                    pypi_0    pypi
> graphite2                 1.3.13            h58526e2_1001    conda-forge
> grpcio                    1.34.0                   pypi_0    pypi
> harfbuzz                  1.9.0                h08d66d9_0    conda-forge
> hdf5                      1.10.2               hc401514_3    conda-forge
> icu                       58.2              hf484d3e_1000    conda-forge
> idna                      2.10                     pypi_0    pypi
> imageio                   2.9.0                    pypi_0    pypi
> importlib-metadata        3.3.0                    pypi_0    pypi
> iopath                    0.1.2                    pypi_0    pypi
> ipython                   7.12.0           py36h5ca1d4c_0    conda-forge
> ipython_genutils          0.2.0                      py_1    conda-forge
> jasper                    2.0.14               habb8e15_1    conda-forge
> jedi                      0.18.0           py36h5fab9bb_1    conda-forge
> jpeg                      9d                   h36c2ea0_0    conda-forge
> kaolin                    0.9.0                     dev_0    <develop>
> kornia                    0.4.1                    pypi_0    pypi
> lcms2                     2.11                 hcbb858e_1    conda-forge
> ld_impl_linux-64          2.35.1               hea4e1c9_1    conda-forge
> libffi                    3.3                  h58526e2_2    conda-forge
> libgcc-ng                 9.3.0               h5dbcf3e_17    conda-forge
> libgfortran               3.0.0                         1    conda-forge
> libglu                    9.0.0             he1b5a44_1001    conda-forge
> libiconv                  1.15              h516909a_1006    conda-forge
> libopencv                 3.4.2                hb342d67_1    defaults
> libpng                    1.6.37               h21135ba_2    conda-forge
> libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
> libtiff                   4.2.0                hdc55705_0    conda-forge
> libuuid                   2.32.1            h7f98852_1000    conda-forge
> libuv                     1.40.0               h7f98852_0    conda-forge
> libwebp-base              1.1.0                h36c2ea0_3    conda-forge
> libxcb                    1.13              h14c3975_1002    conda-forge
> libxml2                   2.9.9                h13577e0_2    conda-forge
> llvm-openmp               11.0.0               hfc4b9b4_1    conda-forge
> lz4-c                     1.9.2                he1b5a44_3    conda-forge
> markdown                  3.3.3                    pypi_0    pypi
> mkl                       2020.4             h726a3e6_304    conda-forge
> mkl-service               2.3.0            py36h8c4c3a4_2    conda-forge
> mkl_fft                   1.2.0            py36h68bb277_1    conda-forge
> mkl_random                1.2.0            py36h7c3b610_1    conda-forge
> munch                     2.5.0                    pypi_0    pypi
> ncurses                   6.2                  h58526e2_4    conda-forge
> nettle                    3.3                           0    conda-forge
> ninja                     1.10.2               h4bd325d_0    conda-forge
> numpy                     1.19.2           py36h54aff64_0    defaults
> numpy-base                1.19.2           py36hfa32c7d_0    defaults
> oauthlib                  3.1.0                    pypi_0    pypi
> olefile                   0.46               pyh9f0ad1d_1    conda-forge
> opencv                    3.4.2            py36h6fd60c2_1    defaults
> openh264                  1.8.0             hdbcaa40_1000    conda-forge
> openssl                   1.1.1i               h7f98852_0    conda-forge
> parso                     0.8.1              pyhd8ed1ab_0    conda-forge
> pcre                      8.44                 he1b5a44_0    conda-forge
> pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
> pickleshare               0.7.5                   py_1003    conda-forge
> pillow                    8.0.1            py36h10ecd5c_0    conda-forge
> pip                       20.3.3             pyhd8ed1ab_0    conda-forge
> pixman                    0.34.0            h14c3975_1003    conda-forge
> pretrainedmodels          0.7.4                    pypi_0    pypi
> prompt-toolkit            3.0.8              pyha770c72_0    conda-forge
> prompt_toolkit            3.0.8                hd8ed1ab_0    conda-forge
> protobuf                  3.14.0                   pypi_0    pypi
> pthread-stubs             0.4               h36c2ea0_1001    conda-forge
> ptyprocess                0.6.0                   py_1001    conda-forge
> py-opencv                 3.4.2            py36hb342d67_1    defaults
> pyasn1                    0.4.8                    pypi_0    pypi
> pyasn1-modules            0.2.8                    pypi_0    pypi
> pygments                  2.7.3              pyhd8ed1ab_0    conda-forge
> python                    3.6.12          hffdb5ce_0_cpython    conda-forge
> python_abi                3.6                     1_cp36m    conda-forge
> pytorch                   1.7.0           py3.6_cuda10.2.89_cudnn7.6.5_0    pytorch
> readline                  8.0                  he28a2e2_2    conda-forge
> requests                  2.25.1                   pypi_0    pypi
> requests-oauthlib         1.3.0                    pypi_0    pypi
> rsa                       4.6                      pypi_0    pypi
> runx                      0.0.10                   pypi_0    pypi
> scipy                     1.5.2                    pypi_0    pypi
> segmentation-models-pytorch 0.1.3                    pypi_0    pypi
> setuptools                49.6.0           py36h9880bd3_2    conda-forge
> six                       1.15.0             pyh9f0ad1d_0    conda-forge
> smplx                     0.1.26                   pypi_0    pypi
> sqlite                    3.34.0               h74cdb3f_0    conda-forge
> tensorboard               2.4.0                    pypi_0    pypi
> tensorboard-plugin-wit    1.7.0                    pypi_0    pypi
> tensorboardx              2.1                      pypi_0    pypi
> timm                      0.3.2                    pypi_0    pypi
> tk                        8.6.10               h21135ba_1    conda-forge
> torchaudio                0.7.0                      py36    pytorch
> torchgeometry             0.1.2                    pypi_0    pypi
> torchvision               0.8.1                py36_cu102    pytorch
> tqdm                      4.55.0                   pypi_0    pypi
> traitlets                 4.3.3            py36h9f0ad1d_1    conda-forge
> typing_extensions         3.7.4.3                    py_0    conda-forge
> urllib3                   1.26.2                   pypi_0    pypi
> usd-core                  20.11                    pypi_0    pypi
> wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
> werkzeug                  1.0.1                    pypi_0    pypi
> wheel                     0.36.2             pyhd3deb0d_0    conda-forge
> x264                      1!152.20180806       h14c3975_0    conda-forge
> xorg-fixesproto           5.0               h14c3975_1002    conda-forge
> xorg-inputproto           2.3.2             h14c3975_1002    conda-forge
> xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
> xorg-libice               1.0.10               h516909a_0    conda-forge
> xorg-libsm                1.2.3             h84519dc_1000    conda-forge
> xorg-libx11               1.6.12               h516909a_0    conda-forge
> xorg-libxau               1.0.9                h14c3975_0    conda-forge
> xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
> xorg-libxext              1.3.4                h516909a_0    conda-forge
> xorg-libxfixes            5.0.3             h516909a_1004    conda-forge
> xorg-libxi                1.7.10               h516909a_0    conda-forge
> xorg-libxrender           0.9.10            h516909a_1002    conda-forge
> xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
> xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
> xorg-xproto               7.0.31            h7f98852_1007    conda-forge
> xz                        5.2.5                h516909a_1    conda-forge
> zipp                      3.4.0                    pypi_0    pypi
> zlib                      1.2.11            h516909a_1010    conda-forge
> zstd                      1.4.5                h6597ccf_2    conda-forge
> ```

Can I ask how did you resolved this issue?

**Comment by ryol8888** [comment]
there is no fvcore lib both. I solved this msg 

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```
install `conda install -c fvcore -c iopath -c conda-forge fvcore iopath` it works for me 

here is my `conda list`

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
blas                      1.0                         mkl
ca-certificates           2021.5.30            ha878542_0    conda-forge
certifi                   2021.5.30        py38h578d9bd_0    conda-forge
chumpy                    0.70                     pypi_0    pypi
cudatoolkit               10.2.89              hfd86e86_1
cycler                    0.10.0                   pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
face-alignment            1.3.4                    pypi_0    pypi
freetype                  2.10.4               h5ab3b9f_0
fvcore                    0.1.5.post20210518            py38    fvcore
imageio                   2.9.0                    pypi_0    pypi
intel-openmp              2021.2.0           h06a4308_610
iopath                    0.1.8                      py38    iopath
jpeg                      9b                   h024ee3a_2
kiwisolver                1.3.1                    pypi_0    pypi
lcms2                     2.12                 h3be6417_0
ld_impl_linux-64          2.33.1               h53a641e_7
libffi                    3.3                  he6710b0_2
libgcc-ng                 9.1.0                hdf63c60_0
libpng                    1.6.37               hbc83047_0
libstdcxx-ng              9.1.0                hdf63c60_0
libtiff                   4.2.0                h85742a9_0
libuv                     1.40.0               h7b6447c_0
libwebp-base              1.2.0                h27cfd23_0
llvmlite                  0.36.0                   pypi_0    pypi
lz4-c                     1.9.3                h2531618_0
matplotlib                3.4.2                    pypi_0    pypi
mkl                       2021.2.0           h06a4308_296
mkl-service               2.3.0            py38h27cfd23_1
mkl_fft                   1.3.0            py38h42c9631_2
mkl_random                1.2.1            py38ha9443f7_2
ncurses                   6.2                  he6710b0_1
networkx                  2.5.1                    pypi_0    pypi
ninja                     1.10.2               hff7bd54_1
nose                      1.3.7                    pypi_0    pypi
numba                     0.53.1                   pypi_0    pypi
numpy                     1.20.2           py38h2d18471_0
numpy-base                1.20.2           py38hfae3a4d_0
olefile                   0.46                       py_0
opencv-python             4.5.2.52                 pypi_0    pypi
openssl                   1.1.1k               h27cfd23_0
pillow                    8.2.0            py38he98fc37_0
pip                       21.1.1           py38h06a4308_0
portalocker               1.7.0            py38h578d9bd_1    conda-forge
pyparsing                 2.4.7                    pypi_0    pypi
python                    3.8.10               hdb3f193_7
python-dateutil           2.8.1                    pypi_0    pypi
python_abi                3.8                      1_cp38    conda-forge
pytorch                   1.7.1           py3.8_cuda10.2.89_cudnn7.6.5_0    pytorch
pytorch3d                 0.4.0           py38_cu102_pyt171    pytorch3d
pywavelets                1.1.1                    pypi_0    pypi
pyyaml                    5.3.1            py38h8df0ef7_1    conda-forge
readline                  8.1                  h27cfd23_0
scikit-image              0.18.1                   pypi_0    pypi
scipy                     1.6.3                    pypi_0    pypi
setuptools                52.0.0           py38h06a4308_0
six                       1.15.0           py38h06a4308_0
sqlite                    3.35.4               hdfb4753_0
tabulate                  0.8.9              pyhd8ed1ab_0    conda-forge
tensorly                  0.6.0                    pypi_0    pypi
termcolor                 1.1.0                      py_2    conda-forge
tifffile                  2021.4.8                 pypi_0    pypi
tk                        8.6.10               hbc83047_0
torchvision               0.8.2                py38_cu102    pytorch
tqdm                      4.61.0             pyhd8ed1ab_0    conda-forge
typing_extensions         3.7.4.3            pyha847dfd_0
wheel                     0.36.2             pyhd3eb1b0_0
xz                        5.2.5                h7b6447c_0
yacs                      0.1.6                      py_0    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zlib                      1.2.11               h7b6447c_3
zstd                      1.4.9                haebb681_0
```
