### ISSUE TITLE
The transformation of MeshRasterizer from NDC to screen coordinates is different with PerspectiveCameras.

### ISSUE THREAD

**Issue by jby1993** [facebookresearch/pytorch3d#498]
I found that the transformation of MeshRasterizer follows the pytorch interpolation setting with align_corners=False(see the PixToNonSquareNdc function). 
    However, the transformation in PerspectiveCameras camera follows the setting of align_corners=True(see _get_sfm_calibration_matrix and transform_points_screen functions in cameras.py).
    This difference can lead little error between rasterized pixels and pixels projected with screen space projection matrix, if defining PerspectiveCameras with screen space.

**Comment by gkioxari** [comment]
Hi @jby1993 
Could you provide an example that reproduces your observation? For example, a setting of cameras in NDC space and screen space that leads to this discrepancy. Is this in the `cameras` and the `transform_points_screen` method? 

Note that in the rasterizer we only assume NDC space. When a camera is defined in screen space, our `cameras` transform it to NDC and all subsequent point transforms in the renderer assume NDC space.

**Comment by jby1993** [comment]
Hi @gkioxari, I provide an example [example.zip](https://github.com/facebookresearch/pytorch3d/files/5749697/example.zip). 
In the example, I first set a PerspectiveCameras with screen space parameters. Then I rasterize a body mesh with MeshRasterizer. With the fragment results, I recover the 3D points for rasterized pixels, then projecting these 3D points to new pixels with the transform_points_screen method of the camera. The projected and rasterized pixels should be totally same. However, they exist 0.2 mean error. I think the error is caused by the different default implementations of ndc and screen transformation in MeshRasterizer and PerspectiveCameras.

PS: note the pytorch3D version and MeshRasterizer setting.
