### ISSUE TITLE
How can i change the background color of the rendering image

### ISSUE THREAD

**Issue by Junwei-LV** [facebookresearch/pytorch3d#499]
I use the pytorch3d-0.2.5 to render a cow, then i get the image as follow. I want to know where and how I can change the background of rendering image to black. 
Because i use pytorch3d-0.2.0, the background is black. 
Thank u
![image](https://user-images.githubusercontent.com/36357628/103211607-9bc5cc80-4943-11eb-9bb7-4b51ae02f2d7.png)

**Comment by Junwei-LV** [comment]
I have solved the problem, thanks

**Comment by yejr0229** [comment]
Hi, I wonder how do you solve this?
