### ISSUE TITLE
Colab

### ISSUE THREAD

**Issue by Arthurg27** [facebookresearch/pytorch3d#505]
## ❓ Questions on how to use PyTorch3D
What is the easiest way to run the tutorial code on Collaboratory?

**Comment by bottler** [comment]
If you go to https://pytorch3d.org/tutorials/ and click on the name of the tutorial you are interested in, you should see a button to open that tutorial in colab. That's probably the easiest way.

**Comment by Arthurg27** [comment]
Jeremy, thank you!
Managed to run the code in colab. and it's looking good till now.
Couldn't find the way to animate the transaction between the sphere and dolphin meshes

**Comment by gkioxari** [comment]
You can save the intermediate obj files after each optimization iteration or render them from a viewpoint of your choice and then visualize them or create a gif. But glad the colab tutorial works!  Closing the issue!
