### ISSUE TITLE
Rasterizer produce nan barycentric coordinates when enabling perspective_correct.

### ISSUE THREAD

**Issue by jby1993** [facebookresearch/pytorch3d#508]
I found the rasterizer will randomly produce nan value in backward computed grad on my mesh data when setting perspective_correct=True. After I check the code, I found the reason should be in BarycentricPerspectiveCorrectionForward and BarycentricPerspectiveCorrectionBackward. eg:
```cuda
__device__ inline float3 BarycentricPerspectiveCorrectionForward(
 const float3& bary,
 const float z0,
 const float z1,
 const float z2) {
 const float w0_top = bary.x * z1 * z2;
 const float w1_top = z0 * bary.y * z2;
 const float w2_top = z0 * z1 * bary.z;
 const float denom = w0_top + w1_top + w2_top;
 const float w0 = w0_top / denom;
 const float w1 = w1_top / denom;
 const float w2 = w2_top / denom;
 return make_float3(w0, w1, w2);
}
```
For my data, I found the denom can be zero, this causes the nan problem. I modified the related code in BarycentricPerspectiveCorrectionForward and BarycentricPerspectiveCorrectionBackward to stop perspective correction if denom closes to zero. And this solves the problem for me.

**Comment by gkioxari** [comment]
You need to give us data and a concise code snippet to reproduce the issue. Otherwise, it's impossible to help you. 
Here are guidelines for bug reports: https://github.com/facebookresearch/pytorch3d/blob/master/.github/ISSUE_TEMPLATE/bugs.md

**Comment by gkioxari** [comment]
No response. Closing this.
