### ISSUE TITLE
How to Do 3D Object/ Mesh Classification

### ISSUE THREAD

**Issue by thesuperboy** [facebookresearch/pytorch3d#509]
So, How to recognize what object it is based on the input obj , so for example if I give it an obj file containing data for a chair the network should take it as input and give the predictions as chair.

It's basically Image Classification but with 3d Data. 

Please Reply As Soon As Possible

**Comment by gkioxari** [comment]
This is not an issue with PyTorch3D, which is what the repo issue page is for. Closing this.
