### ISSUE TITLE
❓ Questions on how to use PyTorch3D for 3D Object/Mesh Classification

### ISSUE THREAD

**Issue by thesuperboy** [facebookresearch/pytorch3d#510]
## ❓ Questions on how to use PyTorch3D for 3D point cloud classification

So, How to recognize what object it is based on the input obj , so for example if I give it an obj file containing data for a chair the network should take it as input and give the predictions as chair.

It's basically Image Classification but with 3d Data. 

Please Reply As Soon As Possible

**Comment by thesuperboy** [comment]
Anyone? Please Reply

**Comment by gkioxari** [comment]
Again, not an issue with PyTorch3D. The issue page should be used for issues and bug reports. Closing this.
