### ISSUE TITLE
Iteration mesh animation

### ISSUE THREAD

**Issue by Arthurg27** [facebookresearch/pytorch3d#512]
❓ How can I animate the multiple mesh iterations in sphere to dolphin transition?
https://pytorch3d.org/tutorials/deform_source_mesh_to_target_mesh

**Comment by gkioxari** [comment]
Can you be a little bit clearer? How exactly do you want to animate it? 
If you mean what I think you mean, you can render the shape for each iteration of the optimization and create a gif.

**Comment by gkioxari** [comment]
No response. Closing.
