### ISSUE TITLE
Renderer Output Unexpected Patterns

### ISSUE THREAD

**Issue by eric-qian-d** [facebookresearch/pytorch3d#516]
## 🐛 Bugs / Unexpected behaviors
I ran a check with a point cloud that forms a square plane and is colored all white. When rendered, however, the output is not always a white square. 

## Instructions To Reproduce the Issue:

1. Code
```
import os
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
from skimage.io import imread

# Util function for loading point clouds|
import numpy as np

# Data structures and functions for rendering
from pytorch3d.structures import Pointclouds
from pytorch3d.renderer import (
    look_at_view_transform,
    FoVOrthographicCameras, 
    PointsRasterizationSettings,
    PointsRenderer,
    PulsarPointsRenderer,
    PointsRasterizer,
    AlphaCompositor,
    NormWeightedCompositor
)

def normalize(coord, h, w):
    c = torch.Tensor([(w - 1) / 2., (h - 1) / 2.]).to(coord.device).float()
    coord_norm = (coord - c) / c
    return coord_norm

def indices_array_generic_builtin(m,n):
    return np.indices((m,n)).transpose(1,2,0).astype(np.float)

device = torch.device("cuda:0")
torch.cuda.set_device(device)

w = 320
test_points = indices_array_generic_builtin(w,w)
test_points = torch.from_numpy(np.flip(test_points,2).copy())
norm_test_points = (normalize(test_points, w, w)).reshape(-1, 2)
norm_test_points = torch.cat((norm_test_points, 2 * torch.ones(norm_test_points.shape[0], 1)),1).float()

test_rgb =  255 * torch.ones(norm_test_points.shape[0], 3).float()

norm_test_points = norm_test_points.to(device)
test_rgb = test_depth.to(device)

point_cloud = Pointclouds(points=[norm_test_points], features=[test_rgb])

R = torch.eye(3).unsqueeze(0)
T = torch.zeros(T.shape)

cameras = FoVOrthographicCameras(device=device, R=R, T=T, znear=0.01)

raster_settings = PointsRasterizationSettings(
    image_size=320, 
    radius = 0.01,
    points_per_pixel = 1
)

rasterizer = PointsRasterizer(cameras=cameras, raster_settings=raster_settings)
renderer = PointsRenderer(
    rasterizer=rasterizer,
    compositor=AlphaCompositor()
)

images = renderer(point_cloud)
plt.figure(figsize=(10, 10))
plt.imshow(images[0, ..., :3].cpu().numpy())
plt.grid("off")
plt.axis("off");

```
2. The exact command you ran: run the file containing this code

3. What you observed:

The key variables seem to be `radius` and `points_per_pixel`.

Running the exact code above with `radius = 0.01` and `points_per_pixel = 1`, the following is produced

![image](https://user-images.githubusercontent.com/30250617/104235410-8e681200-541a-11eb-802f-b32927f421ab.png)

With `radius = 0.01` and `points_per_pixel = 3`, we get

![image](https://user-images.githubusercontent.com/30250617/104235497-ad66a400-541a-11eb-9d56-fc8639f374f5.png)

With `radius = 0.003` and `points_per_pixel = 1`, we get

![image](https://user-images.githubusercontent.com/30250617/104235915-4a294180-541b-11eb-96b1-9b764c8d59c4.png)

Only with `radius = 0.01` and `points_per_pixel >= 8` do I get the white square I would expect.

These all look very different, and none of them are a white square. The first two also have pretty strange artifacts, which I don't think is the expected behavior. The circle is especially confusing since I'm not sure why such a result would occur. I tried making the z values ray depth rather than plane depth in case I was using the wrong convention, but the problem still persists.

I suspect that this could be related to `rasterize_points` since its return value `dists2` is not uniform, even though we would expect it to be since all the points should have the same depth.

**Comment by gkioxari** [comment]
Here is what I get with the code below

![issue_516](https://user-images.githubusercontent.com/4369065/104399880-6b1a9100-5506-11eb-9503-fc7a576c68e4.png)

Note that I defined a perspective camera. The issue with your code is that your pointcloud was spanning the [-1, 1]x[-1,1] XY space and your camera being an FoVOrthographicCamera was mapping this to the screen space. So your pointcloud is effectively and correctly spanning the whole image. The perspective camera (with focal length of 1 and principal point of 0) maps the pointcloud according to `x = f X/Z` and so you get the result above. 

```python
    device = torch.device("cuda:0")
    torch.cuda.set_device(device)

    w = 320
    test_points = indices_array_generic_builtin(w,w)
    test_points = torch.from_numpy(np.flip(test_points,2).copy())
    norm_test_points = (normalize(test_points, w, w)).reshape(-1, 2)
    norm_test_points = torch.cat((norm_test_points, 2 * torch.ones(norm_test_points.shape[0], 1)),1).float()

    test_rgb =  torch.ones(norm_test_points.shape[0], 3).float()

    norm_test_points = norm_test_points.to(device)
    test_rgb = test_rgb.to(device)

    point_cloud = Pointclouds(points=[norm_test_points], features=[test_rgb])

    cameras = PerspectiveCameras(device=device)

    raster_settings = PointsRasterizationSettings(
        image_size=320,
        radius = 0.01,
        points_per_pixel = 10
    )

    rasterizer = PointsRasterizer(cameras=cameras, raster_settings=raster_settings)
    renderer = PointsRenderer(
        rasterizer=rasterizer,
        compositor=AlphaCompositor()
    )

    images = renderer(point_cloud)
    filename = "/tmp/output/issue_516.png"
    rgb = images[0, ..., :3].detach().squeeze().cpu()
    Image.fromarray(
        (rgb.detach().cpu().numpy() * 255).astype(np.uint8)
    ).save(filename)
```
