### ISSUE TITLE
Windows 10 Installation Issue

### ISSUE THREAD

**Issue by AkbarShah96** [facebookresearch/pytorch3d#517]
## Instructions To Reproduce the Issue:

Please include the following (depending on what the issue is):

1. Any changes you made (`git diff`) or code you wrote
 None

2. The exact command(s) you ran:
I am trying to install from a local clone.
I followed the steps for CUB library and set the environment variable CUB_HOME to the directory that contained the `CMakeLists.txt`
Next, I did the required changes in the header files and then I tried to install with the following commands:   
```
git clone https://github.com/facebookresearch/pytorch3d.git
cd pytorch3d && pip install -e .
```
3. What you observed (including the full logs):

[error.txt](https://github.com/facebookresearch/pytorch3d/files/5801589/error.txt)
PyTorch: 1.6
cudatoolkit: 10.1.243

CUDA HOME / CUDA PATH Variables:
![image](https://user-images.githubusercontent.com/44021337/104308701-5e2f7a80-54d1-11eb-8185-8a2af16f0736.png)

Thanks for your time!

**Comment by bottler** [comment]
The main error here is `2021-01-11T22:45:44,551     c:\users\akbar\anaconda3\envs\unsupervised-depth-estimation\lib\site-packages\torch\include\ATen/cuda/CUDAContext.h(5): fatal error C1083: Cannot open include file: 'cuda_runtime_api.h': No such file or directory`. Suggests a problem with cuda installation.

What happens when you type `nvcc` at the prompt? Can you paste the output of `dir C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin\include"`? What is in the PATH environment variable?

There are some discrepancies between the screenshot and the paths in error.txt. For example, a compiler call looks like the following, which looks for cub in `c:\cub-1.8.0` not `C:\Program Files\cub-1.10.0`, and it seems to be using cuda 10.0 not 10.1. Note that changing variables in the System variables thing won't take effect in prompts (or other applications) which have already been opened.

```
cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -DWITH_CUDA -DTHRUST_IGNORE_CUB_VERSION_CHECK -IC:\chamferdist-master\pytorch3d\pytorch3d\csrc -IC:\cub-1.8.0 -Ic:\users\akbar\anaconda3\envs\unsupervised-depth-estimation\lib\site-packages\torch\include -Ic:\users\akbar\anaconda3\envs\unsupervised-depth-estimation\lib\site-packages\torch\include\torch\csrc\api\include -Ic:\users\akbar\anaconda3\envs\unsupervised-depth-estimation\lib\site-packages\torch\include\TH -Ic:\users\akbar\anaconda3\envs\unsupervised-depth-estimation\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin\include" -Ic:\users\akbar\anaconda3\envs\unsupervised-depth-estimation\include -Ic:\users\akbar\anaconda3\envs\unsupervised-depth-estimation\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -c C:\chamferdist-master\pytorch3d\pytorch3d\csrc\ext.cpp /FoC:\chamferdist-master\pytorch3d\build\temp.win-amd64-3.7\Release\chamferdist-master\pytorch3d\pytorch3d\csrc\ext.obj -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
```

**Comment by AkbarShah96** [comment]
Thanks for your reply and noticing the discrepancies. 

I am using the x64 Native Tools Command Prompt for VS 2019. 
When I type in `nvcc` I get the following: `nvcc fatal: No input files specified; use option --help for more information`

For `dir C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin\include" ` command I get: `The system cannot find the file specified`

I did have CUDA 10.0 at one point in the past but then upgraded to 10.1! I am not sure why it's still looking for CUDA 10.0. 

In the PATH environment variable, I can see the following ones related to CUDA:
![image](https://user-images.githubusercontent.com/44021337/104316777-43fb9980-54dd-11eb-85ce-d3665f1ea302.png)

I updated cub since yesterday to the new version so that should be resolved too and I just reinstalled CUDA 10.1 but the problem is still persistent:
[error_new.txt](https://github.com/facebookresearch/pytorch3d/files/5802252/error_new.txt)

**Comment by bottler** [comment]
It's the same error message. The compiler flags show that the location `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\include` is being looked in to for cuda headers, which is empty. Are there headers in `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include`?

I think you might need to move the `\bin` from the end of `CUDA_HOME`.

**Comment by AkbarShah96** [comment]
`C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include` contains many header files. 

I removed the` \bin` from `CUDA_HOME` variable and ran x64 Native Tools as an administrator. 

Now I get the following:
[next_error.txt](https://github.com/facebookresearch/pytorch3d/files/5802921/next_error.txt)

**Comment by bottler** [comment]
This is 

```
2021-01-12T15:58:08,920     
C:/Users/akbar/Anaconda3/lib/site-packages/torch/include\torch/csrc/jit/argument_spec.h(190): 
error: member "torch::jit::ArgumentSpecCreator::DEPTH_LIMIT" may not be initialized
```

Have you made the modifications to pytorch headers detailed in https://github.com/facebookresearch/pytorch3d/issues/323 ?

**Comment by AkbarShah96** [comment]
Yes! I made these changes in the environment ( `C:\Users\akbar\Anaconda3\envs\Unsupervised-Depth-Estimation\Lib\site-packages\torch\include\torch\csrc\jit\runtime\argument_spec.h`) that I was trying to install pytorch3d into but apparently, I also had to make them in the path you specified above. 

I managed to successfully install it finally. :)

Thank you so much for your help!
