### ISSUE TITLE
How can I render a depth map using pytorch3d

### ISSUE THREAD

**Issue by OOF-dura** [facebookresearch/pytorch3d#527]
## ❓ Questions on how to use PyTorch3D

How can we get a depth map as output using pytorch3d?

Given a 3D mesh scene, if it is possible to render the depth map of the scene?

**Comment by nikhilaravi** [comment]
Please see this issue which is about the same issue: https://github.com/facebookresearch/pytorch3d/issues/35

**Comment by OOF-dura** [comment]
> Please see this issue which is about the same question: #35

Thank you!
