### ISSUE TITLE
install and use pytorch3d CPU only (no training)? 

### ISSUE THREAD

**Issue by MarkTension** [facebookresearch/pytorch3d#53]
Hi!

I'd like to just use the simple demo (no training) of mesh-r-cnn, and don't have a cuda-capable gpu on my macbook. Can I install and use this only with CPU? Or is it only made for gpu usage? Thanks!

**Comment by gkioxari** [comment]
Hi @MarkTension! There is currently some functionality in pytorch3d that has only GPU support. We are currently working on adding cpu implementations for all these functions. Stay tuned!

**Comment by nikhilaravi** [comment]
#44 is also referencing this issue.

**Comment by nikhilaravi** [comment]
@MarkTension We now have CPU support for all the functions used in Mesh R-CNN. Please install PyTorch3D from master with pip.
