### ISSUE TITLE
Mathematical formula rendering errors on the PyTorch3D tutorial page 

### ISSUE THREAD

**Issue by mrmiywj** [facebookresearch/pytorch3d#531]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## 🐛 Bugs / Unexpected behaviors
* Platform: Chrome Version 87.0.4280.141 (Official Build) (x86_64)
* OS: macOS catalina 10.15. Time 7
* Link to the page: https://pytorch3d.org/tutorials/bundle_adjustment
* Screenshot: 
<img width="1134" alt="Screen Shot 2021-01-21 at 7 42 20 PM" src="https://user-images.githubusercontent.com/7459820/105443544-d22ff800-5c20-11eb-9d8c-0543c277187e.png">

NOTE: Please look at the existing list of Issues tagged with the label ['bug`](https://github.com/facebookresearch/pytorch3d/issues?q=label%3Abug). **Only open a new issue if this bug has not already been reported. If an issue already exists, please comment there instead.**.

**Comment by nikhilaravi** [comment]
Yes we are aware of this issue - currently there are a number of new features that we are prioritizing first. If you want to try and fix it, all the code for the website is in the `pytorch3d/website` folder - the fix should be to add `mathjax` to the commands used with `nbconvert` to convert the `.ipynb` notebooks to `.html` and maybe to add `LaTex` support in the docusauras config. 

If you want to view the math correctly you can see the notebook here: https://github.com/facebookresearch/pytorch3d/blob/master/docs/tutorials/bundle_adjustment.ipynb
