### ISSUE TITLE
Fail to read a ply file.

### ISSUE THREAD

**Issue by MyEvolution** [facebookresearch/pytorch3d#535]
.ply whose header is as following cannot be correctly read.
```
ply
format ascii 1.0
comment generated by OnePiece
element vertex 3164
property double x
property double y
property double z
property uchar red
property uchar green
property uchar blue
element face 6324
property list uchar uint vertex_indices
end_header
```
Error: Invalid vertices in file.

**Comment by bottler** [comment]
I think you might be using a released version of PyTorch3D, and this may have been fixed or partially fixed since the release. Can you try installing the latest code (e.g. via a nightly build) and seeing if it works?

**Comment by wangsen1312** [comment]
@MyEvolution The latest release version cannot read the ply format with color.

**Comment by bottler** [comment]
This is now fixed on github, so it will be in the next release and if you install from source or use a nightly build it should be fine.
