### ISSUE TITLE
Save per color texture of a mesh or export it as a UV texture image.

### ISSUE THREAD

**Issue by elcronos** [facebookresearch/pytorch3d#546]
## 🚀 Feature

Pytorch3d should provide a way to save per color textures. Either in the .obj or .ply format.

NOTE: Please look at the existing list of Issues tagged with the label ['enhancement`](https://github.com/facebookresearch/pytorch3d/issues?q=label%3Aenhancement). **Only open a new issue if you do not see your feature request there**.

## Motivation
In some of the examples, we have been optimizing per vertex color textures. However, so far, there is not a way to save or export those vertex colors. Alternatively, maybe a feature that allows converting per vertex features to UV textures would be useful as well.

## Pitch

Many of the tutorials show how to optimize shape of a mesh. However, in the cow example with texture we are able to create a new mesh with per vertex color. It would be great to add this feature of saving per vertex colors or being able to export it as UV texture (.png image or so). This will allow more people to be able to experiment with texture.

NOTE: we only consider adding new features if they are useful for many users.

**Comment by nikhilaravi** [comment]
@elcronos thanks for suggesting this feature. It's related to https://github.com/facebookresearch/pytorch3d/pull/332 which we are expanding upon to make the feature more complete for all texture types. Given that there are now multiple people interested in this we will re-evaluate the priority of completing it!

**Comment by elcronos** [comment]
@nikhilaravi Great ! Looking forward to it. Please keep me updated.

**Comment by nikhilaravi** [comment]
@elcronos we have added support for saving UV textures in https://github.com/facebookresearch/pytorch3d/commit/542e2e7c07fdeef815312b087acfa58094a7aa1e. We will add support for saving vertex textures in `.ply` format. Note that `.obj` doesn't support saving per vertex colors.

**Comment by Creling** [comment]
@nikhilaravi I think the format `.ply` should save vertex colors as unchar but not float which pytorch3d current adopts.

references:
- https://github.com/cnr-isti-vclab/meshlab/issues/186#issuecomment-362246783
- http://paulbourke.net/dataformats/ply/
