### ISSUE TITLE
submesh function

### ISSUE THREAD

**Issue by lawy623** [facebookresearch/pytorch3d#547]
## ❓ Questions on how to use PyTorch3D

Hi, 

I am wondering is there any function that supports 'submesh' that existed in Trimesh (https://github.com/mikedh/trimesh/issues/278)? So that I can subset multiple parts of the mesh given groups of faces idx?

Thanks for looking the question!

Yue

**Comment by nikhilaravi** [comment]
@lawy623 thanks for the question. Currently we don't have this functionality but we could potentially add it.  To clarify, you want to have a function that takes in a list of lists/tensors which specify the face indices for the submeshes and returns a list of `Meshes` objects e.g. 

```
# e.g. verts of shape (N, 200, 3), faces of shape (N, 500, 3)
mesh = Meshes(verts=verts, faces=faces)
face_indices = [[1, ...., 100], [101, ...., 200]]
submeshes_list = mesh.submesh(face_indices=face_indices)
```
```
> len(submeshes_list)
>  2
> isinstance(submeshes_list[0], Meshes)
> true 
```

**Comment by lawy623** [comment]
Yes, that's what I expect for 'submesh'. Checking watertight may also be useful. Looking forward to that!

**Comment by kjchalup** [comment]
We recently added submeshing, see https://github.com/facebookresearch/pytorch3d/blob/main/pytorch3d/structures/meshes.py#L1558 and test_meshes.py for examples. Closing the issue, thanks for the suggestion!
