### ISSUE TITLE
Shape broadcast bug in blending

### ISSUE THREAD

**Issue by elliottwu** [facebookresearch/pytorch3d#550]
https://github.com/facebookresearch/pytorch3d/blob/51de308b808ba28096d72ccd3f7c1019da4dea74/pytorch3d/renderer/blending.py#L188

This raises shape mismatch errors with batched cameras when the shape of `zfar` and `znear` is `(N,)` while the shape of `fragments.zbuf` and `mask` is `(N, H, W, K)`.

**Comment by nikhilaravi** [comment]
@elliottwu thanks for pointing this out. We will look into fixing this!

**Comment by Marcus-Zhu** [comment]
Hi! I'm having the same issue when trying to render multiple meshes using a rasterizer with faces_per_pixel set to values other than 1. I wonder if there's any update on this issue.


To reproduce this, see the complete code [here](https://gist.github.com/Marcus-Zhu/199d368ae94ca50583d731c774154980). What I did was copying the [batch rendering tutorial](https://pytorch3d.org/tutorials/render_textured_meshes), and then changing the rendering code in part 2 to (more specifically the value of `face_per_pixel` in `raster_settings`):
```
R, T = look_at_view_transform(2.7, 0, 180) 
cameras = FoVPerspectiveCameras(device=device, R=R, T=T)

from pytorch3d.renderer import BlendParams
import numpy as np
blend_params = BlendParams(sigma=1e-5, gamma=1e-4)
raster_settings = RasterizationSettings(
    image_size=512,
    blur_radius=np.log(1.0 / 1e-4 - 1.0) * blend_params.sigma,
    faces_per_pixel=5, # any value other than 1 will raise the error
)
lights = PointLights(device=device, location=[[0.0, 0.0, -3.0]])
renderer = MeshRenderer(
    rasterizer=MeshRasterizer(cameras=cameras, raster_settings=raster_settings),
    shader=SoftPhongShader(device=device, cameras=cameras, lights=lights),
)
```
This produces the error in part 6:
```
/usr/local/lib/python3.7/dist-packages/pytorch3d/renderer/blending.py in softmax_rgb_blend(colors, fragments, blend_params, znear, zfar)
    186     # TODO: there may still be some instability in the exponent calculation.
    187 
--> 188     z_inv = (zfar - fragments.zbuf) / (zfar - znear) * mask
    189     # pyre-fixme[16]: `Tuple` has no attribute `values`.
    190     # pyre-fixme[6]: Expected `Tensor` for 1st param but got `float`.
RuntimeError: The size of tensor a (20) must match the size of tensor b (5) at non-singleton dimension 3
```

**Comment by nikhilaravi** [comment]
This issue should now be fixed by https://github.com/facebookresearch/pytorch3d/commit/bc8361fa471e39280b1c5e3717309167b08ffed5.
