### ISSUE TITLE
Skew parameter in the perspective camera model

### ISSUE THREAD

**Issue by pengsongyou** [facebookresearch/pytorch3d#552]
Hi,

I have some intrinsic matrix K from OpenCV including focal length, principal points and skew, like:
![](https://learnopencv.com/wp-content/ql-cache/quicklatex.com-e889cfafac2d3a5d268d2dfb8063596a_l3.png)

I am currently using PerspectiveCameras in PyTorch3D. If we need to input the K as the input to PerspectiveCameras, we need to modify the focal length and principal points as shown here [in this document](https://github.com/facebookresearch/pytorch3d/blob/master/docs/notes/cameras.md#perspectivecameras-orthographiccameras). However, for the skew parameter, how should we change it to NDC space as well?

Thanks for the help in advance!

Best,
Songyou

**Comment by gkioxari** [comment]
The existing cameras in PyTorch3D are by no means supposed to be an exhaustive collection of all cameras one might want to define. In your case, you want a camera that is not supported currently, however the existing cameras are great examples of how you can define your own cameras, by subclassing `CamerasBase`.
