### ISSUE TITLE
Pytorch geometric

### ISSUE THREAD

**Issue by jsaisagar** [facebookresearch/pytorch3d#554]
Hi all,

Can we use pytorch geometric's graph convolutions and compute loss using pytorch3D say pytorch3d.loss.mesh_edge_loss?
Will there be any difference in gradients?

Thanks,
Sai Sagar

**Comment by nikhilaravi** [comment]
@jsaisagar thanks for your question! Unfortunately we don't have the time to check all the use cases of PyTorch3D. If you try pytorch geometric with pytorch3d and find any issues and can provide a code example to reproduce any errors then we might be able to help. 
If you'd like to open up a discussion on the [discussions](https://github.com/facebookresearch/pytorch3d/discussions) tab, other people might be able help you with your use case.  This will help us to focus Issues on bug fixes and other urgent problems.
