### ISSUE TITLE
load_obj function returns empty tensor.

### ISSUE THREAD

**Issue by norouzzadeh** [facebookresearch/pytorch3d#557]
## 🐛 Bugs / Unexpected behaviors

Using the following mesh in the load_obj function, an empty tensor is returned for vertices, faces and aux
https://github.com/sofa-framework/sofa/blob/master/share/mesh/liver.obj

## Instructions To Reproduce the Issue:

!wget https://github.com/sofa-framework/sofa/blob/master/share/mesh/liver.obj

Load the liver mesh.
trg_obj = os.path.join('liver.obj')

We read the target 3D model using load_obj
verts, faces, aux = load_obj(trg_obj)
print(verts)

------------------------------------------------------
This is the results:
tensor([], size=(0, 3))

**Comment by gkioxari** [comment]
I get 
```pythong
verts.shape
torch.Size([181, 3])
```
and
```pythong
faces.verts_idx.shape
torch.Size([274, 3])
```

**Comment by norouzzadeh** [comment]
Here's my iPython notebook with the mentioned error.
https://github.com/norouzzadeh/fp/blob/main/Pytorch3D_LiverReconstruction.ipynb

**Comment by bottler** [comment]
In your notebook the downloaded file is "liver.obj.1", but you are loading "liver.obj" (maybe from a previous run of the code) which has a different file size. Can you check what the difference is between these files? Can you have a look inside each file and check it is what you expect?

In particular, you want to download the raw file `https://github.com/sofa-framework/sofa/raw/master/share/mesh/liver.obj`, but I am not sure `!wget https://github.com/sofa-framework/sofa/blob/master/share/mesh/liver.obj` will do that.

**Comment by norouzzadeh** [comment]
I have uploaded the file from local drive to the colab.
The problem is fixed.
Thanks a lot.

**Comment by gkioxari** [comment]
@norouzzadeh 
It would be best if you did a little debugging yourself with such issues before opening an issue and reporting it. Especially with IO issues, it's really easy to diagnose problems. For example, did you open the obj file with a text editor to see if the file is empty or not? Or if it has the structure of an obj file? It's not that we are magicians and do black magic here. Things are reasonable and have answers. Jumping to Github and opening issues before doing your due diligence is something I do not support nor am impressed by.

**Comment by norouzzadeh** [comment]
@gkioxari 
I downloaded the obj file. The file is not empty as i opened it in Blender and Notepad++ too.
I used the same syntax as in the "deform_source_mesh_to_target_mesh" example for loading .obj file.
"!wget https://dl.fbaipublicfiles.com/pytorch3d/data/dolphin/dolphin.obj"
But this is not working with github links.
Sorry for bothering you and making you angry.
