### ISSUE TITLE
Different results between cpu and cuda

### ISSUE THREAD

**Issue by lyp0413** [facebookresearch/pytorch3d#559]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## 🐛 Bugs / Unexpected behaviors
I choose cpu and cuda as different devices to render the same scene.But it seems that the cudaed one is fragmentary .
https://github.com/lyp0413/url/blob/main/pytorch3d_cpu.png?raw=true
https://github.com/lyp0413/url/blob/main/pytorch3d_cuda.png?raw=true
I don`t konw why the difference occurs.Maybe I forgot to set some configs?
The code is mainly from the offical tutorials.

NOTE: Please look at the existing list of Issues tagged with the label ['bug`](https://github.com/facebookresearch/pytorch3d/issues?q=label%3Abug). **Only open a new issue if this bug has not already been reported. If an issue already exists, please comment there instead.**.

## Instructions To Reproduce the Issue:

Please include the following (depending on what the issue is):

1. Any changes you made (`git diff`) or code you wrote
```
device = torch.device("cuda:0")
#device = torch.device("cpu")
mesh = load_objs_as_meshes(["******.obj"], device=device)
R, T = look_at_view_transform(0.3, 45, 0,up=((0,0.707,0.707),))
cameras = FoVPerspectiveCameras(device=device, R=R, T=T)

raster_settings = RasterizationSettings(
    image_size=1080,
    blur_radius=0,
    faces_per_pixel=1,
)

lights = PointLights(device=device, location=[[0.0, 0.0, -3.0]])

renderer = MeshRenderer(
    rasterizer=MeshRasterizer(
        cameras=cameras,
        raster_settings=raster_settings
    ),
    shader=pytorch3d.renderer.HardFlatShader(
        device=device,
        cameras=cameras,
        lights=lights
    )
)

images = renderer(mesh)
```
2. The exact command(s) you ran:
python mycode.py
3. What you observed (including the full logs):
```
** fvcore version of PathManager will be deprecated soon. **
** Please migrate to the version in iopath repo. **
https://github.com/facebookresearch/iopath 
```

Please also simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

**Comment by gkioxari** [comment]
Please check the explanation for this in https://github.com/facebookresearch/pytorch3d/issues/448
