### ISSUE TITLE
pyre-fixme[21]: Could not find name `_C` in `pytorch3d`. ?

### ISSUE THREAD

**Issue by pixellib** [facebookresearch/pytorch3d#562]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-28-247ef8de5a59> in <module>()
----> 1 from pytorch3d.io import load_objs_as_meshes, save_obj

3 frames
/usr/local/lib/python3.6/dist-packages/pytorch3d/renderer/blending.py in <module>()
      7 
      8 # pyre-fixme[21]: Could not find name `_C` in `pytorch3d`.
----> 9 from pytorch3d import _C
     10 
     11 

ImportError: /usr/local/lib/python3.6/dist-packages/pytorch3d/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c104impl23ExcludeDispatchKeyGuardC1ENS_11DispatchKeyE

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Comment by bottler** [comment]
It looks like you have installed PyTorch3D but it is not working; specifically it looks like there is a PyTorch version mismatch. You haven't provided us enough information to help, though. If you haven't yet solved the problem, please explain how you installed PyTorch3D. Please also paste the output of `pip list`. 

(Also it looks like you are using linux and have installed PyTorch3D in the global environment of the system Python. This is probably a bit risky. It would be safer to use a conda environment or a virtualenv or similar.)
