### ISSUE TITLE
Visualization of LIDAR point cloud like KITTI , NUSCENES,Lyft

### ISSUE THREAD

**Issue by abhigoku10** [facebookresearch/pytorch3d#564]
@jreese @likethesky   Is it possible to visualize the lidar point cloud of KITTI , nuscenes using pytorch3d on google colab can you provide the reference code for this ??
THanks in advance

**Comment by nikhilaravi** [comment]
@abhigoku10 You can visualize pointclouds using example code from this tutorial: https://pytorch3d.org/tutorials/render_colored_points.

We don't have the bandwidth to provide code for all use cases but there are plenty of examples in the [PyTorch3D tutorials](https://pytorch3d.org/tutorials/render_colored_points).
