### ISSUE TITLE
"final_model.obj" - vertices don't have values

### ISSUE THREAD

**Issue by felixboevr** [facebookresearch/pytorch3d#566]
I successfully ran the tutorial for [fit_textured_mesh](https://github.com/facebookresearch/pytorch3d/blob/master/docs/tutorials/fit_textured_mesh.ipynb) locally and in Google Colab. 

As a result I got "final_model.obj" file. I imported it to blender but no model was shown. 

When I open the .obj file it shows that only the faces have been calculated but not the vertices. For every line it says "v nan nan nan".

**Comment by gkioxari** [comment]
This possibly relates to this issue https://github.com/facebookresearch/pytorch3d/issues/561

**Comment by nikhilaravi** [comment]
@felixboevr can you try setting `perspective_correct=False` in the `RasterizationSettings` for the rasterizer.

**Comment by felixboevr** [comment]
Thank you both a lot. I'll try...

**Comment by felixboevr** [comment]
After adding "perspective_correct=False" I was able to get the verts. Thank you!
