### ISSUE TITLE
How to increase the polygon count of a mesh in Pytorch3D?

### ISSUE THREAD

**Issue by elcronos** [facebookresearch/pytorch3d#567]
## ❓ Questions on how to use PyTorch3D

Has anyone tried this? I don't think this is a feature that is implemented yet in Pytorch3D. But it would be very useful to know how to increase (and decrease) the number of polygons from a Mesh in Pytorch3D.

**Comment by gkioxari** [comment]
PyTorch3D only supports triangle meshes at this stage. If your mesh in the .obj file is has higher order, then the load_obj function will convert it into a triangle mesh. 
Support for higher order polygons is not in the immediate roadmap for PyTorch3D.

**Comment by nikhilaravi** [comment]
If by "increasing the number of polygons" you mean subdividing the triangle mesh into more triangles you can try to do that using the [`subdivide_meshes`](https://github.com/facebookresearch/pytorch3d/blob/aa9bcaf04c520b5fd0aa8d6d807b8090ea43d61c/pytorch3d/ops/subdivide_meshes.py#L9) op.

**Comment by elcronos** [comment]
@nikhilaravi That's exactly what I want. However when I tried to pass an Meshes object I got an error message:

```
src_mesh = load_objs_as_meshes([obj_filename], device=self.device)
# Subdivide Mesh
src_mesh = SubdivideMeshes(src_mesh)
```
'SubdivideMeshes' object has no attribute 'verts_packed'

Could you please provide an example on how to use SubdivideMeshes?

**Comment by gkioxari** [comment]
`SubdivideMeshes` is a class. So you are not using it right

```python
subdivide = SubdivideMeshes()
subdivided_mesh = subdivide(src_mesh)
```
