### ISSUE TITLE
Unexpected behavior when adjusting image_size in raster_settings

### ISSUE THREAD

**Issue by cmis91** [facebookresearch/pytorch3d#568]
This is related to #482. I used the codes by @gkioxari and 3d teapot data in that post. The only change was the image_size in raster_settings to test out non-square rendering in the recent release. 
When image_size was (600,1200), I got the following rendered image: 
![image](https://user-images.githubusercontent.com/9816523/108675066-2128b180-749b-11eb-98d5-d8aa1c047647.png)
However, after I changed image_size to (600,1199), the rendered image was 
![image](https://user-images.githubusercontent.com/9816523/108675179-474e5180-749b-11eb-9c27-6d3584b2ec6a.png)
Somehow, the aspect ratio 2 is serving as a hard-coded threshold to decide whether stretch out the image during the rendering.

**Comment by nikhilaravi** [comment]
@cmis91 What settings are you using for the cameras? See this related issue about non square image rendering and the explanation of how to set the settings: https://github.com/facebookresearch/pytorch3d/issues/548#issuecomment-775345072  and also this doc about how the cameras and rasterizer works for the non square image case: https://github.com/facebookresearch/pytorch3d/blob/master/docs/notes/renderer_getting_started.md#rasterizing-non-square-images

**Comment by cmis91** [comment]
It's the image_size in RasterizationSettings. I copied the code and data from #482 here. The strange behavior is that why the rendered image changes so dramatically when changing the image_size from (600,1200) to (600,1199). @gkioxari, since you wrote the code below, can you take a quick look and get a sense of what could happen there? 
[teapot.obj.zip](https://github.com/facebookresearch/pytorch3d/files/6024532/teapot.obj.zip)

```Python
device = torch.device("cuda:1")

obj_filename = "/tmp/output/teapot.obj"
verts, faces, aux = load_obj(obj_filename, device=device, load_textures=False)

raster_settings = RasterizationSettings(
    image_size=(600,1199), blur_radius=0, faces_per_pixel=1
)

R = euler_angles_to_matrix(
    torch.tensor([[2.18166, 0.0, 0.0]], dtype=torch.float32, device=device), "XYZ"
)
T = torch.tensor([[0, 0, 350]], dtype=torch.float32, device=device)

lights = PointLights(
    device=device,
    location=((0.0, 30.0, 200.0),),
)

cameras = PerspectiveCameras(device=device, focal_length=3.5, R=R, T=T)
renderer = MeshRenderer(
    rasterizer=MeshRasterizer(cameras=cameras, raster_settings=raster_settings),
    shader=HardGouraudShader(device=device, lights=lights, cameras=cameras),
)

textures = TexturesVertex(
    torch.ones((1, verts.shape[0], 3), device=device, dtype=torch.float32)
)
mesh = Meshes(verts=[verts], faces=[faces.verts_idx], textures=textures)

image = renderer(mesh)

filename = "/tmp/output/teapot.png"
rgb = image[0, ..., :3].detach().squeeze().cpu()
Image.fromarray((rgb.detach().cpu().numpy() * 255).astype(np.uint8)).save(filename)

```

**Comment by gkioxari** [comment]
The aspect ratio is not hard coded but there is a bug in a int division that should be a float division. We will fix this!

**Comment by cmis91** [comment]
Great. Thanks for the quick triage. Feel free to close it now or after fixing the bug.

**Comment by gkioxari** [comment]
Thanks for reporting! We will keep it open until we fix it!

**Comment by nikhilaravi** [comment]
This issue has now been fixed in master https://github.com/facebookresearch/pytorch3d/commit/13429640d3dfcdf20dc3645d74b621f5fb4faee5. If you wait until tomorrow you can install the nightly conda build of PyTorch3D to get the fix or clone from master.

**Comment by gkioxari** [comment]
I am closing this! @cmis91 feel free to re-open if you see more issues!

**Comment by cmis91** [comment]
Pulled from the master branch, tried with different image_size, and verified that the problem mentioned above disappeared. Thanks for the quick fix.
