### ISSUE TITLE
cuda nvcc compile issue with pytorch 1.4.0 on windows 

### ISSUE THREAD

**Issue by ChildAdrian** [facebookresearch/pytorch3d#57]
Hi! my env: win10, pytorch 1.4.0, py3.7, cuda10.2
when i run setup.py it return with:

C:/python37/lib/site-packages/torch/include\torch/csrc/jit/argument_spec.h(190): error: member "torch::jit::ArgumentSpecCreator::DEPTH_LIMIT" may not be initialized

C:/python37/lib/site-packages/torch/include\torch/csrc/jit/script/module.h(467): error: member "torch::jit::script::detail::ModulePolicy::all_slots" may not be initialized

C:/python37/lib/site-packages/torch/include\torch/csrc/jit/script/module.h(480): error: member "torch::jit::script::detail::ParameterPolicy::all_slots" may not be initialized

C:/python37/lib/site-packages/torch/include\torch/csrc/jit/script/module.h(494): error: member "torch::jit::script::detail::BufferPolicy::all_slots" may not be initialized

C:/python37/lib/site-packages/torch/include\torch/csrc/jit/script/module.h(507): error: member "torch::jit::script::detail::AttributePolicy::all_slots" may not be initialized

5 errors detected in the compilation of "C:/Users/xxxx/AppData/Local/Temp/tmpxft_00002db4_00000000-10_rasterize_meshes.cpp1.ii".
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.2\\bin\\nvcc.exe' failed with exit status 1

how to fit it?

**Comment by yuanluxu** [comment]
@ChildAdrian Please check Issue 10[https://github.com/facebookresearch/pytorch3d/issues/10] for patching the pytorch 1.4.0 source code.

**Comment by nikhilaravi** [comment]
This will be fixed by #9. Thanks @yuanluxu for adding this.
