### ISSUE TITLE
How to assign vertex color in packed form

### ISSUE THREAD

**Issue by Wang-Tianyu** [facebookresearch/pytorch3d#570]
I am trying to assign colors to a batch of objects with a different number of vertice.
I now have color in packed form.
How should I generate TexturesVertex with packed color data?

**Comment by nikhilaravi** [comment]
Do you have a `Meshes` object for the batch? If so you can do the following to split the packed vertex colors to a list and then initialize a TexturesVertex class using the list

```
from pytorch3d.structures import utils as struct_utils

split_size = meshes.num_verts_per_mesh().tolist()
verts_colors_list = struct_utils.packed_to_list(verts_colors_packed, split_size)
vertex_textures = TexturesVertex(verts_features= verts_colors_list)
```

See the docs for `TexturesVertex` here which explains the initialization options. 

https://github.com/facebookresearch/pytorch3d/blob/13429640d3dfcdf20dc3645d74b621f5fb4faee5/pytorch3d/renderer/mesh/textures.py#L1234-L1237

**Comment by nikhilaravi** [comment]
Closing this issue. Feel free to reopen if you have further question.
