### ISSUE TITLE
PulsarPointsRenderer, inconsistent image_size assignment

### ISSUE THREAD

**Issue by dingdingcai** [facebookresearch/pytorch3d#571]
When I play with PulsarPointsRenderer, I found there is a inconsistent bug in pytorch3d/renderer/points/pulsar/unified.py line 83. 

Given a tuple image_size, e.g. (height, width) when define a raster_setting `raster_settings=PointsRasterizationSettings(image_size=(480, 640)),`with the order image_size=(height, width) , but the code `width, height = rasterizer.raster_settings.image_size` in the line 83 of renderer/points/pulsar/unified.py assigns the size values in an inverse order, which leads to the rendered image has image size `640 x 480 x 3` (the expected size would be `480 x 640 x 3`).

**Comment by nikhilaravi** [comment]
@dingdingcai good catch! You are correct, this line should be `height, width = rasterizer.raster_settings.image_size` to match the documentation. 

https://github.com/facebookresearch/pytorch3d/blob/13429640d3dfcdf20dc3645d74b621f5fb4faee5/pytorch3d/renderer/points/pulsar/unified.py#L83

https://github.com/facebookresearch/pytorch3d/blob/13429640d3dfcdf20dc3645d74b621f5fb4faee5/pytorch3d/renderer/mesh/rasterize_meshes.py#L60-L61

We will add a fix!

**Comment by nikhilaravi** [comment]
This has now been fixed in https://github.com/facebookresearch/pytorch3d/commit/4bb3fff52b7e26ec0f013021cb26fab7db3d8e0b.
