### ISSUE TITLE
Rendering a Ply mesh

### ISSUE THREAD

**Issue by Zumbalamambo** [facebookresearch/pytorch3d#572]
I have checked the docs but I coudn't find an example that shows how I can render both Pointcloud as well as an image at the corner as I saw in an example video. Please point me the url that has the examples of rendering

**Comment by nikhilaravi** [comment]
We don't have example code for this in PyTorch3D currently. A naive way to do this would be to have a figure with two subplots in matplotlib (with the image in one subplot and the rendered mesh image in the other subplot), then save out all the figures (`fig.save(...)`) and then concat the images into a gif.
