### ISSUE TITLE
NeRF data not accessible

### ISSUE THREAD

**Issue by wolterlw** [facebookresearch/pytorch3d#573]
I am getting a `<Code>AccessDenied</Code>` error when trying to download NeRF project data.

**Comment by davnov134** [comment]
Hi, can you please let us know which downloaded file causes the error? Thanks!

**Comment by wolterlw** [comment]
that's what happens right after I click on the link, or is there a specific way I have to download files from S3?

**Comment by nikhilaravi** [comment]
@wolterlw if you follow the instructions in the readme to train on the two example datasets (lego/fern) then the data should be downloaded automatically. You don't have to download them manually by clicking on the s3 bucket. 

See here: https://github.com/facebookresearch/pytorch3d/blob/9c161d1d040e83c65b934b5a1312c17899e9b565/projects/nerf/nerf/dataset.py#L80-L82

**Comment by wolterlw** [comment]
understood, thank you
please do specify that in the readme.
In my case, I simply wanted to check how Pytorch3D camera pose format is different, without cloning the repo.

**Comment by amberhappy** [comment]
Sorry, I can download lego.pth correctly, but lego.png got ConnectionError.
