### ISSUE TITLE
Question about how to render a batch of vertexes?

### ISSUE THREAD

**Issue by hanssssssss** [facebookresearch/pytorch3d#574]
I used pytorch3d to render a batch of vertexs of human faces.I created a 'TexturesVertex' object with a batch of textures(N,V,3) , and uesd to creat a Meshes(with a batch of vertexes(N,V,3)). I wished to get a output  of (N,W,H,4) that are N rgba images, but I only got (1,W,H,4). I had no idea about the problem.

Thanks.

Here are my code.

`  

        n_vex = int(facemodel.idBase.shape[0] / 3)
        face_shape_r = torch.reshape(face_shape,[batch_size,n_vex,3])
        face_color_r = torch.reshape(face_color,[batch_size,n_vex,3])
        face_buf = (facemodel.face_buf - 1).int()  # index start from 1
        face_idx = face_buf.unsqueeze(0)

        face_color = TexturesVertex(verts_features=face_color_r.to(device))
        mesh_face = Meshes(face_shape_r.to(device), face_idx.to(device), face_color)

        R, T = look_at_view_transform(eye=((0, 0, 10.0),), at=((0, 0, 0),), up=((0, 1., 0),))

        cameras = OpenGLPerspectiveCameras(
            device=device,
            znear=0.01,
            zfar=60.,
            aspect_ratio=1.,
            fov=12.5936,
            R=R, T=T
        )

        # Define the settings for rasterization and shading. Here we set the output image to be of size
        raster_settings = RasterizationSettings(
            image_size=224,
            blur_radius=0.0,
            faces_per_pixel=1,
        )

        # Place a point light in front of the object. As mentioned above, the front of the cow is facing the
        lights = PointLights(
            device=device,
            ambient_color=((0.8, 0.8, 0.8),),
            location=((0.0, 0.0, 1e5),),
            diffuse_color=((0.0, 0.0, 0.0),)
        )

        renderer = MeshRenderer(
            rasterizer=MeshRasterizer(
                cameras=cameras,
                raster_settings=raster_settings
            ),
            shader=SoftPhongShader(
                device=device,
                cameras=cameras,
                lights=lights
            )
        )

        img_rgba=renderer(mesh_face)`

**Comment by nikhilaravi** [comment]
Hi @hanssssssss, can you print the shapes of some of the tensors to check the dimensions are correct e.g. 
```
print(mesh_face.faces_padded().shape)
print(cameras.R.shape)
```

If you can provide the input data we can try to reproduce the issue using the code you have provided.
