### ISSUE TITLE
How to get face_normal with pytorch3d ?

### ISSUE THREAD

**Issue by cuge1995** [facebookresearch/pytorch3d#578]

**Comment by nikhilaravi** [comment]
@cuge1995 you can get the face normals for meshes using the methods on the Meshes object e.g. `faces_normals_packed`, `faces_normals_padded`, `faces_normals_list`:

https://github.com/facebookresearch/pytorch3d/blob/4bb3fff52b7e26ec0f013021cb26fab7db3d8e0b/pytorch3d/structures/meshes.py#L726-L763
