### ISSUE TITLE
Can I generate ‘Non-smooth’ surfaces likes open3D 

### ISSUE THREAD

**Issue by GYTuuT** [facebookresearch/pytorch3d#579]
I want to generate images with regular faces looks like below, what is a result of open3D. Can pytorch3d achieve it?  Thanks !
![Screenshot from 2021-03-02 10-33-57](https://user-images.githubusercontent.com/54807945/109587938-e251c600-7b42-11eb-934d-69d23f1ccd3b.png)

**Comment by nikhilaravi** [comment]
Yes you can use flat shading which will compute the face color using the face normals. See this table with all the shading options currently available: https://github.com/facebookresearch/pytorch3d/blob/master/docs/notes/renderer_getting_started.md#a-custom-shader

**Comment by GYTuuT** [comment]
got it, thanks!
