### ISSUE TITLE
Error in class transforms.Translate

### ISSUE THREAD

**Issue by hfutcgncas** [facebookresearch/pytorch3d#58]
## 🐛 Error in class **pytorch3d.transforms.Translate**

I suppose the “translate” part should be in the last column of matrix, not in the last row. 

## Instructions To Reproduce the Issue:
when I wrote the code like this:
```
import pytorch3d.transforms as p3d_t
t = p3d_t.Transform3d().translate(1,2,3)
print(t.get_matrix())
```
I got
```
tensor([[[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.],
         [1., 2., 3., 1.]]])
```

while I suppose the correct response should be 
```
tensor([[[1., 0., 0., 1.],
         [0., 1., 0., 2.],
         [0., 0., 1., 3.],
         [0., 0., 0., 1.]]])
```

I suppose chang the ```mat[:, :3, 3]``` to ```mat[:, 3, :3]``` in line 388 and 394 of  pytorch3d.transforms would fix it.

**Comment by nikhilaravi** [comment]
@hfutcgncas this just depends on whether you are using row-major or column-major ordering. As explained in the [`__init__` function of the `Translate` class](https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/transforms/transform3d.py#L110), we assume row-major ordering. 

See [this guide](https://www.scratchapixel.com/lessons/mathematics-physics-for-computer-graphics/geometry/row-major-vs-column-major-vector) for a more detailed explanation.

**Comment by hfutcgncas** [comment]
Thank you very much for the explanation.

**Comment by hfutcgncas** [comment]
I still have a problem here. In the case of using row-major,  I suppose the  matrix of **RotateAxisAngle(a, axis="X")** should be like 
```
m = [ [1,       0,       0,     0],
      [0,  cos(a),  sin(a),     0],
      [0, -sin(a),  cos(a),     0],
      [0,       0,       0,     1]]
```
but in [the code of RotateAxisAngle](https://github.com/facebookresearch/pytorch3d/blob/97acf16de248ff799d068380a347651916968edb/pytorch3d/transforms/transform3d.py#L519) it is write like 
```
m = [ [1,       0,       0,     0],
      [0,  cos(a), -sin(a),     0],
      [0,  sin(a),  cos(a),     0],
      [0,       0,       0,     1]]
```
Is there something wrong or I got some mistake about the Coordinate Systems?

**Comment by nikhilaravi** [comment]
@hfutcgncas you're right, thanks for pointing this out. If we assume row-major ordering, a right hand coordinate system and that positive angles result in counter clockwise rotation then we need to transpose the rotation matrix as you mentioned. I will make the fix ASAP.

**Comment by nikhilaravi** [comment]
@hfutcgncas This fix has now been landed.
