### ISSUE TITLE
How to deform the source mesh to form a target mesh in batch ?

### ISSUE THREAD

**Issue by cuge1995** [facebookresearch/pytorch3d#580]

**Comment by nikhilaravi** [comment]
@cuge1995 please provide more information when opening an issue. Do you mean fit meshes via rendering or with known 3D target shapes without rendering? We have two example tutorials for both these methods:

Fit a source mesh to a target mesh without rendering: https://pytorch3d.org/tutorials/deform_source_mesh_to_target_mesh 
Fit a source mesh with texture to a target mesh via rendering: https://pytorch3d.org/tutorials/fit_textured_mesh

**Comment by cuge1995** [comment]
hey, yes, it is [Fit a source mesh to a target mesh without rendering: https://pytorch3d.org/tutorials/deform_source_mesh_to_target_mesh](https://pytorch3d.org/tutorials/deform_source_mesh_to_target_mesh)

**Comment by cuge1995** [comment]
It was hard to perform batch on it for the verts of meshes are different.

**Comment by gkioxari** [comment]
@cuge1995 
You are not providing enough details for us to help you. You are linking to a tutorial that we wrote. I am closing this issue. If you wish to report issues, please provide a compact code snippet and the data that will allow us to reproduce the problem  along with a concrete description of the problem.

**Comment by sainatarajan** [comment]
Hi @gkioxari @nikhilaravi 

I think what he means is this:

Let's take an example of the ShapeFC model with training batch_size set to anything more than 1, let's say 4. His question is how do we create 4 source meshes and then deform them using the offsets predicted by the network? Do we create and deform in a loop or is there any other optimized way?

 For a batch size of 4, the ShapeFC model produces an output of shape `[4, 642, 3]` which corresponds to the offsets. Is there any optimized way of creating and deforming 4 spheres?

**Comment by culurciello** [comment]
I am also wondering if this is possible to extend the example above to have a batch of meshes to run offset_verts on. What do you recommend is the best way?

**Comment by sainatarajan** [comment]
@culurciello Maybe [this](https://github.com/facebookresearch/pytorch3d/blob/main/docs/notes/batching.md) could help you.
