### ISSUE TITLE
Converting a Mesh to an SDF

### ISSUE THREAD

**Issue by srxdev0619** [facebookresearch/pytorch3d#584]
## ❓ Converting a Mesh to an SDF

Hi! 

First up, thanks for creating this library! I was just wondering if there's a way to generate an SDF given a Mesh? More specifically, the Mesh is that of a human head (as shown in the image below). 

<img width="1226" alt="ScreenShot 2021-03-03 at 12 11 41 PM" src="https://user-images.githubusercontent.com/9676573/109843927-a3db0a80-7c19-11eb-935e-0fb75b782c0e.png">

I've tried using [`_PointFaceDistance`](https://github.com/facebookresearch/pytorch3d/blob/327bd2b9762c05ec7a6f74c2ec1e46f2a764e326/pytorch3d/loss/point_mesh_distance.py#L21) to calculate the SDF as follows 1) Calculate the distance between a query point and the triangle closest to it 2) Determining whether or not the point is inside the mesh and assigning the sign appropriately (+ve outside, -ve inside). Running marching cubes using this SDF gives me a shape as shown below:

<img width="1226" alt="ScreenShot 2021-03-03 at 12 13 06 PM" src="https://user-images.githubusercontent.com/9676573/109844123-d422a900-7c19-11eb-94b8-bbdab1d59f09.png">

I'm not sure why the result is such, it be great if you folks could let me know if there's a more straightforward/correct way to do this. Thanks!

**Comment by gkioxari** [comment]
Hi @srxdev0619 
I think this is a great topic to put up in discussions instead of an issue.
It doesn't seem that this is an issue with the library, but instead you are trying to figure out how to get something done. Starting a discussion might get users more involved in helping you out than the issues page.

**Comment by srxdev0619** [comment]
Sure, thanks for the reply! Will do!

**Comment by cajoek** [comment]
Hi @srxdev0619, did you manage to create a SDF from a mesh? How did you do it and how did you render it? I can't find your discussion

Thanks!
