### ISSUE TITLE
How to get the uv positions of vertices in a torch tensor effectively?

### ISSUE THREAD

**Issue by aGIToz** [facebookresearch/pytorch3d#586]
Hello all,
Big thanks for your endeavors in bringing machine learning to 3D world !

Here is my question :
I load an obj file.
```python
verts, faces, aux = load_obj("obj.obj")
```
I can easily check
![image](https://user-images.githubusercontent.com/38216671/110165140-c3795b00-7df2-11eb-914d-ea645531eb64.png)

I can also see each face is composed by which nodes and which texture_ids : 
![image](https://user-images.githubusercontent.com/38216671/110165407-2cf96980-7df3-11eb-8c07-d8a43f2a9a08.png)

Above here,  one can see that the zeroth face (faces[0]) is constructed of the vertices [1,2,0] and texture_idx [0,1,2].

From the `faces.texture_idx` and `aux.verts_uv` I can find uv position of the each face 
![image](https://user-images.githubusercontent.com/38216671/110166086-20c1dc00-7df4-11eb-946b-27a12dd064d9.png)

Like above here, I look for position of the zeroth face in the uv plane and `aux.verts_idx[0], aux.verts_idx[1]` and `aux.vert_idx[2]` gives me the position of the faces[0] in the uv plane (*if I am wrong here then please correct me*).

Also by looking at `faces.verts_idx[0]` and `faces_texture_idx[0]`, I understand that vertex 1 corresponds to texture_idx 0 (and so vertices 2 and 0 to texture_idx 1 and 2 respectively ). Which means that uv position of the vertex 1 is given by `aux.verts_uvs[0]` i.e. `tensor([0.9934, 0.4822])` and hence for the other two vertices 2 and 0,  I can get their uv position (*again, correct if I am wrong here*).

My question is **how to get the those uv positions of all the vertices [0, 1, 2, 3, ... 117] in a torch tensor?** I can think of way in loops, but is there an effective way get the uv positions of the vertices?

**Comment by nikhilaravi** [comment]
@aGIToz so if I understand correctly you want to get the `(V, 2)` tensor of the uv coordinate for each vertex in the mesh?  When using a uv representation of texture, you are not guaranteed to have the same uv coordinate for each vertex. That's why the indices of the `faces.textures_idx` into `aux.verts_uvs` can be different from the `faces_verts_idx`. 

https://github.com/facebookresearch/pytorch3d/blob/95707fba1c8eff99757691468f440f9ce63c8027/pytorch3d/io/obj_io.py#L168-L173

What is your use case for needing the uv coordinate per vertex?

**Comment by aGIToz** [comment]
*The use case is; if  I have uv position coordinates per vertex then I can get the textures associated with the vertices from the aux.texture_images (the texture map). This allows me to convert the obj mesh to point cloud with texture (color) per vertex.*

I need it as I work on textured point cloud and often I am looking for a particular kind of texture to validate an algorithm, and often I find those textures in .obj files.

I do see your point that `T > V` , when a vertex is shared by multiple faces it may have different uv position coordinates, in that case one can go for average value of texture in texture map corresponding to each uv position.

**Comment by gkioxari** [comment]
Hi @aGIToz 
If I understand correctly, this is not an issue with the library but you are seeking for help on how to get something done. While we appreciate you posting here, I think the Discussions forum in github is a better place for such questions than the issue page which is for bugs or feature requests for PyTorch3d. 

If I am mistaken and this is a bug report, please provide a reproducible test case with a compact code snippet and data that will allow us to get to the error.

**Comment by aGIToz** [comment]
Hello,
Yup you are right this is exactly: *How to do X with torch3d?*

I was not aware of the **Discussions tab**, I apologize for positing it here. I will move it there.

But apparently  when one creates a new issue from the **Issues tab** it also shows this option of *How do i do X ..*
![image](https://user-images.githubusercontent.com/38216671/110229168-d5005700-7f07-11eb-9e08-1357d5f27b3d.png)

**Comment by aGIToz** [comment]
Moved to [discussion-588](https://github.com/facebookresearch/pytorch3d/discussions/588)
