### ISSUE TITLE
Points_normal coordinate frame

### ISSUE THREAD

**Issue by dd292** [facebookresearch/pytorch3d#592]
## ❓ Questions on how to use PyTorch3D

I am a bit confused about the output of the estimate_pointcloud_normals function. Is the output of the function in the camera coordinate frame or the local coordinate frame of that specific point?
Also, I think it's a unit vector but would be great if you can confirm that. 

Thanks.

**Comment by gkioxari** [comment]
The normals are in the same space your vertices/points are. 
You can check yourself whether the normals are unit vectors by computing their norm.
