### ISSUE TITLE
Is it possible to generate UV coordinates from Mesh data

### ISSUE THREAD

**Issue by orangeagain** [facebookresearch/pytorch3d#599]
## 🚀 Feature
Can anyone give an example of an UV unwarping example?

## Motivation
UV unwarping is a big problem for art and game developers.
People have been using algorithms or manual UV spreading for decades,and machine learning has never set foot in this field.
I personally believe that the addition of machine learning will be faster and better than those old algorithms in mobile device,and Helps drive the development of AR.

## Pitch

Input:
Mesh Data(Vertex[] and Triangles[])

Output:
UV coordinates(Float2[])

**Comment by nikhilaravi** [comment]
@orangeagain this question is better suited for the [Discussions][https://github.com/facebookresearch/pytorch3d/discussions) tab. 

To clarify your question do you also have a texture map for which you are trying to get the UV coordinates?

**Comment by orangeagain** [comment]
> @orangeagain this question is better suited for the [Discussions][https://github.com/facebookresearch/pytorch3d/discussions) tab.
> 
> To clarify your question do you also have a texture map for which you are trying to get the UV coordinates?

No,not require texture map.
Texture map is to be generated by uv map.so we need uv position first.

**Comment by orangeagain** [comment]
And maybe we can use existing algorithms to generate UV output to make a big training set.
