### ISSUE TITLE
pix_to_face gets all -1

### ISSUE THREAD

**Issue by lawy623** [facebookresearch/pytorch3d#602]
## 🐛 Bugs / Unexpected behaviors

I am using pytorch3d for rendering. I am good to follow the tutorial in pytorch3d and render the cow. But when I want to customize the use of it, I get unknown error that the rendering image has nothing.

I am rendering the smpl model and I suspect that a human mesh is rendered, but see nothing.
![image](https://user-images.githubusercontent.com/13533780/111128191-945fa800-85af-11eb-96f2-eba0c062326a.png)
But I can render it out using pyrender with same process.
![3dpw_vis_render_pyrender_test_rgb](https://user-images.githubusercontent.com/13533780/111131262-0980ac80-85b3-11eb-8cb6-eb4f135dafd8.png)

When I get into the functions, I found that verts_screen is ok, and every other things seems alright, but the result pix_to_face in rasterize_meshes.py is all -1. I am wondering that should be reason why I have no mesh on my image.

But why do I get this? I think the faces_verts looks correct to their pixel location on the image. But final pix_to_face are all -1. I also attach other params to the rasterize_mesh function.
![image](https://user-images.githubusercontent.com/13533780/111129280-de955900-85b0-11eb-970b-65a5d41f088b.png)
Can you tell me that is the -1 in pix_to_face making the final rendered image empty? And can you tell why this happened from what I have supplied? Is it about the depth of points? But since pyrender is okay, I don't think the values are problematic.

Here is also what I set for the settings.
![image](https://user-images.githubusercontent.com/13533780/111129630-464ba400-85b1-11eb-92f5-cd0fc8741bbf.png)

Thanks for looking into this!!

Yue

**Comment by nikhilaravi** [comment]
@lawy623 Can you check what `cameras.transform_points(verts)` gives you? Are the (x, y) values in the range (-1, 1)?
We also have a tutorial on how to render the SMPL model here: https://pytorch3d.org/tutorials/render_densepose so have a look at that as well.

**Comment by gkioxari** [comment]
You have likely not followed PyTorch3D coordinate system assumptions and have mesh vertices that lives in a different coordinate system than what we assume. Please look at our notes and notebooks to understand these things better.

**Comment by lawy623** [comment]
@nikhilaravi, I found the problem. I am using a PerspectiveCameras and specifying my own focal/principal points. when setting the camera, I do not input the **image_size**, so it believe is already in NDC space and do not normalize the projection matrix. Now is fine.

If possible, I believe it is necessary to provide some tutorial in PerspectiveCameras :).

Thanks and you can close the issue.
