### ISSUE TITLE
Quantitative performance measure for the NERF implementation

### ISSUE THREAD

**Issue by zhangmozhe** [facebookresearch/pytorch3d#604]
## ❓ Quantitative performance measure for the NERF implementation

Thanks for releasing the NERF implementation using Open3D. I wonder whether the quantitative performance matches the original implementation? Adding such quantitative measurement will definitely help increase the impact for the project. And It will be nice to add a description about whether there is any simplification or difference in this implementation. 

BTW, the S3 bucket link for the dataset file (https://dl.fbaipublicfiles.com/pytorch3d_nerf_data) does not work.

Thanks for the explanation!

**Comment by nikhilaravi** [comment]
@zhangmozhe you can access the data files following this format:

https://github.com/facebookresearch/pytorch3d/blob/ff9c6612b457a2021d88fea119bdb9b94ba017bd/projects/nerf/nerf/dataset.py#L148-L155

e.g. the lego cameras are at: https://dl.fbaipublicfiles.com/pytorch3d_nerf_data/lego_cameras.pth. 

@davnov134 compared with the original NeRF implementation and can provide more details about performance.

**Comment by zhangmozhe** [comment]
Cool. Thanks for your reply.

**Comment by zhangmozhe** [comment]
When I open the link (https://dl.fbaipublicfiles.com/pytorch3d_nerf_data/lego_cameras.pth.), it prompts:
![image](https://user-images.githubusercontent.com/10203551/111411067-deae6980-8714-11eb-9cf4-c5693e85982c.png)

**Comment by bottler** [comment]
It's https://dl.fbaipublicfiles.com/pytorch3d_nerf_data/lego.pth . The code for downloading it is right.

**Comment by nikhilaravi** [comment]
@bottler thanks, I have updated my previous comment with the correction!

**Comment by davnov134** [comment]
> ## ❓ Quantitative performance measure for the NERF implementation
> Thanks for releasing the NERF implementation using Open3D. I wonder whether the quantitative performance matches the original implementation? Adding such quantitative measurement will definitely help increase the impact for the project. And It will be nice to add a description about whether there is any simplification or difference in this implementation.
> 
> BTW, the S3 bucket link for the dataset file (https://dl.fbaipublicfiles.com/pytorch3d_nerf_data) does not work.
> 
> Thanks for the explanation!

@zhangmozhe we have now updated the readme file with a quantitative comparison to the official TensorFlow implementation.

**Comment by zhangmozhe** [comment]
Great! Thanks for your update about this! BTW, is there any plan to support multi-GPU training using DDP?

**Comment by davnov134** [comment]
It is not on our immediate roadmap, but we will definitely consider this as it seems like a very useful addition.

**Comment by nikhilaravi** [comment]
@zhangmozhe thanks for the suggestion. We will definitely plan to add this support. I will close this issue now that the performance information has been added.
