### ISSUE TITLE
Could pytorch3d support PyTorch 1.8?

### ISSUE THREAD

**Issue by ChenJoya** [facebookresearch/pytorch3d#605]
There are some days that PyTorch 1.8 released. Could this repo, pytorch3d support PyTorch 1.8 and provide a easy install pip wheels? I am looking forward to it. Thank you!

**Comment by bottler** [comment]
PyTorch3D works fine with PyTorch 1.8.0 and if you can build it yourself you can use the combination right now. When the next release of PyTorch3D happens I expect it will have wheels, at least for the upcoming PyTorch 1.8.1. 

We have a nightly build, which is just conda packages at the moment. I expect we will add PyTorch 1.8 support to those soon.

**Comment by nikhilaravi** [comment]
@ChenJoya please follow the instructions in [`INSTALL.md`](https://github.com/facebookresearch/pytorch3d/blob/master/INSTALL.md) for how to build the library from local clone.

**Comment by ManifoldFR** [comment]
Any news on having prebuilt binaries (on PyPi or conda) that support 1.8 ? Also the instructions in the `INSTALL.md` require a few changes for some environments, I think depending on whether one can install `cudatoolkit-dev` to get CUB from there or from the system packages

**Comment by bottler** [comment]
Nightly builds now support PyTorch 1.8.0, 1.8.1 and 1.9.0, and the next release will too.
