### ISSUE TITLE
Given a 2D image with multiple objects, how can I convert these objects to (textureless) meshes?

### ISSUE THREAD

**Issue by monacv** [facebookresearch/pytorch3d#606]
Is PyTorch3D able to do what the neural renderer in https://github.com/JiangWenPL/multiperson/tree/master/neural_renderer is doing in converting a 2D object in a 2D image to 3D mesh? If so, could you please provide pointers to an example code?

**Comment by nikhilaravi** [comment]
@monacv please have a look at:
-  The PyTorch3D [tech report](https://arxiv.org/abs/2007.08501. 
) which has details of how to use PyTorch3D for single image 3D reconstruction using differentiable rendering. We will release the code for this soon. 
- [Mesh R-CNN](https://github.com/facebookresearch/meshrcnn), which also reconstructs objects in 3D and uses PyTorch3D but doesn't use differentiable rendering. 

Are you looking for a pretrained model or to train a model yourself?

**Comment by gkioxari** [comment]
@monacv 
Please read our tech report that has a comprehensive analysis (quantitative and qualitative) to SoftRas. The comparison with NMS vs. SoftRas has been provided by the SoftRas tech paper and the differences in the two rendering pipelines are quite stark (NMR renders one face per pixel - NMR, SoftRas renders all faces per pixel - PyTorch3D renders K faces per pixel).

As a side note, I want to mention that the github issue page is meant to be for reporting erros or bugs in the library. For any discussions or questions on modern literature, Github Discussions is the more appropriate place.
