### ISSUE TITLE
Get intrinsic matrix of cameras

### ISSUE THREAD

**Issue by faneggs** [facebookresearch/pytorch3d#611]
Hi,
I used a set of camera location to initialize cameras. How to get intrinsic matrices same as the following of these cameras by Pytorch3D?

![image](https://user-images.githubusercontent.com/55543262/111658979-cdb24500-8847-11eb-8c97-88b31aac56c9.png)

```
R, T = look_at_view_transform(eye=xyz, up=((1, 0, 0),), device=device)
cameras = FoVPerspectiveCameras(device=device, R=R, T=T)
```

**Comment by gkioxari** [comment]
`cameras.get_projection_transform()` will return a `Transform3d` with the `K` matrix

https://github.com/facebookresearch/pytorch3d/blob/6c4151a820658168dd56b85f21b60e6bcf599c92/pytorch3d/renderer/cameras.py#L879

**Comment by faneggs** [comment]
> `cameras.get_projection_transform()` will return a `Transform3d` with the `K` matrix
> 
> https://github.com/facebookresearch/pytorch3d/blob/6c4151a820658168dd56b85f21b60e6bcf599c92/pytorch3d/renderer/cameras.py#L879

Thanks for your reply~
But I used `cameras.get_projection_transform()` and got an matrix with shape (4,4), but I want get a camera intrinsics matrix with shape (3,3). Do you know get it?
