### ISSUE TITLE
Huge error after 150 iteration in fit_textured_mesh.ipynb running the code as it is

### ISSUE THREAD

**Issue by Sarathcani999** [facebookresearch/pytorch3d#612]
The error running the notebook after 150th iteration was exponential, in the notebook "fit_textured_mesh.ipnyb" ( https://pytorch3d.org/tutorials/fit_textured_mesh ) without changing a line, I run the same code before 3 months and I got small error, but now not getting the same.

![image](https://user-images.githubusercontent.com/47141174/111835904-957c3680-891b-11eb-9121-91a66c2a6efe.png)

**Comment by gkioxari** [comment]
Please check this issue https://github.com/facebookresearch/pytorch3d/issues/561 and set the `perspective_correct` flag to False.

**Comment by Sarathcani999** [comment]
Thanks !!
