### ISSUE TITLE
How do I save the obj_file each time after the iter is updated?

### ISSUE THREAD

**Issue by naotoadachi** [facebookresearch/pytorch3d#620]
I would like to save the result plot image and obj_file

EACH AFTER the iter nomber is updated.

**Comment by naotoadachi** [comment]
I'm sorry for not mention about my question in detail.

I study deform_source_mesh_to_target_mesh script.

I want to save not only the final mesh, but also save the mesh obj_file that is on optimizing loop.

**Comment by nikhilaravi** [comment]
@naotoadachi you can just copy the code for saving the obj (in the last cell of the notebook) into the optimization for loop at the end of the loop. 

If you don't want to save it on every iteration then you can add it in Section 3 e.g. after the mesh is plotted:

```
    # Plot mesh
    if i % plot_period == 0:
        plot_pointcloud(new_src_mesh, title="iter: %d" % i)

        # Save obj
    
        # Fetch the verts and faces of the predicted mesh
        iter_verts, iter_faces = new_src_mesh.get_mesh_verts_faces(0)
        
        # Scale normalize back to the original target size
        iter_verts = iter_verts * scale + center
        
        # Store the predicted mesh using save_obj
        iter_obj = os.path.join('./', 'model_iter_%d.obj' % i)
        save_obj(iter_obj, iter_verts, iter_faces)
```
