### ISSUE TITLE
Why mesh is padded with zero vectors?

### ISSUE THREAD

**Issue by yogeshhk** [facebookresearch/pytorch3d#626]
Zero vector itself represents an Origin point which is a valid data.
By artificially padding with Zero vectors, you are essentially adding multiple Origin points (and Zero area corresponding faces?). This looks wrong, geometry due to multiplicity of overlapping Origin points.

Need to avoid mixing real Origin points in the mesh and artificially added padded Origins.

Possible way out (not sure about its feasibility and efficacy):
- Instead of Zero vector padding, do using some characters. No numerals should be used as they themselves become valid geometric points.
- All the calculations, ie forward and backward propagation weights updates, should be avoided/skipped for 'letter' inputs, during that batch.
- In the next batch, if the inputs become valid points, then they should participate in the calculations.

**Comment by gkioxari** [comment]
Zero padding is used when batching meshes of different topologies and geometries. Please read this note for further details:

https://github.com/facebookresearch/pytorch3d/blob/master/docs/notes/batching.md

The padding should not affect the mesh representation as the faces which index into the vertices define the geometry. The padded vertices do not correspond to any actual vertices in the mesh as no face is indexing into them. The padded values do not affect anything in any computation and don't lead to wrong results. Their sole purpose is to make a 3D or 4D tensor.

**Comment by yogeshhk** [comment]
Got it, thanks @gkioxari
