### ISSUE TITLE
How to remove triangles with big edges?

### ISSUE THREAD

**Issue by elcronos** [facebookresearch/pytorch3d#627]
## ❓ Questions on how to use PyTorch3D

I'm working on a dataset with 3d meshes of faces. Unfortunately, all the 3D meshes seems to have some strange triangles between the shoulders and the head (See Image below). Since the problem is from the data I am using and not Pytorch3D, I was wondering if there is any operation that I can use with Pytorch3D to remove big triangles where the edges exceed a threshold. So I would be able to remove those strange triangles programatically for all meshes loaded. Any suggestions?

<img width="680" alt="Screen Shot 2021-04-07 at 1 29 18 am" src="https://user-images.githubusercontent.com/9023043/113755365-d27d6100-9742-11eb-9063-03f273dfe6b6.png">

**Comment by gkioxari** [comment]
Since this is not an issue with PyTorch3D, could you move this question to the Discussions feature in github? Thank you!
