### ISSUE TITLE
`Transform3d.to()` ignores `dtype` changes if `device` unchanged and `copy=False` (the default)

### ISSUE THREAD

**Issue by AndreiBarsan** [facebookresearch/pytorch3d#633]
## 🐛 Bugs / Unexpected behaviors

Converting back and forth between the `dtypes` used by a `Transform3d` should not care about the device, but currently it does. Changing, e.g., a transform from float32 to float64 only works when _also_ changing the device, or when `copy=True` is set explicitly, which can be a bit confusing to some users.

This can cause numerical problems in code. For example, `numerically_sensitive_stuff(pose.to(dtype=torch.float64))` will  currently not do what the programmer would expect, operating on 32-bit representations.

## Instructions To Reproduce the Issue:

Clean commands:
```python
import torch
from pytorch3d.transforms import Transform3d
t = Transform3d()
print(t.get_matrix().dtype)
print(t.to(dtype=torch.float64, device="cpu").get_matrix().dtype)
```

Commands with output:
```python
>>> import torch
>>> from pytorch3d.transforms import Transform3d
>>> t = Transform3d()
>>> t.get_matrix().dtype
torch.float32
>>> t.to(dtype=torch.float64, device="cpu").get_matrix().dtype
torch.float32   # oh no!
```

## Potential Solution

The culprit seems to be [here](https://github.com/facebookresearch/pytorch3d/blob/24ee279005c2c893f2f005837528e351b3168ad7/pytorch3d/transforms/transform3d.py#L418). That line should probably also check whether the dtype is also unchanged.

**Comment by patricklabatut** [comment]
This bug should now have been fixed on the master branch (see the associated [tests](https://github.com/facebookresearch/pytorch3d/blob/master/tests/test_transforms.py#L45)). Thanks for reporting it!

**Comment by AndreiBarsan** [comment]
Awesome to hear Patrick! Thank you!  🎉
