### ISSUE TITLE
conda install pytorch3d -c pytorch3d-nightly 

### ISSUE THREAD

**Issue by lee9871** [facebookresearch/pytorch3d#636]
## ❓ Questions on how to use PyTorch3D

NOTE: Please look at the existing list of Issues tagged with the label ['question`](https://github.com/facebookresearch/pytorch3d/issues?q=label%3Aquestion) or ['how-to`](https://github.com/facebookresearch/pytorch3d/issues?q=label%3A%22how+to%22). **Only open a new issue if you cannot find an answer there**.

Also note the following:

1. If you encountered any errors or unexpected issues while using PyTorch3D and need help resolving them,
   please use the "Bugs / Unexpected behaviors" issue template.

2. We do not answer general machine learning / computer vision questions that are not specific to
	 PyTorch3D, such as how a model works or what algorithm/methods can be
	 used to achieve X.

**Comment by lee9871** [comment]
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - pytorch3d

**Comment by bottler** [comment]
Please describe your environment, i.e. what you did to set it up. And what command produced that output. Please paste the output of `conda list`.

(The issue template is information for you, so you can help us help you. It is not for you to copy back to us.)

**Comment by nikhilaravi** [comment]
@lee9871 please provide the information as requested by @bottler  or close this issue if you don't need help any more.
