### ISSUE TITLE
The Parameters aspect_ratio of class pytorch3d.renderer.cameras.FoVPerspectiveCameras is not for pixel. I think it may be for image and equal to the image_width/image_height.  From the experiment you can get image without stretching or compressing only if I set the aspect_ratio = image_width/image_height.

### ISSUE THREAD

**Issue by HuangWei93** [facebookresearch/pytorch3d#637]
## ❓ Questions on how to use PyTorch3D

NOTE: Please look at the existing list of Issues tagged with the label ['question`](https://github.com/facebookresearch/pytorch3d/issues?q=label%3Aquestion) or ['how-to`](https://github.com/facebookresearch/pytorch3d/issues?q=label%3A%22how+to%22). **Only open a new issue if you cannot find an answer there**.

Also note the following:

1. If you encountered any errors or unexpected issues while using PyTorch3D and need help resolving them,
   please use the "Bugs / Unexpected behaviors" issue template.

2. We do not answer general machine learning / computer vision questions that are not specific to
	 PyTorch3D, such as how a model works or what algorithm/methods can be
	 used to achieve X.

**Comment by gkioxari** [comment]
The description of the issue is not enough for me to able to help you. 
Could you please provide a compact code snippet that reproduces your issue and the result you get vs what you expected. Thank you!
