### ISSUE TITLE
how to implement customized projection such as spherical projection?

### ISSUE THREAD

**Issue by xiaoaoran** [facebookresearch/pytorch3d#640]
Pytorch3D has two camera types (orthographic/perspective), both project 3D mesh/point cloud into a plane. If I want to do a different projection approach, such as spherical projection, how can I implement it? Can I use existing function in Pytorch3D?

I would appreciate it if you provide me some solutions.

**Comment by nikhilaravi** [comment]
@xiaoaoran You can define your own camera which can do this. We provide some example camera implementations but this is  designed to be easily extensible.  You can create a class which inherits from `CamerasBase` and then define the relevant functions. e.g in your case you might want to change the `get_projection_transform()` method. 

### References
These are the cameras we have available: https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/renderer/cameras.py
Here is a useful reference on the camera conventions: https://github.com/facebookresearch/pytorch3d/blob/master/docs/notes/cameras.md

**Comment by xiaoaoran** [comment]
@nikhilaravi Thank you very much, I will try this.

**Comment by nikhilaravi** [comment]
@xiaoaoran please reopen the issue if you have any further questions.

**Comment by dengchcs** [comment]
> @nikhilaravi Thank you very much, I will try this.

Hi @xiaoaoran , have you implemented the spherical projection? Since this is a non-linear transformation but pytorch3d's `get_projection_transform()` returns a `Transform3d` object, I think it is not impossible to implement this projection?
