### ISSUE TITLE
Can PyTorch3D resize a mesh like we always do for 2D image?

### ISSUE THREAD

**Issue by Wi-sc** [facebookresearch/pytorch3d#641]
For 2D tasks, we can always resize an image into 224*224 so it's more convenient to process for CNN. So I'm wondering if Pytorch3D can also resize any mesh into a new mesh with fixed vertices number?

**Comment by gkioxari** [comment]
Yes you can scale a mesh. 

https://github.com/facebookresearch/pytorch3d/blob/4a9e294436bdd26bcc7332bdb805cac7c717e4e2/pytorch3d/structures/meshes.py#L1350-L1359

**Comment by Wi-sc** [comment]
Sorry for my ambiguity. What I want to ask is that how to change the vertices number to a fixed number. For instance, I have 2 meshes with 100 vertices and 200 vertices respectively, can pytorch3d change them into 2 new meshes with 50 vertices? I don't want to discard their connection,  so sampling into the point cloud is not disered.
