### ISSUE TITLE
Sign issue about quaternion_to_matrix and matrix_to_quaternion

### ISSUE THREAD

**Issue by sailor-z** [facebookresearch/pytorch3d#646]
## 🐛 Bugs / Unexpected behaviors

Hi, Thanks for releasing the amazing project. I'm trying to use "quaternion_to_matrix" and "matrix_to_quaternion" to transform the rotation matrix. The initial rotation is acquired by 

R, T = look_at_view_transform(distance, elevation, azimuth, device=device).
(https://pytorch3d.org/tutorials/camera_position_optimization_with_differentiable_rendering)

Then I perform quaternion_to_matrix and matrix_to_quaternion as

R = matrix_to_quaternion(R)
R = quaternion_to_matrix(R)

Ideally, the transformed matrix should be identical to the initial one, but I found that there is a sign issue like

![image](https://user-images.githubusercontent.com/26895204/115014836-227ec500-9eb3-11eb-9cdd-2340462b8135.png)

How can I solve this problem?

Bests

**Comment by bottler** [comment]
Thanks for reporting this. I agree that there is a problem with `matrix_to_quaternion` when the input is a 180° rotation. Specifically the output gets the right elements but elements get the wrong signs in general. Those two matrices are 180° rotations around different axes. `matrix_to_quaternion` returns the same output for both, which is only correct for the second.

**Comment by sailor-z** [comment]
> Thanks for reporting this. I agree that there is a problem with `matrix_to_quaternion` when the input is a 180° rotation. Specifically the output gets the right elements but elements get the wrong signs in general. Those two matrices are 180° rotations around different axes. `matrix_to_quaternion` returns the same output for both, which is only correct for the second.

Thanks for your reply. How can I solve this problem?

**Comment by bottler** [comment]
> Thanks for your reply. How can I solve this problem?

It should be fixed inside PyTorch3D, but this will not be immediate. If you describe what you are doing, we might be able to find a workaround for your specific case. Or are you wondering how you might help fix it in the code?

**Comment by sailor-z** [comment]
> > Thanks for your reply. How can I solve this problem?
> 
> It should be fixed inside PyTorch3D, but this will not be immediate. If you describe what you are doing, we might be able to find a workaround for your specific case. Or are you wondering how you might help fix it in the code?

Thanks. I'm doing something about optimizing the camera postions.  Given an initial rotation represented by a rotation matrix, first I use "matrix_to_quaternion" to convert it to a quaternion; then some noise is added to this quaternion which generates a new rotation; Finally, the noised quaternion is converted back to a rotation matrix using "quaternion_to_matrix". Ideally, the finial result should be identical to the initial one in the noise-free case.

**Comment by bottler** [comment]
So you could maybe change representations: e.g. use quaternions everywhere, or do the noise in the rotation_6d representation. Or if you know you are working near a 180° rotation, factor it out.

**Comment by shapovalov** [comment]
Fixed by https://github.com/facebookresearch/pytorch3d/commit/1b39cebe9209172e543bdb9cd4d890d4023d5caf
