### ISSUE TITLE
bug in class PointLights (function diffuse & function specular) for multi-light scene

### ISSUE THREAD

**Issue by yoterel** [facebookresearch/pytorch3d#647]
Hello,
Since for now I can't submit a pull request (CLA required), I'm reporting a bug when rendering a multi light scene and also how to fix it here.

To produce this bug, follow these instructions:
1) Create a scene with a mesh and extend to some batch size bigger than 1.
2) Create a PointLights object, but for the location parameter, pass in a tensor in the size of your batch (batch x 3), make sure the locations are different, so you can witness how the bug occurs.
3) Render the scene (for the RasterizationSettings, pass faces_per_pixel = 1 for this example).
4) Behold the render fail.

Why this happens:
Since the functions "diffuse" and "specular" compute the tensor:
`directions = self.location - points`
where points dimensions are (batch_size x w x h x k=1 x 3), and self.location dimensions are (batch_size x 3)
the resulting tensor (directions) is shaped  (batch_size x w x h x batch_size x 3) as opposed to the desired (batch_size x w x h x k=1 x 3) result.

How to fix:
We must broadcast correctly when subtracting self.location and points. I suggest using torch.view on self.location with (batch_size x 1 x 1 x 1 x 3) and only then subtracting.

If we don't yet "support" a multi - light environment, it is too bad, because this small change means we do support it so lets do this :)

**Comment by gkioxari** [comment]
HI @yoterel 
We will look into it. Thank you for reporting the issue.

**Comment by nikhilaravi** [comment]
@yoterel thanks for the detailed explanation, we will look into this issue.

**Comment by tau-yihouxiang** [comment]
@gkioxari @nikhilaravi Could you solve this problem. I also meet the same issue in v0.4:
      "direction = self.location - points
       RuntimeError: The size of tensor a (16) must match the size of tensor b (50) at non-singleton dimension 3 "

**Comment by yoterel** [comment]
I made it work by replacing this:
`direction = self.location - points`
with these two lines instead:
`n, w, h, k, c = points.shape`
`direction = self.location.view(n, 1, 1, 1, c) - points`

you'll have to replace this in both diffuse and specular, and you need to also fix "_apply_lighting" by replacing:
`diffuse_color = materials.diffuse_color * light_diffuse`
 `specular_color = materials.specular_color * light_specular`
with:
`diffuse_color = materials.diffuse_color.view(n, 1, 1, 1, c) * light_diffuse`
 `specular_color = materials.specular_color.view(n, 1, 1, 1, c) * light_specular`

lastly in your shader (e.g. phong_shading) you'll have to replace:
`colors = (ambient + diffuse) * texels + specular`
with:
`colors = (ambient.view(ambient.shape[0], 1, 1, 1, ambient.shape[-1]) + diffuse) * texels + specular`

Note:
this assumes you passed a correct materials argument to the shader, for example:

`materials = Materials(device=device, shininess=torch.ones(batch_size) * 64)`

if you don't, it won't work.

**Comment by tau-yihouxiang** [comment]
> I made it work by replacing this:
> `direction = self.location - points`
> with these two lines instead:
> `n, w, h, k, c = points.shape`
> `direction = self.location.view(n, 1, 1, 1, c) - points`
> 
> you'll have to replace this in both diffuse and specular, and you need to also fix "_apply_lighting" by replacing:
> `diffuse_color = materials.diffuse_color * light_diffuse`
> `specular_color = materials.specular_color * light_specular`
> with:
> `diffuse_color = materials.diffuse_color.view(n, 1, 1, 1, c) * light_diffuse`
> `specular_color = materials.specular_color.view(n, 1, 1, 1, c) * light_specular`
> 
> lastly in your shader (e.g. phong_shading) you'll have to replace:
> `colors = (ambient + diffuse) * texels + specular`
> with:
> `colors = (ambient.view(ambient.shape[0], 1, 1, 1, ambient.shape[-1]) + diffuse) * texels + specular`
> 
> Note:
> this assumes you passed a correct materials argument to the shader, for example:
> 
> `materials = Materials(device=device, shininess=torch.ones(batch_size) * 64)`
> 
> if you don't, it won't work.

@yoterel wow, thank you for your answer!

**Comment by tau-yihouxiang** [comment]
@gkioxari @nikhilaravi Thank you for your contribution, while  I don't think v0.4 is stable.

**Comment by nikhilaravi** [comment]
@tau-yihouxiang we will fix it asap! Thanks for reporting it!

**Comment by nikhilaravi** [comment]
This issue should now be fixed by https://github.com/facebookresearch/pytorch3d/commit/bc8361fa471e39280b1c5e3717309167b08ffed5.
