### ISSUE TITLE
get 3d world coords of a point on the mesh hit with raycast through a given pixel

### ISSUE THREAD

**Issue by fairydora** [facebookresearch/pytorch3d#650]
## ❓ Questions on how to use PyTorch3D

Hello :)
I've got a camera, 3d mesh, image size and 2D coordinates of a pixel on the image (I've got (x, y), but no depth). 
I would like to do an inverse projection - ray cast from the camera through the pixel to hit the mesh, to get the 3d world coords of the very point on the mesh which would have been projected onto this very pixel with "transform_points_screen". Is this possible with pytorch3d?... 
Thank you for help!

**Comment by nikhilaravi** [comment]
@fairydora do you mean you want to unproject the (x, y) point into 3D with the known camera? We have a method on the cameras class called [`unproject_points`](https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/renderer/cameras.py#L79-L119) which may be useful.

**Comment by fairydora** [comment]
Hi Nikhila,
Yes, I've seen this example :)
xyz_unproj_world = cameras.unproject_points(xy_depth, world_coordinates=True)

The unproject_points requires depth with the input 2d points, which I haven't got because the point I want to cast through has not been projected. I've only got coords (x, y) coming from a landmark detection. 

Instead, I've got a new mesh to hit as an input. Nothing has been projected from this mesh on this camera screen. 
So the known inputs are: camera, (x,y) on the screen, mesh.

**Comment by bottler** [comment]
Can you run the `rasterize_meshes` with the camera and the new mesh? Then the first and third outputs (`pix_to_face` and `barycentric`) at the (x,y) value you care about tell you the face index and the barycentric coordinates of the point concerned. You can then weight the vertex locations of that face by the barycentric coordinates (either manually or using the interpolate_face_attributes function) to get the 3D world coordinates you are looking for.

**Comment by fairydora** [comment]
This is exactly what I was looking for!  thank you so much for your advice @bottler and @nikhilaravi :) :)
