### ISSUE TITLE
Cannot render textures from Shapenet models

### ISSUE THREAD

**Issue by sarathcani** [facebookresearch/pytorch3d#651]
I put both the models folder and images folder into the data path, but when I try to render the model it renders the model without texture. Whereas I can view the model with texture with the Windows 3d viewer.

I used Phong Shader

Result I am getting :

![image](https://user-images.githubusercontent.com/59505833/115337232-36317080-a1be-11eb-9448-02c681fee333.png)

Target Result

![image](https://user-images.githubusercontent.com/59505833/115337107-0bdfb300-a1be-11eb-994b-db5b54344c03.png)

**Comment by gkioxari** [comment]
Could you point us to the data/model ID you are rendering? Does it have a texture file (texture is present usually as mtl files - but not all ShapeNet models have it). If it has a texture file, do you make sure you read it when loading the mesh?
