### ISSUE TITLE
Misalignment when rendering with rectangular image

### ISSUE THREAD

**Issue by Len-Li** [facebookresearch/pytorch3d#656]
## 🐛 Misalignment when rendering with rectangular image

I try to render a mesh with a resolution of 1242*375, given camera parameter of fx,fy,px,py. I also project each vertex into image plane using camera matrix. However, they don't show similar appereance.
In the image, pink points are projected vertex, white object is rendered cow. The rendered result may be not a rectangular image but a squere image after stretching. I follow [this](https://github.com/facebookresearch/pytorch3d/blob/master/docs/notes/cameras.md)(the last part) to set PerspectiveCameras.

![cow](https://user-images.githubusercontent.com/40287745/116098437-a91a7a00-a6dd-11eb-8f15-5a1ad227bcce.png)

Here is my code.

```python
import os
import cv2
import torch
import numpy as np
from pytorch3d.io import load_objs_as_meshes, load_obj
from pytorch3d.structures import Meshes
from pytorch3d.renderer import (
    PerspectiveCameras,
    PointLights,
    RasterizationSettings,
    MeshRenderer,
    MeshRasterizer,
    SoftPhongShader,
    TexturesVertex,
    BlendParams,
)
device = torch.device("cpu")

DATA_DIR = "pytorch3d/docs/tutorials/data"
obj_filename = os.path.join(DATA_DIR, "cow_mesh/cow.obj")
verts, faces, aux = load_obj(obj_filename)

faces_idx = faces.verts_idx.to(device)
faces_idx = faces_idx.repeat(1,1,1)
app_col_vert = torch.ones((1, verts.size(0), 3)).to(device).float()
tex = TexturesVertex(verts_features=app_col_vert)

verts[:, 0] += 2   # x and z axis translation
verts[:, 2] += 5

verts = verts.unsqueeze(0)
mesh = Meshes(verts=verts.clone(), faces=faces_idx, textures=tex)

# fx, fy = 600, 600
# px, py = 300, 300   # squere image well behaved, but rectangular image is not
# height=600
# width=600
fx, fy = 7.215377000000e+02, 7.215377000000e+02
px, py = 6.095593000000e+02, 1.728540000000e+02
height = 375
width = 1242
K = [
        [fx,   0,   px],
        [0,   fy,   py],
        [0,    0,    1],
]
cam_mat_33 = np.array(K)
cam_mat_33 = torch.from_numpy(cam_mat_33).to(device)
cam_mat_33 = cam_mat_33.unsqueeze(0)

# matrix multiplication with coordinate changed from kitti format to pytorch3d format
verts_copy = verts.clone()
verts_copy[:, :, 0] = -verts_copy[:, :, 0]
verts_copy[:, :, 1] = -verts_copy[:, :, 1]
vert_cam2 = torch.bmm(verts_copy.float(), cam_mat_33.float().permute(0, 2, 1))

rgb_img = np.zeros((height,width,3))

# colorize each vertex
pix_x, pix_y = vert_cam2[..., 0] / vert_cam2[..., 2], vert_cam2[..., 1] / vert_cam2[..., 2]
pix_x = pix_x[0].detach().cpu().numpy()
pix_y = pix_y[0].detach().cpu().numpy()
for j in range(pix_x.shape[0]):
    rgb_img = cv2.circle(rgb_img, (pix_x[j], pix_y[j]), 2, (255, 0, 255), 0)

cameras = PerspectiveCameras(
    focal_length=((fx, fy),),
    principal_point=((px, py),),
    image_size=((width, height), )
    )
raster_settings = RasterizationSettings(
    image_size=(height, width),
    blur_radius=0.0,
    faces_per_pixel=1,
    )
lights = PointLights(device=device, location=[[0.0, 0.0, -3.0]])
blend_params = BlendParams(background_color=(0, ) * 3)

renderer = MeshRenderer(
    rasterizer=MeshRasterizer(
        cameras=cameras,
        raster_settings=raster_settings),
    shader=SoftPhongShader(
        device=device,
        cameras=cameras,
        lights=lights,
        blend_params=blend_params))

images = renderer(mesh)
images = images.squeeze().cpu().numpy()[..., :3]*255
cv2.imwrite('cow.jpg', images+rgb_img)
```
I also render the same object using squere config(see fx,fy), which shows no problem.

**Comment by nikhilaravi** [comment]
Please see this issue for an explanation of how to set the camera parameters for the non square case when the cameras are defined in screen space vs NDC space: https://github.com/facebookresearch/pytorch3d/issues/548

**Comment by Len-Li** [comment]
> Please see this issue for an explanation of how to set the camera parameters for the non square case when the cameras are defined in screen space vs NDC space: #548

Thanks for your reply. I reset my camera as mention in [#548 ](https://github.com/facebookresearch/pytorch3d/issues/548). However, it doesn't change anything. I set my camera in NDC space, the behavior shows the same in screen space. What am I missing?

```python
cameras = PerspectiveCameras( 
    focal_length=((fx/(width/2.), fy/(height/2.)),),  # fx = fx_screen / half_imwidth, 
                                        # fy = fy_screen / half_imheight 
    principal_point=((-(px-width/2.) / (width/2.), -(py-height/2.) / (height/2.)),),  # px = - (px_screen - half_imwidth) / half_imwidth, 
                                # py = - (py_screen - half_imheight) / half_imheight 
) 
```

**Comment by Len-Li** [comment]
> > Please see this issue for an explanation of how to set the camera parameters for the non square case when the cameras are defined in screen space vs NDC space: #548
> 
> Thanks for your reply. I reset my camera as mention in [#548 ](https://github.com/facebookresearch/pytorch3d/issues/548). However, it doesn't change anything. I set my camera in NDC space, the behavior shows the same in screen space. What am I missing?
> 
> ```python
> cameras = PerspectiveCameras( 
>     focal_length=((fx/(width/2.), fy/(height/2.)),),  # fx = fx_screen / half_imwidth, 
>                                         # fy = fy_screen / half_imheight 
>     principal_point=((-(px-width/2.) / (width/2.), -(py-height/2.) / (height/2.)),),  # px = - (px_screen - half_imwidth) / half_imwidth, 
>                                 # py = - (py_screen - half_imheight) / half_imheight 
> ) 
> ```

Finally I solved this problem.
Note that the above code have a little bug,  fx should equal to fx_screen / half_imheight instead of fx_screen / half_imwidth, which results streaching effect. Same as principal_point. 
```python
cameras = PerspectiveCameras(focal_length=((fx / (height/2.), fy/(height/2.)),),
             principal_point=((-(px-width/2.) / (height/2.), -(py-height/2.) / (height/2.)),), 
)
```
After that, the point and mesh align perfectly.
@gkioxari Please update the documentation if I make a clear elaboration.

![ttt](https://user-images.githubusercontent.com/40287745/117470718-b3643000-af89-11eb-82d2-9c6d85e44a9f.png)
