### ISSUE TITLE
How to render Pointcloud without mesh

### ISSUE THREAD

**Issue by hihunjin** [facebookresearch/pytorch3d#661]
## ❓ Questions on how to use PyTorch3D

![image](https://user-images.githubusercontent.com/32363064/116509274-faa14f80-a8fd-11eb-936c-317cc8bd5e38.png)
Using plotly, I plot my Point Cloud. 
My question : How to nicely render this Point Cloud without mesh, nicely looking connected surface?

I know this question is silly but, wonder if there is a way. We don't need to have a texture in this case in my opinion.

ps.
I think my question is equivalent to asking how to get surface mesh from pointcloud in my opinion.

**Comment by hihunjin** [comment]
I found this [issue](https://github.com/facebookresearch/pytorch3d/issues/136#issuecomment-607570336).
Is there any update?

**Comment by bottler** [comment]
(This is a followup question from #660.) 


One thing you might be happy with is replacing the "points" in the plot with filled-in cubes. I don't think plotly can do this easily, but matplotlib has this feature https://matplotlib.org/stable/gallery/mplot3d/voxels.html .

I wonder if a plotly volume plot of the original data would be helpful. See https://plotly.com/python/3d-volume-plots/ and also isosurface plots.
