### ISSUE TITLE
Where is the original paper of the sample_points_from_meshes functions?

### ISSUE THREAD

**Issue by cuge1995** [facebookresearch/pytorch3d#662]

**Comment by cuge1995** [comment]
or why this function is differentiable?

**Comment by bottler** [comment]
The function does something very simple - it picks random points uniformly distributed on a mesh. This idea could be used in many papers. Why would the procedure be expected to have a particular paper? 

The function is only differentiable, and can only be differentiable, in the simplest sense. Specifically, an output point varies smoothly when you move the vertices of its face, while fixing its barycentric coordinates, and this gives a derivative of each output point with respect to relevant vertices of the input mesh. Nothing more complicated than that. (In particular, if you use the function to do a Monte-Carlo integration to evaluate some integral over the mesh, which is a valid thing to do, you can't expect the gradient to work.)
