### ISSUE TITLE
Camera parameters in Pytorch3D NeRF implementation

### ISSUE THREAD

**Issue by markovka17** [facebookresearch/pytorch3d#664]
Hi,

I tried to train NeRF from "pytorch3d/projects/nerf/" and encountered that the data is different from the original data of their paper. I found that "The S3 bucket files contains the same images while the camera matrices have been adjusted to follow the PyTorch3D convention", so could you help me how to convert camera parameters from "pytorch3d" format to original?

**Comment by gkioxari** [comment]
The following note describes the camera conventions in PyTorch3D which should be useful in understanding how to convert coordinate systems of a dataset to PyTorch3D

https://github.com/facebookresearch/pytorch3d/blob/master/docs/notes/cameras.md

**Comment by yuhez** [comment]
> The following note describes the camera conventions in PyTorch3D which should be useful in understanding how to convert coordinate systems of a dataset to PyTorch3D
> 
> https://github.com/facebookresearch/pytorch3d/blob/master/docs/notes/cameras.md

Thank you for the webpage. However, it seems that the link to the public S3 bucket: https://dl.fbaipublicfiles.com/pytorch3d_nerf_data is not reachable ("AccessDenied"). Is it public available?

**Comment by bottler** [comment]
Various files within that are available - they get [downloaded by the code](https://github.com/facebookresearch/pytorch3d/blob/master/projects/nerf/nerf/dataset.py).

**Comment by nikhilaravi** [comment]
@markovka17 do you still need help with this issue?
