### ISSUE TITLE
Rendering ShapeNetCore.v2

### ISSUE THREAD

**Issue by HectorAnadon** [facebookresearch/pytorch3d#666]
## How to render ShapeNetCore.v2

Hello, trying to render ShapeNetCore.v2 as realistic as possible. I might be missing some hyperparameters like in RasterizationSettings e.g. `max_faces_per_bin` or `bin_size=0` or `texture_resolution` in `pytorch3d.datasets.ShapeNetCore`.

Here is the code following [this tutorial](https://github.com/facebookresearch/pytorch3d/blob/master/docs/tutorials/dataloaders_ShapeNetCore_R2N2.ipynb):

```
shapenet_dataset = ShapeNetCore('/mnt/storage/ShapeNetCore.v2', synsets=['sofa'],
                                    version=2, texture_resolution=100)

# Rendering settings.
R, T = look_at_view_transform(1.0, 30.0, 180)
cameras = FoVPerspectiveCameras(R=R, T=T, device=device)
raster_settings = RasterizationSettings(image_size=512) #  max_faces_per_bin=50000, bin_size=0
lights = PointLights(location=torch.tensor([0.0, 1.0, -2.0], device=device)[None],device=device)

images_by_model_ids = shapenet_dataset.render(
    model_ids=[
        "d21b63623023b40a593ebeeedbff73b",
    ],
    device=device,
    cameras=cameras,
    raster_settings=raster_settings,
    lights=lights,
)
image_grid(images_by_model_ids.cpu().numpy(), rows=1, cols=3, rgb=True)
```

Here is the pytorch3d result: 
![render_pytorch3d](https://user-images.githubusercontent.com/12595599/117167451-8c5e0080-adc7-11eb-98ff-c5332d28c81d.png)

And here is the rendering in meshlab:
![Screenshot from 2021-05-05 17-31-18](https://user-images.githubusercontent.com/12595599/117167684-c29b8000-adc7-11eb-9ec7-bae857dde2be.png)

What am I doing wrong? Thanks for your help!

**Comment by gkioxari** [comment]
It appears to be an issue with the texture. For some reason, the texture is not loaded correctly. Could you share the model (obj and texture) here so that I take a look? Thank you!

**Comment by HectorAnadon** [comment]
I am using the sofa class that can be downloaded [here ](http://shapenet.cs.stanford.edu/shapenet/obj-zip/04256520.zip). I have issues with all the objects (at least the ones I have tested). The exact object of the example `d21b63623023b40a593ebeeedbff73b `can be downloaded [here](https://www.dropbox.com/s/iuo3q98kvy7ru4e/d21b63623023b40a593ebeeedbff73b.zip?dl=0).

**Comment by HectorAnadon** [comment]
I am still experiencing this issue

**Comment by demiantill** [comment]
I'm also finding that objects from ShapeNetCore aren't rendered correctly. I've tried following the same [tutorial](https://github.com/facebookresearch/pytorch3d/blob/master/docs/tutorials/dataloaders_ShapeNetCore_R2N2.ipynb) as @HectorAnadon. It appears that most objects get assigned textures from other objects. Some objects get assigned the correct textures e.g. 

![plate](https://user-images.githubusercontent.com/2950746/123985537-73d02800-d9bd-11eb-819d-740cb19955e7.jpeg)
 But even these objects still suffer from the lighting issues that can be seen in the image above.

**Comment by ck-amrahd** [comment]
I am experiencing the same issue with the ShapaNet car objects.

**Comment by ck-amrahd** [comment]
It has been 2 months since this issue was raised. The problem still exists and there's no response.

**Comment by gkioxari** [comment]
We are looking into this now.

**Comment by gkioxari** [comment]
Some preliminary findings. I don't think this is an issue with PyTorch3D. I think some ShapeNet meshes are poorly designed leading to bad renderings. For example, the sofa model by @HectorAnadon renders as shown below in MeshLab with the `Vert` shading mode. Note that the `Vert` shading mode is close to Phong shader in PyTorch3D.

<img width="702" alt="Screen Shot 2021-07-15 at 5 39 52 PM" src="https://user-images.githubusercontent.com/4369065/125806991-46a2f032-e38c-498a-86bf-5d07059996e5.png">

I will investigate the offending obj more and will report back.

**Comment by ck-amrahd** [comment]
Turns out it's not a problem in pytorch3d, but the shapenet models being messy. I tried on meshlab and if I select face shading instead of vert shading, the problem goes out. The messy shapenet models don't allow for smooth interpolation of face normals. I used hardflatshader and changed some lighting parameters, and it is solved now. Thank you.

**Comment by ColleenKuang** [comment]
> 

Hi, Do you have any update on this issue? I am working on the Shapenet.v2 and facing the same problem.
The rendering result doesn't look good. There are lot of noisy point in the result image.
![Snipaste_2022-08-19_12-55-09](https://user-images.githubusercontent.com/13173313/185548345-3239f8ae-4bbb-4d81-8256-691b2618261d.png)

Here's my part of the code
```
cameras = cameras_from_opencv_projection(R=R_batch, tvec=T_batch, camera_matrix=K_batch, image_size=torch.tensor(image_size)[None]).to(device)
raster_settings = RasterizationSettings(
        image_size=image_size,
        blur_radius=0.0,
        faces_per_pixel=1,
        max_faces_per_bin=50000,
        bin_size=-1
    )
    # Initialize rasterizer by using a MeshRasterizer class
rasterizer = MeshRasterizer(
        cameras=cameras,
        raster_settings=raster_settings
    )
shader = HardFlatShader(device=device, cameras=cameras, lights=lights)
renderer = MeshRendererWithFragments(rasterizer, shader)
image,fragment = renderer(mesh)
```
