### ISSUE TITLE
conda PackageNotFoundError

### ISSUE THREAD

**Issue by peterjohnsonhuang** [facebookresearch/pytorch3d#67]
I followed the instructions in INSTALL.md to create a new anaconda  env, and install the required packages by the instructions. However, when I use "conda install pytorch3d -c pytorch3d", 
I got 
PackageNotFoundError: Packages missing in current channels:            
  - pytorch3d -> pytorch 1.4
here is my result by typing conda list:
![image](https://user-images.githubusercontent.com/20748448/74633881-a1884880-519d-11ea-9967-4c28758edd32.png)

**Comment by bottler** [comment]
The list looks healthy - you have all the dependencies right in that list. (I know you are using a 64bit python on Linux because of the `ld` package.) There isn't an obvious problem.

Can you try `conda install -c pytorch3d pytorch3d --verbose` or `conda install -c pytorch3d pytorch3d --verbose --verbose`? Thanks

**Comment by peterjohnsonhuang** [comment]
when I try conda install -c pytorch3d pytorch3d --verbose, this is what happened:

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : 3.0.22
         python version : 3.6.2.final.0
       requests version : 2.18.4
       root environment : /home/pj/anaconda3  (writable)
    default environment : /home/pj/anaconda3/envs/pytorch3d
       envs directories : /home/pj/anaconda3/envs
                          /home/pj/.conda/envs
          package cache : /home/pj/anaconda3/pkgs
                          /home/pj/.conda/pkgs
           channel URLs : https://conda.anaconda.org/pytorch3d/linux-64
                          https://conda.anaconda.org/pytorch3d/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/3.6.2 Linux/5.3.10-arch1-1 arch/ glibc/2.30    
                UID:GID : 1004:1004

`$ /home/pj/anaconda3/envs/pytorch3d/bin/conda install -c pytorch3d pytorch3d --verbose`




    Traceback (most recent call last):
      File "/home/pj/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 261, in install
        channel_priority_map=_channel_priority_map, is_update=isupdate)
      File "/home/pj/anaconda3/lib/python3.6/site-packages/conda/plan.py", line 489, in install_actions_list
        for specs_by_prefix in required_solves]
      File "/home/pj/anaconda3/lib/python3.6/site-packages/conda/plan.py", line 489, in <listcomp>
        for specs_by_prefix in required_solves]
      File "/home/pj/anaconda3/lib/python3.6/site-packages/conda/plan.py", line 634, in get_actions_for_dists
        pkgs = r.install(specs, installed, update_deps=update_deps)
      File "/home/pj/anaconda3/lib/python3.6/site-packages/conda/resolve.py", line 813, in install
        pkgs = self.solve(specs, returnall=returnall)
      File "/home/pj/anaconda3/lib/python3.6/site-packages/conda/resolve.py", line 853, in solve
        reduced_index = self.get_reduced_index(specs)
      File "/home/pj/anaconda3/lib/python3.6/site-packages/conda/resolve.py", line 374, in get_reduced_index
        specs, features = self.verify_specs(specs)
      File "/home/pj/anaconda3/lib/python3.6/site-packages/conda/resolve.py", line 300, in verify_specs
        raise ResolvePackageNotFound(bad_deps)
    conda.exceptions.ResolvePackageNotFound: 
      - pytorch3d
      - pytorch 1.4
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/pj/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/pj/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/home/pj/anaconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/pj/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 275, in install
        raise PackageNotFoundError(pkg, channels_urls)
    conda.exceptions.PackageNotFoundError: Packages missing in current channels:
                
      - pytorch3d -> pytorch 1.4
    
    We have searched for the packages in the following channels:
                
      - https://conda.anaconda.org/pytorch3d/linux-64
      - https://conda.anaconda.org/pytorch3d/noarch
      - https://repo.continuum.io/pkgs/main/linux-64
      - https://repo.continuum.io/pkgs/main/noarch
      - https://repo.continuum.io/pkgs/free/linux-64
      - https://repo.continuum.io/pkgs/free/noarch
      - https://repo.continuum.io/pkgs/r/linux-64
      - https://repo.continuum.io/pkgs/r/noarch
      - https://repo.continuum.io/pkgs/pro/linux-64
      - https://repo.continuum.io/pkgs/pro/noarch

**Comment by bottler** [comment]
I can reproduce the error in `continuumio/miniconda3:4.3.27p0` from the docker hub, which matches the version of conda you are using.

Specifically
```
sudo docker run --rm -i -t continuumio/miniconda3:4.3.27p0
conda create -n h python=3.6
source activate h
conda install -c pytorch pytorch=1.4 torchvision
conda install -c conda-forge -c fvcore fvcore
conda install -c pytorch3d pytorch3d
```

If I do the same thing in continuumio/miniconda3:4.4.1, which is the next newer version which has an image available, it works.
(There are cudatoolkit discrepancies but I think that's not the main issue.)
My guess is that our installation instructions don't work on conda versions as old as yours. My guess as to why is as follows. When we rely on pytorch we ask for pytorch=1.4, and we rely on the fuzzy matching by which version 1.4.0 satisfies the requirement for 1.4. This fuzziness was introduced in conda 4.4.

**Comment by peterjohnsonhuang** [comment]
Ok, thank you for the reply and contribution. I will try again with newer versions!
