### ISSUE TITLE
Pytorch3D Google Colab - fit_textured_mesh.ipynb Tutorial not working?

### ISSUE THREAD

**Issue by armindocachada** [facebookresearch/pytorch3d#671]
Hello,

Thanks a lot for the great work that you have done with Pytorch3D and the tutorial!

I have tried the PyTorch3D tutorial **fit_textured_mesh.ipynb** on Google Colab. It doesn't seem to be working.
After iteration 0, the sphere mesh goes into oblivion and what we get is an empty mesh after running all the steps in the notebook.

![image](https://user-images.githubusercontent.com/37876786/117539621-67ee6800-b003-11eb-9a26-e1ce38749d50.png)

I attach a PDF output of running the notebook  and the final final mesh produced by the notebook. This occurred both on the stable branch and in master.

[fit_textured_mesh.ipynb_output.pdf](https://github.com/facebookresearch/pytorch3d/files/6445865/fit_textured_mesh.ipynb_output.pdf)

[final_model.obj.zip](https://github.com/facebookresearch/pytorch3d/files/6445867/final_model.obj.zip)

https://colab.research.google.com/github/facebookresearch/pytorch3d/blob/master/docs/tutorials/fit_textured_mesh.ipynb

**Comment by gkioxari** [comment]
Could you share what version of PyTorch3D you are using?

In particular, are you setting `perspective_correct` to False?

**Comment by armindocachada** [comment]
Hi Georgia,

The Google Colab notebook is somehow installing PyTorch3D from source. It seems to be using the stable branch in github:

  !pip install 'git+https://github.com/facebookresearch/pytorch3d.git@stable

In regards to **perspective_correct** where would that be set? I just ran the notebook from the tutorial without changing it, directly from master branch.

**Comment by gkioxari** [comment]
This is set in the rasterization settings of the renderer. 

This is bizarre. We will look into it. I recently taught a class and had student run this notebook and everything was fine.

**Comment by armindocachada** [comment]
Thanks. I will add that setting and see if it helps.
I already had to use the tutorial version in master instead of stable which
contains a fix to an exception.

**Comment by armindocachada** [comment]
After adding perspective_correct=False to the RasterizerSettings, I am now getting the Silhouetes of the sphere.
But the visualise_predictions method is failing. I have tried this locally in my PC

![image](https://user-images.githubusercontent.com/37876786/117573740-8cb11100-b0d1-11eb-9f46-5d8aac530f24.png)

**Comment by bottler** [comment]
Can you show the whole error? I think even the last line could be significant.
You may want to print `losses` just before this function to try to work out what has happened.
(That error looks like it is plot_losses, not visualize_predictions, which is failing.)

**Comment by armindocachada** [comment]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-e9db6de8db21> in <module>
      1 visualize_prediction(new_src_mesh, silhouette=True, 
      2                      target_image=target_silhouette[1])
----> 3 plot_losses(losses)

<ipython-input-8-3c6f12cadcfe> in plot_losses(losses)
     21     ax = fig.gca()
     22     for k, l in losses.items():
---> 23         ax.plot(l['values'], label=k + " loss")
     24     ax.legend(fontsize="16")
     25     ax.set_xlabel("Iteration", fontsize="16")

~\anaconda3\envs\kaolin\lib\site-packages\matplotlib\axes\_axes.py in plot(self, scalex, scaley, data, *args, **kwargs)
   1741         """
   1742         kwargs = cbook.normalize_kwargs(kwargs, mlines.Line2D)
-> 1743         lines = [*self._get_lines(*args, data=data, **kwargs)]
   1744         for line in lines:
   1745             self.add_line(line)

~\anaconda3\envs\kaolin\lib\site-packages\matplotlib\axes\_base.py in __call__(self, data, *args, **kwargs)
    271                 this += args[0],
    272                 args = args[1:]
--> 273             yield from self._plot_args(this, kwargs)
    274 
    275     def get_next_color(self):

~\anaconda3\envs\kaolin\lib\site-packages\matplotlib\axes\_base.py in _plot_args(self, tup, kwargs)
    389             y = _check_1d(tup[-1])
    390         else:
--> 391             x, y = index_of(tup[-1])
    392 
    393         if self.axes.xaxis is not None:

~\anaconda3\envs\kaolin\lib\site-packages\matplotlib\cbook\__init__.py in index_of(y)
   1641         pass
   1642     try:
-> 1643         y = _check_1d(y)
   1644     except (np.VisibleDeprecationWarning, ValueError):
   1645         # NumPy 1.19 will warn on ragged input, and we can't actually use it.

~\anaconda3\envs\kaolin\lib\site-packages\matplotlib\cbook\__init__.py in _check_1d(x)
   1293     """Convert scalars to 1d arrays; pass-through arrays as is."""
   1294     if not hasattr(x, 'shape') or len(x.shape) < 1:
-> 1295         return np.atleast_1d(x)
   1296     else:
   1297         try:

<__array_function__ internals> in atleast_1d(*args, **kwargs)

~\anaconda3\envs\kaolin\lib\site-packages\numpy\core\shape_base.py in atleast_1d(*arys)
     64     res = []
     65     for ary in arys:
---> 66         ary = asanyarray(ary)
     67         if ary.ndim == 0:
     68             result = ary.reshape(1)

~\anaconda3\envs\kaolin\lib\site-packages\numpy\core\_asarray.py in asanyarray(a, dtype, order, like)
    169         return _asanyarray_with_like(a, dtype=dtype, order=order, like=like)
    170 
--> 171     return array(a, dtype, copy=False, order=order, subok=True)
    172 
    173 

~\anaconda3\envs\kaolin\lib\site-packages\torch\tensor.py in __array__(self, dtype)
    628             return handle_torch_function(Tensor.__array__, relevant_args, self, dtype=dtype)
    629         if dtype is None:
--> 630             return self.numpy()
    631         else:
    632             return self.numpy().astype(dtype, copy=False)

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

**Comment by armindocachada** [comment]
Hi Jeremy, See stack trace above.
 I was able at least to get a fitted mesh with texture. But the texture, doesn't seem to be exported as part of the save_obj method?
Is there a way to do it so I can view it in Blender?

**Comment by stephentandjiria** [comment]
can confirm I got the same error:

```
...
D:\Anaconda3\envs\PyTorch3D_Test\lib\site-packages\torch\tensor.py in __array__(self, dtype)
    628             return handle_torch_function(Tensor.__array__, relevant_args, self, dtype=dtype)
    629         if dtype is None:
--> 630             return self.numpy()
    631         else:
    632             return self.numpy().astype(dtype, copy=False)

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
```

**Comment by ankus-wu** [comment]
I got the same error, and I chose to use this to finish the tutorial:
`-ax.plot(chamfer_losses, label="chamfer loss")`
`+ax.plot([c.detach().cpu() for c in chamfer_losses], label="chamfer loss")`

**Comment by bottler** [comment]
> I got the same error, and I chose to use this to finish the tutorial:
> `-ax.plot(chamfer_losses, label="chamfer loss")`
> `+ax.plot([c.detach().cpu() for c in chamfer_losses], label="chamfer loss")`

You mean in the deform meshes tutorial, right?

**Comment by ankus-wu** [comment]
> > I got the same error, and I chose to use this to finish the tutorial:
> > `-ax.plot(chamfer_losses, label="chamfer loss")`
> > `+ax.plot([c.detach().cpu() for c in chamfer_losses], label="chamfer loss")`
> 
> You mean in the deform meshes tutorial, right?

Yes, exactly.

**Comment by nikhilaravi** [comment]
This should now be fixed by https://github.com/facebookresearch/pytorch3d/commit/a343cf534cf906560a28f3a367c6ad1369100059.
