### ISSUE TITLE
convert matrix to euler angles and inverse conversion doesn't yield the same

### ISSUE THREAD

**Issue by justForAsk** [facebookresearch/pytorch3d#672]
Hi,

I've tried to convert rotation matrix to euler angles and convert back but it seems that
it doesn't the same:

`
R = torch.tensor([[ 0.7828,  0.1133,  0.6119],
        [-0.0249,  0.9882, -0.1512],
        [ 0.6218, -0.1031, -0.7764]])
(euler_angles_to_matrix(matrix_to_euler_angles(R,'XYZ'),'XYZ') - R).abs().max()
`

I got:
`tensor(1.9429)`

I used the same convention, perhaps I need to change to convention?
If not, does anyone has an idea why it doens't the same?

**Comment by bottler** [comment]
R is not a rotation matrix. Its determinant is approximately -1.

**Comment by justForAsk** [comment]
OK, I get that, thanks
