### ISSUE TITLE
Nerf: cusolve error for torch.inverse in transform3d.py

### ISSUE THREAD

**Issue by Timon-Hoefer** [facebookresearch/pytorch3d#674]
## 🐛 Bugs / Unexpected behaviors
I was running Nerf on Linemod object 2. The visualization gave me errors in the inverse calculation of torch.inverse() the following error appeared (in the file pytorch3d/transforms/transform3d.py)

    torch.inverse(self._matrix)
RuntimeError: cusolver error: 7, when calling `cusolverDnCreate(handle)`

Tracking the error gave me the following:
The value of self._matrix (line 241 in transform3d.py) is:
tensor([[[ 0.0403,  0.0000, -0.9992,  0.0000],
         [-0.0000,  1.0000,  0.0000,  0.0000],
         [ 0.9992,  0.0000,  0.0403,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  1.0000]]], device='cuda:0')

Applying torch.inverse will result in:

  File "/home/hoefer/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-0e40ae98013b>", line 1, in <module>
    torch.inverse(self._matrix)
RuntimeError: cusolver error: 7, when calling `cusolverDnCreate(handle)`

It was possible to calculate the inverse with numpy. Therefore I am using now the following workaround 

241 return torch.inverse(self._matrix) -->         num = np.array(self._matrix.cpu())
                                                                         x = np.linalg.inv(num)
                                                                         return torch.tensor(x).to(self._matrix.device)

Has anyone else experienced similiar problems or knows a reason for this?

**Comment by nikhilaravi** [comment]
Hi @Timon-Hoefer this seems to be an issue with PyTorch `inverse` function rather than PyTorch3D. How are you initializing the `Transform3d` class?

**Comment by Timon-Hoefer** [comment]
I also think it is an issue with PyTorch inverse forum.  I will therefore close this issue. Above is a working workaround - as it is used only while visualizing, the training time is not increased dramatically.

 "How are you initializing the Transform3d class?" I left everything unchanged.

**Comment by jasonyzhang** [comment]
I have had the same error before when my GPU was almost out of memory (e.g. less than 20 MB left on nvidia-smi). Calling `torch.cuda.empty_cache()` before fixes the problem for me, which suggests to me that Pytorch is not properly managing its cache when close to maximum memory reserved.
