### ISSUE TITLE
is it possible to improve the speed of the shaders?

### ISSUE THREAD

**Issue by WxComeon** [facebookresearch/pytorch3d#675]
Hello, thank you very much for this amazing library.

I am looking for ways to further improve rendering speed because I want to render images online while I am training neural networks.

Regarding the sizes of my model, there are about 100,000 faces and 60,000 points. For 64 images, it takes about 1.2 seconds, so about 19ms per image. I ran a cProfile on my code. It seems that the shader, rather than the rasterization, is taking a relatively longer time?

```
4666 function calls (4658 primitive calls) in 1.206 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
..........irrelevant ones omitted....
 1    0.000    0.000    1.189    1.189 rendering.py:73(img_rendering)
3/1    0.000    0.000    1.189    1.189 module.py:715(_call_impl)
  1    0.000    0.000    1.189    1.189 renderer.py:42(forward)
  1    0.000    0.000    1.167    1.167 shader.py:310(forward)
  8    0.000    0.000    1.151    0.144 meshes.py:894(_compute_packed)
  1    0.000    0.000    1.147    1.147 meshes.py:1502(sample_textures)
  4    0.000    0.000    1.142    0.286 meshes.py:540(faces_packed)
  2    0.000    0.000    1.134    0.567 meshes.py:465(verts_list)
  6    1.134    0.189    1.134    0.189 {method 'tolist' of 'torch._C._TensorBase' objects}
  1    0.000    0.000    0.021    0.021 rasterizer.py:132(forward)
  5    0.012    0.002    0.017    0.003 utils.py:115(list_to_packed)
  1    0.012    0.012    0.016    0.016 shading.py:141(flat_shading)
  1    0.000    0.000    0.013    0.013 rasterize_meshes.py:27(rasterize_meshes)
```

Here is my renderer settings. Are there ways to further improve the speed of the renderer? If not, would multi-GPU help with the speed?

```
def img_renderer(cam_dist = 350, cam_elev = 0, cam_azim = 0, img_size = 256, light_direction = ((0, 0, 10), ), ambient_color = ((0.5, 0.5, 0.5), ), diffuse_color = ((0.5, 0.5, 0.5), ), specular_color = ((0.15, 0.15, 0.15), ), background = (0.5,0.5,0.5), device = None):
    if device is None:
        device=torch.device('cuda:0')

    R, T = look_at_view_transform(cam_dist, cam_elev, cam_azim) 
    cameras = FoVPerspectiveCameras(device=device, R=R, T=T)
    
    # Black background
    blend_params = BlendParams(background_color=background)

    # Define the settings for rasterization
    raster_settings = RasterizationSettings(
        image_size=img_size,
        blur_radius=0.0,
        faces_per_pixel=1, 
    )

    lights = DirectionalLights(device=device, ambient_color=ambient_color, diffuse_color=diffuse_color, specular_color=specular_color, direction = light_direction)

    renderer = MeshRenderer(
        rasterizer= MeshRasterizer(cameras=cameras, raster_settings=raster_settings),
        shader = HardPhongShader(device=device, cameras=cameras, lights=lights, blend_params=blend_params)
    )

    return renderer
```

Thank you very much.

**Comment by bottler** [comment]
I think this trace is showing most time taken in the shader, which calls verts_packed, which calls verts_list, which in this case needs to call tolist on a very small CUDA tensor, which causes a synchronization where Python has to wait for the GPU to catch up. But the critical path could be somewhere else entirely.

If you haven't already, an interesting thing to do would be to rerun the profiling with the environment variable `CUDA_LAUNCH_BLOCKING` set to 1. (This makes every line of code pause until its calculation has actually finished on the GPU).

**Comment by gkioxari** [comment]
@bottler gave a great answer. 

Overall, your meshes are quite large so your best action forward is to profile the computation flow, based on @bottler's suggestion. When you identify the bottleneck you might want to consider a few things:
(a) If you have a desired shader you are using and you don't wish to experiment with different ones, you might want to move certain computations to CUDA. 
(b) If the bottleneck is not in the shader, you might want to consider some alternate behavior, e.g. if it's in the data structure conversion you might want to hack it or bypass it if you don't need all the batching modes in `Meshes` (i.e. list, packed, padded)

**Comment by nikhilaravi** [comment]
@WxComeon in addition to what @gkioxari and @bottler mentioned you could think about writing your own shader based on your use case?  Do you need to use phong shading or lighting? The Shader here applies lighting and then sets the color of the pixel to the closest face in the z direction. If you don't need lighting you can just turn that off completely and define a new shader which only applies the color from the closest face.

**Comment by WxComeon** [comment]
Hello, thank you very much for the suggestions! I indeed forgot to make sure of synchronization. I ran the profiling again, and the problem is not shader -- it is the rasterization. The shader is pretty fast! Sorry about that confusion. 

We also ran profiling of [the rasterize mesh function](https://pytorch3d.readthedocs.io/en/latest/_modules/pytorch3d/renderer/mesh/rasterize_meshes.html). 
A large amount of time is spent in line 300 of rasterize_meshes, the call to _C.rasterize_meshes in rasterize_meshes.py.
If this is the case, are there any more possible improvements?

```
Thu May 13 22:42:06 2021    gpu_render

         9048 function calls (9025 primitive calls) in 1.181 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
..........irrelevant ones omitted....
        1    0.000    0.000    1.161    1.161 rendering.py:71(img_rendering)
      3/1    0.000    0.000    1.160    1.160 module.py:715(_call_impl)
        1    0.000    0.000    1.160    1.160 renderer.py:42(forward)
        1    0.000    0.000    1.113    1.113 rasterizer.py:132(forward)
        1    0.001    0.001    1.102    1.102 rasterize_meshes.py:27(rasterize_meshes)
        2    0.000    0.000    1.084    0.542 {built-in method apply}
        1    0.000    0.000    1.084    1.084 rasterize_meshes.py:280(forward)
        **1    1.084    1.084    1.084    1.084 {built-in method pytorch3d._C.rasterize_meshes}**
        1    0.000    0.000    0.047    0.047 shader.py:175(forward)
        1    0.002    0.002    0.045    0.045 shading.py:87(gouraud_shading)
        5    0.019    0.004    0.030    0.006 utils.py:115(list_to_packed)
        8    0.002    0.000    0.029    0.004 meshes.py:894(_compute_packed)
        1    0.000    0.000    0.016    0.016 Face_19.py:32(generate_maps)
        3    0.000    0.000    0.015    0.005 meshes.py:497(verts_packed)
        3    0.000    0.000    0.014    0.005 meshes.py:540(faces_packed)
```

**Comment by nikhilaravi** [comment]
@WxComeon `_C.rasterize_meshes` is the call to the rasterization CUDA kernel so there aren't any easy optimizations here.  If you're interested, you could play around with some of the [`RasterizationSettings`](https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/renderer/mesh/rasterize_meshes.py#L66-L74) such as `bin_size` or `max_faces_per_bin` - currently they are set heuristically but you could try to set them for your use case.

**Comment by WxComeon** [comment]
@nikhilaravi Thank you very much. I managed to find settings of bin_size that works really fast (on a specific image size)!
