### ISSUE TITLE
Could not find name `_C` in `pytorch3d`

### ISSUE THREAD

**Issue by lu-ming-lei** [facebookresearch/pytorch3d#676]
pip install pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py36_cu101_pyt170/download.html
what should it be if my pytorch is cpu_only?

**Comment by bottler** [comment]
We don't have prebuilt packages which are cpu only. You have two options:
1) Build PyTorch3D from source. E.g. `pip install "git+https://github.com/facebookresearch/pytorch3d.git@stable"`. This will take a small number of minutes.

2) Even though you don't have a GPU and you don't install cuda, I think you can set up a separate conda environment with cudatoolkit and gpu-enabled versions of PyTorch and torchvision. Then you can install one of our GPU builds. As long as you keep all tensors on the CPU it should just work.
