### ISSUE TITLE
ModuleNotFoundError: No module named 'pytorch3d'

### ISSUE THREAD

**Issue by arita89** [facebookresearch/pytorch3d#677]
## after following step by step Installation.md still can not run pytorch3d in python notebook

I am working on this remote Linux server:
Operating System: Ubuntu 20.04.2 LTS
Kernel: Linux 5.8.0-50-generic
Architecture: x86-64

this is what I am doing: 

>conda create -n pytorch3d python=3.8
>conda activate pytorch3d
>conda install -c pytorch pytorch=1.7.1 torchvision cudatoolkit=10.2
>conda install -c fvcore -c iopath -c conda-forge fvcore iopath
>conda install -c bottler nvidiacub
>conda install jupyter
>pip install scikit-image matplotlib imageio plotly opencv-python
>pip install black 'isort<5' flake8 flake8-bugbear flake8-comprehensions

then i tried the following:
-conda install
>conda install pytorch3d -c pytorch3d
(installs, can see the package with !conda list, but returns error below -> uninstalling cause not working)

- pip install
>pip install "git+https://github.com/facebookresearch/pytorch3d.git"
(installs, can see the package with !pip list, but returns error below -> uninstalling cause not working)

- from the notebook
>version_str = "py38_cu102_pyt171"
>!pip install pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/{version_str}/download.html
(as above)

in all cases when running in the notebook 
>from pytorch3d.structures import Pointclouds 
I get: 
ModuleNotFoundError: No module named 'pytorch3d'

what to do? 
thanks

**Comment by bottler** [comment]
Uninstalling can be a bit dangerous and confusing. Can you start a new environment and do the first version. This should be enough 
```
conda create -n pytorch3d_new python=3.8
conda activate pytorch3d_new
conda install -c pytorch pytorch=1.7.1 torchvision cudatoolkit=10.2
conda install -c fvcore -c iopath -c conda-forge fvcore iopath
conda install pytorch3d -c pytorch3d
```

And then (1) check if you can do the import and (2) paste the output of `conda list` and `pip list` here.

**Comment by arita89** [comment]
sure, i try fresh. 5 minutes

**Comment by arita89** [comment]
>conda list
# packages in environment at  ../anaconda3/envs/pytorch3d_new:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
blas                      1.0                         mkl  
ca-certificates           2021.4.13            h06a4308_1  
certifi                   2020.12.5        py38h578d9bd_1    conda-forge
cudatoolkit               10.2.89              hfd86e86_1  
freetype                  2.10.4               h5ab3b9f_0  
fvcore                    0.1.5.post20210515            py38    fvcore
intel-openmp              2021.2.0           h06a4308_610  
iopath                    0.1.8                      py38    iopath
jpeg                      9b                   h024ee3a_2  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_1  
libuv                     1.40.0               h7b6447c_0  
lz4-c                     1.9.3                h2531618_0  
mkl                       2021.2.0           h06a4308_296  
mkl-service               2.3.0            py38h27cfd23_1  
mkl_fft                   1.3.0            py38h42c9631_2  
mkl_random                1.2.1            py38ha9443f7_2  
ncurses                   6.2                  he6710b0_1  
ninja                     1.10.2               hff7bd54_1  
numpy                     1.20.1           py38h93e21f0_0  
numpy-base                1.20.1           py38h7d8b39e_0  
olefile                   0.46                       py_0  
opencv-python             4.5.2.52                 pypi_0    pypi
openssl                   1.1.1k               h27cfd23_0  
pillow                    8.2.0            py38he98fc37_0  
pip                       21.0.1           py38h06a4308_0  
portalocker               1.7.0            py38h578d9bd_1    conda-forge
python                    3.8.8                hdb3f193_5  
python_abi                3.8                      1_cp38    conda-forge
pytorch                   1.7.1           py3.8_cuda10.2.89_cudnn7.6.5_0    pytorch
pytorch3d                 0.4.0           py38_cu102_pyt171    pytorch3d
pyyaml                    5.3.1            py38h8df0ef7_1    conda-forge
readline                  8.1                  h27cfd23_0  
setuptools                52.0.0           py38h06a4308_0  
six                       1.15.0           py38h06a4308_0  
sqlite                    3.35.4               hdfb4753_0  
tabulate                  0.8.9              pyhd8ed1ab_0    conda-forge
termcolor                 1.1.0                      py_2    conda-forge
tk                        8.6.10               hbc83047_0  
torchvision               0.8.2                py38_cu102    pytorch
tqdm                      4.60.0             pyhd8ed1ab_0    conda-forge
typing_extensions         3.7.4.3            pyha847dfd_0  
wheel                     0.36.2             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
yacs                      0.1.6                      py_0    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.9                haebb681_0  


>pip list
Package           Version
----------------- -------------------
certifi           2020.12.5
fvcore            0.1.5.post20210515
iopath            0.1.8
mkl-fft           1.3.0
mkl-random        1.2.1
mkl-service       2.3.0
numpy             1.20.1
olefile           0.46
opencv-python     4.5.2.52
Pillow            8.2.0
pip               21.0.1
portalocker       1.7.0
pytorch3d         0.4.0
PyYAML            5.3.1
setuptools        52.0.0.post20210125
six               1.15.0
tabulate          0.8.9
termcolor         1.1.0
torch             1.7.1
torchvision       0.8.2
tqdm              4.60.0
typing-extensions 3.7.4.3
wheel             0.36.2
yacs              0.1.6


now i can: 
- import pytorch3d 

but i cannot
- import cv2
and when running 
> from pytorch3d.renderer import (
    look_at_view_transform,
    OpenGLOrthographicCameras, 
    PointsRasterizationSettings,
    OpenGLPerspectiveCameras,
    SfMPerspectiveCameras,
    PointsRenderer,
    PointsRasterizer,
    AlphaCompositor,
    NormWeightedCompositor
)

I get 
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-11-8e6e0bbbdfe5> in <module>
      1 # Data structures and functions for rendering
      2 from pytorch3d.structures import Pointclouds
----> 3 from pytorch3d.renderer import (
      4     look_at_view_transform,
      5     OpenGLOrthographicCameras,

~/anaconda3/lib/python3.8/site-packages/pytorch3d/renderer/__init__.py in <module>
      1 # Copyright (c) Facebook, Inc. and its affiliates. All rights reserved.
      2 
----> 3 from .blending import (
      4     BlendParams,
      5     hard_rgb_blend,

~/anaconda3/lib/python3.8/site-packages/pytorch3d/renderer/blending.py in <module>
      7 
      8 # pyre-fixme[21]: Could not find name `_C` in `pytorch3d`.
----> 9 from pytorch3d import _C
     10 
     11 

ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory

**Comment by bottler** [comment]
(Worry about opencv after pytorch3d is sorted. Check carefully when you install it (e.g. via conda) that it doesn't change other packages.)
Those tracebacks are informative. They are looking in files like `~/anaconda3/lib/python3.8/site-packages/pytorch3d/renderer/blending.py`, which look like files in the base environment, not like files in the environment you have created and listed (which lives somewhere like `envs/pytorch3d_new`). Can you explain how this is happening? 
You probably want to ensure that you don't have pytorch3d, or anything much, in the base environment.

**Comment by arita89** [comment]
I have indeed some packages in the base env, I am removing them.

**Comment by arita89** [comment]
but I am not sure how, while being in the activated new environment, it seems the files looked for are the ones in the base

**Comment by arita89** [comment]
maybe its fixed after uninstalling all the pytorch&friends from base :D 

now i install all the other packages one by one... 
thank you :)

**Comment by arita89** [comment]
i confirm that it seems to work, bless you man! ^^
