### ISSUE TITLE
pytorch3d.ops.sample_points_from_meshes invalid multinomial distribution (encountering probability entry = infinity or NaN)

### ISSUE THREAD

**Issue by yadiszzz** [facebookresearch/pytorch3d#678]
`pytorch3d.ops.sample_points_from_meshes` throw error with some mesh data.

> invalid multinomial distribution (encountering probability entry = infinity or NaN)

Attached one example data from ModelNet40 [curtain/train/curtain_0066.off](https://github.com/facebookresearch/pytorch3d/files/6493548/curtain_0066.off.zip)

The issue seems related to 

https://github.com/facebookresearch/pytorch3d/blob/c9dea62162e7bbca87b68ed9bf87b3b8037ec273/pytorch3d/ops/sample_points_from_meshes.py#L86-L90

Minimal code to reproduce

```
from pytorch3d.io import IO 
from pytorch3d.ops import sample_points_from_meshes

mesh = IO().load_mesh(off_filename)
sample_points_from_meshes(mesh, 1024)
```

**Comment by gkioxari** [comment]
Have you tried to print `areas_padded`? Did you observe anything weird in the tensor, like Inf or Nan values?

**Comment by nikhilaravi** [comment]
@yadiszzz do you still need help with this issue?
