### ISSUE TITLE
Transformations for Volumes object

### ISSUE THREAD

**Issue by Relento** [facebookresearch/pytorch3d#683]
## ❓ Transformations for Volumes object
I am wondering how to transform a Volumes object before rendering it.  For example, rotating the volume along y-axis for 45°. It seems that currently the Volumes object only supports translations when transforming local coordinates to world coordinates? Thanks in advance!

**Comment by Relento** [comment]
Still looking for a solution. I would really appreciate it if this can be solved. Thanks in advance!

**Comment by yaojin17** [comment]
@Relento Hello! I'm also confused by this issue. Could you share how you resolved it? Thank you for your time and help!
