### ISSUE TITLE
Convention behind the Fragment.pix_to_face indexing. 

### ISSUE THREAD

**Issue by gaetan-landreau** [facebookresearch/pytorch3d#684]
## ❓ How works the face indexing in the _pix_to_face_ tensors from the __Fragments__ class ? 

I'm trying to work with the Fragment class from the __MeshRendererWithFragments()__ method. By the way, the method might be added in the \__init.py\__ , here if I'm right :  https://github.com/facebookresearch/pytorch3d/blob/cd5af2521a56bf3f8feca2926bbaa55cae3b3604/pytorch3d/renderer/mesh/__init__.py#L12

I understand the overall concepts behind each tensors in the __Fragments__ class, but I don't fully get how the indexing is made in _pix_to_face_. 

##### Settings. 
Considering for instance 24 meshes, each rendered with a different viewpoints (a unique azimuth angle for each mesh) , image size 64x64 and K=30. All the meshes comes from a 3d sphere template, V=642 vertices, F=1280 faces. 
##### Issues
The associated _pix_to_face_ tensor thus have a size [24,64,64,30]. However, given a viewpoint **i**  and any pixel location (x,y) ,  _pix_to_face_[**i**,x,y,:] gives me a 30-length tensor with some  index values larger than 1280 . How such things can occur ? I guess you used a specific indexing strategy but I didn't found any information on the doc / code.  From what I found in the PyTorch3D documentation, _pix_to_face_[**i**,x,y,k]=f  can then be used to track the corresponding face coordinates through **faces_verts[f]** (which give the 3 vertices locations associated to f) 

Hope my question was clear enough and not too naive 😅

**Comment by bottler** [comment]
The values (other than -1) in `pix_to_face` are the index of the face in the packed representation - e.g. `mesh.faces_packed()`.In your example, if **i** is 0 then the value should be what you expect, a value less than 1280. But for other **i** it will be higher. Because in your case you know all the meshes have the same topology with 1280 faces, I think you can just find the faces index in their own mesh with `pix_to_face[i,x,y,:] % 1280`.

**Comment by nikhilaravi** [comment]
@gaetan-landreau here is more information about the convention: https://github.com/facebookresearch/pytorch3d/blob/master/docs/notes/renderer_getting_started.md

Note that all the mesh computations in the rasterization/shading pipeline assume packed verts/faces.
