### ISSUE TITLE
Render different TextureUV image into a given mesh

### ISSUE THREAD

**Issue by ck-amrahd** [facebookresearch/pytorch3d#685]
Hi,
I am generating different texture images, let's say 1024x1024x3 and I want to texture a given mesh with these generated textures. Is there any way to do that in PyTorch3D? I went through the tutorials and I saw one texture optimization that uses:

    new_src_mesh.textures = TexturesVertex(verts_features=sphere_verts_rgb)

which uses textures on a per-vertex basis, but what I want is to render a given mesh with some generated texture map [1024x1024x3 image]. 

Then I tried to apply random image as a texture as follows:

    mesh.textures = TexturesUV(torch.rand(1, 1024, 1024, 3).to(device), faces_uvs=mesh.textures._faces_uvs_list,
                           verts_uvs=mesh.textures._verts_uvs_list)

It did work, but I am not sure if it's the right way. Is there any better way than this?
Thank you.

**Comment by nikhilaravi** [comment]
@ck-amrahd yes the `TexturesUV` class is the correct way to do this. Did you run into any issues with this?

**Comment by ck-amrahd** [comment]
Thanks @nikhilaravi, it works.
