### ISSUE TITLE
Get material name after load_obj call

### ISSUE THREAD

**Issue by MChaus** [facebookresearch/pytorch3d#687]
## 🚀 Feature
Get list of material names after calling load_obj

## Motivation

At the moment load_obj function returns 3 objects: verts, faces and aux. **faces** have a property **_material_idx_** which is torch.Tensor and sets the correspondence between face and face material. **aux** also has a property **_material_colors_** which is dict, where materials names are keys. Therefore it is impossible to get a material for particular face without building a texture atlas. Is it possible to also return materials names?

## Pitch
For example in _load_obj from io.obj_io.py
```
    aux = _Aux(
        normals=normals if len(normals) else None,
        verts_uvs=verts_uvs if len(verts_uvs) else None,
        material_colors=material_colors,
        material_names=material_names,                          # <====== Feature
        texture_images=texture_images,
        texture_atlas=texture_atlas,
    )
```

**Comment by nikhilaravi** [comment]
@MChaus thanks for the suggestion, yes this should be possible to add!

**Comment by nikhilaravi** [comment]
@MChaus actually can you clarify what exactly you are looking for?  You can get the material names using "material_colors.keys()`. Are you looking for the per face material name?

**Comment by nikhilaravi** [comment]
@MChaus do you still need this feature? If not we will close this issue.

**Comment by MChaus** [comment]
Hi, sorry for delay. I've implemented it in my fork as a list of material names, therefore now I can get an idx of material name. Because actual Textures and Materials are stored in a dict, where keys are material names, not ids. But face material correspondence is a list of ints. 
Maybe there's no issues here, and I just didn't find a proper approach to work with materials, so this implementation is up to you:)

**Comment by kampta** [comment]
`material_colors.keys()` is an unordered list, so the mapping between material_name and material_idx is lost. Would it be possible to make `material_colors` an `OrderedDict`? Thanks!

**Comment by bottler** [comment]
In Python 3.6 and newer (officially since 3.7) you get the insertion order when you iterate a dict. So `list(material_colors)` will give you the same. Explicitly, it will be in the order of usemtl statements in the obj file.

**Comment by kampta** [comment]
Ahh wasn't aware of that! Thanks @bottler

**Comment by nikhilaravi** [comment]
Thanks @bottler! Closing this issue now.
