### ISSUE TITLE
Compute shades between objects (meshes)

### ISSUE THREAD

**Issue by tcapelle** [facebookresearch/pytorch3d#69]
I am implementing a irradiance model forPhotoVoltaic modules. Most of the code is already on pytorch, and I was wondering if I could use some of your functions to compute shades.
I am inexperienced with the domain of computer graphics, and terms as shader, or raster are scary.
I am particularly interested on computing shades produced by the sun, from one row of PV modules to the ground and the row behind.  Actually we have a very rudimentary case by case shade computation, but would love to replace this by a more "state of the art" solution.
My model already implements a Mesh object with vertexes and faces for every element on the scene. Most of the code for this comes from Kaolin.
Thank you.

**Comment by nikhilaravi** [comment]
@tcapelle We can only support issues about bugs or specific questions related to the pytorch3d codebase - as mentioned in the issue templates we do not answer general questions about 'how to do X'.  If you have a specific use case of PyTorch3D for which you can explain the exact inputs and outputs we may be able to help.  To get started with PyTorch3D and differentiable rendering, I recommend starting with the [tutorials](https://pytorch3d.org/tutorials/).
