### ISSUE TITLE
Is it possible to color faces individually?

### ISSUE THREAD

**Issue by kuzand** [facebookresearch/pytorch3d#690]
Is it possible to color each face according to a given color?

I could use TexturesVertex with verts_rgb, but if two different faces of different colors share vertices there will be a conflict of colors, e.g.
face_1 {vertices: 0, 1, 2}, {color: red}
face_2 {vertices: 0, 2, 3}, {color: green}
If I set the color of vertices 0, 1, 2 to red, and then the color of vertex 3 to green, the face_1 will appear red but the face_2 will appear yellowish.

**Comment by bottler** [comment]
For one color per face, you can use [TexturesAtlas](https://github.com/facebookresearch/pytorch3d/blob/v0.4.0/pytorch3d/renderer/mesh/textures.py#L320) with R equal to 1 and D=3.

**Comment by kuzand** [comment]
> For one color per face, you can use [TexturesAtlas](https://github.com/facebookresearch/pytorch3d/blob/v0.4.0/pytorch3d/renderer/mesh/textures.py#L320) with R equal to 1 and D=3.

Thank you for the answer! Unfortunately there is no documentation for it, so I was wondering what the parameters (N, F, R, R, D) mean?

**Comment by bottler** [comment]
N is the number of meshes / the batch size. F is the (maximum) number of faces in each mesh. D is the number of channels/colors (basically always 3). R is how much each face is split up (some details are [here](https://github.com/facebookresearch/pytorch3d/blob/v0.4.0/pytorch3d/io/mtl_io.py#L134)). If R is 1 things are simple.

**Comment by kuzand** [comment]
Still it's not clear to me what tensor should I pass to the TexturesAtlas.
Should it be a tensor with rgb colors for each face? E.g. if I have 3 faces with colors red, green and blue, it would be:
```
a = torch.tensor[[1, 0, 0],
                           [0, 1, 0],
                           [0, 0, 1]]
a = a[:, :, None, None, :]
```

**Comment by bottler** [comment]
Yes.

**Comment by nikhilaravi** [comment]
@kuzand here is some documentation about the texturing options: https://github.com/facebookresearch/pytorch3d/blob/v0.4.0/docs/notes/renderer_getting_started.md#texturing-options
