### ISSUE TITLE
cameras.unproject_points does not align with mesh when distance is large

### ISSUE THREAD

**Issue by vaibhavnayel** [facebookresearch/pytorch3d#697]
## 🐛 Unexpected behavior
I'm trying to simulate an aerial depth sensor to capture pointclouds from multiple views and align them in world space. I used the code from #658 as a starting point.

I placed a ring of 4 cameras 90 degrees apart at an elevation of 70 degrees above my model, used the ```MeshRendererWithDepth``` class to render depth and unprojected the points back into world space from each camera.  I also sampled the mesh using ```sample_points_from_meshes``` to check for alignment.

When the camera is close to the model (```dist = 10```), the points appear to align reasonably well but when the camera is moved further away (```dist = 60```), the projection loses alignment drastically. In reality the alignment isn't perfect even at close distances.

<img width="737" alt="Screenshot 2021-06-03 at 7 59 06 PM" src="https://user-images.githubusercontent.com/19236390/120691046-44a1c600-c4a6-11eb-8fc1-7b91eee5f019.png">
<img width="839" alt="Screenshot 2021-06-03 at 7 58 55 PM" src="https://user-images.githubusercontent.com/19236390/120691053-47042000-c4a6-11eb-8f65-4feef403349e.png">

white: sampled mesh, green: camera dist=10, blue: camera dist=30, pink: camera dist=60 
the obj file can be found here: [jeep.zip](https://github.com/facebookresearch/pytorch3d/files/6593494/jeep.zip)

## Code To Reproduce the Issue:

```
import torch
import os
from torch import nn
from pytorch3d.renderer import (
    FoVPerspectiveCameras,
    RasterizationSettings,
    PointLights,
    SoftPhongShader,
    look_at_view_transform,
    MeshRasterizer,
    look_at_rotation
)
from pytorch3d.io import load_objs_as_meshes
from pytorch3d.ops import sample_points_from_meshes

device = 'cuda'
img_size = 1024
dist = 60
file='jeep/Jeep_Renegade_2016.obj'
mesh = load_objs_as_meshes([file], device=device)

class MeshRendererWithDepth(nn.Module):
    def __init__(self, rasterizer, shader):
        super().__init__()
        self.rasterizer = rasterizer
        self.shader = shader

    def forward(self, meshes_world, **kwargs) -> torch.Tensor:
        fragments = self.rasterizer(meshes_world, **kwargs)
        images = self.shader(fragments, meshes_world, **kwargs)
        return images, fragments.zbuf

def get_pointcloud(cameras,mesh):
    raster_settings = RasterizationSettings(image_size=img_size,perspective_correct=True,bin_size=0)
    rasterizer = MeshRasterizer(raster_settings=raster_settings,cameras=cameras)
    shader = SoftPhongShader(device=device,cameras=cameras)
    rasterizer_depth = MeshRendererWithDepth(rasterizer=rasterizer, shader=shader)

    images, zbuf = rasterizer_depth(mesh, cameras=cameras)
    cull=zbuf[zbuf>0].min()

    dist = torch.distributions.uniform.Uniform(-1, 1)
    grid = dist.sample((1, 1, 50000, 2)).to(device)
    depth_sample = torch.nn.functional.grid_sample(zbuf.permute(0, 3, 1, 2), grid, align_corners=False)
    uv_depth = torch.cat([grid[0, 0]*-1, depth_sample[0, 0, 0].unsqueeze(-1)], dim=1)
    xyz_world = cameras.unproject_points(uv_depth, world_coordinates=True)

    return xyz_world[uv_depth[:,-1]>cull]


xyz_world_all = []
for i in range(0,360,90):
    R, T = look_at_view_transform(dist, 70, i)
    cameras = FoVPerspectiveCameras(R=R, T=T, device=device)
    xyz_world = get_pointcloud(cameras,mesh)
    xyz_world_all.append(xyz_world)

xyz_world_all = torch.cat(xyz_world_all).cpu().numpy()
samples = sample_points_from_meshes(mesh).squeeze().cpu().numpy()

```
Things I tried:
1.  toggling ```align_corners=True``` in ```grid_sample```
2.  constructing ```grid``` from ```meshgrid``` instead of sampling a distribution as detailed in https://github.com/facebookresearch/pytorch3d/issues/658#issuecomment-853949637
3.  toggling ```perspective_correct=True``` in ```RasterizationSettings```
4.  varying ```image_size``` from 256 to 1024

I'm also not sure if this is even the right way to go about simulating a depth sensor in pytorch3d, so if there's a better function to do this, let me know.

```
pytorch3d == 0.4.0
torch == 1.7.1
cudatoolkit == 11.0
```

**Comment by vaibhavnayel** [comment]
Is there any progress on this? Am I doing something wrong or is there a problem in the unproject function?

**Comment by patricklabatut** [comment]
Not yet. But if you have a more minimal example (e.g. a reproduction with a very simple fixed object or even a few points) and expected / observed results, that would likely help expedite local reproduction, troubleshooting and providing feedback.

**Comment by nnMan1** [comment]
Point cloud will be much sharper if you set mode for grid sampling to be "nearest"
depth_sample = torch.nn.functional.grid_sample(zbuf.permute(0, 3, 1, 2), grid, align_corners=False, mode="nearest")
