### ISSUE TITLE
Is there some issue with pytorch3d.common path??

### ISSUE THREAD

**Issue by phantomKid13** [facebookresearch/pytorch3d#705]
Plz check the following SS 

![Screenshot (243)](https://user-images.githubusercontent.com/67835508/121458247-a68e8e00-c9c6-11eb-9315-3d1193a01049.png)

**Comment by PartlyFluked** [comment]
I think pytorch3d/common/ just needed a __init__.py file, i've added a PR for it here #706.

**Comment by patricklabatut** [comment]
As previously noted #706 addressed this and has just been merged. Thanks again for reporting (and submitting fixes)!
