### ISSUE TITLE
Pointcloud initialization with padded format bug

### ISSUE THREAD

**Issue by bango123** [facebookresearch/pytorch3d#712]
Hello,

As always, thanks for open-sourcing this incredible code-base! It has been super helpful in my work. I believe I found a bug in the initialization for Pointcloud when using the padded format. The attribute `_num_points_per_cloud` is always hard set in this [line](https://github.com/facebookresearch/pytorch3d/blob/44508ed0db269ed0b7c952fbee6bd09105a1c653/pytorch3d/structures/pointclouds.py#L212) of code. This is not consistent with my understanding of the padded format.

For example, if I wish to initialize a point cloud in a list format with:
` [ tensor([ [1,2,3] ]), tensor([ [4,5,6], [7,8,9] ]) ] `
the `_num_points_per_cloud` should be `[1, 2]`. However, if I do the equivalent in a padded format, which should be:
`tensor([ [ [1,2,3], [0,0,0] ], [ [4,5,6], [7,8,9] ] ])`
then according to the current code, `_num_points_per_cloud` is set to `[2, 2]`.

My current work-around for this issue is to manually set `_num_points_per_cloud` after initializing a Pointcloud object using the padded format. For example:
`point_cloud = Pointclouds(points=points_padded)`
`point_cloud._num_points_per_cloud = num_points_per_cloud `
where num_points_per_cloud is a list computed ahead of time.

**Comment by gkioxari** [comment]
Initializing with padded values is not the intended use of our data structures. 

If you initialize the data structures with a tensor, as in your case, then we assume that the data you provide is homogeneous, i.e. all elements in the batch have the same size. In other words, if you provide as input a NxVx3 tensor then we assume that your data structure is a batch of N elements, each of V points. We don't try to reason about padding at input time, and that is the right choice; remember that a [0,0,0] point could be a point in the cloud and not necessarily a padded value. 

In all our data structures, padding only happens internally and we keep track of padded values with auxiliary variables.

If you have heterogeneous 3D data, you should be providing them as a list to the datastructure, where each element in the list is the 3D data with its corresponding size.
