### ISSUE TITLE
Windows installation with 3090 RTX cards

### ISSUE THREAD

**Issue by neyazyb** [facebookresearch/pytorch3d#713]
## ❓ Windows installation with pytorch 1.7 and cuda 11.0?

For some reason I think we need to use CUDA 11.1 for 30s series cards. please refer the link below for more details.
http://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/

I got a compute 86 error when doing it with CUDA 10.1. so i did the above.

I have tried installing cuda 11.1 driver in my windows system installed pytorch by 
```
conda install pytorch==1.7.1 torchvision==0.8.2 torchaudio==0.7.2 cudatoolkit=11.0 -c pytorch
```
as they are compatible with each other.

I did all the steps mentioned in install.md and also referring to #323 .

I have included my error log with this. Please help me.
[error.txt](https://github.com/facebookresearch/pytorch3d/files/6664985/error.txt)

**Comment by neyazyb** [comment]
Also please let me know if I can change my or to Linux and use cuda 11.1 and install it.

**Comment by bottler** [comment]
I know little about Windows installs. PyTorch 1.8.0 is the first version with builds for CUDA 11.0, and PyTorch 1.9.0 is the first version with builds for CUDA 11.1. The earliest version of CUDA which supports compute capacity 8.6 is CUDA 11.1.

However, the errors in error.txt look unrelated. Your errors seem to be similar to [this issue](https://stackoverflow.com/questions/67732065/why-does-vs2019-pro-have-compile-errors-with-xutility-xmemory-and-atomic-when). It looks like the solution is to remove the two references to "-std=c++14" in setup.py. So comment line 56, and change line 40 to `extra_compile_args = {"cxx": []}`

**Comment by neyazyb** [comment]
Worked like a charm. You are awesome. Thank you

**Comment by neyazyb** [comment]
I am getting error while rendering as 
``` 
CUDA error: no kernel image is available for execution on the device
```

Does pytorch3d support Pytorch 1.9.0. I would like to install PyTorch 1.9.0 along with CUDA 11.1 toolkit.

Or is there a workaround.

please find the environment file

[env.txt](https://github.com/facebookresearch/pytorch3d/files/6669572/env.txt)

I have CUDA 11.0 installed. Or should I go ahead with CUDA 11.1 and repeat the process.
