### ISSUE TITLE
How to convert pulsar 3d reconstruction results to mesh ?  

### ISSUE THREAD

**Issue by Jiakui** [facebookresearch/pytorch3d#714]
I need 3d mesh , how could I get it after I  finished the  pulsar 3d reconstruction process?

Thanks!

**Comment by classner** [comment]
Hi @Jiakui !

Fundamentally, this is a question of how to convert a point cloud to a mesh. This is an open research area with a whole set of methods that could be used. Depending on the data that you are working on, the resulting point cloud will have different noise characteristics, and depending on those different methods might work better or worse. Open3D has a few different methods implemented for point cloud to mesh conversion (see, for example, here: http://www.open3d.org/docs/latest/tutorial/Advanced/surface_reconstruction.html ).

Best,
Christoph
