### ISSUE TITLE
I want to share colab script for mesh deformation with the community + morphing animation

### ISSUE THREAD

**Issue by Mistrymm7** [facebookresearch/pytorch3d#716]
Please find link below link of Colab script 
https://colab.research.google.com/drive/11WNspBYWtTw2dBB6MHElGiXGzRDwo7O7?usp=sharing

**Comment by nikhilaravi** [comment]
@Mistrymm7 if you want to contribute to PyTorch3D please follow the contribution guidelines in [CONTRIBUTING.md](https://github.com/facebookresearch/pytorch3d/blob/master/.github/CONTRIBUTING.md) and if appropriate make a pull request.
