### ISSUE TITLE
0.4.0 install failed

### ISSUE THREAD

**Issue by haoxurt** [facebookresearch/pytorch3d#717]
When I install 0.4.0 by pip install pytorch3d -f pytorch3d-0.4.0-cp38-cp38-linux_x86_64.whl, I receive  'ERROR: Could not install packages due to an EnvironmentError: Invalid URL 'pytorch3d-0.4.0-cp38-cp38-linux_x86_64.whl': No schema supplied. Perhaps you meant http://pytorch3d-0.4.0-cp38-cp38-linux_x86_64.whl?'
How can I solve it ?

**Comment by bottler** [comment]
Where did you hear about `pip install pytorch3d -f pytorch3d-0.4.0-cp38-cp38-linux_x86_64.whl` that made you want to try it?

**Comment by haoxurt** [comment]
I  refered to 'pip install pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py38_cu102_pyt171/download.html'.  However, my server can't connect to the Internet, so I download whl file in advance.

**Comment by bottler** [comment]
Try `pip install ./pytorch3d-0.4.0-cp38-cp38-linux_x86_64.whl`. But it will look for dependencies on PyPI, so if can't connect to the internet and you are missing fvcore or iopath it won't work.
