### ISSUE TITLE
RuntimeError: Expected object of scalar type Double but got scalar type Float 

### ISSUE THREAD

**Issue by IssamLaradji** [facebookresearch/pytorch3d#718]
Hi team,

Shouldn't this line work since there is no change in `dtype? 
```
trafo.translate(-trafo.get_matrix()[:, -1, None, :3][:,0,:]).get_matrix()
```
instead, it gives me,     (I am using the conda environment suggested by this repo)

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/mnt/home/miniconda3/envs/pytorch3d/lib/python3.8/site-packages/pytorch3d/transforms/transform3d.py", line 232, in get_matrix
    composed_matrix = _broadcast_bmm(composed_matrix, other_matrix)
  File "/mnt/home/miniconda3/envs/pytorch3d/lib/python3.8/site-packages/pytorch3d/transforms/transform3d.py", line 700, in _broadcast_bmm
    return a.bmm(b)
RuntimeError: Expected object of scalar type Double but got scalar type Float for argument #2 'mat2' in call to _th_bmm_out
```

**Comment by bottler** [comment]
What is `trafo`? Can you give more context?

**Comment by nikhilaravi** [comment]
I think this is a  Transforms3D `dtype` issue that might have been fixed in https://github.com/facebookresearch/pytorch3d/commit/44508ed0db269ed0b7c952fbee6bd09105a1c653. 

Are you using the PyTorch3D conda package? If so can you try to switch to the nightly build?

**Comment by IssamLaradji** [comment]
`trafo` is a `Transforms3D` object, and 

```
> trafo.get_matrix().dtype
> torch.float64
```

maybe internally there is a `torch.float32` somewhere? is it easy to change `trafo`'s  dtype to `float32`?

**Comment by bottler** [comment]
Many things default to torch.float32. If trafo is entirely float64, you may be able to do
```
trafo.translate(-trafo.get_matrix()[:, -1, None, :3][:,0,:], dtype=torch.float64).get_matrix()
```

**Comment by IssamLaradji** [comment]
That worked, thanks awesome team!
