### ISSUE TITLE
Save volumetric model as mesh

### ISSUE THREAD

**Issue by pangyyyyy** [facebookresearch/pytorch3d#719]
## ❓ How to save volumetric model as mesh?

This is with regards to how to save the volumetric model from the tutorial `fix_textured_volume.ipynb`. 

`volume_model._parameters.keys()` contains 'log_densities', 'log_colors' which gives the voxel's RGB color and occupancy, but I'll like to save it as a mesh model `.obj` file. I can't seem to find a suitable function in the pytorch3d.io documentation and I was wondering if such a function exists? and if it doesn't, any advice on how to save the volume model as a mesh?

**Comment by nikhilaravi** [comment]
@pangyyyyy I think you would need to run marching cubes to extract out a mesh and then save that. We have a naive pytorch version of marching cubes here https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/ops/marching_cubes.py#L88
