### ISSUE TITLE
input and output transform_points(unproject_points()) do not match

### ISSUE THREAD

**Issue by weders** [facebookresearch/pytorch3d#720]
## 🐛 Results of unproject_points and transform_points to do not match

If I unproject a dummy input from NDC space to world using unproject_points() and project them back to NDC using transform_points, the results do not match. To my understanding of the functions, the following condition should hold input = transform_points(unproject_points(input, world_coordinates=True)).

Please see the complete code for reproducing the issue below. 

## Instructions To Reproduce the Issue:

1. Code run in a Jupyter Notebook
```
import torch
import pytorch3d

from pytorch3d.renderer.cameras import PerspectiveCameras
from pytorch3d.renderer import PulsarPointsRenderer
from pytorch3d.renderer.points import PointsRasterizer, PointsRasterizationSettings
from pytorch3d.structures.pointclouds import Pointclouds

device = torch.device('cuda:0')

# perspective camera
fx = 1.
fy = 1.

px = 0.
py = 0.

# define camera extrinsics
R = torch.eye(3).unsqueeze(0)
T = torch.zeros(1, 3)

focal_length = torch.Tensor([fx, fy]).unsqueeze(0)
principal_point = torch.Tensor([px, py]).unsqueeze(0)

camera = PerspectiveCameras(focal_length=focal_length, principal_point=principal_point, R=R, T=T)

# create point clouds
# define scene
n_spheres = 640000

# create pixel coordinates
xx, yy = torch.meshgrid(torch.arange(0, 800), torch.arange(0, 800))
xx = xx.flatten() 
yy = yy.flatten()

# convert to ndc
xx = (xx - 400) / 800 * 2.
yy = (yy - 400) / 800 * 2.
zz =  5. * torch.ones_like(xx)

depth_points = torch.stack([xx, yy, zz]).T
world_points = camera.unproject_points(depth_points, world_coordinates=True)
pos = world_points

print(depth_points)
print(world_points)
print(camera.transform_points(world_points))
```

```
NDC Input
tensor([[-1.0000, -1.0000,  5.0000],
        [-1.0000, -0.9975,  5.0000],
        [-1.0000, -0.9950,  5.0000],
        ...,
        [ 0.9975,  0.9925,  5.0000],
        [ 0.9975,  0.9950,  5.0000],
        [ 0.9975,  0.9975,  5.0000]])
World Points
tensor([[-5.0000, -5.0000,  5.0000],
        [-5.0000, -4.9875,  5.0000],
        [-5.0000, -4.9750,  5.0000],
        ...,
        [ 4.9875,  4.9625,  5.0000],
        [ 4.9875,  4.9750,  5.0000],
        [ 4.9875,  4.9875,  5.0000]])
NDC Output
tensor([[-1.0000, -1.0000,  0.2000],
        [-1.0000, -0.9975,  0.2000],
        [-1.0000, -0.9950,  0.2000],
        ...,
        [ 0.9975,  0.9925,  0.2000],
        [ 0.9975,  0.9950,  0.2000],
        [ 0.9975,  0.9975,  0.2000]])
```

As you can see, the depth values of NDC Input and Output do not match. I know that according to https://pytorch3d.org/docs/cameras#perspectivecameras-orthographiccameras the Z values get inverted when projecting from world space to NDC space. However, I think that the unprojection and projection should yield consistent results.

Thank you very much for your help!

**Comment by gkioxari** [comment]
Hi @weders 
We are in the process of re-factoring the cameras in PyTorch3D and I will look into this. I think the issue is about the coordinate system assumptions that we assume for NDC and screen. This is currently kind of ugly, but our refactor will fix it (hopefully!)

**Comment by gkioxari** [comment]
I misunderstood your question and this is not an issue! It was to do with how we deal with `Z` aka depth. 

If `points_proj = transform_points(xyz)` where `xyz = (x, y, depth)`, then `proj_points[..,3] = 1 / depth` which is the output after applying the transform to the points. 

The `unproject_points` transforms points whose `XY` is on the image plane and their `Z` is their depth, so in other words it takes as input `(x_proj, y_proj, depth)`. The purpose of this transform is to convert image sensory data or for SfM computations that want to convert pixels on the image plane and their corresponding depth values back to the 3D world. So `unproject_points` is NOT the inverse of `transform_points` in that sense. You can also see that in the code. 

https://github.com/facebookresearch/pytorch3d/blob/da9974b4160b6afe2587b473cdd471d4e299b323/pytorch3d/renderer/cameras.py#L934-L946
