### ISSUE TITLE
How to optimize the 3D  mesh according to 2D  chamfer distance ?  

### ISSUE THREAD

**Issue by Jiakui** [facebookresearch/pytorch3d#722]
In the paper "sketch2mesh: reconstructing and editing 3d shapes from sketches ", it is mentioned that , we can project the 3d mesh to an rendered image , with **pytorch3d**,  and then find the **contour of the silhouette**, and then compare the rendered silhouette contour to the contour in the given image (**2d chamfer distance** ). The whole process is differentiable. 

It looks for me that, it is hard to imagine a differentiable way to find the contour of the rendered silhouette, anyone can provide a hint about this question?

Thanks!

**Comment by gkioxari** [comment]
You should be asking the sketch2mesh authors, not us! Thanks!
