### ISSUE TITLE
Encoder Decoder for 3D mesh

### ISSUE THREAD

**Issue by ck-amrahd** [facebookresearch/pytorch3d#724]
Hi guys,
I want to train a model that can encode 3d mesh into latent space [fixed dimensions] and decode it to minimize the reconstruction error [similar to encoder-decoder architecture for 2d images]. I can use conv2d and TransposeConv2d for 2d images. I think I can use the GraphConv layer by transforming mesh into a graph but I am not sure how to map these variable numbers of vertices to a fixed dimensional latent space and not sure how to do the reverse [latent space to mesh] in the decoder. Any help, links, and suggestions will be helpful. Thank you.

**Comment by gkioxari** [comment]
This not an issue with the library so I suggest you post this in the Discussions of the repo rather than the Issues. Thank you!

**Comment by ck-amrahd** [comment]
Thanks @gkioxari, will do that.
