### ISSUE TITLE
Dolphine to Sphere Mesh 

### ISSUE THREAD

**Issue by shersoni610** [facebookresearch/pytorch3d#73]
Transforming a shape with Genus = 0 to a sphere has been well studied topic. Mean Curvature
flow guarantees that during surface evolution, the mesh will not intersect.

In the tutorial on transforming the model what properties are being preserved. Is there any report/article using this approach? Is the Machine learning approach better than classical
approach? Any paper?

**Comment by gkioxari** [comment]
Hi @shersoni610! The purpose of all of our tutorials is purely instructional. The example of a deforming sphere serves as a way to highlight the various differentiable losses/regularizers we have implemented for 3D data. Our goal is to show how these ops can be defined and used when optimizing an objective with SGD. (Note that they're not limited to the purpose of the tutorial. In Mesh R-CNN, we use a similar set of losses/regularizers to learn how to fit an arbitrary topology (genus > 0) to a target shape. )

You might be correct in saying that classical approaches can also deform genus 0 shapes well. We don't claim that the tutorial is state-of-the-art in sphere deformation. Again, its purpose is purely instructional.

**Comment by shersoni610** [comment]
Hello,
I have been trying hard to understand the importance of both Pytorch3D and
Kaolin libraries. I am interested in learning how Machine
learning may fit nicely to the 3D modelling/representation etc problems.
Classical techniques have been implemented in various C++ software
(CGAL, libIGL, Easy3D, Cinolib etc) and I do not know how can I convince
our students to learn these new  machine learning techniques.

I was hoping that the demos will go a few steps further to give solution to
some real hard problems for which classical methods may
have issues.

If someone knows some compelling examples, please share. We will try to
implement them using Pytorch3D.

**Comment by gkioxari** [comment]
Hi @shersoni610! This is a valid question of course. Libraries provide nails and hammers and it's up to the user to find good use cases for them, if any. For me, it's obvious what we can start exploring with PyTorch3D which classical methods cannot offer. Though, a healthy research community is a diverse community, so I do appreciate and would strongly encourage these parallel efforts (ML vs. non ML, learning vs. non learning, etc.) to proceed. I will close the issue for now as it's not related to a bug/feature in the library, but I am happy to keep this discussion going!

**Comment by andrewjong** [comment]
@gkioxari , I am considering trying 3D deep learning for my project, and trying to understand how PyTorch 3D relates/compares to NVIDIA's Kaolin. As this is relatively new, I have not found any comparisons online yet. Could you help explain, please?
