### ISSUE TITLE
How to render mesh wireframe

### ISSUE THREAD

**Issue by shirgur** [facebookresearch/pytorch3d#732]
## ❓ How to render mesh wireframe
Is there a way to render the mesh's wireframe?

Thanks

**Comment by bottler** [comment]
Do you want a differentiable rendering or just a visualization / forward pass? Do you want to only see the wireframe without the mesh, or both the mesh and the wireframe together?

**Comment by shirgur** [comment]
In my case, there's no need for it to be differentiable, only for visualization (with and without the mesh)

I find it very easy to use PyTorch3D for training AND visualization, and I hope not to use other packages for visualization only

**Comment by bottler** [comment]
Plotly has a facility for viewing a wireframe, and we already have encapsulated it in PyTorch3D for visualizing a PyTorch3D mesh. I think it would be quite easy to add a connection in plotly_vis for showing a mesh as a wireframe. Perhaps the easiest thing would be to add a new class `Wireframe` in plotly_vis which contains nothing but a single `Meshes` member, and this new class would be added to the things accepted by the two plotting functions, and the response to it is showing the wireframe. You might be able to do this yourself.

There may be tricks to make the PyTorch3D renderer show some of the wireframe, but this would not be an easy choice if you want to see hidden surfaces, i.e. edges which are behind faces.

**Comment by Tandon-A** [comment]
Is there any update on this?

**Comment by MartensCedric** [comment]
Looking for a solution to this. I want to render a wireframe without needing it to be differentiable, just for visualization

**Comment by bottler** [comment]
No update. But the plotly method may do what you need, or perhaps other libraries.
