### ISSUE TITLE
How to turn two sided lighting as in Maya?

### ISSUE THREAD

**Issue by tjusxh** [facebookresearch/pytorch3d#738]
In Maya, light-> two sided lighting is useful for pasting uv map to the side of the mesh. How to do it in pytorch3d? Thanks.

**Comment by bottler** [comment]
In PyTorch3D, setting `cull_backfaces=True` in the `RasterizationSettings` makes faces behave as one sided. Specifically the rasterization will only include front-facing triangles, meaning those whose indices are ordered in an anti-clockwise fashion, relative to the current view direction. You can store every face twice in a mesh, one in each direction, and in this way get a separate piece of texture on each side of the mesh.

**Comment by bottler** [comment]
Can you clarify what you want? I think I may have misunderstood the question in my previous answer. For example, do you want the same texture on both sides of a face or different? Do you want specular lighting to reflect normals in both directions, or is that not your concern at all?

**Comment by tjusxh** [comment]
@bottler  Thank you very much. I solve the problem.
