### ISSUE TITLE
chamfer loss import error

### ISSUE THREAD

**Issue by aradhyamathur** [facebookresearch/pytorch3d#739]
receiving the following  error however when I import chamfer loss.
`Traceback (most recent call last): File "point2param.py", line 38, in <module> from pytorch3d.loss import chamfer_distance File "/home/aradhya/anaconda3/envs/torchenv/lib/python3.7/site-packages/pytorch3d/loss/__init__.py", line 4, in <module> from .chamfer import chamfer_distance File "/home/aradhya/anaconda3/envs/torchenv/lib/python3.7/site-packages/pytorch3d/loss/chamfer.py", line 7, in <module> from pytorch3d.ops.knn import knn_gather, knn_points File "/home/aradhya/anaconda3/envs/torchenv/lib/python3.7/site-packages/pytorch3d/ops/__init__.py", line 5, in <module> from .graph_conv import GraphConv File "/home/aradhya/anaconda3/envs/torchenv/lib/python3.7/site-packages/pytorch3d/ops/graph_conv.py", line 6, in <module> from pytorch3d import _C ImportError: /home/aradhya/anaconda3/envs/torchenv/lib/python3.7/site-packages/pytorch3d/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZTIN3c1021AutogradMetaInterfaceE
`
For installation I followed the exact steps provided in readme for Linux -
Pytorch installed using the method provided on official site using pip. pytorch3d installed using conda 
Command for pytorch installation 

 `pip install torch==1.7.1 torchvision==0.8.2 torchaudio==0.7.2`
 followed by 
`conda install pytorch3d`

pytorch3d==0.2.0

**Comment by patricklabatut** [comment]
> pytorch3d==0.2.0

PyTorch3D 0.2 was released in Apr 2020 and PyTorch 1.7.1 in Dec 2020.

Could you thus give it a try with a more recent version of PyTorch3D? Thanks.

**Comment by bottler** [comment]
You can't install PyTorch3D with conda in an environment where PyTorch has been installed with pip, because the PyTorch3D conda packages depend on the PyTorch conda packages. Easiest would be to set up a new conda environment installing everything via conda.

**Comment by aradhyamathur** [comment]
Thanks @bottler  a clean install completely with conda worked.
