### ISSUE TITLE
How do I render a batch of meshes with different views?

### ISSUE THREAD

**Issue by HelloMaroon** [facebookresearch/pytorch3d#740]
I've learned this "https://pytorch3d.org/docs/batching", so I know how to put some meshes in a batch. 
And I've learned this "https://pytorch3d.org/tutorials/render_textured_meshes", so I know how to render with different well-setting views. 
However, if I wanna render a batch meshes with many customized views and I wanna update these views as parameters just like this "https://pytorch3d.org/tutorials/camera_position_optimization_with_differentiable_rendering". (it used camera positions as views)
Then what should I do?

**Comment by bottler** [comment]
Rendering has a single batch dimension. So if you have the same number of meshes as cameras/views, and you want to render each mesh with its corresponding view, that should just work. If you want to render each mesh with each camera, you will need to duplicate data or make multiple calls to the renderer.

As you see from the camera_position tutorial, there's nothing special to know to make inputs to a calculation be optimizable parameters. You just need to initialize those inputs as tensors which require grad, or use the nn.module style, and use them to calculate a loss.  The initial parameter could be a batch of positions. (If you want to optimize over camera rotation as well as position, you need to be careful about what space you use.  Making the parameters be 6d and converting them with rotation_6d_to_matrix each time you want to initialize over cameras would be natural.)

**Comment by HelloMaroon** [comment]
Thanks a lot, I thought there may be a masterly way to cope with this issue before. After you answer this, then I know how to do it now. Thanks again.
