### ISSUE TITLE
face_per_pixel broadcast problem not solved, error

### ISSUE THREAD

**Issue by nikjetchev** [facebookresearch/pytorch3d#742]
Hi

 I still get a similar broadcast error as that [old issue]( https://github.com/facebookresearch/pytorch3d/issues/550)
Maybe the bug fix did not solve all possible cases, so the issue should be reopened (or I make a new issue).

Summary of behaviour:

Set face_per_pixel to 8 in the rasterization settings
Call the renderer with 2 cameras, and mesh.extend(2) and get this error

(the same code works  if you set either face_per_pixel=1 , or use only 1 mesh and 1 camera)

```
/usr/local/lib/python3.7/dist-packages/pytorch3d/renderer/mesh/shader.py in forward(self, fragments, meshes, **kwargs)
    135         zfar = kwargs.get("zfar", getattr(cameras, "zfar", 100.0))
    136         images = softmax_rgb_blend(
--> 137             colors, fragments, blend_params, znear=znear, zfar=zfar
    138         )
    139         return images

/usr/local/lib/python3.7/dist-packages/pytorch3d/renderer/blending.py in softmax_rgb_blend(colors, fragments, blend_params, znear, zfar)
    186     # TODO: there may still be some instability in the exponent calculation.
    187 
--> 188     z_inv = (zfar - fragments.zbuf) / (zfar - znear) * mask
    189     # pyre-fixme[16]: `Tuple` has no attribute `values`.
    190     # pyre-fixme[6]: Expected `Tensor` for 1st param but got `float`.

RuntimeError: The size of tensor a (2) must match the size of tensor b (8) at non-singleton dimension 3
```

any help will be appreciated, I want to use face_per_pixel>1 and more than 1 mesh+cameras

**Comment by bottler** [comment]
Which version of PyTorch3D are you using? The bug has been fixed since the latest release (0.4.0), so if you have not installed straight from github you would be expected to still see the problem.

**Comment by nikjetchev** [comment]
I am using the collab code from the tutorials of pytorch3d, I am not sure whether it used pip or github...
Anyway, so you suggest the fix would be to forget pip and use straight github? Thanks a lot

```
need_pytorch3d=False

try:
    import pytorch3d
except ModuleNotFoundError:
    need_pytorch3d=True
if need_pytorch3d:
    if torch.__version__.startswith("1.7") and sys.platform.startswith("linux"):
        # We try to install PyTorch3D via a released wheel.
        version_str="".join([
            f"py3{sys.version_info.minor}_cu",
            torch.version.cuda.replace(".",""),
            f"_pyt{torch.__version__[0:5:2]}"
        ])
        !pip install pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/{version_str}/download.html
    else:
        # We try to install PyTorch3D from source.
        !curl -LO https://github.com/NVIDIA/cub/archive/1.10.0.tar.gz
        !tar xzf 1.10.0.tar.gz
        os.environ["CUB_HOME"] = os.getcwd() + "/cub-1.10.0"
        !pip install 'git+https://github.com/facebookresearch/pytorch3d.git@stable'
```

**Comment by bottler** [comment]
On colab, do a "factory reset runtime", remove just the `@stable` from the last line of that snippet, and then running that cell will build and install the latest PyTorch3D from github.

**Comment by nikjetchev** [comment]
awesome, it installed correctly in this way and now works. Thanks a lot, i am closing the issue.
