### ISSUE TITLE
`so3_exp_map` not defined in the `__init__` of `transforms`.

### ISSUE THREAD

**Issue by SuX97** [facebookresearch/pytorch3d#745]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## 🐛 Bugs / Unexpected behaviors

In the tutorial of [nerf](https://github.com/facebookresearch/pytorch3d/blob/master/docs/tutorials/fit_simple_neural_radiance_field.ipynb),
```
from pytorch3d.transforms import so3_exp_map
```
`so3_exp_map` is used however this name is not registered in the `__init__.py` in release py38_cu102_pyt171, which is the default package one will use if following the install instruction.

NOTE: Please look at the existing list of Issues tagged with the label ['bug`](https://github.com/facebookresearch/pytorch3d/issues?q=label%3Abug). **Only open a new issue if this bug has not already been reported. If an issue already exists, please comment there instead.**.

## Instructions To Reproduce the Issue:

Please include the following (depending on what the issue is):

1. Any changes you made (`git diff`) or code you wrote
```
```

2. The exact command(s) you ran:
run pytorch3d/docs/tutorials/fit_simple_neural_radiance_field.ipynb.

3. What you observed (including the full logs):
```
ImportError: cannot import name 'so3_exp_map' from 'pytorch3d.transforms' 
```

Please also simplify the steps as much as possible so they do not require additional resources to
   run, such as a private dataset.

**Comment by bottler** [comment]
The [stable version of the tutorial](https://github.com/facebookresearch/pytorch3d/blob/stable/docs/tutorials/fit_simple_neural_radiance_field.ipynb) is consistent with the stable version of PyTorch3D (i.e. the latest release 0.4.0) and the [latest version](https://github.com/facebookresearch/pytorch3d/blob/master/docs/tutorials/fit_simple_neural_radiance_field.ipynb) is consistent with the latest code. In this case, so3_exponential_map is used in the stable code and tutorials, and so3_exp_map is used in the latest code and tutorials. The function so3_exponential_map is deprecated and is currently available in the latest code too. 

This kind of divergence is mentioned in [the README of the tutorials directory](https://github.com/facebookresearch/pytorch3d/tree/stable/docs/tutorials).

**Comment by SuX97** [comment]
@bottler Got it! Thanks for your response.
