### ISSUE TITLE
RuntimeError in CPU version of cubify

### ISSUE THREAD

**Issue by patmjen** [facebookresearch/pytorch3d#746]
The CPU version of `cubify` may raise a `RuntimeError` due to inconsistent behavior of PyTorch's `Tensor.scatter_`.
Full details can be found in the comments of Issue #513. Since the tests were done with the GPU version of `cubify` the problem was not reproduced and the issue closed. However, the issue can be reproduced using the CPU version of `cubify`.

Since the issue has already been raised and discussed in issue #513, feel free to re-open that and close this issue. I'm simply creating a new issue since no response was given in the previous.

**Comment by nikhilaravi** [comment]
@patmjen thanks for flagging this I will reopen #513 and close this one as it has more of the context.
