### ISSUE TITLE
RuntimeError: Not compiled with GPU support. (Windows)

### ISSUE THREAD

**Issue by MHong94** [facebookresearch/pytorch3d#747]
It looks like I installed pytorch3d without GPU support, but I cannot figure out what I did wrong following the install guide.  Running into this error on one of the tutorials.

Specs:
OS: Windows 10
GPU: Geforce 1060
cudatoolkit: 10.2.89
pytorch 1.9.0
torchvision: 0.10.0
pytorch3d: 0.4.0                     dev_0    <develop>

Steps to reproduce:
*All commands were run on Anaconda Prompt*

1. conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch
2. curl -LO https://github.com/NVIDIA/cub/archive/1.10.0.tar.gz
    tar xzf 1.10.0.tar.gz
3. Set CUB_HOME as environment variable with location as cub-1.10.0 folder
4. git clone https://github.com/facebookresearch/pytorch3d.git
5. pip install -e .

At this point, it wasn't working, so I tried the next step

6. python setup.py install

Nothing changed

**Comment by bottler** [comment]
(You need to use the visual studio command prompt, with conda environment. I am not clear if this was the case.)

If you start python and import torch, what is the value of `torch.cuda.is_available()`? Does `nvcc --version` work at the prompt? When you say "it wasn't working", do you mean you got the "Not compiled with GPU support" message?

**Comment by MHong94** [comment]
torch.cuda.is_available() returns True, but nvcc is actually returning 'recognized command' error.  Also yes, sorry for the confusion, but that is where I ran into the not compiled with GPU support error.

**Comment by bottler** [comment]
You need to get CUDA fully installed, and then nvcc will work. (The toolkit in conda is not enough.) Then if it's still a problem, look carefully at the build output in pytorch3d. (Calling `python setup.py install` gives more info than using pip).

**Comment by MHong94** [comment]
Installed nvcc, recompiled pytorch3d using `python setup.py install`.  I am now running into the this issue 

`ImportError: DLL load failed while importing _C: The specified module could not be found.`

I have attached an image below showing my pytorch3d folder.  

![image](https://user-images.githubusercontent.com/50376745/124956964-6b837880-dfcd-11eb-888a-dd9c3dec7490.png)

**Comment by bottler** [comment]
Some library that the built extension wants could be different from what you actually have in the environment. Can you maybe open the extension in depends.exe / dependency walker or similar and see what it thinks it depends on?

**Comment by MHong94** [comment]
Sorry I'm not too familiar on how to fix this, I have added another image showing the dependencies.

![image](https://user-images.githubusercontent.com/50376745/124960527-46910480-dfd1-11eb-82e3-da2ce8cb2336.png)

**Comment by bottler** [comment]
I'm also not very familiar. Looking at that, I would guess it's a CPU-only build. It depends on core parts of PyTorch but not cuda stuff. The top three are pytorch things. Maybe you can click on them to find out exactly which functions it wants from them, or what version it wants. You probably have those DLLs in the torch part of your conda environment, and maybe PyTorch3D failing to load PyTorch3D is because there is a mismatch.

MSVCP140 is visual studio 2015. You should build in the Visual Studio 2019 prompt. If you did, then some option has told VS 2019 to use the 2015 runtime. I don't know if that's good or not.

**Comment by MHong94** [comment]
I found those pytorch.dll files in the torch, but not sure why it is not referencing.  Also not sure why it is only installing a CPU-only build, I need to utilize GPU.  Is it easier just to install Ubuntu, then install everything on linux?

**Comment by bottler** [comment]
> Is it easier just to install Ubuntu, then install everything on linux?

Installing PyTorch3D on Windows tends to require quite a lot of understanding and can be quite fiddly. At the moment I think you have two separate problems - why is the build CPU-only, and why does the dll not import. Installing PyTorch3D is much easier on Linux. How easy it is for you to use linux depends on your situation.

**Comment by MHong94** [comment]
I followed the exact steps from the install.md file.  I want to try and get it working on Windows if I can.  Here is what I did and why I don't understand the 2 issues I am having.

1. CPU only build, no cuda
  - installed cudatoolkit=10.2 on conda
  - installed nvidia cuda drivers 10.1
  - downloaded cub library and set env variable `CUB_HOME` library to CMakeLists.txt folder
  - set env variable FORCE_CUDA to 1
  - 
2. Not importing dll
  - One thing I forgot to note is that I cannot build pytorch3d using the latest version of pytorch/torchvision.  I had to revert to version pytorch=1.4.0 and torchvision=0.5.0. 
  - Make some "hacky" changes to code as listed in the install.md file
  - clone local copy, then run `python setup.py install` in x64 Native Tools Command PRompt for VS 2019

Please let me know if there is anything worth trying.

**Comment by bottler** [comment]
It would be helpful if you could include the logs of the build. When you say "2 issues", I am confused about which previous comments are which. Is the depends screenshot from the dll which imports but says "not compiled with GPU support", or the one which fails to import?

**Comment by MHong94** [comment]
The 2 issues are that the build is CPU-only, and the .dll files not correctly importing.  The 'not compiled with GPU support' error is outdated, but come to think of it, that particular build did not run into the issue of .dll imports.

**Comment by MHong94** [comment]
It seems I'm digging myself in a deeper hole.  I can't compile it anymore, and I am being flooded with this error when I try and build it.

```
C:\Users\Matt\anaconda3\lib\site-packages\torch\include\c10/util/Half.h(497): note: see reference to function template instantiation 'bool c10::overflows<To,From>(From)' being compiled
        with
        [
            To=int64_t,
            From=int64_t
        ]

C:\Users\Matt\anaconda3\lib\site-packages\torch\include\c10/util/Half.h(497): note: see reference to function template instantiation 'bool c10::overflows<To,From>(From)' being compiled
        with
        [
            To=int64_t,
            From=int64_t
        ]
```

**Comment by bottler** [comment]
I am still a bit confused, but I think you are saying nothing is importing correctly any more. So "the build is CPU only" is now only a conjecture not a symptom. I can't help without much more detail - can you send build logs and explain how VS 2015 is getting involved?
