### ISSUE TITLE
loss nan when running the " Fit a mesh with texture "  

### ISSUE THREAD

**Issue by Jiakui** [facebookresearch/pytorch3d#748]
I  just  run the  jupyter notebook  example: "Fit a mesh with texture" , and always see the loss become  nan.

My pytorch3d version: 0.4.0 , my pytorch version: 1.7.1, GPU: 1080, python: 3.8 .  

Should I  use the lightly build version of pytorch3d  ?

Thanks !

**Comment by Jiakui** [comment]
this bug is duplicated with  "NaN when using MeshRasterizer #561"  。。

**Comment by nikhilaravi** [comment]
Please follow the instructions in #561 and set `perspective_correct=False` in the rasterization settings. I will close this issue but we will follow up about this bug in #561.
