### ISSUE TITLE
Can I use pytorch3d to cast shadows?

### ISSUE THREAD

**Issue by yoterel** [facebookresearch/pytorch3d#759]
I noticed that when placing two icospheres (or any two distinct objects) one behind another in a scene with a point light, shadows are not cast from one sphere to another. Is there any support for this kind of behavior? (differentiable)
(a.k.a shadow mapping in classical rendering)

Following this question, or to generalize it, does PyTorch3D support any global illumination effects ? (excluding ambient light, since this is trivial).

**Comment by patricklabatut** [comment]
> Is there any support for this kind of behavior?

Not unfortunately there is no support for casting shadows.

> does PyTorch3D support any global illumination effects?

Not at this time, but that is something on our radar.

**Comment by patricklabatut** [comment]
(closed the issue because these feature requests are known and are already tracked in other issues, e.g. [#223](https://github.com/facebookresearch/pytorch3d/issues/223) and [#695](https://github.com/facebookresearch/pytorch3d/issues/695))
