### ISSUE TITLE
How to get the 2D location of each vertex in each render?

### ISSUE THREAD

**Issue by filipetrocadoferreira** [facebookresearch/pytorch3d#76]
Is there any easy way to get the 2D location of each one of the vertices of each rendered image?

**Comment by nikhilaravi** [comment]
@filipetrocadoferreira Do you mean for each pixel in the rendered image you want to know the position of the vertices?

**Comment by filipetrocadoferreira** [comment]
Basically, is applying the same transformations as the render to the 3D and get their 2D location in the image.

**Comment by filipetrocadoferreira** [comment]
using cameras.transform_points() i get the points in 'screen' coordinate system, but to go from this to 2D pixel coordinates I'm having a bit of a trouble

**Comment by nikhilaravi** [comment]
By `2D pixel coordinates` do you mean NDC coordinates in the range [-1, 1] or coordinates in the range x = [0, W],  y = [0, H] where the image is of size (H, W)?

**Comment by filipetrocadoferreira** [comment]
> range x = [0, W], y = [0, H] where the image is of size (H, W)

This one.
I'm having trouble to go from NDC to image coordinates.

**Comment by nikhilaravi** [comment]
Ok so the output of `cameras.transform_points()` will be in NDC coordinates in the range [-1, 1].  If i understand correctly, from this you want to go to pixel coordinates in the range y: [0, H] and x: [0, W].

To do this you just need to do the inverse of this `PixToNdc` function: https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/csrc/rasterize_meshes/rasterize_meshes_cpu.cpp#L12-L15

i.e.  In C++
```
float NdcToPix(int i, int S) {
  // where S is the size of the dimension e.g. H or W
  return ((i + 1.0f) * S - 1.0f)/2.0;
}
```

**Comment by filipetrocadoferreira** [comment]
AH! I think the problem was related with the issue #78 
Doing 

`ndc_points [:,1] *= -1`

solved

**Comment by nikhilaravi** [comment]
@filipetrocadoferreira oh ok makes sense why the rendering problem was affecting your calculations! I will close this issue - please monitor #78 for updates on the rendering fix.
