### ISSUE TITLE
Rasterized outputs do not match transform_points_screen for non-square images

### ISSUE THREAD

**Issue by jbohnslav** [facebookresearch/pytorch3d#761]
## 🐛 Bugs / Unexpected behaviors
I have a scene with a mesh. I have a PerspectiveCamera with non-square image size. Rendering the sphere with the MeshRenderer does not align with the vertices of the mesh projected using PerspectiveCamera.`transform_points_screen.` Everything looks exactly right if the image is square. 

Expected behavior: the projected vertices should align with the where the vertices appear to be when rendered. 

## Instructions To Reproduce the Issue:

```python
# imports 
import matplotlib.pyplot as plt
from pytorch3d.utils import ico_sphere
from pytorch3d.structures import Meshes
from pytorch3d.renderer import (
    look_at_view_transform,
    PerspectiveCameras,
    PointLights, 
    RasterizationSettings, 
    MeshRenderer, 
    MeshRasterizer,  
    SoftPhongShader,
    TexturesVertex
)
import torch

device = torch.device('cuda:0')

# Make a green sphere
mesh1 = ico_sphere(4)  
verts1, faces1 = mesh1.get_mesh_verts_faces(0)
tex1 = torch.zeros_like(verts1) 
tex1[:, 1] = 1.0 # green
tex1 = TexturesVertex(verts_features=[tex1])
mesh = Meshes(verts=[verts1], faces=[faces1], textures=tex1).to(device)

# get vertices directly from Meshes object
points = mesh.verts_list()[0].unsqueeze(0)

# Make an arbitrary light source
lights = PointLights(device=device, location=[[0.0, 0.0, -3.0]])
# get an arbitrary view
R, T = look_at_view_transform(2.7, 0.0, 60.0)

viz_images = []
viz_points = []
for WIDTH in [256, 512]:
    for HEIGHT in [256, 512]:
        cameras = PerspectiveCameras(
                    R=R,
                    T=T,
                    image_size=((WIDTH, HEIGHT),),
                    principal_point=((WIDTH/2, HEIGHT/2),),
                    focal_length=((WIDTH, HEIGHT),),
                    device=device,
                )

        raster_settings = RasterizationSettings(image_size=(HEIGHT, WIDTH))

        # Create a Phong renderer by composing a rasterizer and a shader
        renderer = MeshRenderer(
            rasterizer=MeshRasterizer(cameras=cameras, raster_settings=raster_settings),
            shader=SoftPhongShader(device=device, cameras=cameras,lights=lights
            )
        )
        # pass image size to transform_points_screen
        image_size=torch.Tensor([WIDTH, HEIGHT]).unsqueeze(0).to(device)

        with torch.no_grad():
            image = renderer(mesh) 
            # numpy for visualization
            image = image.detach().cpu().numpy()[0, ..., :3]
            # transform to screen space using the cameras object
            screen_space = cameras.transform_points_screen(points, image_size=image_size)
            screen_space = screen_space.detach().cpu().numpy()[0]

        # save results for visualization
        viz_images.append(image)
        viz_points.append(screen_space)


fig, axes = plt.subplots(2,2,figsize=(16, 9))
axes = axes.flatten()
for i in range(4):
    ax = axes[i]
    imh = ax.imshow(viz_images[i])
    ax.scatter(viz_points[i][:, 0], viz_points[i][:, 1], c='k', s=1)

plt.tight_layout()
plt.show()
```

### results
![image](https://user-images.githubusercontent.com/17788259/125710020-78bc2f35-c4e1-4de7-ab87-1d96fd5232b4.png)

Edits: removed unnecessary code to make it clearer and shorter

**Comment by gkioxari** [comment]
You are right. Our rasterization convention for non-square images do not match `transform_points`. For non-square image rasterization, we assume a `[-1, 1]x[-s,s]` with `the aspect ratio s>1` for the NDC space. For `cameras.transform_points` points are transformed in the `[-1,1]x[-1,1]` space regardless of aspect ratio. We are about to land a fix to this, along with a camera refactor, which will make these things consistent and clear!

**Comment by iAhmedMaher** [comment]
@gkioxari just as an FYI since changes to the cameras are currently being done, I have a similar issue regarding non square images where I am using an orthographic camera. The xmin & xmax visible from the rendered image are much greater that the supplied ones. This happens when the aspect ratio given to the rasterizer surpasses 2.0. I tried different aspect ratio (on a real number scale not int) and it seems 2.0 to be the threshold. Hope this helps figuring out how to squash down those bugs. If more details will help, please let me know.

**Comment by nikhilaravi** [comment]
@jbohnslav, @iAhmedMaher  please see this discussion with the full details of the camera refactor and how to adapt your code to the new conventions: 

https://github.com/facebookresearch/pytorch3d/discussions/783

**Comment by jbohnslav** [comment]
Thanks so much for your work! Here is the above code sample with the PerspectiveCameras initialization changed, and `image_size` removed from the call to `transform_points_screen`: 
```python
# imports 
import matplotlib.pyplot as plt
from pytorch3d.utils import ico_sphere
from pytorch3d.structures import Meshes
from pytorch3d.renderer import (
    look_at_view_transform,
    PerspectiveCameras,
    PointLights, 
    RasterizationSettings, 
    MeshRenderer, 
    MeshRasterizer,  
    SoftPhongShader,
    TexturesVertex
)
import torch

device = torch.device('cuda:0')

# Make a green sphere
mesh1 = ico_sphere(4)  
verts1, faces1 = mesh1.get_mesh_verts_faces(0)
tex1 = torch.zeros_like(verts1) 
tex1[:, 1] = 1.0 # green
tex1 = TexturesVertex(verts_features=[tex1])
mesh = Meshes(verts=[verts1], faces=[faces1], textures=tex1).to(device)

# get vertices directly from Meshes object
points = mesh.verts_list()[0].unsqueeze(0)

# Make an arbitrary light source
lights = PointLights(device=device, location=[[0.0, 0.0, -3.0]])
# get an arbitrary view
R, T = look_at_view_transform(2.7, 0.0, 60.0)

viz_images = []
viz_points = []
for WIDTH in [256, 512]:
    for HEIGHT in [256, 512]:
        cameras = PerspectiveCameras(
                    R=R,
                    T=T,
                    image_size=((HEIGHT, WIDTH),),
                    principal_point=((WIDTH/2, HEIGHT/2),),
                    focal_length=((WIDTH/2, HEIGHT/2),),
                    device=device,
                    in_ndc=False
                )

        raster_settings = RasterizationSettings(image_size=(HEIGHT, WIDTH))

        # Create a Phong renderer by composing a rasterizer and a shader
        renderer = MeshRenderer(
            rasterizer=MeshRasterizer(cameras=cameras, raster_settings=raster_settings),
            shader=SoftPhongShader(device=device, cameras=cameras,lights=lights
            )
        )
        # pass image size to transform_points_screen
        # image_size=torch.Tensor([WIDTH, HEIGHT]).unsqueeze(0).to(device)

        with torch.no_grad():
            image = renderer(mesh) 
            # numpy for visualization
            image = image.detach().cpu().numpy()[0, ..., :3]
            # transform to screen space using the cameras object
            screen_space = cameras.transform_points_screen(points)
            screen_space = screen_space.detach().cpu().numpy()[0]

        # save results for visualization
        viz_images.append(image)
        viz_points.append(screen_space)


fig, axes = plt.subplots(2,2,figsize=(16, 9))
axes = axes.flatten()
for i in range(4):
    ax = axes[i]
    im = viz_images[i]
    imh = ax.imshow(im)
    ax.scatter(viz_points[i][:, 0], viz_points[i][:, 1], c='k', s=1)
    ax.set_xlim([0, im.shape[1]])
    ax.set_ylim([im.shape[0], 0])

plt.tight_layout()
plt.show()
```

And here is the output: 
![image](https://user-images.githubusercontent.com/17788259/129978020-88e31982-17c1-4f64-a073-c0cd49b4a4ef.png)

The rasterized mesh now aligns with the projected points.

**Comment by MohitLamba94** [comment]
> Thanks so much for your work! Here is the above code sample with the PerspectiveCameras initialization changed, and `image_size` removed from the call to `transform_points_screen`:
> 
> ```python
> # imports 
> import matplotlib.pyplot as plt
> from pytorch3d.utils import ico_sphere
> from pytorch3d.structures import Meshes
> from pytorch3d.renderer import (
>     look_at_view_transform,
>     PerspectiveCameras,
>     PointLights, 
>     RasterizationSettings, 
>     MeshRenderer, 
>     MeshRasterizer,  
>     SoftPhongShader,
>     TexturesVertex
> )
> import torch
> 
> device = torch.device('cuda:0')
> 
> # Make a green sphere
> mesh1 = ico_sphere(4)  
> verts1, faces1 = mesh1.get_mesh_verts_faces(0)
> tex1 = torch.zeros_like(verts1) 
> tex1[:, 1] = 1.0 # green
> tex1 = TexturesVertex(verts_features=[tex1])
> mesh = Meshes(verts=[verts1], faces=[faces1], textures=tex1).to(device)
> 
> # get vertices directly from Meshes object
> points = mesh.verts_list()[0].unsqueeze(0)
> 
> # Make an arbitrary light source
> lights = PointLights(device=device, location=[[0.0, 0.0, -3.0]])
> # get an arbitrary view
> R, T = look_at_view_transform(2.7, 0.0, 60.0)
> 
> viz_images = []
> viz_points = []
> for WIDTH in [256, 512]:
>     for HEIGHT in [256, 512]:
>         cameras = PerspectiveCameras(
>                     R=R,
>                     T=T,
>                     image_size=((HEIGHT, WIDTH),),
>                     principal_point=((WIDTH/2, HEIGHT/2),),
>                     focal_length=((WIDTH/2, HEIGHT/2),),
>                     device=device,
>                     in_ndc=False
>                 )
> 
>         raster_settings = RasterizationSettings(image_size=(HEIGHT, WIDTH))
> 
>         # Create a Phong renderer by composing a rasterizer and a shader
>         renderer = MeshRenderer(
>             rasterizer=MeshRasterizer(cameras=cameras, raster_settings=raster_settings),
>             shader=SoftPhongShader(device=device, cameras=cameras,lights=lights
>             )
>         )
>         # pass image size to transform_points_screen
>         # image_size=torch.Tensor([WIDTH, HEIGHT]).unsqueeze(0).to(device)
> 
>         with torch.no_grad():
>             image = renderer(mesh) 
>             # numpy for visualization
>             image = image.detach().cpu().numpy()[0, ..., :3]
>             # transform to screen space using the cameras object
>             screen_space = cameras.transform_points_screen(points)
>             screen_space = screen_space.detach().cpu().numpy()[0]
> 
>         # save results for visualization
>         viz_images.append(image)
>         viz_points.append(screen_space)
> 
> 
> fig, axes = plt.subplots(2,2,figsize=(16, 9))
> axes = axes.flatten()
> for i in range(4):
>     ax = axes[i]
>     im = viz_images[i]
>     imh = ax.imshow(im)
>     ax.scatter(viz_points[i][:, 0], viz_points[i][:, 1], c='k', s=1)
>     ax.set_xlim([0, im.shape[1]])
>     ax.set_ylim([im.shape[0], 0])
> 
> plt.tight_layout()
> plt.show()
> ```
> 
> And here is the output: ![image](https://user-images.githubusercontent.com/17788259/129978020-88e31982-17c1-4f64-a073-c0cd49b4a4ef.png)
> 
> The rasterized mesh now aligns with the projected points.

Hello @jbohnslav,
Thankyou for this piece of code. It works with out of the box with `PerspectiveCameras` but I use `FoVPerspectiveCameras` in my project and the changes suggested over here such as `in_ndc=False` are not applicable for it. Could you please help out on this?

**Comment by RunsenXu** [comment]
> > Thanks so much for your work! Here is the above code sample with the PerspectiveCameras initialization changed, and `image_size` removed from the call to `transform_points_screen`:
> > ```python
> > # imports 
> > import matplotlib.pyplot as plt
> > from pytorch3d.utils import ico_sphere
> > from pytorch3d.structures import Meshes
> > from pytorch3d.renderer import (
> >     look_at_view_transform,
> >     PerspectiveCameras,
> >     PointLights, 
> >     RasterizationSettings, 
> >     MeshRenderer, 
> >     MeshRasterizer,  
> >     SoftPhongShader,
> >     TexturesVertex
> > )
> > import torch
> > 
> > device = torch.device('cuda:0')
> > 
> > # Make a green sphere
> > mesh1 = ico_sphere(4)  
> > verts1, faces1 = mesh1.get_mesh_verts_faces(0)
> > tex1 = torch.zeros_like(verts1) 
> > tex1[:, 1] = 1.0 # green
> > tex1 = TexturesVertex(verts_features=[tex1])
> > mesh = Meshes(verts=[verts1], faces=[faces1], textures=tex1).to(device)
> > 
> > # get vertices directly from Meshes object
> > points = mesh.verts_list()[0].unsqueeze(0)
> > 
> > # Make an arbitrary light source
> > lights = PointLights(device=device, location=[[0.0, 0.0, -3.0]])
> > # get an arbitrary view
> > R, T = look_at_view_transform(2.7, 0.0, 60.0)
> > 
> > viz_images = []
> > viz_points = []
> > for WIDTH in [256, 512]:
> >     for HEIGHT in [256, 512]:
> >         cameras = PerspectiveCameras(
> >                     R=R,
> >                     T=T,
> >                     image_size=((HEIGHT, WIDTH),),
> >                     principal_point=((WIDTH/2, HEIGHT/2),),
> >                     focal_length=((WIDTH/2, HEIGHT/2),),
> >                     device=device,
> >                     in_ndc=False
> >                 )
> > 
> >         raster_settings = RasterizationSettings(image_size=(HEIGHT, WIDTH))
> > 
> >         # Create a Phong renderer by composing a rasterizer and a shader
> >         renderer = MeshRenderer(
> >             rasterizer=MeshRasterizer(cameras=cameras, raster_settings=raster_settings),
> >             shader=SoftPhongShader(device=device, cameras=cameras,lights=lights
> >             )
> >         )
> >         # pass image size to transform_points_screen
> >         # image_size=torch.Tensor([WIDTH, HEIGHT]).unsqueeze(0).to(device)
> > 
> >         with torch.no_grad():
> >             image = renderer(mesh) 
> >             # numpy for visualization
> >             image = image.detach().cpu().numpy()[0, ..., :3]
> >             # transform to screen space using the cameras object
> >             screen_space = cameras.transform_points_screen(points)
> >             screen_space = screen_space.detach().cpu().numpy()[0]
> > 
> >         # save results for visualization
> >         viz_images.append(image)
> >         viz_points.append(screen_space)
> > 
> > 
> > fig, axes = plt.subplots(2,2,figsize=(16, 9))
> > axes = axes.flatten()
> > for i in range(4):
> >     ax = axes[i]
> >     im = viz_images[i]
> >     imh = ax.imshow(im)
> >     ax.scatter(viz_points[i][:, 0], viz_points[i][:, 1], c='k', s=1)
> >     ax.set_xlim([0, im.shape[1]])
> >     ax.set_ylim([im.shape[0], 0])
> > 
> > plt.tight_layout()
> > plt.show()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And here is the output: ![image](https://user-images.githubusercontent.com/17788259/129978020-88e31982-17c1-4f64-a073-c0cd49b4a4ef.png)
> > The rasterized mesh now aligns with the projected points.
> 
> Hello @jbohnslav, Thankyou for this piece of code. It works with out of the box with `PerspectiveCameras` but I use `FoVPerspectiveCameras` in my project and the changes suggested over here such as `in_ndc=False` are not applicable for it. Could you please help out on this?

I encountered the same problem when using FovPerspectiveCameras and found that I should pass image_size: (height, width) not (width, height) to transform_points_screen then everything looks good. Maybe you should check this.
