### ISSUE TITLE
where is the c++ implementation 

### ISSUE THREAD

**Issue by bigdimboom** [facebookresearch/pytorch3d#762]
Doc points out that there are C++ and CUDA implementations. Where can I get the code? 
![image](https://user-images.githubusercontent.com/6119906/125710821-a933909f-5330-4496-a05f-a0b6412da390.png)

**Comment by bottler** [comment]
This is talking about the mesh rasterizer. Its C++ and CUDA implementations are [here](https://github.com/facebookresearch/pytorch3d/tree/v0.4.0/pytorch3d/csrc/rasterize_meshes).
