### ISSUE TITLE
Ray-triangle intersection algorithm

### ISSUE THREAD

**Issue by MingfeiCh** [facebookresearch/pytorch3d#765]
Hi,
I don't know what ray-triangle intersection algorithm is used in PyTorch3D. Is the Moller-Trumbore algorithm implemented in PyTorch3D? Thank you!

**Comment by bottler** [comment]
I don't think we have a direct calculation to find the intersection point of a ray and a triangle. For example, the mesh rasterizer doesn't use one.

**Comment by patricklabatut** [comment]
As noted by @bottler, for mesh rendering, PyTorch3D is not using ray tracing (that would require ray / triangle intersections) but rasterization instead. Other renderers (point cloud and volume / implicit) also do not require ray / triangle intersections.
