### ISSUE TITLE
Can this optimized light model be loaded into unreal engine for real environment map ?

### ISSUE THREAD

**Issue by lith0613** [facebookresearch/pytorch3d#770]
I have used the pytorch3d to learn a light model to render the texture, but now I wonder how can I load the learned light model into unreal engine ?

**Comment by patricklabatut** [comment]
Once light parameters have been learned, you would have to export them for Unreal Engine to consume. I am not familiar with this specific engine, but 3D engines typically support a common set of light sources (e.g. ambient, directional, point, spot, etc...) that should be a superset of what PyTorch3D supports. You could simply instantiate the relevant ones with the learned parameters to render a matching scene in Unreal Engine.
