### ISSUE TITLE
How to : train and optimise only once with variations of object and predict with real life images to obtain a mesh later in run-time

### ISSUE THREAD

**Issue by shank-imironman** [facebookresearch/pytorch3d#771]
Hi Team,

Thank you so much this awesome library !
I have two how to questions:

1. I am using this example provided in repo "fit_textured_mesh.ipynb". In the example, I would like to load multiple meshes of variations of same category object example: holestien_cow, angus_cow.obj,some other cows.... and I want it generalize on all.
 
![image](https://user-images.githubusercontent.com/21685831/126620429-0763b41b-c938-4ce7-bf39-fb0581004153.png)

2. Once optimisation and training is done, instead of predicting on synthetic images created by library, I would like to load a real-life image with opencv with imread, preprocess it, if required(I can do it -- this doesn't need to be perfect) and predict on that loaded image to get a mesh. It doesn't have to be perfect. 

**Goal to achieve is train and optimise only once with variations of object and predict with real life images to obtain a mesh later in run-time. but for now if it can do only one time that also is fine **

Please, if anyone can help with it that will be great !, if it's not possible to do it, please guide me to similar approach where it is possible.
Dataset Information : I have RGB images of cows, segmented masks, and 3D obj files with texture. Sadly no 2D/3D key-points, so I cannot use it with major reconstruction frameworks. It's not feasible for me to do key-point annotation now.

**Comment by patricklabatut** [comment]
This sounds like a research project: I don't think there is something particularly actionable for us unfortunately, but good luck with your project!
