### ISSUE TITLE
Can PyTorch3D render depth images and binary images?

### ISSUE THREAD

**Issue by ChengChen2020** [facebookresearch/pytorch3d#773]
## ❓ Questions on how to use PyTorch3D

The default renderer will return RGBA 4-channel images.
Can PyTorch3D renderer depth images and binary images?

Thanks!

**Comment by patricklabatut** [comment]
One can easily create a custom shader (and associated renderer) that outputs single channel images instead (see [code](https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/renderer/mesh/renderer.py#L60)).
