### ISSUE TITLE
Extracting Camera Intrinsics? 

### ISSUE THREAD

**Issue by collinskatie** [facebookresearch/pytorch3d#775]
## ❓ Questions on how to use PyTorch3D

Hi, I'm trying to extract the camera intrinsic parameters (K with fx and fy + cx,cy or px,py), and I was having a bit of trouble identifying how best to do that, in PyTorch3D. 

Right now, I'm using `.compute_projection_matrix()` from the [docs](https://pytorch3d.readthedocs.io/en/latest/modules/renderer/cameras.html); however, the matrix I'm getting doesn't seem to match the structure of K in the [documentation for the function](https://github.com/facebookresearch/pytorch3d/blob/6c4151a820658168dd56b85f21b60e6bcf599c92/pytorch3d/renderer/cameras.py#L898). I realize a similar question was asked in #611, though I remain a bit unclear as to whether it's possible to get a 3x3 K matrix, as @faneggs had asked?

Below is the code that I used to try to get the camera intrinsics.
```
R, T = look_at_view_transform(3.7, 0.1, 180, at=((-0.15, 0.0, 0.1),),)
cameras = FoVPerspectiveCameras(device=device, R=R, T=T)
znear = 1.0
zfar = 100.0 
fov = 60
degrees = True
aspect_ratio = 1.0
K = cameras.compute_projection_matrix(znear, zfar, fov, aspect_ratio, degrees)
```
And the corresponding entries outputted for K:
```
tensor([[[ 1.7321,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  1.7321,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  1.0101, -1.0101],
         [ 0.0000,  0.0000,  1.0000,  0.0000]]])
```

Apologies if I'm completely misinterpreting the output of this function. Thank you so much for any help!

**Comment by patricklabatut** [comment]
`FoVPerspectiveCameras` is following OpenGL conventions for projection. If you are looking for a `K` matrix closer to SfM-style intrinsic matrices, use `PerspectiveCameras` instead (and `get_projection_transform()`). This is actually the class the documentation you are referring to is pointing to.

**Comment by collinskatie** [comment]
Ah yes, I had linked to that camera instead! Thanks for your help @patricklabatut !
