### ISSUE TITLE
Silhouette Boundary

### ISSUE THREAD

**Issue by yaadhavraajagility** [facebookresearch/pytorch3d#776]
![image](https://user-images.githubusercontent.com/85202628/126821859-8b3800f4-280e-4859-a05d-d9759dd2c5cc.png)

Is there functionality to generate a differentiable boundary image of the rendered object

**Comment by patricklabatut** [comment]
Silhouette shaders are provided (see this [tutorial](https://pytorch3d.org/tutorials/fit_textured_mesh)) but these generate inside / outside masks, not the boundary of the mask.

**Comment by patricklabatut** [comment]
To generate a silhouette boundary mask, here are a few ideas off the top of my head:
- With smooth normals (e.g. with a sphere, not with the provided cube example): implement a custom shader that smoothly extracts a silhouette boundary using the dot product of the fragment normal and the ray direction (that's typical cel-shading). Note this will find edges on all occlusion boundaries (e.g. holes), 
- With hard normals (the provided cube example), which would make typical cel-shading techniques fail), you could try rendering a slightly enlarged object to get a larger silhouette mask and then smoothly combine this new mask with the mask of the normal object to extract a boundary.

**Comment by nikhilaravi** [comment]
@yaadhavraajagility as @patricklabatut mentioned you could try to use a silhouette shader, compute the alpha mask which should be a grayscale value and then threshold it to get the boundary.  This will require setting `blur_radius > 0` in the renderer settings and also `faces_per_pixel > 1`.  (NOTE this suggestion is untested!)

**Comment by yaadhavraajagility** [comment]
thanks for the responses. before i close this, i want to ask, cant i just apply a sobel or some edge detection filter over the silhouette boundary. how would that be different from what you both suggest
