### ISSUE TITLE
Rendering is flipped

### ISSUE THREAD

**Issue by HectorAnadon** [facebookresearch/pytorch3d#78]
Hello,

I believe that the rendering is being flipped in the X axis. For example, if we see the image render in the tutorial [render_textured_meshes](https://github.com/facebookresearch/pytorch3d/blob/master/docs/tutorials/render_textured_meshes.ipynb) the image looks like this: 
![image](https://user-images.githubusercontent.com/12595599/74937118-bd812980-53eb-11ea-85da-7c0035fd0a0b.png)
However, in meshlab
![Screenshot from 2020-02-20 14-12-36](https://user-images.githubusercontent.com/12595599/74937151-cbcf4580-53eb-11ea-83d8-bdbbe49af487.png)
You can see in the texture that the eyes are in the other direction. It is not the texture mapping as I have tested with non-symmetric objs.

**Comment by nikhilaravi** [comment]
@HectorAnadon thanks for pointing this out. I will check the texture interpolation code and get back to you.

**Comment by HectorAnadon** [comment]
Sorry, it is not the texture interpolation

**Comment by HectorAnadon** [comment]
![Screenshot from 2020-02-20 14-08-36](https://user-images.githubusercontent.com/12595599/74945867-b9a7d400-53f8-11ea-8f15-2dbda33eb159.png)
![Screenshot from 2020-02-20 14-08-43](https://user-images.githubusercontent.com/12595599/74945870-bad90100-53f8-11ea-9a1c-e2996ad176b9.png)

Back of the object

**Comment by HectorAnadon** [comment]
![Screenshot from 2020-02-20 13-24-34](https://user-images.githubusercontent.com/12595599/74945910-cb897700-53f8-11ea-8fa6-2659130bffe6.png)
![Screenshot from 2020-02-20 13-24-51](https://user-images.githubusercontent.com/12595599/74945916-cc220d80-53f8-11ea-8319-5d3bf073391f.png)

Front of the object

**Comment by HectorAnadon** [comment]
Might it be that the X axis is inverted?

**Comment by davegreenwood** [comment]
Yes, I agree X is flipped. In the NDC space, if it is right-handed with z-min at z-near, then x should be positive to the left. However, in the projection matrices it is positive to the right.

For the tutorials teapot example, if we get the camera position using camera_position_from_spherical_angles, it is [ 0.3991,  1.9284, -2.2632].
So the camera is 'behind' the teapot in world space.

here is an image to show what I mean:
![image](https://user-images.githubusercontent.com/7338381/75039887-81b09780-54b1-11ea-9b1b-7aca420c9b19.png)
it is clear from this image that the teapot example should show the spout on the left, yet in the example it is spout to the right:
![image](https://user-images.githubusercontent.com/7338381/75040151-0bf8fb80-54b2-11ea-92ee-a50070c2ce00.png)

**Comment by davegreenwood** [comment]
I think I should add some more information:
The first image I posted is from the viewport of Maya. This software uses the same coordinates as OpenGL: y-up, right handed. In the image, the red, green, blue gnomon indicates x, y, z world coordinates.
To position the camera, I called the function: camera_position_from_spherical_angles to give the camera position alongside the teapot object in world space.
Now, we can see an image from that camera should produce an image of the teapot with the spout to the left, yet the tutorial result shows the spout to the right.

There are two possible reasons:
1. The camera extrinsic matrix should position the camera at positive z, but look at the same point. Although all the light positions could be effected. For what it's worth,  I don't think this is the problem :)
2. The camera intrinsic matrix. It is stated that the NDC is also right handed, so if we maintain y-up and have zmin at znear, then x should be positive to the left. In OpenGL the NDC is left handed y-up, with x positive to the right. There is a nice illustration here: http://www.songho.ca/opengl/gl_projectionmatrix.html#perspective
So, if your NDC is right handed as I described you should change x direction in the intrinsic matrix composition, by negating the x-scale in the matrix. Again, for what it's worth, I think this is where the problem lies.

As an example here is a view with that suggested change, and including a light at [1.0, 1.0, -2.0].

![flipped](https://user-images.githubusercontent.com/7338381/75157537-3b0aa980-570c-11ea-8df3-65971f39c6dd.png)

I made a change to the intrinsic matrix in cameras.py line 133 like so:

    P[:, 0, 0] = 2.0 * znear / (right - left)

to:

    P[:, 0, 0] = - 2.0 * znear / (right - left)

You can see that flipping the x gives the expected object orientation,
light highlight etc. given the positions of all objects in world space.

**Comment by nikhilaravi** [comment]
@HectorAnadon thanks for raising this important issue and @davegreenwood thanks for helping answer it.

The coordinate system we use during rasterization is positive y pointing down, positive x pointing to the right, and positive z pointing in to the page. This is a right hand coordinate system but results in the object in the image being "upside down". 

<img width="360" alt="Screen Shot 2020-02-25 at 10 33 54 PM" src="https://user-images.githubusercontent.com/5912647/75318334-04718380-581f-11ea-8d17-957523c171d3.png">

In the blending functions the y axis is flipped at the end which results in mirroring of the image in the y direction but causes the problem mentioned in this issue - the resulting coordinate frame is no longer right handed (i.e. positive x to the right, positive y upwards and positive z into the screen)

<img width="344" alt="Screen Shot 2020-02-25 at 10 34 00 PM" src="https://user-images.githubusercontent.com/5912647/75318343-0a676480-581f-11ea-86a7-260102f98914.png">

Regarding the cow example, I had a look at SoftRasterizer which the PyTorch3D rasterization implementation is inspired by - [their image](https://raw.githubusercontent.com/ShichenLiu/SoftRas/master/data/media/demo/render/forward.gif) is also incorrect in the x direction. They solve the y up/down problem by reversing the y axis **during the rasterization step** (as opposed to blending) but do not reverse the x axis.

For a quick fix, you can change the calls to `torch.flip` to specify flipping in dimensions [1, 2] which will flip the image in both the x and y directions. e.g. 

https://github.com/facebookresearch/pytorch3d/blob/f358b9b14dbc1414c588f308b35f55705d777873/pytorch3d/renderer/blending.py#L184

https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/renderer/blending.py#L90

Replace with:
```
return torch.flip(pix_colors, [1, 2])
```

It would be much cleaner to add a hack here than make any changes to the perspective projection matrices mentioned above. 

For a more thorough fix we will be changing the rasterization code: the default will assume the same coordinate frame as meshlab. We will also enable a setting for users to specify which direction y should be and x will be computed accordingly to give a right handed system.   

<img width="358" alt="Screen Shot 2020-02-25 at 10 34 19 PM" src="https://user-images.githubusercontent.com/5912647/75318525-7a75ea80-581f-11ea-8c35-de8c8001530b.png">

<img width="383" alt="Screen Shot 2020-02-25 at 10 34 28 PM" src="https://user-images.githubusercontent.com/5912647/75318529-7cd84480-581f-11ea-8687-b10136b626b7.png">

**Comment by HectorAnadon** [comment]
Thank you @nikhilaravi. Looking forward to the fix in the rasterization code. Do you have any estimate when the fix will be applied? Thanks!

**Comment by HectorAnadon** [comment]
I am assuming that this line should be updated too https://github.com/facebookresearch/pytorch3d/blob/f358b9b14dbc1414c588f308b35f55705d777873/pytorch3d/renderer/blending.py#L41

**Comment by nikhilaravi** [comment]
@HectorAnadon yes we will update the rasterization code and all the blending functions. We will try to get this fix into master by the end of the week. I will update this issue when the fix has been merged!

**Comment by nikhilaravi** [comment]
We have landed a fix for this and updated the documentation for the renderer. The convention for world and camera coordinates is explained by this diagram:

![world_camera_image](https://user-images.githubusercontent.com/5912647/76094441-8d748180-5fba-11ea-98d0-e0131e2e1d40.png)

**Comment by HectorAnadon** [comment]
@nikhilaravi I haven't test it in depth, but now it looks like Y axis is flipped.

**Comment by nikhilaravi** [comment]
@HectorAnadon what do you mean?

**Comment by HectorAnadon** [comment]
![Screenshot from 2020-03-06 16-24-29](https://user-images.githubusercontent.com/12595599/76096891-0b3e8a00-5fc7-11ea-8d88-ab173f5cdab1.png)

With this camera `R, T = look_at_view_transform(5, 0, 0, device=device)
`

**Comment by HectorAnadon** [comment]
Okay, forget everything. I needed to rebuilt the repository. Pulling was not enough. Is that the recommended way to be up to day? Or shall I use pip from github directly? Sorry for the missunderstanding @nikhilaravi and great work! Thanks for fixing it so fast

**Comment by nikhilaravi** [comment]
@HectorAnadon yes you can install directly from github or if you need to edit any of the code you can pull from master, delete the `build` directory and rebuild.

**Comment by davegreenwood** [comment]
hi @HectorAnadon, could you say exactly what you did to avoid the y-flip you first noticed?
I have git pulled master from here to a clean directory, and done `pip install -e .` and I get y-flipped. 
This is on linux and macOS.
I'm just trying to track down where this happens on our install.
thanks!

**Comment by davegreenwood** [comment]
Actually, I've got it - but in case anyone else is wondering - I had written a custom blend function, and now the rasteriser does not require the flip on return. All, good now :)

**Comment by nikhilaravi** [comment]
@davegreenwood great!!

**Comment by unlugi** [comment]
Has this been fixed, because I am still getting flipped renders around Y axis like mirror? Or do we need to manually flip renders each time?
