### ISSUE TITLE
Found conflicts! UnsatisfiableError: The following specifications were found to be incompatible with each other

### ISSUE THREAD

**Issue by 1337602899** [facebookresearch/pytorch3d#780]
When I run "conda install pytorch3d -c pytorch3d" I encountered a mistake: 

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - feature:|@/linux-64::__glibc==2.31=0

Your installed version is: 2.31

My glibc version is 2.31. The OS is Ubuntu 20.04.2. Which package caused the conflict? What do I need to install? And how can I solve it?

**Comment by bottler** [comment]
Can you paste the output of `conda list` and `conda info`? Thanks
