### ISSUE TITLE
What should I do if I want to place several different PointLights in the scene? Seems that I cannot stack multi lights. 

### ISSUE THREAD

**Issue by JasonBoy1** [facebookresearch/pytorch3d#784]
Thank you for your help.

**Comment by JasonBoy1** [comment]
Anyone can help?

**Comment by bottler** [comment]
Hi. PyTorch3D currently doesn't support this. See also issue #241.

**Comment by JasonBoy1** [comment]
> Hi. PyTorch3D currently doesn't support this. See also issue #241.

Thank you. Is that on a TODO list? I think it would be promising for pytorch3d work for both neural rendering and high-quality displaying.

**Comment by nikhilaravi** [comment]
I will close this issue as #241 already exists. This feature is on our radar but not currently on the roadmap.

**Comment by zzj403** [comment]
> I will close this issue as #241 already exists. This feature is on our radar but not currently on the roadmap.

Hi, is there any progress?  We also need  some combination like ( directional_light + ambient_light ). Thanks!
