### ISSUE TITLE
How to render high quality images? 

### ISSUE THREAD

**Issue by JasonBoy1** [facebookresearch/pytorch3d#787]
Could you highlight some parameters in raster_settings controlling the render quality and the tradeoff between speed and quality?
For example, could I speed up the rendering if I enlarge the blur radius? I also cannot figure out the importance of bin_size and faces_per_pixel from your documents. like [document](https://pytorch3d.readthedocs.io/en/latest/_modules/pytorch3d/renderer/mesh/rasterize_meshes.html#rasterize_meshes).

**Comment by nikhilaravi** [comment]
@JasonBoy1, what do you mean by quality?  Do you only need to do the forward pass for rendering or also the backward pass?

Regarding the settings: 
- `blur_radius` should only be non-zero if you need rendering to be differentiable 
- `bin_size=None` will result in the bin_size being set heuristically so you shouldn't need to modify it
- ` faces_per_pixel` - this is used along with blur_raidius to achieve differentiability. `faces_per_pixel=1` should be used when you don't need to do the backward pass of rendering.

**Comment by JasonBoy1** [comment]
thanks. I mean the forward pass. I think it would be great for pytorch3d both work as a differentiable render tool and high-quality visualization tool.

**Comment by JasonBoy1** [comment]
Maybe a high quality render(none-differentiable, only for visualization) tutorial could be released.

**Comment by JasonBoy1** [comment]
![image](https://user-images.githubusercontent.com/33180378/128303603-8b777a39-bfbc-49f9-a7b0-9c897b9c04f8.png)
could you tell me how to
