### ISSUE TITLE
How to do anti-aliasing in pytorch3d?

### ISSUE THREAD

**Issue by JasonBoy1** [facebookresearch/pytorch3d#788]
![image](https://user-images.githubusercontent.com/33180378/128303724-81a424e5-0cf3-437f-a182-d7e839f6be2a.png)
as you can see, I want to relieve the serrated contour.

**Comment by JasonBoy1** [comment]
could you help me?

**Comment by bottler** [comment]
Can you have a look at the suggestion is issue #399?

**Comment by JasonBoy1** [comment]
> Can you have a look at the suggestion in issue #399?

Supersampling is reasonable but seems not so 'graphics' to me.
I tried the blend_params but get wired results. It mostly changes the color not the edge.

![image](https://user-images.githubusercontent.com/33180378/128657975-a0eb3545-922c-441e-8e9f-460bc60ed0ea.png)

this is the result of official tutorial cow mesh rendering,  I set blend_params=BlendParams(background_color=(1,1,1), sigma=1, gamma=1), the edge is still serrated, and the color becomes too light.

**Comment by nikhilaravi** [comment]
The blend params will change the edges and the opacity so this is not the correct way to resolve the anti aliasing issue.. The explanation in #339 to render at a higher resolution and then use average pooling to reduce back to the target resolution is the correct method.  Were you able to try this?

Note that the PyTorch3D renderer forward pass is designed to support differentiability so some things will naturally be different to a graphics pipeline.

**Comment by JasonBoy1** [comment]
> The blend params will change the edges and the opacity so this is not the correct way to resolve the anti aliasing issue.. The explanation in #339 to render at a higher resolution and then use average pooling to reduce back to the target resolution is the correct method. Were you able to try this?
> 
> Note that the PyTorch3D renderer forward pass is designed to support differentiability so some things will naturally be different to a graphics pipeline.

Thank you. I appreciate your help.

I am a big fan of pytorch3d, so I want to use it both for differentiable render and visualization in my repo.

**Comment by nikhilaravi** [comment]
@JasonBoy1 That is great to hear!! We are planning to do a review to compare PyTorch3D renderer with other graphics renderers to try to support your use case better in future :)
