### ISSUE TITLE
Something is wrong with cubify function

### ISSUE THREAD

**Issue by srahmatian** [facebookresearch/pytorch3d#793]
Hi,
Thanks for sharing code of this project.

I wanted to convert a voxel to a mesh, and I tested the cubify function with a simple data. The code is as following.

from pytorch3d.ops import cubify
voxel = torch.ones(1, 10, 10, 10)
mesh = cubify(voxel, thresh=0.1, align="corner")

And I got this error:
RuntimeError: Expected index [3600] to be smaller than self [1331] apart from dimension 0 and to be smaller size than src [1331].

Becuase at this line "idleverts.scatter_(0, grid_faces.flatten(), 0)",  "idleverts" has 1331 elements but "grid_faces.flatten()" has 3600 elements.

But when I increased the voxel's size (voxel = torch.ones(1, 40, 40, 40)), I got no error. I think when the voxel has a small size it happens.
Is there a way to fix this bug?

Best regards

**Comment by gkioxari** [comment]
There seems to be an issue with PyTorch's scatter function in CPU. See this issue https://github.com/facebookresearch/pytorch3d/issues/513

Could you verify if you get this with CUDA?

**Comment by srahmatian** [comment]
Thanks for your comment,
I checked it with CUDA, and there was no problem.
