### ISSUE TITLE
Unable to import se3_exp_map and se3_log_map transforms

### ISSUE THREAD

**Issue by nivesh48** [facebookresearch/pytorch3d#795]
from pytorch3d.transforms import se3_exp_map, se3_log_map

Unable to import the above functions from transforms

Note: Some of the other libraries in pytorch3d.transforms are working fairly as far i've tried. Could please you help me know why aren't the exponential and logarithmic functions are unable to be imported @nikhilaravi

**Comment by nikhilaravi** [comment]
What error are you getting? What version of PyTorch3D are you using and how are you installing it?

**Comment by nivesh48** [comment]
pytorch3d version is 0.3.0
Installed using PyPi, as building from source is taking for ever
from pytorch3d.transforms import se3_exp_map
Error: cannot import name 'se3_exp_map' from 'pytorch3d.transforms'

**Comment by nikhilaravi** [comment]
`se3_exp_map` was not available in v0.3.0 of PyTorch3D.   See here for the available functions in v0.3.0: https://github.com/facebookresearch/pytorch3d/blob/v0.3.0/pytorch3d/transforms/__init__.py 

SE3 exponential and logarithm maps were only added in v0.5.0 so please install this latest version to use these functions.

**Comment by nivesh48** [comment]
Noted and thank you very much.

**Comment by nivesh48** [comment]
@nikhilaravi, i have doubt are these pytorch3d transform functions autograd enabled? and can we directly dot product two exponential maps for the composite transformations ?
