### ISSUE TITLE
Rendered RGB texture is completely white from blender mesh data.

### ISSUE THREAD

**Issue by zl548** [facebookresearch/pytorch3d#797]
Hi,

I tried to use Pytorch3D to render RGB texture and depth from a Minecraft converted mesh data. The obj files currently work fine on blender and Meshlab. When I use renderer in pytorch, the depth map looks OK (left of the figure below), but rendered texture map is completely white (right of figure below)

![test](https://user-images.githubusercontent.com/7671455/128615436-88cb82d5-975f-45b0-a7c2-3d64371e86af.png)

The obj files used:
[https://drive.google.com/file/d/1vj7WNtqxHDXRrCRaGEXkk6ZTNdpeUNyd/view?usp=sharing](url)
The simple rendering code to reproduce the issue based on instructions:
[https://drive.google.com/file/d/1S1_IpEyxEIZ8p3vSpg5MicUraMc-rU0N/view?usp=sharing](url)

Do you have any idea why the loaded textures do not work properly?

Thanks

**Comment by gkioxari** [comment]
Hints to debug: 
* What does the silhouette look like? `images[0, ..., 3]`
* Is it possible your cameras are off? Check the vertices of the mesh after the R, T transform, aka the vert coords right before they are rendered. Is their scale correct?

**Comment by nikhilaravi** [comment]
@zl548 I am unable to open the links that you shared above. Can you share the files again?

**Comment by gkioxari** [comment]
I figured the issue out. 

`SoftPhongShading` performs a `softmax_rgb_blend` which uses `znear` and `zfar`. 

https://github.com/facebookresearch/pytorch3d/blob/9db70400d8804a80e31877fdcc2efd545b05f24c/pytorch3d/renderer/mesh/shader.py#L157-L158

The z values of your mesh range from 300 to 700 (roughly). So the default values don't work. Setting `znear=300` and `zfar=705` in the cameras

```python
cameras = FoVPerspectiveCameras(device=device, fov=60.0, R=R, T=T, znear=300, zfar=705)
```

gives the right output (first: soft silhouette, second: texture)
![silh](https://user-images.githubusercontent.com/4369065/129057187-cb6d3978-9c9e-4a6f-9255-ca957ab33f21.png)
![rgb](https://user-images.githubusercontent.com/4369065/129057244-0429e706-890a-42fc-b3b9-4ff98bcc58d5.png)

**Comment by zl548** [comment]
Great, thank you very much!

**Comment by sinanbayraktar** [comment]
@gkioxari How do we set `zfar` and `znear` in a `PerspectiveCameras `?
