### ISSUE TITLE
How to close the interpolation in triangle colors?

### ISSUE THREAD

**Issue by JasonBoy1** [facebookresearch/pytorch3d#798]
I rendered a SMPL mesh and used  HardFlatShader. I find that the interpolation still exists between different colors.
The bottom image shows the interpolation on ankle.

![image](https://user-images.githubusercontent.com/33180378/128663523-7fbbc464-08f8-4d94-bfa1-cf85cf3f2a03.png)

![image](https://user-images.githubusercontent.com/33180378/128663627-644d0fb1-229e-423e-be1e-44068e2fc2d4.png)

What I want is that every triangle should be assigned the color of the vertices. If the three vertices share different colors, the color of triangle should not be interpolated, but choose one of them.

**Comment by nikhilaravi** [comment]
Are you using the `TexturesVertex` class? The `sample_textures` function will interpolate the vertex textures for each face based on the barycentric coordinates: 

https://github.com/facebookresearch/pytorch3d/blob/4046677cf1f8a6e5e9f9e8ef43e5c25200183c64/pytorch3d/renderer/mesh/textures.py#L1385-L1412

You could create a subclass of `TexturesVertex` and override the `sample_textures` function to implement the sampling strategy you require - i.e. based on the vertex indices of each face, and the barycentric coordinates of the point on the face, you could choose the closest vertex.

**Comment by JasonBoy1** [comment]
> Are you using the `TexturesVertex` class? The `sample_textures` function will interpolate the vertex textures for each face based on the barycentric coordinates:
> 
> https://github.com/facebookresearch/pytorch3d/blob/4046677cf1f8a6e5e9f9e8ef43e5c25200183c64/pytorch3d/renderer/mesh/textures.py#L1385-L1412
> 
> You could create a subclass of `TexturesVertex` and override the `sample_textures` function to implement the sampling strategy you require - i.e. based on the vertex indices of each face, and the barycentric coordinates of the point on the face, you could choose the closest vertex.

Yes, I used TexturesVertex. Thank you for your help! I would try this.

**Comment by nikhilaravi** [comment]
Great! I'll close this issue but if you have any further questions, feel free to reopen it.

**Comment by JasonBoy1** [comment]
Hi, @nikhilaravi . Sorry to bother. But I read carefully but still don't know how to **choose the closest vertex**. Could you point that to me?
Thanks a lot.
