### ISSUE TITLE
Any plan for raytracing? TPU?

### ISSUE THREAD

**Issue by magicknight** [facebookresearch/pytorch3d#80]
## 🚀 Feature
Hi, do you have any plan for implementing ray tracing on this package? 

## Motivation
I noticed that the rendering in this package is using rastering & Phong shading. The image is good but still not so realisitic.  Just wondering if or not the ray tracing is on the road map. 
Also can this package run on TPU? Thanks.

## Pitch

NOTE: we only consider adding new features if they are useful for many users.

**Comment by nikhilaravi** [comment]
@magicknight do you need to use the ray tracing as part of a deep learning pipeline or only for forward rendering?

**Comment by magicknight** [comment]
> @magicknight do you need to use the ray tracing as part of a deep learning pipeline or only for forward rendering?

Hi nikhilaravi,
Thank you for reply.
I am planning to use it as part of pipline. Some interesting research can be done here. 
Do you think it is a lot of work if I write it myself on pytorch? Thanks.

**Comment by nikhilaravi** [comment]
@magicknight differentiable ray tracing is not on our roadmap. There are existing open source implementations which you could try e.g. https://github.com/BachiLi/redner, but we haven't tried them so cannot guarantee they will be suitable for your use case. TPU support is also not on our roadmap.
