### ISSUE TITLE
About rewriting TexturesVertex

### ISSUE THREAD

**Issue by JasonBoy1** [facebookresearch/pytorch3d#806]
Hi, @nikhilaravi . Sorry to bother. I read carefully in pytorch3d but still don't know how to choose the closest vertex. Could you point that to me?
Thanks a lot.
#798

**Comment by JasonBoy1** [comment]
Here is my experiment:
In the tutorial of rendering cow_mesh,
I printed the bary_coords and find the coords is full -1 as:
a tensor shape of (1, 1080, 1080, 1,3) , every element equals (-1, -1, -1).
I set the first vertices to black (0,0,0) and others to white.
This is the result.
![image](https://user-images.githubusercontent.com/33180378/129178348-abf17a23-0952-4982-b6b7-a4b0b86ea2c2.png)

when I changed the bary_coords to (1, 0, 0)
```
from pytorch3d.ops import interpolate_face_attributes
class TexturesCloset(TexturesVertex):
    def sample_textures(self, fragments, faces_packed=None) -> torch.Tensor:
        verts_features_packed = self.verts_features_packed()
        faces_verts_features = verts_features_packed[faces_packed]

        bary_coords = torch.FloatTensor([0, 0, 1]).view(1, 1, 1, 1, 3)
        bary_coords = bary_coords.repeat(1, 1080, 1080, 1, 1).to(self.device)
        texels = interpolate_face_attributes(
            fragments.pix_to_face, bary_coords, faces_verts_features
        )
        return texels
```
![image](https://user-images.githubusercontent.com/33180378/129178539-15fb0e2a-bf7c-4be6-ab61-152fdda01e5e.png)

to (0, 1, 0)
![image](https://user-images.githubusercontent.com/33180378/129178895-31f2e228-a6af-4067-aa38-2683babce5b3.png)


to (1, 1, 1)
![image](https://user-images.githubusercontent.com/33180378/129178801-f8328d35-678c-404e-85ab-13c0ef6710e8.png)


- It is weird that the sum of bary_coords does not equal 1.
- I can now set the bary_coords to (1, 0, 0) to make the triangle the color of its first vertex, but this does not satisfy my request: choose the closest vertex.

**Comment by nikhilaravi** [comment]
@JasonBoy1  you don't even need to have lighting - you can turn off the lighting completely if you don't need it.

Depending on which lighting method you choose it is applied by using the barycentric coordinate as well so just changing `sample_textures` to sample the closest vertex will not also update how lighting is applied. 

You can create your own custom shader that doesn't use lighting e.g

```
class CustomShaderNoLighting(nn.Module):
    def __init__(
        self,
        device: Device = "cpu",
        blend_params: Optional[BlendParams] = None,
    ) -> None:
        super().__init__()
        self.blend_params = blend_params if blend_params is not None else BlendParams()

    def forward(self, fragments: Fragments, meshes: Meshes, **kwargs) -> torch.Tensor:
        texels = meshes.sample_textures(fragments)
        blend_params = kwargs.get("blend_params", self.blend_params)
        images = hard_rgb_blend(texels, fragments, blend_params)
        return images
```

**Comment by JasonBoy1** [comment]
> @JasonBoy1 you don't even need to have lighting - you can turn off the lighting completely if you don't need it.
> 
> Depending on which lighting method you choose it is applied by using the barycentric coordinate as well so just changing `sample_textures` to sample the closest vertex will not also update how lighting is applied.
> 
> You can create your own custom shader that doesn't use lighting e.g
> 
> ```
> class CustomShaderNoLighting(nn.Module):
>     def __init__(
>         self,
>         device: Device = "cpu",
>         blend_params: Optional[BlendParams] = None,
>     ) -> None:
>         super().__init__()
>         self.blend_params = blend_params if blend_params is not None else BlendParams()
> 
>     def forward(self, fragments: Fragments, meshes: Meshes, **kwargs) -> torch.Tensor:
>         texels = meshes.sample_textures(fragments)
>         blend_params = kwargs.get("blend_params", self.blend_params)
>         images = hard_rgb_blend(texels, fragments, blend_params)
>         return images
> ```

What's the difference between this shader and this setting? Maybe I can close the lights by only using the ambient_lights.
```
ambient_light = {
    'ambient_color': [[1.0, 1.0, 1.0]],
    'diffuse_color': [[0, 0, 0]],
    'specular_color': [[0, 0, 0]],
    'location': [[0.0, 0.0, -3.0]],
}

material_params = {
    'ambient_color': [[1.0, 1.0, 1.0]],
    'diffuse_color': [[0.0, 0.0, 0.0]],
    'specular_color': [[0.0, 0.0, 0.0]],
    'shininess': 1.0,
}

lights = PointLights(device=self.device, **ambient_light)
materials = Materials(device=self.device, **material_params)

```

**Comment by bottler** [comment]
I would expect using full ambient white light to be equivalent to not using lighting.
