### ISSUE TITLE
Saving a mesh predicted from images (Tutorial : https://pytorch3d.org/tutorials/fit_textured_mesh)  with the predicted texture.

### ISSUE THREAD

**Issue by bhowmickarka** [facebookresearch/pytorch3d#810]
Hello everyone,
I have a very simple question. I am trying to save the predicted mesh from the tutorial along with the texture information.
From what I understood, the texture from the predicted mesh belongs to the TexturesVertex class. Hence, here I have the RGB information of each vertex. But, is there a way to save this information so that I can visualize the coloured mesh in blender.

I have tried to save using **IO().save_mesh()** and also **io.save_ply()** . In the **io.save_obj()** function, there is a verts_uvs(), faces_uvs() and texture_map() to save the texture but I am unable to understand how I can extract these informations from the predicted mesh. It will be really helpful if anyone would kindly guide me on how can I save the texture information of the predicted mesh.
Best regards,
Arka Bhowmick

**Comment by bottler** [comment]
Which tutorial? If your Meshes object before saving is `meshes`, what is `type(meshes.textures)`? Which version of PyTorch3D are you using?

If the textures are indeed TexturesVertex, and you are using the latest version 0.5.0, then `save_ply` should be saving the colours to the PLY file automatically, and blender should be able to load them.

**Comment by bhowmickarka** [comment]
Hello @bottler ,
Thank you so much for your reply.
**Link  of tutorial :** https://pytorch3d.org/tutorials/fit_textured_mesh
_**Please note** : I am not using the default cow.obj. I am using a different obj file,  a small hut._
**Pytorch3d version :** 0.4.0
**type(meshes.textures)** : pytorch3d.renderer.mesh.textures.TexturesVertex 

I understand your point about the version and I dug a little deeper into the source code and modified **save_ply()** function on my own in 0.4.0 version because I was unaware of the 0.5.0 version (sorry for that), and now I am able to store the vertex RGB value. But the resultant mesh with the vertex colours are not visually appealing because I think when we have only vertex RGB values, the face colour is applied using some kind of interpolation (I might be wrong). 

Hence, it will be helpful if you may kindly explain me that is it possible for me to save the predicted mesh as an **obj** file using **save_obj()** function and save the predicted texture as a texture map, because I saw that the **save_obj()** function has been extended in June to provide this texture saving functionality. 

I will wait patiently for your response.

Best regards,
Arka

**Comment by bottler** [comment]
If the data you want to save is a TexturesVertex, then yes, it must be interpolated to color the faces. I expect blender can do this, just as PyTorch3D can do this. Whether the transfer is done as a PLY or an OBJ won't matter.

When you say it is "not visually appealing" in blender, are you sure that the data *is* visually appealing in PyTorch3D - e.g. by checking renderer output or using plotly visualization. If not, then the problem is elsewhere. If yes, this is odd. Perhaps you can convert the data before export somehow, for example by running SubdivideMeshes on it many times.

**Comment by bhowmickarka** [comment]
Hello @bottler ,
Thank you for you reply. To be completely honest it is not very visually appealing in the rendered O/P as well, but when I am exporting it , it seems like it is getting much more fainter when I visualise it in blender. So, I will try your suggestion of mesh subdivision to see if it improves anything.

But, my real question is now, that can I somehow save this texture information as **Texture UV**? 
Or
If I want to **predict the texture of the mesh as  a Texture UV (and not as vertex RGB colours) that could be saved as an image file**, what steps should I follow, because with the official tutorial, the texture is always predicted as vertex RGB colours (TexturesVertex class).

I hope, I was able to explain myself. I will wait patiently for your reply,
best,
Arka

**Comment by bottler** [comment]
There is no perfect smooth general way to convert a TexturesVertex to a TexturesUV. I think you can preserve the colors on  the faces (i.e. ignoring blur_radius effects) if you do a conversion which takes each face to a separate isolated triangle.

To predict as a TexturesUV might be a significant modelling challenge: you need to design how your model is and how to train it. We can't help you here with that. But once you have that design, doing it with PyTorch3D is straightforward.

**Comment by bhowmickarka** [comment]
Hello @bottler,
Thank you for your help and consideration. 
Best,
Arka

**Comment by JasonBoy1** [comment]
@bottler hello, seems that pytorch3d cannot save mesh with TexturesVertex. Is that so?
