### ISSUE TITLE
Loading some .obj files as meshes uses an unusual amount of memory 

### ISSUE THREAD

**Issue by lahavlipson** [facebookresearch/pytorch3d#812]
I am loading two .obj files as meshes. One is the `cow.obj` from the Pytorch3D **fit_textured_mesh.ipynb** tutorial, and the second is my own (a mustard bottle). When I load each of the respective .obj files using `load_objs_as_meshes`, the cow mesh uses **13MB** of CUDA memory while the mustard bottle uses **247MB** of memory. However, the directory containing the mustard model and associated textures is much smaller than this:
```
lahav@desktop cow_and_mustard$ du -sh *
24M     cow_mesh
58M     006_mustard_bottle
```

I don't understand why one object takes up so much more memory than the other, or why the memory used by the mustard bottle is more than the disk usage for its source files. Could this be an issue with the files themselves or how I am loading them?

If it helps, when I load the mustard bottle using `load_textures=False`, the CUDA memory usage decreases from 247MB to 15MB. Although the texture files for the mustard bottle are not particularly big.

Here is a google drive download link for the two objects (29Mb) if it is at all helpful: https://drive.google.com/file/d/18CwH5c-4Vv2W1Qg9ZlQ3enqJXQSP4GHj/view?usp=sharing

The code I used to measure the CUDA memory usage is
```
from pytorch3d.io import load_objs_as_meshes
import torch

obj_path = "/home/lahav/Downloads/cow_and_mustard/006_mustard_bottle/textured.obj"
# obj_path = "/home/lahav/Downloads/cow_and_mustard/cow_mesh/cow.obj"
mesh = load_objs_as_meshes([obj_path], device=torch.device('cuda:0'), load_textures=True)
print(f"Memory usage: {torch.cuda.memory_allocated()/1e6}MB")
```

Please let me know if there is any additional info I can provide. Thanks for your help!

**EDIT:**
I suspect that part of the issue is that the texture values are stored using 32-bit precision rather than uint8.

**Comment by bottler** [comment]
Yes, the texture map data type is significant. Both texture maps are 8-bit png on disk. PyTorch3D stores them uncompressed in 32-bit floats. The cow texture map is 1024x1024. Inside PyTorch3D, it uses 12MB. The mustard texture map is 4096x4096, so it will use 192MB.

**Comment by lahavlipson** [comment]
Thanks for the explanation! It might be nice to have a function for downsampling UVTexture objects, if there isn't one already that I missed.
