### ISSUE TITLE
Blender camera to Pytorch3d camera

### ISSUE THREAD

**Issue by YaroslavShchekaturov** [facebookresearch/pytorch3d#817]
Hi! 

Thank you very much for the provided project. Curently I got stucked with importing meshes/cameras to pytorch3d from blender. Suppose I have a mesh and a camera in Blender.  I can get the camera parameters (intrinsic and extrinsic) from Blender.

![image](https://user-images.githubusercontent.com/22734034/130621898-4f074ddf-6594-469d-ba6b-c2d7c552e4d1.png)
![image](https://user-images.githubusercontent.com/22734034/130621954-f511026e-b23d-4954-ba42-5035d2b39a16.png)

After that, following the issue #294 I tried to render and image from the camera possition extracted from blender. I have no idea whats wrong, but the camera orientation is absolutly wrong. Am I right that openGL and Blender has the same coordinates?

example:
https://drive.google.com/file/d/1aRPe0mCPfJEangY_LK83i6dnrbrbKTYr/view?usp=sharing

**Comment by g-gaurav** [comment]
@YaroslavShchekaturov Hi can you please help me with this issue. I am facing the same problem.

Thanks in advance

**Comment by mshooter** [comment]
This might help https://github.com/facebookresearch/pytorch3d/issues/1105
