### ISSUE TITLE
Slice CamerasBase

### ISSUE THREAD

**Issue by jc211** [facebookresearch/pytorch3d#819]
## ❓ Questions on how to use PyTorch3D

Lets say I have a cameras object of type CamerasBase. It has a batch size of 10. I want to select only the third and sixth camera and make a new cameras object from those batches. Is there slicing operation I can do within the camera class?

**Comment by patricklabatut** [comment]
> Is there slicing operation I can do within the camera class?

It is possible slice index the properties of cameras, e.g. `cameras[0:3].R` (and then construct another cameras object from these slices if needed).
