### ISSUE TITLE
function "join_meshes_as_scene" produces wrong UV coordinates

### ISSUE THREAD

**Issue by WhoTHU** [facebookresearch/pytorch3d#826]
It seems that the function join_meshes_as_scene produces weird results.
I joined several single meshes as a whole mesh by running:
```
mesh = p3d.structures.join_meshes_as_scene(meshes)
```
where "meshes" is a list of meshes with textures. However, when I render "mesh", it comes to this
![image](https://user-images.githubusercontent.com/20219437/131683704-499c19ef-c680-4bdd-8002-429cda69c6f7.png)

But it is supposed to be
![image](https://user-images.githubusercontent.com/20219437/131683678-f865b8f5-79e7-4d64-b67e-a80bedc069ca.png)
which I got by  joining these meshes manually

I checked the map of the new mesh:
![image](https://user-images.githubusercontent.com/20219437/131682597-86490370-604e-4564-b487-63995328cced.png)

It seems that the black area on the body results from the black area on the texture map. The function may mistake the transformed UV coordinates.

**Comment by bottler** [comment]
This is really weird, and should be working if the original meshes are working. Can you perhaps paste the output of rendering the original meshes, and use the texturesuv_image_PIL function on each of the input meshes and also the output meshes and paste the pictures? That should make it easy to see what is going on.

**Comment by WhoTHU** [comment]
> This is really weird, and should be working if the original meshes are working. Can you perhaps paste the output of rendering the original meshes, and use the texturesuv_image_PIL function on each of the input meshes and also the output meshes and paste the pictures? That should make it easy to see what is going on.

Sure I put the texturesuv_images here. To simplify I joined 2 meshes, where the original  texturesuv_images are
![image](https://user-images.githubusercontent.com/20219437/131810465-4c879b6e-4b18-4134-8b26-069c279a89ec.png)
![image](https://user-images.githubusercontent.com/20219437/131810507-63246660-ba03-4c43-821f-ac28f0a81d47.png)
The joined texturesuv_image is 
![image](https://user-images.githubusercontent.com/20219437/131810579-1ff04515-0021-4553-bdd0-61e49af4212a.png)

**Comment by gkioxari** [comment]
@bottler has fixed the issue! @WhoTHU feel free to reopen if you have further questions!
