### ISSUE TITLE
link to "functions to render meshes and pointclouds in plotly" is broken

### ISSUE THREAD

**Issue by hopezh** [facebookresearch/pytorch3d#829]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## 🐛 Bugs / Unexpected behaviors

The link to "functions to render meshes and pointclouds in plotly." is broken as shown in PyTorch3D doc [visualization](https://pytorch3d.org/docs/visualization) 

NOTE: Please look at the existing list of Issues tagged with the label ['bug`](https://github.com/facebookresearch/pytorch3d/issues?q=label%3Abug). **Only open a new issue if this bug has not already been reported. If an issue already exists, please comment there instead.**.

## Instructions To Reproduce the Issue:

Please include the following (depending on what the issue is):

1. Any changes you made (`git diff`) or code you wrote
N/A

2. The exact command(s) you ran:
N/A

3. What you observed (including the full logs):
N/A

Please also simplify the steps as much as possible so they do not require additional resources to
   run, such as a private dataset.

**Comment by bottler** [comment]
I think this was fixed in Pull Request #818 and so the links will work when the next release happens.

**Comment by gkioxari** [comment]
Closing this!
