### ISSUE TITLE
Rendering results to white image

### ISSUE THREAD

**Issue by zhangy76** [facebookresearch/pytorch3d#837]
Hi, 

I define a render as below 

``
from pytorch3d.structures import Meshes
from pytorch3d.renderer import TexturesUV
from pytorch3d.renderer import (
    look_at_view_transform,
    DirectionalLights, 
    RasterizationSettings, 
    MeshRenderer, 
    SoftPhongShader,
    PerspectiveCameras,
    Textures
)

lights_coeff = torch.zeros([1,9]).type(torch.float32).to(device)
lights_coeff[:,:3] = 1 
lights = DirectionalLights(device=device, ambient_color=lights_coeff[:,:3], diffuse_color=lights_coeff[:,3:6], direction=lights_coeff[:,6:])
cameras = PerspectiveCameras(device=device, image_size=imagesize, principal_point=camera_center, focal_length=-focallength, T=pred_cam_t)

raster_settings = RasterizationSettings(
    image_size=IMS, 
    blur_radius=0.0, 
    faces_per_pixel=1, 
    )

renderer = MeshRenderer(
        rasterizer=MeshRasterizer(
            cameras=cameras, 
            raster_settings=raster_settings
            ),
        shader=SoftPhongShader(
            device=device, 
            cameras=cameras,
            lights=lights
            )
        )
verts_rgb = torch.ones_like(verts)
textures = Textures(verts_rgb=verts_rgb.to(device))
mesh = Meshes(verts, faces, textures)

predicted_rgb = renderer(mesh.clone())
``

When rendering a mesh model like `predicted_rgb = renderer(mesh.clone())`. The first 3D channel of predicted_rgb  is all white. While the last channel is 
<img width="433" alt="Screen Shot 2021-09-10 at 6 42 53 PM" src="https://user-images.githubusercontent.com/60193243/132925087-a2d372db-a8cf-4852-994c-b8fce1a219be.png">

I wonder what's the possible reason? Also, what does the last channel indicate?

**Comment by gkioxari** [comment]
If you wish to get help from us, you need to provide a compact code snippet with data so that we can reproduce your issue. Otherwise, we can't possibly do anything with the information you provide

**Comment by zhangy76** [comment]
Thanks for the reply. My data and rendering code are pretty simple. The 3D mesh model has about only 80 vertices and 130 faces. Only the rendered image has problem while the last channel of the output is correct as shown above.

**Comment by bottler** [comment]
We don't have enough of your code to know what is going on. Simple example: what is `mesh`? But the last two lines of your snippet look like you are defining a mesh texture to be all white, so if you use that it wouldn't be surprising if the output is all white.

**Comment by gkioxari** [comment]
@zhangy76 If we can't run your code to reproduce the issue, we can't help you.

**Comment by zhangy76** [comment]
I have updated my code. I may not be able to upload the mesh data. But the mesh is a simple, close, triangle mesh. verts is size of 1x84x3; faces is size of 1x164x3, which includes the vertices index of each face. Also, I can use the code to successfully render another mesh with its corresponding texture.

**Comment by bottler** [comment]
You are rendering a white mesh in full ambient light on a white background. So you should expect the image to be white. If that's not your intention, please explain what you want to do and what you expect the output to be.

**Comment by zhangy76** [comment]
Thanks. That's not what I plan to do. I just want to get a rendered image, where I can see it's shape no matter what the color is. May I ask how to change the background color?

**Comment by bottler** [comment]
For the background color to be blue, say, you could import `BlendParams` from `pytorch3d.renderer`, and change 
```
SoftPhongShader(
device=device,
cameras=cameras,
lights=lights
)
```
to
```
SoftPhongShader(
device=device,
cameras=cameras,
lights=lights,
blend_params=BlendParams(background_color=(0.0, 0.0, 1.0)),
)
```

Another simple way to get some visibility would be to randomly color the mesh: change
```
verts_rgb = torch.ones_like(verts)
```
to
```
verts_rgb = torch.rand_like(verts)
```

**Comment by zhangy76** [comment]
Both of these two ways work well. Close the issue and thanks!
