### ISSUE TITLE
different image sizes between 0.4.0 and 0.5.0 

### ISSUE THREAD

**Issue by vincentbonnetcg** [facebookresearch/pytorch3d#842]
Hello, 

This request is a follow-up to this previous question : https://github.com/facebookresearch/pytorch3d/issues/838
We are experimenting with the latest PyTorch from PyTorch3D 0.4.0 and experiencing some compatibilities issues. 

## 1.  Code

This code works for both version of PyTorch3D (0.4.0 and 0.5.0).  The aspect ratio is working, but there is a difference on the image size (See 2. Result)

```
from packaging import version
import os
import torch
import matplotlib.pyplot as plt

# Data structures and functions for rendering
import pytorch3d
from pytorch3d.io import load_objs_as_meshes
from pytorch3d.renderer import (
    BlendParams,
    look_at_view_transform,
    FoVPerspectiveCameras,
    PointLights,
    RasterizationSettings,
    MeshRenderer,
    MeshRasterizer,
    SoftPhongShader,
)
import urllib.request

# Download cow
urls = ['https://dl.fbaipublicfiles.com/pytorch3d/data/cow_mesh/cow.obj',
        'https://dl.fbaipublicfiles.com/pytorch3d/data/cow_mesh/cow.mtl',
        'https://dl.fbaipublicfiles.com/pytorch3d/data/cow_mesh/cow_texture.png']

names = ['cow.obj', 'cow.mtl', 'cow_texture.png']
for i in range(3):
    if os.path.exists(names[i]) == False:
        urllib.request.urlretrieve(urls[i], names[i])

# Create device
device = torch.device("cuda:0")

# Load mesh
mesh = load_objs_as_meshes(["cow.obj"], device=device)


# Function to render with different image size
def render(image_height, image_width, device, mesh):
    # Compute aspect ratio based on pyTorch
    aspect_ratio = 1.0
    if version.parse(pytorch3d.__version__) < version.parse("0.5.0"):
        aspect_ratio = image_width / image_height

    # Initialize camera
    R, T = look_at_view_transform(2.7, 0, 180)
    cameras = FoVPerspectiveCameras(device=device, R=R, T=T, aspect_ratio=aspect_ratio)

    # Initialize render
    raster_settings = RasterizationSettings(
        image_size=(image_height, image_width),
        blur_radius=0.0,
        faces_per_pixel=1,
    )
    lights = PointLights(device=device, location=[[0.0, 0.0, -3.0]])
    rasterizer = MeshRasterizer(
        cameras=cameras,
        raster_settings=raster_settings
    )
    blend_params = BlendParams(sigma=1e-4, gamma=1e-4, background_color=(0.0, 0.0, 0.0))
    shader = SoftPhongShader(
        device=device,
        cameras=cameras,
        blend_params=blend_params,
        lights=lights)

    renderer = MeshRenderer(
        rasterizer, shader)

    return renderer(mesh)[0, ..., :3].cpu().numpy()

# Render image
fig, ax = plt.subplots(1, 3, figsize=(8,8), sharex='all')
ax[0].imshow(render(512, 512, device, mesh))
ax[0].set_title('512x512')
ax[1].imshow(render(512, 300, device, mesh))
ax[1].set_title('512x300')
ax[2].imshow(render(300, 512, device, mesh))
ax[2].set_title('300x512')
plt.show()
```
### 2.1  Result PyTorch_0.4.0

After running the above code with PyTorch_0.4.0
![torch3d_040](https://user-images.githubusercontent.com/13979887/133362127-a2a8200d-81b8-4a2e-b4aa-e8aeb380c014.png)

### 2.2  Result PyTorch_0.5.0

After running the above code with PyTorch_0.5.0
![torch3d_050](https://user-images.githubusercontent.com/13979887/133362131-532bb1e3-9d3d-4016-8c17-7c6f14305839.png)

## 3. Questions

Our resolution is based on 512x300 (tall matrix , height > width) , as you can see, the render changes drastically between the two versions - unlucky :)
- Is the result on PyTorch 0.5.0 expected?  
- If the result is expected what would be the best approach to get a similar result to PyTorch 0.4.0 ? 

Thanks, 
Vincent

**Comment by gkioxari** [comment]
Hi @vincentbonnetcg! Now is the proper time to refer to the camera change in 0.5.0 :) As you can read in the Discussion https://github.com/facebookresearch/pytorch3d/discussions/783, we have changed how the image size is defined from 0.4.0 to make it compatible with rendering (See B2, point 2).

**Comment by vincentbonnetcg** [comment]
the FoVPerspectiveCameras doesn't have a image size arguments but found a way around my issue. 
Thanks again @gkioxari ,the discussion on https://github.com/facebookresearch/pytorch3d/discussions/783 is very useful.

**Comment by gkioxari** [comment]
@vincentbonnetcg What was the solution after all? It might be helpful for others if they read this!

**Comment by vincentbonnetcg** [comment]
@gkioxari ,  It is a pretty lame solution but works :) On PyTorch 0.4.0, our cameras were tuned to render square/tall images. Instead of trying to reproduce the same outcome with PyTorch 0.5.0 for a rectangular image, I'll just render it in a square image and crop it to fit.
