### ISSUE TITLE
ImportError while importing 'SilhouetteShader' from 'pytorch3d.renderer' in the Camera position optimisation example

### ISSUE THREAD

**Issue by raincrash** [facebookresearch/pytorch3d#85]
While importing SilhouetteShader (or PhongShader), the 'Camera Position Optimization' example fails with,

```
ImportError: cannot import name 'SilhouetteShader' from 'pytorch3d.renderer'
``` 
This is probably because the API is now modified to `SoftSilhouetteShader` (and `Soft|Hard PhongShader`). If this is the issue, I can send a PR fixing the example.

**Comment by raincrash** [comment]
Closing this because the commit https://github.com/facebookresearch/pytorch3d/commit/f0dc65110aa9687e83712950f6d47b280761f078 already exists.

**Comment by nikhilaravi** [comment]
@raincrash thanks for pointing this out! I will update the website!
