### ISSUE TITLE
Different pix_to_face values for identical rasterizer input

### ISSUE THREAD

**Issue by lahavlipson** [facebookresearch/pytorch3d#850]
In the **render_textured_meshes.ipynb** Colab, I found that if I rasterize two copies of the mesh using duplicated cameras, the resulting fragments have the same zbuf (as expected) but _different_ pix_to_face values. 

To reproduce the issue, I insert the following code cell just below the code cell for the **Create a renderer** section:

```
double_R = R.repeat(2,1,1)
double_T = T.repeat(2,1)
double_cameras = FoVPerspectiveCameras(device=device, R=double_R, T=double_T)
double_mesh = mesh.extend(2)

rasterizer=MeshRasterizer(
    cameras=double_cameras, 
    raster_settings=RasterizationSettings(
        image_size=512, 
        blur_radius=0.0, 
        faces_per_pixel=1, 
    )
)

fragments = rasterizer(double_mesh)
a, b = fragments.pix_to_face.squeeze(-1)
img = (a == b).cpu().numpy()
plt.imshow(img)
plt.show()
```
![image](https://user-images.githubusercontent.com/16674837/133896114-7f0d54a6-7afe-4eab-abcf-a7ff5a20cc41.png)

I expected `a` and `b` to have the same values everywhere on the image. However, they have different values everywhere on the cow. Is this expected behavior?

Please let me know if there is additional information I can provide, thank you.

**Comment by bottler** [comment]
The indices (i.e. nonnegative values) in `pix_to_face` are indices in the packed representation of the faces, i.e. the concatenation of the face array for all batch elements. The values in `b` will be higher than the values in `a` by the number of faces in the single mesh.

**Comment by lahavlipson** [comment]
Oh, I assumed `mesh.extend(2)` aliased the mesh properties instead of copied them. That clears it up, thank you!
