### ISSUE TITLE
How to convert between TexturesUV and TexturesVertex

### ISSUE THREAD

**Issue by univ-esuty** [facebookresearch/pytorch3d#854]
## ❓ Questions about how to convert TexturesUV into TexturesVertex
According to pytorch3d documents, Pytorch3d mainly supports 3 types of textures formats `TexturesUV, TexturesVertex, TexturesAtlas`.
I want to convert TexturesUV class into TexturesVertex class.  
I have 3 parameters `maps, faces_uvs, verts_uvs`  and I can construct TexturesUV and render with it.  But, I want to calculate  `verts_features`  in TexturesVertex class from these 3 parameters. 　　
No problem if the resolution of textures decreases however, the rendering results with TexturesUV and TexturesVertex must be almost the same

```python
maps, faces_uvs, verts_uvs = np.load('maps.npy'), np.load('faces_uvs.npy'), np.load('verts_uvs.npy')
maps, faces_uvs, verts_uvs = convert_to_pytorchTensor(maps, faces_uvs, verts_uvs)
textures_uv = TexturesUV(maps=maps, faces_uvs=faces_uvs, verts_uvs=verts_uvs)

## convert 
textures_vertex = convert_to_textureVertex(textures_uv)  ## What I want to do.

print(textures_vertex.verts_features_padded())
```

**Comment by bottler** [comment]
This is in general impossible. One reason is as follows. TexturesVertex has only one color per vertex. TexturesUV doesn't have one color per vertex, but rather one color per corner of a face, and a single vertex could appear in multiple faces, and the corresponding element of faces_uvs could be different. You might, however, know that this doesn't happen in your mesh or doesn't matter for your application.

We are going to need the `faces` from the mesh to do this conversion. Could you try something like this
```
def convert_to_textureVertex(textures_uv: TexturesUV, meshes:Meshes) -> TexturesVertex:
    verts_colors_packed = torch.zeros_like(meshes.verts_packed())
    verts_colors_packed[meshes.faces_packed()] = textures_uv.faces_verts_textures_packed()  # (*)
    return TexturesVertex(packed_to_list(verts_colors_packed, meshes.num_verts_per_mesh()))
```
If two faces contain the same vert, the answer for that vert is not clear; this is mirrored in nondeterminism in the line marked `(*)`.

**Comment by univ-esuty** [comment]
Thank you for the quick reply and attaching sample code to solve the problem.  
I tested it with 3d cow data. it seems to be working very well.  
I don't know if it will work and return my expected results in all my situations, but I think it will be useful.
  
Thank you!

test results.
![example](https://user-images.githubusercontent.com/82131731/134525837-46fefb6b-46ac-4b1c-af79-50b0117487a2.png)

test code. 
```python
DATA_DIR = "./data"
obj_filename = os.path.join(DATA_DIR, "cow_mesh/cow.obj")
mesh = load_objs_as_meshes([obj_filename])
mesh_dash = load_objs_as_meshes([obj_filename])

## TextureUV
textures_uv_rgb = torch.rand(1, 64, 64, 3) #test maps parameters
mesh.textures._maps_padded = textures_uv_rgb

## TexturesUV -> TexturesVertex
textures_vertex = convert_to_textureVertex(mesh.textures, mesh)
mesh_dash.textures = textures_vertex

## rendering
meshes = mesh.extend(num_views)
images_a = renderer(meshes)
image_grid(images_a.cpu().detach().numpy(), rows=1, cols=6, rgb=True)

meshes_dash = mesh_dash.extend(num_views)
images_b = renderer(meshes_dash)
image_grid(images_b.cpu().detach().numpy(), rows=1, cols=6, rgb=True)

diff = np.abs( (images_a - images_b).numpy() )
image_grid(diff, rows=1, cols=6, rgb=True)
```

**Comment by DYamIK** [comment]
> This is in general impossible. One reason is as follows. TexturesVertex has only one color per vertex. TexturesUV doesn't have one color per vertex, but rather one color per corner of a face, and a single vertex could appear in multiple faces, and the corresponding element of faces_uvs could be different. You might, however, know that this doesn't happen in your mesh or doesn't matter for your application.
> 
> We are going to need the `faces` from the mesh to do this conversion. Could you try something like this
> 
> ```
> def convert_to_textureVertex(textures_uv: TexturesUV, meshes:Meshes) -> TexturesVertex:
>     verts_colors_packed = torch.zeros_like(meshes.verts_packed())
>     verts_colors_packed[meshes.faces_packed()] = textures_uv.faces_verts_textures_packed()  # (*)
>     return TexturesVertex(packed_to_list(verts_colors_packed, meshes.num_verts_per_mesh()))
> ```
> 
> If two faces contain the same vert, the answer for that vert is not clear; this is mirrored in nondeterminism in the line marked `(*)`.

A question, is this convert function differentiable?❓

**Comment by bottler** [comment]
Yes
