### ISSUE TITLE
Render multiple meshes in one scene

### ISSUE THREAD

**Issue by zhangy76** [facebookresearch/pytorch3d#855]
Hi,

I wonder if I can render multiple meshes in one scene? Basically, I have the multiple meshes. I define one renderer and generate one image.

Thanks,

**Comment by nikhilaravi** [comment]
You can join multiple meshes into one mesh and render it e.g. using the `join_meshes_as_scene` function. 

https://github.com/facebookresearch/pytorch3d/blob/860b742a02e62ec85f48929268349916ca4ce8a5/pytorch3d/structures/meshes.py#L1608-L1623

**Comment by zhangy76** [comment]
Thanks! I have several other questions, (1) Is that possible to render with different texture type? (2) I would like to obtain an rendered image with some color information but I do not have its texture information. I wonder if there is any general texture color? (Currently I can only manualy define an all ones texture map) (3) What does the last chanel indicate in a rendered rgb image?
