### ISSUE TITLE
FoVPerspectiveCameras K input not working as intended

### ISSUE THREAD

**Issue by yaadhavraajagility** [facebookresearch/pytorch3d#856]
I have a function that looks as follows, where i generate a projection matrix  below from the standard camera model with fx, fy, cx, cy. However, the rendering appears to be incorrect (nothing is shown). However, if i set the fov manually then i am able to see the object (albeit with some cx/cy offset)
```
    # Camera Matrix
    K = torch.tensor([
        [fx, 0, cx, 0],
        [0, fy, cy, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]
    ]).unsqueeze(0).to(self.device)
    self.cameras = FoVPerspectiveCameras(device=K.device, K=K)
```

How exactly do I pass the camera matrix ?

**Comment by nikhilaravi** [comment]
@yaadhavraajagility you can use a different camera class such as `PerspectiveCamera`.  See this note for more details about the cameras: https://github.com/facebookresearch/pytorch3d/blob/main/docs/notes/cameras.md.

**Comment by gkioxari** [comment]
I suspect that the camera that you set is not properly defined under PyTorch3D conventions. Could you please provide a compact code snippet with the data so that we can reproduce your error? Otherwise, we can't really help you.
