### ISSUE TITLE
How to render a mesh using Extrinsics and intrinsic ?

### ISSUE THREAD

**Issue by lith0613** [facebookresearch/pytorch3d#859]
I tried to use the Extrinsics and intrinsic to render the 3D point,  I project the point manually and use pytorch3d perspective cameras but get different result. 
the result 1 is projected manually:
![image](https://user-images.githubusercontent.com/31385806/134845806-cefd6768-e765-4d32-bc28-d25baf3c3177.png)

and the result 2 is projected using pytorch3d pespective camera :
![image](https://user-images.githubusercontent.com/31385806/134845857-ccebcd5a-55bb-44f9-aaef-7cac75d51032.png)

the obj file used in this script is as follows:
https://drive.google.com/file/d/1avjIZoZfDYpCSkoaLBPDMkk1vi_nN-CO/view?usp=sharing

the test script is as follows:
```
import argparse

import numpy as np
import torch

import pytorch3d
from pytorch3d.renderer import (
    PerspectiveCameras, FoVPerspectiveCameras,
    RasterizationSettings, BlendParams,
    MeshRenderer, MeshRasterizer, HardPhongShader, SoftPhongShader, Textures, Materials, PointLights
)


from pytorch3d.io import load_obj
import matplotlib.pyplot as plt


def main():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")



    fx, fy, cx, cy = (1845.6875, 1845.6875, 185.58625, 267.13125)
    w, h = (376, 514)
    Extrinsics_R = np.array([[ 1.00000e+00,  7.50026e-05, -5.99776e-04],
       [-7.51583e-05,  1.00000e+00, -2.59566e-04],
       [ 5.99757e-04,  2.59611e-04,  1.00000e+00]], dtype=np.float32)
    Extrinsics_T = np.array([[ 0.00577083, -0.0151595 , -0.0333987 ]], dtype=np.float32)


    verts, faces, aux = load_obj('test.obj', load_textures=False)
    verts = verts.to(device)

    ## Create Camera, R,T,K
    R = torch.from_numpy(Extrinsics_R).float().to(device).unsqueeze(0)
    T = torch.from_numpy(Extrinsics_T).float().to(device)

    #use camera projecttion to test
    intrinsic = torch.tensor([[fx, 0, cx],
                           [0, fy, cy],
                           [0, 0, 1]]).to(device)
    X1 = R[0].mm(verts.transpose(1, 0)).transpose(1, 0) + T
    X2 = intrinsic.mm(X1.transpose(1, 0)).transpose(1, 0)
    X2[:, 0] = X2[:, 0] / X2[:, 2]
    X2[:, 1] = X2[:, 1] / X2[:, 2]

   #show result 1 manually projection
    fake = np.zeros((h, w, 3)).astype(np.float32)
    for u,v in X2.cpu().numpy()[:, :2]:
        if v<h and u<w:
            fake[int(v), int(u), :] = (1, 0, 0)
    plt.imshow(fake)
    plt.show()


    # define pytorch3d cameras
    cameras = PerspectiveCameras(focal_length= torch.tensor([fx,fy]).unsqueeze(0),
                                 principal_point = torch.tensor([cx,cy]).unsqueeze(0),
                                 device=device,
                                 in_ndc=False,
                                 R=R, T=T,
                                 image_size=torch.tensor([h,w]).unsqueeze(0))

    #flip x,y to -x, -y
    verts_pt3d = verts.clone()
    verts_pt3d[:, 0:2] = verts_pt3d[:, 0:2]*(-1)


    # X2 = cameras.get_full_projection_transform().transform_points(verts)[:,:2].detach().cpu().numpy()
    X2 = cameras.transform_points_screen(verts_pt3d)[:,:2].cpu().numpy()


    #show result 2 using pytorch3d perspective camera
    fake = np.zeros((h, w, 3)).astype(np.float32)
    for u,v in X2[:, :2]:
        if v<h and u<w:
            fake[int(v), int(u), :] = (1, 0, 0)
    plt.imshow(fake)
    plt.show()



if __name__ == "__main__":
    main()

```

I just want to get the same projection result, that is to say, the manually projection point should be same as the pytorch3d pespective camera projection result .

**Comment by pengwangucla** [comment]
> I tried to use the Extrinsics and intrinsic to render the 3D point, I project the point manually and use pytorch3d perspective cameras but get different result. the result 1 is projected manually: ![image](https://user-images.githubusercontent.com/31385806/134845806-cefd6768-e765-4d32-bc28-d25baf3c3177.png)
> 
> and the result 2 is projected using pytorch3d pespective camera : ![image](https://user-images.githubusercontent.com/31385806/134845857-ccebcd5a-55bb-44f9-aaef-7cac75d51032.png)
> 
> the obj file used in this script is as follows: https://drive.google.com/file/d/1avjIZoZfDYpCSkoaLBPDMkk1vi_nN-CO/view?usp=sharing
> 
> the test script is as follows:
> 
> ```
> import argparse
> 
> import numpy as np
> import torch
> 
> import pytorch3d
> from pytorch3d.renderer import (
>     PerspectiveCameras, FoVPerspectiveCameras,
>     RasterizationSettings, BlendParams,
>     MeshRenderer, MeshRasterizer, HardPhongShader, SoftPhongShader, Textures, Materials, PointLights
> )
> 
> 
> from pytorch3d.io import load_obj
> import matplotlib.pyplot as plt
> 
> 
> def main():
>     device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
> 
> 
> 
>     fx, fy, cx, cy = (1845.6875, 1845.6875, 185.58625, 267.13125)
>     w, h = (376, 514)
>     Extrinsics_R = np.array([[ 1.00000e+00,  7.50026e-05, -5.99776e-04],
>        [-7.51583e-05,  1.00000e+00, -2.59566e-04],
>        [ 5.99757e-04,  2.59611e-04,  1.00000e+00]], dtype=np.float32)
>     Extrinsics_T = np.array([[ 0.00577083, -0.0151595 , -0.0333987 ]], dtype=np.float32)
> 
> 
>     verts, faces, aux = load_obj('test.obj', load_textures=False)
>     verts = verts.to(device)
> 
>     ## Create Camera, R,T,K
>     R = torch.from_numpy(Extrinsics_R).float().to(device).unsqueeze(0)
>     T = torch.from_numpy(Extrinsics_T).float().to(device)
> 
>     #use camera projecttion to test
>     intrinsic = torch.tensor([[fx, 0, cx],
>                            [0, fy, cy],
>                            [0, 0, 1]]).to(device)
>     X1 = R[0].mm(verts.transpose(1, 0)).transpose(1, 0) + T
>     X2 = intrinsic.mm(X1.transpose(1, 0)).transpose(1, 0)
>     X2[:, 0] = X2[:, 0] / X2[:, 2]
>     X2[:, 1] = X2[:, 1] / X2[:, 2]
> 
>    #show result 1 manually projection
>     fake = np.zeros((h, w, 3)).astype(np.float32)
>     for u,v in X2.cpu().numpy()[:, :2]:
>         if v<h and u<w:
>             fake[int(v), int(u), :] = (1, 0, 0)
>     plt.imshow(fake)
>     plt.show()
> 
> 
>     # define pytorch3d cameras
>     cameras = PerspectiveCameras(focal_length= torch.tensor([fx,fy]).unsqueeze(0),
>                                  principal_point = torch.tensor([cx,cy]).unsqueeze(0),
>                                  device=device,
>                                  in_ndc=False,
>                                  R=R, T=T,
>                                  image_size=torch.tensor([h,w]).unsqueeze(0))
> 
>     #flip x,y to -x, -y
>     verts_pt3d = verts.clone()
>     verts_pt3d[:, 0:2] = verts_pt3d[:, 0:2]*(-1)
> 
> 
>     # X2 = cameras.get_full_projection_transform().transform_points(verts)[:,:2].detach().cpu().numpy()
>     X2 = cameras.transform_points_screen(verts_pt3d)[:,:2].cpu().numpy()
> 
> 
>     #show result 2 using pytorch3d perspective camera
>     fake = np.zeros((h, w, 3)).astype(np.float32)
>     for u,v in X2[:, :2]:
>         if v<h and u<w:
>             fake[int(v), int(u), :] = (1, 0, 0)
>     plt.imshow(fake)
>     plt.show()
> 
> 
> 
> if __name__ == "__main__":
>     main()
> ```
> 
> I just want to get the same projection result, that is to say, the manually projection point should be same as the pytorch3d pespective camera projection result .

looks the two do produce difference results.  Have you solved the issue ?

**Comment by pengwangucla** [comment]
@lith0613  looks the two do have different output. Have you solved the issue ?
