### ISSUE TITLE
Point Rasterizer

### ISSUE THREAD

**Issue by grgkopanas** [facebookresearch/pytorch3d#86]
Hi,

I am looking for a point rasterizer instead of a mesh and I didn't help to notice that the implementation for the Cuda/C++ side is uploaded under csrc/rasterize_points folder, and as far as I managed to find there is no related python implementation with that. Is the implementation somewhere and/or do you plan to push it soon in the repository?

Thanks,
George

**Comment by nikhilaravi** [comment]
@grgkopanas we will be releasing the python wrapper for this implementation along with more complete point cloud rendering support around the end of March.
