### ISSUE TITLE
How to set nfar value for  PerspectiveCameras? 

### ISSUE THREAD

**Issue by huameichen0523** [facebookresearch/pytorch3d#861]
It appears to me that if the distance between object and camera is greater than 100, nothing is rendered. I guess there is a default nfar values associated with PerspectiveCameras. However, I could not find it in the source code. Is there a way to specify the nfar value ? Or there is a different way of handling this issue for PerspectiveCameras? Thank you.

**Comment by bottler** [comment]
If you are using `SoftGouraudShader` or `SoftPhongShader`, then the shader needs a maximum depth, and this defaults to 100 whenever you are using a camera type (like PerspectiveCameras) which doesn't have its own `zfar`. You can set your own value by supplying e.g. `zfar=1000.0` when you call the renderer.

**Comment by huameichen0523** [comment]
Thank you very much!

**Comment by bottler** [comment]
I'll close this for now - you can reopen if you need to follow up.

**Comment by huameichen0523** [comment]
It solved the problem.
Thank you very much.



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
