### ISSUE TITLE
backward error,when use euler_angles_to_matrix

### ISSUE THREAD

**Issue by zhangzscn** [facebookresearch/pytorch3d#864]
this is my code:

def forward(self):
    return PerspectiveCameras(focal_length=self.focal_length_list,
                              principal_point=self.principal_point_list,
                              R=euler_angles_to_matrix(self.rvec_euler_angle_list, "XYZ"),
                              T=self.tvec_list,
                              image_size=self.image_size_list,
                              in_ndc=True)

this is the error,after run the backward function:

[W python_anomaly_mode.cpp:85] Warning: Error detected in BmmBackward0. No forward pass information available. Enable detect anomaly during forward pass for more information. (function _print_stack)
Traceback (most recent call last):
  File "/home/zhangzs/代码/HumanAi/opt.py", line 96, in <module>
    loss.backward()
  File "/home/zhangzs/snap/anaconda3/envs/HumanAi/lib/python3.9/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/zhangzs/snap/anaconda3/envs/HumanAi/lib/python3.9/site-packages/torch/autograd/__init__.py", line 147, in backward
    Variable._execution_engine.run_backward(
RuntimeError: Trying to backward through the graph a second time (or directly access saved variables after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved variables after calling backward.

if remove the euler_angles_to_matrix,everything is fine.

def forward(self):
    return PerspectiveCameras(focal_length=self.focal_length_list,
                              principal_point=self.principal_point_list,
                              R=self.rvec_list,
                              T=self.tvec_list,
                              image_size=self.image_size_list,
                              in_ndc=True)

**Comment by bottler** [comment]
The problem here will have something to do with something else going on in your code, and is not a strangeness in pytorch3d. Best to think carefully about all the gradient calculations in your code. E.g. there's been a backwards or an optimizer step which has affected the current `self.rvec_euler_angle_list`, and you just need to add `retain_grad=True` to that or maybe the calculation which makes `self.rvec_euler_angle_list` is meant to be inside your training loop but it has been placed outside. Maybe paste more of your program?

**Comment by zhangzscn** [comment]
@bottler this is the camera parameter

`import torch
import torch.nn as nn
from pytorch3d.common import Device
from pytorch3d.renderer import PerspectiveCameras
from pytorch3d.transforms import matrix_to_euler_angles, euler_angles_to_matrix
from pytorch3d.utils import cameras_from_opencv_projection

from human.data.camera_data import CameraData


class CameraParameter(nn.Module):
    def __init__(self,
                 camera_data: CameraData,
                 device: Device = "cpu",
                 dtype=torch.float32):
        super(CameraParameter, self).__init__()

        camera_matrix_list = torch.from_numpy(camera_data.camera_matrix_list).to(device)
        rvec_list = torch.from_numpy(camera_data.rvec_list).to(device)
        tvec_list = torch.from_numpy(camera_data.tvec_list).to(device)
        image_size_list = torch.from_numpy(camera_data.image_size_list).to(device)

        pytorch_cameras = cameras_from_opencv_projection(rvec_list, tvec_list, camera_matrix_list, image_size_list)

        self.register_buffer("focal_length_list", pytorch_cameras.focal_length)
        self.register_buffer("principal_point_list", pytorch_cameras.principal_point)
        self.register_parameter("rvec_euler_angle_list", nn.Parameter(matrix_to_euler_angles(pytorch_cameras.R, "XYZ")))
        self.register_parameter("tvec_list", nn.Parameter(pytorch_cameras.T))
        self.to(device, dtype)
        self.register_buffer("image_size_list", image_size_list)
        self.register_buffer("rvec_list", pytorch_cameras.R)
        self.to(device)

    def forward(self):
        return PerspectiveCameras(focal_length=self.focal_length_list,
                                  principal_point=self.principal_point_list,
                                  R=euler_angles_to_matrix(self.rvec_euler_angle_list, "XYZ"),
                                  T=self.tvec_list,
                                  image_size=self.image_size_list,
                                  in_ndc=True)
`
this is the smpl parameter

`import torch
import torch.nn as nn
from pytorch3d.common import Device

from human.data.smpl_data import SmplData


class SmplParameter(nn.Module):
    def __init__(self,
                 smpl_data: SmplData,
                 device: Device = "cpu",
                 dtype=torch.float32):
        super(SmplParameter, self).__init__()

        self.batch_size = smpl_data.pose_list.shape[0]

        self.register_parameter("pose_part_list", torch.nn.Parameter(torch.from_numpy(smpl_data.pose_list[..., 3:])))
        self.register_parameter("shape", torch.nn.Parameter(torch.from_numpy(smpl_data.shape_list.mean(0))))
        self.register_buffer("pose_zero_list", torch.zeros([self.batch_size, 3]))
        self.register_buffer("tran_list", torch.zeros([self.batch_size, 3]))
        self.to(device, dtype)

    def forward(self):
        pose_list = torch.cat([self.pose_zero_list, self.pose_part_list], 1)
        shape_list = self.shape.repeat(self.batch_size, 1)
        return pose_list, shape_list, self.tran_list
`
this is the main optmize code:

`optimizer = torch.optim.AdamW([{'params': smpl_parameter.get_parameter("pose_part_list")},
                               {'params': smpl_parameter.get_parameter("shape")},
                               # {'params': smpl_parameter.get_parameter("tran_list")},
                               {'params': camera_parameter.get_parameter("rvec_euler_angle_list")},
                               {'params': camera_parameter.get_parameter("tvec_list")}
                               ],
                              lr=0.001, weight_decay=0.0)

n = 200
loop = tqdm(range(n))

for i in loop:
    optimizer.zero_grad()
    pose_list, shape_list, tran_list = smpl_parameter()
    verts, faces, joint3d = smpl(pose_list, shape_list, tran_list, True)

    cameras = camera_parameter()
    diff_render = DiffRenderer(cameras=cameras,
                               device=device)

    silhouette, zbuf = diff_render(meshes=Meshes(verts=verts, faces=faces))
`

**Comment by zhangzscn** [comment]
`ddddd`

**Comment by bottler** [comment]
We can't see the rest of the loop. You only backwards and step the optimizer once in the loop, right?
I can't spot anything obviously wrong here. If you remove euler_angles_to_matrix then there's no calculation to backprop through in camera_parameter, which means  nothing would go wrong if you reused `cameras`, unlike now.

**Comment by zhangzscn** [comment]
I find the problem.I have set the camera to the ReProjecter class before the loop,but without updata the camera in the loop when use the ReProjecter。

<details>
<summary>code</summary>

```python
reprojecter = ReProjecter(camera=cameras,
                          device=device)

for i in loop:
    optimizer.zero_grad()
    pose_list, shape_list, tran_list = smpl_parameter()
    verts, faces, joint3d = smpl(pose_list, shape_list, tran_list, True)

    cameras = camera_parameter()

    diff_render = DiffRenderer(cameras=cameras,
                               device=device)

    silhouette, zbuf = diff_render(meshes=Meshes(verts=verts, faces=faces))
    joint2d = reprojecter(verts=joint3d)
    joint2d = joint2d[..., :2]
```
</details>
