### ISSUE TITLE
Successfully uninstall pytorch3d for Linux, while got "RuntimeError: Not compiled with GPU support"

### ISSUE THREAD

**Issue by catherine-qian** [facebookresearch/pytorch3d#866]
## ❓ Questions on how to use PyTorch3D

I successfully install pytorch3d (on slurm cluster with linux) while got the following error when run an experiment:

  File "data_util/face_tracking/face_tracker.py", line 218, in <module>
    sel_light.to(device_render))
  File "/home/qian/anaconda3/envs/adnerf/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/qian/Documents/AD-NeRF/data_util/face_tracking/render_3dmm.py", line 189, in forward
    rendered_img = self.renderer(mesh)
  File "/home/qian/anaconda3/envs/adnerf/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/qian/anaconda3/envs/adnerf/lib/python3.7/site-packages/pytorch3d/renderer/mesh/renderer.py", line 59, in forward
    fragments = self.rasterizer(meshes_world, **kwargs)
  File "/home/qian/anaconda3/envs/adnerf/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/qian/anaconda3/envs/adnerf/lib/python3.7/site-packages/pytorch3d/renderer/mesh/rasterizer.py", line 203, in forward
    cull_to_frustum=raster_settings.cull_to_frustum,
  File "/home/qian/anaconda3/envs/adnerf/lib/python3.7/site-packages/pytorch3d/renderer/mesh/rasterize_meshes.py", line 246, in rasterize_meshes
    cull_backfaces,
  File "/home/qian/anaconda3/envs/adnerf/lib/python3.7/site-packages/pytorch3d/renderer/mesh/rasterize_meshes.py", line 320, in forward
    cull_backfaces,
RuntimeError: Not compiled with GPU support

============================== 
conda info
     active environment : adnerf
    active env location : /home/qian/anaconda3/envs/adnerf
            shell level : 2
       user config file : /home/qian/.condarc
 populated config files : 
          conda version : 4.10.1
    conda-build version : 3.21.4
         python version : 3.7.9.final.0
       virtual packages : __cuda=11.2=0
                          __linux=4.15.0=0
                          __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/qian/anaconda3  (writable)
      conda av data dir : /home/qian/anaconda3/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/qian/anaconda3/pkgs
                          /home/qian/.conda/pkgs
       envs directories : /home/qian/anaconda3/envs
                          /home/qian/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.7.9 Linux/4.15.0-158-generic ubuntu/18.04.5 glibc/2.27
                UID:GID : 1018:1018
             netrc file : None
           offline mode : False

================= conda list
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    conda-forge
_openmp_mutex             4.5                       1_gnu  
absl-py                   0.13.0                   pypi_0    pypi
astor                     0.8.1                    pypi_0    pypi
autopep8                  1.5.7              pyhd3eb1b0_0  
blas                      1.0                         mkl    conda-forge
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2021.5.25            h06a4308_1  
cached-property           1.5.2                    pypi_0    pypi
cairo                     1.14.12              h8948797_3  
certifi                   2021.5.30        py37h06a4308_0  
chardet                   4.0.0                    pypi_0    pypi
configargparse            1.4                pyhd3eb1b0_0  
cudatoolkit               11.1.1               h6406543_8    conda-forge
cycler                    0.10.0                   py37_0  
dbus                      1.13.18              hb2f20db_0  
decorator                 4.4.2                    pypi_0    pypi
expat                     2.4.1                h2531618_2  
face-alignment            1.3.4                    pypi_0    pypi
ffmpeg                    4.0                  hcdf2ecd_0  
fontconfig                2.13.1               h6c09931_0  
freeglut                  3.0.0                hf484d3e_5  
freetype                  2.10.4               h5ab3b9f_0  
fvcore                    0.1.5.post20210617          pypi_0    pypi
gast                      0.2.2                    pypi_0    pypi
glib                      2.63.1               h5a9c865_0  
google-pasta              0.2.0                    pypi_0    pypi
graphite2                 1.3.14               h23475e2_0  
grpcio                    1.38.0                   pypi_0    pypi
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
h5py                      3.2.1                    pypi_0    pypi
harfbuzz                  1.8.8                hffaf4a1_0  
hdf5                      1.10.2               hba1933b_1  
icu                       58.2                 he6710b0_3  
idna                      2.10                     pypi_0    pypi
imageio                   2.9.0              pyhd3eb1b0_0  
importlib-metadata        4.5.0                    pypi_0    pypi
intel-openmp              2021.2.0           h06a4308_610  
iopath                    0.1.8                    pypi_0    pypi
jasper                    2.0.14               h07fcdf6_1  
joblib                    1.0.1              pyhd3eb1b0_0  
jpeg                      9b                   h024ee3a_2  
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.3.1            py37h2531618_0  
lcms2                     2.12                 h3be6417_0  
libedit                   3.1.20210216         h27cfd23_1  
libffi                    3.2.1             hf484d3e_1007  
libgcc-ng                 9.3.0               h5101ec6_17  
libgfortran-ng            7.5.0               ha8ba4b0_17  
libgfortran4              7.5.0               ha8ba4b0_17  
libglu                    9.0.0                hf484d3e_1  
libgomp                   9.3.0               h5101ec6_17  
libllvm10                 10.0.1               hbcb73fb_5  
libopencv                 3.4.2                hb342d67_1  
libopus                   1.3.1                h7b6447c_0  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.3.0               hd4cf53a_17  
libtiff                   4.2.0                h85742a9_0  
libuuid                   1.0.3                h1bed415_2  
libuv                     1.41.0               h7f98852_0    conda-forge
libvpx                    1.7.0                h439df22_0  
libwebp-base              1.2.0                h27cfd23_0  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.10               hb55368b_3  
llvmlite                  0.36.0           py37h612dafd_4  
lz4-c                     1.9.3                h2531618_0  
markdown                  3.3.4                    pypi_0    pypi
matplotlib                3.3.4            py37h06a4308_0  
matplotlib-base           3.3.4            py37h62a2d02_0  
mkl                       2021.2.0           h06a4308_296  
mkl-service               2.3.0            py37h27cfd23_1  
mkl_fft                   1.3.0            py37h42c9631_2  
mkl_random                1.2.1            py37ha9443f7_2  
natsort                   7.1.1              pyhd3eb1b0_0  
ncurses                   6.2                  he6710b0_1  
networkx                  2.5.1                    pypi_0    pypi
ninja                     1.10.2               h4bd325d_0    conda-forge
numba                     0.53.1           py37ha9443f7_0  
numpy                     1.20.2           py37h2d18471_0  
numpy-base                1.20.2           py37hfae3a4d_0  
olefile                   0.46               pyh9f0ad1d_1    conda-forge
opencv                    3.4.2            py37h6fd60c2_1  
opencv-python             4.5.2.54                 pypi_0    pypi
openssl                   1.1.1k               h27cfd23_0  
opt-einsum                3.3.0                    pypi_0    pypi
pandas                    1.2.4            py37h2531618_0  
pcre                      8.44                 he6710b0_0  
pillow                    8.2.0            py37he98fc37_0  
pip                       21.1.2           py37h06a4308_0  
pixman                    0.40.0               h7b6447c_0  
portalocker               2.3.0                    pypi_0    pypi
protobuf                  3.17.3                   pypi_0    pypi
py-opencv                 3.4.2            py37hb342d67_1  
pycodestyle               2.7.0              pyhd3eb1b0_0  
pyparsing                 2.4.7              pyhd3eb1b0_0  
pyqt                      5.9.2            py37h05f1152_2  
python                    3.7.1                h0371630_7  
python-dateutil           2.8.1              pyhd3eb1b0_0  
python-speech-features    0.6                      pypi_0    pypi
python_abi                3.7                     1_cp37m    conda-forge
pytorch                   1.8.1           py3.7_cuda11.1_cudnn8.0.5_0    pytorch
pytorch3d                 0.5.0                    pypi_0    pypi
pytz                      2021.1             pyhd3eb1b0_0  
pywavelets                1.1.1                    pypi_0    pypi
pyyaml                    5.4.1                    pypi_0    pypi
qt                        5.9.7                h5867ecd_1  
readline                  7.0                  h7b6447c_5  
requests                  2.25.1                   pypi_0    pypi
resampy                   0.2.2                      py_0    conda-forge
scikit-image              0.18.1                   pypi_0    pypi
scikit-learn              0.24.2           py37ha9443f7_0  
scipy                     1.6.2            py37had2a1c9_1  
setuptools                52.0.0           py37h06a4308_0  
sip                       4.19.8           py37hf484d3e_0  
six                       1.16.0             pyhd3eb1b0_0  
sqlite                    3.33.0               h62c20be_0  
tabulate                  0.8.9                    pypi_0    pypi
tbb                       2020.3               hfd86e86_0  
tensorboard               1.15.0                   pypi_0    pypi
tensorflow-estimator      1.15.1                   pypi_0    pypi
tensorflow-gpu            1.15.2                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tifffile                  2021.6.14                pypi_0    pypi
tk                        8.6.10               hbc83047_0  
toml                      0.10.2             pyhd3eb1b0_0  
torchaudio                0.8.1                      py37    pytorch
torchvision               0.2.2                      py_3    pytorch
tornado                   6.1              py37h27cfd23_0  
tqdm                      4.59.0             pyhd3eb1b0_1  
typing_extensions         3.10.0.0           pyha770c72_0    conda-forge
urllib3                   1.26.5                   pypi_0    pypi
werkzeug                  2.0.1                    pypi_0    pypi
wheel                     0.36.2             pyhd3eb1b0_0  
wrapt                     1.12.1                   pypi_0    pypi
xz                        5.2.5                h7b6447c_0  
yacs                      0.1.8                    pypi_0    pypi
zipp                      3.4.1                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.9                haebb681_0

**Comment by bottler** [comment]
You have installed a version (it is unclear how, but not from a conda package) without GPU support, and you want GPU support. Can I suggest you start a new conda environment and use the instructions in INSTALL.md, and use a released pytorch3d conda package?
