### ISSUE TITLE
Can I use pytorch 3d to calculate the gt, predict of the vertices of a 2d image with Differentiable rendering loss?

### ISSUE THREAD

**Issue by nobug-code** [facebookresearch/pytorch3d#87]
## ❓ Questions on how to use PyTorch3d
Can I use pytorch 3d to calculate the gt, predict of the vertices of a 2d image with Differentiable rendering loss?

**Comment by nikhilaravi** [comment]
@nobug-code I'm not sure I understand what you are asking. Do you mean predict 3D vertices of a mesh from a 2D image?

**Comment by nobug-code** [comment]
Can I render if I have a 2D image and given coordinates?

**Comment by nikhilaravi** [comment]
Do you have the 3D vertex coordinates of the object? What are you trying to render? What do you want as the output? Please provide some more details about what you are trying to achieve.

**Comment by nikhilaravi** [comment]
@nobug-code please provide more details with examples if you still need help with this issue.

**Comment by nobug-code** [comment]
I'm sorry for the late contact. What I'm trying to implement is the neural-render-pytorch version of the feature, so I'm going to use it.
I was trying to render a 3d z axis of 1 from a point.
thanks for your answer!

**Comment by nikhilaravi** [comment]
@nobug-code can you provide pseudo code or more detailed example of exactly what you are trying to do?

**Comment by nobug-code** [comment]
What I want to do is to draw 3d renders using 2d points information (fix z axis to 1)

**Comment by bottler** [comment]
If what you mean here is take the points from an image and assign them all a z value of 1, and then render the resulting mesh (which is flat) in PyTorch3d, then that is demonstrated in the attached, which I run from the tutorials folder.

[render_logo.txt](https://github.com/facebookresearch/pytorch3d/files/4281327/render_logo.txt)

**Comment by nikhilaravi** [comment]
@nobug-code if this answers your question please close this issue.
