### ISSUE TITLE
Is there a way to get the depth map from poincloud in pytorch3d?

### ISSUE THREAD

**Issue by m-richa** [facebookresearch/pytorch3d#871]
## ❓ Questions on how to use PyTorch3D

NOTE: Please look at the existing list of Issues tagged with the label ['question`](https://github.com/facebookresearch/pytorch3d/issues?q=label%3Aquestion) or ['how-to`](https://github.com/facebookresearch/pytorch3d/issues?q=label%3A%22how+to%22). **Only open a new issue if you cannot find an answer there**.

Also note the following:

1. If you encountered any errors or unexpected issues while using PyTorch3D and need help resolving them,
   please use the "Bugs / Unexpected behaviors" issue template.

2. We do not answer general machine learning / computer vision questions that are not specific to
   PyTorch3D, such as how a model works or what algorithm/methods can be
   used to achieve X.

**Comment by m-richa** [comment]
I could get the image coordinates by taking a cross-product of the projection matrix and the 3D world coordinates. But the resulting points will not be in the form of a regular grid and there is no interpolation function implemented in pytorch yet to handle this. Is there a way to do this in pytorch3d?

**Comment by zhangzscn** [comment]
hi，you can use the zbuffer
