### ISSUE TITLE
Different rendering result between verion 0.4 and 0.6

### ISSUE THREAD

**Issue by lg93lggt** [facebookresearch/pytorch3d#877]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## Instructions To Reproduce the Issue:

Please include the following (depending on what the issue is):

use the same camera setting, after upgrade pytorch3d to 0.60, it has different render result(the axis on images)

0.4(correct):
![2021-10-13_19-50](https://user-images.githubusercontent.com/26531443/137127204-05579461-5fbc-4ede-85ff-95b9fbd071cc.png)

0.6(incorrect):
![2021-10-13_19-43](https://user-images.githubusercontent.com/26531443/137126927-1f177ea1-16f8-4267-a1d4-695b5b17d9a7.png)

**Comment by lg93lggt** [comment]
Thank you so much. I've just skipped the notes of 0.5 version.  I will read it.

**Comment by JasonBoy1** [comment]
hi, how did you get the axis?

**Comment by nikhilaravi** [comment]
@lg93lggt do you still need help with this issue?  @JasonBoy1 what exactly is your question about the axis?

**Comment by lg93lggt** [comment]
> hi, how did you get the axis?

Create a axis 3dmesh and convert it to pytorch3d Meshes， render it with pytorch3d renderer.

**Comment by lg93lggt** [comment]
> @lg93lggt do you still need help with this issue? @JasonBoy1 what exactly is your question about the axis?

Yes actually i still have the problem. After using 0.6's new param in_ndc, or using  utils.cameras_from_opencv_projection, neither of them cant project correctly.

**Comment by JasonBoy1** [comment]
@lg93lggt I am just wondering how to add the XYZ axis mesh in pytorch3d.
