### ISSUE TITLE
How to render a new view image from a small size 384x216 depth map and 960x720 RGB image?

### ISSUE THREAD

**Issue by ansj11** [facebookresearch/pytorch3d#879]
I generate a sparse points cloud from 384x216 depth map, but the xy coordinates are pixel coordinate such as 0, 1, 2, ..., H, I need unproject points to world coordinate and my code is as following:

    cameras = FoVPerspectiveCameras(device=device)
    verts = cameras.unproject_points(node_str_point)

    texture_images = {}
    texture_images['material_1'] = torch.tensor(image/255.0, dtype=torch.float32, device=device)
    material_properties = {}
    material_properties['material_1'] = {}
    material_properties['material_1']['diffuse_color'] = torch.tensor([1.000, 1.000, 1.000], dtype=torch.float32, device=device)
    material_properties['material_1']['ambient_color'] = torch.tensor([1.000, 1.000, 1.000], dtype=torch.float32, device=device)
    material_properties['material_1']['specular_color'] = torch.tensor([0.000, 0.000, 0.000], dtype=torch.float32, device=device)
    material_properties['material_1']['shininess'] = torch.tensor([10.000], dtype=torch.float32, device=device)

    from collections import namedtuple
    _Face = namedtuple("Faces", 'verts_idx normals_idx textures_idx materials_idx')
    _Aux = namedtuple("Properties", 'normals verts_uvs material_colors texture_images texture_atlas')
    faces = _Face(verts_idx=faces_verts_idx,
                  normals_idx=faces_normals_idx,
                  textures_idx=faces_textures_idx,
                  materials_idx=faces_materials_idx)
    texture_atlas = None
    aux = _Aux(normals=normals if len(normals) else None,
               verts_uvs=verts_uvs if len(verts_uvs) else None,
               material_colors=material_properties,
               texture_images=texture_images,
               texture_atlas=texture_atlas)

    create_texture_atlas = False
    tex = None
    from pytorch3d.renderer import TexturesAtlas, TexturesUV
    from pytorch3d.structures import Meshes, join_meshes_as_batch
    if create_texture_atlas:
        tex = TexturesAtlas(atlas=[aux.texture_atlas.to(device)])
    else:
        tex_maps = aux.texture_images
        if tex_maps is not None and len(tex_maps) > 0:
            verts_uvs = aux.verts_uvs.to(device)
            faces_uvs = faces.textures_idx.to(device)
            image = list(tex_maps.values())[0].to(device)[None]
            tex = TexturesUV(verts_uvs=[verts_uvs], faces_uvs=[faces_uvs], maps=image)

    mesh = Meshes(verts=[verts.to(device)], faces=[faces.verts_idx.to(device)], textures=tex)

    raster_settings = RasterizationSettings(
        image_size=(H, W),
        blur_radius=0.0,
        faces_per_pixel=1,
    )
    lights = PointLights(device=device, location=[[0.0, 0.0, -3.0]])

    materials = Materials(
        device=device,
        specular_color=[[0.0, 1.0, 0.0]],
        shininess=10.0
    )

    batch_size = 20

    t = time.time()
    meshes = mesh.extend(batch_size)

    # Get a batch of viewing angles.
    elev = torch.linspace(0, 10, batch_size)
    azim = torch.linspace(-10, 10, batch_size)

    R, T = look_at_view_transform(dist=2.7, elev=elev, azim=azim)
    cameras = FoVPerspectiveCameras(device=device, R=R, T=T)#, znear=0.1, zfar=depth1.max()+0.5, aspect_ratio=H/W)
    """cameras = PerspectiveCameras(focal_length=torch.tensor([W, H]).unsqueeze(0),
                                 principal_point=torch.tensor([W//2, H//2]).unsqueeze(0),
                                 device=device,
                                 in_ndc=False,
                                 R=torch.eye(3).float().to(device),
                                 T=torch.tensor([0,0,0]).float().to(device),
                                 image_size=(H,W)
                                )"""

    lights.location = torch.tensor([[0.0, 0.0, -3.0]], device=device)

    renderer = MeshRenderer(
        rasterizer=MeshRasterizer(cameras=cameras, raster_settings=raster_settings),
        shader=HardPhongShader(device=device, cameras=cameras)
    )

    #images = renderer(meshes, cameras=cameras, lights=lights)
    images = renderer(meshes, cameras=cameras)

but the rendered image is not right
![image](https://user-images.githubusercontent.com/24786133/137313092-4bf7f6f3-af07-4f84-b808-268095ebe7bb.png)

the original image is 

![IMG_9145](https://user-images.githubusercontent.com/24786133/137313228-3efb8008-ae64-4294-b3d9-27ef7416669e.jpg)

**Comment by nikhilaravi** [comment]
@ansj11 What is `node_str_point`? Can you provide a reproducible code example with the input data as well?
