### ISSUE TITLE
module 'pytorch3d' has no attribute 'loss

### ISSUE THREAD

**Issue by avani17101** [facebookresearch/pytorch3d#882]
module 'pytorch3d' has no attribute 'loss
I am on pytorch3d = 0.5.0 version, and when trying to import pytorch3d.loss it throws error

```
>>> import pytorch3d
>>> pytorch3d.loss
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pytorch3d' has no attribute 'loss'
```
I went through version release of 0.5.0 and seems pytorch.loss was there, hence I am not getting why this error

 I did the installation following https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md
 I changed the pytorch version to 1.9.0 while installing rest all same as installation instructions.
```
conda create -n pytorch3d python=3.8
conda activate pytorch3d
conda install -c pytorch pytorch=1.9.0 torchvision cudatoolkit=10.2
conda install -c fvcore -c iopath -c conda-forge fvcore iopath
conda install pytorch3d -c pytorch3d

```

**Comment by bottler** [comment]
Can you paste the output of `conda list`? I think pytorch3d is not properly installed.

**Comment by nikhilaravi** [comment]
@avani17101 do you still need help with this issue? If not please close it.

**Comment by lnykyks** [comment]
maybe you should use "import pytorch3d.ops" instead of "import pytorch3d" @avani17101

**Comment by raja-kumar** [comment]
It looks like an old issue but I am still facing this. Below are my installation details

python                    3.9.16               h7a1cb2a_2
pytorch                   1.13.0          py3.9_cuda11.6_cudnn8.3.2_0    pytorch
pytorch-cuda              11.6                 h867d48c_1    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytorch3d                 0.7.2           py39_cu116_pyt1130    pytorch3d

**Comment by raja-kumar** [comment]
In case anyone still looking for this, 

`from pytorch3d.loss import chamfer_distance`

this worked for me, which is weird!
