### ISSUE TITLE
Great work! How to convert original camera pose from NeRF to Pytorch3d style?

### ISSUE THREAD

**Issue by zhiwenfan** [facebookresearch/pytorch3d#883]
Thank you for submitting your re-implementation for NeRF and it is quite easy to start with.
However, it is unclear how to convert the original camera pose provided by [original NeRF paper](https://github.com/bmild/nerf) to your given camera pose(I already found some discussions in https://github.com/facebookresearch/pytorch3d/issues/664).
I wish to enquire could you please submit the code to convert the camera pose from original style to pytorch3d style?

**Comment by zhiwenfan** [comment]
@gkioxari Sorry for bothering you. Could you please help with this problem? 
Thanks!

**Comment by nikhilaravi** [comment]
@zhiwenfan In Pytorch3D the axis convention is +X left, +Y up, +Z into the screen - can you check what the NeRF convention is for the axes? Based on this you would need to convert the R/T matrices.  You could also look at the original data and compare it to the cameras we provide to get the mapping e.g. this file for the lego data: `https://dl.fbaipublicfiles.com/pytorch3d_nerf_data/lego.pth`

**Comment by hust-kevin** [comment]
@zhiwenfan @zhiwenfan how to create nerf style data like pt3logo?
if I design the log by myself, how can I get the corresponding cameras params, like R, T ,focal_length, principal_point?
