### ISSUE TITLE
Smaller faces are abandoned?

### ISSUE THREAD

**Issue by kunyao** [facebookresearch/pytorch3d#888]
When I trace a very weird bug in my program, I find pytorch3d sometimes fails to render some parts of the meshes. An example mesh and rendering scripts are attached below. I am not sure if it's because the renderer abandons some small triangles. Is there any way to solve this? 

```python
import os
import torch
import numpy as np

# Util function for loading meshes
from pytorch3d.io import load_objs_as_meshes, load_obj

# Data structures and functions for rendering
from pytorch3d.structures import Meshes
from pytorch3d.renderer import (
    look_at_view_transform,
    FoVPerspectiveCameras,
    OrthographicCameras,
    PointLights,
    DirectionalLights,
    AmbientLights,
    Materials,
    BlendParams,
    RasterizationSettings,
    MeshRenderer,
    MeshRasterizer,
    SoftPhongShader,
    SoftSilhouetteShader,
    Textures,
    TexturesUV,
    TexturesVertex
)
import torchvision


device = torch.device("cuda:0")
print("Loading...")
obj_filename = './a.obj'
verts, faces, aux = load_obj(obj_filename)
verts = verts * 0.7
meshes = Meshes(verts=[verts], faces=[faces.verts_idx], textures=None)

print("Done...")

print("Generating...")
meshes = meshes.cuda()

cameras = OrthographicCameras(focal_length=((1, 1280 / 720),), principal_point=((0, 0),), device=device)

raster_settings = RasterizationSettings(
    image_size=(1280, 720),
    bin_size=None,
    blur_radius=1e-3,
    faces_per_pixel=1,
)

lights = AmbientLights(device=device)
blend_params = BlendParams(background_color=(0, 0, 0))
renderer = MeshRenderer(
    rasterizer=MeshRasterizer(cameras=cameras, raster_settings=raster_settings),
    shader=SoftSilhouetteShader(blend_params=blend_params)
)

print("Rendering...")
images = renderer(meshes)
images[images !=0 ]= 1.0

torchvision.utils.save_image(images.permute(0, 3, 1, 2)[:, 3:4, :, :], 'out.png')
```
[mesh.zip](https://github.com/facebookresearch/pytorch3d/files/7371480/mesh.zip)

A whole face is rendered with many strip artifect
![out](https://user-images.githubusercontent.com/5549300/137870623-5eb41ec4-4936-4d5e-a07e-fa207d09950d.png)

**Comment by nikhilaravi** [comment]
Hi @kunyao apologies for the late response. Can you confirm that all vertices have a positive z value? If not they will be culled.

**Comment by kunyao** [comment]
@nikhilaravi Thanks for your response. I've double checked the issue and pretty sure it came from neither depth culling nor back face culling. I attached the obj file above(see mesh.zip).

**Comment by ompugao** [comment]
same here, and the similar behavior can be observed when the camera is far from the object.

**Comment by ompugao** [comment]
ah, sorry. my problem is already well-explained here https://github.com/facebookresearch/pytorch3d/issues/348#issuecomment-691297469.
