### ISSUE TITLE
Exporting camera position model

### ISSUE THREAD

**Issue by dhrosquete** [facebookresearch/pytorch3d#89]
Hi! First of all, is an amazing job you have done in here. Congrats and thank you!!! :+1: 

My question is that, you have an example of camera position optimization, running a model back and forth to get to the camera position.

Is this model exportable? I mean, I get that the model as you developed it doesn't receive an image as an input, but the image as the model has it stored. But is it possible to make it receive an image and predict the camera position?

Once again, thank you so much!

**Comment by nikhilaravi** [comment]
@dhrosquete the term 'model' in the camera position optimization demo is perhaps misleading - the parameter which is learnt during the optimization is the 'xyz' position of the camera in the reference image and is specific to the teapot example in the demo. There are no learned 'weights' which are exportable as is possible after training neural network models.

**Comment by gkioxari** [comment]
Hi @dhrosquete! Thank you for your kind words! If I understand correctly, you want a method that given an input image returns the camera position `(R, t)`? If yes, then the answer is Structure from Motion (SfM). SfM methods usually take in as input video frames and estimate the relative positions of the cameras. We don't provide any SfM pipelines in PyTorch3D but I believe that with some searching you can find something out there that will work for you!

**Comment by dhrosquete** [comment]
Hi @nikhilaravi and @gkioxari Thank you very much for your response! I'm aware that there are no weights on this model and that is focused on the xyz position of the camera. But could this be possible somehow?

The problem im trying to solve is the one mentioned by @gkioxari, training a network to receive an image and return the R and t of the object or the camera looking at the object. I think that I could contribute to solve this problem. Let me know if you are interested and have the time to help me a bit answering some questions. Thank you a lot!

**Comment by nikhilaravi** [comment]
@dhrosquete if you have any specific questions about how to use PyTorch3D for this we can help. I'm closing this issue but feel free to reopen it if you have questions.
