### ISSUE TITLE
How to project 3D point cloud into it's rendered image

### ISSUE THREAD

**Issue by Pooya448** [facebookresearch/pytorch3d#893]
## ❓ Questions on how to use PyTorch3D

Hello everyone,

I have a 3D pointcloud (with coordinates of all the points in 3D coordinate system)  and I have rendered the pointcloud to an image (512x512). I want to project the points into the image so that for every 3D point I get the pixel value in the image. Can this be achieved using pytorch3d, and if yes I would appreciate if you could help me.

The points have following coordinate system: 
+z outward 
+y upward

**Comment by nikhilaravi** [comment]
Hi @Pooya448 I'm not sure I understand your question. Do you know the camera pose from which the image of the pointcloud was generated? If so you can use the PyTorch3D pointcloud renderer to render an image following the example in this tutorial: https://github.com/facebookresearch/pytorch3d/blob/main/docs/tutorials/render_colored_points.ipynb. 

If you want to get the RGB pixel value from an image for each 3D point in the pointcloud then you just need to know the projected [x,y] pixel coordinates of each of the 3D points which you can also get from the intermediate output of the rasterizer - i.e the `fragments.pix_to_face` which gives the index of the point in the pointcloud at each pixel location e.g. look at the code example in [#850](https://github.com/facebookresearch/pytorch3d/issues/850)
