### ISSUE TITLE
How to download other scenes in project nerf

### ISSUE THREAD

**Issue by tau-yihouxiang** [facebookresearch/pytorch3d#901]
## ❓ Questions on how to download the other transformed NeRF data  in project nerf, such as hotdog

"The dataset files are located in the following public S3 bucket: https://dl.fbaipublicfiles.com/pytorch3d_nerf_data". But I cannot access the link for access deny. 

Could you provide the download link? Thank you in advance!

**Comment by nikhilaravi** [comment]
@tau-yihouxiang the files are [downloaded in the code](https://github.com/facebookresearch/pytorch3d/blob/master/projects/nerf/nerf/dataset.py) directly e.g.  for lego the cameras are at `https://dl.fbaipublicfiles.com/pytorch3d_nerf_data/lego.pth`.
