### ISSUE TITLE
How to determine the impact of blur_radius on silhouette size？

### ISSUE THREAD

**Issue by zhangzscn** [facebookresearch/pytorch3d#903]
When the blur_radius is set to zero，the silhouette is the same with the rendered color image。When blur_radius is not zero，the silhouette will be much bigger than the rendered color image，so How many pixels bigger，Is there a formula for that？

**Comment by nikhilaravi** [comment]
@zhangzscn apologies for the late response. The bounding box for each face is expanded by the square root of the blur radius e.g. https://github.com/facebookresearch/pytorch3d/blob/7ce18f38cd7e7f61037322d7532cd7891190a540/pytorch3d/csrc/rasterize_meshes/rasterize_meshes.cu#L85-L88.

**Comment by zhangzscn** [comment]
thank you，I will look the code
