### ISSUE TITLE
How to convert depth image to point cloud?

### ISSUE THREAD

**Issue by StefanoBerti** [facebookresearch/pytorch3d#906]
## ❓ How to convert depth image to point cloud?

I am trying to create a point cloud from the depth image of a mesh taken with a PerspectiveCamera. The depth is obtained in the following way:

```
class MeshRendererWithDepth(nn.Module):
    def _init_(self, rasterizer, shader):
        super()._init_()
        self.rasterizer = rasterizer
        self.shader = shader

    def forward(self, meshes_world, **kwargs):
        fragments = self.rasterizer(meshes_world, **kwargs)
        images = self.shader(fragments, meshes_world, **kwargs)
        return images, fragments.zbuf

render = MeshRendererWithDepth(...)
_, depth = render(mesh)
```
I also need the coordinates of the reconstructed point cloud to match the initial mesh, so the reconstructed point cloud should overlap with the initial mesh.
I tried to use `cameras.unproject_points`, I also tried to apply all the transformation given by the camera (also inverted).

**Comment by nikhilaravi** [comment]
@StefanoBerti can you share the code you were using to unproject the points using `cameras.unproject_points`? Please also include the initialization of the `cameras` class. 

Note there are several settings which you need to be aware of: https://github.com/facebookresearch/pytorch3d/blob/7ce18f38cd7e7f61037322d7532cd7891190a540/pytorch3d/renderer/cameras.py#L583-L589

In particular if you want to unproject the points so they align with the camera of the image then you need to set `world_coordinates=False`.  If you set `in_ndc=False` you need to provide the correct `image_size` when initializing the camera.
