### ISSUE TITLE
How do I initialize a mesh at a specific (x, y, z) location?

### ISSUE THREAD

**Issue by sainatarajan** [facebookresearch/pytorch3d#909]
## ❓ Questions on how to use PyTorch3D

I'm working on a project where I need to create N meshes before passing them into the graph network. However, when I create my meshes, all of them have the same (X, Y, Z) as their centers. 

Is there any way of initializing the meshes other than the following steps?

```
1. Calculate the center by taking the mean of the vertices
2. Change the values of the center to the desired location
3. Update all the vertices.
```

**Comment by nikhilaravi** [comment]
@sainatarajan what are you using to initialize the meshes? Are you creating `ico_spheres` using the PyTorch3D function? If so, then yes they will all have the same center and you will need to manually shift them.

**Comment by sainatarajan** [comment]
@nikhilaravi Thanks for your answer. Yes, I'm using `ico_spheres` to create the initial meshes.
