### ISSUE TITLE
Multiple Cameras in renderers is not providing multiple images.

### ISSUE THREAD

**Issue by grgkopanas** [facebookresearch/pytorch3d#91]
## 🐛 Bugs / Unexpected behaviors
When running with multiple cameras you only get  a mesh projection to a single screen space. Based on the plural of parameters "cameras" and Objects like OpenGLPerpectiveCameras I would expect this to be able to project in a single go multiple cameras.

https://github.com/facebookresearch/pytorch3d/blob/f358b9b14dbc1414c588f308b35f55705d777873/pytorch3d/renderer/mesh/rasterizer.py#L74

## Instructions To Reproduce the Issue:
Run any renderer with multiple cameras and you will get a single image.

**Comment by nikhilaravi** [comment]
@grgkopanas the plural `Cameras` refers to a **batch** of cameras which corresponds to a batch of input `Meshes` i.e. for each mesh in the batch, there is one camera and we render one output image.  We don't support the case of multiple cameras per scene.

**Comment by xyp8023** [comment]
Hi,

Any updates on the support of multiple cameras per scene? Now, for N cameras in the same scene, I am rendering one camera per scene at a time in a loop of N, but the training is quite slow. I'd love to hear that the support of multiple cameras per scene might be on your roadmap!

**Comment by bottler** [comment]
I'm afraid not. This is not currently planned. Have you considered extend()ing the mesh and doing the rendering as a batch? 

If that is infeasible because it uses too much memory, you may be able to customise parts of the code for your specific case to save some of this memory.

**Comment by xyp8023** [comment]
I've tried to extend the mesh and do the rendering as a batch, but in the end, I have to fuse the N meshes into one after each step of the optimization. After all, I only have one scene in reality. But the problem of fusing N meshes into one is that if I use the flag `retain_graph=True` in the backpropagation I would not have enough memory, but if I use `retain_graph=False`, then PyTorch would complain. Do you have some suggestions that I can try? I'd be much appreciated.
