### ISSUE TITLE
Voxelization of Pointsets alongside features

### ISSUE THREAD

**Issue by Sentient07** [facebookresearch/pytorch3d#911]
## ❓ Questions on how to use PyTorch3D

Hello. I have a `(B, N, 3)` pointsets and `(B, N, 1)` pointwise features which I wish to voxelize. The goal of this voxelisation is to be able to query the (approximated) feature at any given point. A typical solution would be using `ball_query`, but when N is large (typically 1million), this operation is quite slow. Hence, I am trying to use the `ops.points_to_volumes` to voxelize my point sets as 

```
grid_sizes=torch.LongTensor([[64, 64, 64], [64, 64, 64]]).cuda()
vol_density, vol_feat = _splat_points_to_volumes(points, feats, torch.zeros((2, 262144, 1)).cuda(), torch.zeros((2, 1, 262144)).cuda(), grid_sizes=grid_sizes)
```

To test if my implementation is correct, i attempt to query at known locations (i.e the pointsets described above), the values of features as follows,

```
pt_ind_int = ((points[:, :10, :] + 1) * 0.5) * (grid_sizes[:, [2, 1, 0]][:, None].type_as(points) - 1)
torch.take(vol_feat.view(2, 64, 64, 64), pt_ind_int.floor().long())
```

I expect the observed values to be close to the values of feature that corresponds to the respective pointset, but the disparity seems large. Can you please help me figure where I am going wrong?

Thanks

**Comment by bottler** [comment]
Can I suggest that you initialise a Volumes object and then use the `add_pointclouds_to_volumes` function?
That is a higher level interface which is less fiddly. You also get the benefit of a custom CUDA kernel.

**Comment by Sentient07** [comment]
Hello. Thank you for the response. If I understand correctly, do you suggest something like the snippet below? If so, I think the number of unique values in the feature between original feat tensor and the voxelised on seems to low? Is this expected? In my mind, the goal of this voxelisation is something like `torch.histogramdd` but with negative weights from the `point_feat`. Thank you. 
![image](https://user-images.githubusercontent.com/6195312/139751610-73372133-fa8c-43b3-895d-9a6ac5a5b82f.png)

**Comment by bottler** [comment]
When you do `initial_volumes.features().unique().shape`, do you mean to use `updated_volumes`? I'm a bit surprised you got 63 not 1.

What is the distribution of the point locations? If they are outside the volumes (here about -64 to 64 in each direction) then they will make no contribution. And if they are all around similar voxels then few voxels will be nonzero.

And what is the sum of the densities in updated_volumes? That should tell you how many points were inside the volumes object.

**Comment by Sentient07** [comment]
Hi,

> When you do initial_volumes.features().unique().shape, do you mean to use updated_volumes? I'm a bit surprised you got 63 not 1.

Yes you're right. I changed to `updated_volumes` and now have 57 unique values.

> What is the distribution of the point locations? If they are outside the volumes (here about -64 to 64 in each direction) then they will make no contribution. And if they are all around similar voxels then few voxels will be nonzero.

That makes sense. My pointcloud are scaled to unit sphere. So to place each point into a voxel grid, I should perhaps be using a smaller voxel size? I tried `voxel_size=1/128` and the unique values are `727194` - close to what I'd want.

The next thing I'm looking for is how to access the neighbouring points' features. i.e given a new point `query` of size `(P,3)` I should be able to interpolate the features of `query` from the features in the voxel I just created. How do I go about this?

Thanks!

**Comment by bottler** [comment]
I don't know what you mean by "interpolate". The features of that voxel divided by its density is a rough average of features locally? Or add up a few neighboring voxels and divide by the some of the densities? Is that what you mean?

Going back to ball_query, how many query points do you have, and how long does it actually take? What time are you aiming for?

**Comment by Sentient07** [comment]
> I don't know what you mean by "interpolate". 

Basically, when I'm given N points and features with shape `(N,4)`  have `(M, 3)`  query points, I infer the features of these query points as "mean" of nearest query point features. Instead, I think it would be more reasonable to infer through bi/tri linear interpolation if those N points' features are represented on a node of a voxel grid. This is exactly what I try to achieve.  

> Going back to ball_query, how many query points do you have, and how long does it actually take? What time are you aiming for?

My current timing is this `55.2 ms ± 798 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)`. I don't have a target in mind, but I'm certain if I know the neighbouring grid index of a query point, I can infer its 8 neighbour within voxel and do a bi-linear interpolation that is more efficient than this. My N=500k and M=12k and i do this in every iteration which makes training slow.

**Comment by bottler** [comment]
Then for interpolating, torch's grid_sample might help you. You may want to consider other libraries like FAISS, which has built in ways to build indices for neighborhood search.

**Comment by Sentient07** [comment]
I see, your suggestion is something like this?

```
pointclouds = Pointclouds(points=points, features=point_feat)
initial_volumes = Volumes(features = torch.zeros(2, 1, 128, 128, 128).cuda(),
                          densities=torch.zeros(2, 1, 128, 128, 128).cuda(),
                         voxel_size=1/128)
updated_volumes = add_pointclouds_to_volumes(
            pointclouds=pointclouds.cuda(),
            initial_volumes=initial_volumes.cuda(),
            mode="trilinear",
        )
torch.nn.functional.grid_sample(points.unsqueeze(0), updated_volumes.features().squeeze())
```

I gave it a shot and it gives me the following error, 

```---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-35-243fcf2bc07e> in <module>
     11             mode="trilinear",
     12         )
---> 13 torch.nn.functional.grid_sample(points.unsqueeze(1), updated_volumes.features().squeeze())

/anaconda/anaconda3/envs/ramana/lib/python3.8/site-packages/torch/nn/functional.py in grid_sample(input, grid, mode, padding_mode, align_corners)
   3987         align_corners = False
   3988 
-> 3989     return torch.grid_sampler(input, grid, mode_enum, padding_mode_enum, align_corners)
   3990 
   3991 

RuntimeError: grid_sampler(): expected grid to have size 2 in last dimension, but got grid with sizes [2, 128, 128, 128]
```

**Comment by bottler** [comment]
You need to study the doc for grid_sample and work out what shapes you need and how to get them from your code. This isn't a PyTorch3D question. As a start, note that this is a 3D interpolation so both arguments to grid_sample will need to have 5 dimensions.

**Comment by Sentient07** [comment]
If I understand right, those 5D inputs are supposed to be voxels that I create from pytorch3D right? That function seems appropriate for me but it brings me back to creation of a voxelised input from point sets and which is why I tried to use `Volumes`. If possible, can you please show a toy example as it is not obvious to me how to do it without pytorch3d. 

Thank you

**Comment by bottler** [comment]
We cannot help at this point. It may be quite complicated, but it isn't a question about PyTorch3D.
