### ISSUE TITLE
Clicking "Pictures" of a point cloud / Mesh from various angles

### ISSUE THREAD

**Issue by AD2605** [facebookresearch/pytorch3d#912]
## ❓ Questions on how to use PyTorch3D

Hello all

Suppose I have a point cloud or a mesh. I would like to go around this point cloud and take "pictures" of it from that particular angle. Let's say I start from a top angle of the point cloud and go around it and capture it as I go around. 

Next, I change my angle and my height of viewing from the base and repeat the same exercise. 

I would like to directly add this functionality to a dataloader, hence PyTorch 3D might be a better option. 

How can I achieve this ?

**Comment by sainatarajan** [comment]
Have you looked at the cow mesh tutorial?

**Comment by AD2605** [comment]
> Have you looked at the cow mesh tutorial?

Thank you for your response.
Nope I am not aware of it, could you please share the link of the same ?

**Comment by sainatarajan** [comment]
Here it is: [Render a textured mesh](https://github.com/facebookresearch/pytorch3d/blob/main/docs/tutorials/render_textured_meshes.ipynb)

**Comment by AD2605** [comment]
Thanks a lot

**Comment by nikhilaravi** [comment]
@sainatarajan thanks for jumping in and answering this question! 🙌🏽
