### ISSUE TITLE
how to use save_obj()

### ISSUE THREAD

**Issue by weihui1308** [facebookresearch/pytorch3d#913]
## ❓ Questions on how to use PyTorch3D

Tutorial :https://pytorch3d.org/tutorials/fit_textured_mesh

```
4. Save the final predicted mesh

# Fetch the verts and faces of the final predicted mesh
final_verts, final_faces = new_src_mesh.get_mesh_verts_faces(0)

# Scale normalize back to the original target size
final_verts = final_verts * scale + center

# Store the predicted mesh using save_obj
final_obj = os.path.join('./', 'final_model.obj')
save_obj(final_obj, final_verts, final_faces)
```

the API shows:
```
pytorch3d.io.save_obj(
    f: Union[pathlib.Path, str], 
    verts,
    faces,
    decimal_places: Optional[int] = None,
    path_manager: Optional[iopath.common.file_io.PathManager] = None,
    *,
    verts_uvs: Optional[torch.Tensor] = None,
    faces_uvs: Optional[torch.Tensor] = None,
    texture_map: Optional[torch.Tensor] = None) → None

Save a mesh to an .obj file.

Parameters:	
f – File (str or path) to which the mesh should be written.
verts – FloatTensor of shape (V, 3) giving vertex coordinates.
faces – LongTensor of shape (F, 3) giving faces.
decimal_places – Number of decimal places for saving.
path_manager – Optional PathManager for interpreting f if it is a str.
verts_uvs – FloatTensor of shape (V, 2) giving the uv coordinate per vertex.
faces_uvs – LongTensor of shape (F, 3) giving the index into verts_uvs for each vertex in the face.
texture_map – FloatTensor of shape (H, W, 3) representing the texture map for the mesh which 
will be saved as an image. The values are expected to be in the range [0, 1],
```
-----------------------------------------------------------------------------------------------------------
how to use save_obj in Tutorial :https://pytorch3d.org/tutorials/fit_textured_mesh contain the parameters: verts_uvs, faces_uvs and texture_map.
In the other word, how to get the value of verts_uvs, faces_uvs and texture_map.

**Comment by bottler** [comment]
In the tutorial, the texture is a TexturesVertex object - i.e. one color per vertex. This format of colors is not mentioned in the normal OBJ file format description, and is not in our implementation of OBJ.

What are you trying to do? If you want to save the learned mesh from that tutorial to a file and then load it with other software, the OFF format or the PLY format could work.

**Comment by weihui1308** [comment]
Thank you for your quick reply.

I want to save a mesh with texture to a .obj or .ply or other format file, and use this file for 3D printing.

I have try to use the function save_ply().

In the tutorial, I change:

`
# Store the predicted mesh using save_obj
final_obj = os.path.join('./', 'final_model.obj')
save_obj(final_obj, final_verts, final_faces)
`

to

`
# Store the predicted mesh using save_ply
final_obj = os.path.join('./', 'final_model.ply')
save_ply(final_obj, final_verts, final_faces)
`

but when I open the saved .ply file in Blender, it has no color, too.
What's the reason. Please tell me my mistake. Did I give less parameters? Thank you.

**Comment by bottler** [comment]
The `save_ply` function doesn't have the full functionality. You should construct a `Meshes` object with the final values including a `TexturesVertex`, and then do
```
from pytorch3d.io import IO
IO().save_mesh(mesh, "final_model.ply")
```

**Comment by weihui1308** [comment]
I visualized the img as following:

`new_mesh.textures = TexturesVertex(verts_features=sphere_verts_rgb) `
`images_predicted = renderer_textured(new_mesh, cameras=target_cameras[j], lights=lights)`

`img = images_predicted.permute(0, 3, 1, 2)[:, 0:3]`
`torchvision.utils.save_image(img_cls.data, "1.png", normalize=True)`

![200](https://user-images.githubusercontent.com/67093771/139866925-d78c7f90-292e-41bb-b0ff-2fa90a072802.png)

But when I use the function `IO().save_mesh(mesh, "final_model.ply")`, the file `final_model.ply` in Blender is: 

![image](https://user-images.githubusercontent.com/67093771/139867726-c0cc3a4e-2ebd-4244-819c-80efb107d3cc.png)

It has no color!

**Comment by bottler** [comment]
Which version of PyTorch3D? Can you paste the header from the file `final_model.ply`?

**Comment by weihui1308** [comment]
The version of PyTorch3D is:
>>> import pytorch3d
>>> print(pytorch3d.__version__)
0.6.0
>>>

The header from the file `final_model.ply` is:
ply
format binary_little_endian 1.0
element vertex 2930
property float x
property float y
property float z
property float nx
property float ny
property float nz
property float red
property float green
property float blue
element face 5856
property list uchar int vertex_index
end_header

Thank you for your help.

**Comment by bottler** [comment]
The colors are being saved. Blender is not reading them. I have heard of something like this before, caused by the color fomat. Can you try
`IO().save_mesh(new_mesh, "final_model.ply", colors_as_uint8=True)`?

**Comment by weihui1308** [comment]
I tried `IO().save_mesh(new_mesh, "final_model.ply", colors_as_uint8=True)`.
It is useless. The code can run successfully. But still has no color!

and I tried IO().save_mesh(new_mesh, "final_model.ply", binary=True). It also has no color!

I open the .ply file use vim. It shows as following:

![image](https://user-images.githubusercontent.com/67093771/140050579-4df0f823-4067-42d7-bc17-02c63177b5fd.png)

**Comment by bottler** [comment]
`binary=True` makes no difference. It is the default.
Can you try other combinations - maybe `binary=False, colors_as_uint8=True` works?

If you have other mesh software, like meshlab, could you try opening in that?

**Comment by weihui1308** [comment]
Oh, yes!
The combination` binary=False, colors_as_uint8=True` is works. And I open the .ply file use meshlab. 
Thanks so much.

By the way, the `.obj file` support for 3D printing is more friendly. Are there any tutorials that save mesh with texture or color using the function `save_obj() `.

**Comment by bottler** [comment]
No.

**Comment by YaroslavShchekaturov** [comment]
Hi everyone!

I'm trying to save mesh as ply file and get the following error: 
![image](https://user-images.githubusercontent.com/22734034/142402977-cd429d0b-c3fd-4a6d-9590-8c8c931bc989.png)

![image](https://user-images.githubusercontent.com/22734034/142403040-4da49738-9b0f-4462-93e0-3f1091c746e3.png)

**Comment by bottler** [comment]
@YaroslavShchekaturov Please start a new issue and ask there. Your question is not related to this issue.
