### ISSUE TITLE
Questions on how to use PyTorch3D to build a mesh from vertices and adjacency matrix

### ISSUE THREAD

**Issue by YanhaoZhang** [facebookresearch/pytorch3d#914]
Hi I would like to build a mesh from its vertices and adjacency matrix using pytorch3d. I know that if I have faces, it can be done as follow. May I know if I could do similar thing using vertices and its adjacency matrix? Thanks a lot.   

``` python
mesh = Meshes(
            verts=[verts],
            faces=[faces],
            textures=aor_textures
        )
```

**Comment by sainatarajan** [comment]
I encountered the same issue yesterday, and here's a quick piece of code that I wrote yesterday:

```python
def get_adjacency_matrix(edges):
    
        matrix = np.zeros((edges.max()+1, edges.max()+1))
        matrix[edges[:,0], edges[:,1]] = 1

        return torch.from_numpy(matrix).cuda()

adj_mat = get_adjacency_matrix(mesh.edges_packed().cpu().numpy())
```
Let me know if any improvements can be made.

**Comment by LarsPh** [comment]
For the people who need to build list of faces from an adjacency matrix of vertices, I did not find existing code that does this but here's a simple implementation.
```
import networkx as nx 
def build_edges(adjmat):
    """Build edge list from adjacency matrix."""
    G = nx.from_scipy_sparse_matrix(adjmat)
    nodes = list(G.nodes())
    faces = set()
    for node in nodes:
        neighbors = set(G.neighbors(node))
        for n1 in neighbors:
            for n2 in neighbors - {n1}:
                if G.has_edge(n1, n2):
                    faces.add(frozenset([node, n1, n2]))
    return [list(face) for face in faces]`
```
Definitely not the best algorithm but the result seems to be correct.
