### ISSUE TITLE
Projection volume problem

### ISSUE THREAD

**Issue by Sunshine19980919** [facebookresearch/pytorch3d#915]
This is my definition of camera：

*************************************************
R ,  T  =  look_at_view_transform ( 2.5 ,  0 ,  180 ) 

cameras  =  FoVPerspectiveCameras ( device = device ,R = R, T=T ) 
raster_settings  =  RasterizationSettings ( 
    image_size = (3072,3072) ,  
    blur_radius = 0.0 ,  
    faces_per_pixel = 1 ,  
)

lights  =  PointLights ( device = device ,  location = [[ 0.0 ,  0.0 ,  - 3.0 ]]) 
blend_params = BlendParams(background_color=(1, 1, 1))

renderer  =  MeshRenderer ( 
    rasterizer=MeshRasterizer(
        cameras=cameras, 
        raster_settings=raster_settings
    ),
    shader=SoftPhongShader(
        device=device, 
        cameras=cameras,
        lights=lights,
        blend_params=blend_params
    )
)
***************************************

I try to render a 3D model into a 2D image, trying to achieve the following objectives: assuming that a vertex coordinate of the 3D model is (v_x, v_y, v_z) = (0.6,0.6,0.6) and projected into the image size of (512，512), its image coordinate (p_x, py) is (256 + 256 * 0.6，256 + 256 * 0.6), that is, the vertex coordinate and projection coordinate correspond one by one.

First, I try to use the orthogonal projection camera, which achieves the purpose of point correspondence.

I tried to pursue a stronger sense of space, so I tried to use a perspective projection camera, but I failed. The point of the rendered image does not achieve the corresponding purpose, but I can manually adjust the size of the parameter dist (from function: look_at_view_transform). For example, the following figure: the dict distance of two corresponds to the projection of X and Y respectively, y corresponds to the projection of dist = 2.9, X corresponds to the projection of dist = 2.2, and X is the desired effect, But I tried dist = 2.2 one by one, and I couldn't find the theoretical support for dist value.

![image](https://user-images.githubusercontent.com/81543547/139851903-2460affe-97b9-42a3-8305-48d944e8d979.png)

I tried to read carefully the source code of pytorch3d and read the relevant knowledge of 3D rendering. After several days of trying, I still failed. I still can't find the dist distance corresponding to points one by one.

**Comment by bottler** [comment]
I don't fully understand, but I think you are trying to make an FoVPerspectiveCameras camera which is similar to an orthographic camera which you already have. I think you have a couple of parameters to play with, and you can balance them between each other (e.g. try making a grid of images with different values of them).

1. You can move the camera in and out, which you are already doing.
2. You can vary the field of view angle (a float passed in as `fov` to `FoVPerspectiveCameras`). In your code I think you are leaving this to the default value of 60 (degrees).

**Comment by Sunshine19980919** [comment]
> Try: focal length in pixels from the `fov` using focal_length= image_width /(2tan (`fov`/2)), and then use that the image's width of the object will be focal_length*(object width in world)/(object distance from camera). It's an inverse relationship.

Thank you for your advice. My idea worked. It looks very cool! Unfortunately, I still run pytorch3d on the CPU version. I have to say that installing pytorch3d on windows is too cumbersome. In the past week, I tried to install 0.6 CUDA pytorch3d, but still failed. Look forward to a more complete and detailed installation tutorial!
