### ISSUE TITLE
cannot import name 'Textures' from 'pytorch3d.structures'

### ISSUE THREAD

**Issue by changfali** [facebookresearch/pytorch3d#918]
my code is :
from pytorch3d.structures import Textures
import torch
verts_rgb_colors = torch.zeros([1, 1000, 3]).to('cuda')
tex = Textures(verts_rgb=verts_rgb_colors)

and i get an error:
ImportError: cannot import name 'Textures' from 'pytorch3d.structures'
(...\Miniconda3\envs\pytorch3d\lib\site-packages\pytorch3d-0.5.0-py3.8-win-amd64.egg\pytorch3d\structures\__init__.py)

can anyone help me with this?

**Comment by bottler** [comment]
This changed quite a long time ago, [in version 0.2.5](https://github.com/facebookresearch/pytorch3d/releases/tag/v0.2.5). You want 
```
from pytorch3d.renderer import TexturesVertex
tex=TexturesVertex(verts_features=verts_rgb_colors)
```
