### ISSUE TITLE
Windows installation problem

### ISSUE THREAD

**Issue by Sunshine19980919** [facebookresearch/pytorch3d#919]
I'm sorry to ask questions, but I really need help! It's too complicated and professional.

1 . conda list :

![image](https://user-images.githubusercontent.com/81543547/140606926-3b3a04e0-ef82-4f13-980f-7a82d91f3204.png)
![image](https://user-images.githubusercontent.com/81543547/140606929-901737b5-f18d-4c03-81fe-47b38b6fb8eb.png)

2.  NVIDA cuda11.1+cudnn8.04 +set CUB_HOME
 
3. in '' pytorch3d\csrc\iou_box3d\iou_utils.cuh'' and '' pytorch3d\csrc\iou_box3d\iou_utils.h'', use '!' to replace 'not' 
 
4. install  pytorch3d0.6:

set DISTUTILS_USE_SDK=1
python setup.py build

 5 . Complete error recording：

  [eorr_1.txt](https://github.com/facebookresearch/pytorch3d/files/7490287/eorr_1.txt)

**Comment by bottler** [comment]
Looking at the log, you have the problem which has been seen before with `error: expected a "("`. Please see https://github.com/facebookresearch/pytorch3d/issues/876#issuecomment-943763630

**Comment by spyroot** [comment]
I tried different CUDA, torch, etc so far no result.     It is like a massive dump of errors.
I see many 

warning C4624: 'c10::constexpr_storage_t<T>': destructor was implicitly defined as deleted
        with
        [
            T=std::vector<at::Tensor,std::allocator<at::Tensor>>
        ]

**Comment by Sunshine19980919** [comment]
> Looking at the log, you have the problem which has been seen before with `error: expected a "("`. Please see [#876 (comment)](https://github.com/facebookresearch/pytorch3d/issues/876#issuecomment-943763630)

Very constructive suggestions! Thank you for your timely reply. After installing vs 2019 version 16.9, I successfully installed pytorch0.6. I hope my experience can help some people! By the way, do you have any attempts or modifications to speed up the rendering of meshes?

**Comment by Sunshine19980919** [comment]
> 但最后一个不是

I also have this problem, but I don't think it's the main problem. After I ignored it and solved other problems, I successfully installed pytorch3d

**Comment by bottler** [comment]
> By the way, do you have any attempts or modifications to speed up the rendering of meshes? For example, delete redundant modules or judgment logic?

You could start a github discussion about this? It's a big topic and you probably have a particular type of problem in mind.

**Comment by Sunshine19980919** [comment]
> > 顺便说一下，您是否有任何尝试或修改来加速网格的渲染？比如删除冗余模块或者判断逻辑？
> 
> 你可以开始一个关于这个的github讨论吗？这是一个很大的话题，您可能会想到特定类型的问题。

All right ! Thank your reply !
