### ISSUE TITLE
Document, API and tutorial is different from the conda version.

### ISSUE THREAD

**Issue by NengQian** [facebookresearch/pytorch3d#92]
I can not run the tutorial "render textured mesh" under the conda version of pytorch 3d.
I cannot install it from source code ( no permission)
Are there any suggestions?

**Comment by nikhilaravi** [comment]
Hi @NengQian. Apologies about this. We are updating the conda package and will have a new version very soon. The tutorials have been updated to match the current version of the code on master. You should definitely be able to install from source with:

```
pip install 'git+https://github.com/facebookresearch/pytorch3d.git'
```

Add `--user` to the end of the command if you don't have permission.

**Comment by NengQian** [comment]
Great, thank you
