### ISSUE TITLE
How do I obtain all faces corresponding to a given pixel with PyTorch3D?

### ISSUE THREAD

**Issue by Floflette32** [facebookresearch/pytorch3d#924]
## ❓ Questions on how to use PyTorch3D

Hi,

Here is the general problem I'm working on:
I have a picture of an object, as well as a mesh model of it, and I'm looking for its surface area at a specific region only. So I already know the pixels coordinates corresponding to my region of interest on the picture and I'm looking for their surface area in the real 3D world and not in the 2D world.
I already used PyTorch3D to find the camera position from the picture and to render the mesh in the same position as the object on my picture.

But now my question is:
I know how to calculate my surface area if I have the all the indices of faces corresponding to each pixel, but I don't really know where I can obtain those indices with PyTorch3D. In the pix_to_face coordinates we have the K nearest faces per pixel we keep track of, and for my problem I only need K=1. But in reality there can be multiple faces in one single pixel. I also know that some faces will probably be split between multiple pixels or that some faces won't be completely on the visible side of my object. But do you know where I could find this information about all the faces corresponding to each pixel with PyTorch3D?

Thank you and have a good day!

**Comment by bottler** [comment]
I don't understand. If you increase `K` you should get more of the faces corresponding to each pixel. When you say you only need `K=1`, is that for rendering? You can do a separate rasterization call with larger K.

**Comment by Floflette32** [comment]
Thank you for responding so quickly!

What I understand, but maybe I'm totally wrong, is that:
if I increase K, I will have face indices which correspond to hidden parts of my object at a specific pixel position.

So, I think I'm not interested in these faces, since I only need to calculate surface area that I could really see from a given camera position.

![Cube](https://user-images.githubusercontent.com/93918292/140883979-d163ac89-eaac-4f8b-bfea-5faccbe4e80e.png)

Let's say you have this cube which is modeled with a triangular mesh of 12 faces, plotted in a grid of 4X4 pixels (in blue). If you want to calculate its visible surface area in real world, we need to sum the areas of faces A, B, C, D, E and F (in orange). But if we take K=1, we will only obtain a maximum of 4 face indices (let's say A, B, C, D). And if we increase K, the problem stays the same since it will give us indices of hidden faces along the z-axis (G, H, I, J, K or L not visible here) and not the two missing neighboring visible faces F and E.

We could increase the number of pixels of the grid until we get all the faces, but it is not ideal, so is there a way with PyTorch to obtain all the indices of the 6 visible faces of my cube, or at least to recover the missing ones from pix_to_face?

**Comment by bottler** [comment]
I think the rasterization outputs are each the faces hit by a ray through a point - the centre of the pixel. So you're right, increasing K won't get you the faces which are small compared to pixels. You could rasterize on an image with more pixels which are smaller to get more of the top layer.

**Comment by Floflette32** [comment]
Alright, so if it's the better way of doing that, I will rasterize with more pixels. Thank you!
