### ISSUE TITLE
Training with variable-size meshes in a batch

### ISSUE THREAD

**Issue by nicolasugrinovic** [facebookresearch/pytorch3d#925]
Hi, 
Thanks for the great work! I need to train a network that has as inputs small 3D pointclouds of varying sizes, therefore, inside one batch I have pointclouds of different sizes. I came across  [batching for pytorch3D](https://pytorch3d.org/docs/batching) and I can see that one can get the padded vertices `meshes.verts_padded() `to have a uniform-sized batch of tensors containing the vertices. 

Can I use these padded vertices as an input to a network and expect to be able to train it (meaning, will be able to do backdrop) knowing that pytorch3D will handle proper gradient computation by masking the vertices that were padded?

**Comment by bottler** [comment]
The gradient calculation works correctly around padding. There's nothing special to worry about.
