### ISSUE TITLE
in-plane camera rotation parameter for look_at_view_transform

### ISSUE THREAD

**Issue by erpayne1129** [facebookresearch/pytorch3d#927]
## 🚀 Feature

An additional `roll` parameter for the `look_at_view_transform` function to offer control over rotation in the plane of the camera. 

## Motivation

Elevation  (`elev`) and Azimuth (`azim`) are sufficient to locate any point on the sphere, but these two parameters alone do not allow for all possible viewing angles centered on an object. The addition of a roll parameter to rotate the camera around its viewing axis would then allow for `look_at_view_transform` to span the entire space of centered viewpoints. 

When optimizing the camera viewing angle, I have noticed that the shortest path to a desired viewpoint is often not traversable if optimizing only elevation and azimuth, resulting in diminished optimization performance. The third degree of freedom offered by a `roll` parameter would free up these optimization pathways and would offer additional viewing angles to anyone using spherical angles.

It may be possible to work around this limitation by modifying the `up` vector, but even if possible that would be very unintuitive for users.

## Pitch

The actual rotation transformation for `roll` should not be difficult to implement considering that spherical angle functionality for `elev` and `azim` are already implemented elsewhere. The only difference should be the rotation matrix itself, which can be obtained from any geometry reference source (https://www.meccanismocomplesso.org/en/3d-rotations-and-euler-angles-in-python/). It may be best to add the `roll` functionality inside of `look_at_rotation`, called by `look_at_view_transform`.

**Comment by bottler** [comment]
I think `look_at_view_transform` is designed for a specific task and matches other libraries. But what you want to do should be easy to achieve with other functionality. Can you look at the documentation `rotate_on_spot` function [here](https://github.com/facebookresearch/pytorch3d/blob/main/pytorch3d/renderer/camera_utils.py#L71), which illustrates applying a roll to an existing camera location?

**Comment by erpayne1129** [comment]
Thank you, this is exactly what I was looking for, very glad to see it's already available. I tried looking through the camera utils for a function like this but clearly I didn't look hard enough, since I was just looking for the word "roll". It may help other people find this function in their searches in the future if the term "camera roll" is added to its documentation somewhere.

**Comment by nikhilaravi** [comment]
@erpayne1129 thanks for the feedback. If you want to submit a PR which updates the docs to include the term "camera roll" we can accept it.
