### ISSUE TITLE
Windows 10 installation problem

### ISSUE THREAD

**Issue by Timothychance** [facebookresearch/pytorch3d#928]
I am sorry to bother you, and i have noticed that there are some similar issues, but I still can't fix problems according to instructions and i relly need help!

1.pytorch1.7+NVIDA cuda11.0+cudnn8.04 +set CUB_HOME + VS2019 16.9

2.in '' pytorch3d\csrc\iou_box3d\iou_utils.cuh'' and '' pytorch3d\csrc\iou_box3d\iou_utils.h'', use '!' to replace 'not'
   deleted const auto kEpsilon and replaced all of its references with its value (1e-4) in pytorch3d\csrc\iou_box3d/iou_utils.cuh

3.set DISTUTILS_USE_SDK=1
   python setup.py install 

4 . Complete error recording：
[error_1.txt](https://github.com/facebookresearch/pytorch3d/files/7513232/error_1.txt)

I am very grateful for your help！

**Comment by bottler** [comment]
I'm afraid I can't read the main error in the log, due to language and encoding problems. I see
```
D:\Anaconda\lib\site-packages\torch\include\ATen/cuda/Exceptions.h(54): error C2373: ¡°cusparseGetErrorString¡±: ÖØ¶¨Òå£»²»Í¬µÄÀàÐÍÐÞÊÎ·û
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\include\cusparse.h(306): note: ²Î¼û¡°cusparseGetErrorString¡±µÄÉùÃ÷
```
or
```
D:\Anaconda\lib\site-packages\torch\include\ATen/cuda/Exceptions.h(54): error C2373: °∞cusparseGetErrorString°±: ÷ÿ∂®“Â£ª≤ªÕ¨µƒ¿‡–Õ–ﬁ Œ∑˚
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\include\cusparse.h(306): note: ≤Œº˚°∞cusparseGetErrorString°±µƒ…˘√˜
◊
```
Can you see the error properly? Also, what versions of PyTorch and CUDA and VSCode are you using?

**Comment by Timothychance** [comment]
> I'm afraid I can't read the main error in the log, due to language and encoding problems. I see
> 
> ```
> D:\Anaconda\lib\site-packages\torch\include\ATen/cuda/Exceptions.h(54): error C2373: ¡°cusparseGetErrorString¡±: ÖØ¶¨Òå£»²»Í¬µÄÀàÐÍÐÞÊÎ·û
> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\include\cusparse.h(306): note: ²Î¼û¡°cusparseGetErrorString¡±µÄÉùÃ÷
> ```
> 
> or
> 
> ```
> D:\Anaconda\lib\site-packages\torch\include\ATen/cuda/Exceptions.h(54): error C2373: °∞cusparseGetErrorString°±: ÷ÿ∂®“Â£ª≤ªÕ¨µƒ¿‡–Õ–ﬁ Œ∑˚
> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\include\cusparse.h(306): note: ≤Œº˚°∞cusparseGetErrorString°±µƒ…˘√˜
> ◊
> ```
> 
> Can you see the error properly? Also, what versions of PyTorch and CUDA and VSCode are you using?

Thank you so much for such a quick reply, I am sorry for such mistakes, and now I have changed encoding from ANSI to UTF-8, does it work this time?
[error_1.txt](https://github.com/facebookresearch/pytorch3d/files/7513950/error_1.txt)
I am not sure whether the language makes confusion, if that happens, I will build it again and set English as default language when I return to laboratory from dormitory tomorrow.

By the way, I use pytorch1.7, cuda11.0 and VS2019 16.9.6

**Comment by Timothychance** [comment]
I notice what you say in #920 
I am using the latest main, so there is no problem with the code. I just make the change:
`    extra_compile_args = {"cxx": ["/std:c++14"]} `

but I get the error report, and I did not find similar error in existing issues.

I don't know what's wrong, is there any good idea to fix the problems?Thank a lot! @bottler

**Comment by bottler** [comment]
> Thank you so much for such a quick reply, I am sorry for such mistakes, and now I have changed encoding from ANSI to UTF-8, does it work this time? [error.txt](https://github.com/facebookresearch/pytorch3d/files/7517555/error.txt)

There's no compiler error in this file, but the build just stopped. I think the parallel compilation ran out of memory. Can you retry the build setting the environment variable `PYTORCH3D_NO_NINJA` to `1` or `MAX_JOBS` to `1`?

**Comment by hfpro** [comment]
hello. please tell me what the error is and how to fix
it when compiling an assembly in windows 10 and visual studio 2019, an error occurs.
[error.txt](https://github.com/facebookresearch/pytorch3d/files/7523051/error.txt)

**Comment by bottler** [comment]
@hfpro I think you are not using the latest version of the code from the `main` branch. Your error refers to something which has been fixed since the last release. If you have any further questions, please start a new issue, rather than commenting on an existing issue.

**Comment by hfpro** [comment]
I tried to compile from the links and the main branch, but the errors are repeated.
please help
[error.txt](https://github.com/facebookresearch/pytorch3d/files/7523195/error.txt)

**Comment by bottler** [comment]
No. Please open a new issue.

**Comment by Timothychance** [comment]
Hi, thank for your help, I try it again follow your suggestions, and now I get :
`Finished processing dependencies for pytorch3d==0.6.0`

it seems like a complete build. 
![Image_20211112152538](https://user-images.githubusercontent.com/50390011/141427060-79485945-a66e-4c54-82c3-70fe44f5e2fa.png)

Now I follow **INSTALL.md** to test:
`python3 -m unittest discover -p *.py`
but here seems to be something wrong:

FAIL: test_simple_sphere_batched (test_render_points.TestRenderPoints)

Traceback (most recent call last):
  File "D:\Users\O0001974\Downloads\Compressed\pytorch3d-main\tests\pulsar\..\test_render_points.py", line 327, in test_simple_sphere_batched
    self.assertClose(rgb, image_ref)
  File "D:\Users\O0001974\Downloads\Compressed\pytorch3d-main\tests\common_testing.py", line 183, in assertClose
    self.fail(err)
AssertionError: Not close. Max diff 1.0. Shape (256, 256, 3). At (24, 148, 0).


FAIL: test_simple_sphere_pulsar (test_render_points.TestRenderPoints)

Traceback (most recent call last):
  File "D:\Users\O0001974\Downloads\Compressed\pytorch3d-main\tests\pulsar\..\test_render_points.py", line 129, in test_simple_sphere_pulsar
    self.assertClose(rgb, image_ref, rtol=7e-3, atol=5e-3)
  File "D:\Users\O0001974\Downloads\Compressed\pytorch3d-main\tests\common_testing.py", line 183, in assertClose
    self.fail(err)
AssertionError: Not close. Max diff 1.0. Shape (256, 256, 3). At (19, 116, 0).


FAIL: test_is_eigen_gpu (test_symeig3x3.TestSymEig3x3)

Traceback (most recent call last):
  File "D:\Users\O0001974\Downloads\Compressed\pytorch3d-main\tests\test_symeig3x3.py", line 47, in test_is_eigen_gpu
    self._test_is_eigen(test_input)
  File "D:\Users\O0001974\Downloads\Compressed\pytorch3d-main\tests\test_symeig3x3.py", line 65, in _test_is_eigen
    rtol=rtol,
  File "D:\Users\O0001974\Downloads\Compressed\pytorch3d-main\tests\common_testing.py", line 183, in assertClose
    self.fail(err)
AssertionError: Not close. Max diff 0.00126725435256958. Max relative diff 1.540574550628662 Shape (1024, 3, 3). At (371, 1, 1).


FAIL: test_inverse (test_transforms.TestTransform)

Traceback (most recent call last):
  File "D:\Users\O0001974\Downloads\Compressed\pytorch3d-main\tests\pulsar\..\test_transforms.py", line 310, in test_inverse
    self.assertTrue(torch.allclose(m, m5, atol=1e-3))
AssertionError: False is not true


FAIL: test_coord_grid_transforms (test_volumes.TestVolumes)

Traceback (most recent call last):
  File "D:\Users\O0001974\Downloads\Compressed\pytorch3d-main\tests\pulsar\..\test_volumes.py", line 380, in test_coord_grid_transforms
    self.assertClose(grid_world, grid_world_2, atol=1e-5)
  File "D:\Users\O0001974\Downloads\Compressed\pytorch3d-main\tests\common_testing.py", line 183, in assertClose
    self.fail(err)
AssertionError: Not close. Max diff 0.01593017578125. Max relative diff 0.0009660190553404391 Shape (3, 4, 5, 7, 3). At (0, 0, 0, 6, 0).


Ran 919 tests in 325.243s

FAILED (failures=47, errors=160, skipped=16)


**So, I wonder whether the build is finished? Thank you for help!**

**Comment by bottler** [comment]
I don't know if the tests pass on Windows. There may be small numerical differences which break some. Can you attach a log with all the failures? It may be that your build of pulsar is not working but the rest of PyTorch3D is fine.

**Comment by LewisSean** [comment]
my first isstallation's compile error log is same with yours
then i try to `command out Line 60` in setup.py
`# "-std=c++14",`
it works!
