### ISSUE TITLE
Batching viewpoints

### ISSUE THREAD

**Issue by HectorAnadon** [facebookresearch/pytorch3d#93]
Hello! As it is possible to batch render different meshes, is it possible to batch render the same mesh from different viewpoints e.g (different rotation and translation)?

**Comment by nikhilaravi** [comment]
Look at the [`render_textured_meshes`](https://github.com/facebookresearch/pytorch3d/blob/master/docs/tutorials/render_textured_meshes.ipynb) demo notebook - we have an example of rendering the same mesh from multiple viewpoints.

**Comment by HectorAnadon** [comment]
I see that the R and T have a batch dimension. Thanks for the quick answer.
