### ISSUE TITLE
PyTorch3D prebuilt binaries on anaconda for Python 3.8 and cuda 11.1

### ISSUE THREAD

**Issue by shadowninjazx** [facebookresearch/pytorch3d#930]
## 🚀 Feature
Anaconda does not seem to have prebuilt binaries for Python 3.8 and cuda 11.1 combination. 

Is there a way to install PyTorch3D 0.6.0 with Python 3.8 and cuda 11.1 from anaconda?

## Motivation

I cannot seem to install the latest version of PyTorch3D (0.6.0) from anaconda with Python 3.8 and cuda 11.1. I noticed that it is missing from here https://anaconda.org/pytorch3d/pytorch3d/files. However, I noticed that for version 0.5.0, anaconda has a corresponding build for Python 3.8 and cuda 11.1. The same build seems to be missing in 0.6.0. 

## Pitch

It will make installing and upgrading PyTorch3D easier.

**Comment by bottler** [comment]
Yes - this was noticed in #917. We intend to rectify this with another release soon.

**Comment by bottler** [comment]
You can use the nightly build now if that helps.

**Comment by shadowninjazx** [comment]
Thanks.
