### ISSUE TITLE
error installing windows 10 and visual studio 2019

### ISSUE THREAD

**Issue by hfpro** [facebookresearch/pytorch3d#932]
hello. please tell me what the error is and how to fix
it when compiling an assembly in windows 10 and visual studio 2019, an error occurs.
I tried to compile from the links and the main branch, but the errors are repeated.
please help
[Uploading error.txt…]()

**Comment by bottler** [comment]
The file upload failed. Please try again to upload the file. Also please tell us about you environment - e.g. `conda info` and `conda list`.

**Comment by hfpro** [comment]
[error.txt](https://github.com/facebookresearch/pytorch3d/files/7523218/error.txt)
yes, I install according to the instructions in the conda environment

**Comment by hfpro** [comment]
[conda.txt](https://github.com/facebookresearch/pytorch3d/files/7523228/conda.txt)

**Comment by bottler** [comment]
I think that conda list output is not from inside the environment - it isn't the right one. 

The error you have is 
```
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.5\include\cub\util_namespace.cuh(46): fatal error C1189: #error:  CUB requires a definition of CUB_NS_QUALIFIER when CUB_NS_PREFIX/POSTFIX are defined.
```
You seem to be using newer cuda and cub than what we and torch recommend. We haven't tested PyTorch3D with any cuda newer than 11.3.  You are off the beaten track :) , so please be proactive about fixing things which have changed.  I think CUB_NS_PREFIX and CUB_NS_POSTFIX are being set by PyTorch (depending on version) automatically, and as you are using a newer CUB than recommended (the one inside the newish cuda) you need to deal with this requirement.

**Comment by hfpro** [comment]
you were right, the problem was in the cuda version
, I had to reinstall the driver for the video card and replace the cuda, everything worked.
thanks

**Comment by hfpro** [comment]
hello, when using the library in scripts, I get the message "WARNING: CPU only, this will be slow!" I tried to install a video card driver update, an error constantly occurs during assembly, now CUDA TOOLKIT 10.2, CUDA video card 10.0. what do you advise me to do?

**Comment by bottler** [comment]
That error is only in some tutorials, and is raised when `torch.cuda.is_available()` is False. So it would only come from a script if you put it there. Can you work out more of what is happening? Does `torch.cuda.is_available()` return False? Does it matter? Do you need cuda and why?

**Comment by hfpro** [comment]
here is the message "WARNING: CPU only, this will be slow! ...\anaconda 3\envs\pytorch3d\lib\site-packages\torch\cuda\__init__.py:52: User Warning: CODE initialization: The NVIDIA driver on your system is too old (found version 10010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. ((Triggered internally at ..\c10\cuda\CUDA Functions.cpp:100.)
return torch._C._cuda_getDeviceCount() > 0"
yes, I would like to use the computing power of a video cardyes,

**Comment by bottler** [comment]
You need to sort out your GPU/driver/CUDA/PyTorch setup. This isn't a PyTorch3D thing.

**Comment by hfpro** [comment]
I got it, thanks.
I thought you would advise something

**Comment by nikhilaravi** [comment]
@hfpro closing this issue for now. If you have further questions feel free to reopen it!
