### ISSUE TITLE
error installing in Windows10，It feels like a problem about VisualStudio

### ISSUE THREAD

**Issue by 18809609617** [facebookresearch/pytorch3d#933]
My environment is
Python3.7 CUDA10.2 Pytorch1.6
I have installed other dependent libraries required. Cudacub I haven't found the installation method and haven't been installed yet. I checked the method on the Internet to solve the problem of Nijia during installation. Now I've been troubled by this problem about vs (error 1181, installation error, full text in the text) for a long time and can't be solved. Thank you very much for your advice and help!

Is Linux more stable in the installation and use of pytorch3d? I wonder if I can't solve the installation problem of win10, I'm going to switch to Linux to use pytorch3d. Cry.
[conda list.txt](https://github.com/facebookresearch/pytorch3d/files/7525609/conda.list.txt)
[Error.txt](https://github.com/facebookresearch/pytorch3d/files/7525612/Error.txt)

**Comment by bottler** [comment]
It's much easier to install PyTorch3D on Linux than on Windows, and we provide built packages for Linux. If you don't have a special need for windows and have access to Linux, even if only in a container, it's best to start with Linux. I have no idea what this error 1181 means. It's coming from the linker.

I think the`conda list` you sent might not be from the right conda environment. But with this error I don't think it matters. More likely the compiler setup matters.

**Comment by nikhilaravi** [comment]
@18809609617 closing this issue for now. If you have issues installing PyTorch3D on linux please open a new issue.

**Comment by 18809609617** [comment]
ok，thank u~
