### ISSUE TITLE
hot to save ply with colors

### ISSUE THREAD

**Issue by YaroslavShchekaturov** [facebookresearch/pytorch3d#942]
Tutorial :https://pytorch3d.org/tutorials/fit_textured_mesh

Follwing #913 I want to save my cow mesh as a ply with textures. To do that I've used 

IO().save_mesh(new_mesh, "final_model.ply", binary=False, colors_as_uint8=True). but results seems weird in Meshlab. 

![image](https://user-images.githubusercontent.com/22734034/142452447-58bdfd56-6d60-4faa-b4d8-982e438be5c0.png)

![image](https://user-images.githubusercontent.com/22734034/142452392-3039683a-77a2-4e03-ab0f-e212f4ef4749.png)

How can I save ply such that Ill have the same colors as in my jupyter notebook?

**Comment by bottler** [comment]
I think meshlab has not read the colors at all and you are seeing a lighting effect.
What happens if you save with `binary=False`?
Note that you can't pass `verts_colors` to our `io.save_mesh` - it will be ignored. The colors need to be in the mesh.

**Comment by YaroslavShchekaturov** [comment]
Hi Jeremy!

I've tried both with binary=False and with binary=True - results are the same. This is the result without verts_colors which is the same
![image](https://user-images.githubusercontent.com/22734034/142453941-e61a8d58-8c20-4f6d-8494-c71597063d8e.png)

**Comment by YaroslavShchekaturov** [comment]
I'm using pytorch3d 0.6 version now

**Comment by bottler** [comment]
Can you share the ply file here?

**Comment by YaroslavShchekaturov** [comment]
https://drive.google.com/file/d/1HA6xNO-TuGow9M26E3yC51GMfoIBHevM/view?usp=sharing

**Comment by bottler** [comment]
That file contains the same PLY data twice, not sure why. But the colors are as you've displayed in your meshlab screenshots: white with blue patches. I think the saving worked, it just doesn't look like the original cow.

**Comment by YaroslavShchekaturov** [comment]
I did the same rutine once again and got this this ply file https://drive.google.com/file/d/178QgiqtAJJT132jrkxN5O8QtKDryvAy4/view?usp=sharing

**Comment by bottler** [comment]
It's also mostly white with some other colors. I think you are successfully writing data from PyTorch3D which can be read by meshlab. What is your question?

**Comment by YaroslavShchekaturov** [comment]
I just do not understand why I have thsese magenta faces and how to get out of them 

![image](https://user-images.githubusercontent.com/22734034/142467029-2bb719ac-06df-46e5-869b-c555db955a46.png)

**Comment by bottler** [comment]
I think you have them in your notebook with PyTorch3D, which you have based on the tutorial. Can you look at that? And look what data is in the mesh you are saving and how it got there. Maybe use plot_batch_individually on the mesh object in the notebook.

**Comment by YaroslavShchekaturov** [comment]
But why dont I see them during vizualisation? If I visualize my mesh I get 
![image](https://user-images.githubusercontent.com/22734034/142476483-92db1df2-1cdc-415e-a218-c911fc220798.png)

**Comment by bottler** [comment]
What's the difference between new_mesh and new_src_mesh? Could you share the whole ipynb?

**Comment by YaroslavShchekaturov** [comment]
new_mesh and new_src_mesh are the same!
Sure! https://drive.google.com/file/d/1X6iZUrqLojhQVJVRC2_0eym2ZW-wL9rN/view?usp=sharing

**Comment by klloggss** [comment]
I have exactly the same issue. The .ply model looks fine if I plot it in code, but if I want to export it has some strange blue areas.
