### ISSUE TITLE
Avoid render mesh from backside. `cull_backfaces` not sufficient.

### ISSUE THREAD

**Issue by PeterL1n** [facebookresearch/pytorch3d#945]
## 🚀 Feature
https://user-images.githubusercontent.com/7651753/142588786-035baea7-9bbc-4e5e-8721-6671679c0fe2.mp4

I am trying to render this mesh. With `cull_backfaces` turned on, there are still some parts of the mesh leaking out when the camera rotates to the back. This is because currently, PyTorch3D treats backfaces as a passthrough, but I really need it to terminate.

**Comment by PeterL1n** [comment]
I created a pull request to address this issue. https://github.com/facebookresearch/pytorch3d/pull/948

I took a different and more general approach. I let `rasterize_meshes` function return an additional BoolTensor indicating whether the rasterized face is front-facing or back-facing. This way, I can set `cull_backfaces=False` to NOT bypass backfaces and render the mesh from both sides, then manually mask out the back-facing pixels.

This approach is completely backward compatible, as it does not change any forward or backward logics. It is merely exposing additional information that is already implemented in the kernel to the python frontend.

Before: Using `cull_backfaces=True`
https://user-images.githubusercontent.com/7651753/142703443-3e6c064e-63ef-48d6-a8ac-a2afd2d17b3e.mp4

After: Using `cull_backfaces=False` to rasterize both sides, then use the returned `back_faces` BoolTensor to determine whether the face is front-facing or not, and manually mask it.
https://user-images.githubusercontent.com/7651753/142703510-21389412-6184-4099-980c-7a3f96762274.mp4

**Comment by bottler** [comment]
The idea looks good, and thanks for this. Couple of things:
1. The rasterize_meshes_python function needs to produce the new output too so that the tests keep passing.
2. More seriously, the change produces a measurable slowdown to the rasterizer, like 10% or more on the benchmarks. We need to come up with a way to make the new output optional, and working out how best to do it will require some significant discussion internally.

**Comment by RafailFridman** [comment]
I found myself in need of this too. Are there any plans on adding this functionality to some future pytorch3d release?
