### ISSUE TITLE
How to build pytorch3d faster with multi-cores?

### ISSUE THREAD

**Issue by wikiwen** [facebookresearch/pytorch3d#949]
I build pytorch3d from source according to the install.md by `pip install .`
It's very slow to build about 15~30 minutes. I found this command compile with only one core.
I try to set `export MAKEFLAGS="-j$(nproc)"` according to [url](https://stackoverflow.com/a/57014278/6147756), but it doesn't work.

Dose anyone know how to build pytorch3d faster with multi-cores?

**Comment by bottler** [comment]
By default, assuming PyTorch 1.5 or higher, PyTorch3D should be using `ninja` to build, so the compilation happens in parallel. The parallelism is controlled by the environment variable `MAX_JOBS`. Can you work out why this isn't working for you?

**Comment by wikiwen** [comment]
> By default, assuming PyTorch 1.5 or higher, PyTorch3D should be using `ninja` to build, so the compilation happens in parallel. The parallelism is controlled by the environment variable `MAX_JOBS`. Can you work out why this isn't working for you?

Thanks for your reply. You are right. It works!

According to your remind, I run `pip install -v .` to see more logs and found a warning about `ninja`
` UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.`
So i install it and rebuild pytorch3d. It's so fast. Thank you very much.

**Comment by swapnilsengupta2301-maker** [comment]
How can I install pytorch3d fast using cloning github repository in Google colab in T4 GPU
