### ISSUE TITLE
Visible line artifacts when optimizing mesh texture and cameras

### ISSUE THREAD

**Issue by YuvalNirkin** [facebookresearch/pytorch3d#953]
I am getting visible line artifacts when optimizing mesh texture and cameras:

![image](https://user-images.githubusercontent.com/3984115/143013446-6a3a0328-fd48-463e-9250-5bdaec8687e5.png)
Those lines correspond to the mesh edges.

I am following the [fit_textured_mesh](https://github.com/facebookresearch/pytorch3d/blob/main/docs/tutorials/fit_textured_mesh.ipynb) example, using the same losses with the following parameters:
```Python
sigma = 1e-6
gamma = 1e-4
faces_per_pixel = 50

raster_settings = RasterizationSettings(
            image_size=image_size,
            blur_radius=np.log(1. / 1e-4 - 1.) * sigma,
            faces_per_pixel=faces_per_pixel,
            perspective_correct=False   # Test
        )

blend_params = BlendParams(sigma=sigma, gamma=gamma, background_color=(0.0, 0.0, 0.0))
```
I have tried different combination of the *sigma*, *gamma*, and *faces_per_pixel* parameters, and higher resolution texture but it did not solve the issue.

Please help.

Thanks in advance,
Yuval

**Comment by bottler** [comment]
I think this (and the similar #953) are caused by interpolation from parts of the texture map which weren't intended. I suggest playing with the `perspective_correct` and `clip_barycentric_coords` members of `RasterizationSettings` and maybe the details of how the TexturesUV was constructed - e.g. the `align_corners`.

**Comment by JasonBoy1** [comment]
Dear @YuvalNirkin , have you solved this?
