### ISSUE TITLE
Import Error after installing Pytorch3d

### ISSUE THREAD

**Issue by Kiesi1991** [facebookresearch/pytorch3d#959]
Hello, I hope anyone could help me with my error after installing pytorch3D.

here are my used packages:  [package-list.txt](https://github.com/facebookresearch/pytorch3d/files/7611563/package-list.txt)
 
error massage after running code `from pytorch3d.io import load_obj, save_obj:`

`Traceback (most recent call last):
  File "/home/markus/PycharmProjects/pytorch3d/01_FitMesh.py", line 7, in <module>
    from pytorch3d.io import load_obj, save_obj
  File "/home/markus/anaconda3/envs/pytorch3d_v01/lib/python3.8/site-packages/pytorch3d/io/__init__.py", line 8, in <module>
    from .obj_io import load_obj, load_objs_as_meshes, save_obj
  File "/home/markus/anaconda3/envs/pytorch3d_v01/lib/python3.8/site-packages/pytorch3d/io/obj_io.py", line 22, in <module>
    from pytorch3d.renderer import TexturesAtlas, TexturesUV
  File "/home/markus/anaconda3/envs/pytorch3d_v01/lib/python3.8/site-packages/pytorch3d/renderer/__init__.py", line 7, in <module>
    from .blending import (
  File "/home/markus/anaconda3/envs/pytorch3d_v01/lib/python3.8/site-packages/pytorch3d/renderer/blending.py", line 11, in <module>
    from pytorch3d import _C
ImportError: /home/markus/anaconda3/envs/pytorch3d_v01/lib/python3.8/site-packages/pytorch3d/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor2leERKN3c106ScalarE`

I read some issues about the same problem, it was mentioned to use different versions of pytorch and python. I have tried several different versions too, but I was not able to solve it. Are there any recommendations about specific versions?

Just for info: I am using a **Nvidea RTX3060.**

Thank you for your help!

**Comment by PeterL1n** [comment]
I usually install directly from pip which fixes the problem.

pip install git+git://github.com/facebookresearch/pytorch3d.git

**Comment by Kiesi1991** [comment]
> I usually install directly from source which fixes the problem.
> 
> pip install git+git://github.com/facebookresearch/pytorch3d.git

ok, if I install directly from source another error occurred `ERROR: Failed building wheel for pytorch3d`

I have also tried:
`curl -LO https://github.com/NVIDIA/cub/archive/1.10.0.tar.gz`
`tar xzf 1.10.0.tar.gz`
`export CUB_HOME=$PWD/cub-1.10.0`
to solve the building wheel issue. (as mentioned from: [https://github.com/facebookresearch/pytorch3d/issues/483]) This was not working.

So I can install pytorch3d with Install wheels for Linux:
`pip install pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py38_cu102_pyt190/download.html`

after successfully installations, I got the import error again.

**Comment by bottler** [comment]
These problems can be caused by mismatched versions of PyTorch or cuda. In the last case you mention, you are using the PyTorch 1.9.0 build, but according to your text file above you have PyTorch 1.7.1. Can you maybe start a brand new environment e.g. as described in our INSTALL.md, and install the PyTorch3D wheel which is exactly corresponding?

**Comment by PeterL1n** [comment]
Also, try conda install. Conda usually just work.

**Comment by Kiesi1991** [comment]
> These problems can be caused by mismatched versions of PyTorch or cuda. In the last case you mention, you are using the PyTorch 1.9.0 build, but according to your text file above you have PyTorch 1.7.1. Can you maybe start a brand new environment e.g. as described in our INSTALL.md, and install the PyTorch3D wheel which is exactly corresponding?

Thank you for your reply! I tried a brand new environment, but it was not working. Here are my steps:

1.  `conda create -n pytorch3d_v10 python=3.8`
2.  `conda activate pytorch3d_v10`
3.  `conda install -c pytorch pytorch=1.9.0 torchvision cudatoolkit=10.2`
4.  `conda install -c fvcore -c iopath -c conda-forge fvcore iopath`

5. `curl -LO https://github.com/NVIDIA/cub/archive/1.10.0.tar.gz`
6. `tar xzf 1.10.0.tar.gz`
7. `export CUB_HOME=$PWD/cub-1.10.0`

8. `conda install jupyter`
9. `pip install scikit-image matplotlib imageio plotly opencv-python`
10. `pip install black 'isort<5' flake8 flake8-bugbear flake8-comprehensions`

11. `pip install pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py38_cu102_pyt190/download.html`

I got again this error after running `from pytorch3d.utils import ico_sphere`:

```
Traceback (most recent call last):
  File "/home/markus/PycharmProjects/pytorch3d/01_FitMesh.py", line 13, in <module>
    from pytorch3d.utils import ico_sphere
  File "/home/markus/anaconda3/envs/pytorch3d_v09/lib/python3.8/site-packages/pytorch3d/utils/__init__.py", line 3, in <module>
    from .ico_sphere import ico_sphere
  File "/home/markus/anaconda3/envs/pytorch3d_v09/lib/python3.8/site-packages/pytorch3d/utils/ico_sphere.py", line 5, in <module>
    from pytorch3d.ops.subdivide_meshes import SubdivideMeshes
  File "/home/markus/anaconda3/envs/pytorch3d_v09/lib/python3.8/site-packages/pytorch3d/ops/__init__.py", line 5, in <module>
    from .graph_conv import GraphConv
  File "/home/markus/anaconda3/envs/pytorch3d_v09/lib/python3.8/site-packages/pytorch3d/ops/graph_conv.py", line 8, in <module>
    from pytorch3d import _C
ImportError: /home/markus/anaconda3/envs/pytorch3d_v09/lib/python3.8/site-packages/pytorch3d/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor7is_cudaEv
```

maybe my nvidia driver is also intresting to know (`nvidia-smi`):

```
Mon Nov 29 10:06:46 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.82.00    Driver Version: 470.82.00    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
| N/A   39C    P8    12W /  N/A |    272MiB /  5938MiB |     20%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A       933      G   /usr/lib/xorg/Xorg                161MiB |
|    0   N/A  N/A      1278      G   /usr/bin/gnome-shell               53MiB |
|    0   N/A  N/A      2907      G   ...AAAAAAAAA= --shared-files       55MiB |
+-----------------------------------------------------------------------------+
```

**Comment by timemao** [comment]
pip uninstall torch
then follow install.Md I get below output.
>>> import torch
>>> import pytorch3d
>>> from pytorch3d import _C
>>> exit()

**Comment by Kiesi1991** [comment]
> > These problems can be caused by mismatched versions of PyTorch or cuda. In the last case you mention, you are using the PyTorch 1.9.0 build, but according to your text file above you have PyTorch 1.7.1. Can you maybe start a brand new environment e.g. as described in our INSTALL.md, and install the PyTorch3D wheel which is exactly corresponding?
> 
> Thank you for your reply! I tried a brand new environment, but it was not working. Here are my steps:
> 
> 1. `conda create -n pytorch3d_v10 python=3.8`
> 2. `conda activate pytorch3d_v10`
> 3. `conda install -c pytorch pytorch=1.9.0 torchvision cudatoolkit=10.2`
> 4. `conda install -c fvcore -c iopath -c conda-forge fvcore iopath`
> 5. `curl -LO https://github.com/NVIDIA/cub/archive/1.10.0.tar.gz`
> 6. `tar xzf 1.10.0.tar.gz`
> 7. `export CUB_HOME=$PWD/cub-1.10.0`
> 8. `conda install jupyter`
> 9. `pip install scikit-image matplotlib imageio plotly opencv-python`
> 10. `pip install black 'isort<5' flake8 flake8-bugbear flake8-comprehensions`
> 11. `pip install pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py38_cu102_pyt190/download.html`
> 
> I got again this error after running `from pytorch3d.utils import ico_sphere`:
> 
> ```
> Traceback (most recent call last):
>   File "/home/markus/PycharmProjects/pytorch3d/01_FitMesh.py", line 13, in <module>
>     from pytorch3d.utils import ico_sphere
>   File "/home/markus/anaconda3/envs/pytorch3d_v09/lib/python3.8/site-packages/pytorch3d/utils/__init__.py", line 3, in <module>
>     from .ico_sphere import ico_sphere
>   File "/home/markus/anaconda3/envs/pytorch3d_v09/lib/python3.8/site-packages/pytorch3d/utils/ico_sphere.py", line 5, in <module>
>     from pytorch3d.ops.subdivide_meshes import SubdivideMeshes
>   File "/home/markus/anaconda3/envs/pytorch3d_v09/lib/python3.8/site-packages/pytorch3d/ops/__init__.py", line 5, in <module>
>     from .graph_conv import GraphConv
>   File "/home/markus/anaconda3/envs/pytorch3d_v09/lib/python3.8/site-packages/pytorch3d/ops/graph_conv.py", line 8, in <module>
>     from pytorch3d import _C
> ImportError: /home/markus/anaconda3/envs/pytorch3d_v09/lib/python3.8/site-packages/pytorch3d/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor7is_cudaEv
> ```
> 
> maybe my nvidia driver is also intresting to know (`nvidia-smi`):
> 
> ```
> Mon Nov 29 10:06:46 2021       
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 470.82.00    Driver Version: 470.82.00    CUDA Version: 11.4     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |                               |                      |               MIG M. |
> |===============================+======================+======================|
> |   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
> | N/A   39C    P8    12W /  N/A |    272MiB /  5938MiB |     20%      Default |
> |                               |                      |                  N/A |
> +-------------------------------+----------------------+----------------------+
>                                                                                
> +-----------------------------------------------------------------------------+
> | Processes:                                                                  |
> |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
> |        ID   ID                                                   Usage      |
> |=============================================================================|
> |    0   N/A  N/A       933      G   /usr/lib/xorg/Xorg                161MiB |
> |    0   N/A  N/A      1278      G   /usr/bin/gnome-shell               53MiB |
> |    0   N/A  N/A      2907      G   ...AAAAAAAAA= --shared-files       55MiB |
> +-----------------------------------------------------------------------------+
> ```
> 
> Here are my installed packages: [package-list_pytorch3d_v10.txt](https://github.com/facebookresearch/pytorch3d/files/7617028/package-list_pytorch3d_v10.txt)

ok I tried the same procedure again and now itś working. Thank you!
