### ISSUE TITLE
R is not an valid rotation matrix problem

### ISSUE THREAD

**Issue by tjdhg456** [facebookresearch/pytorch3d#96]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## 🐛 Bugs / Unexpected behaviors

Hello, At first thank you for sharing the wonderful library; pytorch3d. It was really helpful.

When trying to optimize the camera position by following the tutorial 4, I encountered 'R is not a valid rotation matrix' problem. 

I only changed the obj file (my own file).
When the problem happened ('R is not a valid rotation matrix'), the camera position parameter changed into nan, which means couldn't be backpropagated.

I checked similar issues, but there is also no solution. So raise the issue again.
Thank you.

## Instructions To Reproduce the Issue:

Please include the following (depending on what the issue is):

1. Any changes you made (`git diff`) or code you wrote

I only used one of the ShapeNet chair object files.
another partis same.

2. The exact command(s) you ran:
3. What you observed (including the full logs):

Please also simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

**Comment by tjdhg456** [comment]
I used the attached obj file.
[05_0191.zip](https://github.com/facebookresearch/pytorch3d/files/4279911/05_0191.zip)

**Comment by nikhilaravi** [comment]
@tjdhg456 thanks for raising this issue. This is related to another issue #50 which is about the same tutorial and error. We'll look into this further and get back to you.

**Comment by tjdhg456** [comment]
Thank you very much. I'll close the issue. Thank you.
