### ISSUE TITLE
Hello Our server can't use GPU and can only use DCU, so we use amd version of pytorch1.9, but my environment needs pytorch3d. I want to ask whether there is pytorch3d that can match amd version or CPU version

### ISSUE THREAD

**Issue by miaowang525** [facebookresearch/pytorch3d#961]
Our server can't use GPU and can only use DCU, so we use amd version of pytorch1.9, but my environment needs pytorch3d. I want to ask whether there is pytorch3d that can match amd version or CPU version @bottler

**Comment by bottler** [comment]
What operating system are you using? If mac, we have builds on PyPI. Otherwise you can build PyTorch3D CPU-only from source, which should be easy.

**Comment by miaowang525** [comment]
> 你在使用什么操作系统？如果是Mac，我们就建立在PyPI上。否则，您可以构建PyTorch3D CPU-仅从源代码，这应该很容易。

Thank you very much for your reply，I use CentOS 7.6，I didn't find the CPU version pytorch3d，I wonder where I can find the CPU version of pytorch3d？，and I have another question:is there a pytorch3d that can match the AMD version of pytorch？

**Comment by miaowang525** [comment]
> What operating system are you using? If mac, we have builds on PyPI. Otherwise you can build PyTorch3D CPU-only from source, which should be easy.

@bottler Thank you very much for your reply，I use CentOS 7.6，I didn't find the CPU version pytorch3d，I wonder where I can find the CPU version of pytorch3d？，and I have another question:is there a pytorch3d that can match the AMD version of pytorch？

**Comment by bottler** [comment]
When you say "AMD version of pytorch", are you talking about AMD CPUs, or ROCm or something else? The compiled part of PyTorch3D only has two versions: C++ which should work on all CPUs, and CUDA which should work on nvidia GPUs. There's nothing for AMD GPUs. 

We don't provide linux CPU-only binaries of PyTorch3D, but it should be straightforward to build it yourself. E.g. something like this:
```
conda create -n pytorch3d python=3.8
conda activate pytorch3d
conda install -c pytorch pytorch=1.10.0 torchvision cpuonly
conda install -c fvcore -c iopath -c conda-forge fvcore iopath
pip install "git+https://github.com/facebookresearch/pytorch3d.git"
```
