### ISSUE TITLE
Pixel2Mesh Re-implementation with pytorch3D

### ISSUE THREAD

**Issue by marcomameli1992** [facebookresearch/pytorch3d#962]
Dear,
I'm a PhD student I'm trying to use PyTorch3D to reproduce the Pixel2Mesh network.
My question is:

- For the projection as described in the [original git](https://github.com/nywang16/Pixel2Mesh/blob/7c5a7a142d5f64f15250f9e98ee496980f69e005/p2m/layers.py#L204) I'm going to use the [vert_align](https://pytorch3d.readthedocs.io/en/latest/modules/ops.html?highlight=vert_align#pytorch3d.ops.vert_align) function in pytorch3D 
- For the GraphConvolution I'm using the [ops.GraphConv](https://pytorch3d.readthedocs.io/en/latest/modules/ops.html?highlight=graphconv#pytorch3d.ops.GraphConv) for the Graph Convolution on the concatenated features obtained by the vert_allign summed to the vertex features

Now the question is:
How I can implement the GraphPooling? I have done some research and I have found the pytorch-geometric implementation with some [pooling layer](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html?highlight=pooling#pooling-layers) How can I use one of these layers with the mesh data structure in the pytorch3D? Which one do you suggest to use?

**Comment by bottler** [comment]
Is GraphUnpooling in that paper the same as PyTorch3D's [SubdivideMeshes](https://github.com/facebookresearch/pytorch3d/blob/main/pytorch3d/ops/subdivide_meshes.py#L13)? Is that what you are looking for?

**Comment by marcomameli1992** [comment]
Thank you for the Help, I think that it is what i'm searching. 
For a question on the use of vert_align I have to open a new issue?

**Comment by bottler** [comment]
What exactly is the question on vert_align? I think you want to identify exactly what the model is you are reproducing, and what our operations do, and bring things together. This can be a bit fiddly, but we can't do it for you.

**Comment by marcomameli1992** [comment]
For the projection as described in the [original git](https://github.com/nywang16/Pixel2Mesh/blob/7c5a7a142d5f64f15250f9e98ee496980f69e005/p2m/layers.py#L204) I'm going to use the [vert_align](https://pytorch3d.readthedocs.io/en/latest/modules/ops.html?highlight=vert_align#pytorch3d.ops.vert_align) function in pytorch3D but I need to know the V in the  (N, V, 3) of verts parameter is the number of vertices in the mesh?

In addition, I would like to understand better what does it mean packed features? and how can I obtain the vertex features from the opened mesh, so this means at the starting point, (which is the F_(i-1) from the [pixel2mesh paper](https://openaccess.thecvf.com/content_ECCV_2018/papers/Nanyang_Wang_Pixel2Mesh_Generating_3D_ECCV_2018_paper.pdf) in Figure 3. 

The last question is: this function contains parameters that are trainable?

**Comment by bottler** [comment]
You can make any parameters trainable.

V is the maximum number of vertices among meshes in a batch of meshes. If there is one mesh (N=1) then V is its number of vertices. You can see information about batching, padded and packed in https://github.com/facebookresearch/pytorch3d/blob/main/docs/notes/batching.md .

We can't read the paper for you. I don't know what "opened mesh" means.

**Comment by marcomameli1992** [comment]
Ok thank you for the answers
