### ISSUE TITLE
How to deactivate splatting in the point rasterizer

### ISSUE THREAD

**Issue by theponpon** [facebookresearch/pytorch3d#967]
## ❓ Questions on how to use PyTorch3D

Hi

First of all, thank you for this great library!

I would like to use the pointcloud rasterizer without any splatting, meaning that only the pixel on which a point is projected should cumulate this point.

Thank you in advance,

Pierre

**Comment by theponpon** [comment]
I think I found the good value for radius with:
radius=1.0 / min(width, height) * 2.0,
But if you have any comment, you are welcome

PP

**Comment by bottler** [comment]
You want to set up the rasterizer in such a way that each point in any location will land in exactly one pixel, but that is impossible. Basically, points will be rasterized if their disc intersects the centre of the pixel, so the domain of a pixel is a circle not a square.

Which particular outputs of rasterization do you want? If you just need to find occupied pixels, it may be easy to write the calculation from scratch.

**Comment by theponpon** [comment]
Hi, thank you for your quick response. It makes total sense.
I am good with the radius = 1.0 / min(width, height) * 2.0, so need for any particular output.

I am closing this issue.

Regards,

Pierre
