### ISSUE TITLE
Use GraphConv with batches of images and meshes

### ISSUE THREAD

**Issue by marcomameli1992** [facebookresearch/pytorch3d#968]
Dear I have created a GraphConvolution and when I'm trying to use a batch of 2 meshes and 2 features maps (obtained with vert_align) as input on graphconv I obtain that the input has to be a 2 dimension tensor. How can I use it with batches of data? I have to create a for loop on the batch and get the single tensor and use it as single input for the graphconv?

I'm using pytorch3D 0.5.0 with pytorch 1.8.0 and cuda 11.1

**Comment by marcomameli1992** [comment]
Dear, sorry I was out from the project for a little bit. I would like to reopen that issue because I need to understand how I can use a batch of meshes as input for the graph network for the mesh generation

**Comment by bottler** [comment]
I think using a for loop might be the best way.

**Comment by marcomameli1992** [comment]
So this means that every time I need to train the network I have to use a for loop on the batch dimension, but in this way, it becomes unuseful application of the batch of mesh.

**Comment by bottler** [comment]
If you have a Meshes object representing multiple meshes, the edges_packed is a (total, 2) array which includes the "graph" of all meshes (and the indices correspond to the indices in verts_packed, not the indices in each mesh separately). That might let you do the whole thing in a single GraphConv with packed data. I don't understand what you want to do well enough to know if that can help.
