### ISSUE TITLE
Render 2d-images with background transparent?

### ISSUE THREAD

**Issue by Yougrianes** [facebookresearch/pytorch3d#969]
Hello!

First of all, thank you for this great library! And may I have a question? 

*****************************
I encountered a problem when using MeshRenderer. How do I render my .obj 3d model with texture using MeshRenderer(...), PyTorch 3D, while make the background transparent? 

I'm a beginner of using renderer and may confused about some basic concepts... :-< My codes are basically follow this tutorial: https://pytorch3d.org/tutorials/render_textured_meshes, and my goal is to mix the rendered image with another image with specified position, of which I mean... the R, T matrix.

At first I was thought that it maybe something wrong with matplotlib.pyplot, but I just find that the color of background pixel that the rendered image is white. Is there some parameters on the renderer or rasterizer that can change the background transparency? I cannot find these parameters in PyTorch3d-API documents. Tks!

**Comment by bottler** [comment]
Are you, like that tutorial, running code like `plt.imshow(images[0, ..., :3].cpu().numpy())` and using SoftPhongShader? If so, the output of the renderer, `image`, is actually a  image where the last channel is like an occupancy probability. If you send the fourth channel in to `imshow` as well as the RGB, then occupancy will be used as transparency, which might be exactly what you want.  To try, just change to `plt.imshow(images[0].cpu().numpy())`.

Or you may need to rescale the last channel. In more general cases, you can do anything like this with a custom shader.

**Comment by Yougrianes** [comment]
> Are you, like that tutorial, running code like `plt.imshow(images[0, ..., :3].cpu().numpy())` and using SoftPhongShader? If so, the output of the renderer, `image`, is actually a image where the last channel is like an occupancy probability. If you send the fourth channel in to `imshow` as well as the RGB, then occupancy will be used as transparency, which might be exactly what you want. To try, just change to `plt.imshow(images[0].cpu().numpy())`.
> 
> Or you may need to rescale the last channel. In more general cases, you can do anything like this with a custom shader.

That's exactly what I'm looking for. You really helped me a lot! 
Tks!! :-D
