### ISSUE TITLE
install pytorch3d wrong in wsl2(ubuntu)

### ISSUE THREAD

**Issue by mxcai08** [facebookresearch/pytorch3d#970]
I use wsl2 to install and compile pytorch3d. Before the compilation starts, it shows that the dependencies are satisfied. With the same operation and conda environment, I can install pytorch3d normally on google colab, but not on wsl, and there are too many errors displayed. I even Unable to locate the specific error，My GPU is 3070 laptop nvidia-smi information as shown below

![屏幕截图 2021-12-04 025309](https://user-images.githubusercontent.com/35069239/144664010-ff6d599e-9ef1-4205-b364-80e66d0362dc.png)
![屏幕截图 2021-12-04 023713](https://user-images.githubusercontent.com/35069239/144664009-63a90037-fbb6-4b4a-a047-1538e872fb0c.png)
![屏幕截图 2021-12-04 023426](https://user-images.githubusercontent.com/35069239/144664007-3850da06-2f56-4c3e-9398-631e80c41398.png)
![屏幕截图 2021-12-04 023212](https://user-images.githubusercontent.com/35069239/144664005-e3bc6a52-c6f2-4306-bb2b-19d9123fcc1c.png)
![屏幕截图 2021-12-04 023006](https://user-images.githubusercontent.com/35069239/144664001-41c5a7c6-6535-40e7-b283-7a6f82510425.png)

**Comment by bottler** [comment]
the only error I can see here is "operation not permitted". There might be a complication around users and permissions in WSL which you need to sort out. Did you set up the environment in exactly the same prompt just before you launched the build? If not, can you try again in that manner?

**Comment by marcomameli1992** [comment]
I have the same problem when I try to install it with pip, but if you use conda inside the WSL2 you can install it.
For the moment the configuration that works for me is based on pytorch 1.8.0 and pytorch3d 0.5.0
