### ISSUE TITLE
Very slow point rendering speed from high-resolution RGBD images

### ISSUE THREAD

**Issue by zl548** [facebookresearch/pytorch3d#972]
I am trying to use point cloud renderer to render point cloud unprojected from a RGBD image with resolution 1600x2133 (the code is below, I didn't put data here but code itself should be self-explained), it took ~5s on a V100 GPU. If I change resolution to 800x1000 (i.e, 1/4 of original resolution), it took ~0.3s, which is fine.

I am wondering if there is any way to speed up rendering for a point cloud with millions of points? I don't care about differentiability in this case.

[pts_rendering.zip](https://github.com/facebookresearch/pytorch3d/files/7658091/pts_rendering.zip)

**Comment by bottler** [comment]
There are two methods for point cloud rendering in PyTorch3D. Pulsar is faster by far if you can use it. Have you tried?

**Comment by zl548** [comment]
Thanks. I did tried Pulsar, but when I tried to render 1M points with the script below based on [https://github.com/facebookresearch/pytorch3d/blob/main/docs/examples/pulsar_basic_unified.py](url), I got the error as follows, could you help me check if I wrote something wrong:

> Traceback (most recent call last):
  File "pulsar_rendering.py", line 61, in <module>
    image = pts_renderer(
  File "/opt/conda/envs/pytorch171/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/envs/pytorch171/lib/python3.8/site-packages/pytorch3d/renderer/points/pulsar/unified.py", line 543, in forward
    self.renderer(
  File "/opt/conda/envs/pytorch171/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/envs/pytorch171/lib/python3.8/site-packages/pytorch3d/renderer/points/pulsar/renderer.py", line 672, in forward
    ret_res = _Render.apply(
  File "/opt/conda/envs/pytorch171/lib/python3.8/site-packages/pytorch3d/renderer/points/pulsar/renderer.py", line 127, in forward
    image, info = ctx.native_renderer.forward(
RuntimeError: invalid argument 9: num_balls must be >0 and <= max num balls! (3412800 vs. 1000000) at /tmp/pip-req-build-k0v8tatb/pytorch3d/csrc/pulsar/cuda/../include/./renderer.forward.device.h:4


[pulsar_rendering.zip](https://github.com/facebookresearch/pytorch3d/files/7662494/pulsar_rendering.zip)

**Comment by bottler** [comment]
I don't think this is a compiled limit. I think you can set max_num_spheres to something larger when you make the PulsarPointsRenderer, e.g. to `int(1e7)`.

**Comment by zl548** [comment]
Thanks! After I changed max_num_spheres, it will not throw any error, but the rendered image is still completely blank. Script pts_rendering.py below is based on standard point cloud renderer and this works fine (although it's slow). pulsar_rendering.py is based on Pulsar with almost the same settings, but produces blank rendering. Any idea? 

[pts_rendering.py.zip](https://github.com/facebookresearch/pytorch3d/files/7663241/pts_rendering.py.zip)
.

**Comment by bottler** [comment]
Can you try using the same pulsar calculation but without moving anything to CUDA? There have been problems where CUB doesn't work properly and pulsar produces blank outputs on GPU. Trying on CPU should reveal if the problem is like that or something more to do with the logic.

**Comment by gkioxari** [comment]
@zl548 
Have you played with `K` (`K=num_points_per_pixel`). K plays a role in speed and memory. PyTorch3D's implementation is modular and spits out intermediate outputs of size (`NxHxWxK`) to allow for flexibility in downstream usage. If you don't care about any of that then pulsar is a great alternative. I tag @classner to help out with the pulsar issue.

**Comment by classner** [comment]
Hi @zl548 !

Happy to help you out with the Pulsar rendering problem! I see that in your code you require loading of a .tar file with the point data. Can you share that, too, or instead generate a random point cloud in roughly the same space where the original points are to create a self-contained example?
