### ISSUE TITLE
Is the MeshRenderer has the maximum depth limit (threshold)?

### ISSUE THREAD

**Issue by Yougrianes** [facebookresearch/pytorch3d#973]
I tried to define the Rotation and Translation matrices separately, and found some magic happening as follows:
```
R, T = look_at_view_transform(10.0, 0, 0)
# add an offset of translation matrix, and customize the depth
depth = 50
T = T + torch.tensor([[ 2, -10, depth ]]) 
cameras = FoVPerspectiveCameras(device=device, R=R, T=T)
```
and the rendered object will become pure white or partially white( vertically ) when the depth being set too big..... or losing some triangle mesh maybe?

I think it should have some maximum depth limit (or threshold I mean) because it will become less than one pixel when the depth → +∞

Another thing makes me confused is whether the pixel should be counted in digital or based on physics like (mm , cm , m, etc)

this issue may related to #950 (something overflow... ?) , but I cannot say it for sure.

**Comment by bottler** [comment]
`FoVPerspectiveCameras` has a far clipping plane defined by `zfar` which you can change but defaults to 100. Depending on the renderer setup, things could be ignored beyond that.

**Comment by Yougrianes** [comment]
finally use ```bin_size = 0``` solve my problem.

**Comment by Yougrianes** [comment]
> `FoVPerspectiveCameras` has a far clipping plane defined by `zfar` which you can change but defaults to 100. Depending on the renderer setup, things could be ignored beyond that.

Tks! so what you mean is that the renderer doesn't manipulate objects that beyond `zfar` depth?

**Comment by bottler** [comment]
> Nice! so what you mean is that the renderer doesn't manipulate objects that beyond `zfar` depth?

It depends on various settings. E.g. the blending function and whether clipping is turned on.

**Comment by Yougrianes** [comment]
> > Nice! so what you mean is that the renderer doesn't manipulate objects that beyond `zfar` depth?
> 
> It depends on various settings. E.g. the blending function and whether clipping is turned on.

I have a lot to learn, perhaps... but still tks! :->
