### ISSUE TITLE
Artifacts in texture map related to perspective_correct

### ISSUE THREAD

**Issue by simon-cross** [facebookresearch/pytorch3d#974]
I am working on the tutorial "Fit a Mesh with Texture via Rendering" and instead of computing a color per mesh vertex, I compute a texture map. When I set perspective_correct=False I get strange artifacts.

perspective_correct=False
![Screenshot from 2021-12-05 11-42-49](https://user-images.githubusercontent.com/92995595/144745317-eaec5e00-0a9f-4ee3-a1f5-dbf1cf53f9ca.png)

perspective_correct=True
![Screenshot from 2021-12-05 11-42-54](https://user-images.githubusercontent.com/92995595/144745321-82b2d07f-bc60-43b1-8125-6b27f48d93da.png)

My version of PyTorch3D is 0.6.0.

Is it a bug or an expected behaviour?

**Comment by bottler** [comment]
We'd need a lot more information about what you are doing to be able to help. But yes, a numerical bug with perspective_correct has been fixed since the last release. You might want to check if you still get unexpected results with a build from `main` or the nightly build.
(I'm not sure how this relates to issue #971 by the way.)

**Comment by simon-cross** [comment]
I have installed PyTorch3D with the following command
pip3 install "git+https://github.com/facebookresearch/pytorch3d.git"
but, I still get nan when running the tutorial fit_textured_mesh.py.

Am I not using the code of the main branch?

**Comment by simon-cross** [comment]
.

**Comment by nikhilaravi** [comment]
@simon-cross do you still need help with this issue?

**Comment by crocis** [comment]
I opened another issue about perspective_correct: [#991](https://github.com/facebookresearch/pytorch3d/issues/991). This new issue was closed a few days ago. Have you fixed the bug related to perspective_correct?

**Comment by simon-cross** [comment]
I opened another issue about perspective_correct: #991. This new issue was closed a few days ago. Have you fixed the bug related to perspective_correct?

**Comment by bottler** [comment]
There is still a known problem with perspective_correct, but I am not sure if it is related to these artifacts. Investigation is needed.
