### ISSUE TITLE
Windows local clone installation issue..

### ISSUE THREAD

**Issue by RAJA-PARIKSHAT** [facebookresearch/pytorch3d#978]
So I have followed the tutorial in a following way:

```
conda create -n pytorch3d python=3.8
conda activate pytorch3d
conda install -c pytorch pytorch=1.7.1 torchvision cudatoolkit=10.2
conda install -c fvcore -c iopath -c conda-forge fvcore iopath
```
then 
I download the cub library from the github provided and set the environment variable path

then I did all of these
```
pip install scikit-image matplotlib imageio plotly opencv-python

# Tests/Linting
pip install black 'isort<5' flake8 flake8-bugbear flake8-comprehensions
```
after that the last step I followed to install from local clone, as I first cloned the repository and then 
python setup.py install

but whatever I do I am struck at the error
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

Please help me out
@bottler

**Comment by bottler** [comment]
You should have a log file from the failed build. Please look for the word `error` in it. You might want to attach it here.
