### ISSUE TITLE
Transform: 3D mesh rescale

### ISSUE THREAD

**Issue by Yougrianes** [facebookresearch/pytorch3d#979]
I want to rescale my mesh model using this api-doc :https://pytorch3d.readthedocs.io/en/latest/modules/transforms.html?highlight=scale# ...... is there any code block or toy-example provided?
how to implement this transform into mesh?  I just want to manipulate the size of the mesh model, and do not use the back-propagation or something like training stuff.

**Comment by bottler** [comment]
It sounds like you have a batch size of 1. If you want to scale the mesh by a constant factor, you don't need `Scale`. You can just use `scaled_mesh=mymesh.scale_verts(scale_factor)` and there is an in-place equivalent `mymesh.scale_verts_(scale_factor)`.

If you have a separate `float` scale factor in each direction you do need `Scale`. You can do something like this:
```
from pytorch3d.transforms import Scale
scale=Scale(scalex, scaley, scalez, device=mymesh.device)
new_verts = scale.transform_points(mymesh.verts_padded())
new_mesh=mymesh.update_padded(new_verts) 
```

**Comment by Yougrianes** [comment]
> It sounds like you have a batch size of 1. If you want to scale the mesh by a constant factor, you don't need `Scale`. You can just use `scaled_mesh=mymesh.scale_verts(scale_factor)` and there is an in-place equivalent `mymesh.scale_verts_(scale_factor)`.
> 
> If you have a separate `float` scale factor in each direction you do need `Scale`. You can do something like this:
> 
> ```
> from pytorch3d.transforms import Scale
> scale=Scale(scalex, scaley, scalez, device=mymesh.device)
> new_verts = scale.transform_points(mymesh.verts_padded())
> new_mesh=mymesh.update_padded(new_verts) 
> ```

tks! really useful :-D

**Comment by Yougrianes** [comment]
And,
