### ISSUE TITLE
render the object with grid to check the vanish point?

### ISSUE THREAD

**Issue by Yougrianes** [facebookresearch/pytorch3d#981]
I think it's a wise choice when I can see the rendered image with grid, so that I can check out whether the rotation and translation is manipulated correctly. For example I can use this method to find out the vanishing point. 
Sounds like an inner parameter in renderer, maybe?

**Comment by bottler** [comment]
The existing plotly visualisation functionality in PyTorch3D should hopefully be enough to check what you want to check. If not, you could add a grid to that? I think adding a grid to one of the differential renderers would be difficult and the wrong way to go.

**Comment by Yougrianes** [comment]
> 

yep I agree with your opinion. and I just try to use an calibration board image instead. 
Thanks! :->
