### ISSUE TITLE
How to render a 3d-model without texture .png image

### ISSUE THREAD

**Issue by Yougrianes** [facebookresearch/pytorch3d#982]
I have some 3d-models in online internet galleries and meet some problems. Mainly because the 3d-models only have .obj and .mtl, without the texture image .png. It seems okey in my software **blender**, but the pytorch3d code occured error: ```ValueError: Meshes does not have textures ```. Have anybody know how to solve this problem? Is the texture image necessary? For example, I can make the surface just in the material file .mtl (such as pure color) so that the texture image is no needed ever? :-<

**Comment by bottler** [comment]
That error is coming from the renderer and not from the dataloading. You have successfully loaded the data and have a `Meshes` without a `textures`. You now need to decide how you want to render it. An easy way to render it with a constant color would be to create a TexturesVertex for it and assign it to `mesh.textures`.

**Comment by zeakey** [comment]
An example of assign constant texture is as below:
```
from pytorch3d.renderer import TexturesVertex


# your mesh
mesh = pytorch3d.structures.Meshes(verts3d, faces)
# assign constant color texture
color = torch.ones(1, verts3d.size(1), 3, device=device)
mesh.textures = TexturesVertex(verts_features=color)
```

**Comment by Yougrianes** [comment]
> That error is coming from the renderer and not from the dataloading. You have successfully loaded the data and have a `Meshes` without a `textures`. You now need to decide how you want to render it. An easy way to render it with a constant color would be to create a TexturesVertex for it and assign it to `mesh.textures`.

Yes that's true. Furthermore, how to render the mesh with assigning a .png file separately? 
I mean first load_mesh without texture, and assign the texture .png file later (to avoid some absolute directories in .mtl files).

**Comment by Yougrianes** [comment]
> An example of assign constant texture is as below:
> 
> ```
> from pytorch3d.renderer import TexturesVertex
> # your mesh
> mesh = pytorch3d.structures.Meshes(verts3d, faces)
> # assign constant color texture
> color = torch.ones(1, verts3d.size(1), 3, device=device)
> mesh.textures = TexturesVertex(verts_features=color)
> ```

Tks!
