### ISSUE TITLE
slow speed when using estimate estimate_normals

### ISSUE THREAD

**Issue by syguan96** [facebookresearch/pytorch3d#988]
Given the shape of `particles` as `[1, 104314, 3]`, I estimate their normals as follows:
```
Pointclouds(particles).estimate_normals(neighborhood_size=10)
```
However, I found the calculating process is extremely slow (more than 0.5 min). Is it normal?

**Comment by patricklabatut** [comment]
Thanks for reporting this potential problem!

> the calculating process is extremely slow (more than 0.5 min)

1. Would you have comparison points with other libraries for a similar operation?
2. What speed would you consider "normal"?
3. Do you think the observed speed is specific to the data you have and if so, could you please share that data to allow us to fully reproduce?

**Comment by bottler** [comment]
(Just to explain: the commit c2862ff which is referenced should have made a big speedup.)
