### ISSUE TITLE
Citing anterior differentiable rendering working in the documentation

### ISSUE THREAD

**Issue by martinResearch** [facebookresearch/pytorch3d#99]
## 🚀 Feature
The documentation page on the differentiable rendering [here](https://pytorch3d.org/docs/renderer) provides only 2 citations (Neural 3D Mesh Renderer ans Soft-Rasterizer) while there is anterior work to these differentiable renderers, some of which is cited by neither of these two papers. In the chronological order: 

- *Model-based 3D Hand Pose Estimation from Monocular Video.* M. de la Gorce, N. Paragios and David Fleet. PAMI 2011 [code](https://github.com/martinResearch/DEODR)
- *OpenDR: An Approximate Differentiable* Renderer Loper, Matthew M. and Black, Michael J. ECCV 2014. [code](https://github.com/mattloper/opendr/wiki)
- *Differentiable Monte Carlo Ray Tracing through Edge Sampling*. zu-Mao Li, Miika Aittala, Frédo Durand, Jaakko Lehtinen. SIGGRAPH Asia 2018

Also some newer paper prior to you library publication could be worth citing

- *Differentiable Surface Splatting for Point-based Geometry Processing*. Felice Yifan, Serena Wang, Shihao Wu, Cengiz Oztireli and Olga Sorkine-Hornung. SIGGRAPH Asia 2019. [code](https://github.com/yifita/DSS)
- *Reparameterizing discontinuous integrands for differentiable rendering.* Guillaume Loubet, Nicolas Holzschuch and Wenzel Jakob. SIGGRAPH Asia 2019

I understand you library documentation is not a scientific publication and thus is not required to provide an exhaustive list of citations. However, considering the large impact your library has, it would be great for the authors of these papers if you could had these citations to your documentation.

**Comment by gkioxari** [comment]
Hi @martinResearch! Definitely. Thank you for the suggestions! We will include all these citations in the documentation. The reason we primarily focus on NMR and SoftRas in the documentation of our implementation is because they were the source of inspiration for our differentiable renderer. However, I completely agree that it is always good to give proper credit to more efforts out there.

**Comment by gkioxari** [comment]
Added DR citations by https://github.com/facebookresearch/pytorch3d/commit/112d32eaf0f25735ac1c2d76d1871a8dd8f18234. Closing this issue!
